---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by richyczhou.
--- DateTime: 2025/9/8 20:38
---
local LuaClass = require("Core/LuaClass")
local UIViewModel = require("UI/UIViewModel")
local FLinearColor = _G.UE.FLinearColor;
local FLOG_INFO = _G.FLOG_INFO

---@class EquipStainItemVM : UIViewModel
local EquipStainItemVM = LuaClass(UIViewModel)

function EquipStainItemVM:Ctor()
    self.SectionID = nil
    self.Text = nil

    self.ColorID = nil
    self.JPDisplayName = nil
    self.DisplayName = nil
    self.Color = nil
    self.HexColor = nil
end

---UpdateVM
---@param List table
function EquipStainItemVM:UpdateVM(List)
    -- Text = "全部", Index = 0, ColorID = 0
    self.SectionText = List.Text
    self.SectionID = List.SectionID
    self.ColorID = List.ColorID
    self.HexColor = List.HexColor
    FLOG_INFO("[EquipStainItemVM:UpdateVM] Text:%s, SectionID:%d, ColorID:%d, HexColor:%s ", List.Text, List.SectionID, List.ColorID, List.HexColor)
end

function EquipStainItemVM:IsEqualVM(Value)
    return nil ~= Value and Value.SectionID == self.SectionID
end

function EquipStainItemVM:GetName()
    return "EquipStainItemVM"
end

return EquipStainItemVM