---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by richyczhou.
--- DateTime: 2025/9/8 20:38
---
local LuaClass = require("Core/LuaClass")
local UIViewModel = require("UI/UIViewModel")
local FLinearColor = _G.UE.FLinearColor;
local FLOG_INFO = _G.FLOG_INFO

---@class EquipColorItemVM : UIViewModel
local EquipColorItemVM = LuaClass(UIViewModel)

function EquipColorItemVM:Ctor()
    self.bItemSelect = false

    self.ColorID = nil
    self.JPDisplayName = nil
    self.DisplayName = nil
    self.Color = nil
    self.HexColor = nil
end

---UpdateVM
---@param List table
function EquipColorItemVM:UpdateVM(List)
    self.ColorID = List.ColorID
    self.JPDisplayName = List.JPDisplayName
    self.DisplayName = List.DisplayName
    self.Color = List.Color
    self.HexColor = List.HexColor
    --FLOG_INFO("[EquipColorItemVM:UpdateVM] ColorID:%d, Color:%d, HexColor:%s", List.ColorID, List.Color, List.HexColor)
end

function EquipColorItemVM:IsEqualVM(Value)
    return nil ~= Value and Value.ColorID == self.ColorID
end

--function EquipColorItemVM:UpdateData(ColorData)
--    local ColorValue = ColorData.Color
--    if ColorValue == nil then
--        _G.FLOG_ERROR("[EquipColorItemVM:UpdateData] ColorValue error, please check CColorList")
--        return
--    end
--
--    self.ItemColorAndOpacity = FLinearColor(ColorValue.R/255, ColorValue.G/255, ColorValue.B/255, ColorValue.A/255)
--    self.DataValue = ColorData.DataValue
--    self.ColorType = ColorData.ColorType
--    self.SelectText = tostring(ColorData.DataValue)
--end

function EquipColorItemVM:OnSelectedChange(IsSelected)
    self.bItemSelect = IsSelected
end

function EquipColorItemVM:GetName()
    return "EquipColorItemVM"
end

return EquipColorItemVM