---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2024/11/4 18:30
---

local LuaClass = require("Core/LuaClass")
local MapMarker = require("Game/Map/Marker/MapMarker")
local MapDefine = require("Game/Map/MapDefine")
local MapUtil = require("Game/Map/MapUtil")
local BuddyColorCfg = require("TableCfg/BuddyColorCfg")
local ActorUtil = require("Utils/ActorUtil")
local ChocoboDefine = require("Game/Chocobo/ChocoboDefine")

local MapMarkerType = MapDefine.MapMarkerType
local MapMarkerBPType = MapDefine.MapMarkerBPType
local IconPath = "Texture2D'/Game/Assets/Icon/MapIconSnap/UI_Icon_060444.UI_Icon_060444'"

---@class MapMarkerChocoboRacer
local MapMarkerChocoboRacer = LuaClass(MapMarker)

---Ctor
function MapMarkerChocoboRacer:Ctor()
end

function MapMarkerChocoboRacer:GetType()
    return MapMarkerType.ChocoboRacer
end

function MapMarkerChocoboRacer:GetBPType()
    return MapMarkerBPType.ChocoboRacer
end

function MapMarkerChocoboRacer:InitMarker(Params)
    self.RoleID = Params.RoleID
    self.EntityID = Params.EntityID

    local IsNpcChallenge = _G.ChocoboRaceMgr:IsNpcChallengeByEntityID(self.EntityID)
    if IsNpcChallenge then
        self.IconPath = MapDefine.MapIconConfigs.MonsterBoss  -- 暂时用boss资源，后续替换
    else
        self.IconPath = IconPath
    end
end

function MapMarkerChocoboRacer:GetAreaMapPos()
    if self.EntityID then
        return MapUtil.GetActorUIPosByEntityID(self.UIMapID, self.EntityID)
    end
    return 0, 0
end

function MapMarkerChocoboRacer:GetWorldPos()
    if self.EntityID then
        local Actor = ActorUtil.GetActorByEntityID(self.EntityID)
        if Actor then
            local Location = Actor:FGetActorLocation()
            return Location.X, Location.Y, Location.Z, Location
        end
    end

    return 0, 0, 0, nil
end

--function MapMarkerChocoboRacer:OnTriggerMapEvent(EventParams)
--    local Name = self:GetTipsName()
--    if nil ~= Name and string.len(Name) > 0 then
--        local Params = { Name = Name, ScreenPosition = EventParams.ScreenPosition }
--        UIViewMgr:ShowView(UIViewID.WorldMapMarkerTipsTarget, Params)
--    end
--end

function MapMarkerChocoboRacer:GetTipsName()
    local ChocoboData = _G.ChocoboRaceMgr:GetRacerData(self.EntityID)
    if nil == ChocoboData then
        return ""
    end

    return ChocoboData.Name
end

function MapMarkerChocoboRacer:GetChocoboColor()
    local ChocoboData = _G.ChocoboRaceMgr:GetRacerData(self.EntityID)
    if nil ~= ChocoboData then
        local ColorCfg = BuddyColorCfg:FindCfgByKey(ChocoboData.Color)
        if nil ~= ColorCfg then
            return _G.UE.FLinearColor(ColorCfg.R / 255, ColorCfg.G / 255, ColorCfg.B / 255, 1)
        end
    end
    return ChocoboDefine.DEFAULT_HEAD_COLOR
end


return MapMarkerChocoboRacer