---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by mingyyzhang.
--- DateTime: 2025/7/14 9:50
---

local LuaClass = require("Core/LuaClass")
local UIViewModel = require("UI/UIViewModel")
local UIBindableList = require("UI/UIBindableList")
local MajorUtil = require("Utils/MajorUtil")
local RoleInfoMgr = require("Game/Role/RoleInfoMgr")
local HouseLocalDef = require("Game/House/HouseLocalDef")
local ProtoCS = require("Protocol/ProtoCS")
---@class HouseInfoInviteFriendsWinVM : UIViewModel
local HouseInfoRoomItemVM = LuaClass(UIViewModel)

function HouseInfoRoomItemVM:Ctor()
    self.PanelAvailabilityVisibility = false
    self.PanelRoomHideVisibility = false
    self.ImgPhotoVisibility = true
    self.PanelLikeTagVisibility = true
    self.ImgPaperVisibility = true
    self.CommHeadVisibility = true
    self.Icon = ""
    self.TextLike = 0
    self.TextHide = HouseLocalDef.HouseArmyRoom.RoomHide
    self.TextName = ""
    self.RoomNumber = ""
    self.TextAvailability = HouseLocalDef.HouseArmyRoom.RoomEmpty
    self.HouseID = 0
    self.OwnerID = 0
    self.Url = ""
end


function HouseInfoRoomItemVM:UpdateVM(Params)
    if Params.HouseID then
        self.ImgPhotoVisibility = true
        self.PanelRoomHideVisibility = false
        self.PanelAvailabilityVisibility = false
        self.ImgPaperVisibility = true
        self.CommHeadVisibility = true
        self.PanelLikeTagVisibility = true
        self.TextLike = Params.BeLikeNum
        self.RoomNumber = string.format("%03d", Params.Index)
        self.TextName = Params.Name
        self.HouseID = Params.HouseID
        self.OwnerID = Params.RoleID
        self.VisitSetting = Params.VisitSetting
        local MajorID = MajorUtil.GetMajorRoleID()
        if self.OwnerID == MajorID then
            self.Icon = string.format(HouseLocalDef.HouseArmyRoom.IconPath, 5, 5)
            self.Url = Params.PicUrl
        else
            local CanVisit = _G.HouseLandMgr.GetVisitPrivile(self.OwnerID, self.VisitSetting, {}, ProtoCS.HouseVisitSettingType.HouseVisitSettingType_Browser,
                        HouseLocalDef.BuyHouseBelongType.Army)
            if CanVisit == true then
                self.Icon = string.format(HouseLocalDef.HouseArmyRoom.IconPath, 4, 4)
                self.Url = Params.PicUrl
            else
                self.Icon = string.format(HouseLocalDef.HouseArmyRoom.IconPath, 2, 2)
                self.ImgPhotoVisibility = false
                self.PanelRoomHideVisibility = true
                self.PanelLikeTagVisibility = false
                self.Url = ""
            end
        end
    else
        self.RoomNumber = string.format("%03d", Params.Index)
        self.ImgPhotoVisibility = false
        self.PanelAvailabilityVisibility = true
        self.PanelLikeTagVisibility = false
        self.ImgPaperVisibility = false
        self.CommHeadVisibility = false
        self.Icon = string.format(HouseLocalDef.HouseArmyRoom.IconPath, 1, 1)
    end
end









return HouseInfoRoomItemVM