---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by mingyyzhang.
--- DateTime: 2025/6/17 18:26
---

local LuaClass = require("Core/LuaClass")
local UIViewModel = require("UI/UIViewModel")

local HouseInfoRoommateItemVM = LuaClass(UIViewModel)
local LSTR = _G.LSTR

function HouseInfoRoommateItemVM:Ctor()
    self.RoleID = 0
end 

function HouseInfoRoommateItemVM:UpdateVM(Params)
    self.RoleID = Params.RoleID
    
end

function HouseInfoRoommateItemVM:IsEqualVM(Value)
    return false
end
return HouseInfoRoommateItemVM