---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by richyczhou.
--- DateTime: 2024/6/27 19:05
---

local CommonDefine = require("Define/CommonDefine")

---Maple区服节点信息
---@field WorldID number
---@field Name string
---@field Host string
---@field Index number
---@field State number
---@field Tag number
---@field CustomValue1 number
---@field CustomValue2 number
---@field RoleItem RoleItem 服务器角色信息项
---@class ServerListItem

---Maple区服节点树项
---@field GroupID number
---@field ServerList ServerListItem[]
---@class ServerTreeItem

---Maple区服节点树
---@field ServerTreeList ServerTreeItem[]
---@class ServerTree

---Maple区服组信息
---@field GroupID number
---@field Name string
---@field Key string
---@class ServerGroupItem

---@field ServerGroupList ServerGroupItem[]
---@class ServerGroup

---服务器角色信息项
---@field WorldID number
---@field RoleID string
---@field Name string
---@field Level number
---@field Prof number 职业
---@field LoginTime string
---@field HeadPortraitID number
---@field LoginChannel number
---@field IsOnline boolean
---@class RoleItem

---服务器角色信息
---@field Roles RoleItem[]
---@class ServerRoles

---好友服务器信息项
---@field Name string
---@field HeadUrl string
---@field Role RoleItem
---@class FriendRoleItem

---好友服务器角色信息
---@field Accounts FriendRoleItem[]
---@class ServerFriends

---Maple区服节点信息 + 服务器角色信息项
---@field ServerItem ServerListItem
---@field RoleItem RoleItem
---@class ServerDataItem


---账号注销协议信息项
---@field RoleID string
---@field RoleName string
---@field GroupChat boolean
---@field Friend boolean
---@field NewChannel boolean
---@field Team boolean
---@class AccountInfoItem

local LoginStrID =
{
    ConfirmBtnStr = 10002, --确  认
    CancelBtnStr = 10003, --取  消
    TipsTitle = 10004, --提  示
    QuitBtnStr = 10010, --退  出
    ServerListFailed = 470001, --服务器列表获取失败\n错误码:%d
    Retry = 470002, --重  试
    ResetAndRestart = 470003, --已重置客户端，请重启游戏
    RepairAndRestart = 470004, --已修复客户端，请重启游戏
    MSDKEvnChanged = 470005, --MSDK环境已切换，重启生效
    SvrStateFull = 470006, --爆满
    SvrStateBusy = 470007, --繁忙
    SvrStateFluency = 470008, --流畅
    SvrStateMaintenance = 470009, --维护
    SvrRecommend = 470010, --推荐服务器
    SvrMine = 470011, --我的服务器
    SvrFriend = 470012, --好友服务器
    SvrAllList = 470013, --服务器列表
    DownloadErr = 470014, --资源下载失败，请稍后再试。
    DownloadErrWithCode = 470015, --资源下载失败，请稍后再试。\n错误码：%d
    PufferStartErr = 470016, --启动错误
    PufferInitErr = 470017, --初始化失败
    QuitPlayer = 470018, --退出播放
    ConfirmQuitPlayer = 470019, --确认要退出动画播放吗？
    AppVer = 470020, --版本号：
    ResourceVer = 470021, --资源版本号：
    TaiHuVer = 470022, --当前太湖账号：
    Feedback = 470023, --联系客服
    LoginCancel = 470024, --您取消了授权
    LoginFailed = 470025, --登录失败，错误码:%d，请重试或联系客服。
    InputOpenID = 470026, --请输入OpenID
    SvrMaintenance = 470027, --服务器正在维护中...
    RepairContent = 470028, --使用游戏修复功能快速解决游戏无法进入、频繁闪退等问题。若无法解决，则可尝试游戏重置。
    ResetBtnStr = 470029, --游戏重置
    RepairBtnStr = 470030, --游戏修复
    Guest = 470031, --游客
    Facebook = 470032, --Facebook
    Email = 470033, --Email
    Apple = 470034, --Apple
    Google = 470035, --Google
    More = 470036, --更多
    GuestTips = 470037, --游客账号在更换设备等情况存在丢失风险，请尽快关联其它账号
    License = 470038, --游戏许可及服务协议
    FFPrivacy = 470039, --最终幻想14：水晶世界隐私保护指引
    ChildrenPrivacy = 470040, --儿童隐私保护指引
    InfoShareList = 470041, --第三方信息共享清单
    ReadAndAgree = 470042, --我已经详细阅读并同意
    And = 470043, --和
    CheckAgreement = 470044, --请先勾选同意下方的服务协议，即可进入游戏
    SelectServer = 470045, --选择服务器
    AllServer = 470046, --全部服务器
    Online = 470047, --在线
    UserAgreement = 470048, --User Agreement
    AgreeTo = 470049, --I agree to the
    PrivacyPolicy = 470050, --Privacy Policy
    Acknowledge = 470051, --I acknowledge the
    DateUnfilled = 470052, --Date of birth unfilled
    ConfirmAgreement = 470053, --Please confirm user agreement
    GetCode = 470054, --Get Code
    InvalidEmail = 470055, --需要输入有效邮箱
    WaitCD = 470056, --请等待发送冷却
    CodeSent = 470057, --验证码已发送
    CodeSentEmail = 470058, --验证码已发送，请查看邮箱
    InputCode = 470059, --请输入验证码
    LangSwitchContent = 470060, --切换语言后，需要重启游戏，是否确认切换？
    Twitter = 470061, --Twitter
    Line = 470062, --Line
    ConfirmRefusePermission = 470063, --确定要拒绝对应权限开启吗？拒绝后将退出游戏！
    Back = 470064, --返回
    ExpectedUpdates = 470065, --<span color="#D5D5D5FF">预计更新</><span color="#BEAC8C">%d分钟</>
    Downloading = 470066, --下载中
    PreDownloadInit = 470067, --初始化
    PreDownloadResume = 470068, --点击按钮继续下载
    PreDownloadFinish = 470069, --下载完成
    PreDownloadFailed = 470070, --下载失败
    PreDownloadNewVer = 470071, --新版本已开启
    PreDownloadNewVer2 = 470072, --预下载已完成，距新版本还有<span color=\"#ffeebb\">%s</>
    SvrQueueTitle = 470073, --服务器排队
    SvrFull = 470074, --服务器已满
    DayHour = 470075, --%d天%d小时
    HourMin = 470076, --%d小时%d分钟
    MinSecond = 470077, --%d分钟%d秒
    ClickToView = 470078, --点击查看
    RefusePrivacyTips = 470079, --确定要拒绝用户协议和隐私保护指引吗？拒绝后将无法进入游戏！
    CurrentSvr = 470080, --当前服务器：%s
    MainInfo = 470081, --本公司积极履行《网络游戏行业防沉迷自律公约》
    MainInfo2 = 470082, --根据国家新闻出版署《关于防止未成年人沉迷网络游戏的通知》、《国家新闻出版署关于进一步严格管理切实防止未成年人沉迷网络游戏的通知》，所有网络游戏用户均需使用有效身份信息完成账号实名注册后方可进入游戏，认证为未成年的玩家将受到防沉迷功能限制。
    MainHealthy = 470083, --《健康游戏忠告》抵制不良游戏，拒绝盗版游戏。注意自我保护，谨防受骗上当。适度游戏益脑，沉迷游戏伤身。合理安排时间，享受健康生活。
    MainInfo3 = 470084, --京新出文〔2023〕214号  审批文号：国新出审〔2024〕1600号  出版物号： ISBN 978-7-498-13823-1
    MainInfo4 = 470085, --著作权人：深圳市腾讯网络信息技术有限公司 出版单位：北京中电电子出版社 运营单位：北京博润智佳科技有限公司
    ResearchLogin = 470086, --研发登录
    WXLogin = 470087, --微信登录
    QQLogin = 470088, --QQ登录
    ScanLogin = 470089, --扫码登录
    Prepare = 470090, --准备更新资源... (此过程不消耗流量)
    Friend = 470091, --同玩\n好友
    InputHint = 470092, --点击输入ID
    Logout = 470093, --注销
    Copyright1 = 470094, --© 【2024】Tencent. FINAL FANTASY XIV© SQUARE ENIX
    Copyright2 = 470095, --LOGO ILLUSTRATION: © YOSHITAKA AMANO
    LoginWith = 470096, --Login with
    OverseaCopyright = 470097, --© 【2024】Proxima Beta Pte. Limited.FINAL FANTASY XIV© SQUARE ENIX          LOGO ILLUSTRATION: © YOSHITAKA AMANO
    EnterGame = 470098, --进入游戏
    EnterGameEn = 470099, --进入游戏
    AgeTips = 470100, --适龄提示
    AgeTipsContent = 470101, --
    AgeTips1 = 470102, --温馨提示:我们不保存您的出生日期
    IAgreeFollowing = 470103, --I confirm the following:
    Agreements = 470104, --协议
    EmailLogin = 470105, --邮箱登录
    InputEmail = 470106, --请输入邮箱地址
    ChooseLanguage = 470107, --选择语言
    SwitchLoginAccount = 470108, --切换登录账号
    NoShowAgain = 470109, -- 不再显示
    PreDownloadTitle = 470110, -- 资源包预下载
    PreDownloadNo = 470111, -- 暂不下载
    PreDownloadYes = 470112, -- 提前下载
    SvrQueueQuit = 470113, -- 退出排队
    SvrQueueRecommend = 470114, -- 选择推荐服
    SvrQueuing = 470115, -- 排队中:
    SvrQueueDuration = 470116, -- 排队时长:
    SvrQueueWait = 470117, -- (预计等待
    SvrQueueTips = 470118, -- 当前服务器注册人数已满，请选择其他服
    UpdateTipsTitle = 470119, -- 更新提示
    Agree = 470120, -- 同  意
    NoAgree = 470121, -- 不同意
    UpdateContent = 470122, -- 尊敬的腾讯游戏用户:.........
    PreDownloadName = 470123, -- 预下载
    Pause = 470124, -- 暂停中
    Finished = 470125, -- 已完成
    GoTo = 470126, -- 前往
    NoNotice = 470127, -- 暂无公告
    Offline = 470148, -- 离线
    LoginRetryTips = 470165, -- 操作太频繁啦，请%ds后重试。
    EmptyMyServer = 470166, -- 当前暂无角色
    EmptyFriends = 470167, -- 暂无同玩好友
}

-- MSdk角色简要信息
--message RoleSimpleOfMSdk {
--    uint64 RoleID = 1;
--    int32 WorldID = 2; // 大区ID
--    string OpenID = 3;
--    string Name = 4;
--    int32 Prof = 5; // 职业
--    int32 Level = 6;
--    int64 LoginTime = 7;
--    int32 HeadPortraitID = 8;  // 头像ID
--}

--local ServerDomainTest = "http://119.147.3.250:30002" -- 性能测试
--local ServerDomainTest = "http://119.147.3.250:31030" -- 每日构建01
--local ServerDomainTest = "http://119.147.3.250:31019" -- 功能测试01
local ServerDomainTest = "http://119.147.3.250"
local ServerDomainAuditing = "https://profile-pre.fmgame.qq.com:31445"
local ServerDomain = "https://profile.fmgame.qq.com:30443"

local TestEnvPortMap = {
    [10] = ":31030", -- 每日构建01
    [13] = ":31019", -- 功能测试01
    [14] = ":30002", -- 性能测试
}

--- 登录渠道id
local ChannelIDs = {
    WeChat = 1,
    QQ = 2,
    Guest = 3,
    Facebook = 4,
    --GameCenter = 5,
    GooglePlay = 6,
    --IEGPass = 7,
    Twitter = 8,
    --Garena = 9,
    SelfAccount = 10,
    --EGame = 12,
    Line = 14,
    Apple = 15,
    --Kwai = 17,
    --VK = 19,
    --Steam = 21,
}

--- 操作系统标示
local Os = {
    Android = 1,
    iOS = 2,
    --Web = 3,
    --Linux = 4,
    Windows = 5,
}

local NoticeGroup = {
    PreLogin = "1",

}

--- MSDK自建账号支持的语言列表
--- https://docs.msdk.qq.com/v5/zh-CN/Channel/Self/#%E4%BA%94%E3%80%81%E8%AF%AD%E8%A8%80-langtype-%E5%88%97%E8%A1%A8
local EMailLangType = {
    Chinese 	= "zh_CN",  -- 简体中文(中国)
    Japanese 	= "ja_JP",  -- 日语(日本)
    English 	= "en_GB",  -- 英语(英国)
    Korean 		= "ko_KR",  -- 韩文(韩国)
    French 		= "fr_FR",  -- 法语(法国)
    German 		= "de_DE",  -- 德语(德国)
}
--- 本地化区域名称
local CultureName = CommonDefine.CultureName
--- 【本地化区域名称】 映射到 【SDK自建账号支持的语言列表】
local EMailLangTypeMap = {
    [CultureName.Chinese] 	= EMailLangType.Chinese,
    [CultureName.English] 	= EMailLangType.English,
    [CultureName.Japanese] 	= EMailLangType.Japanese,
    [CultureName.Korean] 	= EMailLangType.Korean,
    [CultureName.French] 	= EMailLangType.French,
    [CultureName.German] 	= EMailLangType.German,
}

--- 海外协议Check状态
local AgreementCheckEnum = {
    All             = 1,
    UserAgreement   = 2,
    PrivacyPolicy   = 3,
}

--- 合规相关Url
local AgreementEnum = {
    Contract                = 1,    -- 游戏许可及服务协议
    Privacy                 = 2,    -- 最终幻想14：水晶世界隐私保护指引
    ChildrenPrivacy         = 3,    -- 儿童隐私保护指引
    PrivacySDK              = 4,    -- 第三方信息共享清单
    SelfDisciplinePact      = 5,
    OverseaUseAgreement     = 6,    -- [海外]用户协议
    OverseaPrivacyPolicy    = 7,    -- [海外]隐私政策
}

--- 合规相关Url
local AgreementUrls = {
    Contract                = "https://game.qq.com/tencent_other_contract.shtml",           -- 游戏许可及服务协议
    Privacy                 = "https://rule.tencent.com/rule/202411130001",            -- 最终幻想14：水晶世界隐私保护指引
    ChildrenPrivacy         = "https://game.qq.com/tencent_other_children_privacy.shtml",   -- 儿童隐私保护指引
    PrivacySDK              = "https://rule.tencent.com/rule/202411110002",             -- 第三方信息共享清单
    SelfDisciplinePact      = "https://game.qq.com/self-discipline_pact.shtml",
    OverseaUseAgreement     = "https://game.qq.com/self-discipline_pact.shtml",             -- [海外]用户协议
    OverseaPrivacyPolicy    = "https://game.qq.com/self-discipline_pact.shtml",             -- [海外]隐私政策
}

--- 海外服务器分区ID
local OverseasSvrAreaId = {
    None            = 0,    -- 未定义
    NorthAmerica    = 1,    -- 北美
    Asia            = 2,    -- 亚洲
    Japan           = 3,    -- 日本
    Korea           = 4,    -- 韩国
    Europe          = 5,    -- 欧洲
}

--- GVoice全球服务器地址
local GVoiceServerUrl = {
    [OverseasSvrAreaId.None] = "udp://cn.voice.gcloudcs.com:10001", -- 默认国内
    [OverseasSvrAreaId.NorthAmerica] = "udp://us.voice.gcloudcs.com:8700",
    [OverseasSvrAreaId.Asia] = "udp://sg.voice.gcloudcs.com:8700",
    [OverseasSvrAreaId.Japan] = "udp://jp.voice.gcloudcs.com:8700",
    [OverseasSvrAreaId.Korea] = "udp://kr.voice.gcloudcs.com:8700",
    [OverseasSvrAreaId.Europe] = "udp://de.voice.gcloudcs.com:8700",
}

local GVoiceServerTestUrl = "udp://gvtest.qq.com:10001"

--- 服务器状态
local ServerStateEnum = {
    -- 16:繁忙, 32:拥挤 64:良好 128:维护
    Maintenance     = 128,    -- 维护
    Fluency         = 64,    -- 流畅
    Busy            = 32,    -- 繁忙
    Full            = 16     -- 爆满
}

--- 服务器Tag
local ServerTagEnum = {
    -- 0:无, 1:热 2:荐 4:新
    None            = 0,    -- 无
    Hot             = 1,    -- 热
    Recommend       = 2,    -- 荐
    New             = 4,    -- 新
    Limit           = 8,    -- 限
    Experience      = 16,   -- 体验服
}

--- 服务器类型
local MapleTabTypeCN = {
    Recommend   = 1,    -- 推荐服务
    Mine        = 2,    -- 我的服务器
    Friend      = 3,    -- 好友服务器
    All         = 4     -- 所有服务器列表
}

--- 服务器类型
local MapleTabTypeOversea = {
    Recommend   = 1,    -- 推荐服务
    All         = 2     -- 所有服务器列表
}

--- 服务器状态
local ServerStateConfig = {
    {
        State = ServerStateEnum.Full,
        -- 470006(爆满)
        Name = LSTR(LoginStrID.SvrStateFull),
        Icon = "PaperSprite'/Game/UI/Atlas/LoginNew/Frames/UI_LoginNew_Img_ServerFull_png.UI_LoginNew_Img_ServerFull_png'"
    },
    {
        State = ServerStateEnum.Busy,
        -- 470007(繁忙)
        Name = LSTR(LoginStrID.SvrStateBusy),
        Icon = "PaperSprite'/Game/UI/Atlas/LoginNew/Frames/UI_LoginNew_Img_ServerBusy_png.UI_LoginNew_Img_ServerBusy_png'"
    },
    {
        State = ServerStateEnum.Fluency,
        -- 470008(流畅)
        Name = LSTR(LoginStrID.SvrStateFluency),
        Icon = "PaperSprite'/Game/UI/Atlas/LoginNew/Frames/UI_LoginNew_Img_ServerSmooth_png.UI_LoginNew_Img_ServerSmooth_png'"
    },
    {
        State = ServerStateEnum.Maintenance,
        -- 470009(维护)
        Name = LSTR(LoginStrID.SvrStateMaintenance),
        Icon = "PaperSprite'/Game/UI/Atlas/LoginNew/Frames/UI_LoginNew_Img_ServerMaintain_png.UI_LoginNew_Img_ServerMaintain_png'",
    },
}

local ServerStateConfigMap = {
    [ServerStateEnum.Full] = {
        -- 470006(爆满)
        Name = LSTR(LoginStrID.SvrStateFull),
        Icon = "PaperSprite'/Game/UI/Atlas/LoginNew/Frames/UI_LoginNew_Img_ServerFull_png.UI_LoginNew_Img_ServerFull_png'"
    },
    [ServerStateEnum.Busy] = {
        -- 470007(繁忙)
        Name = LSTR(LoginStrID.SvrStateBusy),
        Icon = "PaperSprite'/Game/UI/Atlas/LoginNew/Frames/UI_LoginNew_Img_ServerBusy_png.UI_LoginNew_Img_ServerBusy_png'"
    },
    [ServerStateEnum.Fluency] = {
        -- 470008(流畅)
        Name = LSTR(LoginStrID.SvrStateFluency),
        Icon = "PaperSprite'/Game/UI/Atlas/LoginNew/Frames/UI_LoginNew_Img_ServerSmooth_png.UI_LoginNew_Img_ServerSmooth_png'"
    },
    [ServerStateEnum.Maintenance] = {
        -- 470009(维护)
        Name = LSTR(LoginStrID.SvrStateMaintenance),
        Icon = "PaperSprite'/Game/UI/Atlas/LoginNew/Frames/UI_LoginNew_Img_ServerMaintain_png.UI_LoginNew_Img_ServerMaintain_png'",
    },
}

--- 国服服务器类型
local MapleTabCategoryCN = {
    {
        Type = MapleTabTypeCN.Recommend,
        -- 470010(推荐服务器)
        Desc = LSTR(LoginStrID.SvrRecommend),
        CheckIconPath = "PaperSprite'/Game/UI/Atlas/LoginNew/Frames/UI_LoginNew_Icon_Recommend2_png.UI_LoginNew_Icon_Recommend2_png'",
        UnCheckIconPath = "PaperSprite'/Game/UI/Atlas/LoginNew/Frames/UI_LoginNew_Icon_Recommend_png.UI_LoginNew_Icon_Recommend_png'",
    },
    {
        Type = MapleTabTypeCN.Mine,
        -- 470011(我的服务器)
        Desc = LSTR(LoginStrID.SvrMine),
        CheckIconPath = "PaperSprite'/Game/UI/Atlas/LoginNew/Frames/UI_LoginNew_Icon_My2_png.UI_LoginNew_Icon_My2_png'",
        UnCheckIconPath = "PaperSprite'/Game/UI/Atlas/LoginNew/Frames/UI_LoginNew_Icon_My_png.UI_LoginNew_Icon_My_png'",
    },
    {
        Type = MapleTabTypeCN.Friend,
        -- 470012(好友服务器)
        Desc = LSTR(LoginStrID.SvrFriend),
        CheckIconPath = "PaperSprite'/Game/UI/Atlas/LoginNew/Frames/UI_LoginNew_Icon_Friend2_png.UI_LoginNew_Icon_Friend2_png'",
        UnCheckIconPath = "PaperSprite'/Game/UI/Atlas/LoginNew/Frames/UI_LoginNew_Icon_Friend_png.UI_LoginNew_Icon_Friend_png'",
    },
    {
        Type = MapleTabTypeCN.All,
        -- 470013(服务器列表)
        Desc = LSTR(LoginStrID.SvrAllList),
        CheckIconPath = "PaperSprite'/Game/UI/Atlas/LoginNew/Frames/UI_LoginNew_Icon_All2_png.UI_LoginNew_Icon_All2_png'",
        UnCheckIconPath = "PaperSprite'/Game/UI/Atlas/LoginNew/Frames/UI_LoginNew_Icon_All_png.UI_LoginNew_Icon_All_png'",
    }
}

--- 海外服务器类型
local MapleTabCategoryOverseas = {
    {
        Type = MapleTabTypeOversea.Recommend,
        -- 470010(推荐服务器)
        Desc = LSTR(LoginStrID.SvrRecommend),
        CheckIconPath = "PaperSprite'/Game/UI/Atlas/LoginNew/Frames/UI_LoginNew_Icon_Recommend2_png.UI_LoginNew_Icon_Recommend2_png'",
        UnCheckIconPath = "PaperSprite'/Game/UI/Atlas/LoginNew/Frames/UI_LoginNew_Icon_Recommend_png.UI_LoginNew_Icon_Recommend_png'",
    },
    {
        Type = MapleTabTypeOversea.All,
        -- 470013(服务器列表)
        Desc = LSTR(LoginStrID.SvrAllList),
        CheckIconPath = "PaperSprite'/Game/UI/Atlas/LoginNew/Frames/UI_LoginNew_Icon_All2_png.UI_LoginNew_Icon_All2_png'",
        UnCheckIconPath = "PaperSprite'/Game/UI/Atlas/LoginNew/Frames/UI_LoginNew_Icon_All_png.UI_LoginNew_Icon_All_png'",
    }
}

--- 预下载状态
local PreDownloadState = {
    Normal      = 0,
    Init        = 1,
    Downloading = 2,
    Pause       = 3,
    Finish      = 4,
    Error       = 5
}

--- 服务器类型
local AccountCancellationCheckType = {
    None        = 0,    -- 推荐服务
    GroupChat   = 1,    -- 通讯贝
    Friend      = 2,    -- 好友
    NewChannel  = 3,    -- 新人频道
    Team        = 4     -- 部队
}

local LoginConnectAuthType = {
    kAuthNone       = 0,
    kAuthMSDKv3     = 32767,
    kAuthMSDKv5     = 4096,
    kAuthWeGame     = 4101,
    kAuthMSDKPC     = 4102,
    kAuthMSDKPCUID  = 4105,
    kAuthMSDKV5UID  = 4112,
    kAuthINTL       = 4117,
}

local LoginNewDefine = {
    ChannelIDs                  = ChannelIDs,
    Os                          = Os,
    NoticeGroup                 = NoticeGroup,
    EMailLangTypeMap            = EMailLangTypeMap,
    AgreementCheckEnum          = AgreementCheckEnum,
    AgreementEnum               = AgreementEnum,
    AgreementUrls               = AgreementUrls,
    ServerStateEnum             = ServerStateEnum,
    ServerTagEnum               = ServerTagEnum,
    ServerStateConfig           = ServerStateConfig,
    ServerStateConfigMap        = ServerStateConfigMap,
    OverseasSvrAreaId           = OverseasSvrAreaId,
    GVoiceServerTestUrl         = GVoiceServerTestUrl,
    GVoiceServerUrl             = GVoiceServerUrl,
    MapleTabTypeCN              = MapleTabTypeCN,
    MapleTabTypeOversea         = MapleTabTypeOversea,
    MapleTabCategoryCN          = MapleTabCategoryCN,
    MapleTabCategoryOverseas    = MapleTabCategoryOverseas,
    LoginStrID                  = LoginStrID,
    TestEnvPortMap              = TestEnvPortMap,

    DefaultMaterial = "MaterialInstanceConstant'/Game/UI/Material/UI_Desaturate.UI_Desaturate'",
    DefaultFriendImage = "PaperSprite'/Game/UI/Atlas/LoginNew/Frames/UI_LoginNew_Icon_My_png.UI_LoginNew_Icon_My_png'",
    DefaultFriendImageMax = 200,

    PreDownloadState            = PreDownloadState,

    HelpUrl    = "https://game.qq.com/self-discipline_pact.shtml",
    HelpUrlOversea    = "https://game.qq.com/self-discipline_pact.shtml",

    QQPrivilegeUrl = "https://speed.gamecenter.qq.com/pushgame/v1/inner-game/privilege?launchqq=1",

    FriendBtnBgNormal = "PaperSprite'/Game/UI/Atlas/LoginNew/Frames/UI_LoginNew_Btn_Go_png.UI_LoginNew_Btn_Go_png'",
    FriendBtnBgDisable = "Texture2D'/Game/UI/Texture/LoginNew/UI_LoginNew_Btn_Go2.UI_LoginNew_Btn_Go2'",

    VersionErrCode = 120006, -- 客户端版本过低
    ErrCodeAuthFailed = 212, -- 鉴权失败

    AccountCancellationCheckType = AccountCancellationCheckType,
    LoginConnectAuthType = LoginConnectAuthType,
}

local function BuildServerUrl(WorldID, Path)
    local IsAudit = _G.UE.UGCloudMgr.Get():IsAppAuditing()
    if IsAudit then
        return ServerDomainAuditing .. Path
    end

    if UE.UCommonUtil.IsShipping() then
        return ServerDomain .. Path
    else
        local Port = TestEnvPortMap[WorldID] or TestEnvPortMap[10]
        return ServerDomainTest .. Port .. Path
    end
end

function LoginNewDefine:GetMyServerUrl(WorldID)
    return BuildServerUrl(WorldID, "/rpc.fgame.profile.MSdk/QueryRoles")
end

function LoginNewDefine:GetFriendServerUrl(WorldID)
    return BuildServerUrl(WorldID, "/rpc.fgame.profile.MSdk/QueryRolesOfFriend")
end

function LoginNewDefine:GetAccountCancellationUrl(WorldID)
    return BuildServerUrl(WorldID, "/rpc.fgame.profile.Mix/QueryAccountCancellation")
end

function LoginNewDefine:GetArkUrl(WorldID)
    return BuildServerUrl(WorldID, "/rpc.fgame.profile.MSdk/QueryQQGameCenter")
end

function LoginNewDefine:GetIntegrationUrl(WorldID)
    return BuildServerUrl(WorldID, "/rpc.fgame.profile.Mix/QueryPreLoginActivityCfg")
end

function LoginNewDefine:GetDefaultWorldID()
    if UE.UCommonUtil.IsShipping() then
        return 5
    else
        return 10
    end
end

return LoginNewDefine