--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by yuhang_lightpaw.
--- DateTime: 2025/7/7 15:14
---
local LuaClass = require("Core/LuaClass")
local MgrBase = require("Common/MgrBase")
local CommonUtil = require("Utils/CommonUtil")
local MajorUtil = require("Utils/MajorUtil")
local SaveKey = require("Define/SaveKey")
local AudioUtil = require("Utils/AudioUtil")
local ClientGlobalCfg = require("TableCfg/ClientGlobalCfg")
local ProtoRes = require("Protocol/ProtoRes")
local PathMgr = require("Path/PathMgr")
local GameGlobalCfg = require("TableCfg/GameGlobalCfg")
local UIViewID = require("Define/UIViewID")
local EventID = require("Define/EventID")
local ProtoCS = require("Protocol/ProtoCS")
local RhythmGameVM = require("Game/StarlightCelebration/RhythmGame/VM/RhythmGameVM")

local LSTR = nil
local StoryMgr = nil
local FLOG_ERROR = nil
local FLOG_INFO = nil
local UIViewMgr = nil

local ActivtyNodeID = 2507210114    -- 星芒节音游活动节点ID

---@class RhythmGameMgr : MgrBase
local RhythmGameMgr = LuaClass(MgrBase)

local SEQUENCE_BASE_PATH = "LevelSequence'/Game/Assets/Cut/ffxiv_m/fesxma/fesxma00100/fesxma00100_proj/"
RhythmGameMgr.SEQUENCE_PATH = {
    FIRST_ENTRY    = SEQUENCE_BASE_PATH .. "fesxma00100-1st.fesxma00100-1st'",  -- 首次进入
    REGULAR_ENTRY  = SEQUENCE_BASE_PATH .. "fesxma00100-2nd.fesxma00100-2nd'",  -- 常规进入
    SUCCESS_SETTLEMENT = SEQUENCE_BASE_PATH .. "fesxma00100-suc.fesxma00100-suc'", -- 成功结算
    FAILURE_SETTLEMENT = SEQUENCE_BASE_PATH .. "fesxma00100-fal.fesxma00100-fal'"  -- 失败结算
}

local BadBGM = "AkAudioEvent'/Game/WwiseAudio/Events/Music/Sequence/Play_BGM_Season_XmasCho_Bad.Play_BGM_Season_XmasCho_Bad'"
local GoodBGM = "AkAudioEvent'/Game/WwiseAudio/Events/Music/Sequence/Play_BGM_Season_XmasCho_Good.Play_BGM_Season_XmasCho_Good'"

RhythmGameMgr.GameMode =
{
    EASY = 1,
    HARD = 2,
}

-- 音符类型
RhythmGameMgr.NoteType = {
    CLICK = 0,    -- 点击音符
    HOLD = 1,   -- 长按音符
}

-- 判定等级
RhythmGameMgr.Judgement = {
    PERFECT = 0,
    GREAT = 1,
    GOOD = 2,
    MISS = 3
}

-- 判定时间窗口（毫秒）
RhythmGameMgr.JudgementWindows = {
    [RhythmGameMgr.Judgement.PERFECT] = 0.2,
    [RhythmGameMgr.Judgement.GREAT] = 0.5,
    [RhythmGameMgr.Judgement.GOOD] = 1,
    [RhythmGameMgr.Judgement.MISS] = 0,
}

-- 得分
RhythmGameMgr.ScoreValues = {
    [RhythmGameMgr.Judgement.PERFECT] = 1000,
    [RhythmGameMgr.Judgement.GREAT] = 700,
    [RhythmGameMgr.Judgement.GOOD] = 300,
    [RhythmGameMgr.Judgement.MISS] = 0
}

RhythmGameMgr.GameState = {
    NotStarted = 0,
    Playing = 1,
    Paused = 2,
    Settling = 3,
    Ended = 4
}

-- 音符状态枚举
local NoteState = {
    Approaching = 0,  -- 正在接近
    Active = 1,       -- 可交互状态
    Holding = 2,      -- 长按保持中
    Judged = 3        -- 已判定
}

function RhythmGameMgr:OnInit()
    self.DebugMode = false
    self.GameSpeed = 1
    self.NoteShowTime = 900
    self.CurrentState = self.GameState.NotStarted  -- 初始状态
end

function RhythmGameMgr:OnBegin()
    LSTR = _G.LSTR
    StoryMgr = _G.StoryMgr
    FLOG_ERROR = _G.FLOG_ERROR
    FLOG_INFO = _G.FLOG_INFO
    UIViewMgr = _G.UIViewMgr
    
    _G.UE.FTickHelper.GetInst():SetTickIntervalByFrame(self.TickTimerID, 1)  -- 每帧更新
    _G.UE.FTickHelper.GetInst():SetTickDisable(self.TickTimerID)
end

function RhythmGameMgr:OnEnd()
    self:CleanupGame()
end

function RhythmGameMgr:OnShutdown()
    self:CleanupGame()
end

function RhythmGameMgr:OnRegisterGameEvent()
    self:RegisterGameEvent(EventID.OpsActivityUpdateInfo, self.UpdateActivityEndInfo)
end

function RhythmGameMgr:OnRegisterNetMsg()
end

function RhythmGameMgr.OnTick(DeltaTime)
    _G.RhythmGameMgr:Update(DeltaTime * _G.RhythmGameMgr.GameSpeed)
end

function RhythmGameMgr:UpdateActivityEndInfo(MsgBody)
    if not MsgBody then
        return
    end
    
    local Data = MsgBody.NodeOperate
    if Data and Data.OpType == ProtoCS.Game.Activity.NodeOpType.NodeOpTypeStarDayMusicEnd then
        local StarDayMusicGameEnd = Data.Result.StarDayMusicGameEnd
        if StarDayMusicGameEnd then
            self:GetRhythmGameVM():SetIsNewSatisfaction(StarDayMusicGameEnd.SatisfactionNewRecord == true)
            self:GetRhythmGameVM():SetIsNewSScore(StarDayMusicGameEnd.ScoreNewRecord == true)
        end
    end
end

function RhythmGameMgr:OnReconnectStart()
    if self.CurrentState == self.GameState.Playing then
        self:PauseGame()
    end
end

function RhythmGameMgr:OnGameEventLoginRes(Params)
    if Params.bReconnect then
        if self.CurrentState == self.GameState.Playing or self.CurrentState == self.GameState.Paused then
            if not UIViewMgr:IsViewVisible(UIViewID.StarLightRhythmGameMainView) then
                UIViewMgr:ShowView(UIViewID.StarLightRhythmGameMainView)
            end

            if not UIViewMgr:IsViewVisible(UIViewID.CommonMsgBox) then
                self:ShowPauseMsgBox()
            end
        elseif self.CurrentState == self.GameState.Settling then
            self:EndGame()
        end
    end
end

-- 切后台
function RhythmGameMgr:OnEventAppEnterBackground()
    if self.CurrentState == self.GameState.Playing then
        self:PauseGame()
    end
end

-- 返回前台
function RhythmGameMgr:OnEventAppEnterForeground()
    if self.CurrentState == self.GameState.Playing or self.CurrentState == self.GameState.Paused then
        if not UIViewMgr:IsViewVisible(UIViewID.StarLightRhythmGameMainView) then
            UIViewMgr:ShowView(UIViewID.StarLightRhythmGameMainView)
        end
        if not UIViewMgr:IsViewVisible(UIViewID.CommonMsgBox) then
            self:ShowPauseMsgBox()
        end
    elseif self.CurrentState == self.GameState.Settling then
        self:EndGame()
    end
end

-- 重置游戏状态
function RhythmGameMgr:ResetGameState()
    self.CurrentState = self.GameState.NotStarted
    self.Mode = self.Mode or self.GameMode.EASY
    self.MusicData = nil
    self.StartTime = 0
    self.SScore = 0
    self.Combo = 0
    self.MaxCombo = 0
    self.JudgementCounts = {
        [self.Judgement.PERFECT] = 0,
        [self.Judgement.GREAT] = 0,
        [self.Judgement.GOOD] = 0,
        [self.Judgement.MISS] = 0
    }
    
    self.ActiveNotes = {}
    self.NoteObjects = {}
    self.HoldNotes = {}
    self.ConsecutiveMisses = 0  -- 连续Miss次数
    self.ConsecutiveSuccesses = 0 -- 连续成功次数
    self.CurrentBGM = GoodBGM -- 初始化为正常音频
    self.MaxSatisfaction = 0 -- 最大满意度
    self.Satisfaction = 0 -- 当前满意度
    self.SubSatisfaction = 0 -- 达到减满意度的Miss次数
    self.CurrentMissCount = 0 -- 当前连续Miss次数

    if self.RhythmGameVM then
        self.RhythmGameVM:Cleanup()
    end
    
    FLOG_INFO("[RhythmGame] Game state reset")
end

-- 清理游戏资源
function RhythmGameMgr:CleanupGame()
    self.ActiveNotes = {}
    self.NoteObjects = {}
    self.HoldNotes = {}
    self.ConsecutiveMisses = 0
    self.ConsecutiveSuccesses = 0
    self.CurrentBGM = GoodBGM
    if self.RhythmGameVM then
        self.RhythmGameVM:OnEnd()
    end
    self.RhythmGameVM = nil
end

-- 加载谱面数据
function RhythmGameMgr:LoadJson(Mode)
    local JsonPath = PathMgr.ContentDirRelative() .. "MusicGameScore/HARD.json"
    if Mode == self.GameMode.EASY then
        JsonPath = PathMgr.ContentDirRelative() .. "MusicGameScore/CHAOS.json"
    end
    
    self.MusicData = CommonUtil.LoadJsonFile(JsonPath)

    -- 预计算音符时间
    self:PrecalculateNoteTimes()
end

-- 预计算音符的实际出现时间（支持多段变速）
function RhythmGameMgr:PrecalculateNoteTimes()
    local NoteList = self.MusicData.note_list
    local TimeBase = self.MusicData.time_base
    local TempoList = self.MusicData.tempo_list
    local PageList = self.MusicData.page_list

    -- 1. 对速度变化事件按tick排序
    table.sort(TempoList, function(a, b) return a.tick < b.tick end)

    -- 对页面列表按起始tick排序
    table.sort(PageList, function(a, b) return a.start_tick < b.start_tick end)

    -- 2. 预处理速度段
    local TempoSegments = {}
    for i = 1, #TempoList do
        local Segment = {
            StartTick = TempoList[i].tick,
            Tempo = TempoList[i].value,
            MsPerTick = nil,
            EndTick = i < #TempoList and TempoList[i+1].tick or math.huge
        }

        -- Tempo表示一拍的持续时间（微秒）
        -- 每个tick的时间（毫秒）= (Tempo / 1000) / TimeBase
        -- 整个代码的计算不需要，也最好不要带入BPM的概念
        Segment.MsPerTick = (Segment.Tempo / 1000) / TimeBase

        table.insert(TempoSegments, Segment)
    end

    -- 定准线
    local Current_tempo = TempoSegments[1]  -- 假设当前谱面使用单一速度
    for __, page in ipairs(PageList) do
        page.start_time = page.start_tick * Current_tempo.MsPerTick
        page.end_time = page.end_tick * Current_tempo.MsPerTick
    end

    -- 3. 为每个音符计算出现时间和Y坐标
    local CurrentSegmentIndex = 1
    local CumulativeTime = 0

    -- 当前页面索引
    local CurrentPageIndex = 1

    for _, Note in ipairs(NoteList) do
        -- 查找当前音符所在的页面
        while CurrentPageIndex <= #PageList and Note.tick >= PageList[CurrentPageIndex].end_tick do
            CurrentPageIndex = CurrentPageIndex + 1
        end

        -- 计算音符的归一化Y坐标
        if CurrentPageIndex <= #PageList then
            local Page = PageList[CurrentPageIndex]
            local PageDuration = Page.end_tick - Page.start_tick
            Note.scan_line_direction = Page.scan_line_direction
            
            if PageDuration > 0 then
                -- 计算音符在页面内的位置比例 (0-1)
                local PositionInPage = (Note.tick - Page.start_tick) / PageDuration
                
                -- 根据扫描线方向计算Y坐标
                if Page.scan_line_direction == 1 then
                    -- 从下到上：开始位置为1，结束位置为0
                    Note.y = 1 - PositionInPage
                else
                    -- 从上到下：开始位置为0，结束位置为1
                    Note.y = PositionInPage
                end
            else
                Note.y = 0.5  -- 默认中间位置
            end
        else
            Note.y = 0.5  -- 默认中间位置
        end

        -- 查找当前音符对应的速度段
        while Note.tick >= TempoSegments[CurrentSegmentIndex].EndTick do
            -- 计算当前段的持续时间并累加到总时间
            local Segment = TempoSegments[CurrentSegmentIndex]
            local SegmentDuration = (Segment.EndTick - Segment.StartTick) * Segment.MsPerTick
            CumulativeTime = CumulativeTime + SegmentDuration

            -- 移动到下一段
            CurrentSegmentIndex = CurrentSegmentIndex + 1
        end

        -- 计算音符在当前速度段内的时间偏移
        local Segment = TempoSegments[CurrentSegmentIndex]
        local TimeOffset = (Note.tick - Segment.StartTick) * Segment.MsPerTick

        -- 设置音符出现时间
        Note.appearTime = CumulativeTime + TimeOffset
        Note.msPerTick = Segment.MsPerTick
    end

    -- 4. 对音符按出现时间排序
    table.sort(NoteList, function(a, b) return a.appearTime < b.appearTime end)

    -- 5. 记录总时间
    self.TotalTime = CumulativeTime
    FLOG_INFO(string.format("[RhythmGame] Total calculated time: %.2fms", self.TotalTime))
end

-- 生成音符
function RhythmGameMgr:SpawnNotes(CurrentTime)
    local NoteList = self.MusicData.note_list
    local SpawnedNotes = {}

    -- 查找应该出现的音符
    for i = self.NextNoteIndex, #NoteList do
        local Note = NoteList[i]

        -- 提前900MS出现
        if Note.appearTime <= CurrentTime + self.NoteShowTime then
            -- 创建音符对象
            local NoteObj = self:CreateNoteObject(Note)
            table.insert(self.ActiveNotes, NoteObj)
            table.insert(SpawnedNotes, NoteObj)
            self.NextNoteIndex = i + 1

            FLOG_INFO("[RhythmGame] Spawned note ID: %d at %.1fms (type: %s)",
                    NoteObj.ID, NoteObj.AppearTime, NoteObj.Type == self.NoteType.CLICK and "CLICK" or "HOLD")
        else
            break
        end
    end

    return SpawnedNotes
end

-- 创建音符对象
function RhythmGameMgr:CreateNoteObject(NoteData)
    return {
        ID = NoteData.id,
        Type = NoteData.type,
        AppearTime = NoteData.appearTime,
        MsPerTick = NoteData.msPerTick,
        HoldTick = NoteData.hold_tick,
        X = NoteData.x,
        Y = NoteData.y,
        ScanLineDirection = NoteData.scan_line_direction,
        State = NoteState.Approaching,
        IsHeld = false,
        Judgement = nil,
    }
end

-- 更新游戏
function RhythmGameMgr:Update(DeltaTime)
    if self.CurrentState ~= self.GameState.Playing then
        return
    end

    -- 更新当前时间（毫秒）
    self.CurrentTime = self.CurrentTime + DeltaTime * 1000

    -- 生成新音符
    local NoteParam = self:SpawnNotes(self.CurrentTime)
    local GameView = UIViewMgr:FindView(UIViewID.StarLightRhythmGameMainView)
    if GameView then
        GameView:SpawnNotes(NoteParam)
    end
    
    -- 更新活跃音符
    for i = #self.ActiveNotes, 1, -1 do
        local Note = self.ActiveNotes[i]

        -- 更新音符状态
        if Note.State == NoteState.Approaching then
            if Note.AppearTime <= self.CurrentTime then
                Note.State = NoteState.Active
                FLOG_INFO(string.format("[RhythmGame] Note ID %d became active at %.1fms", Note.ID, self.CurrentTime))
            end
        end
    end

    if self.DebugMode then
        -- 定准线
        self:UpdateScanLinePosition()
    end 
end

function RhythmGameMgr:RemoveActiveNote(ID)
    if not self.ActiveNotes then
        return
    end

    for i = #self.ActiveNotes, 1, -1 do
        local Note = self.ActiveNotes[i]
        if Note.ID == ID then
            local GameView = UIViewMgr:FindView(UIViewID.StarLightRhythmGameMainView)
            if GameView then
                GameView:RemoveNote(ID)
            end
            table.remove(self.ActiveNotes, i)
        end
    end
end

function RhythmGameMgr:UpdateScanLinePosition()
    if self.CurrentState ~= self.GameState.Playing then return end

    local Active_page = nil

    -- 查找当前生效的页面
    for _, page in ipairs(self.MusicData.page_list) do
        if self.CurrentTime >= page.start_time and self.CurrentTime <= page.end_time then
            Active_page = page
            break
        end
    end
    
    local ScanLineY = 0
    if not Active_page then
        return
    end

    -- 计算扫描线进度
    local PageDuration = Active_page.end_time - Active_page.start_time
    local Progress = 0
    if PageDuration > 0 then
        local ElapsedTime = self.CurrentTime - Active_page.start_time
        Progress = ElapsedTime / PageDuration
    else
        Progress = (Active_page.scan_line_direction == 1) and 1.0 or 0.0
    end

    -- 根据扫描方向计算Y坐标
    if Active_page.scan_line_direction == 1 then
        ScanLineY = Progress
    else
        ScanLineY = 1 - Progress
    end
    
    local GameView = UIViewMgr:FindView(UIViewID.StarLightRhythmGameMainView)
    if GameView then
        GameView:UpdateScanLinePosition(ScanLineY)
    end
end

-- 获取判定名称
function RhythmGameMgr:GetJudgementName(Judgement)
    if Judgement == self.Judgement.PERFECT then return "PERFECT" end
    if Judgement == self.Judgement.GREAT then return "GREAT" end
    if Judgement == self.Judgement.GOOD then return "GOOD" end
    if Judgement == self.Judgement.MISS then return "MISS" end
    return "UNKNOWN"
end

-- 判定音符
function RhythmGameMgr:JudgeNote(Note, Judgement)
    Note.Judgement = Judgement
    Note.State = NoteState.Judged

    local JudgementName = self:GetJudgementName(Judgement)
    local TimeDiff = math.abs(self.CurrentTime - Note.AppearTime)
    local CurTick = 0
    if Note.MsPerTick > 0 then
        CurTick = self.CurrentTime / Note.MsPerTick
    end
    FLOG_INFO(string.format("[RhythmGame] Judged note ID %d as %s (time diff: %.1fms, Time: %.1fms, Tick: %.1f)",
            Note.ID, JudgementName, TimeDiff, self.CurrentTime, CurTick))
    
    -- 更新统计
    local MissIncrement = 1  -- 默认Miss增量
    ---- 长按类型且未激活保持状态时应用双倍处罚
    --if Note.Type == self.NoteType.HOLD and Judgement == self.Judgement.MISS then
    --    MissIncrement = 2  -- 双倍计数增量
    --end
    
    self.JudgementCounts[Judgement] = self.JudgementCounts[Judgement] + MissIncrement
    if self.DebugMode then
        self:GetRhythmGameVM():UpdateDebugText(self.JudgementCounts)
    end

    -- 更新连击
    if Judgement ~= self.Judgement.MISS then
        self.Combo = self.Combo + 1
        if self.Combo > self.MaxCombo then
            self.MaxCombo = self.Combo
        end
        self:GetRhythmGameVM():UpdateCombo(self.Combo)
        self.ConsecutiveMisses = 0  -- 重置连续Miss计数
        --self.CurrentMissCount = 0    -- 重置当前Miss计数（连续成功时重置）

        -- 更新连续成功计数
        self.ConsecutiveSuccesses = self.ConsecutiveSuccesses + 1

        -- 检查是否需要切换回正常音频
        if self.ConsecutiveSuccesses >= 2 then
            self:SwitchToGoodBGM()
        end
    else
        self.Combo = 0
        self:GetRhythmGameVM():UpdateCombo(self.Combo)
        -- 更新连续Miss计数
        self.ConsecutiveMisses = self.ConsecutiveMisses + MissIncrement
        self.CurrentMissCount = self.CurrentMissCount + MissIncrement  -- 增加当前Miss计数
        -- 检查是否需要减少满意度
        if self.CurrentMissCount >= self.SubSatisfaction then
            self.Satisfaction = math.max(0, self.Satisfaction - 1)  -- 减少满意度，最低为0
            self.CurrentMissCount = 0  -- 重置当前Miss计数
            --FLOG_INFO("[RhythmGame] Satisfaction decreased to %d (after %d misses)", self.Satisfaction, self.SubSatisfaction)
        end
        
        self:GetRhythmGameVM():UpdateSatisfaction(self.Satisfaction)
        self.ConsecutiveSuccesses = 0  -- 重置连续成功计数

        -- 检查是否需要切换到跑调音频
        if self.ConsecutiveMisses == 2 then
            self:SwitchToBadBGM()
        end
    end

    -- 计算得分
    self:CalculateScore(Judgement)

    -- 播放判定效果
    self:PlayJudgementEffect(Judgement)
end

function RhythmGameMgr:PlayBGM()
    local EntityID = MajorUtil.GetMajorEntityID()
    self.GoodAudioID = AudioUtil.SyncLoadAndPlaySoundEvent(EntityID, GoodBGM, true)
    self.BadAudioID = AudioUtil.SyncLoadAndPlaySoundEvent(EntityID, BadBGM, true)
    _G.UE.UAudioMgr.Get().SetRTPCValueByPlayingID("BGM_volume_playing_id", 0, self.BadAudioID, 0)
    self.CurrentBGM = self.GoodAudioID
end

---关闭一些音频
function RhythmGameMgr:CloseSomeAudios()
    _G.UE.UBGMMgr.Get():Pause()
    --_G.UE.UAudioMgr:Get():SetAudioVolume(_G.UE.EWWiseAudioType.Music, 0) 		-- 背景音
    _G.UE.UAudioMgr:Get():SetAudioVolume(_G.UE.EWWiseAudioType.MainPlayer, 0) 	-- 音效
    _G.UE.UAudioMgr:Get():SetAudioVolume(_G.UE.EWWiseAudioType.Ambient_Sound, 0) -- 环境音 
end

---恢复被关闭的音频
function RhythmGameMgr:RecoverBeClosedAudios()
    _G.UE.UBGMMgr.Get():Resume()
    --_G.UE.UAudioMgr:Get():SetAudioVolume(_G.UE.EWWiseAudioType.Music, _G.SettingsMgr:GetValueBySaveKey("MusicVol"))				-- 背景音
    _G.UE.UAudioMgr:Get():SetAudioVolume(_G.UE.EWWiseAudioType.MainPlayer, _G.SettingsMgr:GetValueBySaveKey("MainPlayerVol")) 	-- 音效
    _G.UE.UAudioMgr:Get():SetAudioVolume(_G.UE.EWWiseAudioType.Ambient_Sound, _G.SettingsMgr:GetValueBySaveKey("AmbientVol")) 	-- 环境音 
end

function RhythmGameMgr:PauseBGM()
    if self.GoodAudioID then
        _G.UE.UAkGameplayStatics.ExecuteActionOnPlayingID(1, self.GoodAudioID)
    end
    if self.BadAudioID then
        _G.UE.UAkGameplayStatics.ExecuteActionOnPlayingID(1, self.BadAudioID)
    end
end

function RhythmGameMgr:ResumeBGM()
    if self.GoodAudioID then
        _G.UE.UAkGameplayStatics.ExecuteActionOnPlayingID(2, self.GoodAudioID)
    end
    if self.BadAudioID then
        _G.UE.UAkGameplayStatics.ExecuteActionOnPlayingID(2, self.BadAudioID)
    end
end

function RhythmGameMgr:StopBGM()
    if self.GoodAudioID then
        AudioUtil.StopSound(self.GoodAudioID)
    end
    if self.BadAudioID then
        AudioUtil.StopSound(self.BadAudioID)
    end
    self.CurrentBGM = nil
    self.GoodAudioID = nil
    self.BadAudioID = nil
end

-- 切换到跑调音频
function RhythmGameMgr:SwitchToBadBGM()
    if self.CurrentBGM ~= self.BadAudioID then
        FLOG_INFO("[RhythmGame] Switching to bad BGM")
        _G.UE.UAudioMgr.Get().SetRTPCValueByPlayingID("BGM_volume_playing_id", 0, self.GoodAudioID, 0)
        _G.UE.UAudioMgr.Get().SetRTPCValueByPlayingID("BGM_volume_playing_id", 100, self.BadAudioID, 0)
        self.CurrentBGM = self.BadAudioID
    end
end

-- 切换到正常音频
function RhythmGameMgr:SwitchToGoodBGM()
    if self.CurrentBGM ~= self.GoodAudioID then
        FLOG_INFO("[RhythmGame] Switching to good BGM")
        _G.UE.UAudioMgr.Get().SetRTPCValueByPlayingID("BGM_volume_playing_id", 100, self.GoodAudioID, 0)
        _G.UE.UAudioMgr.Get().SetRTPCValueByPlayingID("BGM_volume_playing_id", 0, self.BadAudioID, 0)
        self.CurrentBGM = self.GoodAudioID
    end
end

-- 计算得分
function RhythmGameMgr:CalculateScore(Judgement)
    -- 基础分 + 连击加成
    local BaseScore = self.ScoreValues[Judgement] or 0
    if self.ConsecutiveSuccesses > 2 then
        BaseScore = BaseScore * 2
    end
    self.SScore = self.SScore + BaseScore
    self:GetRhythmGameVM():UpdateScore(self.SScore)
end

-- 播放判定效果
function RhythmGameMgr:PlayJudgementEffect(Judgement)
    if Judgement == self.Judgement.PERFECT then
        AudioUtil.SyncLoadAndPlay2DSound("AkAudioEvent'/Game/WwiseAudio/Events/sound/battle/etc/SE_Bt_Etc_MG_Xmas_Hit_Great/Play_SE_Bt_Etc_MG_Xmas_Hit_Great.Play_SE_Bt_Etc_MG_Xmas_Hit_Great'")
        AudioUtil.SyncLoadAndPlay2DSound("AkAudioEvent'/Game/WwiseAudio/Events/sound/battle/etc/SE_Bt_Etc_MG_Xmas_Hit_Perfect/Play_SE_Bt_Etc_MG_Xmas_Hit_Perfect.Play_SE_Bt_Etc_MG_Xmas_Hit_Perfect'")
    elseif Judgement == self.Judgement.GREAT then
        AudioUtil.SyncLoadAndPlay2DSound("AkAudioEvent'/Game/WwiseAudio/Events/sound/battle/etc/SE_Bt_Etc_MG_Xmas_Hit_Great/Play_SE_Bt_Etc_MG_Xmas_Hit_Great.Play_SE_Bt_Etc_MG_Xmas_Hit_Great'")
    elseif Judgement == self.Judgement.GOOD then
        AudioUtil.SyncLoadAndPlay2DSound("AkAudioEvent'/Game/WwiseAudio/Events/sound/battle/etc/SE_Bt_Etc_MG_Xmas_Trans_Good/Play_SE_Bt_Etc_MG_Xmas_Trans_Good.Play_SE_Bt_Etc_MG_Xmas_Trans_Good'")
    elseif Judgement == self.Judgement.MISS then
        if self.ConsecutiveMisses == 2 then
            AudioUtil.SyncLoadAndPlay2DSound("AkAudioEvent'/Game/WwiseAudio/Events/sound/battle/etc/SE_Bt_Etc_MG_Xmas_Trans_Bad/Play_SE_Bt_Etc_MG_Xmas_Trans_Bad.Play_SE_Bt_Etc_MG_Xmas_Trans_Bad'")
        end
    end
end

-- 输入回调处理
function RhythmGameMgr:OnClickNote(ID, Judgement)
    if self.CurrentState ~= self.GameState.Playing then
        return
    end

    -- 查找最接近的可判定音符
    local ClosestNote, MinDiff = nil, math.huge
    for i, Note in ipairs(self.ActiveNotes) do
        if Note.ID == ID and Note.Type == self.NoteType.CLICK and not Note.Judgement then
            --local TimeDiff = math.abs(Note.AppearTime - self.CurrentTime)
            --if TimeDiff < MinDiff then
                ClosestNote = Note
            --    MinDiff = TimeDiff
            --end
        end
    end

    if ClosestNote then
        self:JudgeNote(ClosestNote, Judgement)
    end
end

function RhythmGameMgr:OnPressedNote(ID, Judgement)
    if self.CurrentState ~= self.GameState.Playing then
        return
    end

    -- 查找对应的长按音符
    local TargetNote = nil
    for i, Note in ipairs(self.ActiveNotes) do
        if Note.ID == ID and Note.Type == self.NoteType.HOLD and not Note.Judgement then
            --local TimeDiff = math.abs(Note.AppearTime - self.CurrentTime)
            TargetNote = Note
            break
        end
    end

    if TargetNote then
        -- 开始长按
        TargetNote.IsHeld = true
        TargetNote.State = NoteState.Holding
        self.HoldNotes[ID] = TargetNote
        
        self:JudgeNote(TargetNote, Judgement)
    end
end

function RhythmGameMgr:OnReleasedNote(ID, Judgement)
    if self.CurrentState ~= self.GameState.Playing then
        return
    end

    local Note = self.HoldNotes[ID]
    if Note then
        -- 结束长按
        Note.IsHeld = false
        self:JudgeNote(Note, Judgement)

        self.HoldNotes[ID] = nil
    end
end

-- 首次进入处理
function RhythmGameMgr:PlayFirstEntrySequence()
    local PlaybackSettings = {
        bDisableMovementInput = true,
        bDisableLookAtInput = true,
        bPauseAtEnd = true,
    }
    
    local function SequenceStopCallback(_)
        self:RegisterTimer(self.StartSettlement, 0.01)
    end

    StoryMgr:PlaySequenceByPath(self.SEQUENCE_PATH.FIRST_ENTRY, SequenceStopCallback, nil, nil, PlaybackSettings)
end

-- 非首次进入处理
function RhythmGameMgr:PlayRegularEntrySequence()
    local PlaybackSettings = {
        bDisableMovementInput = true,
        bDisableLookAtInput = true,
        bPauseAtEnd = true,
    }
    local function SequenceStopCallback(_)
        self:RegisterTimer(self.StartSettlement, 0.01)
    end
    
    StoryMgr:PlaySequenceByPath(self.SEQUENCE_PATH.REGULAR_ENTRY, SequenceStopCallback, nil, nil, PlaybackSettings)
end

-- 结算成功处理
function RhythmGameMgr:PlaySuccessSettlement()
    local PlaybackSettings = {
        bDisableMovementInput = true,
        bDisableLookAtInput = true,
        bPauseAtEnd = true,
    }
    StoryMgr:PlaySequenceByPath(self.SEQUENCE_PATH.SUCCESS_SETTLEMENT, nil, nil, nil, PlaybackSettings)
end

-- 结算失败处理
function RhythmGameMgr:PlayFailureSettlement()
    local PlaybackSettings = {
        bDisableMovementInput = true,
        bDisableLookAtInput = true,
        bPauseAtEnd = true,
    }
    StoryMgr:PlaySequenceByPath(self.SEQUENCE_PATH.FAILURE_SETTLEMENT, nil, nil, nil, PlaybackSettings)
end

function RhythmGameMgr:InitGame(Mode)
    local TableData = nil
    TableData = GameGlobalCfg:FindValue(ProtoRes.Game.game_global_cfg_id.GAME_CFG_STAR_LIGHT_MUSIC_SATISFACTION_CFG, "Value")

    if TableData then
        self.Satisfaction = TableData[1] and TableData[1] or 0
        self.MaxSatisfaction = TableData[1] and TableData[1] or 0
        if Mode == self.GameMode.EASY then
            self.SubSatisfaction = TableData[2] and TableData[2] or 0
        else
            self.SubSatisfaction = TableData[3] and TableData[3] or 0
        end
    end

    TableData = GameGlobalCfg:FindValue(ProtoRes.Game.game_global_cfg_id.GAME_CFG_STAR_LIGHT_MUSIC_SCORE_CFG, "Value")
    if TableData then
        self.ScoreValues[self.Judgement.PERFECT] = TableData[1] and TableData[1] or 0
        self.ScoreValues[self.Judgement.GREAT] = TableData[2] and TableData[2] or 0
        self.ScoreValues[self.Judgement.GOOD] = TableData[3] and TableData[3] or 0
        self.ScoreValues[self.Judgement.MISS] = TableData[4] and TableData[4] or 0
    end

    TableData = GameGlobalCfg:FindValue(ProtoRes.Game.game_global_cfg_id.GAME_CFG_STAR_LIGHT_MUSIC_NOTE_TIME_CFG, "Value")
    if TableData then
        self.NoteShowTime = TableData[1] or 900
    end
    
    TableData = GameGlobalCfg:FindValue(ProtoRes.Game.game_global_cfg_id.GAME_CFG_STAR_LIGHT_MUSIC_NOTE_RANGE_CFG, "Value")
    if TableData then
        self.JudgementWindows[self.Judgement.PERFECT] = TableData[1] and TableData[1] / 100 or 0.2
        self.JudgementWindows[self.Judgement.GREAT] = TableData[2] and TableData[2] / 100 or 0.5
        self.JudgementWindows[self.Judgement.GOOD] = TableData[3] and TableData[3] / 100 or 1
        self.JudgementWindows[self.Judgement.MISS] = TableData[4] and TableData[4] / 100 or 0
    end
end

function RhythmGameMgr:EnterGame(Mode)
    self:RegisterGameEvent(EventID.NetworkReconnectStart, self.OnReconnectStart)
    self:RegisterGameEvent(EventID.RoleLoginRes, self.OnGameEventLoginRes)
    self:RegisterGameEvent(EventID.AppEnterBackground, self.OnEventAppEnterBackground)
    self:RegisterGameEvent(EventID.AppEnterForeground, self.OnEventAppEnterForeground)

    self:ResetGameState()
    self.Mode = Mode or self.GameMode.EASY
    self.CurrentState = self.GameState.NotStarted
    self:CloseSomeAudios()
    
    local IsFirstTime = _G.UE.USaveMgr.GetInt(SaveKey.StarlightRhythmGameFirstTime, 0, true) == 0
    if IsFirstTime then
        self:PlayFirstEntrySequence()
        _G.UE.USaveMgr.SetInt(SaveKey.StarlightRhythmGameFirstTime, 1, true)
    else
        self:PlayRegularEntrySequence()
    end
    
    -- 发送活动协议
    _G.OpsActivityMgr:SendActivityNodeOperate(ActivtyNodeID, ProtoCS.Game.Activity.NodeOpType.NodeOpTypeStarDayMusicStart,
            { StarDayMusicGameStart = {}})
    _G.ClientReportMgr:SendClientReport(ProtoCS.ReportType.ReportTypeEnterCutScenes)
end

function RhythmGameMgr:StartGame()
    if self.CurrentState ~= self.GameState.NotStarted then
        return
    end

    self:PlayBGM()
    
    self:GetRhythmGameVM()
    self:InitGame(self.Mode)
    self:LoadJson(self.Mode)
    self:GetRhythmGameVM():UpdateMode(self.Mode)

    -- 开始游戏
    self.CurrentState = self.GameState.Playing
    self.NextNoteIndex = 1
    self.CurrentTime = 0

    -- 生成初始音符
    local NoteParam = self:SpawnNotes(0)
    local GameView = UIViewMgr:FindView(UIViewID.StarLightRhythmGameMainView)
    if GameView then
        GameView:SpawnNotes(NoteParam)
    end
    _G.UE.FTickHelper.GetInst():SetTickEnable(self.TickTimerID)
end

function RhythmGameMgr:PauseGame()
    if self.CurrentState == self.GameState.Playing then
        self.CurrentState = self.GameState.Paused
        self:PauseBGM()
        StoryMgr:PauseSequence()

        if StoryMgr.SequencePlayer then
            StoryMgr.SequencePlayer:AdjustCharactersPostion()
        end
        
        local GameView = UIViewMgr:FindView(UIViewID.StarLightRhythmGameMainView)
        if GameView then
            GameView:PauseGame()
        end
    end
end

function RhythmGameMgr:ResumeGame()
    if self.CurrentState == self.GameState.Paused then
        self.CurrentState = self.GameState.Playing
        self:ResumeBGM()
        StoryMgr:ContinueSequence()

        local GameView = UIViewMgr:FindView(UIViewID.StarLightRhythmGameMainView)
        if GameView then
            GameView:ResumeGame()
        end
    end
end

function RhythmGameMgr:ReStartGame()
    _G.StoryMgr:StopSequence()
    --清理音乐
    self:StopBGM()
    -- 清理节点
    local GameView = UIViewMgr:FindView(UIViewID.StarLightRhythmGameMainView)
    if GameView then
        GameView:RemoveActiveNodes()
    else
        self:EnterGame(self.Mode)
    end
end

-- 开始结算
function RhythmGameMgr:StartSettlement()
    if self.CurrentState == self.GameState.Playing then
        self.CurrentState = self.GameState.Settling
        _G.StoryMgr:StopSequence()
        
        local Params = {}
        Params.FadeColorType = 3
        Params.Duration = 1
        Params.DelayHide = 1
        UIViewMgr:ShowView(UIViewID.CommonFadePanel, Params)
        
        -- 保存分数
        self:SaveScore()
        if self.Satisfaction > 0 then
            self:PlaySuccessSettlement()
        else
            self:PlayFailureSettlement()
        end
        
        _G.UE.FTickHelper.GetInst():SetTickDisable(self.TickTimerID)
    end
end

-- 保存分数
function RhythmGameMgr:SaveScore()
    local VM = self:GetRhythmGameVM()

    VM:UpdateScore(self.SScore)
    VM:UpdateSatisfaction(self.Satisfaction)
    VM:UpdateResult(self.Mode, self.JudgementCounts)
    
    local AwardType = ProtoCS.Game.Activity.AwradType.None
    if VM.IsPerfectCombo then
        AwardType = ProtoCS.Game.Activity.AwradType.AllPerfect
    elseif VM.IsFullCombo then
        AwardType = ProtoCS.Game.Activity.AwradType.FullCombo
    elseif VM.IsSuc then
        AwardType = ProtoCS.Game.Activity.AwradType.Normal
    end

    if VM.IsSuc then
        -- 发送活动协议
        _G.OpsActivityMgr:SendActivityNodeOperate(ActivtyNodeID,
                ProtoCS.Game.Activity.NodeOpType.NodeOpTypeStarDayMusicEnd,{
                    StarDayMusicGameEnd = {
                        IsHard = self.Mode == self.GameMode.HARD,
                        Score = VM.SScore,
                        Satisfaction = VM.Satisfaction,
                        Award = AwardType,
                    }
                })

        local Params = {
            GameID = ProtoRes.Game.GameID.GameIDStarlight
        }
        _G.EventMgr:SendEvent(EventID.QuestFinishGameplay, Params)
    end
end

-- 结束游戏
function RhythmGameMgr:EndGame()
    StoryMgr:StopSequence()

    if UIViewMgr:IsViewVisible(UIViewID.StarLightRhythmGameMainView) then
        UIViewMgr:HideView(UIViewID.StarLightRhythmGameMainView)
    end
    if UIViewMgr:IsViewVisible(UIViewID.StarLightRhythmGameResultWinView) then
        UIViewMgr:HideView(UIViewID.StarLightRhythmGameResultWinView)
    end
    
    self:UnRegisterGameEvent(EventID.NetworkReconnectStart, self.OnReconnectStart)
    self:UnRegisterGameEvent(EventID.RoleLoginRes, self.OnGameEventLoginRes)
    self:UnRegisterGameEvent(EventID.AppEnterBackground, self.OnEventAppEnterBackground)
    self:UnRegisterGameEvent(EventID.AppEnterForeground, self.OnEventAppEnterForeground)
    
    self:RecoverBeClosedAudios()
    _G.UE.FTickHelper.GetInst():SetTickDisable(self.TickTimerID)
    self.CurrentState = self.GameState.Ended
    _G.ClientReportMgr:SendClientReport(ProtoCS.ReportType.ReportTypeQuitCutScenes)
end

function RhythmGameMgr:GetRhythmGameVM()
    if not self.RhythmGameVM then
        self.RhythmGameVM = RhythmGameVM.New()
    end
    
    return self.RhythmGameVM
end

function RhythmGameMgr:SetSpeed(Value)
    self.GameSpeed = Value
end

function RhythmGameMgr:ShowPauseMsgBox()
    local LeftCB = function()
        _G.StoryMgr:StopSequence()
        self.CurrentState = self.GameState.Settling

        local Params = {}
        Params.FadeColorType = 3
        Params.Duration = 1
        Params.DelayHide = 1
        UIViewMgr:ShowView(UIViewID.CommonFadePanel, Params)
        
        self.Satisfaction = 0
        self:SaveScore()
        self:PlayFailureSettlement()
        _G.UE.FTickHelper.GetInst():SetTickDisable(self.TickTimerID)
    end

    local MidCB = function()
        self:ReStartGame()
    end

    local RightCB = function()
        self:ResumeGame()
    end

    self:PauseGame()
    _G.MsgBoxUtil.ShowMsgBoxThreeOp(self, _G.LSTR(1710003), _G.LSTR(1710004), RightCB, MidCB,
            LeftCB, _G.LSTR(1710005), _G.LSTR(1710006), _G.LSTR(1710007),{
                CloseClickCB = RightCB,
            })
end

--region 测试代码
function RhythmGameMgr:SetDebug(Value)
    self.DebugMode = Value or false
end

function RhythmGameMgr:TestStart()
    self:ResetGameState()
    UIViewMgr:ShowView(UIViewID.StarLightRhythmGameMainView)
end

function RhythmGameMgr:Test(X, Y)
    local NoteParam = {
        ID = 1,
        Type = 0,
        AppearTime = 0,
        X = X,
        Y = Y,
        State = NoteState.Approaching,
        IsHeld = false,
        Judgement = nil,
    }
    local GameView = UIViewMgr:FindView(UIViewID.StarLightRhythmGameMainView)
    if GameView then
        GameView:SpawnNotes({[1] = NoteParam})
    end
end

function RhythmGameMgr:Test2()
    local GameView = UIViewMgr:FindView(UIViewID.StarLightRhythmGameMainView)
    if GameView then
        local Note = GameView:GetNote(1)
        if Note then
            Note.RhythmGameBtnItem:PlayAnimation(Note.RhythmGameBtnItem.AnimReset)
            Note.RhythmGameBtnItem:PlayAnimNormalScale(200, 100, 1)
        end
    end
end

function RhythmGameMgr:Test3()
    local GameView = UIViewMgr:FindView(UIViewID.StarLightRhythmGameMainView)
    if GameView then
        local Note = GameView:GetNote(1)
        if Note then
            Note.RhythmGameBtnItem:PlayAnimation(Note.RhythmGameBtnItem.AnimReset)
            Note.RhythmGameBtnItem:PlayAnimLongPressScale(200, 100, 1)
        end
    end
end

function RhythmGameMgr:Test4()
    local GameView = UIViewMgr:FindView(UIViewID.StarLightRhythmGameMainView)
    if GameView then
        local Note = GameView:GetNote(1)
        if Note then
            Note.RhythmGameBtnItem:PlayAnimation(Note.RhythmGameBtnItem.AnimReset)
            Note.RhythmGameBtnItem:PlayAnimLongPressLongMove(300, 0, 1)
        end
    end
end
--endregion

return RhythmGameMgr
