---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2024/1/11 10:05
---

local LuaClass = require("Core/LuaClass")
local UIViewModel = require("UI/UIViewModel")
local UIUtil = require("Utils/UIUtil")
local ProtoRes = require("Protocol/ProtoRes")
local ChocoboUiIconCfg = require("TableCfg/ChocoboUiIconCfg")
local BuddyEquipCfg = require("TableCfg/BuddyEquipCfg")

---@class ChocoboArmorVM : UIViewModel
local ChocoboArmorVM = LuaClass(UIViewModel)

---Ctor
function ChocoboArmorVM:Ctor()
    self.ArmorID = 0
    self.Pos = 0
    self.BGPath = ""
    self.IconPath = ""
    self.IsShowSlot = false
end

function ChocoboArmorVM:UpdateVM(Data)
    self.ArmorID = Data.ArmorID
    self.Pos = Data.Pos
    self.BGPath = ChocoboUiIconCfg:FindPathByKey(ProtoRes.CHOCOBO_UI_ICON_TYPE.DEFAULT_ARMOR_HEAD + self.Pos)
    if self.ArmorID ~= 0 then
        self.IsShowSlot = true
        local EquipCfg = BuddyEquipCfg:FindCfgByKey(self.ArmorID)
        if EquipCfg ~= nil then
            self.IconPath = UIUtil.GetIconPath(EquipCfg.IconID)
        end
    else
        self.IsShowSlot = false
    end
end

function ChocoboArmorVM:IsEqualVM(Value)
    return false
end

return ChocoboArmorVM