---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2024/1/10 16:13
---

local LuaClass = require("Core/LuaClass")
local UIViewModel = require("UI/UIViewModel")
local ChocoboDefine = require("Game/Chocobo/ChocoboDefine")

---@class ChocoboTitleProbarItemVM : UIViewModel
local ChocoboTitleProbarItemVM = LuaClass(UIViewModel)

---Ctor
function ChocoboTitleProbarItemVM:Ctor()
    self.ID = 0
    self.Progress = 0
    self.NodeName = ""
    self.NodeNameColor = "D1BA8EFF"
    self.IsGet = false
    self.IsShowRedPoint = false
    self.IsSelect = false
    self.State = ChocoboDefine.TITLE_REWARD_STATE.GO_ON
end

function ChocoboTitleProbarItemVM:UpdateVM(Data)
    self.ID = Data.ID
    self.Progress = Data.Progress
    self.NodeName = Data.NodeName
    self.State = Data.State
    self.IsGet = Data.IsGet
    self.IsShowRedPoint = Data.IsShowRedPoint
    self.IsSelect = Data.IsSelect
    if self.State >= ChocoboDefine.TITLE_REWARD_STATE.CAN_REWARD then
        self.NodeNameColor = "D1BA8EFF"
    else
        self.NodeNameColor = "828282FF"
    end
end

function ChocoboTitleProbarItemVM:IsEqualVM(Value)
    return false
end

function ChocoboTitleProbarItemVM:SetSelect(Value)
    self.IsSelect = Value
end

function ChocoboTitleProbarItemVM:UpdateState(Value)
    self.State = Value
    self.Progress = 1
    self.IsGet = Value == ChocoboDefine.TITLE_REWARD_STATE.ALREADY_GET
    self.IsShowRedPoint = Value == ChocoboDefine.TITLE_REWARD_STATE.CAN_REWARD
    if self.State >= ChocoboDefine.TITLE_REWARD_STATE.CAN_REWARD then
        self.NodeNameColor = "D1BA8EFF"
    else
        self.NodeNameColor = "828282FF"
    end
end

return ChocoboTitleProbarItemVM