---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2024/1/10 16:13
---

local LuaClass = require("Core/LuaClass")
local UIViewModel = require("UI/UIViewModel")
local ChocoboDefine = require("Game/Chocobo/ChocoboDefine")
local ProtoRes = require("Protocol/ProtoRes")

---@class ChocoboTitleWinItemVM : UIViewModel
local ChocoboTitleWinItemVM = LuaClass(UIViewModel)

---Ctor
function ChocoboTitleWinItemVM:Ctor()
    self.ID = 0
    self.Index = 0
    self.Type = ProtoRes.CHOCOBO_MISSION_TYPE.CHOCOBO_MISSION_TYPE_RACE_PARTICIPATE
    self.IconPath = ""
    self.TextContent = ""
    self.TextProgress = ""
    self.TextNum = ""
    self.IsRewardGet = false
    self.IsShowMask = false
    self.IsShowNum = true
    self.ButtonState = ChocoboDefine.TITLE_REWARD_STATE.GO_ON
end

function ChocoboTitleWinItemVM:UpdateVM(Data)
    self.ID = Data.ID
    self.Index = Data.Index
    self.Type = Data.Type
    self.IconPath = Data.IconPath
    self.TextContent = Data.TextContent
    self.TextProgress = Data.TextProgress
    self.TextNum = Data.TextNum
    self.IsRewardGet = Data.IsRewardGet
    self.IsShowMask = Data.IsShowMask
    self.ButtonState = Data.ButtonState
end

function ChocoboTitleWinItemVM:IsEqualVM(Value)
    return false
end

function ChocoboTitleWinItemVM:UpdateState(Value)
    self.ButtonState = Value
    self.IsRewardGet = Value == ChocoboDefine.TITLE_REWARD_STATE.ALREADY_GET
    self.IsShowMask = Value == ChocoboDefine.TITLE_REWARD_STATE.ALREADY_GET
end

return ChocoboTitleWinItemVM