---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2023/12/30 14:46
---
local LuaClass = require("Core/LuaClass")
local UIViewModel = require("UI/UIViewModel")

---@class ChocoboGenerationItemVM : UIViewModel
local ChocoboGenerationItemVM = LuaClass(UIViewModel)

---Ctor
function ChocoboGenerationItemVM:Ctor()
    self.ID = 0
    self.IsSelect = false
end

function ChocoboGenerationItemVM:UpdateVM(Data)
    self.ID = Data.ID
end

function ChocoboGenerationItemVM:IsEqualVM(Value)
    return Value ~= nil and Value.ID == self.ID
end

function ChocoboGenerationItemVM:SetIsSelect(Value)
    self.IsSelect = Value
end

return ChocoboGenerationItemVM