---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2024/1/23 9:57
---

local LuaClass = require("Core/LuaClass")
local UIViewModel = require("UI/UIViewModel")
local ChocoboLevelUpItemVM = require("Game/Chocobo/Life/VM/ChocoboLevelUpItemVM")

---@class ChocoboLevelUpTipsVM : UIViewModel
local ChocoboLevelUpTipsVM = LuaClass(UIViewModel)

---Ctor
function ChocoboLevelUpTipsVM:Ctor()
    self.TableViewList = self:ResetBindableList(self.TableViewList, ChocoboLevelUpItemVM)
end

function ChocoboLevelUpTipsVM:UpdateVM(Data)
    self.TableViewList:UpdateByValues(Data.Attr)
end

return ChocoboLevelUpTipsVM