-- AUTO GENERATED CODE, PLEASE DON'T MODIFY

local ProtoCS = {
	Externalserviceagent = {
		Ace = {
			CsAceCmd = {
				CS_ACE_INVALID = 0,
				CS_ACE_RECEIVE_PACKET = 1,
			},
		},
		PlayerReport = {
		},
		TsS = {
		},
	},
	CsAchievementCmd = {
		CS_ACHIEVEMENT_INVALID = 0,
		CS_ACHIEVEMENT_QUERY = 1,
		CS_ACHIEVEMENT_CLAIM = 2,
		CS_ACHIEVEMENT_TARGET_LIST = 3,
		CS_ACHIEVEMENT_LEVEL_AWARD = 4,
		CS_ACHIEVEMENT_COMPLETE = 5,
		CS_ACHIEVEMENT_UPDATE = 6,
		CS_ACHIEVEMENT_LEVEL_UP = 7,
		CS_ACHIEVEMENT_SHOWED_COMPLETED = 8,
		CS_ACHIEVEMENT_OTHER_COMPLETE = 9,
	},
	LevelType = {
		LEVEL_TYPE_ALL = 0,
		LEVEL_TYPE_COMBAT = 1,
		LEVEL_TYPE_PLAYER_BATTLE = 2,
		LEVEL_TYPE_ROLE = 3,
		LEVEL_TYPE_ITEM = 4,
		LEVEL_TYPE_GATHER = 5,
		LEVEL_TYPE_QUEST = 6,
		LEVEL_TYPE_EXPLORE = 7,
		LEVEL_TYPE_ARMY = 8,
	},
	AchievementStatus = {
		ACHIEVEMENT_STATUS_COMPLETED = 0,
		ACHIEVEMENT_STATUS_CLIAMED = 1,
	},
	Game = {
		Activity = {
			Cmd = {
				None = 0,
				Reward = 1,
				List = 2,
				Detail = 3,
				EventReport = 5,
				NodeOperate = 6,
				ActReward = 7,
				ListByID = 8,
				MultiReward = 9,
				NodesChange = 10,
				ChgNotify = 11,
			},
			NodeOpType = {
				NodeOpType_None = 0,
				NodeOpTypeShareBuyPurchase = 1,
				NodeOpTypeShardBuyInput = 2,
				NodeOpTypeLotteryDrawLayBack = 3,
				NodeOpTypeLotteryDrawNoLayBack = 4,
				NodeOpTypeLotteryDrawWeigt = 5,
				NodeOpTypeExchange = 6,
				NodeOpTypeBindCallCode = 7,
				NodeOpTypeUnBindInvitee = 8,
				NodeOpTypePullBindRole = 11,
				NodeOpTypePhoneBindCode = 13,
				NodeOpTypePhoneBindAuth = 14,
				NodeOpTypePhoneBindAgreements = 15,
			},
			PhoneBindMode = {
				PhoneBindMode_Bind = 0,
				PhoneBindMode_Unbind = 1,
				PhoneBindMode_Renew = 2,
			},
			RewardStatus = {
				RewardStatusNo = 0,
				RewardStatusWaitGet = 1,
				RewardStatusDone = 2,
			},
			enStatus = {
				None = 0,
				OriginalPayed = 1,
				CodeInputed = 2,
				DiscountPayed = 3,
				Status = 1,
				CouponCode = 2,
				UsedTimes = 3,
			},
		},
		AreaMail = {
			CS_AREA_MAIL_CMD = {
				CS_AREA_MAIL_INVALID = 0,
				CS_AREA_MAIL_GET = 1,
				CS_AREA_MAIL_UPDATE = 2,
			},
		},
		Barbershop = {
			Cmd = {
				None = 0,
				SetFace = 1,
				Update = 2,
				UnlockHair = 3,
				ChangeMap = 4,
			},
		},
		BlindBox = {
			CS_BLINDBOX_CMD = {
				INVALID = 0,
				GETLIST = 1,
				BUY = 2,
			},
		},
		ChooseTreasureChest = {
			CS_CHOOSETREASURECHEST_CMD = {
				INVALID = 0,
				EXCHANGE = 1,
			},
		},
		FairyBlessed = {
			CS_FAIRY_BLESSED_CMD = {
				CS_FAIRY_BLESSED_CMD_INVALID = 0,
				CS_FAIRY_BLESSED_CMD_GET = 1,
			},
			BLESSED_KIND = {
				BLESSED_KIND_NONE = 0,
				BLESSED_KIND_LITTLE = 1,
				BLESSED_KIND_BIG = 2,
			},
		},
		FashionCheck = {
			Cmd = {
				None = 0,
				Check = 1,
				Update = 2,
			},
		},
		Lantern = {
			CS_LANTERN_CMD = {
				LANTERN_INVALID = 0,
				LANTERN_GETLIST = 1,
				LANTERN_NTF_ADD = 2,
				LANTERN_NTF_DEL = 3,
			},
		},
		MysteryMerchant = {
			MERCHANT_TYPE = {
				MERCHANT_TYPE_NONE = 0,
				MERCHANT_TYPE_SHARED = 1,
				MERCHANT_TYPE_EXCLUSIVE = 2,
			},
			MERCHANT_TASK_STATUS = {
				MERCHANT_TASK_STATUS_NONE = 0,
				MERCHANT_TASK_STATUS_UNFINISHED = 1,
				MERCHANT_TASK_STATUS_SCENE_WAIT_SUBMIT = 2,
				MERCHANT_TASK_STATUS_WAIT_SUBMIT = 3,
				MERCHANT_TASK_STATUS_FINISH = 4,
			},
			INVEST_MERCHANT_STATUS = {
				INVEST_MERCHANT_STATUS_NONE = 0,
				INVEST_MERCHANT_STATUS_TRIGGER = 1,
				INVEST_MERCHANT_STATUS_INVESTED = 2,
				INVEST_MERCHANT_STATUS_WAIT_RECEIVE = 3,
				INVEST_MERCHANT_STATUS_RECEIVED = 4,
			},
			Cmd = {
				None = 0,
				QueryMerchantMapData = 1,
				QueryMerchantData = 3,
				MerchantTaskStats = 9,
				SharedMerchantBirth = 11,
				QueryMerchantGoods = 12,
				BuyMerchantGoods = 13,
				TriggerMerchantTask = 14,
				SubmitMerchantTask = 15,
				InvestMerchant = 16,
				ReceiveInvestRewards = 17,
				MerchantBuffDestroy = 18,
				ExclusiveRefresh = 19,
			},
		},
		PvPColosseum = {
			CS_PVPCOLOSSEUM_CMD = {
				INVALID = 0,
				INVITE_DUEL = 1,
				CANCLE_DUEL = 2,
				INVITE_NTF_TGT_DUEL = 3,
				ACCEPT_NTF_TGT_DUEL = 4,
				ACCEPT_DUEL = 5,
				DUEL_RESULT = 6,
				JOIN_GAME = 7,
				FASTCHAT_INGAME = 8,
				GAME_RESULT = 9,
				GAME_RESULT_LIKE = 10,
				BTLMATERIALS = 11,
				STAR_ROADSIGN_REWARD = 12,
				STAR_ROADSIGN_LEVELUP_NTF = 13,
				DUEL_BEGIN_COUNTDOWN_NTF = 14,
				GET_DUEL_INFO = 15,
				GET_LIKE_INFO = 16,
				BADGE_UPDATE = 17,
			},
			PvPColosseumGameType = {
				Invalid = 0,
				Crystal = 1,
				FrontLine = 2,
			},
			PvPColosseumMode = {
				Exercise = 0,
				Rank = 1,
				Custom = 2,
			},
			PvpColosseumBtlResultClass = {
				CurSeason = 0,
				LastSeason = 1,
				CurWeek = 2,
			},
			PvPColosseumBtlMtlType = {
				BMTInvalid = 0,
				BMTOverview = 1,
				BMTFrontLine = 2,
				BMTCrystal = 3,
				BMTSpecialSkill = 4,
				BMTFastChat = 5,
			},
			PvPColosseumUserDataKey = {
				PvPColosseumUserDataKeyPvPGame = 0,
				PvPColosseumUserDataKeyDuel = 1,
			},
		},
		Questionnaire = {
			Cmd = {
				Invalid = 0,
				QueryQuestionnaire = 1,
				TriggerQuestionnaire = 2,
				QuestionnaireValid = 3,
			},
		},
		TouringBand = {
			ReportType = {
				ReportNone = 0,
				Emotion = 1,
				Equip = 2,
				Companion = 3,
				Appearance = 4,
			},
			BandInteractStatus = {
				UnFinish = 0,
				Wait = 1,
				Finish = 2,
			},
			Cmd = {
				None = 0,
				QueryCollection = 1,
				QueryBandMapData = 2,
				BandCollectedUnlock = 3,
				BandInteractReport = 5,
				BandInteractFinish = 6,
				ClickBandEmotion = 7,
				BandBirthNotify = 8,
			},
		},
		TreasureHunt = {
			CmdTreasureHunt = {
				CmdTreasureHuntNone = 0,
				InterpretMap = 1,
				DigTreasure = 2,
				TreasureAward = 3,
				TreasureHuntInfo = 4,
				TreasureAllMap = 5,
				InterpretFinMap = 6,
				DigTreasureActNotify = 7,
				EnterTreasury = 8,
				TeleportInviteNotify = 9,
				OpenMapNotify = 10,
				MarkPointTreasureMap = 11,
				GuessCardStart = 12,
				GuessCardNotify = 13,
				NormalGameStart = 14,
				OpenWildBox = 15,
				DiscardMap = 16,
				CheckInterpretMap = 17,
				PreDigTreasure = 18,
				TreasurySpin = 19,
				GetGuessCardInfo = 20,
				TreasureDigFinNotify = 21,
			},
			TreasureHuntState = {
				TreasureNone = 0,
				Interpret_Map = 1,
				Dig_Box = 2,
				Dig_Box_Fin = 3,
				Open_Box = 4,
				Treasure_Fin = 5,
				Treasure_Award = 6,
			},
			NormalGameType = {
				GameTypeNone = 0,
				FairyGuide = 1,
				DesireTrap = 2,
			},
			ETreasureType = {
				Wild = 0,
				Aquapolis = 1,
				Sanctums = 2,
			},
			EOpsType = {
				OpsNone = 0,
				MarkPoint = 1,
				OpenMap = 2,
				CloseMap = 3,
			},
			EDigType = {
				DigNone = 0,
				PreStart = 1,
				Finish = 2,
			},
			TreasurehuntUserDataKey = {
				TreasurehuntUserDataKeyDefault = 0,
				TreasurehuntUserDataKeyRoulette = 1,
				TreasurehuntUserDataKeyAquapolis = 2,
				TreasurehuntUserDataKeyBox = 3,
			},
			EStatus = {
				EStatusClose = 0,
				EStatusCanOpen = 1,
				EStatusOpened = 2,
			},
		},
		WildBox = {
			Cmd = {
				None = 0,
				Update = 1,
				OpenBox = 2,
			},
		},
		ZeroSceneRank = {
			CS_ZEROSCENERANK_CMD = {
				INVALID = 0,
				ALLRANKS = 1,
			},
		},
	},
	CS_ADVENTURE_CMD = {
		CS_ADVENTURE_CMD_INVALID = 0,
		CS_ADVENTURE_CMD_CHALLENGE_LOG = 1,
		CS_ADVENTURE_CMD_CHALLENGE_LOG_REWARD = 2,
		CS_ADVENTURE_CMD_CHALLENGE_LOG_COLLECT = 3,
		CS_ADVENTURE_CMD_CHALLENGE_LOG_REWARD_COLLECT = 4,
	},
	CS_ALONE_TREE_CMD = {
		CS_ALONE_TREE_INVALID = 0,
		CS_ALONE_TREE_ENTER = 1,
		CS_ALONE_TREE_SELECT_DIFFICULTY = 2,
		CS_ALONE_TREE_CUT = 3,
		CS_ALONE_TREE_DOUBLE_CHANCE = 4,
		CS_ALONE_TREE_EXIT = 5,
	},
	ALONE_TREE_HAND_FEEL = {
		ALONE_TREE_HAND_FEEL_FAILED = 0,
		ALONE_TREE_HAND_FEEL_LITTLE = 1,
		ALONE_TREE_HAND_FEEL_WELL = 2,
		ALONE_TREE_HAND_FEEL_OK = 3,
	},
	ACTIVITY_TYPE = {
		ACTIVITY_TYPE_INVALID = 0,
		ACTIVITY_TYPE_ALONE_TREE = 1,
		ACTIVITY_TYPE_ORE_SEARCH = 2,
	},
	CS_AREA_CLEAN_CMD = {
		AREA_CLEAN_CMD_INVALID = 0,
		AREA_CLEAN_CMD_ENTER_RANGE = 1,
		AREA_CLEAN_CMD_EXIT_RANGE = 2,
		AREA_CLEAN_CMD_SYNC_PROGRESS = 3,
		AREA_CLEAN_CMD_REFRESH_EOBJ = 4,
	},
	UserDataKey = {
		UserDataKeyDefault = 0,
		AreaID = 1,
		PosID = 2,
	},
	CS_BAG_CMD = {
		CS_CMD_BAG_USE_ITEM = 0,
		CS_CMD_BAG_INFO = 1,
		CS_CMD_BAG_BUY = 2,
		CS_CMD_BAG_TRIM = 3,
		CS_CMD_BAG_SELL = 4,
		CS_CMD_BAG_UPDATE = 5,
		CS_CMD_BAG_DROP = 6,
		CS_CMD_BAG_TRANS_DEPOT = 7,
		CS_CMD_ITEM_CD = 8,
		CS_CMD_ITEM_CD_ALL = 9,
		CS_CMD_ITEM_RECYC = 10,
		CS_CMD_ITEM_BIND = 11,
		CS_CMD_ITEM_TOMQ = 12,
	},
	ITEM_USE_FROM = {
		ITEM_USE_FROM_BAG = 0,
		ITEM_USE_FROM_MAP = 1,
	},
	ITEM_UPDATE_TYPE = {
		ITEM_UPDATE_TYPE_ADD = 0,
		ITEM_UPDATE_TYPE_DELETE = 1,
		ITEM_UPDATE_TYPE_RENEW = 2,
	},
	BattlePass = {
		BattlePassCmd = {
			BattlePassCmdNone = 0,
			BattlePassCmdState = 1,
			BattlePassCmdLevel = 2,
			BattlePassCmdGetLevelReward = 3,
			BattlePassCmdTask = 4,
			BattlePassCmdGetTaskReward = 5,
			BattlePassCmdWeekSign = 6,
			BattlePassCmdExpChange = 7,
			BattlePassCmdGradeChange = 8,
			BattlePassCmdLevelUp = 9,
		},
		GradeType = {
			GradeNone = 0,
			GradeBasic = 1,
			GradeMiddle = 2,
			GradeUltimate = 3,
		},
		TaskType = {
			TaskNone = 0,
			TaskWeek = 1,
			TaskBattle = 2,
			TaskAll = 3,
		},
	},
	BonusStateCmd = {
		BonusStateCmdNone = 0,
		BonusStateCmdPull = 1,
		BonusStateCmdUpdate = 2,
		BonusStateCmdRemove = 3,
		BonusStateCmdPullByRoleID = 4,
	},
	BuddyCmd = {
		BuddyCmdQuery = 0,
		BuddyCmdCall = 1,
		BuddyCmdLearnSkill = 2,
		BuddyCmdAIOn = 3,
		BuddyCmdTrain = 4,
		BuddyCmdBroken = 5,
		BuddyCmdSkillReset = 6,
		BuddyCmdRename = 7,
		BuddyLevelExpUpdate = 8,
		BuddyFavFoodUpdate = 9,
		BuddyArmorRepoUpdate = 10,
		BuddyTimeUpdate = 11,
		BuddyBuffUpdate = 12,
	},
	BuddyAIStrategy = {
		AIStrategyFree = 0,
		AIStrategyFollow = 1,
		AIStrategyDefence = 2,
		AIStrategyHealth = 3,
		AIStrategyAttack = 4,
	},
	CatchBallCmd = {
		CatchBallInvalid = 0,
		CatchBallStart = 1,
		CatchBallCatch = 2,
		CatchBallDouble = 3,
		CatchBallExit = 4,
	},
	MogulBallType = {
		MogulBallTypeInvalid = 0,
		MogulBallTypeOrange = 1,
		MogulBallTypeBlue = 2,
		MogulBallTypeRed = 3,
	},
	CHANNEL_TYPE_DEFINE = {
		CHANNEL_TYPE_NONE = 0,
		CHANNEL_TYPE_NEWBIE = 1,
		CHANNEL_TYPE_ARMY = 2,
		CHANNEL_TYPE_AREA = 3,
		CHANNEL_TYPE_NEIGHBOUR = 4,
		CHANNEL_TYPE_TEAM = 5,
		CHANNEL_TYPE_PERSON = 6,
		CHANNEL_TYPE_GROUP = 7,
		CHANNEL_TYPE_SYSTEM = 8,
		CHANNEL_TYPE_SCENE_TEAM = 9,
		CHANNEL_TYPE_RECRUIT = 10,
		CHANNEL_TYPE_VANGUARD = 14,
		CHANNEL_TYPE_MAX = 15,
	},
	CS_CHAT_CMD = {
		CS_CHAT_CMD_NONE = 0,
		CS_CHAT_CMD_MSG_PUSH = 1,
		CS_CHAT_CMD_MSG_PULL = 2,
		CS_CHAT_CMD_CHANNEL_HAVE_READ = 3,
		CS_CHAT_CMD_SET_CHANNEL_HAVE_READ = 4,
		CS_CHAT_CMD_HREF_DETAIL = 5,
		CS_CHAT_CMD_MSG_SEQ_NOTIFY = 7,
		CS_CHAT_CMD_MSG_DETAIL_NOTIFY = 8,
		CS_CHAT_CMD_CHANNEL_UPDATE_NOTIFY = 9,
		CS_CHAT_CMD_PRIVATE_CHAT_MSG_NTF = 10,
		CS_CHAT_CMD_DELETE_ROLE_MSG = 11,
		CS_CHAT_CMD_UPDATE_CLIENT_SETUP = 13,
		CS_CHAT_CMD_GET_CLIENT_SETUP = 14,
		CS_CHAT_CMD_QUERY_MEMBER = 15,
		CS_CHAT_CMD_ACTIVE_ROLE = 16,
		CS_CHAT_CMD_QUERY_UNLOCK_GIF = 17,
		CS_CHAT_CMD_UNLOCK_GIF_NOFITY = 18,
		CS_CHAT_CMD_VANGUARD_INFO = 19,
		CS_CHAT_CMD_VANGUARD_JOIN = 20,
		CS_CHAT_CMD_VANGUARD_QUIT = 21,
		CS_CHAT_CMD_VANGUARD_NOTIFY = 22,
	},
	FailReason = {
		ReasonOK = 0,
		ReasonBlockStranger = 1,
		ReasonBan = 2,
	},
	NOTIFY_UPDATE_TYPE = {
		CHANNEL_JOIN_TYPE = 0,
		CHANNEL_QUIT_TYPE = 1,
	},
	PARAM_TYPE_DEFINE = {
		PARAM_TYPE_DEFINE_SYSTEM = 0,
		PARAM_TYPE_DEFINE_ITEM = 1,
		PARAM_TYPE_DEFINE_TASK = 2,
		PARAM_TYPE_DEFINE_EMOTION = 3,
		PARAM_TYPE_DEFINE_VOICE = 4,
		PARAM_TYPE_DEFINE_MAP = 5,
		PARAM_TYPE_DEFINE_NEWBIE = 6,
		PARAM_TYPE_DEFINE_GIF = 7,
		PARAM_TYPE_DEFINE_SPC_TIPS = 8,
		PARAM_TYPE_DEFINE_TEAM_RECRUIT = 9,
		PARAM_TYPE_DEFINE_TEAM_TREASUREHUNT = 10,
		PARAM_TYPE_DEFINE_ACHIEVEMENT_SHARE = 11,
	},
	SPECIAL_SYSTEM_MSG_ID = {
		SPECIAL_SYSTEM_MSG_ID_NONE = 0,
		SPECIAL_SYSTEM_MSG_ID_EMOTION = 10005,
		SPECIAL_SYSTEM_MSG_ID_GET_GOODS = 10008,
	},
	SPECIAL_TIPS_TYPE = {
		ACCEPT_FRIEND_APPLY = 0,
		CLOSED_TASK_NOTIFY = 1,
		RENAME = 2,
		APPLY_FRIEND_SUC = 3,
	},
	ChocoboCmd = {
		ChocoboCmdInvalid = 0,
		ChocoboCmdQuery = 1,
		ChocoboCmdQuerySkillList = 2,
		ChocoboCmdLearnSkill = 3,
		ChocoboCmdSkillOp = 4,
		ChocoboCmdMating = 5,
		ChocoboCmdMatingReceive = 6,
		ChocoboCmdRentInfo = 7,
		ChocoboCmdRentRefresh = 8,
		ChocoboCmdRent = 9,
		ChocoboCmdLike = 10,
		ChocoboCmdFree = 11,
		ChocoboCmdRename = 12,
		ChocoboCmdDyeColor = 13,
		ChocoboCmdArmor = 14,
		ChocoboCmdGetSuitProcessAward = 15,
		ChocoboCmdGetPartProcessAward = 16,
		ChocoboCmdGetSuitCollected = 17,
		ChocoboCmdReduceCD = 18,
		ChocoboCmdUsedColor = 19,
		ChocoboCmdUsedArmor = 20,
		ChocoboCmdOut = 21,
		ChocoboCmdQueryMatchChocobo = 22,
		ChocoboCmdUpdateNotify = 23,
		ChocoboCmdArmorRepoUpdate = 24,
		ChocoboCmdQueryTitle = 25,
		ChocoboCmdGetTitleAward = 26,
		ChocoboCmdGetMissionAward = 27,
		ChocoboCmdLevelUpNotify = 28,
		ChocoboCmdAdopt = 29,
		ChocoboCmdGetNewbieChocobo = 30,
	},
	ChocoboAttrType = {
		ChoAttrMaxSpeed = 0,
		ChoAttrSprint = 1,
		ChoAttrAcc = 2,
		ChoAttrAdapt = 3,
		ChoAttrAbility = 4,
	},
	ChocoboStatus = {
		StatusNull = 0,
		StatusNormal = 1,
		StatusLike = 2,
		StatusMating = 3,
	},
	SkillOp = {
		OpInvalid = 0,
		OpEquip = 1,
		OpRemove = 2,
		OpReplace = 3,
	},
	ChocoboDyeType = {
		ChocoboDyeTypeInvalid = 0,
		ChocoboDyeTypeNormal = 1,
		ChocoboDyeTypeFast = 2,
		ChocoboDyeTypeSpecial = 3,
	},
	ChocoboArmorPos = {
		ChocoboArmorPosHead = 0,
		ChocoboArmorPosBody = 1,
		ChocoboArmorPosLeg = 2,
	},
	ChocoboTransferCmd = {
		ChocoboTransferCmdInvalid = 0,
		ChocoboTransferCmdQuery = 1,
		ChocoboTransferCmdBook = 2,
		ChocoboTransferCmdTransfer = 3,
		ChocoboTransferCmdEnd = 4,
	},
	ReportType = {
		ReportTypeEnterCutScenes = 0,
		ReportTypeQuitCutScenes = 1,
		ReportTypeEnterTakePhotos = 2,
		ReportTypeQuitTakePhotos = 3,
		ReportTypeRoleLeave = 4,
		ReportTypeRoleComeBack = 5,
		ReportTypeBandListen = 6,
		ReportTypeRecollect = 7,
		ReportTypeTakePhotos = 8,
	},
	CsClosetCmd = {
		CS_CLOSET_INVALID = 0,
		CS_CLOSET_QUERY = 1,
		CS_CLOSET_UNLOCK = 2,
		CS_CLOSET_CLOTHING = 3,
		CS_CLOSET_COLLECT = 4,
		CS_CLOSET_DYE_UNLOCK = 5,
		CS_CLOSET_SUIT_ENLARGE = 6,
		CS_CLOSET_SUIT_RENAME = 7,
		CS_CLOSET_SUIT_SAVE = 8,
		CS_CLOSET_SUIT_LINK_PROF = 9,
		CS_CLOSET_ACTIVE_STAIN = 10,
		CS_CLOSET_DYE = 11,
		CS_CLOSET_CHARISM_REWARD = 12,
		CS_CLOSET_DYE_RECOVERY = 13,
		CS_CLOSET_CHOOSESUIT = 14,
		CS_CLOSET_UNCLOTHING = 15,
		CS_CLOSET_ACTIVE_COLOR = 16,
		CS_CLOSET_QUERY_UNLOCK = 17,
		CS_CLOSET_APPEAR_NOTIFY = 18,
		CS_CLOSET_RANDOM_PATTERN = 19,
		Cs_CLOSET_REGION_DYE = 20,
		CS_CLOSET_USED_STAIN_QUERY = 21,
		CS_CLOSET_USED_STAIN_SAVE = 22,
		CS_CLOSET_QUERY_PART_UNLOCK = 23,
		CS_CLOSET_SUIT_CLOTHING = 24,
	},
	GenderLimit = {
		GENDER_ALL = 0,
		GENDER_MALE = 1,
		GENDER_FEMALE = 2,
	},
	CS_COLLECT_CMD = {
		CS_CMD_COLLECT_NONE = 0,
		CS_CMD_COLLECT_EXCHANGE = 1,
		CS_CMD_COLLECT_RECORD = 2,
	},
	CS_COLOSSEUM_COMBAT_CMD = {
		CS_COLOSSEUM_COMBAT_CMD_NONE = 0,
		CS_COLOSSEUM_COMBAT_CMD_BUNDLE = 1,
		CS_COLOSSEUM_COMBAT_CMD_SEQUENCE = 2,
		CS_COLOSSEUM_COMBAT_CMD_TEAM = 3,
		CS_COLOSSEUM_COMBAT_CMD_CRYSTAL = 4,
		CS_COLOSSEUM_COMBAT_CMD_EVENT_NOTIFY = 5,
		CS_COLOSSEUM_COMBAT_CMD_VISION_INFO = 6,
	},
	ColosseumSequence = {
		COLOSSEUM_PHASE_NONE = 0,
		COLOSSEUM_PHASE_INIT = 1,
		COLOSSEUM_PHASE_WAIT = 2,
		COLOSSEUM_PHASE_REGULAR = 3,
		COLOSSEUM_PHASE_OVERTIME = 4,
		COLOSSEUM_PHASE_END = 5,
		COLOSSEUM_PHASE_RESULT = 6,
	},
	CrystalStatus = {
		CRYSTAL_STATUS_NONE = 0,
		CRYSTAL_STATUS_BINDING = 1,
		CRYSTAL_STATUS_RELEASE = 2,
		CRYSTAL_STATUS_DESTINATION_CENTER = 3,
		CRYSTAL_STATUS_DESTINATION_ASTRA = 4,
		CRYSTAL_STATUS_DESTINATION_UMBRA = 5,
		CRYSTAL_STATUS_DESTINATION_DEADLOCK = 6,
		CRYSTAL_STATUS_ASTRA_BREAKING = 7,
		CRYSTAL_STATUS_UMBRA_BREAKING = 8,
		CRYSTAL_STATUS_IDLE = 9,
	},
	EventType = {
		EVENT_TYPE_NONE = 0,
		EVENT_TYPE_ERUPTION_WARNING = 1,
		EVENT_TYPE_GUST_WARNING = 2,
		EVENT_TYPE_KO = 4,
		EVENT_TYPE_CRYSTAL_LEAVE_WARNING = 5,
		EVENT_TYPE_NOT_ENOUGH_PLAYERS = 6,
	},
	CS_COMBAT_CMD = {
		CS_COMBAT_CMD_INVALID = 0,
		CS_COMBAT_CMD_SING = 1,
		CS_COMBAT_CMD_ACTION = 2,
		CS_COMBAT_CMD_ATTACK = 3,
		CS_COMBAT_CMD_CD_LIST = 4,
		CS_COMBAT_CMD_CD = 5,
		CS_COMBAT_CMD_UPDATE_BUFF = 6,
		CS_COMBAT_CMD_SYNC_BUFF = 7,
		CS_COMBAT_CMD_REMOVE_BUFF = 8,
		CS_COMBAT_CMD_EFFECT = 9,
		CS_COMBAT_CMD_ATTR_UPDATE = 10,
		CS_COMBAT_CMD_QUIT_ACTION = 11,
		CS_COMBAT_CMD_STORAGE_BEGIN = 12,
		CS_COMBAT_CMD_UPDATE_PERDUE_SKILL = 13,
		CS_COMBAT_CMD_SYNC_PERDUE_SKILL = 14,
		CS_COMBAT_CMD_REMOVE_PERDUE_SKILL = 15,
		CS_COMBAT_CMD_SPECTRUM_ON = 16,
		CS_COMBAT_CMD_SPECTRUM_OFF = 17,
		CS_COMBAT_CMD_SPECTRUM_SUCC = 18,
		CS_COMBAT_CMD_SPECTRUM_RESOURCE_UPDATE = 19,
		CS_COMBAT_CMD_STAT_UPDATE = 20,
		CS_COMBAT_CMD_GET_ENMITY_LIST = 21,
		CS_COMBAT_CMD_SKILL_REPLACE = 22,
		CS_COMBAT_CMD_SKILL_BREAK = 23,
		CS_COMBAT_CMD_UPDATE_CHARGE = 24,
		CS_COMBAT_CMD_SYNC_CHARGE_LIST = 25,
		CS_COMBAT_CMD_QUERY_ALL_ATTRS = 26,
		CS_COMBAT_CMD_RESET_SKILL_SERIES = 27,
		CS_COMBAT_CMD_QUIT_SING = 28,
		CS_COMBAT_CMD_QUERY_CAMP = 29,
		CS_COMBAT_CMD_QUERY_RELATE_ENMITY_LIST = 30,
		CS_COMBAT_CMD_BUFF_STATUS_CHG = 31,
		CS_COMBAT_CMD_UPDATE_SPECTRUM_LIMIT = 32,
		CS_COMBAT_CMD_SYNC_PLAYER_STATUS = 33,
		CS_COMBAT_CMD_SYNC_LIMIT_BREAK = 34,
		CS_COMBAT_CMD_SYNC_SKILL_RES = 35,
		CS_COMBAT_CMD_PERFORM_SKILL = 36,
		CS_COMBAT_CMD_CAST_PERFORM_ACTION = 37,
		CS_COMBAT_CMD_SYNC_PERFORM_POS = 38,
		CS_COMBAT_CMD_REVISE_SKILL = 39,
		CS_COMBAT_CMD_LIMIT_BREAK_FINPLAY = 40,
		CS_COMBAT_CMD_SYNC_SPECTRUM = 41,
		CS_COMBAT_CMD_QUERY_SKILLLIST = 42,
		CS_COMBAT_CMD_QUERY_SKILL_REVISE = 43,
		CS_COMBAT_CMD_STORAGE_END = 44,
		CS_COMBAT_CMD_CLEAR_ALL_CD = 45,
		CS_COMBAT_CMD_SUBSCRIBE_ENMITY_CHANGES = 46,
		CS_COMBAT_CMD_CANCEL_SUBSCRIBE_ENMITY_CHANGES = 47,
		CS_COMBAT_CMD_BATCH_COMBAT_PKG = 48,
		CS_COMBAT_CMD_SPECTRUM_CHANGE_VALUE = 49,
		CS_COMBAT_CMD_ENTITY_DIE_NTF = 50,
		CS_COMBAT_CMD_LIMIT_BREAK_BEGIN = 51,
		CS_COMBAT_CMD_LIMIT_BREAK_FINISH = 52,
		CS_COMBAT_CMD_NOTIFY_SELF_ENMITY_LIST = 53,
		CS_COMBAT_CMD_NOTIFY_IS_FORBID_PERDUE_SKILL = 54,
		CS_COMBAT_CMD_NOTIFY_IS_FORBID_SPECTRUM_SKILL = 55,
	},
	SkillRangeType = {
		SRT_NONE = 0,
		SRT_CIRCLE = 1,
		SRT_AABB = 3,
		SRT_SECTOR = 4,
		SRT_SPHERE = 7,
		SRT_AABB_STRIP = 8,
	},
	BUFF_ADD_REASON = {
		OTHER = 0,
		SKILL = 1,
		LEVEL = 2,
		BUFF = 3,
		BIRTH = 4,
	},
	CS_ATTACK_EFFECT = {
		CS_ATTACK_EFFECT_NULL = 0,
		CS_ATTACK_EFFECT_FLASH_MOVE = 1,
		CS_ATTACK_EFFECT_HP_DAMAGE = 2,
		CS_ATTACK_EFFECT_HP_HEAL = 3,
		CS_ATTACK_EFFECT_BLOOD_DRAIN = 4,
		CS_ATTACK_EFFECT_MP_DAMAGE = 5,
		CS_ATTACK_EFFECT_MP_HEAL = 6,
		CS_ATTACK_EFFECT_PARRY = 7,
		CS_ATTACK_EFFECT_MISS = 8,
		CS_ATTACK_EFFECT_DODGE = 9,
		CS_ATTACK_EFFECT_SUPERMAN = 10,
		CS_ATTACK_EFFECT_BREAK = 11,
		CS_ATTACK_EFFECT_IMMUNE = 12,
		CS_ATTACK_EFFECT_ABSORB = 13,
		CS_ATTACK_EFFECT_REVIVE = 14,
		CS_ATTACK_EFFECT_CALL = 15,
		CS_ATTACK_EFFECT_SKILL_ACT = 16,
		CS_ATTACK_EFFECT_REBOUND_DAMAGE = 17,
		CS_ATTACK_EFFECT_CRITICAL = 18,
		CS_ATTACK_EFFECT_DIRECT_ATK = 19,
		CS_ATTACK_EFFECT_BLOW_OFF = 20,
		CS_ATTACK_EFFECT_PUSH = 21,
		CS_ATTACK_EFFECT_PULL = 22,
		CS_ATTACK_EFFECT_SKATE = 23,
		CS_ATTACK_EFFECT_SHIELD_COST = 24,
		CS_ATTACK_EFFECT_CHARGE = 25,
		CS_ATTACK_EFFECT_ATTR_HP = 26,
		CS_ATTACK_EFFECT_ATTR_MP = 27,
		CS_ATTACK_EFFECT_ATTACH_HP_DAMAGE = 28,
		CS_ATTACK_EFFECT_ATTACK_INVALID = 29,
		CS_ATTACK_EFFECT_BUFF_TRANSFER = 30,
		CS_ATTACK_EFFECT_FLOAT_AIR = 31,
	},
	CS_SKILL_REPLACE_TYPE = {
		CS_SKILL_REPLACE_TYPE_BACK = 0,
		CS_SKILL_REPLACE_TYPE_NORMAL = 1,
		CS_SKILL_REPLACE_TYPE_ENHANCE = 2,
	},
	PLAYER_SYNC_TYPE = {
		PLAYER_SKILL = 0,
	},
	skill_perform_status = {
		SKILL_PERFORM_STATUS_NULL = 0,
		SKILL_PERFORM_STATUS_ON = 1,
		SKILL_PERFORM_STATUS_OFF = 2,
	},
	revise_skill_type = {
		REVISE_SKILL_NULL = 0,
		REVISE_SKILL_SING = 1,
		REVISE_SKILL_ACTION = 2,
		REVISE_SKILL_CD = 3,
	},
	CompanionCmd = {
		CompanionCmdNone = 0,
		CompanionCmdQuery = 1,
		CompanionCmdCall = 2,
		CompanionCmdOps = 3,
		CompanionCmdActivateNotify = 4,
		CompanionCmdActionNotify = 5,
		CompanionCmdExpNotify = 6,
		CompanionCmdCallNotify = 11,
	},
	CompanionFlag = {
		CompanionFlagNew = 0,
		CompanionFlagLike = 1,
		CompanionFlagArchiveNew = 2,
	},
	CompanionAuto = {
		CompanionAutoNone = 0,
		CompanionAutoLast = 1,
		CompanionAutoAll = 2,
		CompanionAutoLike = 3,
	},
	CompanionOps = {
		CompanionOpsRead = 0,
		CompanionOpsLike = 1,
		CompanionOpsUnlike = 2,
		CompanionOpsAuto = 3,
		CompanionOpsArchiveRead = 4,
	},
	CS_COUNTER_CMD = {
		INVALID = 0,
		LIST = 1,
		UPDATE_NOTIFY = 2,
		CLEAR = 3,
	},
	CrystalTowerCmd = {
		CrystalTowerCmdInvalid = 0,
		CrystalTowerCmdEnter = 1,
		CrystalTowerCmdInteraction = 2,
		CrystalTowerCmdExit = 3,
	},
	CS_COMM_STAT_CMD = {
		CS_COMM_STAT_CMD_NOTIFY = 0,
		CS_COMM_STAT_CMD_LEAVE = 1,
		CS_COMM_STAT_CMD_STATUS = 2,
		CS_COMM_STAT_CMD_CONTROL = 3,
	},
	CommStatControlOP = {
		CommStatControlOP_NONE = 0,
		CommStatControlOP_SET = 1,
		CommStatControlOP_CLEAR = 2,
	},
	CSErrCode = {
		ERRORCODE_NOERROR = 0,
		ERRORCODE_Unknown = 1,
		ERRORCODE_FRIENDS_OPtTooOften = 1000,
		ERRORCODE_FRIENDS_NoThisFriends = 1001,
		ERRORCODE_FRIENDS_CanNotAddSelf = 1002,
		ERRORCODE_FRIENDS_AlreadyFriend = 1003,
		ERRORCODE_FRIENDS_TheListIsFull = 1004,
		ERRORCODE_FRIENDS_DeleteSelf = 1005,
		ERRORCODE_FRIENDS_MoveInSelf = 1006,
		ERRORCODE_FRIENDS_PreRmFriends = 1007,
		ERRORCODE_FRIENDS_AlreadyInBlackList = 1008,
		ERRORCODE_FRIENDS_ReqConsortListMax = 1009,
		ERRORCODE_FRIENDS_AlreadyInConsortList = 1010,
		ERRORCODE_FRIENDS_NOTINCONSORTLIST = 1011,
	},
	CS_MAP_AREA_CMD = {
		CS_MAP_AREA_CMD_INVALID = 0,
		CS_MAP_AREA_CMD_ENTER = 1,
	},
	CS_NPC_CMD = {
		CS_CMD_NPC_INVALID = 0,
		CS_CMD_NPC_RUN = 1,
	},
	PerformActionCmd = {
		CS_PERFORM_ACTION_CMD_INVALID = 0,
		CS_PERFORM_ACTION_CMD_YELL = 1,
		CS_PERFORM_ACTION_CMD_ACTION_TIME_LINE = 2,
		CS_PERFORM_ACTION_CMD_LINE_VOICE = 3,
	},
	CS_REVIVE_CMD = {
		CS_REVIVE_CMD_INVALID = 0,
		CS_REVIVE_CMD_NOTIFY = 1,
		CS_REVIVE_CMD_READY = 2,
		CS_REVIVE_CMD_CONFIRM = 3,
		CS_REVIVE_CMD_INFO = 4,
		CS_REVIVE_CMD_TRANS = 5,
		CS_REVIVE_CMD_RESCUE = 6,
	},
	CS_TARGET_CMD = {
		CS_TARGET_CMD_NOTIFY = 0,
		CS_TARGET_CMD_SET = 1,
		CS_TARGET_CMD_GET = 2,
	},
	CS_VISION_CMD = {
		CS_VISION_CMD_INVALID = 0,
		CS_VISION_CMD_ENTER = 1,
		CS_VISION_CMD_LEAVE = 2,
		CS_VISION_CMD_QUERY = 3,
		CS_VISION_CMD_MONSTER_ID_CHG = 4,
		CS_VISION_CMD_MONSTER_FACADE_CHG = 5,
		CS_VISION_CMD_MONSTER_FIRSTATTACKER_CHG = 6,
		CS_VISION_CMD_TEAM_FLAG_CHG = 7,
		CS_VISION_CMD_AVATAR_CHG = 8,
		CS_VISION_CMD_IN_COMBAT_CHG = 9,
		CS_VISION_CMD_CAMP_CHG = 10,
		CS_VISION_CMD_PROF_CHG = 11,
		CS_VISION_CMD_LEVEL_CHG = 12,
		CS_VISION_CMD_GATHERATTR_CHG = 13,
		CS_VISION_CMD_SPELL_CHG = 14,
		CS_VISION_CMD_BIND_CHG = 15,
		CS_VISION_CMD_CLIENT_CFG_CHG = 16,
		CS_VISION_CMD_AVATAR_SYNC = 17,
		CS_VISION_CMD_EOBJ_CHG = 18,
		CS_VISION_CMD_CHOCOBO_CHG = 19,
		CS_VISION_CMD_EOBJ_VISIBILITY = 20,
		CS_VISION_CMD_USER_DATA_CHG = 21,
	},
	VROLE_TEAM_FLAG = {
		VROLE_FLAG_TEAM_NONE = 0,
		VROLE_FLAG_TEAM_MEMBER = 1,
		VROLE_FLAG_TEAM_CAPTAIN = 2,
	},
	MonsterCreateWay = {
		MonsterCreateWayRefresh = 0,
		MonsterCreateWayEvent = 1,
		MonsterCreateWayDynamic = 2,
	},
	VBNpcType = {
		VBNpcTypeNone = 0,
		VBNpcTypeFaith = 1,
		VBNpcTypeBuddy = 2,
		VBNpcTypeMonster = 3,
	},
	VisionEnterFlag = {
		VisionEnterFlagInvalid = 0,
		VisionEnterFlagNewBorn = 0,
		VisionEnterFlagCombat = 0,
	},
	VDataType = {
		DisplayTag = 0,
		Guide = 1,
		Title = 2,
		GroupName = 3,
	},
	CS_DEBUG_CMD = {
		CS_DEBUG_CMD_NONE = 0,
		CS_DEBUG_CMD_AI_INFO_GET = 1,
		CS_DEBUG_CMD_SKILL_INFO_GET = 2,
	},
	depot_type = {
		DEPOT_TYPE_DEFAULT = 0,
		DEPOT_TYPE_TOOL = 1,
		DEPOT_TYPE_MATERIAL = 2,
		DEPOT_TYPE_FOOD = 3,
		DEPOT_TYPE_ARM = 4,
		DEPOT_TYPE_ARMOR = 5,
		DEPOT_TYPE_ORNAMENTS = 6,
		DEPOT_TYPE_OTHER = 7,
	},
	CS_DEPOT_CMD = {
		CS_DEPOT_CMD_NONE = 0,
		CS_DEPOT_CMD_SIMPLE_INFO = 1,
		CS_DEPOT_CMD_DETAIL_INFO = 2,
		CS_DEPOT_CMD_TRANSFER = 3,
		CS_DEPOT_CMD_MOVE = 4,
		CS_DEPOT_CMD_RENAME = 5,
		CS_DEPOT_CMD_ENLARGE = 6,
		CS_DEPOT_CMD_TRIM = 7,
		CS_DEPOT_CMD_UPDATE = 8,
	},
	update_type = {
		UPDATE_TYPE_ADD = 0,
		UPDATE_TYPE_DELETE = 1,
		UPDATE_TYPE_RENEW = 2,
	},
	Role = {
		DirectUpgrade = {
			Cmd = {
				Invalid = 0,
				Upgrade = 1,
				Update = 2,
				AdventureReward = 3,
				ReadyUpgrade = 4,
			},
		},
		Exchange = {
			ExchangeCmd = {
				ExchangeCmdNone = 0,
				ExchangeCmdCommon = 1,
			},
		},
		FashionDecorate = {
			CsFashionDecorateCmd = {
				CsFashionDecorateInvalid = 0,
				CsFashionDecorateQuery = 1,
				CsFashionDecorateClothing = 2,
				CsFashionDecorateUnClothing = 3,
				CsFashionDecorateCollect = 4,
				CsFashionDecorateCall = 5,
				CsFashionDecorateShowNotify = 6,
				CsFashionDecorateRead = 7,
				CsFashionDecorateUnlock = 8,
				CsFashionDecoratePlay = 9,
			},
			FashionDecorateType = {
				FashionDecorateNone = 0,
				FashionDecorateUmbrella = 1,
				FashionDecorateWing = 2,
			},
			FashionDecorateChooseType = {
				FashionDecorateUseByNone = 0,
				FashionDecorateUseByRand = 1,
				FashionDecorateUseByLike = 2,
				FashionDecorateUseByLast = 3,
			},
			FashionDecorateBitmap = {
				FashionDecorateStart = 0,
				FashionDecorateLast = 1,
				FashionDecorateNew = 4,
			},
		},
		GrandCompany = {
			GrandCompanyCmd = {
				GrandCompanyCmdNone = 0,
				GrandCompanyCmdState = 1,
				GrandCompanyCmdMilitaryUpgrade = 2,
				GrandCompanyCmdTransferCompany = 3,
				GrandCompanyCmdPrepareTask = 4,
				GrandCompanyCmdFinishPrepareTask = 5,
				GrandCompanyCmdJoinCompany = 6,
				GrandCompanyCmdExchangeCompanySeal = 7,
			},
			GrandCompanyType = {
				GrandCompanyNone = 0,
				GrandCompanyMaelstrom = 1,
				GrandCompanyTwinAdder = 2,
				GrandCompanyImmortalFlames = 3,
			},
			GrandCompanyPrepareTaskType = {
				PrepareTaskNone = 0,
				PrepareTaskMilitaryNeed = 1,
				PrepareTaskMilitarySupply = 2,
				PrepareTaskMilitaryAll = 3,
			},
			PrepareTaskState = {
				StateUnFinish = 0,
				StateFinished = 1,
			},
		},
		HeaderFrame = {
			CsHeaderFrameCmd = {
				CsHeaderFrameInvalid = 0,
				CsHeaderFrameQuery = 1,
				CsHeaderFrameUse = 2,
				CsHeaderFrameNotify = 3,
			},
		},
		LightJourney = {
			LightJourneyCmd = {
				CmdNone = 0,
				CmdTotalValue = 1,
				CmdPersonalityValue = 2,
			},
			JourneyGameID = {
				GameIDNone = 0,
				GameIDFate = 1,
				GameIDCloset = 2,
				GameIDGoldSauser = 3,
				GameIDMakerNote = 4,
				GameIDGatherNote = 5,
				GameIDFisherNote = 6,
				GameIDCombatProf = 7,
			},
		},
		Photos = {
			PhotosOptCmd = {
				PhotosSave = 0,
				PhotosGet = 1,
				PhotosDelete = 2,
			},
		},
		Portrait = {
			PersonalPortraitOptCmd = {
				PersonalPortrait_Save = 0,
				PersonalPortrait_Get = 1,
				PersonalPortrait_GetResList = 2,
				PersonalPortrait_UpdateProfAppear = 3,
				PersonalPortrait_Remove = 4,
				PersonalPortrait_SaveDataList = 5,
				PersonalPortrait_ChangeNotify = 6,
				PersonalPortrait_UnlockResNotify = 7,
				PersonalPortrait_GetAppear = 8,
			},
			PortraitResState = {
				PortraitResStateNone = 0,
				PortraitResStateUnknown = 1,
				PortraitResStateLock = 2,
				PortraitResStateUnlock = 3,
			},
			HeadPortraitOptCmd = {
				HeadPortrait_Get = 0,
				HeadPortrait_Save = 1,
				HeadPortrait_Set = 2,
				HeadPortrait_Delete = 3,
			},
			HeadType = {
				DEFAULT = 0,
				CUSTOM = 1,
			},
			IsSet = {
				NO = 0,
				NEED = 1,
			},
		},
		Search = {
			CsSubMsgIDSearch = {
				CsSubMsgIDSearchUnknown = 0,
				CsSubMsgIDSearchFriend = 1,
			},
			SearchFriendType = {
				SearchFriendUnknown = 0,
				SearchFriendRoleID = 1,
				SearchFriendName = 2,
				SearchFriendDim = 3,
			},
		},
		SummonBeast = {
			SummonBeastCmd = {
				SummonBeastCmdNone = 0,
				SummonBeastCmdCallBack = 1,
			},
		},
		Tribe = {
			TribeCmd = {
				TribeCmdNone = 0,
				TribeCmdQuestList = 1,
				TribeCmdQuestAccept = 2,
				TribeCmdInfo = 3,
				TribeCmdFriendUpdate = 4,
			},
		},
	},
	EmotionSubMsg = {
		EmotionSubMsgStart = 0,
		EmotionSubMsgEnter = 1,
		EmotionSubMsgNotify = 2,
		EmotionSubMsgLeave = 3,
		EmotionSubMsgQuery = 4,
		EmotionSubMsgActive = 5,
		EmotionSubMsgQueryStat = 6,
		EmotionSubMsgLike = 7,
	},
	EmotionType = {
		EmotionTypeAll = 0,
		EmotionTypeLast = 1,
		EmotionTypeStat = 2,
	},
	EmotionTargetType = {
		EmotionTargetTypeEntity = 0,
		EmotionTargetTypeListID = 1,
		EmotionTargetTypeListNpc = 2,
		EmotionTargetTypeListEObj = 3,
		EmotionTargetTypeListCompanion = 4,
		EmotionTargetTypeMountFacade = 5,
	},
	Entourage = {
		EntourageCmd = {
			EntourageInvalid = 0,
			EntouragePrepare = 1,
		},
	},
	CS_EQUIP_CMD = {
		CS_CMD_EQUIP_ON = 0,
		CS_CMD_EQUIP_OFF = 1,
		CS_CMD_EQUIP_GEM_INLAY = 3,
		CS_CMD_EQUIP_GEM_UNINLAY = 4,
		CS_CMD_EQUIP_REPAIR = 5,
		CS_CMD_EQUIP_INFO = 6,
		CS_CMD_EQUIP_IMPROVE = 11,
		CS_CMD_EQUIP_EXCHANGE_RECEIPT = 12,
	},
	Rpc = {
		FGame = {
			Externalserviceagent = {
			},
			Role = {
				CS_VISION_CMD = {
					CS_VISION_CMD_INVALID = 0,
					CS_VISION_CMD_LEVEL_CHG = 12,
				},
			},
			Profile = {
			},
		},
	},
	CsFaceCmd = {
		CSFACE_CMD_INVALID = 0,
		CSFACE_CMD_SAVE = 1,
		CSFACE_CMD_GET = 2,
	},
	FairyColorState = {
		StateNone = 0,
		StateNotBuy = 1,
		StateWait = 2,
		StateExchange = 3,
		StateExpired = 4,
		StateReceived = 5,
	},
	FairyColorStatus = {
		FairyColorStatusNone = 0,
		FairyColorStatusWait = 1,
		FairyColorStatusAfoot = 2,
	},
	FairyColorPlayerStatus = {
		FairyColorPlayerNone = 0,
		FairyColorPlayerNotBuy = 1,
		FairyColorPlayerWait = 2,
		FairyColorPlayerExchange = 3,
		FairyColorPlayerExpired = 4,
	},
	FairyColorRewardType = {
		TypeNone = 0,
		Value = 1,
		Scale = 2,
	},
	FairyColorReportType = {
		FairyColorReportType_None = 0,
		FairyColorReportType_LotteryEffect = 1,
		FairyColorReportType_ExchangeExpired = 2,
	},
	FairyColorGameCmd = {
		CmdNone = 0,
		QueryBase = 1,
		BuyGuessNumber = 2,
		QueryLotteryResult = 4,
		ExchangeReward = 5,
		QueryWinningList = 6,
		QueryRewardBonus = 7,
		ExchangeCoupons = 8,
		PlayEffect = 9,
		PushStage = 10,
		PushReward = 11,
		LastBuyNumbers = 12,
		QueryProgress = 14,
		EndPlayDynamic = 15,
		StartRaffle = 16,
		EndRaffle = 17,
		StartJoinPrize = 18,
		EndJoinPrize = 19,
	},
	FANTASY_CARD_OP = {
		FANTASY_CARD_OP_INVALID = 0,
		FANTASY_CARD_OP_RECOVER = 1,
		FANTASY_CARD_OP_ENTER = 3,
		FANTASY_CARD_OP_NEW_MOVE = 5,
		FANTASY_CARD_OP_FINISH = 6,
		FANTASY_CARD_OP_SELECT = 2,
		FANTASY_CARD_OP_EDIT = 7,
		FANTASY_CARD_OP_VIEW_GROUP = 8,
		FANTASY_CARD_OP_UPDATE_COLLECTION = 10,
		FANTASY_CARD_OP_UPDATE_NPC = 11,
		FANTASY_CARD_OP_COLLECTION_ROLE_COUNT = 12,
		FANTASY_CARD_OP_COLLECTION_PROGRESS_AWARD = 13,
		FANTASY_CARD_OP_COLLECTION_AWARD_RECORD = 23,
		FANTASY_CARD_OP_TOURNAMENT_INFO = 14,
		FANTASY_CARD_OP_TOURNAMENT_SIGNUP = 15,
		FANTASY_CARD_OP_TOURNAMENT_MATCH = 16,
		FANTASY_CARD_OP_TOURNAMENT_CANCEL_MATCH = 17,
		FANTASY_CARD_OP_TOURNAMENT_AWARD = 18,
		FANTASY_CARD_OP_TOURNAMENT_RANK = 19,
		FANTASY_CARD_OP_TOURNAMENT_CHOOSE = 20,
		FANTASY_CARD_OP_TOURNAMENT_MATCH_DONE = 21,
		FANTASY_CARD_OP_TOURNAMENT_MATCH_CONFIRM = 22,
		FANTASY_CARD_OP_TOURNAMENT_OPPONENT_LEAVE = 24,
		FANTASY_CARD_OP_TOURNAMENT_EFFECT_REROLL = 26,
		FANTASY_CARD_OP_ROOM_UPDATE = 25,
	},
	FLIP_MOVEMENT = {
		FLIP_MOVEMENT_NONE = 0,
		FLIP_MOVEMENT_LEVEL = 1,
		FLIP_MOVEMENT_VERTICAL = 2,
	},
	BATTLE_RESULT = {
		BATTLE_RESULT_WIN = 0,
		BATTLE_RESULT_FAIL = 1,
		BATTLE_RESULT_TIE = 2,
	},
	BATTLE_GROUP = {
		BATTLE_GROUP_ATTACK = 0,
		BATTLE_GROUP_DEFENSE = 1,
		BATTLE_GROUP_NONE = 2,
	},
	FANTASY_CARD_NPC_STATUS = {
		FANTASY_CARD_NPC_STATUS_INVALID = 0,
		FANTASY_CARD_NPC_STATUS_NEVER_WIN = 1,
		FANTASY_CARD_NPC_STATUS_HAS_COLLECTABLE_CARD = 2,
		FANTASY_CARD_NPC_STATUS_ALL_CARDS_COLLECTED = 3,
	},
	EFFECT_STATUS = {
		EFFECT_STATUS_IN_PROGRESS = 0,
		EFFECT_STATUS_SUCCESS = 1,
		EFFECT_STATUS_FAIL = 2,
		TournamentIndex = 12,
		Stats = 13,
		StageBattle = 1,
		StageScore = 2,
		EffectChoices = 14,
		EffectID = 1,
		Reroll = 2,
	},
	FantasyMedicineCmd = {
		FantasyMedicineCmdInvalid = 0,
		FantasyMedicineCmdUse = 1,
		FantasyMedicineCmdChangeMap = 2,
		FantasyMedicineCmdQuery = 3,
		FantasyMedicineCmdChangeStatus = 4,
		FantasyMedicineCmdNotifyStatus = 5,
	},
	CS_FATE_CMD = {
		CS_FATE_CMD_INVALID = 0,
		CS_FATE_CMD_UPDATE = 1,
		CS_FATE_CMD_END = 2,
		CS_FATE_CMD_ENTER = 3,
		CS_FATE_CMD_EXIT = 4,
		CS_FATE_CMD_NPC_START = 5,
		CS_FATE_CMD_SUBMIT_ITEM = 7,
		CS_FATE_CMD_UPDATE_GATHER = 8,
		CS_FATE_CMD_GET_RECORD = 9,
		CS_FATE_CMD_GET_ACH_MAP_REWARD = 10,
		CS_FATE_CMD_GET_STATS = 11,
		CS_FATE_CMD_NPC_ACTION = 12,
		CS_FATE_CMD_TRIGGER = 13,
		CS_FATE_CMD_CONFIRM_REWARD = 14,
		CS_FATE_CMD_UPDATE_BATTLE_RUNE = 15,
		CS_FATE_CMD_ACTIVITY_RESULT = 16,
		CS_FATE_CMD_START_PUZZLE = 17,
		CS_FATE_CMD_END_PUZZLE = 18,
		CS_FATE_CMD_DANCE = 19,
		CS_FATE_CMD_NPC_DANCE_NOTIFY = 20,
		CS_FATE_CMD_DANCE_NPC_HIDDEN = 21,
	},
	FateState = {
		FateState_Invalid = 0,
		FateState_WaitNPCTrigger = 1,
		FateState_InProgress = 2,
		FateState_EndSubmitItem = 3,
		FateState_Finished = 4,
	},
	FatePlayerJoinState = {
		FatePlayerJoinState_NotJoined = 0,
		FatePlayerJoinState_InRange = 1,
		FatePlayerJoinState_OutOfRange = 2,
	},
	CS_FATE_STATS = {
		CS_FATE_STATS_INVALID = 0,
		CS_FATE_STATS_MAP_PROGRESS = 1,
		CS_FATE_STATS_POWERFUL_MONSTER = 2,
		CS_FATE_STATS_DIFFICULT_FATE = 3,
	},
	CS_FATE_NPC_ACTION = {
		CS_FATE_NPC_ACTION_INVALID = 0,
		CS_FATE_NPC_ACTION_YELL = 1,
		CS_FATE_NPC_ACTION_PERFORM_ATL = 2,
	},
	FateUserDataKey = {
		FateUserDataKeyDefault = 0,
	},
	CSExploreFogCmd = {
		ExploreFogInvalidCmd = 0,
		ExploreFogAreaIDListCmd = 1,
		ExploreFogActivateAreaIDCmd = 2,
	},
	CS_FOOT_MARK_CMD = {
		CS_FOOT_MARK_CMD_NONE = 0,
		CS_FOOT_MARK_CMD_PULL = 1,
		CS_FOOT_MARK_CMD_REGION_ACHIEVE = 2,
		CS_FOOT_MARK_CMD_RECORD_UPDATE = 3,
	},
	CmdFootprint = {
		CmdFootprintNone = 0,
		CmdGetFootprint = 1,
		CmdReceiveMapAward = 2,
		CmdFootprintNotify = 3,
		CmdFootRedPoint = 4,
		CmdFootPointAllInfo = 5,
	},
	Profile = {
		Friendrecall = {
		},
		Mix = {
			CsMixNotifyClientCmd = {
				CS_MIX_INVALID = 0,
				CS_MIX_UPDATE_CLIENT = 1,
				CS_MIX_PLAYER_PRIVACY = 2,
				CS_MIX_PLAYER_GVOICE = 3,
				CS_MIX_CLIENT_CMD = 105,
			},
			PlayerPrivacyType = {
				PlayerPrivacyAll = 0,
				PlayerPrivacyRelationship = 1,
				PlayerPrivacyInfo = 2,
				PlayerPrivacyVoice = 3,
				PlayerPrivacyEdit = 4,
				PlayerPrivacyEditName = 5,
				PlayerPrivacyEditGroup = 6,
			},
		},
		PreLogin = {
			CsPreLoginCmd = {
				CMD_INVALID = 0,
				CS_PRELOGIN_FACE_CMD_SAVE = 1,
				CS_PRELOGIN_CMD_GET = 2,
				CS_PRELOGIN_IDIP_CFG_CMD_QUERY = 3,
			},
		},
		RedPosition = {
			CsRedPositionCmd = {
				CMD_INVALID = 0,
				CS_RED_POSITION_QUERY = 1,
				CS_RED_POSITION_CANCEL = 2,
			},
		},
	},
	Friend = {
		Friends = {
			FRIENDS_CONST = {
				FRIENDS_CONST_START = 0,
				MAX_FRIENDS_COUNT = 200,
				MAX_FRIENDS_REQ_COUNT = 100,
			},
			CS_SUBMSGID_FRIENDS = {
				CS_SUB_CMD_FRIENDS_START = 0,
				CS_SUB_CMD_FRIENDS_CONSORT = 10,
				CS_SUB_CMD_FRIENDS_INBLACKLIST = 11,
				CS_SUB_CMD_FRIENDS_OUTBLACKLIST = 12,
				CS_SUB_CMD_FRIENDS_REMOVE = 14,
				CS_SUB_CMD_FRIENDS_GET_LIST = 15,
				CS_SUB_CMD_FRIENDS_MOVEGROUP = 16,
				CS_SUB_CMD_FRIENDS_REMOVEGROUP = 17,
				CS_SUB_CMD_FRIENDS_NEWGROUP = 18,
				CS_SUB_CMD_FRIENDS_EDITGROUP = 19,
				CS_SUB_CMD_FRIENDS_CONSORTLIST = 22,
				CS_SUB_CMD_FRIENDS_CLEARCOMSORTLIST = 23,
				CS_SUB_CMD_FRIENDS_CONFIRMADD = 24,
				CS_SUB_CMD_FRIENDS_FRIENDSETREMARD = 25,
				CS_SUB_CMD_FRIENDS_BLACKMENSERREMARK = 26,
				CS_SUB_CMD_FRIENDS_CONSORT_NTF = 27,
				CS_SUB_CMD_FRIENDS_CONFIRMADD_NTF = 28,
				CS_SUB_CMD_FRIENDS_SAVE_SETTING = 29,
				CS_SUB_CMD_FRIENDS_PULL_SETTING = 30,
				CS_SUB_CMD_FRIENDS_FIND = 40,
				CS_SUB_CMD_FRIENDS_RECOMMOND = 50,
			},
			FIND_FRIEND = {
				FF_UNKNOW = 0,
				ROLEID = 1,
				ROLENAME = 2,
				TEAM = 4,
				FriendSearchDim = 5,
			},
			FriendSettingType = {
				FriendSettingType_Invalide = 0,
				FriendSettingType_BlockStranger = 1,
				FriendSettingType_Max = 2,
			},
		},
	},
	CSGilgameshCmd = {
		CSGilgameshCmdInvalid = 0,
		CSGilgameshCmdENTER = 1,
		CSGilgameshCmdInteraction = 2,
		CSGilgameshCmdExit = 3,
	},
	CS_GOLD_SAUSER_CMD = {
		CS_GOLD_SAUSER_CMD_INVALID = 0,
		CS_GOLD_SAUSER_CMD_UPDATE = 1,
		CS_GOLD_SAUSER_CMD_SIGNUP = 2,
		CS_GOLD_SAUSER_CMD_END = 3,
		CS_GOLD_SAUSER_CMD_TELE = 4,
		CS_GOLD_SAUSER_CMD_TELE_TO_STAGE = 6,
		CS_GOLD_SAUSER_CMD_UPDATE_GAME_STATE = 7,
		CS_GOLD_SAUSER_CMD_RESIGNUP = 8,
		CS_GOLD_SAUSER_CMD_QUICK_EXANGE = 9,
		CS_GOLD_SAUSER_CMD_UPDATE_NOTIFY = 10,
		CS_GOLD_SAUSER_CMD_LEAP_OF_FAITH_INFO = 11,
		CS_GOLD_SAUSER_CMD_REPORT_LEAP_OF_FAITH_INFO = 12,
		CS_GOLD_SAUSER_CMD_REPORT_CELEBRATION_BUFF = 13,
	},
	GoldSauserUpdateGameStateType = {
		GoldSauserUpdateGameStateType_Invalid = 0,
		GoldSauserUpdateGameStateType_Stage = 1,
		GoldSauserUpdateGameStateType_ObjID = 2,
		GoldSauserUpdateGameStateType_SIRtimes = 3,
	},
	GoldSauserEntertainState = {
		GoldSauserEntertainState_Invalid = 0,
		GoldSauserEntertainState_SignUp = 1,
		GoldSauserEntertainState_InProgress = 2,
		GoldSauserEntertainState_End = 3,
		GoldSauserEntertainState_EarlyEnd = 4,
	},
	GoldSauserPlayer = {
		GoldSauserPlayer_Invalid = 0,
		GoldSauserPlayer_NotSignUp = 1,
		GoldSauserPlayer_SignUp = 2,
		GoldSauserPlayer_End = 3,
		GoldSauserPlayer_SignUpLeaveStage = 4,
	},
	CS_GOLD_SAUSER_MAIN_CMD = {
		CS_GOLD_SAUSER_MAIN_CMD_INVALID = 0,
		CS_GOLD_SAUSER_MAIN_CMD_GET_EVENT = 1,
		CS_GOLD_SAUSER_MAIN_CMD_GET_REWARD = 2,
		CS_GOLD_SAUSER_MAIN_CMD_GET_ITEM = 3,
		CS_GOLD_SAUSER_MAIN_CMD_GAME_NOTIFY = 4,
		CS_GOLD_SAUSER_MAIN_CMD_GAME_FINISH = 5,
		CS_GOLD_SAUSER_MAIN_CMD_GAME_CELEBRATION = 6,
		CS_GOLD_SAUSER_MAIN_CMD_EVENT_UPDATE = 7,
		CS_GOLD_SAUSER_MAIN_CMD_DATA_QUERY = 8,
	},
	MiniGameType = {
		MiniGameTypeNone = 0,
		MiniGameTypeAirForceOne = 1,
		MiniGameTypeCliffHanger = 2,
		MiniGameTypeBodyGuard = 3,
		MiniGameTypeTyphon = 4,
	},
	CS_GROUP_CMD = {
		CS_CMD_GROUP_NONE = 0,
		CS_CMD_GROUP_QUERY_SELF = 1,
		CS_CMD_GROUP_QUERY = 33,
		CS_CMD_GROUP_QUERY_LOGS = 2,
		CS_CMD_GROUP_CREATE = 3,
		CS_CMD_GROUP_DISBAND = 4,
		CS_CMD_GROUP_NOTIFY_DISBAND = 34,
		CS_CMD_GROUP_QUIT = 5,
		CS_CMD_GROUP_EDIT_NOTICE = 6,
		CS_CMD_GROUP_EDIT_RECRUIT_INFO = 7,
		CS_CMD_GROUP_EDIT_EMBLEM = 8,
		CS_CMD_GROUP_EDIT_NAME = 9,
		CS_CMD_GROUP_EDIT_ALIAS = 10,
		CS_CMD_GROUP_SET_MEMBER_CATEGORY = 18,
		CS_CMD_GROUP_TRANSFER_LEADER = 19,
		CS_CMD_GROUP_SEARCH = 20,
		CS_CMD_GROUP_APPLY = 21,
		CS_CMD_GROUP_QUERY_APPLY_LIST = 32,
		CS_CMD_GROUP_ACCEPT_APPLY = 22,
		CS_CMD_GROUP_NOTIFY_JOIN = 35,
		CS_CMD_GROUP_REFUSE_APPLY = 23,
		CS_CMD_GROUP_SEND_INVITATION = 24,
		CS_CMD_GROUP_QUERY_INVITATIONS = 25,
		CS_CMD_GROUP_NOTIFY_INVITATION = 26,
		CS_CMD_GROUP_IGNORE_INVITATION = 27,
		CS_CMD_GROUP_ACCEPT_INVITATION = 28,
		CS_CMD_GROUP_KICK_MEMBER = 29,
		CS_CMD_GROUP_NOTIFY_KICKED = 30,
		CS_CMD_GROUP_QUERY_APPLIED_GROUPS = 31,
		CS_CMD_GROUP_NOTIFY_SELF = 36,
		CS_CMD_GROUP_EDIT_INFO = 37,
		CS_CMD_GROUP_QUERY_ROLE_GROUP = 38,
		CS_CMD_GROUP_NOTIFY_APPLICATION_LIST = 39,
		CS_CMD_GROUP_CHECK_SLOGAN = 40,
		CS_CMD_GROUP_ADD_GROUP_SCORE = 41,
		CS_CMD_GROUP_STORE_DEPOSIT_ITEM = 42,
		CS_CMD_GROUP_STORE_FETCH_ITEM = 43,
		CS_CMD_GROUP_STORE_ADD_EXTRA_GRID = 44,
		CS_CMD_GROUP_STORE_SET_STORE_NAME = 45,
		CS_CMD_GROUP_STORE_REQ_STORE_INFO = 46,
		CS_CMD_GROUP_STORE_REQ_STORE_BASE_INFO = 47,
		CS_CMD_GROUP_CATEGORY_PERMISSION_CHANGE = 48,
		CS_CMD_GROUP_STORE_STORE_CHANGE = 49,
		CS_CMD_GROUP_CATEGORY_UPDATE = 50,
		CS_CMD_GROUP_NOTIFY_MEMBER_JOIN = 51,
		CS_CMD_GROUP_NOTIFY_MEMBER_LEAVE = 52,
		CS_CMD_GROUP_QUERY_MEMBERS = 53,
		CS_CMD_GROUP_NOTIFY_REDS = 54,
		CS_CMD_GROUP_READ_BAG = 55,
		CS_CMD_GROUP_QUERY_ROLES_GROUP = 56,
		CS_CMD_GROUP_CATEGORY_INTERN_UP_CONFIRM = 57,
		CS_CMD_GROUP_EDIT_CATEGORY = 58,
		CS_CMD_GROUP_QUERY_CATEGORY = 59,
		CS_CMD_GROUP_NOTIFY_ALIAS = 60,
		CS_CMD_GROUP_QUERY_EDITED_TIMES = 61,
		CS_CMD_GROUP_BONUS_STATE_QUERY = 62,
		CS_CMD_GROUP_BONUS_STATE_BUY = 63,
		CS_CMD_GROUP_BONUS_STATE_USE = 64,
		CS_CMD_GROUP_BONUS_STATE_STOP = 65,
		CS_CMD_GROUP_CHECK_SENSITIVE_TEXT = 66,
		CS_CMD_GROUP_QUERY_MEMBERS_BY_CATEGORY = 67,
		CS_CMD_GROUP_NOTIFY_LOG = 68,
		CS_CMD_GROUP_MONEY_BAG_DEPOSIT = 69,
		CS_CMD_GROUP_MONEY_BAG_WITHDRAW = 70,
		CS_CMD_GROUP_MONEY_BAG_QUERY = 71,
		CS_CMD_GROUP_NOTIFY_MEMBER_ONLINE = 72,
		CS_CMD_GROUP_QUERY_GROUP_BASE_INFO = 73,
		CS_CMD_GROUP_INVITE_SET_READ = 74,
		CS_CMD_GROUP_QUERY_SELF_MEMBERS = 75,
		CS_CMD_GROUP_PETITION_GAIN = 76,
		CS_CMD_GROUP_PETITION_QUERY = 77,
		CS_CMD_GROUP_PETITION_EDIT = 78,
		CS_CMD_GROUP_PETITION_CANCEL = 79,
		CS_CMD_GROUP_SIGN_INVITE = 80,
		CS_CMD_GROUP_SIGN_AGREE = 81,
		CS_CMD_GROUP_SIGN_REFUSE = 82,
		CS_CMD_GROUP_SIGN_CANCEL = 83,
		CS_CMD_GROUP_SIGN_QUERY_INVITES = 84,
		CS_CMD_GROUP_GRAND_COMPANY_CHANGE = 85,
		CS_CMD_GROUP_PROFILE_INFO = 89,
		CS_CMD_GROUP_SIGN_INVITED_TOC = 90,
		CS_CMD_GROUP_SIGN_NUM_TOC = 91,
		CS_CMD_GROUP_GRAND_COMPANY_TOC = 92,
		CS_CMD_GROUP_REPUTATION_QUERY = 93,
		CS_CMD_GROUP_PETITION_CANCEL_TOC = 94,
		CS_CMD_GROUP_PROFILE_EDIT = 95,
		CS_CMD_GROUP_SIGN_REFUSE_TOC = 96,
		CS_CMD_GROUP_SIGN_FULL_READ = 97,
		CS_CMD_GROUP_NOTIFY_REPUTATION = 98,
	},
	GroupRedDotType = {
		GroupRedDotTypeApply = 0,
		GroupRedDotTypeInvite = 1,
		GroupRedDotTypeBag = 2,
		GroupRedDotTypeSignInvite = 3,
		GroupRedDotTypeSignFull = 4,
	},
	GroupPermissionType = {
		GROUP_PERMISSION_TYPE_None = 0,
		GROUP_PERMISSION_TYPE_EditSimple = 1,
		GROUP_PERMISSION_TYPE_EditNotice = 2,
		GROUP_PERMISSION_TYPE_Invite = 3,
		GROUP_PERMISSION_TYPE_AcceptJoin = 4,
		GROUP_PERMISSION_TYPE_KickMember = 5,
		GROUP_PERMISSION_TYPE_SetMemberCategory = 6,
		GROUP_PERMISSION_TYPE_EditCategory = 7,
		GPT_EDIT_STORE_NAME = 8,
		GPT_STORE_1_USE = 101,
		GPT_STORE_2_USE = 102,
		GPT_STORE_3_USE = 103,
		GPT_STORE_4_USE = 104,
		GPT_STORE_5_USE = 105,
	},
	RoleGroupState = {
		RoleGroupStateInit = 0,
		RoleGroupStateGainedPetition = 1,
		RoleGroupStateSignedOtherPetition = 2,
		RoleGroupStateJoinedGroup = 3,
	},
	GroupRecruitStatus = {
		GROUP_RECRUIT_STATUS_Open = 0,
		GROUP_RECRUIT_STATUS_Closed = 1,
	},
	JoinWay = {
		JoinWayNone = 0,
		JoinWaySign = 1,
		JoinWayApply = 2,
		JoinWayInvite = 3,
	},
	GuideOptCmd = {
		GuideOptCmd_None = 0,
		GuideOptCmd_Status = 1,
		GuideOptCmd_Condition = 2,
		GuideOptCmd_Attestation = 3,
		GuideOptCmd_Resign = 4,
		GuideOptCmd_ConditionUpdateNotice = 5,
		GuideOptCmd_NewbieStatus = 6,
		GuideOptCmd_NewbieCondition = 7,
		GuideOptCmd_NewbieAttestation = 8,
		GuideOptCmd_GuideNum = 9,
		GuideOptCmd_JoinChannel = 10,
		GuideOptCmd_QuitChannel = 11,
		GuideOptCmd_InviteJoinNewbieChannel = 12,
		GuideOptCmd_RspInviteJoinNewbieChannel = 13,
		GuideOptCmd_MoveOutNewbieChannel = 14,
		GuideOptCmd_InviteJoinNewbieChannelNtf = 15,
		GuideOptCmd_ChannelData = 16,
		GuideOptCmd_ReturneeStatus = 17,
		GuideOptCmd_AllStatus = 18,
		GuideOptCmd_IdentifyChangeNotice = 19,
		GuideOptCmd_BeMoveOutNewbieChannelNotice = 20,
	},
	CS_HOPE_CMD = {
		CS_CMD_UNDEF = 0,
		CS_CMD_HOPE_EXECUTEINSTRUCTION = 1,
	},
	INSTRUCTIONTYPE = {
		INSTRUCTIONTYPE_UNDEFINED = 0,
		INSTRUCTIONTYPE_TIPS = 1,
		INSTRUCTIONTYPE_LOGOUT = 2,
		INSTRUCTIONTYPE_OPENURL = 3,
		INSTRUCTIONTYPE_USERDEFINED = 4,
		INSTRUCTIONTYPE_STOP = 7,
		INSTRUCTIONTYPE_PRELOGOUT = 8,
	},
	CsInteractionCMD = {
		CsInteractionCMDStart = 0,
		CsInteractionCMDEnd = 4,
		CsInteractionCMDSpellChg = 1,
		CsInteractionCMDReport = 2,
		CsInteractionCMDBreak = 5,
		CsInteractionCmdVfx = 3,
	},
	InteractionObjType = {
		InteractionObjTypeEobj = 0,
		InteractionObjTypeEobjListID = 1,
		InteractionObjTypeNPC = 2,
		InteractionObjTypeNPCListID = 3,
		InteractionObjTypeCrystal = 4,
		InteractionObjTypeEmpty = 5,
	},
	SpellResult = {
		SpellResultSuccell = 0,
		SpellResultBreak = 1,
		SpellResultNext = 2,
		SpellResultFirst = 3,
	},
	LatencyType = {
		LatencyTypeNone = 0,
		LatencyTypePing = 1,
		LatencyTypePong = 2,
	},
	CsLegendaryWeaponCmd = {
		CS_LEGENDARY_WEAPON_CMD_INVALID = 0,
		CS_LEGENDARY_WEAPON_CMD_QUERY = 1,
		CS_LEGENDARY_WEAPON_CMD_PRODUCE = 2,
	},
	LeveQuest = {
		LeveQuestCmd = {
			LeveQuestInvalid = 0,
			LeveQuestQuery = 1,
			LeveQuestAcceptTask = 2,
			LeveQuestGiveUpTask = 3,
			LeveQuestAcceptTaskList = 4,
			LeveQuestSubmitTask = 5,
			LeveQuestBatchAbandon = 6,
			LeveQuestBatchSubmit = 7,
		},
	},
	FeatureType = {
		FEATURE_TYPE_INVALID = 0,
		FEATURE_TYPE_STEPS = 1,
		FEATURE_TYPE_DURABILITY = 2,
		FEATURE_TYPE_PROGRESS = 3,
		FEATURE_TYPE_QUALITY = 4,
		FEATURE_TYPE_HQRATE = 5,
		FEATURE_TYPE_REACTION_INTENSITY = 6,
		FEATURE_TYPE_TENSION = 7,
		FEATURE_TYPE_HEAT_BASE = 50,
		FEATURE_TYPE_HEAT_AA = 51,
		FEATURE_TYPE_HEAT_AB = 52,
		FEATURE_TYPE_HEAT_BA = 53,
		FEATURE_TYPE_HEAT_BB = 54,
		FEATURE_TYPE_HEAT_MAX = 55,
	},
	MakeType = {
		MakeTypeNormal = 0,
		MakeTypeTrain = 1,
		MakeTypeFast = 2,
		MakeTypeSimple = 3,
	},
	BallType = {
		BallTypeInvalid = 0,
		BallTypeNormal = 1,
		BallTypeGreen = 2,
		BallTypeYellow = 3,
		BallTypeRed = 4,
	},
	CS_LIFE_SKILL_CMD = {
		LIFE_SKILL_INVALID = 0,
		LIFE_SKILL_ACTION_CMD = 1,
		LIFE_SKILL_PULLBUFF_CMD = 2,
		LIFE_SKILL_LEAVE_FISH_LOCATION_CMD = 4,
		LIFE_SKILL_FISH_END = 5,
		LIFE_SKILL_REPLACE = 28,
		LIFE_SKILL_FISH_DROP_CMD = 6,
		LIFE_SKILL_FISH_LIFT_CMD = 7,
		LIFE_SKILL_FISH_LIFT_END = 8,
		LIFE_SKILL_FISH_LIFT_SIT = 19,
		LIFE_SKILL_PULL_PRIVATE_GATHERS_CMD = 3,
		LIFE_SKILL_GATHER_CMD = 9,
		LIFE_SKILL_PRIVATE_GATHER_CMD = 10,
		LIFE_SKILL_GATHER_START_CMD = 20,
		LIFE_SKILL_GATHER_END_CMD = 21,
		LIFE_SKILL_GATHER_POINT_INFO_CMD = 22,
		LIFE_SKILL_GATHER_GET_CMD = 24,
		LIFE_SKILL_GATHER_GET_REWARD = 30,
		LIFE_SKILL_BUFF_CMD = 11,
		LIFE_SKILL_EXIT_COLLECTION_CMD = 12,
		LIFE_SKILL_COLLECTION_CMD = 13,
		LIFE_SKILL_ATTR_UPDATE = 14,
		LIFE_SKILL_CRAFTER_START_MAKE = 15,
		LIFE_SKILL_CRAFTER_SKILL = 16,
		LIFE_SKILL_CRAFTER_QUIT_MAKE = 17,
		LIFE_SKILL_CRAFTER_RESULT = 18,
		LIFE_SKILL_CRAFTER_CULINARY_ORIGIN = 23,
		LIFE_SKILL_CRAFTER_GET = 25,
		LIFE_SKILL_CRAFTER_SYNC_COST = 26,
		LIFE_SKILL_CRAFTER_EFFECT_NOTICE = 27,
		LIFE_SKILL_CRAFTER_CULINARY_STORM = 29,
		LIFE_SKILL_CRAFTER_SIMPLE_SKILL_END = 31,
	},
	NoFishReason = {
		NoFishReason_Invalid = 0,
		NoFishReason_NoMatch = 1,
		NoFishReason_Skill = 2,
		NoFishReason_TimeWeather = 3,
		NoFishReason_Level = 4,
		NoFishReason_Attr = 5,
		NoFishReason_BaitLevel = 6,
	},
	LiftResult = {
		LiftResultSuccess = 0,
		LiftResultFail1 = 1,
		LiftResultFail2 = 2,
		LiftResultFailGathering = 3,
	},
	LifeSkillGatherType = {
		LIFE_SKILL_GATHER_TYPE_NONE = 0,
		LIFE_SKILL_GATHER_TYPE_MISS = 1,
		LIFE_SKILL_GATHER_TYPE_COMMON = 2,
		LIFE_SKILL_GATHER_TYPE_HQ = 3,
	},
	Gather_Collection_OP = {
		COLLECTION_FAIL = 0,
		COLLECTION_SCOUR = 1,
		COLLECTION_COLLECT = 2,
		COLLECTION_ENTER = 3,
		COLLECTION_ENTER_FAIL = 4,
	},
	LifeSkillType = {
		LIFE_SKILL_TYPE_INVALID = 0,
		LIFE_SKILL_TYPE_FISH = 1,
		LIFE_SKILL_TYPE_MINE = 2,
		LIFE_SKILL_TYPE_BOTANY = 3,
	},
	LifeSkillQuality = {
		LIFE_SKILL_QUALITY_NQ = 0,
		LIFE_SKILL_QUALITY_HQ = 1,
	},
	LifeSkillBuffOp = {
		LIFE_SKILL_BUFF_INVALID = 0,
		LIFE_SKILL_BUFF_ADD = 1,
		LIFE_SKILL_BUFF_REMOVE = 2,
		LIFE_SKILL_BUFF_UPDATE = 3,
	},
	GroupChat = {
		LinkShells = {
			CS_SUBMSGID_LINKSHELL = {
				CS_SUB_CMD_LINKSHELL_START = 0,
				CS_SUB_CMD_LINKSHELL_GETLIST = 1,
				CS_SUB_CMD_LINKSHELL_GETDETAILS = 2,
				CS_SUB_CMD_LINKSHELL_CREATE = 3,
				CS_SUB_CMD_LINKSHELL_DESTROY = 4,
				CS_SUB_CMD_LINKSHELL_UPDATEDETAILS = 5,
				CS_SUB_CMD_LINKSHELL_GETMEMS = 6,
				CS_SUB_CMD_LINKSHELL_REQJOINLIST = 7,
				CS_SUB_CMD_LINKSHELL_JOIN = 8,
				CS_SUB_CMD_LINKSHELL_AUDITJOIN = 9,
				CS_SUB_CMD_LINKSHELL_MOVEINBLACKLIST = 10,
				CS_SUB_CMD_LINKSHELL_MOVEOUTBLACKLIST = 11,
				CS_SUB_CMD_LINKSHELL_INVITEJOIN = 12,
				CS_SUB_CMD_LINKSHELL_ANSWERINVITEJOIN = 13,
				CS_SUB_CMD_LINKSHELL_TRANSFERCREATE = 14,
				CS_SUB_CMD_LINKSHELL_SETMANAGE = 15,
				CS_SUB_CMD_LINKSHELL_LEAVE = 16,
				CS_SUB_CMD_LINKSHELL_KICKOFF = 17,
				CS_SUB_CMD_LINKSHELL_EVENTS = 18,
				CS_SUB_CMD_LINKSHELL_FIND = 19,
				CS_SUB_CMD_LINKSHELL_COLLECT = 20,
				CS_SUB_CMD_LINKSHELL_BLACKLIST = 21,
				CS_SUB_CMD_LINKSHELL_BE_INVITE_RECORD = 22,
				CS_SUB_CMD_LINKSHELL_STICK = 24,
				CS_SUB_CMD_LINKSHELL_AUDITJOIN_RESULT_NTF = 50,
				CS_SUB_CMD_LINKSHELL_INVITE_JOIN_NTF = 51,
				CS_SUB_CMD_LINKSHELL_JOIN_LINKSHELL = 52,
				CS_SUB_CMD_LINKSHELL_DESTROY_NTF = 53,
				CS_SUB_CMD_LINKSHELL_KICKOFF_NTF = 54,
				CS_SUB_CMD_LINKSHELL_TITLE_CHANGE_NTF = 55,
				CS_SUB_CMD_LINKSHELL_APPLY_JOIN_NTF = 56,
			},
			LINKSHELL_IDENTIFY = {
				IDENTIFY_UNKNOWN = 0,
				CREATOR = 1,
				MANAGER = 2,
				NORMAL = 3,
			},
			RECRUITING_SET = {
				SET_UNKNOWN = 0,
				OPEN = 1,
				AUDIT = 2,
				INVITE = 3,
			},
			FOCUS_EVENT = {
				FOCUS_UNKNOWN = 0,
				FOCUS_BATTLE = 1,
				FOCUS_MAKE = 2,
				FOCUS_GATHER = 3,
				FOCUS_FAMILY = 4,
				FOCUS_SCENE = 5,
				FOCUS_COLLECT = 6,
				FOCUS_ACHIEVEMENT = 7,
				FOCUS_IDLE = 8,
				FOCUS_SOCIAL = 9,
				FOCUS_GOLD_SAUCER = 10,
			},
			FIND_LINKSHELL = {
				FIND_LINKSHELL_UNKNOWN = 0,
				ID = 1,
				LS_NAME = 2,
				LS_ACTIVITY = 3,
				WEIGHT = 4,
			},
			LINKSHELL_EVENT = {
				EVENT_UNKNOWN = 0,
				CREATE_LINKSHELL = 1,
				JOIN_LINKSHELL = 2,
				LEAVE_LINKSHELL = 3,
				SET_MANAGE_LINKSHELL = 4,
				TRANSFER_CREATOR = 5,
				KICKOFF_LINKSHELL = 6,
				MODIFY_LINKSHELL_NAME = 7,
				MODIFY_MANIFESTO = 8,
				MOVE_IN_BLACKLIST = 9,
				DEL_MANAGE_LINKSHELL = 10,
			},
		},
	},
	LogoutReason = {
		Logout = 0,
		SwitchRole = 1,
		ExitDemo = 2,
		OtherLogin = 1001,
		HelloOverTime = 1007,
		ServerBan = 1008,
		LogoutByGM = 1009,
		EnterSceneFailed = 1010,
		LogoutByWorldKick = 1011,
	},
	SampleCmd = {
		SampleCmdNone = 0,
		SampleCmdRegister = 1,
		SampleCmdLogin = 2,
		SampleCmdEnter = 3,
		SampleCmdExit = 4,
	},
	ClientSetupMsgID = {
		ClientSetupMsgIDStart = 0,
		ClientSetupMsgIDQuery = 1,
		ClientSetupMsgIDSet = 2,
		ClientSetupMsgIDNtf = 3,
	},
	ClientSetupKey = {
		ClientSetupKeyStart = 0,
		CSKAutoFoldWeapon = 1,
		CSKIdleAnims = 2,
		CSKOpenClimb = 3,
		CSKAutoSyncVisionEnd = 20,
		CSCombatDrug = 21,
		MapMarkerPlaced = 22,
		MapTransferFavor = 23,
		CSOnlineStatusSet = 24,
		PerferredProf = 25,
		ActiveHours = 26,
		Playstyle = 27,
		PersonalSignature = 28,
		HeadPortrait = 29,
		ActiveHeadPortrait = 30,
		NewbieChannel = 36,
		ChatBan = 37,
		FantacyCardEmoList = 38,
		CSKAutoSkipCutScene = 39,
		CSKBrowsedCutScene = 40,
		CSAirForceOneBeginTime = 41,
		CSKPerformAgreement = 42,
		CSFashionCheckTrackEqiu = 43,
		MallGiftDecorativeStyle = 44,
		CSKLeveQuestPayMethod = 45,
		CSKWildBoxOpen = 46,
	},
	LOOT_TYPE = {
		LOOT_TYPE_SCORE = 0,
		LOOT_TYPE_ITEM = 1,
	},
	Mail = {
		Mail = {
			MailType = {
				SystemNone = 0,
				System = 1,
				Gift = 2,
				PrivateChat = 10,
				OutboxGift = 5000,
			},
			CmdMail = {
				CmdMailNone = 0,
				CmdGetMail = 1,
				CmdSetRead = 2,
				CmdReceiveAttachmentAward = 3,
				CmdDelMail = 4,
				CmdNewMailNotify = 5,
			},
		},
	},
	AttachmentType = {
		UnknownType = 0,
		ItemType = 1,
		MallType = 2,
		FateMailType = 3,
	},
	MailType = {
		SystemNone = 0,
		System = 1,
		Gift = 2,
	},
	CsMallAndStoreCmd = {
		CS_MALL_AND_STORE_CMD_INVALID = 0,
		CS_MALL_AND_STORE_CMD_STORE_QUERY = 1,
		CS_MALL_AND_STORE_CMD_STORE_PURCHASE = 2,
		CS_MALL_AND_STORE_CMD_MALL_QUERY = 3,
		CS_MALL_AND_STORE_CMD_MALL_PURCHASE = 4,
		CS_MALL_AND_STORE_CMD_MALL_GIFT = 5,
		CS_MALL_AND_STORE_CMD_QUERY_RESIDS = 6,
		CS_MALL_AND_STORE_CMD_BATCH_PRUCHASE = 7,
	},
	MarketMacro = {
		MarketMacro_None = 0,
		MarketMacro_QueryGoodsNum = 128,
	},
	MarketOptCmd = {
		MarketOptCmd_None = 0,
		MarketOptCmd_Status = 1,
		MarketOptCmd_Sale = 2,
		MarketOptCmd_Close = 3,
		MarketOptCmd_Money = 4,
		MarketOptCmd_Price = 5,
		MarketOptCmd_QueryGoods = 6,
		MarketOptCmd_Buy = 7,
		MarketOptCmd_ListFollows = 8,
		MarketOptCmd_Follow = 9,
		MarketOptCmd_ListRecords = 10,
		MarketOptCmd_ListStalls = 12,
		MarketOptCmd_ReSale = 13,
		MarketOptCmd_Login = 14,
		MarketOptCmd_BatchReSale = 15,
		MarketOptCmd_BatchClose = 16,
		MarketOptCmd_StallChgNtf = 17,
	},
	MarketRecordType = {
		MarketRecordType_Sell = 0,
		MarketRecordType_Buy = 1,
	},
	MarkingCmd = {
		MarkingCmdInfo = 0,
		MarkingCmdTarget = 1,
		MarkingCmdGround = 2,
		MarkingCmdGroundClear = 3,
	},
	CSSubMsgIDMatch = {
		CSSubMsgIDMatch_START = 0,
		CSSubMsgIDMatch_Match = 1,
		CSSubMsgIDMatch_CancelMatch = 2,
		CSSubMsgIDMatch_GetMatchInfo = 3,
		CSSubMsgIDMatch_Punishment = 6,
		CSSubMsgIDMatch_Query = 7,
		CSSubMsgIDMatch_Waiting = 8,
	},
	MatchType = {
		MatchUnknow = 0,
		MatchDuty = 1,
		ChocoboMatch = 2,
		TournamentMatch = 3,
		CrystalConflict = 4,
	},
	MatchObjType = {
		MatchObjTypeUnknow = 0,
		MatchObjTypeSingle = 1,
		MatchObjTypeTeam = 2,
	},
	PvPColosseumGameType = {
		Invalid = 0,
		Crystal = 1,
		FrontLine = 2,
	},
	PvPColosseumMode = {
		Exercise = 0,
		Rank = 1,
		Custom = 2,
	},
	CancelReason = {
		CancelUnknow = 0,
		CancelBySelf = 1,
		VoteSuccessEnterScene = 2,
		TeamMemNotVote = 3,
		TeamMemRefuse = 4,
		SelfRefuseEnter = 5,
		PlayerJoinTeam = 6,
		PlayerEnterScene = 7,
		GuideDailyRandomTimeout = 8,
		LoseFightGuideIdentity = 9,
		SceneMatchTimeout = 10,
		TeamMemLogout = 11,
	},
	MatchInfomation = {
		MatchInfoUnknow = 0,
		MatchInfoRanking = 1,
		MatchInfoLackFunc = 2,
	},
	QueryMatchType = {
		QueryMatchTypeQuery = 0,
		QueryMatchTypeMatch = 1,
	},
	CS_MATCH_CONFIRM_CMD = {
		CS_MATCH_CONFIRM_CMD_INVALID = 0,
		CS_MATCH_CONFIRM_CMD_QUERY = 1,
		CS_MATCH_CONFIRM_CMD_VOTE = 2,
	},
	MatchVoteObjType = {
		MatchVoteObjType_Self = 0,
		MatchVoteObjType_Team = 1,
		MatchVoteObjType_Match = 2,
		MatchVoteObjType_Scene = 3,
	},
	MatchPollType = {
		MatchPollType_Invaild = 0,
		MatchPollType_EnterScene = 1,
		MatchPollType_Chocobo = 2,
		MatchPollType_EnterCrystal = 3,
	},
	CS_MEET_TRADE_CMD = {
		CS_MEET_TRADE_CMD_None = 0,
		CS_MEET_TRADE_CMD_Apply = 1,
		CS_MEET_TRADE_CMD_Reply = 2,
		CS_MEET_TRADE_CMD_Place = 3,
		CS_MEET_TRADE_CMD_Lock = 4,
		CS_MEET_TRADE_CMD_Confirm = 5,
		CS_MEET_TRADE_CMD_Cancel = 6,
		CS_MEET_TRADE_CMD_Keep = 7,
	},
	enState = {
		Init = 0,
		Lock = 1,
		Confirm = 2,
		Cancel = 3,
		RoleID = 1,
		State = 2,
		TaxRate = 3,
		Items = 4,
	},
	Macro = {
		None = 0,
		Interval = 60,
		TradeID = 1,
	},
	MESSAGE_BOARD_ID = {
		MESSAGE_BOARD_ID_INVALID = 0,
		MESSAGE_BOARD_ID_CREATE = 1,
		MESSAGE_BOARD_ID_LIKE = 2,
		MESSAGE_BOARD_ID_DEL = 3,
		MESSAGE_BOARD_ID_QUERY = 4,
		MESSAGE_BOARD_ID_UNLIKE = 5,
		MESSAGE_BOARD_ID_REPORT = 6,
	},
	POST_TYPE = {
		POST_TYPE_INVLAID = 0,
		POST_TYPE_MOUNT = 1,
	},
	MINI_CACTPOT_OP = {
		MINI_CACTPOT_OP_INVALID = 0,
		MINI_CACTPOT_OP_ENTER = 1,
		MINI_CACTPOT_OP_CLICK_CELL = 2,
		MINI_CACTPOT_OP_FINISH = 3,
		MINI_CACTPOT_OP_VIEW = 4,
		MINI_CACTPOT_OP_EXIT = 5,
		MINI_CACTPOT_OP_SCRATCH = 6,
	},
	ModuleOpenCmd = {
		ModuleOpenCmdStart = 0,
		ModuleOpenCmdQuery = 1,
		ModuleOpenCmdNotify = 2,
	},
	CSMonsterBasketballCmd = {
		CSMonsterBasketball_Invalid = 0,
		CSMonsterBasketball_Enter = 1,
		CSMonsterBasketball_Throw = 2,
		CSMonsterBasketball_Finish = 3,
	},
	BasketballType = {
		BasketballType_Invalid = 0,
		BasketballType_Normal = 1,
		BasketballType_Super = 2,
		BasketballType_Bang = 3,
		BasketballType_Star = 4,
	},
	CS_MONSTORHUNT_CMD = {
		CS_MONSTORHUNT_CMD_INVALID = 0,
		CS_MONSTOR_HUNT_CMD_GET_AWARD_B = 1,
		CS_MONSTOR_HUNT_CMD_AWARD_NOTIFY = 2,
		CS_MONSTOR_HUNT_CMD_GET_DATA_B = 3,
		CS_MONSTOR_HUNT_CMD_GET_WEEKLY_AWARD_B = 4,
		CS_MONSTOR_HUNT_CMD_GET_AWARD_A = 5,
		CS_MONSTOR_HUNT_CMD_GET_UNLOCK_DATA = 6,
		CS_MONSTOR_HUNT_CMD_REP_UNLOCK_DATA = 7,
	},
	MonthCardCmd = {
		MonthCardCmd_None = 0,
		MonthCardCmd_Status = 1,
		MonthCardCmd_DailyReward = 2,
		MonthCardCmd_RechargePreCheck = 3,
		MonthCardCmd_RewardShow = 4,
	},
	MountCmd = {
		MountCmdStart = 0,
		MountCmdQuery = 1,
		MountCmdLike = 2,
		MountCmdCallOut = 3,
		MountCmdUnlock = 5,
		MountCmdPreCallOut = 6,
		MountCmdRead = 7,
		MountCmdInviteTrans = 8,
		MountCmdFacade = 9,
		MountCmdReadFacade = 10,
		MountCmdCallBack = 11,
		MountCmdNextSeat = 12,
		MountCmdApplyOn = 13,
		MountCmdReplyOn = 14,
		MountCmdApplyNotify = 15,
		MountCmdReplyNotify = 16,
		MountCmdFacadeUnlock = 17,
		MountCmdSpeedPromote = 21,
	},
	MountFlagBitmap = {
		MountFlagStart = 0,
		MountFlagLike = 1,
		MountFlagLast = 2,
		MountFlagNew = 4,
		MountFlagHandbookNew = 8,
	},
	MountCallOutType = {
		MountCallOutByOnly = 0,
		MountCallOutByRand = 1,
		MountCallOutByLike = 2,
		MountCallOutByLast = 3,
	},
	CS_SUBMSGID_MOVE = {
		CS_SUB_CMD_MOVE_START = 0,
		CS_SUB_CMD_MOVE_INFO_REQ = 1,
		CS_SUB_CMD_MOVE_INFO_NOTIFY = 3,
		CS_SUB_CMD_MOVE_RESET = 4,
		CS_SUB_CMD_MOVE_DASH = 5,
		CS_SUB_CMD_MOVE_PAHTSTATE_SYNC = 11,
		CS_SUB_CMD_FIND_PATH = 12,
		CS_SUB_CMD_MOVE_ROTATE_NOTIFY = 14,
		CS_SUB_CMD_MOVE_CHASE_NOTIFY = 15,
		CS_SUB_CMD_MOVE_FORCEFIELD_NOTIFY = 16,
		CS_SUB_CMD_MOVE_DRAW_POINT_RES = 17,
	},
	MOVESTAND_MOVE = {
		MOVESTAND_NONE = 0,
		MOVESTAND_NORAML = 1,
		MOVESTAND_CROUCH = 2,
		MOVESTAND_CRAWL = 3,
	},
	MOVEDIR_MODE = {
		MOVEDIR_FORWARD = 0,
		MOVEDIR_LEFTFORWARD = 1,
		MOVEDIR_LEFT = 2,
		MOVEDIR_LEFTBACK = 3,
		MOVEDIR_BACK = 4,
	},
	MOVEHEALTH_MODE = {
		MOVEHEALTH_NORAML = 0,
		MOVEHEALTH_DYING = 1,
	},
	MOVE_MOVING_MODE = {
		MOVE_MOVING_MODE_START = 0,
		MOVE_MOVING_MODE_IDLE = 1,
		MOVE_MOVING_MODE_MOVING = 2,
		MOVE_MOVING_MODE_SPRINT = 3,
		MOVE_MOVING_MODE_INAIR = 4,
		MOVE_MOVING_MODE_LANDING = 5,
		MOVE_MOVING_MODE_SWIM = 6,
		MOVE_MOVING_MODE_CLIMBLADDER = 7,
		MOVE_MOVING_MODE_VAULT = 8,
		MOVE_MOVING_MODE_VEHICLE = 9,
		MOVE_MOVING_MODE_PARACHUTE = 10,
		MOVE_MOVING_MODE_SIMULATE_MOVE = 11,
		MOVE_MOVING_MODE_DIVE = 12,
		MOVE_MOVING_MODE_VEHICLE_DIVE = 13,
		MOVE_MOVING_MODE_CLIMB = 14,
		MOVE_MOVING_MODE_FLOATING = 15,
		MOVE_MOVING_MODE_WALKING = 51,
		MOVE_MOVING_MODE_END = 100,
	},
	MOVE_STATUS = {
		MOVE_STATUS_START = 0,
		MOVE_STATUS_STOP = 1,
		MOVE_STATUS_WALKING = 2,
		MOVE_STATUS_FALLING = 3,
		MOVE_STATUS_FLYING = 4,
		MOVE_STATUS_ARTPATH = 5,
		MOVE_STATUS_CLIENTDRIVEN = 6,
		MOVE_STATUS_SELFARTPATH = 7,
		MOVE_STATUS_VEHICLE_MOVE = 8,
		MOVE_STATUS_ON_SWIMMING = 9,
		MOVE_STATUS_ON_VEHICLE = 10,
		MOVE_STATUS_TOURISM_MOVE = 11,
		MOVE_STATUS_CLIENT_LOCAL = 12,
		MOVE_STATUS_CLIMB = 13,
		MOVE_STATUS_SERVER_DRIVEN = 14,
		MOVE_STATUS_CLIENT_SIMULATE_MOVE = 17,
		MOVE_STATUS_END = 40,
		MOVE_SUBSTATUS_START = 41,
		MOVE_SUBSTATUS_END = 47,
	},
	MoveDestType = {
		EN_MOVETYPE_NONE = 0,
		EN_MOVEDESTBYDIRECT = 1,
		EN_MOVEDESTBYPOSLIST = 2,
	},
	SmoothMoveType = {
		EN_SMOOTH_NONE = 0,
		EN_SMOOTH_MOVE = 1,
		EN_SMOOTH_ART = 2,
	},
	MoveForceFieldType = {
		MoveForceFieldTypeDir = 0,
		MoveForceFieldTypePoint = 1,
		MoveForceFieldTypeTarget = 2,
	},
	CSArtPathReason = {
		CSArtPathReason_None = 0,
		CSArtPathReason_DynamicBlockPush = 1,
	},
	MusicOptCmd = {
		MusicOptCmd_None = 0,
		MusicOptCmd_UnLock = 1,
		MusicOptCmd_GET = 2,
		MusicOptCmd_GetUnLockList = 3,
		MusicOptCmd_SavePlayList = 4,
		MusicOptCmd_GetReward = 5,
		MusicOptCmd_GetRecordList = 6,
		MusicOptCmd_RedUpdate = 7,
		MusicOptCmd_UnlockNotify = 8,
		MusicOptCmd_Query = 9,
	},
	NavmeshPointType = {
		NAVPOINT_TYPE_NONE = 0,
		NAVPOINT_TYPE_NOT_WAYPOINT = 1,
		NAVPOINT_TYPE_IN_WAYPOINT = 2,
		NAVPOINT_TYPE_OUT_WAYPOINT = 3,
	},
	CS_AUTO_FINDPATH_CMD = {
		CS_AUTO_FINDPATH_CMD_NONE = 0,
		CS_AUTO_FINDPATH_CMD_START = 1,
		CS_AUTO_FINDPATH_CMD_STOP = 2,
	},
	NoteType = {
		NOTE_TYPE_NONE = 0,
		NOTE_TYPE_FISH = 1,
		NOTE_TYPE_PRODUCTION = 2,
		NOTE_TYPE_COLLECTION = 3,
	},
	CS_NOTE_CMD = {
		CS_CMD_NOTE_NONE = 0,
		CS_CMD_NOTE_MARK = 1,
		CS_CMD_NOTE_MARK_LIST = 2,
		CS_CMD_NOTE_HISTORY_LIST = 3,
		CS_CMD_NOTE_CLOCK = 4,
		CS_CMD_NOTE_CLOCK_LIST_UPDATE = 5,
		CS_CMD_NOTE_CLOCK_SET = 6,
		CS_CMD_NOTE_NOTIFY_HISTORY_UPDATE = 9,
		CS_CMD_FISH_NOTE_BOOK_LIST = 7,
		CS_CMD_FISH_NOTE_NOTIFY_FISH_UPDATE = 10,
		CS_CMD_NOTE_QUERY_VERSION = 11,
		CS_CMD_NOTE_CANCEL_MARK = 12,
		CS_CMD_NOTE_CANCEL_CLOCK = 13,
		CS_CMD_NOTE_RED_POINT = 14,
		CS_CMD_NOTE_FISH_GROUND_RED_POINT = 15,
		CS_CMD_FISH_CLOCK_UPDATE = 16,
		CS_CMD_FISH_CLOCK_CANCEL = 17,
		CS_CMD_FISH_GROUND_QUERY = 18,
		CS_CMD_GROUND_UNLOCK = 19,
		CS_CMD_SCENE_FINISH_LOG = 20,
	},
	SpecialType = {
		SpecialTypeNone = 0,
		SpecialTypeSecret = 1,
		SpecialTypeInherit = 2,
		SpecialTypeCollection = 3,
	},
	NoteOps = {
		NoteOpsLevel = 0,
		NoteOpsProfVolume = 1,
		NoteOpsFishGround = 2,
	},
	ProfVolumeType = {
		ProfVolumeNone = 0,
		ProfVolumeSecret = 1,
		ProfVolumeInherit = 2,
		ProfVolumeCollection = 3,
	},
	CSOnlineStatusCmd = {
		CSOnlineStatusCmdNotifyIdentify = 0,
		CSOnlineStatusCmdQuery = 1,
		CSOnlineStatusCmdNotifyStatus = 2,
	},
	RouteType = {
		ROUTE_DEFAULT = 0,
		ROUTE_HASH = 1,
		ROUTE_INST = 2,
	},
	CS_CMD = {
		CS_CMD_START = 0,
		CS_CMD_CHECK_NAME = 1, --csproto.CheckNameReq
		CS_CMD_QUERY_ROLELIST = 2, --csproto.QueryRoleListByOpenIDReq
		CS_CMD_QUERY_ROLESIMPLE = 3, --csproto.QueryRoleListByIDListReq
		CS_CMD_REGISTER = 4, --csproto.RegisterRoleReq
		CS_CMD_LOGIN = 5, --csproto.RoleLoginReq
		CS_CMD_LOGOUT = 6, --csproto.RoleLogoutReq
		CS_CMD_VISION = 8, --csproto.VisionReq
		CS_CMD_MOVE = 9, --csproto.CSMoveReq
		CS_CMD_PWORLD = 10, --csproto.PWorldReq
		CS_CMD_COMBAT = 11, --csproto.CombatReq
		CS_CMD_ROLE_INFO = 12, --csproto.SimpleReq
		CS_CMD_TEAM = 13, --csproto.team.team.TeamReq
		CS_CMD_QUERY_ROLEDETAIL = 14, --csproto.QueryRoleDetailByIDListReq
		CS_CMD_MAP_AREA = 15, --csproto.MapAreaReq
		CS_CMD_COMM_STAT = 16, --csproto.CommStatReq
		CS_CMD_REVIVE = 17, --csproto.ReviveReq
		CS_CMD_TARGET = 18, --csproto.TargetReq
		CS_CMD_NPC = 19, --csproto.NpcReq
		CS_CMD_ACTIVITY = 20, --csproto.ActivityReq
		CS_CMD_SKILL = 21, --csproto.SkillRsp
		CS_CMD_RENAME = 22, --csproto.RenameReq
		CS_CMD_FRIENDS = 23, --csproto.Friend.friends.csFriendsReq
		CS_CMD_WEATHER = 24, --csproto.WeatherReq
		CS_CMD_QUERY_HISTORY_NAME = 25, --csproto.profile.prelogin.QueryNameHistoryReq
		CS_CMD_QUERY_EQUIP_GEM = 26, --csproto.profile.prelogin.QueryEquipGemReq
		CS_CMD_SUMMON_BEAST = 27, --csproto.role.summonbeast.SummonBeastReq
		CS_CMD_QUERY_LAST_LOGIN_ROLES = 28, --csproto.profile.friendrecall.QueryLastLoginRolesByOpenIDsReq
		CS_CMD_TRAVEL = 29, --csproto.travel.TravelReq
		CS_CMD_PROF = 30, --csproto.ProfReq
		CS_CMD_EQUIPMENT = 31, --csproto.CsEquipReq
		CS_CMD_SCORE = 32, --csproto.ScoreReq
		CS_CMD_BAG = 33, --csproto.BagMsgReq
		CS_CMD_QUEST = 34, --csproto.QuestReq
		CS_CMD_LOOT = 36, --csproto.LootItemUpdateRsp
		CS_CMD_LIFE_SKILL = 37, --csproto.LifeSkillReq
		CS_CMD_EMOTION = 38, --csproto.EmotionReq
		CS_CMD_CHATC = 39, --csproto.ChatsReq
		CS_CMD_TELEPORT_CRYSTAL = 40, --csproto.TeleportCrystalReq
		CS_CMD_INTERAVIVE = 41, --csproto.InteractionReq
		CS_CMD_COUNTER = 42, --csproto.CounterReq
		CS_CMD_DEPOT = 43, --csproto.DepotMsgReq
		CS_CMD_DEBUG = 44, --csproto.DebugReq
		CS_CMD_LINKSHELL = 45, --csproto.groupchat.linkshells.LinkShellReq
		CS_CMD_MOUNT = 46, --csproto.MountReq
		CS_CMD_TEAM_RECRUIT = 48, --csproto.team.teamrecruit.TeamRecruitReq
		CS_CMD_ROLL = 49, --csproto.RollReq
		CS_CMD_ADVENTURE = 50, --csproto.AdventureReq
		CS_CMD_QUERY_ROLE_ITEM_INFO = 51, --csproto.QueryRoleItemReq
		CS_CMD_BONUS_STATE = 52, --csproto.BonusStateReq
		CS_CMD_ONLINE_STATUS = 53, --csproto.CSOnlineStatusReq
		CS_CMD_CLIENT_REPORT = 54, --csproto.ClientReportReq
		CS_CMD_MESSAGE_BOARD = 55, --csproto.MessageBoardReq
		CS_CMD_PAY = 56, --csproto.PayReq
		CS_CMD_GUIDE = 58, --csproto.GuideOptReq
		CS_CMD_MODULE_OPEN = 59, --csproto.ModuleOpenReq
		CS_CMD_HOPE = 60, --csproto.HopeReq
		CS_CMD_MATCH = 61, --csproto.csMatchReq
		CS_CMD_VOTE = 62, --csproto.VoteOpReq
		CS_CMD_JUDGE_SEARCH_INPUT = 63, --csproto.JudgeSearchInputReq
		CS_CMD_BUDDY = 64, --csproto.BuddyReq
		CS_CMD_COMPANION = 65, --csproto.CompanionReq
		CS_CMD_MALL_AND_STORE = 66, --csproto.CsMallAndStoreReq
		CS_CMD_TITLE = 67, --csproto.TitleOptReq
		CS_CMD_CHOCOBO_TRANSFER = 68, --csproto.ChocoboTransferReq
		CS_CMD_PERFORM = 69, --csproto.PerformReq
		CS_CMD_CHOCOBO = 70, --csproto.ChocoboReq
		CS_CMD_CHOCOBO_RACE = 71, --csproto.ChocoboRaceReq
		CS_CMD_FACE_DATA = 72, --csproto.CsFaceDataReq
		CS_CMD_MARKING = 73, --csproto.MarkingReq
		CS_CMD_ACHIEVEMENT = 74, --csproto.CsAchievementReq
		CS_CMD_PERFORM_ACTION = 75, --csproto.PerformActionRsp
		CS_CMD_LEGENDARY_WEAPON = 76, --csproto.LegendaryWeaponReq
		CS_CMD_CLOSET = 77, --csproto.CsClosetReq
		CS_CMD_LATENCY = 78, --latency.Latency
		CS_CMD_CLIENT_OPERATION = 79, --csproto.ClientOperationReq
		CS_CMD_SYS_NOTICE = 80, --csproto.SysNoticeRsp
		CS_CMD_NAVMESH = 81, --navmesh.FindPathReq
		CS_CMD_SEARCH = 82, --csproto.role.search.CsSearchReq
		CS_CMD_COLOSSEUM_COMBAT = 83, --colosseum.ColosseumCombatReq
		CS_CMD_LOGIC_TIME = 93, --csproto.LogicTimeReq
		CS_CMD_SAMPLE = 94, --csproto.SampleReq
		CS_CMD_LOGIN_ENTER = 95, --csproto.EnterSceneReq
		CS_CMD_RECONNECT = 96, --csproto.ReconnectReq
		CS_CMD_CLIENT_CFG = 97, --csproto.ClientSetupReq
		CS_CMD_CONFIG = 98, --csproto.ModuleConfigReq
		CS_CMD_ERR = 99, --common.CommonErrRsp
		CS_CMD_GM = 100, --csproto.CSGMReq
		CS_ACE_GM = 101, --csproto.externalserviceagent.ace.CsAceReq
		CS_CMD_PRELOGIN = 102, --csproto.profile.prelogin.CsPreLoginReq
		CS_CMD_REDPOSITION = 103, --csproto.profile.redposition.CsRedPositionReq
		CS_CMD_PLAYPRIVACY = 104, --csproto.profile.mix.CsPlayerPrivacyReq
		CS_CMD_MIXNOTIFY = 105, --csproto.profile.mix.CsMixNotifyClientReq
		CS_CMD_PLAYERREPORT = 106, --csproto.externalserviceagent.playerreport.PlayerReportReq
		CS_CMD_MEETTRADE = 199, --csproto.CSMeetTradeReq
		CS_CMD_FANTASYCARD = 201, --csproto.EntertainFantasyCardReq
		CS_CMD_MINI_CACTPOT = 202, --csproto.EntertainMiniCactpotReq
		CS_CMD_FATE = 203, --csproto.FateReq
		CS_CMD_FAIRY_COLOR = 204, --csproto.GameFairyColorReq
		CS_CMD_GOLD_SAUSER = 205, --csproto.GoldSauserReq
		CS_CMD_FASHION_CHECK = 206, --csproto.game.fashioncheck.Req
		CS_CMD_GOLD_SAUSER_MAIN = 207, --csproto.GoldSauserMainReq
		CS_CMD_BARBER_SHOP = 208, --csproto.game.barbershop.Req
		CS_CMD_MATCH_CONFIRM = 209, --csproto.MatchConfirmReq
		CS_CMD_WILD_BOX = 210, --csproto.game.wildbox.Req
		CS_CMD_MYSTER_MERCHANT = 211, --csproto.game.mysterymerchant.Req
		CS_CMD_PvPColosseum = 212, --csproto.game.pvpcolosseum.PvPColosseumReq
		CS_CMD_TOURING_BAND = 213, --csproto.game.touringband.Req
		CS_CMD_QUESTIONNAIRE = 214, --csproto.game.questionnaire.Req
		CS_CMD_ACTIVITY_SYSTEM = 215, --csproto.game.activity.Req
		CS_CMD_MONSTORHUNT = 216, --csproto.game.monstorhunt.CSMonstorHuntReq
		CS_CMD_TRIBE = 217, --csproto.role.tribe.TribeReq
		CS_CMD_ZeroSceneRank = 218, --csproto.game.zeroscenerank.ZeroSceneRankReq
		CS_CMD_DIRECT_UPGRADE = 219, --csproto.role.directupgrade.Req
		CS_CMD_LIGHT_JOURNEY = 220, --csproto.role.lightjourney.LightJourneyReq
		CS_CMD_WINDPULSE = 401, --csproto.WindPulseReq
		CS_CMD_ALONE_TREE = 402, --csproto.AloneTreeReq
		CS_CMD_FOG = 403, --csproto.ExploreFogReq
		CS_CMD_MONTH_CARD = 404, --csproto.MonthCardReq
		CS_CMD_PERSONAL_HEADER = 407, --csproto.role.portrait.PersonalPortraitReq
		CS_CMD_MUSIC = 408, --csproto.MusicOptReq
		CS_CMD_LEVE_QUEST = 409, --csproto.levequest.LeveQuestReq
		CS_CMD_ENTOURAGE = 410, --csproto.entourage.EntourageReq
		CS_CMD_BASKETBALL = 411, --csproto.MonsterBasketballReq
		CS_CMD_BATTLE_PASS = 412, --csproto.battlepass.BattlePassReq
		CS_CMD_CRYSTAL_TOWER = 413, --csproto.CrystalTowerReq
		CS_CMD_GILGAMESH = 414, --csproto.GilgameshReq
		CS_CMD_PERSONAL_PIC = 415, --csproto.PersonalPortraitReq
		CS_CMD_FANTASY_MEDICINE = 416, --csproto.FantasyMedicineReq
		CS_CMD_PHOTOS = 417, --csproto.role.photos.PhotosReq
		CS_CMD_GRAND_COMPANY = 418, --csproto.role.grandcompany.GrandCompanyReq
		CS_CMD_EXCHANGE = 419, --csproto.role.exchange.ExchangeReq
		CS_CMD_MARKET = 420, --csproto.MarketOptReq
		CS_CMD_HEAD_PORTRAIT = 421, --csproto.role.portrait.HeadPortraitReq
		CS_CMD_HEADER_FRAME = 422, --csproto.role.headerframe.CsHeaderFrameReq
		CS_CMD_FAIRY_BLESSED = 423, --csproto.game.fairyblessed.FairyBlessedReq
		CS_CMD_FASHION_DECORATE = 424, --csproto.role.fashiondecorate.CsFashionDecorateReq
		CS_CMD_GROUP = 500, --csproto.CsGroupMsgReq
		CS_CMD_NOTE = 501, --csproto.CsNoteMsgReq
		CS_CMD_COLLECT = 502, --csproto.CsCollectMsgReq
		CS_CMD_MAIL = 503, --csproto.mail.mail.MailMsgReq
		CS_CMD_TREASURE_HUNT = 504, --csproto.game.treasurehunt.TreasureHuntReq
		CS_CMD_CATCH_BALL = 505, --csproto.CatchBallReq
		CS_CMD_FOOT_PRINT = 506, --csproto.FootprintMsgReq
		CS_CMD_SEARCH_NOTE = 507, --csproto.SearchNoteReq
		CS_CMD_LANTERN = 508, --csproto.game.lantern.LanternReq
		CS_CMD_AREA_MAIL = 509, --csproto.game.areamail.AreaMailReq
		CS_CMD_AREA_CLEAN = 510, --csproto.game.areaclean.AreaCleanReq
		CS_CMD_CHOOSETREASURECHEST = 511, --csproto.game.choosetreasurechest.ChooseTreasureChestReq
		CS_CMD_BLINDBOX = 512, --csproto.game.blindbox.BlindBoxReq
		CS_CMD_AUTOFINDPATH = 513, --navmesh.AutoFindPathReq
		CS_CMD_FOOT_MARK = 600, --csproto.CsFootMarkMsgReq
	},
	CS_PAY_CMD = {
		CS_CMD_PAY_INVALID = 0,
		CS_CMD_PAY_QUERY_RECHARGE_AWARD = 1,
		CS_CMD_PAY_RECHARGE_AWARD = 2,
		CS_CMD_PAY_DISTRIBUTE_ORDER = 3,
		CS_CMD_PAY_DISTRIBUTE_NOTIFY = 4,
		CS_CMD_PAY_DISTRIBUTE_COUPON = 5,
	},
	DevicePlatform = {
		DevicePlatformNone = 0,
		DevicePlatformAndroid = 1,
		DevicePlatformIOS = 2,
	},
	PerformCmd = {
		PerformCmdNone = 0,
		PerformCmdEnter = 1,
		PerformCmdExit = 2,
		PerformCmdPerform = 3,
		PerformCmdUpdateTimbre = 4,
		EnsembleCmdQuery = 10,
		EnsembleCmdAskConfirm = 11,
		EnsembleCmdConfirm = 12,
		EnsembleCmdEnsemble = 13,
		EnsembleCmdExit = 14,
		EnsembleCmdNotifyReady = 21,
	},
	EnsembleStatus = {
		EnsembleStatusNone = 0,
		EnsembleStatusPerform = 1,
		EnsembleStatusConfirm = 2,
		EnsembleStatusReady = 3,
		EnsembleStatusEnsemble = 4,
		EnsembleStatusResult = 5,
	},
	Status = {
		None = 0,
		Yes = 1,
		No = 2,
	},
	ProfSubMsg = {
		ProfSubMsgStart = 0,
		ProfSubMsgActive = 1,
		ProfSubMsgSwitch = 2,
		ProfSubMsgLevelUp = 3,
		ProfSubMsgCamp = 4,
	},
	LevelUpReason = {
		LevelUpReasonProf = 0,
		LevelUpReasonScene = 1,
	},
	CS_PWORLD_CMD = {
		CS_PWORLD_CMD_INVALID = 0,
		CS_PWORLD_CMD_ENTER = 1,
		CS_PWORLD_CMD_LEAVE = 2,
		CS_PWORLD_CMD_RESULT = 3,
		CS_PWORLD_CMD_PROGRESS = 4,
		CS_PWORLD_CMD_TRANS = 5,
		CS_PWORLD_CMD_MAP_DYN_DATA_LIST = 6,
		CS_PWORLD_CMD_MAP_DYN_DATA_UPDATE = 7,
		CS_PWORLD_CMD_COUNT_DOWN = 8,
		CS_PWORLD_CMD_SHARED_GROUP_LIST = 9,
		CS_PWORLD_CMD_SHARED_GROUP_UPDATE = 10,
		CS_PWORLD_CMD_SHARED_GROUP_VISIBILITY = 11,
		CS_PWORLD_CMD_LACK_OF_RESOURCE = 12,
		CS_PWORLD_CMD_BEGIN = 13,
		CS_PWORLD_CMD_READY = 14,
		CS_PWORLD_CMD_VIDEO_BEGIN = 15,
		CS_PWORLD_CMD_VIDEO_END = 16,
		CS_PWORLD_CMD_SWITCH_CAMERA = 17,
		CS_PWORLD_CMD_PROGRESS_SLOT = 18,
		CS_PWORLD_CMD_PLAY_AUDIO = 19,
		CS_PWORLD_CMD_TRIGGER_ACTION_EXEC = 20,
		CS_PWORLD_CMD_WARNING = 21,
		CS_PWORLD_CMD_BOSS_TRANS = 22,
		CS_PWORLD_CMD_NAVIMESH_FINDPATH = 23,
		CS_PWORLD_CMD_VOTE_START = 24,
		CS_PWORLD_CMD_VOTE_REPLY = 25,
		CS_PWORLD_CMD_VOTE_RESULT = 26,
		CS_PWORLD_CMD_VOTE_CANCEL = 27,
		CS_PWORLD_CMD_MVP_VOTE = 28,
		CS_PWORLD_CMD_MVP_INFO = 29,
		CS_PWORLD_CMD_DEBUG_SWITCH = 30,
		CS_PWORLD_CMD_DEBUG_EVENT_LIST = 31,
		CS_PWORLD_CMD_DEBUG_ACTION_EXEC = 32,
		CS_PWORLD_CMD_DEBUG_ACTION_CANCEL = 33,
		CS_PWORLD_CMD_VARIABLE_LIST = 34,
		CS_PWORLD_CMD_VARIABLE_UPDATE = 35,
		CS_PWORLD_CMD_ADD_MEMBERS = 36,
		CS_PWORLD_CMD_CANCEL_ADD_MEMBERS = 37,
		CS_PWORLD_CMD_FINISHED = 38,
		CS_PWORLD_CMD_TEMPORARY_TEAM_MEM_STAT_CHG = 39,
		CS_PWORLD_CMD_LAYER_SET_CHANGED = 40,
		CS_PWORLD_CMD_SET_SELF_DATA = 41,
		CS_PWORLD_CMD_SELF_DATA_NTF = 42,
		CS_PWORLD_CMD_RELOGIN_DATA_RECOVER = 43,
		CS_PWORLD_CMD_MAP_COUNT_DOWN = 44,
		CS_PWORLD_CMD_LINE_QUERY = 45,
		CS_PWORLD_CMD_LINE_ENTER = 46,
		CS_PWORLD_CMD_SCENE_TEAM_QUERY = 47,
		CS_PWORLD_CMD_QUERY_SCENE_MEMBER = 48,
		CS_PWORLD_CMD_SCENE_MEMBER_ENTER = 49,
		CS_PWORLD_CMD_SCENE_MEMBER_LEAVE = 50,
		CS_PWORLD_CMD_SCENE_TEAM_MEMBER_STATUS = 51,
		CS_PWORLD_CMD_MECHANISM_DATA = 52,
		CS_PWORLD_CMD_QUERY_ROLE_DATA = 53,
	},
	EnterFlag = {
		EnterFlagBefore = 0,
		EnterFlagReConnect = 1,
		EnterFlagAfter = 2,
		EnterFlagBeforeReConnect = 3,
	},
	PWorldEnterTag = {
		PWorldEnterTagNone = 0,
		PWorldEnterTagNewbie = 1,
		PWorldEnterTagDailyRandomID = 2,
		PWorldEnterTagIsMatch = 3,
		PWorldEnterTagTransID = 4,
		PWorldEnterTagIsFinished = 5,
		PWorldEnterTagLineID = 6,
		PWorldEnterTagPerform = 7,
	},
	ExternalType = {
		ExternalTypeNone = 0,
		ExternalTypeMount = 1,
	},
	PWORLD_TRANS_TYPE = {
		PWORLD_TRANS_TYPE_INVALID = 0,
		PWORLD_TRANS_TYPE_POINT = 1,
		PWORLD_TRANS_TYPE_BOSS = 2,
		PWORLD_TRANS_TYPE_EXIT_RANGE = 3,
	},
	ResourceType = {
		Invalid = 0,
		Map = 1,
		PWorldInstID = 1,
		Type = 2,
	},
	ElevatorCtrl = {
		ElevatorCtrlForward = 0,
		ElevatorCtrlBackward = 1,
	},
	VideoFlag = {
		VIDEO_FLAG_FINISH = 0,
		VIDEO_FLAG_INTERRUPT = 1,
		SEQUENCE_FLAG_FINISH = 0,
		SEQUENCE_FLAG_INTERRUPT = 1,
		SEQUENCE_FLAG_CONTINUE = 2,
	},
	PWorldVoteCancelReason = {
		PWROLD_VOTE_CANCEL_UNKNOWN = 0,
		PWROLD_VOTE_CANCEL_MEM_CHG = 1,
		PWROLD_VOTE_CANCEL_KICK_LEAVE = 2,
		PWROLD_VOTE_CANCEL_SCENE_FINISHED = 3,
		PWROLD_VOTE_CANCEL_SCENE_ACTIVE = 4,
	},
	PWorldEventStatus = {
		PWROLD_EVENT_CLOSED = 0,
		PWROLD_EVENT_OPENED = 1,
		PWROLD_EVENT_EXECUTING = 2,
	},
	SceneTeamEntityType = {
		SceneTeamEntityTypePlayer = 0,
		SceneTeamEntityTypeFaith = 1,
	},
	Operate = {
		List = 0,
		Add = 1,
		Remove = 2,
		Update = 3,
		Entities = 1,
		Op = 2,
	},
	CS_QUEST_CMD = {
		QUEST_LIST_CMD = 0,
		QUEST_ACCEPT_CMD = 1,
		QUEST_SUBMIT_CMD = 2,
		QUEST_GIVEUP_CMD = 3,
		QUEST_TARGET_FINISH_CMD = 5,
		QUEST_UPDATE_NOTIFY_CMD = 6,
		QUEST_TRACK_CMD = 7,
		QUEST_GET_TRACK_CMD = 8,
		QUEST_CLEAR_CMD = 9,
		QUEST_GET_DISPLAY_DATA = 10,
		QUEST_TARGET_REVERT = 11,
		QUEST_FAULT_TOLERANT = 12,
		QUEST_AREA_SCENE = 13,
		QUEST_TRIGGER_ACTION = 14,
	},
	CS_QUEST_STATUS = {
		CS_QUEST_STATUS_NOT_STARTED = 0,
		CS_QUEST_STATUS_IN_PROGRESS = 1,
		CS_QUEST_STATUS_CAN_SUBMIT = 2,
		CS_QUEST_STATUS_FINISHED = 3,
		CS_QUEST_STATUS_FAILED = 4,
	},
	CS_QUEST_NODE_STATUS = {
		CS_QUEST_NODE_STATUS_NOT_STARTED = 0,
		CS_QUEST_NODE_STATUS_IN_PROGRESS = 1,
		CS_QUEST_NODE_STATUS_FINISHED = 2,
		CS_QUEST_NODE_STATUS_FAILED = 3,
	},
	QuestUserDataKey = {
		QuestUserDataKeyMonster = 0,
		QuestUserDataKeyGuardEntityID = 1,
	},
	MonsterType = {
		None = 0,
		Owned = 1,
		FollowNPC = 2,
		Wild = 3,
	},
	ChocoboRaceCmd = {
		ChocoboRaceCmdQuery = 0,
		ChocoboRaceCmdJoin = 1,
		ChocoboRaceCmdReady = 2,
		ChocoboRaceCmdCtrl = 3,
		ChocoboRaceCmdPickup = 4,
		ChocoboRaceCmdUpdate = 5,
		ChocoboRaceCmdResult = 6,
		ChocoboRaceCmdBuff = 7,
		ChocoboRaceCmdQueryProgress = 8,
		ChocoboRaceReward = 9,
		ChocoboRaceQueryResult = 10,
		ChocoboRaceQueryReward = 11,
		ChocoboRaceOnceStatus = 12,
		ChocoboRaceNpcchallengeData = 13,
		ChocoboRaceStartNpcchallenge = 14,
		ChocoboRaceAllUserIn = 15,
		ChocoboRaceDebugInfo = 16,
		ChocoboRaceSkillCDChange = 17,
	},
	ChocoboRaceConst = {
		ChocoboRaceConstInvalid = 0,
		ChocoboRaceConstRacerNum = 8,
	},
	ChocoboRaceMode = {
		ChocoboRaceModeRoom = 0,
		ChocoboRaceModeRanking = 1,
		ChocoboRaceModeChallenge = 2,
	},
	ChocoboRaceStatus = {
		ChocoboRaceStatusNone = 0,
		ChocoboRaceStatusReady = 1,
		ChocoboRaceStatusRunning = 2,
		ChocoboRaceStatusGoal = 4,
		ChocoboRaceStatusResult = 5,
		ChocoboRaceStatusQuit = 6,
	},
	ChocoboRaceCtrl = {
		ChocoboRaceParamLeft = 0,
		ChocoboRaceParamRight = 1,
		ChocoboRaceParamAbilityAcc = 2,
		ChocoboRaceParamAbilityJump = 3,
		ChocoboRaceParamAbility1 = 4,
		ChocoboRaceParamAbility2 = 5,
		ChocoboRaceParamAbility3 = 6,
		ChocoboRaceParamAbilityItem = 7,
	},
	ChocoboRacerStatus = {
		ChocoboRacerStatusNormal = 0,
		ChocoboRacerStatusAcc = 1,
		ChocoboRacerStatusBrake = 2,
		ChocoboRacerStatusGoal = 3,
		ChocoboRacerStatusArrived = 4,
	},
	ChocoboRacerOneceStatus = {
		ChocoboRacerStatusOnceFieldRefound = 0,
		ChocoboRacerStatusOnceDash = 1,
	},
	CS_ROLL_CMD = {
		ROLL_CMD_INVALID = 0,
		OPERATE = 1,
		AWARD_NOTIFY = 2,
		ROLL_NOTIFY = 3,
		BELONG_NOTIFY = 4,
		RollQuery = 5,
	},
	ROLL_OPERATE = {
		ROLL_INVALID = 0,
		DEMAND = 1,
		GIVE_UP = 2,
	},
	CS_SCORE_CMD = {
		SCORE_SELECT_CMD = 0,
		SCORE_CONVERT_CMD = 1,
		SCORE_UPDATE_CMD = 2,
		SCORE_ITERATION_CONVERT_CMD = 3,
		SCORE_LIMIT_INFO = 4,
	},
	SearchNoteCmd = {
		SearchNoteCmdNone = 0,
		SearchNoteCmdQuery = 1,
		SearchNoteCmdNotify = 2,
	},
	FlagBit = {
		FlagBitEmotionClueIdx = 0,
		FlagBitWeatherClueIdx = 1,
		FlagBitTimeClueIdx = 2,
		FlagBitNormalIdx = 3,
		FlagBitPerfectIdx = 4,
		FlagBitUnPerfectIdx = 5,
	},
	RenameCmd = {
		RenameCmdNone = 0,
		RenameCmdRename = 1,
		RenameCmdNotify = 2,
	},
	SkillSubMsg = {
		SkillSubMsgStart = 0,
		SkillSubMsgReplace = 2,
	},
	Team = {
		Team = {
			TEAM_CONST = {
				TEAM_CONST_START = 0,
				MAX_TEAM_MEMBER_COUNT = 8,
			},
			CS_SUBMSGID_TEAM = {
				CS_SUB_CMD_TEAM_START = 0,
				CS_SUB_CMD_TEAM_LEAVE = 3,
				CS_SUB_CMD_TEAM_DESTROY = 4,
				CS_SUB_CMD_TEAM_INVITE_JOIN = 7,
				CS_SUB_CMD_TEAM_ANSWER_INVITE = 8,
				CS_SUB_CMD_TEAM_SET_CAPTAIN = 9,
				CS_SUB_CMD_TEAM_KICK_MEMBER = 11,
				CS_SUB_CMD_TEAM_ASK_VOTE = 12,
				CS_SUB_CMD_TEAM_ANSWER_VOTE = 13,
				CS_SUB_CMD_TEAM_QUERY_TEAM = 14,
				CS_SUB_CMD_TEAM_SET_SELF_DATA = 19,
				CsSubCmdQueryByTeamID = 20,
				CS_SUB_CMD_TEAM_UPDATE_MEMBER = 10,
				CS_SUB_CMD_TEAM_JOIN_NOTIFY = 21,
				CS_SUB_CMD_TEAM_LEAVE_NOTIFY = 22,
				CS_SUB_CMD_TEAM_DESTROY_NOTIFY = 23,
				CS_SUB_CMD_TEAM_INVITEJOIN_NOTIFY = 26,
				CS_SUB_CMD_TEAM_CAPTAINCHANGED_NOTIFY = 27,
				CS_SUB_CMD_TEAM_TASKCHANGED_NOTIFY = 28,
				CS_SUB_CMD_TEAM_ASK_VOTE_NOTIFY = 29,
				CS_SUB_CMD_TEAM_ANSWER_VOTE_NOTIFY = 30,
				CS_SUB_CMD_TEAM_REFUSE_INVITE_NOTIFY = 31,
				CS_SUB_CMD_TEAM_COMMSTAT_NOTIFY = 32,
				CS_SUB_CMD_TEAM_BROADCAST = 33,
				CS_SUB_CMD_TEAM_MEMBER_DATA_NTF = 34,
				CS_SUB_CMD_TEAM_ROLE_JOIN_TEAM_NTF = 35,
				CsSubCmdTeamQueryRoleInfo = 36,
				CsQueryTeamMemberLocation = 37,
				CsQueryTeamMemberData = 38,
			},
			JOIN_TEAM_REASON = {
				JOIN_TEAM_RELATION = 0,
				JOIN_TEAM_APPLY = 1,
				JOIN_TEAM_SYSTEM = 2,
				JOIN_TEAM_CREATE = 3,
				JOIN_TEAM_INVITE = 4,
				JOIN_TEAM_RECRUIT = 5,
			},
			LEAVE_TEAM_REASON = {
				LEAVE_TEAM_SELF = 0,
				LEAVE_TEAM_LOGOUT = 1,
				LEAVE_TEAM_KICKOFF = 2,
				LEAVE_TEAM_TEAM_DESTROY = 3,
				LEAVE_TEAM_LOGOUTCLEAR = 4,
			},
			ReqSource = {
				ReqSourceUnknown = 0,
				ReqSourceFriend = 1,
				ReqSourceRecent = 2,
				ReqSourceNearby = 3,
				ReqSourceGroup = 4,
				ReqSourceNewbieChannel = 5,
				ReqSourceAreaChannel = 6,
				ReqSourceGroupChannel = 7,
				ReqSourceRecruit = 10,
			},
			ChangeCaptainReason = {
				ChangeCaptainReasonUnknown = 0,
				ChangeCaptainReasonSelf = 1,
				ChangeCaptainReasonCaptainLeave = 2,
				ChangeCaptainReasonOffline = 3,
			},
			MemPropUpdate = {
				MemPropUpdate_Unknow = 0,
				MemPropUpdate_Login = 1,
				MemPropUpdate_Logout = 2,
				MemPropUpdate_EnterScene = 3,
				MemPropUpdate_Prof = 4,
				MemPropUpdate_ProfLevel = 5,
			},
			TEAM_VOTE_TYPE = {
				TEAM_VOTE_TYPE_START = 0,
				TEAM_VOTE_TYPE_ENTERPWORLD = 1,
				TEAM_VOTE_TYPE_KICKROLE = 2,
			},
			TeamBroadcastType = {
				TeamEventUnknow = 0,
				TeamMemStateChg = 1,
			},
			MemStateType = {
				MemStateTypeUnknown = 0,
				MemStateTypeLogin = 1,
				MemStateTypeLogout = 2,
				MemStateTypeEnterScene = 3,
				MemStateTypeDie = 4,
				MemStateTypeRevive = 5,
				MemStateDisplayTag = 6,
			},
			TeamMemberDataQueryType = {
				TeamMemberDataQueryTypeLocation = 0,
				TeamMemberDataQueryTypeCounter = 1,
			},
		},
		TeamRecruit = {
			CS_SUBMSGID_TEAM_RECRUIT = {
				CS_SUBMSGID_TEAM_RECRUIT_UNKNOW = 0,
				CS_SUBMSGID_TEAM_RECRUIT_CREATE = 1,
				CS_SUBMSGID_TEAM_RECRUIT_UPDATE = 2,
				CS_SUBMSGID_TEAM_RECRUIT_QUERY = 3,
				CS_SUBMSGID_TEAM_RECRUIT_OPEN = 4,
				CS_SUBMSGID_TEAM_RECRUIT_CLOSE = 5,
				CS_SUBMSGID_TEAM_RECRUIT_GET_LIST = 6,
				CS_SUBMSGID_TEAM_RECRUIT_JOIN = 7,
				CS_SUBMSGID_TEAM_RECRUIT_INDEX = 8,
				CS_SUBMSGID_TEAM_RECRUIT_QUERY_SELF = 9,
				CS_SUBMSGID_TEAM_RECRUIT_QUERY_RELATION = 10,
				CS_SUBMSGID_TEAM_RECRUIT_QUERY_RELATION_INFO = 11,
				CS_SUBMSGID_TEAM_RECRUIT_CREATE_NTF = 30,
				CS_SUBMSGID_TEAM_RECRUIT_COMPLETE_NTF = 31,
				CS_SUBMSGID_TEAM_RECRUIT_CLOSE_NTF = 32,
				CS_SUBMSGID_TEAM_RECRUIT_JOIN_NTF = 33,
			},
			RECRUIT_STATE = {
				RECRUIT_STATE_CLOSE = 0,
				RECRUIT_STATE_OPEN = 1,
			},
			TASK_LIMIT = {
				TASK_LIMIT_UNKNOW = 0,
				TASK_LIMIT_CHALLENGE = 1,
				TASK_LIMIT_FREE_UNLIMITED = 2,
				TASK_LIMIT_FREE_ORIENTATION = 3,
			},
			UPDATE_RECRUIT = {
				UPDATE_RECRUIT_UNKNOW = 0,
				UPDATE_RECRUIT_CONTENT = 1,
				UPDATE_RECRUIT_MESSAGE = 2,
				UPDATE_RECRUIT_PROF = 3,
				UPDATE_RECRUIT_TASKLIMIT = 4,
				UPDATE_RECRUIT_PASSWORD = 5,
				UPDATE_RECRUIT_EQUIP_LEVEL = 6,
				UPDATE_RECRUIT_TASKS = 7,
				UPDATE_QUICK_MESSAGE = 8,
				UPDATE_RECRUIT_ZERO_FORM_AWARD = 9,
			},
			CloseReason = {
				CloseReasonDefault = 0,
				CloseReasonEdit = 1,
				CloseReasonFull = 2,
				CloseReasonTimeout = 3,
			},
		},
	},
	CS_SUBMSGID_TELEPORT_CRYSTAL = {
		START = 0,
		CRYSTAL_INFO = 1,
		ACTIVATE_CRYSTAL = 2,
		ACTIVATE_NTF = 3,
		TRANSFER = 4,
		TRANSFER_NTF = 5,
		QueryOther = 6,
		CROSS_WORLD_TRANSFER = 7,
	},
	TitleOptCmd = {
		TOCNone = 0,
		TOCTitle = 1,
		TOCTitleMsg = 2,
		TOCSet = 3,
		TOCCollect = 4,
		TOCUpdate = 5,
	},
	TitleCollectOpt = {
		TCOCollect = 0,
		TCOCancelCollect = 1,
	},
	Travel = {
		TravelCmd = {
			TravelCmdInvalid = 0,
			TravelCmdChange = 1,
		},
	},
	VoteSubCmd = {
		VoteSubCmd_Invaild = 0,
		VoteSubCmd_Poll = 1,
		VoteSubCmd_Vote = 2,
		VoteSubCmd_Query = 3,
		VoteSubCmd_PollNtf = 10,
		VoteSubCmd_VoteNtf = 11,
		VoteSubCmd_VoteResultNtf = 12,
		VoteSubCmd_PollTimeOutNtf = 13,
		VoteSubCmd_CancelVoteNtf = 14,
	},
	PollType = {
		PollType_Invaild = 0,
		PollType_EnterScene = 1,
		PollType_Chocobo = 2,
		PoolType_Tournament = 3,
		PoolType_CrystalConflict = 4,
	},
	VoteObjType = {
		VoteObjType_Self = 0,
		VoteObjType_Team = 1,
		VoteObjType_Match = 2,
		VoteObjType_Scene = 3,
	},
	EnterSceneOption = {
		EnterSceneSingle = 0,
		EnterSceneTeam = 1,
		EnterSceneMatch = 2,
	},
	CancelVoteReason = {
		CancelVoteReasonUnknow = 0,
		CancelVoteReasonTeamMemChg = 1,
		CancelVoteReasonTeamMemLogout = 2,
		CancelVoteReasonTeamCaptainChg = 3,
		CancelVoteReasonTeamDestory = 4,
	},
	WeatherCmd = {
		WeatherCmdNow = 0,
		WeatherCmdFuture = 1,
		WeatherCmdIndividual = 2,
	},
	CSWindPulseCmd = {
		WindPulseInvalid = 0,
		WindPulseDataSync = 1,
		WindPulseActivatePointSuccess = 2,
		WindPulseMapActivate = 3,
	},
}

return ProtoCS