-- AUTO GENERATED CODE, PLEASE DON'T MODIFY

local ProtoCommon = {
	ELEVATOR_STATUS = {
		ELEVATOR_STATUS_STOP = 0,
		ELEVATOR_STATUS_RUNNING = 1,
	},
	MapDynType = {
		MAP_DYNAMIC_DATA_TYPE_NONE = 0,
		MAP_DYNAMIC_DATA_TYPE_AREA = 1,
		MAP_DYNAMIC_DATA_TYPE_DYN_OBSTACLE = 2,
		MAP_DYNAMIC_DATA_TYPE_DYN_INSTANCE = 3,
		MAP_DYNAMIC_DATA_TYPE_TRANSPOINT = 4,
		MAP_DYNAMIC_DATA_TYPE_SWITCH = 5,
		MAP_DYNAMIC_DATA_TYPE_REVIVEPOINT = 6,
		MAP_DYNAMIC_DATA_TYPE_CAMPPOINT = 7,
		MAP_DYNAMIC_DATA_TYPE_BIRTHPOINT = 8,
		MAP_DYNAMIC_DATA_TYPE_WEATHER = 9,
		MAP_DYNAMIC_DATA_TYPE_MUSIC = 10,
		MAP_DYNAMIC_DATA_TYPE_MAP_SEQUENCE = 11,
		MAP_DYNAMIC_DATA_TYPE_MAP_MOVIE_SEQUENCE = 12,
		MAP_DYNAMIC_DATA_TYPE_MAP_WAY_POINT = 13,
	},
	DeadReason = {
		DEAD_REASON_NA = 0,
		DEAD_REASON_BUFF = 1,
		DEAD_REASON_SKILL = 2,
		DEAD_REASON_SYSTEM_RECYCLE = 3,
		DEAD_REASON_GM = 4,
		DEAD_REASON_SUICIDE = 5,
	},
	ITEM_TYPE = {
		ITEM_TYPE_START = 0,
		ITEM_TYPE_EQUIP = 1,
		ITEM_TYPE_GEM = 2,
		ITEM_TYPE_COLLECTION = 3,
		ITEM_TYPE_TASK = 4,
		ITEM_TYPE_DRUG = 5,
	},
	UnitType = {
		UNIT_NULL = 0,
		UNIT_ABSOLUTE = 1, --数值
		UNIT_WAN_RATE = 2, --万分比
	},
	PWorldType = {
		PWORLD_TYPE_MAZE_CHALLENGE = 0, --迷宫挑战
		PWORLD_TYPE_DAILY_PICK = 1, --每日随机
		PWORLD_TYPE_ATTACK_WAR = 2, --讨伐歼灭战
		PWORLD_TYPE_MASSIVE_TASK = 3, --大型任务
		PWORLD_TYPE_MAX = 4,
	},
	MonsterSourceType = {
		MONSTER_SOURCE_TYPE_NONE = 0,
		MONSTER_SOURCE_TYPE_ENTERTAIN_FATE = 1,
		MONSTER_SOURCE_TYPE_QUEST_OWNED = 2,
		MONSTER_SOURCE_TYPE_QUEST_FOLLOW = 3,
		MONSTER_SOURCE_TYPE_QUEST_WILD = 4,
		MONSTER_SOURCE_TYPE_TREASURE_HUNT = 5,
	},
	InteractiveObjType = {
		InteractiveObjTypeUnknown = 0,
		InteractiveObjTypeNPC = 1,
		InteractiveObjTypeCrystal = 2,
		InteractiveObjTypeEObj = 3,
	},
	MemStateType = {
		MemStateTypeUnknown = 0,
		MemStateTypeLogin = 1,
		MemStateTypeLogout = 2,
		MemStateTypeEnterScene = 3,
		MemStateTypeDie = 4,
		MemStateTypeRevive = 5,
	},
	SceneReason = {
		SceneReasonUnknown = 0,
		SceneReasonLogin = 1,
		SceneReasonChange = 2,
		SceneReasonLeave = 3,
		SceneReasonTrans = 4,
		SceneReasonVoteKick = 5,
		SceneReasonForceKick = 6,
		SceneReasonGiveUp = 7,
		SceneReasonOffline = 8,
	},
	AttachmentType = {
		UnknownType = 0,
		ItemType = 1,
		MallType = 2,
		FateMailType = 3,
	},
	RouteMode = {
		ROUTE_RAND = 0,
		ROUTE_HASH = 1,
		ROUTE_INST = 2,
	},
	RouteKey = {
		ROUTE_KEY_GATE = 0,
		ROUTE_KEY_ZONE = 1,
		ROUTE_KEY_SCENE = 2,
		ROUTE_KEY_CELL = 3,
		ROUTE_KEY_TEAM = 4,
		ROUTE_KEY_OPENID = 5,
		ROUTE_KEY_ROLE = 6,
		ROUTE_KEY_FANTASYCARD = 7,
		ROUTE_KEY_MINICACTPOT = 8,
		ROUTE_KEY_CHOCOBORACE = 9,
		ROUTE_KEY_MAX = 300,
	},
	YesNo = {
		MACRO_NO = 0, --否
		MACRO_YES = 1, --是
	},
	EntityType = {
		EntityTypeNull = 0,
		EntityTypePlayer = 1,
		EntityTypeMonster = 2,
		EntityTypePickItem = 4,
		EntityTypeEObj = 5,
		EntityTypeNpc = 6,
		EntityTypeBNpc = 7,
		EntityTypeMax = 8,
	},
	attr_type = {
		attr_null = 0,
		attr_force = 1, --力量
		attr_agility = 2, --敏捷
		attr_dexterous = 3, --灵巧
		attr_wisdom = 4, --智力
		attr_mind = 5, --精神
		attr_stamina = 6, --耐力
		attr_hp_max = 7, --体力上限
		attr_mp_max = 8, --魔力上限
		attr_hp_recover = 9, --体力回复
		attr_mp_recover = 10, --魔力回复
		attr_atk = 11, --攻击力
		attr_physic_def = 12, --物理防御
		attr_physic_immune_atk_rate = 13, --物理免伤率
		attr_magic_def = 14, --魔法防御
		attr_magic_immune_atk_rate = 15, --魔法免伤率
		attr_move_speed = 16, --移动速度
		attr_belief = 17, --信念
		attr_critical = 18, --暴击
		attr_cri_rate = 19, --暴击发生概率
		attr_cri_multiple = 20, --暴击倍率
		attr_direct_atk = 21, --直击
		attr_direct_atk_rate = 22, --直击发生概率
		attr_quick = 23, --急速
		attr_shorten_action_time = 24, --动作时间缩短
		attr_shorten_cd_time = 25, --冷却时间缩短
		attr_shorten_sing_time = 26, --咏唱时间缩短
		attr_puncture = 27, --穿刺
		attr_ductility = 28, --韧性
		attr_group_assist_add_hurt = 29, --团辅增伤率
		attr_group_assist_sub_hurt = 30, --团辅减伤率
		attr_add_hurt = 31, --非团辅增伤率
		attr_sub_hurt = 32, --非团辅减伤率
		attr_special_add_hurt = 33, --特殊增伤率
		attr_special_sub_hurt = 34, --特殊减伤率
		attr_monster_add_atk = 35, --对怪物伤害加成
		attr_monster_sub_beatk = 36, --受怪物伤害降低
		attr_move_acc = 37, --移动加速度
		attr_heal_rate = 38, --治疗率
		attr_be_heal_rate = 39, --被治疗率
		attr_be_remote_prof_hurt_derate = 40, --受远程职业伤害减免
		attr_to_remote_prof_hurt_add = 41, --对远程职业伤害增加
		attr_physic_resist = 42, --物理抗性
		attr_magic_resist = 43, --魔法抗性
		attr_combat_slash = 45, --斩击耐性
		attr_combat_stick = 46, --刺击耐性
		attr_combat_beat = 47, --打击耐性
		attr_combat_pichak = 48, --吐息耐性
		attr_combat_shoot = 49, --射击耐性
		attr_combat_magic = 50, --魔法耐性
		attr_combat_wind = 51, --风属性耐性
		attr_combat_fire = 52, --火属性耐性
		attr_combat_thunder = 53, --雷属性耐性
		attr_combat_water = 54, --水属性耐性
		attr_combat_soil = 55, --土属性耐性
		attr_combat_ice = 56, --冰属性耐性
		attr_combat_null = 57, --无属性耐性
		attr_gp_max = 61, --采集力
		attr_gp_recover = 62, --采集力回复
		attr_gathering = 63, --获得力
		attr_perception = 64, --鉴别力
		attr_mk_max = 65, --制作力
		attr_mk_recover = 66, --制作力回复
		attr_work_precision = 67, --作业精度
		attr_produce_precision = 68, --加工精度
		attr_prof_main_attr = 70, --职业主属性
		attr_static_max = 100,
		attr_hp = 101, --当前体力
		attr_mp = 102, --当前魔力
		attr_shield = 103, --护盾
		attr_z_speed = 104, --垂直速度
		attr_gp = 105, --当前采集力
		attr_mk = 106, --当前制作力
		attr_arm_ratio = 107, --武器伤害倍率
		attr_exp_all = 108, --所有经验
		attr_exp_combat = 109, --战斗经验
		attr_exp_gather = 110, --采集经验
		attr_exp_make = 111, --制作经验
		attr_exp_fish = 112, --捕鱼经验
		attr_exp_quest = 113, --任务经验
		attr_exp_fate = 114, --危命经验
		attr_exp_scene = 115, --副本结算经验
		attr_fall_hurt_fix = 117, --掉落伤害修正
		attr_effect_enmity_ratio = 118, --效果仇恨系数
		attr_mount_speed_rate = 119, --坐骑移速提升率
		attr_fate_damage_bonus = 120, --Fate怪伤害加成
		attr_max = 121,
	},
	prof_type = {
		PROF_TYPE_NULL = 0,
		PROF_TYPE_GLADIATOR = 1, --剑术师
		PROF_TYPE_MARAUDER = 2, --斧术师
		PROF_TYPE_PUGILIST = 3, --格斗家
		PROF_TYPE_LANCER = 4, --枪术师
		PROF_TYPE_ROGUE = 5, --双剑师
		PROF_TYPE_ARCHER = 6, --弓箭手
		PROF_TYPE_THAUMATURGE = 7, --咒术师
		PROF_TYPE_ARCANIST = 8, --秘术师
		PROF_TYPE_CONJURER = 9, --幻术师
		PROF_TYPE_PALADIN = 10, --骑士
		PROF_TYPE_DARKKNIGHT = 11, --暗黑骑士
		PROF_TYPE_WARRIOR = 12, --战士
		PROF_TYPE_GUNBREAKER = 13, --绝枪战士
		PROF_TYPE_SAMURAI = 14, --武士
		PROF_TYPE_NINJA = 15, --忍者
		PROF_TYPE_DRAGOON = 16, --龙骑士
		PROF_TYPE_MONK = 17, --武僧
		PROF_TYPE_BARD = 18, --吟游诗人
		PROF_TYPE_MACHINIST = 19, --机工士
		PROF_TYPE_DANCER = 20, --舞者
		PROF_TYPE_BLACKMAGE = 21, --黑魔法师
		PROF_TYPE_SUMMONER = 22, --召唤师
		PROF_TYPE_REDMAGE = 23, --赤魔法师
		PROF_TYPE_BLUEMAGE = 24, --青魔法师
		PROF_TYPE_WHITEMAGE = 25, --白魔法师
		PROF_TYPE_SCHOLAR = 26, --学者
		PROF_TYPE_ASTROLOGIAN = 27, --占星术士
		PROF_TYPE_BLACKSMITH = 28, --锻铁匠
		PROF_TYPE_ARMOR = 29, --铸甲匠
		PROF_TYPE_CARPENTER = 30, --刻木匠
		PROF_TYPE_GOLDSMITH = 31, --雕金匠
		PROF_TYPE_WEAVER = 32, --裁衣匠
		PROF_TYPE_LEATHER_WORK = 33, --制革匠
		PROF_TYPE_ALCHEMIST = 34, --炼金术士
		PROF_TYPE_CULINARIAN = 35, --烹调师
		PROF_TYPE_MINER = 36, --采矿工
		PROF_TYPE_BOTANIST = 37, --园艺工
		PROF_TYPE_FISHER = 38, --捕鱼人
	},
	race_type = {
		RACE_TYPE_NULL = 0,
		RACE_TYPE_Hyur = 1, --人族
		RACE_TYPE_Elezen = 2, --精灵族
		RACE_TYPE_Lalafell = 3, --拉拉菲尔族
		RACE_TYPE_Miqote = 4, --猫魅族
		RACE_TYPE_Roegadyn = 5, --鲁加族
		RACE_TYPE_AuRa = 6, --敖龙族
		RACE_TYPE_Hrothgar = 7, --硌狮族
		RACE_TYPE_Viera = 8, --维埃拉族
	},
	tribe_type = {
		TRIBE_TYPE_NULL = 0,
		TRIBE_TYPE_MIDDLE = 1, --中原之民
		TRIBE_TYPE_HIGH = 2, --高地之民
		TRIBE_TYPE_FOREST = 3, --森林之民
		TRIBE_TYPE_SHADOW = 4, --黑影之民
		TRIBE_TYPE_PLAIN = 5, --平原之民
		TRIBE_TYPE_DESERT = 6, --沙漠之民
		TRIBE_TYPE_FOLLOWSUN = 7, --逐日之民
		TRIBE_TYPE_DEFENDMOON = 8, --护月之民
		TRIBE_TYPE_NORTHOCEAN = 9, --北洋之民
		TRIBE_TYPE_REDFIRE = 10, --红焰之民
		TRIBE_TYPE_DAWN = 11, --晨曦之民
		TRIBE_TYPE_TWILIGHT = 12, --暮晖之民
		TRIBE_TYPE_WOODS = 13, --密林之民
		TRIBE_TYPE_MOUNTAIN = 14, --山林之民
		TRIBE_TYPE_PLUNDERSUN = 15, --掠日之民
		TRIBE_TYPE_STRAY = 16, --迷踪之民
	},
	twelve_god_type = {
		TWELVE_GOD_NULL = 0,
		TWELVE_GOD_Halone = 1, --哈罗妮
		TWELVE_GOD_Menphina = 2, --梅茵菲娜
		TWELVE_GOD_Thaliak = 3, --沙利亚克
		TWELVE_GOD_Nymeia = 4, --妮美雅
		TWELVE_GOD_Llymlaen = 5, --利姆莱茵
		TWELVE_GOD_Oschon = 6, --奥修昂
		TWELVE_GOD_Byregot = 7, --比尔格
		TWELVE_GOD_Rhalgr = 8, --拉尔戈
		TWELVE_GOD_Azeyma = 9, --阿泽玛
		TWELVE_GOD_Naldthal = 10, --纳尔札尔
		TWELVE_GOD_Nophica = 11, --诺菲卡
		TWELVE_GOD_Althyk = 12, --阿尔基克
	},
	CampType = {
		CampTypeNone = 0,
		CampTypeTwinAdder = 1, --双蛇党
		CampTypeMaelstrom = 2, --黑涡团
		CampTypeImmortalFlames = 3, --恒辉队
	},
	team_recruit_prof = {
		TEAM_RECRUIT_MODEL_PROF_NULL = 0,
		TEAM_RECRUIT_MODEL_GUARD = 1, --防护
		TEAM_RECRUIT_MODEL_ATTACK = 2, --进攻
		TEAM_RECRUIT_MODEL_RECOVER = 3, --回复
		TEAM_RECRUIT_MODEL_COMBAT = 4, --战斗职业
		TEAM_RECRUIT_MODEL_ALL = 5, --所有人
	},
	team_recruit_model = {
		TEAM_RECRUIT_MODEL_NULL = 0,
		TEAM_RECRUIT_MODEL_DAMAGE = 1, --挑战
		TEAM_RECRUIT_MODEL_UNLIMITED = 2, --解除限制
		TEAM_RECRUIT_MODEL_FREE_ORIENTATION = 3, --自由探索
	},
	function_type = {
		FUNCTION_TYPE_NULL = 0,
		FUNCTION_TYPE_GUARD = 1, --防护
		FUNCTION_TYPE_ATTACK = 2, --进攻
		FUNCTION_TYPE_RECOVER = 3, --回复
		FUNCTION_TYPE_PRODUCTION = 4, --制造
		FUNCTION_TYPE_GATHER = 5, --采集
	},
	specialization_type = {
		SPECIALIZATION_TYPE_NULL = 0,
		SPECIALIZATION_TYPE_COMBAT = 1, --战斗职业
		SPECIALIZATION_TYPE_PRODUCTION = 2, --生产职业
	},
	class_type = {
		CLASS_TYPE_NULL = 0,
		CLASS_TYPE_TANK = 1, --防护
		CLASS_TYPE_NEAR = 2, --近战
		CLASS_TYPE_FAR = 3, --远程
		CLASS_TYPE_MAGIC = 4, --魔法
		CLASS_TYPE_HEALTH = 5, --治疗
		CLASS_TYPE_CARPENTER = 6, --能工巧匠
		CLASS_TYPE_EARTHMESSENGER = 7, --大地使者
		CLASS_TYPE_COMBAT = 8, --战斗职业
		CLASS_TYPE_PRODUCTION = 9, --生产职业
		CLASS_TYPE_GATHER = 20, --采集园艺
	},
	avatar_personal = {
		AvatarPersonalStart = 0,
		AvatarPersonalHair = 1,
		AvatarPersonalHairColor = 2,
		AvatarPersonalHeadColor = 4,
		AvatarPersonalBodyColor = 7,
		AvatarPersonalLegColor = 10,
		AvatarPersonalFeetColor = 13,
		AvatarPersonalGlovesColor = 16,
		AvatarEquipHeadShow = 21,
		AvatarEquipHandShow = 22,
		AvatarEquipSwitchShow = 23,
		AvatarEquipOnOffOnly = 24,
		AvatarCompanion = 31,
		AvatarPerform = 32,
		AvatarTitle = 33,
		AvatarGuide = 34,
		AvatarHeaderFrame = 35,
		AvatarWing = 36,
		AvatarUmbrella = 37,
		AvatarPersonalHeight = 101,
		AvatarPersonalModelState = 102,
		AvatarMount = 103,
		AvatarFaceBase = 104,
		AvatarSkinColor = 105,
		AvatarFaceContour = 106,
		AvatarEye = 107,
		AvatarEyeBrow = 108,
		AvatarNose = 109,
		AvatarLips = 110,
		AvatarPupilSize = 111,
		AvatarLeftEyeColor = 112,
		AvatarRightEyeColor = 113,
		AvatarLipMode = 114,
		AvatarLipsColor = 115,
		AvatarFaceDecal = 116,
		AvatarFaceDecalFlip = 117,
		AvatarFaceDecalColor = 118,
		AvatarHairVariation = 119,
		AvatarChestSize = 120,
		AvatarSpecific1 = 121,
		AvatarSpecific2 = 122,
		AvatarOption = 123,
		AvatarOptionColor = 124,
		AvatarHeightScaleRate = 125,
		AvatarVoice = 126,
		AvatarHairVariationColor = 127,
		AvatarChocoboTransStation = 128,
	},
	Color = {
		ColorNone = 0,
		ColorSnowWhite = 1, --素雪白
		ColorAshGrey = 2, --苍白灰
		ColorGoobbueGrey = 3, --古菩灰
		ColorSlateGrey = 4, --石板灰
		ColorCharcoalGrey = 5, --木炭灰
		ColorSootBlack = 6, --煤烟黑
		ColorRosePink = 7, --玫瑰粉
		ColorLilacPurple = 8, --丁香紫
		ColorRolanberryRed = 9, --罗兰莓
		ColorDalamudRed = 10, --卫月红
		ColorRustRed = 11, --铁锈红
		ColorWineRed = 12, --果酒红
		ColorCoralPink = 13, --珊瑚粉
		ColorBloodRed = 14, --鲜血红
		ColorSalmonPink = 15, --鲑鱼粉
		ColorSunsetOrange = 16, --日落橙
		ColorMesaRed = 17, --台地红
		ColorBarkBrown = 18, --树皮棕
		ColorChocolateBrown = 19, --巧克力
		ColorRussetBrown = 20, --铁锈棕
		ColorKoboldBrown = 21, --钴铁棕
		ColorCorkBrown = 22, --软木棕
		ColorQiqirnBrown = 23, --卢恩棕
		ColorOpoOpoBrown = 24, --奥猴棕
		ColorAldgoatBrown = 25, --山羊棕
		ColorPumpkinOrange = 26, --南瓜橙
		ColorAcornBrown = 27, --橡果棕
		ColorOrchardBrown = 28, --果园棕
		ColorChestnutBrown = 29, --山栗棕
		ColorGobbiebagBrown = 30, --哥布林
		ColorShaleBrown = 31, --页岩棕
		ColorMoleBrown = 32, --鼹鼠棕
		ColorLoamBrown = 33, --沃土棕
		ColorBoneWhite = 34, --骸骨白
		ColorUlBrown = 35, --黄沙棕
		ColorDesertYellow = 36, --沙漠黄
		ColorHoneyYellow = 37, --蜂蜜黄
		ColorMillioncornYellow = 38, --玉米黄
		ColorCoeurlYellow = 39, --猛豹黄
		ColorCreamYellow = 40, --奶油黄
		ColorHalataliYellow = 41, --日影黄
		ColorRaisinBrown = 42, --萄干棕
		ColorMudGreen = 43, --泥沼绿
		ColorSylphGreen = 44, --妖精绿
		ColorLimeGreen = 45, --青柠绿
		ColorMossGreen = 46, --苔藓绿
		ColorMeadowGreen = 47, --牧草绿
		ColorOliveGreen = 48, --橄榄绿
		ColorMarshGreen = 49, --沼泽绿
		ColorAppleGreen = 50, --苹果绿
		ColorCactuarGreen = 51, --仙人掌
		ColorHunterGreen = 52, --猎人绿
		ColorOchuGreen = 53, --口花绿
		ColorAdamantoiseGreen = 54, --金龟绿
		ColorNophicaGreen = 55, --地神绿
		ColorDeepwoodGreen = 56, --深林绿
		ColorCelesteGreen = 57, --天上蓝
		ColorTurquoiseGreen = 58, --绿松蓝
		ColorMorbolGreen = 59, --魔花绿
		ColorIceBlue = 60, --寒冰蓝
		ColorSkyBlue = 61, --天空蓝
		ColorSeafogBlue = 62, --海雾蓝
		ColorPeacockBlue = 63, --孔雀蓝
		ColorRhotanoBlue = 64, --罗海蓝
		ColorCorpseBlue = 65, --腐尸蓝
		ColorCeruleamBlue = 66, --青磷蓝
		ColorWoadBlue = 67, --靛青蓝
		ColorInkBlue = 68, --油墨蓝
		ColorRaptorBlue = 69, --盗龙蓝
		ColorOthardBlue = 70, --东洲蓝
		ColorStormBlue = 71, --风暴蓝
		ColorVoidBlue = 72, --虚空蓝
		ColorRoyalBlue = 73, --皇室蓝
		ColorMidnightBlue = 74, --午夜蓝
		ColorShadowBlue = 75, --阴影蓝
		ColorAbyssalBlue = 76, --深渊蓝
		ColorLavenderPurple = 77, --薰衣草
		ColorGloomPurple = 78, --忧郁紫
		ColorCurrantPurple = 79, --醋栗紫
		ColorIrisPurple = 80, --鸢尾紫
		ColorGrapePurple = 81, --葡萄紫
		ColorLotusPink = 82, --莲花粉
		ColorColibriPink = 83, --蜂鸟粉
		ColorPlumPurple = 84, --仙子梅
		ColorRegalPurple = 85, --帝王紫
		ColorGemRed = 86, --宝石红
		ColorCherryPink = 87, --樱桃粉
		ColorCanaryYellow = 88, --丝雀黄
		ColorVanillaYellow = 89, --香草黄
		ColorDragonBlue = 90, --龙骑蓝
		ColorTurquoiseBlue = 91, --松石蓝
		ColorGunBlack = 92, --炮铜黑
		ColorPearlWhite = 93, --珍珠白
		ColorMetalCopper = 94, --金属铜
		ColorGeneralPurposePureWhite = 101, --无瑕白
		ColorCoalJadeBlack = 102, --煤玉黑
		ColorSoftPink = 103, --柔彩粉
		ColorDarkRed = 104, --黑暗红
		ColorDarkBrown = 105, --黑暗棕
		ColorSoftGreen = 106, --柔彩绿
		ColorDarkGreen = 107, --黑暗绿
		ColorSoftBlue = 108, --柔彩蓝
		ColorDarkBlue = 109, --黑暗蓝
		ColorSoftPurple = 110, --柔彩紫
		ColorDarkPurple = 111, --黑暗紫
		ColorBlingSilver = 112, --闪耀银
		ColorBlingGold = 113, --闪耀金
		ColorMetalRed = 114, --金属红
		ColorMetalOrange = 115, --金属橙
		ColorMetalYellow = 116, --金属黄
		ColorMetalGreen = 117, --金属绿
		ColorMetalBlue = 118, --金属蓝
		ColorMetalIndigo = 119, --金属靛
		ColorMetalPurple = 120, --金属紫
	},
	EFFECT_HURT_TYPE = {
		EFFECT_HURT_TYPE_NULL = 0,
		EFFECT_HURT_TYPE_PHY = 1,
		EFFECT_HURT_TYPE_MAG = 2,
	},
	rev_type = {
		REV_TYPE_BASE = 0, --基础值
		REV_TYPE_STATIC_SCALE1 = 1, --静态1次缩放
		REV_TYPE_STATIC_SCALE2 = 2, --静态2次缩放
		REV_TYPE_DYNAMIC_SCALE1 = 3, --动态1次缩放
		REV_TYPE_DYNAMIC_SCALE2 = 4, --动态2次缩放
		REV_TYPE_DYNAMIC_OFFSET = 5, --动态偏移
		REV_TYPE_MAX = 6, --最大值
	},
	role_gender = {
		GENDER_UNKNOWN = 0, --通用
		GENDER_MALE = 1, --男
		GENDER_FEMALE = 2, --女
	},
	SkillMode = {
		SKILL_MODE_PVE = 0, --PVE
		SKILL_MODE_PVP = 1, --PVP
		SKILL_MODE_BUFF = 2, --BUFF
	},
	PushDirType = {
		PushDirStay = 0, --保持
		PushDirBackward = 1, --背向
		PushDirForward = 2, --前向
	},
	ReviveChannelType = {
		REVIVE_CHANNEL_DEFAULT = 0, --默认复活
		REVIVE_CHANNEL_PAY = 1, --付费复活
		REVIVE_CHANNEL_BE_REVIVE = 2, --被他人复活
	},
	ReviveType = {
		REVIVE_TYPE_CUR_POINT = 0, --当前点复活
		REVIVE_TYPE_REVIVE_POINT = 1, --复活点复活
		REVIVE_TYPE_BACK_POINT = 2, --回城点复活
		REVIVE_TYPE_NONE = 3, --不可以复活
		REVIVE_TYPE_CRYSTAL = 4, --水晶位置复活
	},
	CommStatRelation = {
		COMM_STAT_RELATION_COEXIST = 0, --并存
		COMM_STAT_RELATION_EXCLUDE = 1, --排斥
		COMM_STAT_RELATION_REPLACE = 2, --替换
	},
	CommStatID = {
		COMM_STAT_MOVING = 0, --移动
		COMM_STAT_DEAD = 1, --死亡
		COMM_STAT_COMBAT = 2, --战斗
		COMM_STAT_QTE = 3, --QTE
		COMM_STAT_VIDEO = 4, --观看视频
		COMM_STAT_INVISIBLE = 5, --不可见
		COMM_STAT_EMOTION = 6, --情感动作
		COMM_STAT_MOUNT = 7, --坐骑
		COMM_STAT_PICKUP = 8, --采集
		COMM_STAT_FISH = 9, --钓鱼
		COMM_STAT_SPELL = 10, --通用读条
		CommStatPerform = 11, --演奏
		CommStatTrans = 12, --运输
		CommStatSWIMMING = 13, --游泳
		CommStatCraft = 14, --制作
		CommStatFantasyCard = 15, --幻卡
		CommStatScene = 16, --副本
		CommStatCutScene = 17, --过场动画
		CommStatDialog = 18, --对话
		CommStatFly = 19, --飞行
		CommStatAutoNavi = 20, --自动寻路
		CommStatJump = 21, --跳跃
		CommStatCrossWorld = 22, --跨界
		CommStatPVPDuel = 23, --决斗
		CommStatRecall = 24, --回想
		CommStatFacade = 25, --变身
		CommStatMatch = 26, --匹配中
		COMM_STAT_MAX = 64,
	},
	CommBehaviorID = {
		COMM_BEHAVIOR_NA = 0,
		COMM_BEHAVIOR_MOVE = 1, --移动
		COMM_BEHAVIOR_JUMP = 2, --跳跃
		COMM_BEHAVIOR_ENTER_EMOTION = 3, --情感动作
		COMM_BEHAVIOR_CALL_MOUNT = 4, --召唤坐骑
		COMM_BEHAVIOR_USE_SKILL = 5, --使用技能
		COMM_BEHAVIOR_USE_ITEM = 6, --使用道具
		COMM_BEHAVIOR_CHANGE_PROF = 7, --变更职业
		COMM_BEHAVIOR_CHANGE_EQUIP = 8, --更换装备
		COMM_BEHAVIOR_CLOSET_CLOTHING = 9, --衣橱外观更换
		COMM_BEHAVIOR_CLOSET_UNLOCK = 10, --衣橱外观解锁
		COMM_BEHAVIOR_CLOSET_DYE = 11, --衣橱外观染色
		COMM_BEHAVIOR_TEAM_INVITE = 12, --组队邀请
		COMM_BEHAVIOR_TEAM_ANSWER_INVITE = 13, --加入队伍
		COMM_BEHAVIOR_TEAM_LEAVE = 14, --退出队伍
		COMM_BEHAVIOR_TEAM_KICK_MEMBER = 15, --移出小队
		COMM_BEHAVIOR_TEAM_DESTROY = 16, --解散队伍
		COMM_BEHAVIOR_TEAM_SET_CAPTAIN = 17, --转让队长
		COMM_BEHAVIOR_MATCH = 18, --参加匹配
		COMM_BEHAVIOR_CRYSTAL_TRANS = 19, --水晶传送
		COMM_BEHAVIOR_EFFECT_TRANS = 20, --功能表传送
		COMM_BEHAVIOR_CRAFT = 21, --制作
		COMM_BEHAVIOR_GATHER = 22, --采集
		COMM_BEHAVIOR_FISH = 23, --钓鱼
		COMM_BEHAVIOR_INTERACTION = 24, --通用交互
		COMM_BEHAVIOR_DUEL = 25, --决斗
		COMM_BEHAVIOR_MEETTRADE = 26, --面对面交易
		COMM_BEHAVIOR_SUBMIT = 27, --交纳
		COMM_BEHAVIOR_MOUNT_RIDE_APPLY = 28, --申请上坐骑
		COMM_BEHAVIOR_MOUNT_RIDE_APPLY_AGREE = 29, --同意上坐骑申请
		COMM_BEHAVIOR_MOUNT_RIDE_INVITE_AGREE = 30, --同意上坐骑邀请
		COMM_BEHAVIOR_COLLECT_EXCHANGE = 31, --藏品交纳
		COMM_BEHAVIOR_LEVE_SUBMIT = 32, --提交理符任务
		COMM_BEHAVIOR_MUSIC_RECALL = 33, --回想
		COMM_BEHAVIOR_REVIVE = 999999, --复活
	},
	EmotionType = {
		EMOTION_TYPE_LOOK = 0,
		EMOTION_TYPE_COMM = 1,
		EMOTION_TYPE_LAST = 2,
		EMOTION_TYPE_STAT = 3,
	},
	emotion_check_stat = {
		emotion_check_stat_idle = 0,
		emotion_check_stat_ground = 1,
		emotion_check_stat_chair = 2,
		emotion_check_stat_riding = 3,
		emotion_check_stat_fishing = 4,
		emotion_check_stat_floating = 5,
		emotion_check_stat_diving = 6,
	},
	emotion_id = {
		emotion_id_none = 0,
		emotion_id_holdweapon = 116,
	},
	MountType = {
		MountTypeNone = 0,
		MountWalking = 1, --步行
		MountFlying = 2, --浮空
	},
	CombatStatID = {
		COMBAT_STAT_VERTIGO = 0, --眩晕
		COMBAT_STAT_FLOATED = 1, --浮空
		COMBAT_STAT_PUSH = 2, --击退
		COMBAT_STAT_PULL = 3, --牵引
		COMBAT_STAT_SKATING = 4, --滑冰
		COMBAT_STAT_REVIVE = 5, --复活
		COMBAT_STAT_CANNOT_SELECT = 6, --不可选中
		COMBAT_STAT_CANNOT_INVINCIBILITY = 7, --无敌
		COMBAT_STAT_NEGATIVE_EFFECT_IMMUNE = 8, --负面效果免疫
		COMBAT_STAT_CHARGE = 9, --冲锋
		COMBAT_STAT_VIDEO = 26, --观看视频
		COMBAT_STAT_MAX = 256,
	},
	CombatActionID = {
		COMBAT_ACTION_MOVE = 0, --移动
		COMBAT_ACTION_TURN = 1, --转向
		COMBAT_ACTION_USEITEM = 2, --使用物品
		COMBAT_ACTION_USESKILL = 3, --使用技能
		COMBAT_ACTION_HURT = 4, --受到伤害
		COMBAT_ACTION_NEGATIVE_EFFECT = 5, --受到负面效果
		COMBAT_ACTION_CTRL_EFFECT = 6, --受到控制效果
		COMBAT_ACTION_CONTINUE_SKILL = 7, --继续技能流程
		COMBAT_ACTION_SHOW_HEAD_UI = 8, --是否显示头顶UI
		COMBAT_ACTION_SNEER = 9, --受到嘲讽
		COMBAT_ACTION_COST_HP = 10, --真实扣血
		COMBAT_STAT_PLAYER_SKILL_SELECTED = 11, --玩家技能可选中
		COMBAT_STAT_MONSTER_SKILL_SELECTED = 12, --怪物技能可选中
		COMBAT_STAT_NPC_SKILL_SELECTED = 13, --NPC技能可选中
		COMBAT_STAT_PLAYER_SELECTED = 14, --玩家可选中
		COMBAT_ACTION_USE_MOVE_SKILL = 15, --使用位移技能
		COMBAT_ACTION_CONTINUE_ART_MOVE = 16, --继续美术位移
		COMBAT_ACTION_CLIENT_CAN_MOVE = 17, --允许客户端移动
		COMBAT_ACTION_FLOAT_AIR = 18, --战斗受控
		COMBAT_ACTION_COMBAT_BE_CTRL = 19, --战斗受控
		COMBAT_ACTION_MAX = 64,
	},
	ItemMainType = {
		ItemMainTypeNone = 0,
		ItemArmor = 1, --防具
		ItemAccessory = 2, --饰品
		ItemArm = 3, --武器
		ItemTool = 4, --工具
		ItemConsumables = 5, --消耗品
		ItemCollage = 6, --收集品
		ItemMaterial = 7, --素材
		ItemHousing = 8, --房屋装饰
		ItemMiscellany = 9, --杂货
	},
	ITEM_TYPE_DETAIL = {
		ItemTypeOther = 0, --其他
		ARMOR_HEAD = 1, --头部防具
		ARMOR_BODY = 2, --身体防具
		ARMOR_HANDS = 3, --手部防具
		ARMOR_LEGS = 4, --腿部防具
		ARMOR_FEET = 5, --脚部防具
		ARMOR_SHIELD = 6, --盾
		ACCESSORY_EARRINGS = 7, --耳饰
		ACCESSORY_NECKLACE = 8, --项链
		ACCESSORY_BRACELETS = 9, --手镯
		ACCESSORY_RING = 10, --戒指
		ARM_PALADIN = 11, --单手剑
		ARM_WARRIOR = 12, --大斧
		ARM_DARKKNIGHT = 13, --双手剑
		ARM_GUNBREAKER = 14, --枪刃
		ARM_DRAGOON = 15, --长枪
		ARM_MONK = 16, --格斗武器
		ARM_NINJA = 17, --双剑
		ARM_SAMURAI = 18, --武士刀
		ARM_BARD = 19, --弓
		ARM_MACHINIST = 20, --火枪
		ARM_DANCER = 21, --投掷武器
		ARM_BLACK_MAGE = 22, --双手咒杖
		ARM_SCHOLAR = 23, --魔导典
		ARM_RED_MAGE = 24, --刺剑
		ARM_BLUE_MAGE = 25, --青魔杖
		ARM_WHITE_MAGE = 26, --双手幻杖
		ARM_SUMMONER = 27, --魔导书
		ARM_ASTROLOGIAN = 28, --天球仪
		PRIMARYTOOL_ALCHEMIST = 29, --炼金主工具
		PRIMARYTOOL_CULINARIAN = 30, --烹调主工具
		PRIMARYTOOL_CARPENTER = 31, --刻木主工具
		PRIMARYTOOL_BLACKSMITH = 32, --锻铁主工具
		PRIMARYTOOL_ARMORER = 33, --铸甲主工具
		PRIMARYTOOL_GOLDSMITH = 34, --雕金主工具
		PRIMARYTOOL_LEATHERWORKER = 35, --制革主工具
		PRIMARYTOOL_WEAVER = 36, --裁衣主工具
		PRIMARYTOOL_MINER = 37, --采矿主工具
		PRIMARYTOOL_BOTANIST = 38, --园艺主工具
		PRIMARYTOOL_FISHER = 39, --捕鱼主工具
		SECONDARYTOOL_ALCHEMIST = 40, --炼金副工具
		SECONDARYTOOL_CULINARIAN = 41, --烹调副工具
		SECONDARYTOOL_CARPENTER = 42, --刻木副工具
		SECONDARYTOOL_BLACKSMITH = 43, --锻铁副工具
		SECONDARYTOOL_ARMORER = 44, --铸甲副工具
		SECONDARYTOOL_GOLDSMITH = 45, --雕金副工具
		SECONDARYTOOL_LEATHERWORKER = 46, --制革副工具
		SECONDARYTOOL_WEAVER = 47, --裁衣副工具
		SECONDARYTOOL_MINER = 48, --采矿副工具
		SECONDARYTOOL_BOTANIST = 49, --园艺副工具
		SECONDARYTOOL_FISHER = 50, --捕鱼副工具
		CONSUMABLES_MEAL = 51, --食品
		CONSUMABLES_MEDICINE = 52, --药品
		CONSUMABLES_BAIT = 53, --钓饵
		CONSUMABLES_SCROLL = 54, --卷轴
		CONSUMABLES_DYESTUFF = 55, --染料
		CONSUMABLES_CRYSTAL = 56, --水晶
		CONSUMABLES_CATALYST = 57, --触媒
		CONSUMABLES_RECIPE = 58, --配方
		CONSUMABLES_TREASUREBOX = 59, --宝箱
		CONSUMABLES_BUDDYMEAL = 60, --搭档食物
		COLLAGE_FISH = 100, --水产品
		COLLAGE_TRIPLETRIADCARD = 101, --九宫幻卡
		COLLAGE_ORCHESTRIONROLL = 102, --管弦琴乐谱
		COLLAGE_COIFFURE = 103, --发型
		COLLAGE_MOUNT = 104, --坐骑
		COLLAGE_MINION = 105, --宠物
		COLLAGE_ACTINGBOOK = 106, --演技教材
		COLLAGE_ACCESSORY = 107, --时尚配饰
		COLLAGE_BUDDYEQUIT = 108, --陆行鸟装甲
		COLLAGE_FASHION = 109, --时装
		MATERIAL_FOODSTUFF = 200, --食材
		MATERIAL_STONE = 201, --石材
		MATERIAL_METAL = 202, --金属
		MATERIAL_WOOD = 203, --木材
		MATERIAL_CLOTH = 204, --布料
		MATERIAL_LEATHER = 205, --皮革
		MATERIAL_BONE = 206, --骨材
		MATERIAL_LOREINGREDIENTS = 207, --炼金原料
		MATERIAL_UNIT = 208, --部件
		HOUSING_ROOF = 300, --房顶
		HOUSING_EXTERNALWALL = 301, --外墙
		HOUSING_WINDOW = 302, --窗户
		HOUSING_DOOR = 303, --房门
		HOUSING_ROOFDECORATION = 304, --房顶装饰
		HOUSING_EXTERNALWALLDECORATION = 305, --外墙装饰
		HOUSING_DOORPLATE = 306, --门牌
		HOUSING_COURTYARDWALLS = 307, --院墙
		HOUSING_INTERIORWALL = 308, --内墙
		HOUSING_FLOOR = 309, --地板
		HOUSING_ROOFLIGHTING = 310, --屋顶照明
		HOUSING_COURTFURNITURE = 311, --庭具
		HOUSING_FURNITURE = 312, --家具
		HOUSING_TABLE = 313, --桌台
		HOUSING_DESK = 314, --桌上
		HOUSING_HANGING = 315, --壁挂
		HOUSING_CARPET = 316, --地毯
		HOUSING_CULTIVATIONSUPPLIES = 317, --栽培用品
		HOUSING_PAINTING = 318, --绘画作品
		MISCELLANY_TASKONLY = 400, --任务物品
		MISCELLANY_MATERIA = 401, --魔晶石
		MISCELLANY_CURRENCY = 402, --货币
		MISCELLANY_SPECIAL = 403, --特殊
		MISCELLANY_TOTEM = 404, --图腾
		MISCELLANY_COLLECTION = 405, --收藏品
		MISCELLANY_CERTIFICATE = 406, --证书
		MISCELLANY_AGREEMENT = 407, --契约
		MISCELLANY_BILL = 408, --票据
		MISCELLANY_SEASONALACTIVITIES = 409, --季节活动
		MISCELLANY_GIFTPACK = 410, --礼包
		MISCELLANY_OTHERS = 411, --其他
		MISCELLANY_TRASH = 412, --作废道具
		MISCELLANY_TREASUREMAP = 413, --藏宝图
		MISCELLANY_AETHERCURRENT = 414, --风脉仪
		MISCELLANY_AETHERYTETICKET = 415, --传送券
		MISCELLANY_TASKAETHERCURRENT = 416, --任务型风脉泉
		CONSUMABLES_CHOOSETREASURECHEST = 417, --自选宝箱
	},
	equip_part = {
		EQUIP_PART_NONE = 0,
		EQUIP_PART_MASTER_HAND = 1, --主手
		EQUIP_PART_SLAVE_HAND = 2, --副手
		EQUIP_PART_HEAD = 3, --头部
		EQUIP_PART_BODY = 4, --身体
		EQUIP_PART_ARM = 5, --手部
		EQUIP_PART_LEG = 6, --腿部
		EQUIP_PART_FEET = 7, --脚部
		EQUIP_PART_NECK = 8, --颈部
		EQUIP_PART_LEFT_FINGER = 9, --左指
		EQUIP_PART_RIGHT_FINGER = 10, --右指
		EQUIP_PART_WRIST = 11, --腕部
		EQUIP_PART_EAR = 12, --耳部
		EQUIP_PART_MAX = 13,
		EQUIP_PART_FINGER = 14, --手指
		EQUIP_PART_BODY_HAIR = 15, --素体头发
		EQUIP_PART_BODY_HEAD = 16, --素体头部
		EQUIP_PART_BODY_EAR = 17, --素体耳朵
		EQUIP_PART_BODY_TAIL = 18, --素体尾巴
		EquipHeadShow = 21,
		EquipHandShow = 22,
		EquipSwitchShow = 23,
	},
	arm_type = {
		ARM_TYPE_NONE = 0,
		ARM_TYPE_SINGLE_HAND = 1, --单手
		ARM_TYPE_BOTH_HAND = 2, --双手
	},
	equip_property = {
		EQUIP_PROPERTY_NONE = 0,
		EQUIP_PROPERTY_BATTLE = 1, --战斗
		EQUIP_PROPERTY_PRODUCT = 2, --生产
		EQUIP_PROPERTY_OTHER = 3, --其它
	},
	counter_type = {
		COUNTER_TYPE_NONE = 0,
		COUNTER_TYPE_DAY = 1, --天计数器
		COUNTER_TYPE_WEEK = 2, --周计数器
		COUNTER_TYPE_MONTH = 3, --月计数器
		COUNTER_TYPE_YEAR = 4, --年计数器
		COUNTER_TYPE_FOREVER = 5, --永久计数器
	},
	item_operate_type = {
		ITEM_OPERATE_NONE = 0,
		ITEM_OPERATE_PROMPT = 1,
		ITEM_OPERATE_FORBIN = 2,
	},
	ContainerType = {
		CONTAINER_TYPE_NONE = 0,
		CONTAINER_TYPE_DEPOT1 = 1,
		CONTAINER_TYPE_DEPOT2 = 2,
		CONTAINER_TYPE_DEPOT3 = 3,
		CONTAINER_TYPE_DEPOT4 = 4,
		CONTAINER_TYPE_DEPOT5 = 5,
		CONTAINER_TYPE_DEPOT6 = 6,
		CONTAINER_TYPE_DEPOT7 = 7,
		CONTAINER_TYPE_DEPOT8 = 8,
		CONTAINER_TYPE_DEPOT9 = 9,
		CONTAINER_TYPE_DEPOT10 = 10,
		CONTAINER_TYPE_DEPOT11 = 11,
		CONTAINER_TYPE_DEPOT12 = 12,
		CONTAINER_TYPE_DEPOT13 = 13,
		CONTAINER_TYPE_DEPOT14 = 14,
		CONTAINER_TYPE_DEPOT15 = 15,
		CONTAINER_TYPE_DEPOT16 = 16,
		CONTAINER_TYPE_DEPOT17 = 17,
		CONTAINER_TYPE_DEPOT18 = 18,
		CONTAINER_TYPE_DEPOT19 = 19,
		CONTAINER_TYPE_DEPOT20 = 20,
		CONTAINER_TYPE_DEPOT_MAX = 200,
		CONTAINER_TYPE_SCORE = 201,
		CONTAINER_TYPE_BAG = 202,
		CONTAINER_TYPE_LOOT = 203,
	},
	LIFESKILL_STATUS = {
		INVALID = 0,
		FISHER_PREPARE = 1, --钓鱼准备期
		FISHER_WAIT = 2, --钓鱼等待期
		FISHER_LIFT_WINDOW = 3, --钓鱼提竿窗口期
		FISHER_AFTER_LIFT = 4, --钓鱼提竿后窗口期
		FISHER_ESCAPE = 5, --钓鱼鱼逃脱期
		FISHER_LIFTING = 6, --钓鱼提竿动作期
		GATHERER_PREPARE = 7, --采集准备
		GATHERER_GATHERING = 8, --采集中
		CRAFTER_PREPARE = 9, --制作准备
		CRAFTER_MAKING = 10, --制作中
	},
	hole_type = {
		HOLE_TYPE_NONE = 0,
		HOLE_TYPE_NORMAL = 1, --普通
		HOLE_TYPE_TABOO = 2, --禁忌
	},
	GemConst = {
		GemConstNone = 0,
		HoleCount = 5,
	},
	ownership_strategy = {
		OWNERSHIP_STRATEGY_NONE = 0,
		OWNERSHIP_STRATEGY_CREATE = 1, --创建
		OWNERSHIP_STRATEGY_FIRST_ATK = 2, --首伤
		OWNERSHIP_STRATEGY_KILL = 3, --击杀
		OWNERSHIP_STRATEGY_HURT_RATE = 4, --伤害占比
	},
	SceneOwnerType = {
		SceneOwnerNone = 0,
		SceneOwnerZone = 1,
		SceneOwnerRole = 2,
		SceneOwnerTeam = 3,
		SceneOwnerMatch = 4,
	},
	SceneMode = {
		SceneModeNormal = 0, --常规
		SceneModeChallenge = 1, --挑战
		SceneModeUnlimited = 2, --解除限制
		SceneModeExplore = 3, --自由探索
		SceneModeStory = 4, --剧情辅助
	},
	MemberTag = {
		MemberTagTemporaryTeamPriority = 0,
		MemberTagMatchEnterDailyRandomID = 1,
		MemberTagDailyRandomEnterLackProp = 2,
		MemberTagProf = 3,
		MemberTagEnterWay = 4,
		MemberTagTransID = 5,
		MemberTagPassTimes = 6,
		MemberTagFaith = 7,
		MemberTagRaidLoot = 8,
	},
	SceneTag = {
		SceneTagMode = 0,
		SceneTagMatch = 1,
		SceneTagZone = 2,
		SceneTagSyncLevel = 3,
	},
	ScenePoolType = {
		ScenePoolNull = 0,
		ScenePoolRandom = 1, --每日随机
		ScenePoolChallenge = 2, --迷宫挑战
		ScenePoolAnnihilation = 3, --讨伐歼灭战
		ScenePoolLargeTask = 4, --大型任务
		ScenePoolChocobo = 5, --陆行鸟竞赛
		ScenePoolChocoboRandomTrack = 6, --陆行鸟随机赛道
		ScenePoolMuRen = 7, --木人歼灭战
		ScenePoolFantasyCard = 8, --幻卡大赛
		ScenePoolPVPCrystal = 9, --水晶冲突
		ScenePoolPVPCrystalRank = 10, --水晶冲突段位赛
		ScenePoolPVPCrystalCustom = 11, --水晶冲突自定赛
		ScenePoolTreasureHuntBabyLibrary = 12, --寻宝宝物库
		ScenePoolActivity = 13, --活动副本
	},
	SceneVoteType = {
		SceneVoteNil = 0,
		SceneVoteKick = 1, --驱逐
		SceneVoteGiveup = 2, --放弃
	},
	SceneVotePass = {
		SceneVotePassHalf = 0, --过半通过
		SceneVotePassAll = 1, --全员通过
	},
	SceneEnterWay = {
		SceneEnterWayNone = 0,
		SceneEnterWayTeam = 1, --组队
		SceneEnterWayMatch = 2, --匹配
	},
	gambit_target = {
		GAMBIT_TARGET_NONE = 0,
		GAMBIT_TARGET_MYSELF = 1, --自身
		GAMBIT_TARGET_HATE_TOP = 2, --一仇
		GAMBIT_TARGET_HATE_SECOND = 3, --二仇
		GAMBIT_TARGET_COND0_TARGET = 4, --条件0的目标
		GAMBIT_TARGET_COND1_TARGET = 5, --条件1的目标
		GAMBIT_TARGET_COND2_TARGET = 6, --条件2的目标
		GAMBIT_TARGET_RANDOM = 7, --随机
		GAMBIT_TARGET_RANDOM_WITHOUT_HATE_TOP = 8, --随机(排除一仇)
		GAMBIT_TARGET_RANDOM_PLAYER = 9, --随机玩家(cm)
		GAMBIT_TARGET_RANDOM_ENEMY = 10, --随机敌人(cm)
		GAMBIT_TARGET_RANDOM_ALLY = 11, --随机友方(cm)
		GAMBIT_TARGET_NEAREST_PLAYER = 12, --最近玩家(cm)
		GAMBIT_TARGET_NEAREST_ENEMY = 13, --最近敌人(cm)
		GAMBIT_TARGET_NEAREST_ALLY = 14, --最近友方(cm)
		GAMBIT_TARGET_ATTACK_EXCEPT_TOP_ENMITY = 15, --非一仇DPS
		GAMBIT_TARGET_RECOVER_EXCEPT_TOP_ENMITY = 16, --非一仇治疗
		GAMBIT_MAIN_TARGET = 17, --主目标
	},
	gambit_action_type = {
		ACTION_TYPE_NONE = 0,
		ACTION_TYPE_CAST_SKILL = 1, --释放技能
		ACTION_TYPE_ACTION_PACK = 2, --执行行为包
		ACTION_TYPE_SET_GAMBIT_PACK = 3, --设置PackID
		ACTION_TYPE_MOVE = 4, --移动
		ACTION_TYPE_SUSPEND = 5, --暂停
		ACTION_TYPE_SAY = 6, --说话
		ACTION_TYPE_PATROL = 7, --巡逻
		ACTION_TYPE_COUNTER_SET = 8, --设定计数器N的值为M
		ACTION_TYPE_COUNTER_UP = 9, --计数器N+1
		ACTION_TYPE_COUNTER_DOWN = 10, --计数器N-1
		ACTION_TYPE_TIMER1_SET_RAND = 11, --计时器1在N~M随机
		ACTION_TYPE_TIMER2_SET_RAND = 12, --计时器2在N~M随机
		ACTION_TYPE_TIMER1_CLEAR = 13, --清除计时器1
		ACTION_TYPE_TIMER2_CLEAR = 14, --清除计时器2
		ACTION_TYPE_VOICE = 15, --音频
		ACTION_TYPE_MODE_STATE = 16, --模型状态
		ACTION_TYPE_MOVE_TO_TARGET_AROUND = 17, --移动到目标的(n)度(m)厘米
	},
	gambit_cond_target = {
		GAMBIT_COND_TARGET_NONE = 0,
		GAMBIT_COND_TARGET_MYSELF = 1, --自身
		GAMBIT_COND_TARGET_HATE_TOP = 2, --一仇
		GAMBIT_COND_TARGET_HATE_SECOND = 3, --二仇
		GAMBIT_COND_TARGET_NEAR_PC_5M = 4, --5m内玩家
		GAMBIT_COND_TARGET_NEAR_PC_10M = 5, --10m内玩家
		GAMBIT_COND_TARGET_NEAR_PC_20M = 6, --20m内玩家
		GAMBIT_COND_TARGET_NEAR_PC_30M = 7, --30m内玩家
		GAMBIT_COND_TARGET_NEAR_PC_40M = 8, --40m内玩家
		GAMBIT_COND_TARGET_NEAR_ENEMY_10M = 9, --10m内敌方
		GAMBIT_COND_TARGET_NEAR_ENEMY_20M = 10, --20m内敌方
		GAMBIT_COND_TARGET_NEAR_ENEMY_30M = 11, --30m内敌方
		GAMBIT_COND_TARGET_NEAR_ENEMY_40M = 12, --40m内敌方
		GAMBIT_COND_TARGET_NEAR_FRIEND_10M = 13, --10m内友方
		GAMBIT_COND_TARGET_NEAR_FRIEND_20M = 14, --20m内友方
		GAMBIT_COND_TARGET_NEAR_FRIEND_30M = 15, --30m内友方
		GAMBIT_COND_TARGET_NEAR_FRIEND_40M = 16, --40m内友方
		GAMBIT_COND_TARGET_MAIN_TARGET = 17, --主目标
		GAMBIT_COND_TARGET_PARTY = 18, --队友
		GAMBIT_COND_TARGET_NEAR_PARTY_20M = 19, --20m内队友(不含自身)
		GAMBIT_COND_TARGET_NEAR_MY_PARTY_20M = 20, --20m内队友(含自身)
		GAMBIT_COND_TARGET_RANDOM_HATE_LIST = 21, --仇恨列表随机
		GAMBIT_COND_TARGET_RANDOM_HATE_LIST_WITHOUT_HATE_TOP = 22, --仇恨列表随机(排除一仇)
		GAMBIT_COND_TARGET_NEAR_ENEMY_30M_RANDOM = 23, --30m内敌方随机
		GAMBIT_COND_TARGET_NEAR_PC_30M_RANDOM = 24, --30m内玩家随机
		GAMBIT_COND_TARGET_MASTERS_TARGET = 25, --主人的目标
		GAMBIT_COND_TARGET_NEAR_ENEMY_40M_RANDOM = 26, --40m内敌方随机
		GAMBIT_COND_TARGET_NEAR_PC_40M_RANDOM = 27, --40m内玩家随机
		GAMBIT_COND_TARGET_NEAR_PC_10M_HEIGHT_30M = 28, --10m内玩家(高低差30m内)
		GAMBIT_COND_TARGET_NEAR_PC_20M_HEIGHT_30M = 29, --20m内玩家(高低差30m内)
		GAMBIT_COND_TARGET_NEAR_PC_30M_HEIGHT_30M = 30, --30m内玩家(高低差30m内)
		GAMBIT_COND_TARGET_NEAR_PC_40M_HEIGHT_30M = 31, --40m内玩家(高低差30m内)
		GAMBIT_COND_TARGET_NEAR_ENEMY_10M_HEIGHT_30M = 32, --10m内敌方(高低差30m内)
		GAMBIT_COND_TARGET_NEAR_ENEMY_20M_HEIGHT_30M = 33, --20m内敌方(高低差30m内)
		GAMBIT_COND_TARGET_NEAR_ENEMY_30M_HEIGHT_30M = 34, --30m内敌方(高低差30m内)
		GAMBIT_COND_TARGET_NEAR_ENEMY_40M_HEIGHT_30M = 35, --40m内敌方(高低差30m内)
		GAMBIT_COND_TARGET_NEAR_FRIEND_10M_HEIGHT_30M = 36, --10m内友方(高低差30m内)
		GAMBIT_COND_TARGET_NEAR_FRIEND_20M_HEIGHT_30M = 37, --20m内友方(高低差30m内)
		GAMBIT_COND_TARGET_NEAR_FRIEND_30M_HEIGHT_30M = 38, --30m内友方(高低差30m内)
		GAMBIT_COND_TARGET_NEAR_FRIEND_40M_HEIGHT_30M = 39, --40m内友方(高低差30m内)
		GAMBIT_COND_TARGET_NEAR_MY_FRIEND_40M_HEIGHT_30M = 40, --40m内友方(高低差30m内，包含自身)
		GAMBIT_COND_TARGET_ADD_TO_PREVIOUS = 41, --上一个条件目标
	},
	gambit_cond_type = {
		GAMBIT_COND_TYPE_NONE = 0,
		GAMBIT_COND_TYPE_NO_COND = 1, --无条件
		GAMBIT_COND_TYPE_HP_BELOW = 2, --血量百分比低于
		GAMBIT_COND_TYPE_HP_OVER = 3, --血量百分比高于
		GAMBIT_COND_TYPE_MP_BELOW = 4, --蓝量百分比低于
		GAMBIT_COND_TYPE_MP_OVER = 5, --蓝量百分比高于
		GAMBIT_COND_TYPE_BUFF_N_BELOW = 6, --buff数量低于
		GAMBIT_COND_TYPE_BUFF_N_OVER = 7, --buff数量高于
		GAMBIT_COND_TYPE_BUFF_EXIST = 8, --存在buff
		GAMBIT_COND_TYPE_BUFF_UN_EXIST = 9, --不存在buff
		GAMBIT_COND_TYPE_DIS_BELOW = 10, --距离低于
		GAMBIT_COND_TYPE_DIS_OVER = 11, --距离高于
		GAMBIT_COND_TYPE_WT_OVER = 12, --WT高于
		GAMBIT_COND_TYPE_COUNTER_N_OVER_M = 13, --计数器N大于等于M
		GAMBIT_COND_TYPE_COUNTER_N_BELOW_M = 14, --计数器N小于等于M
		GAMBIT_COND_TYPE_TIMER1_OVER_N = 15, --计时器1大于N
		GAMBIT_COND_TYPE_TIMER2_OVER_N = 16, --计时器2大于N
		GAMBIT_COND_TYPE_TIMER1_BELOW_N = 17, --计时器1小于N
		GAMBIT_COND_TYPE_TIMER2_BELOW_N = 18, --计时器2小于N
		GAMBIT_COND_TYPE_RANDOM = 19, --随机概率(%)
		GAMBIT_COND_TYPE_DEAD = 20, --死亡
		GAMBIT_COND_TYPE_NOT_HATE_TOP = 21, --自身非一仇
		GAMBIT_COND_TYPE_RECAST = 22, --技能中
		GAMBIT_COND_TYPE_NOT_RECAST = 23, --非技能中
		GAMBIT_COND_TYPE_ABOVE_CONDITION_IS_TRUE = 24, --上个条件成立
		GAMBIT_COND_TYPE_WITHIN_N_DEGREE_FROM_FRONT = 25, --前方(n)度以内
		GAMBIT_COND_TYPE_WITHIN_N_DEGREE_FROM_BACK = 26, --后方(n)度以内
		GAMBIT_COND_TYPE_WITHIN_N_DEGREE_FROM_LEFT = 27, --左方(n)度以内
		GAMBIT_COND_TYPE_WITHIN_N_DEGREE_FROM_RIGHT = 28, --右方(n)度以内
		GAMBIT_COND_TYPE_PREVIOUS_ACTION_WAS_N = 29, --上一个技能是
		GAMBIT_COND_TYPE_LB_OVER_N = 30, --LB槽达到(n)以上
		GAMBIT_COND_TYPE_ROLE = 31, --职能为
		GAMBIT_COND_TYPE_NOT_ROLE = 32, --职能不为
	},
	tree_args_type = {
		CHASE_TARGET_MOVE_DIS = 0, --跟随_移动距离
		CHASE_TARGET_STOP_DIS = 1, --跟随_停止距离
		CHASE_TARGET_FAIL_DIS = 2, --跟随_失败距离
		GAMBIT_ID = 3, --gambit_id
	},
	ENTERTAIN_ID = {
		ENTERTAIN_ID_INVALID = 0,
		ENTERTAIN_ID_ANY_WAY_WIND_BLOWS = 1, --喷风中的幸存者
		ENTERTAIN_ID_SLICE_IS_RIGHT = 2, --必中一闪快刀斩魔
		ENTERTAIN_ID_AIR_FORCE_ONE = 3, --空军装甲驾驶员
		ENTERTAIN_ID_LEAP_OF_FAITH = 4, --虚景跳跳乐大挑战
		ENTERTAIN_ID_CLIFFHANGER = 5, --小雏鸟的营救者
		ENTERTAIN_ID_FANTASY_CARD = 6, --金碟九宫幻卡
		ENTERTAIN_ID_MINI_CACTPOT = 7, --金蝶仙人微彩
		ENTERTAIN_ID_FAIRY_COLOR = 8, --金蝶仙人仙彩
		ENTERTAIN_ID_FASHION_CHECK = 9, --金蝶时尚品鉴
		ENTERTAIN_ID_GATE = 10, --金蝶机遇临门
		ENTERTAIN_ID_FAIRY_COLOR_OPEN_LOTTERY_CEREMONY = 12, --金蝶仙人仙彩开奖仪式
		ENTERTAIN_ID_GOLD_SAUSER_MAIN = 13, --金蝶主界面
		ENTERTAIN_ID_FATE = 11, --临危受命
		ENTERTAIN_ID_BARBERSHOP = 14, --理发屋
		ENTERTAIN_ID_TREASUREHUNT = 15, --寻宝
		EntertainIDChocoboTransfer = 16, --陆行鸟运输
		MatchResultConfirm = 17, --匹配结果确认
		EntertainIDMonsterBasketball = 18, --怪物投篮
		EntertainIDCrystalTower = 19, --强袭水晶塔
		EntertainIDGilgamesh = 20, --重击吉尔伽美什
		EntertainIDCatchBall = 21, --莫古抓球机
		EntertainIDAloneTree = 22, --孤树无援和矿脉探索
		ENTERTAIN_ID_MYSTERY_MERCHANT = 23, --神秘商人
		ENTERTAIN_ID_TOURING_BAND = 27, --巡回乐团
		Match = 24, --匹配
		ENTERTAIN_ID_PVPCOLOSSEUM_CRYSTAL = 25, --水晶冲突
		ENTERTAIN_ID_PVPCOLOSSEUM_FRONTLINE = 26, --纷争前线
		ENTERTAIN_ID_AREAMAIL = 28, --小区邮件
		ENTERTAIN_ID_ACTIVITY = 29, --活动系统
	},
	INTERACT_TYPE = {
		INTERACT_TYPE_GENERAL = 0,
		INTERACT_TYPE_CRAFT = 1,
		INTERACT_TYPE_GATHER = 2,
	},
	ModuleID = {
		ModuleIDStart = 0,
		ModuleIDMount = 101, --坐骑
		ModuleIDAvatar = 102, --外观
		ModuleIDHOUSE = 103, --房屋
		ModuleIDGatherNote = 104, --采集笔记
		ModuleIDMakerNote = 105, --制作笔记
		ModuleIDFisherNote = 106, --钓鱼笔记
		ModuleIDChallengeNote = 107, --挑战笔记
		ModuleIDArmy = 108, --部队
		ModuleIDBattle = 109, --对战
		ModuleIDStoneSkySea = 110, --木人歼灭战
		ModuleIDScene = 111, --副本
		ModuleIDLinkShell = 112, --通讯贝
		ModuleIDTeamRecruit = 113, --队伍招募
		ModuleIDAdviseTask = 114, --推荐任务
		ModuleIDMountFly = 115, --坐骑飞行
		ModuleIDCompanion = 116, --宠物
		ModuleIDNewbie = 117, --新手指南
		ModuleIDEntertain = 118, --玩法
		ModuleIDShadow = 119, --投影台
		ModuleIDMall = 120, --商城
		ModuleIDAdventure = 121, --冒险日程
		ModuleIDDailyRand = 122, --每日随机
		ModuleIDDawnQuestHelper = 123, --剧情辅助器
		ModuleIDMonthCard = 124, --月卡
		ModuleIDBuddy = 125, --搭档
		ModuleIDChocoboArmorCollect = 126, --陆行鸟装甲图鉴
		ModuleIDBarberShop = 127, --理发屋
		ModuleIDHotel = 128, --旅馆
		ModuleIDLegendaryWeapon = 129, --传奇武器
		ModuleIDZodiacWeapon = 130, --上古武器
		ModuleIDZodiacWeaponPlus = 131, --黄道武器
		ModuleIDLeveQuest = 132, --理符
		ModuleIDBattlePass = 133, --战令
		ModuleIDPerform = 134, --乐器演奏
		ModuleIDTravelLog = 135, --旅行笔录
		ModuleIDGemInfo = 136, --魔晶石镶嵌
		ModuleIDCollection = 137, --收藏品
		ModuleIDFantasyCard = 138, --幻卡
		ModuleIDChocobo = 139, --陆行鸟
		ModuleIDChocoboRace = 140, --陆行鸟竞赛
		ModuleIDFashionCheck = 141, --时尚品鉴
		ModuleIDFairyColor = 142, --仙人仙彩
		ModuleIDMiniCactpot = 143, --仙人微彩
		ModuleIDSightseeingLog = 144, --探索笔记
		ModuleIDAetherCurrent = 145, --风脉
		ModuleIDTreasureHunt = 146, --寻宝
		ModuleIDActivity = 147, --福利
		ModuleIDGoldSauserMain = 148, --金碟游乐场
		ModuleIDFATE = 149, --临危受命
		ModuleIDQuest = 150, --任务
		ModuleIDCompanySeal = 151, --军票
		ModuleIDMysteryMerchant = 152, --神秘商人
		ModuleIDPvPColosseumCrystal = 153, --水晶冲突
		ModuleIDPvPColosseumFrontLine = 154, --纷争前线
		ModuleIDTouringBand = 155, --巡回乐团
		ModuleIDTest = 156, --测试
		ModuleIDActivitySystem = 157, --活动系统
		ModuleIDJobQuest = 158, --职业任务
		ModuleIDGuide = 159, --指导者
		ModuleIDSpecialTrain = 160, --机制特训
		ModuleIDAreaClean = 161, --区域清理
		ModuleIDAchievement = 162, --成就
		ModuleIDFashionDecorate = 163, --时尚配饰
		ModuleIDCrystal = 164, --水晶传送
		ModuleAutoNavi = 165, --自动寻路
		ModuleIDGamePworld = 166, --玩法战斗系统
		ModuleIDLightJourney = 167, --光之启程
		ModuleIDWaterCityTreasure = 168, --水城宝物库
		ModuleIDWorldExplore = 169, --世界探索
		ModuleIDFantasyCardTournament = 170, --幻卡大赛
		ModuleIDPWorldGame = 171, --副本玩法
		ModuleIDGoldGame = 172, --金碟玩法
		ModuleIDPvPGame = 173, --对战玩法
		ModuleIDGuardSky2025 = 174, --守护天2025
		ModuleIDGuardSky2026 = 175, --守护天2026
		ModuleIDGuardSky2027 = 176, --守护天2027
		ModuleIDGuardSky2028 = 177, --守护天2028
		ModuleIDGuardSky2029 = 178, --守护天2029
		ModuleIDNews = 179, --资讯
		ModuleIDMarketTrade = 183, --市场交易
		ModuleIDMeetTrade = 184, --面对面交易
		ModuleIDGroupBag = 185, --部队储物柜
		ModuleIDNote = 200, --笔记
	},
	ModuleType = {
		ModuleTypeStart = 0,
		ModuleTypeProf = 1, --职业
		ModuleTypeSystem = 2, --系统
		ModuleTypeScene = 3, --副本
	},
	EObjType = {
		EObjTypeNone = 0,
		EObjTypeTreasure = 1, --宝箱
		EObjTypeTask = 2, --任务
		EObjTypeAetherCurrent = 3, --风脉泉
		EObjTypeFateGather = 4, --Fate采集物
		EObjTypeHousingOrnament = 5, --房屋物件
		EObjTypeDiscoverNote = 6, --探索笔记探索点
		EObjTypeWildBox = 7, --野外宝箱
		EObjTypeMerchantGather = 8, --神秘商人交互物
	},
	ChocoboAttrType = {
		AttrTypeNone = 0,
		AttrTypeMaxSpeed = 1,
		AttrTypeSprintSpeed = 2,
		AttrTypeAcceleration = 3,
		AttrTypeStamina = 4,
		AttrTypeSkillStrenth = 5,
		AttrTypeMax = 6,
	},
	TreasureStatus = {
		TreasureStatusClosed = 0,
		TreasureStatusOpened = 1,
	},
	group_category_type = {
		GROUP_CATEGORY_TYPE_INTERN = 0,
		GROUP_CATEGORY_TYPE_PRESIDENT = 1,
		GROUP_CATEGORY_TYPE_MEMBER = 2,
	},
	ChocoboProcessAwardType = {
		ChocoboProcessAwardTypeNone = 0,
		ChocoboProcessAwardTypePart = 1,
		ChocoboProcessAwardTypeSuit = 2,
	},
	GUIDE_TYPE = {
		GUIDE_TYPE_NONE = 0,
		GUIDE_TYPE_FIGHT = 1, --战斗指导者
		GUIDE_TYPE_GATHER = 2, --采集指导者
		GUIDE_TYPE_SENIOR = 3, --资深指导者
		GUIDE_TYPE_NEWBIE = 4, --新人
		GUIDE_TYPE_RETURNEE = 5, --回归者
		GUIDE_TYPE_FIGHT_NEED_UPDATE = 6, --需要资格更新的战斗指导者
		GUIDE_TYPE_GATHER_NEED_UPDATE = 7, --需要资格更新的采集指导者
		GUIDE_TYPE_SENIOR_NEED_UPDATE = 8, --需要资格更新的资深指导者
		GUIDE_TYPE_RED_FLOWER = 9, --小红花指导者
	},
	PersonalPortraitUnlockType = {
		PersonalPortraitUnlockUnknown = 0,
		PersonalPortraitUnlockDefault = 1, --默认解锁
		PersonalPortraitUnlockTask = 2, --任务解锁
	},
	DesignerType = {
		DesignerType_None = 0,
		DesignerType_Predict = 1, --预设
		DesignerType_BackGround = 2, --背景
		DesignerType_Decoration = 3, --装饰
		DesignerType_Decoration_Frame = 4, --装饰框
		DesignerType_ModelEdit = 5, --模型编辑
		DesignerType_Action = 6, --动作
		DesignerType_Emotion = 7, --表情
		DesignerType_Light = 8, --灯光
	},
	GoldSauserGameType = {
		GoldSauserGameTypeNone = 0,
		GoldSauserGameTypeGate = 1, --机遇临门
		GoldSauserGameTypeFantasyCard = 2, --幻卡
		GoldSauserGameTypeChocobo = 3, --陆行鸟
		GoldSauserGameTypeFashionCheck = 4, --时尚品鉴
		GoldSauserGameTypeMiniCactpot = 5, --仙人微彩
		GoldSauserGameTypeFairyColor = 6, --仙人仙彩
	},
	ExpirationType = {
		ExpirationTypeInvalid = 0,
		ExpirationTypeRelative = 1, --相对有效期限
		ExpirationTypeAbsolute = 2, --绝对有效期限
	},
}

return ProtoCommon