---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2024/7/16 15:55
---

local TouringBandDefine =
{
    DEBUG = false,
    TALK_CHEERING_NUM = 4,
    STATES_TYPE = {
        NONE = 0,
        CREATE = 1,
        PERFORMING = 2,
        MOVE_IN_END = 3, -- 入场移动结束
        COME_ON = 4, -- 入场
        MOVE_OUT_READY = 5, -- 准备离场
        SHOW_SYSTEM_WEAPON = 6, -- 显示乐器
    },
    
    DEFAULT_POSTER_TEXTURE = "Texture'/Game/UI/Texture/TouringBand/MI_UI_Mask_TouringBandPoster.MI_UI_Mask_TouringBandPoster'",
    BAND_MANAGER_HUD_ICON = "PaperSprite'/Game/UI/Atlas/HUD/Frames/UI_HUD_Icon_TouringBand_png.UI_HUD_Icon_TouringBand_png'",
    NORMAL_LINSTEN_HUD_ICON = "PaperSprite'/Game/UI/Atlas/HUD/Frames/UI_HUD_TouringBand_Icon_NormalListen_png.UI_HUD_TouringBand_Icon_NormalListen_png'",
    FANS_LINSTEN_HUD_ICON = "PaperSprite'/Game/UI/Atlas/HUD/Frames/UI_HUD_TouringBand_Icon_FansListen_png.UI_HUD_TouringBand_Icon_FansListen_png'",
}

return TouringBandDefine