---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by skysong.
--- DateTime: 2025/5/16 16:30
---

local LuaClass = require("Core/LuaClass")
local UIViewModel = require("UI/UIViewModel")
local MainFunctionDefine = require("Game/Main/FunctionPanel/MainFunctionDefine")

---@class MainHouseListItemVM : UIViewModel
local MainHouseListItemVM = LuaClass(UIViewModel)
---Ctor
function MainHouseListItemVM:Ctor()
    self.Type = MainFunctionDefine.ButtonType.NONE

    self.RowIndex = 0  -- 按钮所在行数，1在最上方
    self.ColumnIndex = 0  -- 按钮所在列数，1在最右侧

    self.Icon = ""
    self.RedDotID = 0

    self.IsUnlock = true            -- 按钮对应的系统是否已经解锁（或处于开启时期）
    self.IsVisibleOrigin = true     -- 业务层可以通过这个变量临时控制按钮是否显示
    self.IsVisible = true           -- 实际ItemView绑这个变量
end

---@param Value MainFunctionItemVM
function MainHouseListItemVM:IsEqualVM(Value)
    return self.Type == Value.Type
end

---UpdateVM
---@param Value table
function MainHouseListItemVM:UpdateVM(Params)
    if nil == Params then
        _G.FLOG_ERROR("MainHouseListItemVM.UpdateVM: Invalid params")
        return
    end

    local Type = Params.Type

    if nil == Type then
        _G.FLOG_ERROR("MainHouseListItemVM.UpdateVM: Invalid type: " .. tostring(Type))
        return
    end

    self.Type = Type
    self.RowIndex = Params.RowIndex
    self.ColumnIndex = Params.ColumnIndex

    local ButtonCfg = MainFunctionDefine.GetButtonConfig(Type)
    self.Icon = ButtonCfg.Icon or ""
    self.RedDotID = ButtonCfg.RedDotID or 0

    self:SetIsVisible(true)
end

function MainHouseListItemVM:SetIsVisible(IsVisible)
    self.IsVisibleOrigin = IsVisible
    self:UpdateIsVisibleInternal()
end

function MainHouseListItemVM:UpdateIsVisibleInternal()
    self.IsVisible = self.IsVisibleOrigin
end

return MainHouseListItemVM