---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by skysong.
--- DateTime: 2025/5/12 10:36
---

local LuaClass = require("Core/LuaClass")
local UIViewModel = require("UI/UIViewModel")
local ItemCfg = require("TableCfg/ItemCfg")
local ProtoCommon = require("Protocol/ProtoCommon")
local HouseCommon = require("Game/House/HouseCommon")
local HouseMainPanelVM = require("Game/House/VM/HouseMainPanelVM")
local HouseUtil = require("Game/House/HouseUtil")
local ProtoRes = require("Protocol/ProtoRes")

local ITEM_TYPE_DETAIL = ProtoCommon.ITEM_TYPE_DETAIL

---@class HouseSlotItemTipsVM : UIViewModel
local HouseSlotItemTipsVM = LuaClass(UIViewModel)

function HouseSlotItemTipsVM:Ctor()
    self.BtnPlaceVisible = true
    self.BtnReplaceVisible = false
    self.BtnBackBagVisible = false
    self.BtnMBackDepotVisible = true

    self.BtnReplaceEnable = true

    self.Value = nil
end

function HouseSlotItemTipsVM:UpdateVM(Value,IsRightItem)
    self.Value = Value
    local ItemResID = Value.ResID
    local Cfg = ItemCfg:FindCfgByKey(ItemResID)
    if Cfg == nil then
        return
    end

    if HouseMainPanelVM:GetTabSelectIndex() == HouseCommon.SelectHouseLeftBarType.Bag then
        self.BtnBackBagVisible = false
        self.BtnMBackDepotVisible = true
    elseif HouseMainPanelVM:GetTabSelectIndex() == HouseCommon.SelectHouseLeftBarType.StoreHouse then
        self.BtnBackBagVisible = true
        self.BtnMBackDepotVisible = false
    end

    if IsRightItem then
        local HouseModel = _G.HousingMgr:GetHouseModel()

        --放置情况下显示放置
        if HouseModel == HouseCommon.HouseModel.FurnitureModel or HouseModel == HouseCommon.HouseModel.YardModel then
            self.BtnReplaceVisible = false
            if HouseMainPanelVM:GetTabSelectIndex() == HouseCommon.SelectHouseLeftBarType.Placed then
                self.BtnPlaceVisible = false
                self.BtnBackBagVisible = true
                self.BtnMBackDepotVisible = true
            else
                self.BtnPlaceVisible = true
            end
        else
            self.BtnReplaceVisible = true
            self.BtnPlaceVisible = false

            local ExteriorCfg = HouseUtil.GetHousePartsCfg(ItemResID) or {}
            local HouseID = _G.HousingMgr.HouseID
            local HouseSize = _G.HousingMgr:GetHouseSize(HouseID)
            self.BtnReplaceEnable = (not ExteriorCfg.Size) or
                    (ExteriorCfg.Size == HouseSize) or
                    (ExteriorCfg.Size == ProtoRes.HOUSING_SIZE_TYPE.HOUSING_SIZE_ALL)

        end
    else
        self.BtnReplaceVisible = false
        self.BtnPlaceVisible = false
        self.BtnBackBagVisible = true
        self.BtnMBackDepotVisible = true
    end
end

return HouseSlotItemTipsVM