---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by mingyyzhang.
--- DateTime: 2025/6/19 16:30
---
local LuaClass = require("Core/LuaClass")
local UIViewModel = require("UI/UIViewModel")
local MsgTipsUtil = require("Utils/MsgTipsUtil")
local ProtoCS = require("Protocol/ProtoCS")
local HouseFlagCfg = require("TableCfg/HouseFlagCfg")
local HouseLocalDef = require("Game/House/HouseLocalDef")
local MathUtil = require("Utils/MathUtil")

local HouseInfoSettingsWinVM = LuaClass(UIViewModel)
local LSTR = _G.LSTR

function HouseInfoSettingsWinVM:Ctor()
    self.VisitPrivilege = nil
    self.PanelHouseInfoVisible = true
    self.PanelTagVisible = false
    self.PanelViewPermissionsVisible = false
    self.PanelOtherVisible = false
    self.HouseTagSelect = {}
    self.ModifyTypes = {}
    self.DestoryHouseConditions = {}
    self.GiveUpLandConditions = {}
    self.TagNum = 0
    self.HouseID = nil
    self.HouseType = nil
    self.CacheTagTable = {}
    self.OwnerID = nil
end

-- 保存房屋信息
function HouseInfoSettingsWinVM:RecordHouseInfo(IsEmpty)
    -- 更新HouseName和HouseGreet
    if IsEmpty then
        MsgTipsUtil.ShowTips(LSTR("请先输入房屋名称"))
    else
        self.ModifyTypes = {}
        if self.Page == 1 then
            table.insert(self.ModifyTypes, ProtoCS.ModifyHouseInfoType.ModifyHouseInfoType_Name)
            table.insert(self.ModifyTypes, ProtoCS.ModifyHouseInfoType.ModifyHouseInfoType_Greeting)
        elseif self.Page == 2 then
            table.insert(self.ModifyTypes, ProtoCS.ModifyHouseInfoType.ModifyHouseInfoType_Tags)
        end

        local SendTag = {}
        for i = 1, #self.TagTable do
            if self.TagTable[i] == 1 then
                table.insert(SendTag, i)
            end
        end

        local HouseID = self.HouseID
        if HouseID then
            _G.HouseInfoMgr:SendModifyHouseInfo(HouseID, self.ModifyTypes, self.HouseName, self.HouseGreet,
            SendTag)
            self.CacheTagTable = SendTag
            self.TagNum = #SendTag
        end
    end
end

function HouseInfoSettingsWinVM:HouseTagInit()
    local TagCfg = nil
    for i = 1, 23 do
        TagCfg = HouseFlagCfg:FindCfgByKey(i)
        local TagList = {
            IconPath = nil,
            TagText = nil,
            ID = nil,
            SettingVM = self
        }
        TagList.IconPath = string.format(HouseLocalDef.LocationHouseTagIconPath, TagCfg.ID, TagCfg.ID)
        TagList.TagText = TagCfg.FlagName
        TagList.ID = TagCfg.ID
        table.insert(self.HouseTagSelect, TagList)
    end
end

function HouseInfoSettingsWinVM:InitParam(Params)
    self.TagNum = 0
    self.HouseID = nil
    self.HouseType = nil
    self.CacheTagTable = Params.TagTable

    if Params.TagTable then
        self.TagNum = #Params.TagTable
    end

    self.TagTable = {}
    for i = 1, HouseLocalDef.HouseTagMaxNum do -- 初始化Tag列表 数量通过HouseLocalDef的值修改
        table.insert(self.TagTable, 0)
    end

    for i = 1, #self.CacheTagTable do
        self.TagTable[self.CacheTagTable[i]] = 1
    end

    self.HouseName = Params.HouseName
    self.HouseGreet = Params.HouseGreet
    self.Page = nil
    self.VisitPrivilege = table.deepcopy(Params.VisitPrivilege)
    self.HouseID = Params.HouseID
    self.HouseType = Params.HouseType
    self.OwnerID = Params.OwnerID
    local DestroyData = {}
    for _, Value in ipairs(HouseLocalDef.DestoryHouseConditions) do
        local DesData = {
            Desc = Value.Desc,
            HouseOpType = Value.HouseOpType,
            BtnName = Value.BtnName,
            HouseID = self.HouseID,
            HouseType = self.HouseType,
        }

        table.insert(DestroyData, DesData)
    end

    self.DestoryHouseConditions = DestroyData
    local GiveUpData = {}
    for i, v in ipairs(HouseLocalDef.GiveUpLandConditions) do
        local GpData = {
            Desc = v.Desc,
            HouseOpType = v.HouseOpType,
            BtnName = v.BtnName,
            HouseID = self.HouseID,
            HouseType = self.HouseType,
        }
        
        table.insert(GiveUpData, GpData)
    end

    self.GiveUpLandConditions = GiveUpData
end

return HouseInfoSettingsWinVM
