---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by skysong.
--- DateTime: 2025/5/22 9:34
---

local LuaClass = require("Core/LuaClass")
local UIViewModel = require("UI/UIViewModel")
local HouseCommon = require("Game/House/HouseCommon")
local UIBindableList = require("UI/UIBindableList")
local UIBindableBagSlotList = require("Game/NewBag/VM/UIBindableBagSlotList")
local HouseSlotLItemVM = require("Game/House/VM/HouseSlotLItemVM")
local ItemCfg = require("TableCfg/ItemCfg")

local HouseDecorateSlotItemVM = LuaClass(UIViewModel)
local LSTR = _G.LSTR

function HouseDecorateSlotItemVM:Ctor()
    self.IsSelect = nil
    self.Name = nil
    self.Item = nil
    self.IsValid = false
    self.GID = nil
    self.ResID = nil
    self.Icon = nil
    self.IconPath = nil
end

function HouseDecorateSlotItemVM:IsEqualVM(Value)
    return nil ~= Value and Value.Index == self.Index
end

function HouseDecorateSlotItemVM:SetEmptyItem(Param)
    if Param == HouseCommon.HouseItemCatagory.EXTERIOR_WALL_OPTION then
        self.IconPath = "Texture2D'/Game/UI/Texture/House/UI_House_Icon_Slot1.UI_House_Icon_Slot1'"
        self.Name = LSTR(1640026)
    elseif Param == HouseCommon.HouseItemCatagory.EXTERIOR_ROOF_OPTION then
        self.IconPath = "Texture2D'/Game/UI/Texture/House/UI_House_Icon_Slot2.UI_House_Icon_Slot2'"
        self.Name = LSTR(1640027)
    elseif Param == HouseCommon.HouseItemCatagory.EXTERIOR_SIGN then
        self.IconPath = "Texture2D'/Game/UI/Texture/House/UI_House_Icon_Slot3.UI_House_Icon_Slot3'"
        self.Name = LSTR(1640028)
    elseif Param == HouseCommon.HouseItemCatagory.EXTERIOR_FENCE then
        self.IconPath = "Texture2D'/Game/UI/Texture/House/UI_House_Icon_Slot4.UI_House_Icon_Slot4'"
        self.Name = LSTR(1640029)
    end
end

function HouseDecorateSlotItemVM:UpdateVM(Value, Param)
    local IsValid = nil ~= Value and Value.ResID ~= nil
    self.IsValid = IsValid

    if not IsValid then
        self.ResID = nil
        return
    end

    local ValueResID = Value.ResID
    self.Index = Value.Index

    --如果是空的这里显示默认图片
    if Value.ResID == HouseCommon.HouseItemCatagory.EXTERIOR_WALL_OPTION or Value.ResID == HouseCommon.HouseItemCatagory.EXTERIOR_ROOF_OPTION or
            Value.ResID == HouseCommon.HouseItemCatagory.EXTERIOR_SIGN or Value.ResID == HouseCommon.HouseItemCatagory.EXTERIOR_FENCE then
        self.Icon = nil
        self:SetEmptyItem(ValueResID)
        self.GID = ValueResID
        self.ResID = ValueResID
        self.IsSelect = false
        return
    end

    self.Item = Value
    self.GID = Value.GID
    self.ResID = Value.ResID
    self.IconPath = nil

    local Cfg = ItemCfg:FindCfgByKey(ValueResID)
    if nil == Cfg then
        FLOG_WARNING("ItemVM:UpdateVM can't find item cfg, ResID =%d", ValueResID)
        return
    end

    self.Name = ItemCfg:GetItemName(ValueResID)
    self.Icon = Cfg.IconID
    --选中标识
    self.IsSelect = false
end

function HouseDecorateSlotItemVM:AdapterOnGetCanBeSelected()
    return true
end

function HouseSlotLItemVM:SetItemSelected(IsSelected)
    self.IsSelect = IsSelected
end

return HouseDecorateSlotItemVM