---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by skysong.
--- DateTime: 2025/5/8 15:49
---

local LuaClass = require("Core/LuaClass")
local UIViewModel = require("UI/UIViewModel")
local HouseCommon = require("Game/House/HouseCommon")
local UIBindableList = require("UI/UIBindableList")
local UIBindableBagSlotList = require("Game/NewBag/VM/UIBindableBagSlotList")
local HouseSlotLItemVM = require("Game/House/VM/HouseSlotLItemVM")
local RichTextUtil = require("Utils/RichTextUtil")
local ProtoCS = require("Protocol/ProtoCS")
local HouseUtil = require("Game/House/HouseUtil")
local ProtoRes = require("Protocol/ProtoRes")
local ItemCfg = require("TableCfg/ItemCfg")
local HousingFurnitureCfg = require("TableCfg/HousingFurnitureCfg")
local HousingYardCfg = require("TableCfg/HousingYardobjectCfg")
local ITEM_UPDATE_TYPE = ProtoCS.ITEM_UPDATE_TYPE

local LSTR =_G.LSTR
local BagMgr = _G.BagMgr

local HouseMainPanelVM = LuaClass(UIViewModel)

function HouseMainPanelVM:Ctor()
    self.TabList = {}
    self.TitleText = ""
    self.ShowTitleEntity = false
    self.TabSelectIndex = 0
    self.TabSelectType = 0
    self.CommBackpackEmptyVisible = false
    self.CommBackpackEmptySVisible = false
    self.HouseDecoratePanelVisible = false
    self.ItemDetailVisible = nil
    self.CurrentItemVMList = UIBindableBagSlotList.New(HouseSlotLItemVM)
    self.RichTextBoxlayoutText = nil
    self.RichTextBoxWarehouseText = nil
    self.HouseMovePanelVisible = false
    self.PanelDecorateVisible = true
    self.ToggleBtnGridlVisible = false
    self.ToggleBtnTableVisible = false
    self.TableViewSlotLVisible = true
    self.ToggleBtnArrowVisible = true
    self.BtnBackVisible = false
    self.IsToggleChecked = true
    self.BtnCloseVisible = true
    self.BtnBackVisible = false
    self.OpenGrid = false
    self.OpenTableState = false
    self.OpenHideUI = false
    self.PanelMainVisible = true
end

function HouseMainPanelVM:OnShutdown()
    self.CurrentItemVMList:Clear()
end

function HouseMainPanelVM:InitData()
    --self:UpdateTabList()
end

function HouseMainPanelVM:ResetPreviewModelData()
    self.PreviewModelData = {}
    self.PreviewModelData.Bag = {}
    self.PreviewModelData.InternalDepot = {}
    self.PreviewModelData.HouseDepot = {}
    self.PreviewModelData.InternalData = {} --内装数据
    self.PreviewModelData.ExteriorData = {} --外装数据
end

function HouseMainPanelVM:FindItemInPreviewDataBag(GID)
    for k,BagItems in pairs(self.PreviewModelData.Bag) do
        for _,v in pairs(BagItems) do
            if v.GID == GID then
                return true
            end
        end
    end

    return false
end

function HouseMainPanelVM:FindItemInPreviewDataDepot(GID,Indoor)
    if Indoor then
        for k,DepotItems in pairs(self.PreviewModelData.InternalDepot) do
            for _,v in pairs(DepotItems) do
                if v.GID == GID then
                    return v
                end
            end
        end
    else
        for k,DepotItems in pairs(self.PreviewModelData.HouseDepot) do
            for _,v in pairs(DepotItems) do
                if v.GID == GID then
                    return v
                end
            end
        end
    end

    return nil
end

function HouseMainPanelVM:GetDecorateInfo()
    local HousingMgr = _G.HousingMgr
    local HouseDecorateInfo = HousingMgr:GetHouseInfo(HousingMgr.HouseID, HousingMgr.Region)
    local FloorData = {}
    local ChangePosOps = {}
    local HaveUnBindItem = false

    if HouseDecorateInfo == nil then
        return { HaveUnBindItem = HaveUnBindItem, FloorData = FloorData, ChangePosOps = ChangePosOps }
    end

    --总体思路就是只看装修slot上的数据预览数据与真实数据在每一个位置上是不是有变化，如果有说明一定被替换了，那么就去预览数据的背包和仓库中找，找到的话就记录装修变化记录
    if HousingMgr:IsInDoor() then
        local HouseDecorateInfos = { {}, {}, {}, {}, {}, {}, {}, {}, {}, {} }

        if HouseDecorateInfo.DoUp.Floors ~= nil then
            for k,v in pairs(HouseDecorateInfo.DoUp.Floors) do
                for _,Entity in pairs(v.Entities) do
                    local Index = HouseUtil.GetHouseDoUpPosToIndex(Entity.Pos)
                    if v.Floor == HouseCommon.FloorCategory.FLOOR_CATEGORY_1F then
                        HouseDecorateInfos[Index].Floor = v.Floor
                        HouseDecorateInfos[Index].Pos = Entity.Pos
                        HouseDecorateInfos[Index].GID = Entity.GID
                        HouseDecorateInfos[Index].EntityKey = Entity.Key
                    elseif v.Floor == HouseCommon.FloorCategory.FLOOR_CATEGORY_2F then
                        HouseDecorateInfos[3 + Index].Floor = v.Floor
                        HouseDecorateInfos[3 + Index].Pos = Entity.Pos
                        HouseDecorateInfos[3 + Index].GID = Entity.GID
                        HouseDecorateInfos[3 + Index].EntityKey = Entity.Key
                    else
                        HouseDecorateInfos[6 + Index].Floor = v.Floor
                        HouseDecorateInfos[6 + Index].Pos = Entity.Pos
                        HouseDecorateInfos[6 + Index].GID = Entity.GID
                        HouseDecorateInfos[6 + Index].EntityKey = Entity.Key
                    end
                end
            end
        end

        local Entity = HousingMgr:GetHouseCenterLightEntity(HousingMgr.HouseID)
        if Entity ~= nil then
            HouseDecorateInfos[10].Floor = HouseCommon.FloorCategory.FLOOR_CATEGORY_COMMON
            HouseDecorateInfos[10].Pos = Entity.Pos
            HouseDecorateInfos[10].GID = Entity.GID
            HouseDecorateInfos[10].EntityKey = Entity.Key
        end

        --比较预览数据如果不同则说明变化了
        local SlotItemGIDs = { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 }
        local SlotItemResIDs = { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 }
        local Index = 1
        for k,v in pairs(self.PreviewModelData.InternalData) do
            SlotItemGIDs[Index] = v.GID
            SlotItemResIDs[Index] = v.ResID
            Index = Index + 1
        end

        for i = 1, #HouseDecorateInfos do
            local SlotInfo = HouseDecorateInfos[i]
            local SlotItemGID = SlotItemGIDs[i]

            -- 跳过未变化的槽位
            if SlotInfo.GID and SlotInfo.GID ~= SlotItemGID then
                local ItemFound = false

                -- 1. 在背包中查找物品
                local BagItem = _G.BagMgr:FindItem(SlotItemGID)
                if BagItem then
                    ItemFound = true
                    local ItemConfig = ItemCfg:FindCfgByKey(SlotItemResIDs[i])
                    if not ItemConfig then
                        return { HaveUnBindItem = HaveUnBindItem, FloorData = FloorData, ChangePosOps = ChangePosOps }
                    end

                    if not BagItem.IsBind then
                        HaveUnBindItem = true
                    end
                    
                    -- 添加到装潢操作
                    table.insert(FloorData, {
                        Floor = SlotInfo.Floor,
                        Pos = SlotInfo.Pos,
                        BagType = ProtoCS.HouseUseBagType.HouseUseBagType_RoleBag,
                        Item = { GID = BagItem.GID, ResID = BagItem.ResID },
                        EntityKey = ItemConfig.KeyID
                    })
                end

                -- 2. 在仓库中查找物品
                if not ItemFound then
                    local DepotItem = HousingMgr:FindDepotItem(SlotItemGID)
                    if DepotItem then
                        ItemFound = true
                        local ItemConfig = ItemCfg:FindCfgByKey(SlotItemResIDs[i])
                        if not ItemConfig then
                            return { HaveUnBindItem = HaveUnBindItem, FloorData = FloorData, ChangePosOps = ChangePosOps }
                        end

                        if not DepotItem.IsBind then
                            HaveUnBindItem = true
                        end

                        -- 添加到装潢操作
                        table.insert(FloorData, {
                            Floor = SlotInfo.Floor,
                            Pos = SlotInfo.Pos,
                            BagType = ProtoCS.HouseUseBagType.HouseUseBagType_HouseDepot,
                            Item = { GID = DepotItem.GID, ResID = DepotItem.ResID },
                            EntityKey = ItemConfig.KeyID
                        })
                    end
                end

                -- 3. 在装修数据中查找物品
                if not ItemFound then
                    local DecorateItem = nil
                    for _, Item in ipairs(HouseDecorateInfos) do
                        if Item.GID == SlotItemGID then
                            DecorateItem = Item
                            break
                        end
                    end

                    if DecorateItem then
                        ItemFound = true
                        
                        local BagType = ProtoCS.HouseUseBagType.HouseUseBagType_RoleBag
                        if self.TabSelectIndex == HouseCommon.SelectHouseLeftBarType.StoreHouse then
                            BagType = ProtoCS.HouseUseBagType.HouseUseBagType_HouseDepot
                        end
                        
                        -- 添加到位置移动操作
                        table.insert(ChangePosOps, {
                            Floor = SlotInfo.Floor,
                            Pos = SlotInfo.Pos,
                            FromFloor = DecorateItem.Floor,
                            FromPos = DecorateItem.Pos,
                            BagType = BagType
                        })
                    else
                        _G.FLOG_WARNING("Cant Find HouseItem GID:%d", SlotItemGID)
                        return { HaveUnBindItem = HaveUnBindItem, FloorData = FloorData, ChangePosOps = ChangePosOps }
                    end
                end
            end
        end

        return { HaveUnBindItem = HaveUnBindItem, FloorData = FloorData, ChangePosOps = ChangePosOps }
    else
        local HouseDecorateInfos =
        {{},{},{},{},
         {GID = 0,Pos = ProtoRes.HouseDoUpPos.HouseDoUpPos_YardRoofDecoration, Floor = HouseCommon.ServerFloorCategory.FLOOR_CATEGORY_1F},
         {GID = 0,Pos = ProtoRes.HouseDoUpPos.HouseDoUpPos_YardWallDecoration, Floor = HouseCommon.ServerFloorCategory.FLOOR_CATEGORY_1F},
         {GID = 0,Pos = ProtoRes.HouseDoUpPos.HouseDoUpPos_YardDoorplateDecoration, Floor = HouseCommon.ServerFloorCategory.FLOOR_CATEGORY_1F},
         {GID = 0,Pos = ProtoRes.HouseDoUpPos.HouseDoUpPos_YardFenceDecoration, Floor = HouseCommon.ServerFloorCategory.FLOOR_CATEGORY_1F}}

        if HouseDecorateInfo.DoUp.Floors ~= nil then
            for k,v in pairs(HouseDecorateInfo.DoUp.Floors) do
                for _,Entity in pairs(v.Entities) do
                    local Index = HouseUtil.GetHouseDoUpPosToIndex(Entity.Pos)
                    if v.Floor == HouseCommon.FloorCategory.FLOOR_CATEGORY_1F then
                        HouseDecorateInfos[Index].Floor = v.Floor
                        HouseDecorateInfos[Index].Pos = Entity.Pos
                        HouseDecorateInfos[Index].GID = Entity.GID
                        HouseDecorateInfos[Index].EntityKey = Entity.Key
                    end
                end
            end
        end

        local SlotItemGIDs = {0,0,0,0,0,0,0,0}
        local SlotItemResIDs = {0,0,0,0,0,0,0,0}
        local Index = 1

        for k,v in pairs(self.PreviewModelData.ExteriorData) do
            SlotItemGIDs[Index] = v.GID
            SlotItemResIDs[Index] = v.ResID
            Index = Index + 1
        end

        for i=1, #HouseDecorateInfos do
            if HouseDecorateInfos[i].GID ~= nil and HouseDecorateInfos[i].GID ~= SlotItemGIDs[i] then
                --先从背包中去找当前预览槽位上的数据
                local BagItem = _G.BagMgr:FindItem(SlotItemGIDs[i])
                if BagItem ~= nil then
                    --这里还要判断一下是不是未绑定数据，后面做二次提示
                    local Cfg = ItemCfg:FindCfgByKey(SlotItemResIDs[i])

                    if BagItem ~= nil then
                        if not BagItem.IsBind then
                            HaveUnBindItem = true
                        end
                    end

                    table.insert(FloorData, {
                        Floor = HouseDecorateInfos[i].Floor,
                        Pos = HouseDecorateInfos[i].Pos,
                        BagType = ProtoCS.HouseUseBagType.HouseUseBagType_RoleBag,
                        Item = { GID = BagItem.GID, ResID = BagItem.ResID },
                        EntityKey = Cfg.KeyID
                    })
                else
                    local DepotItem = HousingMgr:FindDepotItem(SlotItemGIDs[i])
                    if DepotItem ~= nil then
                        local Cfg = ItemCfg:FindCfgByKey(SlotItemResIDs[i])

                        if DepotItem ~= nil then
                            if not DepotItem.IsBind then
                                HaveUnBindItem = true
                            end

                            table.insert(FloorData, {
                                Floor = HouseDecorateInfos[i].Floor,
                                Pos = HouseDecorateInfos[i].Pos,
                                BagType = ProtoCS.HouseUseBagType.HouseUseBagType_HouseDepot,
                                Item = { GID = DepotItem.GID, ResID = DepotItem.ResID },
                                EntityKey = Cfg.KeyID
                            })
                        end
                    else
                        FLOG_WARNING("Cant Find HouseItem ResID is %d", HouseDecorateInfos[i].GID)
                        return { HaveUnBindItem = HaveUnBindItem, FloorData = FloorData, ChangePosOps = ChangePosOps }
                    end
                end
            end
        end
    end

    return { HaveUnBindItem = HaveUnBindItem, FloorData = FloorData, ChangePosOps = ChangePosOps }
end

--检查当前预览数据是否与真实数据之间产生了变化，说明需要保存
function HouseMainPanelVM:CheckInterOrExterDataChange()
    local HousingMgr = _G.HousingMgr
    local HouseDecorateInfo = HousingMgr:GetHouseInfo(HousingMgr.HouseID,HousingMgr.Region)

    if HouseDecorateInfo == nil then
        return false
    end

    if HousingMgr:IsInDoor() then
        local ItemGIDs = { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 }
        --取所有楼层Item的GID
        if HouseDecorateInfo.DoUp.Floors ~= nil then
            for k,v in pairs(HouseDecorateInfo.DoUp.Floors) do
                for _,Entity in pairs(v.Entities) do
                    local Index = HouseUtil.GetHouseDoUpPosToIndex(Entity.Pos)
                    if v.Floor == HouseCommon.FloorCategory.FLOOR_CATEGORY_1F then
                        ItemGIDs[Index] = Entity.GID
                    elseif v.Floor == HouseCommon.FloorCategory.FLOOR_CATEGORY_2F then
                        ItemGIDs[3 + Index] = Entity.GID
                    else
                        ItemGIDs[6 + Index] = Entity.GID
                    end
                end
            end
        end

        local Entity = HousingMgr:GetHouseCenterLightEntity(HousingMgr.HouseID)
        if Entity ~= nil then
            ItemGIDs[10] = Entity.GID
        end

        --比较预览数据如果不同则说明变化了
        local SlotItemGIDs = { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 }
        local Index = 1
        for k,v in pairs(self.PreviewModelData.InternalData) do
            SlotItemGIDs[Index] = v.GID
            Index = Index + 1
        end

        for i=1, #SlotItemGIDs do
            if SlotItemGIDs[i] ~= ItemGIDs[i] then
                return true
            end
        end
    else
        local ItemGIDs = {0,0,0,0,0,0,0,0}
        --取所有楼层Item的GID
        if HouseDecorateInfo.DoUp.Floors ~= nil then
            for k,v in pairs(HouseDecorateInfo.DoUp.Floors) do
                for _,Entity in pairs(v.Entities) do
                    local Index = HouseUtil.GetHouseDoUpPosToIndex(Entity.Pos)
                    ItemGIDs[Index] = Entity.GID
                end
            end
        end

        local SlotItemGIDs = {0,0,0,0,0,0,0,0}
        local Index = 1
        for k,v in pairs(self.PreviewModelData.ExteriorData) do
            SlotItemGIDs[Index] = v.GID
            Index = Index + 1
        end

        for i=1, #SlotItemGIDs do
            if SlotItemGIDs[i] ~= ItemGIDs[i] then
                return true
            end
        end
    end

    return false
end

--更新预览装修槽数据
function HouseMainPanelVM:UpdatePreviewInterExterData(Params)
    local Type = Params.Type
    local Item = Params.Item
    local Pos = Params.Pos
    local Floor = Params.Floor

    local Index = HouseUtil.GetHouseDoUpPosToIndex(Pos)

    if _G.HousingMgr:IsInDoor() then
        if Floor == HouseCommon.FloorCategory.FLOOR_CATEGORY_2F then
            Index = Index + 3
        elseif Floor == HouseCommon.FloorCategory.FLOOR_CATEGORY_B1 then
            Index = Index + 6
        end

        --在预览下
        if #self.PreviewModelData.InternalData > 0 then
            if Type == HouseCommon.HouseItemUpdateType.AddDecorSlotItem then
                self:AddPreviewItem(HouseCommon.PreviewModelDataType.InternalData,nil,Item,Index)
            else
                self:RemovePreviewItem(HouseCommon.PreviewModelDataType.InternalData,nil,nil,Index)
            end
        end
    else
        --在预览下
        if #self.PreviewModelData.ExteriorData > 0 then
            if Type == HouseCommon.HouseItemUpdateType.AddDecorSlotItem then
                self:AddPreviewItem(HouseCommon.PreviewModelDataType.ExteriorData,nil,Item,Index)
            else
                self:RemovePreviewItem(HouseCommon.PreviewModelDataType.ExteriorData,nil,nil,Index)
            end
        end
    end
end

function HouseMainPanelVM:UpdatePreviewBagData(Params)
    local Items = Params
    local NeedUpdateView = false

    for k,Item in ipairs(Items) do
        local Cfg = ItemCfg:FindCfgByKey(Item.PstItem.ResID)

        if Cfg ~= nil  then
            local HouseItemType = HouseUtil.CovertItemTypeDetailToHouseItemCategory(Cfg.ItemType)

            if self.PreviewModelData.Bag[HouseItemType] ~= nil then
                if Item.Type == ITEM_UPDATE_TYPE.ITEM_UPDATE_TYPE_ADD then
                    self:AddPreviewItem(HouseCommon.PreviewModelDataType.Bag,HouseItemType,Item.PstItem)
                elseif Item.Type == ITEM_UPDATE_TYPE.ITEM_UPDATE_TYPE_DELETE then
                    self:RemovePreviewItem(HouseCommon.PreviewModelDataType.Bag,HouseItemType,Item.PstItem)
                end
            end

            if _G.HousingMgr:IsInDoor() then
                if self.TabSelectIndex == HouseCommon.SelectHouseLeftBarType.Bag and HouseUtil.ConvertInDoorPartsCategoryHouseItemCategory(_G.HousingMgr.SelectInDoorPartsCategory) == HouseItemType then
                    NeedUpdateView = true
                end
            else
                if self.TabSelectIndex == HouseCommon.SelectHouseLeftBarType.Bag and HouseUtil.ConvertHousePartsCategoryHouseItemCategory(_G.HousingMgr.SelectHousePartsCategory) == HouseItemType then
                    NeedUpdateView = true
                end
            end
        end
    end

    if NeedUpdateView then
        self:UpdateItemList()
    end
end

function HouseMainPanelVM:UpdatePreviewDepotData(Params)
    local Type = Params.Type
    local Items = Params.Items
    local UpdateItem = false

    for k,Item in pairs(Items) do
        local Cfg = ItemCfg:FindCfgByKey(Item.ResID)

        if Cfg ~= nil then
            local HouseItemType = HouseUtil.CovertItemTypeDetailToHouseItemCategory(Cfg.ItemType)

            if _G.HousingMgr:IsInDoor() then
                if self.PreviewModelData.InternalDepot[HouseItemType] ~= nil then
                    --更新预览仓库数数
                    if Type == HouseCommon.HouseItemUpdateType.AddDepotItem then
                        self:AddPreviewItem(HouseCommon.PreviewModelDataType.InternalDepot,HouseItemType,Item)
                    else
                        self:RemovePreviewItem(HouseCommon.PreviewModelDataType.InternalDepot,HouseItemType,Item)
                    end
                end

                --如果当前选的就是这个类型则要更新右边道具列表
                if HouseUtil.ConvertInDoorPartsCategoryHouseItemCategory(_G.HousingMgr.SelectInDoorPartsCategory) == HouseItemType then
                    UpdateItem = true
                end

            else
                if self.PreviewModelData.HouseDepot[HouseItemType] ~= nil then
                    if Type == HouseCommon.HouseItemUpdateType.AddDepotItem then
                        self:AddPreviewItem(HouseCommon.PreviewModelDataType.HouseDepot,HouseItemType,Item)
                    else
                        self:RemovePreviewItem(HouseCommon.PreviewModelDataType.HouseDepot,HouseItemType,Item)
                    end
                end

                --如果当前选的就是这个类型则要更新右边道具列表
                if HouseUtil.ConvertHousePartsCategoryHouseItemCategory(_G.HousingMgr.SelectHousePartsCategory) == HouseItemType then
                    UpdateItem = true
                end
            end
        end
    end

    if UpdateItem then
        self:UpdateItemList()
    end

end

--填充内装预览信息
function HouseMainPanelVM:FillPreviewModelInternalData()
    --初始三层数据不管有没有
    local Items = {
        { GID = 0, ResID = 0 }, { GID = 0, ResID = 0 }, { GID = 0, ResID = 0 },
        { GID = 0, ResID = 0 }, { GID = 0, ResID = 0 }, { GID = 0, ResID = 0 },
        { GID = 0, ResID = 0 }, { GID = 0, ResID = 0 }, { GID = 0, ResID = 0 },
        { GID = 0, ResID = 0 },
    }
    local HousingMgr = _G.HousingMgr
    local HouseDecorateInfo = HousingMgr:GetHouseInfo(HousingMgr.HouseID, HousingMgr.Region)

    if HouseDecorateInfo ~= nil then
        for k,v in pairs(HouseDecorateInfo.DoUp.Floors) do
            local Index = 1
            for _,Entity in pairs(v.Entities) do
                local Cfg = HouseUtil.GetHouseItemCfg(Entity.Key,ProtoRes.HOUSE_MAPPING_TABLE_ID.HOUSE_INDORR_TERRITORY)

                if Cfg ~= nil then
                    if v.Floor == HouseCommon.FloorCategory.FLOOR_CATEGORY_1F then
                        Items[Index] = {GID = Entity.GID,ResID = Cfg.ItemID}
                    elseif v.Floor == HouseCommon.FloorCategory.FLOOR_CATEGORY_2F then
                        Items[3 + Index] = {GID = Entity.GID,ResID = Cfg.ItemID}
                    else
                        Items[6 + Index] = {GID = Entity.GID,ResID = Cfg.ItemID}
                    end
                else
                    if v.Floor == HouseCommon.FloorCategory.FLOOR_CATEGORY_1F then
                        Items[Index] = {GID = Entity.GID,ResID = 0}
                    elseif v.Floor == HouseCommon.FloorCategory.FLOOR_CATEGORY_2F then
                        Items[3 + Index] = {GID = Entity.GID,ResID = 0}
                    else
                        Items[6 + Index] = {GID = Entity.GID,ResID = 0}
                    end
                end

                Index = Index + 1
            end
        end

        local Entity = HousingMgr:GetHouseCenterLightEntity(HousingMgr.IndoorHouseID)
        if Entity ~= nil then
            local Cfg = HouseUtil.GetHouseItemCfg(Entity.Key, ProtoRes.HOUSE_MAPPING_TABLE_ID.HOUSE_INDORR_TERRITORY)
            if Cfg ~= nil then
                Items[10] = { GID = Entity.GID, ResID = Cfg.ItemID }
            end
        end

        self:AddInternalData(Items)
    end
end

--填充外装预览信息
function HouseMainPanelVM:FillPreviewModelExteriorData()
    local HouseDecorateInfo = _G.HousingMgr:GetHouseInfo(_G.HousingMgr.HouseID,_G.HousingMgr.Region)
    local Items = {{GID=0,ResID=0},{GID=0,ResID=0},{GID=0,ResID=0},{GID=0,ResID=0}}
    table.insert(Items,{GID = 0,ResID = HouseCommon.HouseItemCatagory.EXTERIOR_ROOF_OPTION})
    table.insert(Items,{GID = 0,ResID = HouseCommon.HouseItemCatagory.EXTERIOR_WALL_OPTION})
    table.insert(Items,{GID = 0,ResID = HouseCommon.HouseItemCatagory.EXTERIOR_SIGN})
    table.insert(Items,{GID = 0,ResID = HouseCommon.HouseItemCatagory.EXTERIOR_FENCE})

    if HouseDecorateInfo == nil then
        return
    end

    for k,v in pairs(HouseDecorateInfo.DoUp.Floors) do
        if v.Floor == HouseCommon.FloorCategory.FLOOR_CATEGORY_1F then
            for _,Entity in pairs(v.Entities) do
                local Cfg = HouseUtil.GetHouseItemCfg(Entity.Key,ProtoRes.HOUSE_MAPPING_TABLE_ID.HOUSE_TERRITORY)
                local Index = HouseUtil.GetHouseDoUpPosToIndex(Entity.Pos)

                if Cfg ~= nil then
                    Items[Index] = {GID=Entity.GID,ResID=Cfg.ItemID}
                else
                    FLOG_WARNING("Cant Find Item")
                    Items[Index] = {GID=Entity.GID}
                end
            end
        end
    end

    self:AddExteriorData(Items)
end

function HouseMainPanelVM:RevertPartsCategoryToHouseItemCategory(PartsCategory,Indoor)
    if Indoor then
        if PartsCategory == HouseCommon.HouseInteriorParts.INTERIOR_CATEGORY_WALL then
            return HouseCommon.HouseItemCatagory.INTERIOR_WALL
        elseif PartsCategory == HouseCommon.HouseInteriorParts.INTERIOR_CATEGORY_FLOOR then
            return HouseCommon.HouseItemCatagory.INTERIOR_FLOOR
        elseif PartsCategory == HouseCommon.HouseInteriorParts.INTERIOR_CATEGORY_ILLUMINATION then
            return HouseCommon.HouseItemCatagory.INTERIOR_LIGHT
        end
    else
        if PartsCategory == HouseCommon.HouseExteriorParts.HOUSE_EXTERIOR_PARTS_ROOF then
            return HouseCommon.HouseItemCatagory.EXTERIOR_ROOF
        elseif PartsCategory == HouseCommon.HouseExteriorParts.HOUSE_EXTERIOR_PARTS_WALL then
            return HouseCommon.HouseItemCatagory.EXTERIOR_WALL
        elseif PartsCategory == HouseCommon.HouseExteriorParts.HOUSE_EXTERIOR_PARTS_WIND then
            return HouseCommon.HouseItemCatagory.EXTERIOR_WINDOW
        elseif PartsCategory == HouseCommon.HouseExteriorParts.HOUSE_EXTERIOR_PARTS_DOOR then
            return HouseCommon.HouseItemCatagory.EXTERIOR_DOOR
        elseif PartsCategory == HouseCommon.HouseExteriorParts.HOUSE_EXTERIOR_PARTS_OPT_ROOF then
            return HouseCommon.HouseItemCatagory.EXTERIOR_ROOF_OPTION
        elseif PartsCategory == HouseCommon.HouseExteriorParts.HOUSE_EXTERIOR_PARTS_OPT_WALL then
            return HouseCommon.HouseItemCatagory.EXTERIOR_WALL_OPTION
        elseif PartsCategory == HouseCommon.HouseExteriorParts.HOUSE_EXTERIOR_PARTS_OPT_SIGN then
            return HouseCommon.HouseItemCatagory.EXTERIOR_SIGN
        elseif PartsCategory == HouseCommon.HouseExteriorParts.HOUSE_EXTERIOR_PARTS_FENCE then
            return HouseCommon.HouseItemCatagory.EXTERIOR_FENCE
        end
    end

    return HouseCommon.HouseItemCatagory.Invalid
end

function HouseMainPanelVM:CheckPreviewModelAndFillData()

    local ItemTypes = {}
    table.insert(ItemTypes,self.TabSelectType)

    if _G.HousingMgr:IsInDoor() then
        local PartsCategory = self:RevertPartsCategoryToHouseItemCategory(_G.HousingMgr.SelectInDoorPartsCategory,true)

        if PartsCategory ~= HouseCommon.HouseItemCatagory.Invalid then
            --检查背包
            if self.PreviewModelData.Bag[PartsCategory] == nil then
                local HouseItems = _G.BagMainVM:GetHouseItems(ItemTypes)
                self:AddBagPreviewData({Type = PartsCategory,Items = HouseItems})
            end

            --内装检查二块数据InternalData,InternalDepot
            if self.PreviewModelData.InternalDepot[PartsCategory] == nil then
                local HouseItems = _G.HousingMgr:GetDepotItems(ItemTypes)
                self:AddDepotPreviewData({Type = PartsCategory,Items = HouseItems})
            end
        end


        if #self.PreviewModelData.InternalData == 0 then
            self:FillPreviewModelInternalData()
        end
    else
        local PartsCategory = self:RevertPartsCategoryToHouseItemCategory(_G.HousingMgr.SelectHousePartsCategory,false)

        if PartsCategory ~= HouseCommon.HouseItemCatagory.Invalid then
            --检查背包
            if self.PreviewModelData.Bag[PartsCategory] == nil then
                local HouseItems = _G.BagMainVM:GetHouseItems(ItemTypes)
                self:AddBagPreviewData({Type = PartsCategory,Items = HouseItems})
            end

            --外装检查二块数据ExteriorData,HouseDepot
            if self.PreviewModelData.HouseDepot[PartsCategory] == nil then
                local HouseItems = _G.HousingMgr:GetDepotItems(ItemTypes)
                self:AddDepotPreviewData({Type = PartsCategory,Items = HouseItems})
            end
        end

        if #self.PreviewModelData.ExteriorData == 0 then
            self:FillPreviewModelExteriorData()
        end
    end
end

function HouseMainPanelVM:AddBagPreviewData(BagData)
    local Items = {}
    for _,Item in pairs(BagData.Items) do
        table.insert(Items,{GID = Item.GID,ResID = Item.ResID})
    end

    self.PreviewModelData.Bag[BagData.Type] = Items
end

function HouseMainPanelVM:AddDepotPreviewData(DepotData)
    local Items = {}
    for _,Item in pairs(DepotData.Items) do
        table.insert(Items,{GID = Item.GID,ResID = Item.ResID})
    end

    if _G.HousingMgr:IsInDoor() then
        self.PreviewModelData.InternalDepot[DepotData.Type] = Items
    else
        self.PreviewModelData.HouseDepot[DepotData.Type] = Items
    end
end

function HouseMainPanelVM:AddInternalData(Items)
    local LocalItems = {}

    for _,Item in pairs(Items) do
        table.insert(LocalItems,{GID = Item.GID,ResID = Item.ResID})
    end

    self.PreviewModelData.InternalData = LocalItems
end

function HouseMainPanelVM:AddExteriorData(Items)
    local LocalItems = {}

    for _,Item in pairs(Items) do
        table.insert(LocalItems,{GID = Item.GID,ResID = Item.ResID})
    end

    self.PreviewModelData.ExteriorData = LocalItems
end

function HouseMainPanelVM:ReplacePreviewItem(From)
    local FromType = nil
    local FromSubType = nil
    local ToType = nil
    local ToSubType = nil
    local To = nil

    local HousingMgr = _G.HousingMgr

    if HousingMgr:IsInDoor() then
        if self.TabSelectIndex == HouseCommon.SelectHouseLeftBarType.Bag then
            FromType = HouseCommon.PreviewModelDataType.Bag
        else
            FromType = HouseCommon.PreviewModelDataType.InternalDepot
        end

        local PartsCategory = self:RevertPartsCategoryToHouseItemCategory(HousingMgr.SelectInDoorPartsCategory,true)

        FromSubType = PartsCategory
        ToType = HouseCommon.PreviewModelDataType.InternalData
        ToSubType = FromSubType
    else
        if self.TabSelectIndex == HouseCommon.SelectHouseLeftBarType.Bag then
            FromType = HouseCommon.PreviewModelDataType.Bag
        else
            FromType = HouseCommon.PreviewModelDataType.HouseDepot
        end

        local PartsCategory = self:RevertPartsCategoryToHouseItemCategory(HousingMgr.SelectHousePartsCategory,false)

        FromSubType = PartsCategory
        ToType = HouseCommon.PreviewModelDataType.ExteriorData
        ToSubType = FromSubType
    end


    local FromTypeItemList = {}
    local ToTypeItemList = {}

    if FromType == HouseCommon.PreviewModelDataType.Bag then
        FromTypeItemList = self.PreviewModelData.Bag[FromSubType]
    elseif FromType == HouseCommon.PreviewModelDataType.InternalDepot then
        FromTypeItemList = self.PreviewModelData.InternalDepot[FromSubType]
    elseif FromType == HouseCommon.PreviewModelDataType.HouseDepot then
        FromTypeItemList = self.PreviewModelData.HouseDepot[FromSubType]
    end

    if ToType == HouseCommon.PreviewModelDataType.InternalData then
        ToTypeItemList = self.PreviewModelData.InternalData
    elseif ToType == HouseCommon.PreviewModelDataType.ExteriorData then
        ToTypeItemList = self.PreviewModelData.ExteriorData
    end

    local SlotIndex = HouseUtil.GetSlotIndexWithPartsCategory(HousingMgr.SelectInDoorPartsCategory)

    --室内根据层数和当前选择的位置算具体那个位置
    if HousingMgr:IsInDoor() then
        if HousingMgr.SelectFloor == HouseCommon.FloorCategory.FLOOR_CATEGORY_COMMON then
            SlotIndex = 10
        else
            SlotIndex = HousingMgr.SelectFloor * 3 - 2 + SlotIndex - 1
        end
        To = ToTypeItemList[SlotIndex]
    else
        SlotIndex = HouseUtil.GetSlotIndexWithHousePartsCategory(HousingMgr.SelectHousePartsCategory)
        To = ToTypeItemList[SlotIndex]

        if To.GID == 0 then
            To = nil
        end
    end

    --如果To为nil说明那个slot是空的，所以要先把右方背包或者仓库的ITEM删除再替换掉下方的装修Slot
    if To == nil then
        self:RemovePreviewItem(FromType,FromSubType,From)
        self:AddPreviewItem(ToType,ToSubType,From,SlotIndex)
        --更新右边道具栏
        self:UpdateItemList()
        --更新下面的装修slot
        _G.EventMgr:SendEvent(_G.EventID.UpdateDecorateSlotItem,{Item = From,Index = SlotIndex})
    else
        local FromItem = {GID = From.GID,ResID = From.ResID}
        if FromTypeItemList ~= nil then
            for k,v in pairs(FromTypeItemList) do
                if v.GID == From.GID and v.ResID == From.ResID then
                    v.GID = To.GID
                    v.ResID = To.ResID
                    break
                end
            end

            --更新右边道具栏
            self.ItemIndex = self:UpdateItemIndexByGID(From.GID)

            local CurItemVM = self.CurrentItemVMList:Get(self.ItemIndex)

            if CurItemVM ~= nil then
                CurItemVM:UpdateVM({Index = CurItemVM.Index,GID = To.GID,ResID = To.ResID})
            end

        else
            FLOG_INFO("Replace From ItemList Empty")
        end

        for k,v in pairs(ToTypeItemList) do
            if v.GID == To.GID and v.ResID == To.ResID then
                v.GID = FromItem.GID
                v.ResID = FromItem.ResID
                --更新下面的装修slot
                _G.EventMgr:SendEvent(_G.EventID.UpdateDecorateSlotItem,{Item = FromItem,Index = SlotIndex})
                break
            end
        end
    end
end

function HouseMainPanelVM:RemovePreviewItem(Type,SubType,Item,Index)
    local ItemList = {}
    if Type == HouseCommon.PreviewModelDataType.Bag then
        ItemList = self.PreviewModelData.Bag[SubType]
    elseif Type == HouseCommon.PreviewModelDataType.InternalDepot then
        ItemList = self.PreviewModelData.InternalDepot[SubType]
    elseif Type == HouseCommon.PreviewModelDataType.HouseDepot then
        ItemList = self.PreviewModelData.HouseDepot[SubType]
    elseif Type == HouseCommon.PreviewModelDataType.InternalData then
        ItemList = self.PreviewModelData.InternalData
    elseif Type == HouseCommon.PreviewModelDataType.ExteriorData then
        ItemList = self.PreviewModelData.ExteriorData
    end

    --只有外装的可选配件才会有
    if Index ~= nil then
        if ItemList[Index] ~= nil then
            ItemList[Index].GID = 0
        end
    else
        if ItemList ~= nil then
            Index = 1
            for k,v in ipairs(ItemList) do
                if v.GID == Item.GID and v.ResID == Item.ResID then
                    table.remove(ItemList,Index)
                    return
                end
                Index = Index + 1
            end
        end
    end
end

function HouseMainPanelVM:AddPreviewItem(Type,SubType,Item,Index)
    local ItemList = {}

    if Type == HouseCommon.PreviewModelDataType.Bag then
        ItemList = self.PreviewModelData.Bag[SubType]
    elseif Type == HouseCommon.PreviewModelDataType.InternalDepot then
        ItemList = self.PreviewModelData.InternalDepot[SubType]
    elseif Type == HouseCommon.PreviewModelDataType.HouseDepot then
        ItemList = self.PreviewModelData.HouseDepot[SubType]
    elseif Type == HouseCommon.PreviewModelDataType.InternalData then
        ItemList = self.PreviewModelData.InternalData
    elseif Type == HouseCommon.PreviewModelDataType.ExteriorData then
        ItemList = self.PreviewModelData.ExteriorData
    end

    --这里说明蛤要将当前Itemlist中Index位置的ITEM的GID,RESID都置Item中的值
    if Index ~= nil then
        if ItemList~= nil and ItemList[Index] ~= nil then
            ItemList[Index].GID = Item.GID
            ItemList[Index].ResID = Item.ResID
        end
    else
        table.insert(ItemList,{GID = Item.GID,ResID = Item.ResID})
    end
end

--判断当前ITEM是不是被交换了，比如背包中的道具替换成了内外装SLOT中的道具这是在预览模式下
function HouseMainPanelVM:IsItemIsReplaced(Item,Slot)
    --查找原始数据确定有没有被变动
    if Slot == HouseCommon.SelectHouseLeftBarType.Bag then
        if _G.BagMgr:FindItem(Item.GID) ~= nil then
            return false
        end
    elseif Slot == HouseCommon.SelectHouseLeftBarType.StoreHouse then
        if _G.HousingMgr:FindDepotItem(Item.GID) then
            return false
        end
    elseif Slot == HouseCommon.SelectHouseLeftBarType.DecorateSlot then
        --只有外装才会需要判断替换(可选配件可为空所以可以收回到背包，在收回前需要判断是否已替换成其它物件了)
        local DoUpData = _G.HousingMgr:GetCurHouseDecorateData()

        if DoUpData.Floors ~= nil and #DoUpData.Floors > 0 then
            for k, Entity in pairs(DoUpData.Floors[1].Entities) do
                if Entity.GID == Item.GID then
                    return false
                end
            end
        end
        if DoUpData.Global ~= nil and #DoUpData.Global > 0 then
            for k, Entity in pairs(DoUpData.Global[1].Entities) do
                if Entity.GID == Item.GID then
                    return false
                end
            end
        end
    end

    return true
end

function HouseMainPanelVM:UpdateTabList()
   local HouseModel = _G.HousingMgr:GetHouseModel()

    if HouseModel ~= HouseCommon.HouseModel.None then
        self.TabList = {}
        if HouseModel == HouseCommon.HouseModel.FurnitureModel then
            local Children = {{Key = 100,Name = LSTR(1640004),IsLast = false},{Key = HouseCommon.HouseItemTabCatagory.FURNITURE_SINGLE_Placed,Name = LSTR(1640005),IsLast = false},
                              {Key = HouseCommon.HouseItemTabCatagory.FURNITURE_BASE_Placed,Name = LSTR(1640006),IsLast = false},{Key = HouseCommon.HouseItemTabCatagory.FURNITURE_DESKTOP_Placed,Name = LSTR(1640007),IsLast = false},
                              {Key = HouseCommon.HouseItemTabCatagory.FURNITURE_WALLHUNG_Placed,Name = LSTR(1640008),IsLast = false},{Key = HouseCommon.HouseItemTabCatagory.FURNITURE_CARPET_Placed,Name = LSTR(1640009),IsLast = true}}
            local Children1 = {{Key = 101,Name = LSTR(1640004),IsLast = false},{Key = HouseCommon.HouseItemTabCatagory.FURNITURE_SINGLE_Bag,Name = LSTR(1640005),IsLast = false},
                              {Key = HouseCommon.HouseItemTabCatagory.FURNITURE_BASE_Bag,Name = LSTR(1640006),IsLast = false},{Key = HouseCommon.HouseItemTabCatagory.FURNITURE_DESKTOP_Bag,Name = LSTR(1640007),IsLast = false},
                              {Key = HouseCommon.HouseItemTabCatagory.FURNITURE_WALLHUNG_Bag,Name = LSTR(1640008),IsLast = false},{Key = HouseCommon.HouseItemTabCatagory.FURNITURE_CARPET_Bag,Name = LSTR(1640009),IsLast = true}}
            local Children2 = {{Key = 102,Name = LSTR(1640004),IsLast = false},{Key = HouseCommon.HouseItemTabCatagory.FURNITURE_SINGLE_Depot,Name = LSTR(1640005),IsLast = false},
                              {Key = HouseCommon.HouseItemTabCatagory.FURNITURE_BASE_Depot,Name = LSTR(1640006),IsLast = false},{Key = HouseCommon.HouseItemTabCatagory.FURNITURE_DESKTOP_Depot,Name = LSTR(1640007),IsLast = false},
                              {Key = HouseCommon.HouseItemTabCatagory.FURNITURE_WALLHUNG_Depot,Name = LSTR(1640008),IsLast = false},{Key = HouseCommon.HouseItemTabCatagory.FURNITURE_CARPET_Depot,Name = LSTR(1640009),IsLast = true}}
            local TempItemTab1 = { Name = LSTR(1640001), Key = HouseCommon.SelectHouseLeftBarType.Placed, Children = Children}
            local TempItemTab2 = { Name = LSTR(1640002), Key = HouseCommon.SelectHouseLeftBarType.Bag, Children = Children1}
            local TempItemTab3 = { Name = LSTR(1640003), Key = HouseCommon.SelectHouseLeftBarType.StoreHouse, Children = Children2}
            table.insert(self.TabList,TempItemTab1)
            table.insert(self.TabList,TempItemTab2)
            table.insert(self.TabList,TempItemTab3)

            self.ShowTitleEntity = false
            self.PanelDecorateVisible = true
            self.ToggleBtnGridlVisible = true
            self.ToggleBtnTableVisible = true
            self.BtnCloseVisible = true
            self.BtnBackVisible = false
            self:ChangeTab(HouseModel, HouseCommon.SelectHouseLeftBarType.Placed,100)
            _G.HousingMgr:EnableGridModel(true)

        elseif HouseModel == HouseCommon.HouseModel.YardModel then
            local Children = {{Key = 100,Name = LSTR(1640004)},{Key = HouseCommon.HouseItemTabCatagory.FURNITURE_YARD_Placed,Name = LSTR(1640148),IsLast = true}}
            local Children1 = {{Key = 101,Name = LSTR(1640004)},{Key = HouseCommon.HouseItemTabCatagory.FURNITURE_YARD_Bag,Name = LSTR(1640148),IsLast = true}}
            local Children2 = {{Key = 102,Name = LSTR(1640004)},{Key = HouseCommon.HouseItemTabCatagory.FURNITURE_YARD_Depot,Name = LSTR(1640148),IsLast = true}}
            local TempItemTab1 = { Name = LSTR(1640001), Key = HouseCommon.SelectHouseLeftBarType.Placed, Children = Children}
            local TempItemTab2 = { Name = LSTR(1640002), Key = HouseCommon.SelectHouseLeftBarType.Bag, Children = Children1}
            local TempItemTab3 = { Name = LSTR(1640003), Key = HouseCommon.SelectHouseLeftBarType.StoreHouse, Children = Children2}
            table.insert(self.TabList,TempItemTab1)
            table.insert(self.TabList,TempItemTab2)
            table.insert(self.TabList,TempItemTab3)

            self.ShowTitleEntity = false
            self.PanelDecorateVisible = true
            self.ToggleBtnGridlVisible = true
            self.ToggleBtnTableVisible = false
            self.BtnCloseVisible = true
            self.BtnBackVisible = false
            self:ChangeTab(HouseModel, HouseCommon.SelectHouseLeftBarType.Placed,100)
            _G.HousingMgr:EnableGridModel(true)

        elseif HouseModel == HouseCommon.HouseModel.IndoorTerritoryModel then   --内装
            local Children = {{Key = HouseCommon.HouseItemTabCatagory.INTERIOR_WALL_Bag,Name = LSTR(1640013),IsLast = false},
                              {Key = HouseCommon.HouseItemTabCatagory.INTERIOR_FLOOR_Bag,Name = LSTR(1640014),IsLast = false},
                              {Key = HouseCommon.HouseItemTabCatagory.INTERIOR_LIGHT_Bag,Name = LSTR(1640015),IsLast = true}}
            local Children1 = {{Key = HouseCommon.HouseItemTabCatagory.INTERIOR_WALL_Depot,Name = LSTR(1640013),IsLast = false},
                              {Key = HouseCommon.HouseItemTabCatagory.INTERIOR_FLOOR_Depot,Name = LSTR(1640014),IsLast = false},
                               {Key = HouseCommon.HouseItemTabCatagory.INTERIOR_LIGHT_Depot,Name = LSTR(1640015),IsLast = true}}
            local TempItemTab1 = { Name = LSTR(1640002), Key = HouseCommon.SelectHouseLeftBarType.Bag, Children = Children}
            local TempItemTab2 = { Name = LSTR(1640003), Key = HouseCommon.SelectHouseLeftBarType.StoreHouse, Children = Children1}
            table.insert(self.TabList,TempItemTab1)
            table.insert(self.TabList,TempItemTab2)

            self.ShowTitleEntity = true
            self.PanelDecorateVisible = false
            self.ToggleBtnGridlVisible = false
            self.ToggleBtnTableVisible = false
            self.BtnCloseVisible = false
            self.BtnBackVisible = true
            self.TitleText = LSTR(1640037)
            self:ChangeTab(HouseModel, HouseCommon.SelectHouseLeftBarType.Bag,HouseCommon.HouseItemTabCatagory.INTERIOR_WALL_Bag)

        elseif HouseModel == HouseCommon.HouseModel.HouseTerritoryModel then --外装
            local OptType = _G.HousingMgr:GetHouseTerritoryType()

            self.TitleText = LSTR(1640037)
            self.PanelDecorateVisible = false
            self.ToggleBtnGridlVisible = false
            self.ToggleBtnTableVisible = false
            self.BtnCloseVisible = false
            self.BtnBackVisible = true

            if OptType == HouseCommon.TerritoryOptType.Base then
                local Children = {{Key = HouseCommon.HouseItemTabCatagory.EXTERIOR_WALL_Bag,Name = LSTR(1640019),IsLast = false},
                                  {Key = HouseCommon.HouseItemTabCatagory.EXTERIOR_ALLWALL_Bag,Name = LSTR(1640020),IsLast = false},
                                  {Key = HouseCommon.HouseItemTabCatagory.EXTERIOR_ROOF_Bag,Name = LSTR(1640021),IsLast = false},
                                  {Key = HouseCommon.HouseItemTabCatagory.EXTERIOR_WINDOW_Bag,Name = LSTR(1640022),IsLast = false},
                                  {Key = HouseCommon.HouseItemTabCatagory.EXTERIOR_DOOR_Bag,Name = LSTR(1640023),IsLast = true}}
                local Children1 = {{Key = HouseCommon.HouseItemTabCatagory.EXTERIOR_WALL_Depot,Name = LSTR(1640019),IsLast = false},
                                  {Key = HouseCommon.HouseItemTabCatagory.EXTERIOR_ALLWALL_Depot,Name = LSTR(1640020),IsLast = false},
                                   {Key = HouseCommon.HouseItemTabCatagory.EXTERIOR_ROOF_Depot,Name = LSTR(1640021),IsLast = false},
                                  {Key = HouseCommon.HouseItemTabCatagory.EXTERIOR_WINDOW_Depot,Name = LSTR(1640022),IsLast = false},
                                   {Key = HouseCommon.HouseItemTabCatagory.EXTERIOR_DOOR_Depot,Name = LSTR(1640023),IsLast = true}}
                local TempItemTab1 = { Name = LSTR(1640002), Key = HouseCommon.SelectHouseLeftBarType.Bag, Children = Children}
                local TempItemTab2 = { Name = LSTR(1640003), Key = HouseCommon.SelectHouseLeftBarType.StoreHouse, Children = Children1}
                table.insert(self.TabList,TempItemTab1)
                table.insert(self.TabList,TempItemTab2)
                self:ChangeTab(HouseModel, HouseCommon.SelectHouseLeftBarType.Bag,HouseCommon.HouseItemTabCatagory.EXTERIOR_WALL_Bag)
            else
                local Children = {{Key = HouseCommon.HouseItemTabCatagory.EXTERIOR_ROOF_OPTION_Bag,Name = LSTR(1640027),IsLast = false},
                                  {Key = HouseCommon.HouseItemTabCatagory.EXTERIOR_WALL_OPTION_Bag,Name = LSTR(1640026),IsLast = false},
                                  {Key = HouseCommon.HouseItemTabCatagory.EXTERIOR_SIGN_Bag,Name = LSTR(1640028),IsLast = false},
                                  {Key = HouseCommon.HouseItemTabCatagory.EXTERIOR_FENCE_Bag,Name = LSTR(1640029),IsLast = true}}
                local Children1 = {{Key = HouseCommon.HouseItemTabCatagory.EXTERIOR_ROOF_OPTION_Depot,Name = LSTR(1640027),IsLast = false},
                                   {Key = HouseCommon.HouseItemTabCatagory.EXTERIOR_WALL_OPTION_Depot,Name = LSTR(1640026),IsLast = false},
                                  {Key = HouseCommon.HouseItemTabCatagory.EXTERIOR_SIGN_Depot,Name = LSTR(1640028),IsLast = false},
                                   {Key = HouseCommon.HouseItemTabCatagory.EXTERIOR_FENCE_Depot,Name = LSTR(1640029),IsLast = true}}
                local TempItemTab1 = { Name = LSTR(1640002), Key = HouseCommon.SelectHouseLeftBarType.Bag, Children = Children}
                local TempItemTab2 = { Name = LSTR(1640003), Key = HouseCommon.SelectHouseLeftBarType.StoreHouse, Children = Children1}
                table.insert(self.TabList,TempItemTab1)
                table.insert(self.TabList,TempItemTab2)
                self:ChangeTab(HouseModel, HouseCommon.SelectHouseLeftBarType.Bag,HouseCommon.HouseItemTabCatagory.EXTERIOR_WALL_OPTION_Bag)
            end

            self.ShowTitleEntity = true
        end
    end
end

--region 菜单列表
function HouseMainPanelVM:GetDefaultMenuKey()
    if nil == self.TabList then
        return 0
    end

    for k,v in pairs(self.TabList) do
        if v.Key == self.TabSelectIndex then
            if nil ~= v.Children and next(v.Children) then
                return v.Children[1].Key
            else
                return v.Key
            end
        end
    end

    return 0
end

function HouseMainPanelVM:UpdateItemList()
    self.CurrentItemVMList:Clear()
    local ItemTypes = {}
    local HouseItems = {}

    local SelectGID = 0

    --先记一下之前选的GID
    --[[
    for i = 1, self.CurrentItemVMList:Length() do
        local ItemVM = self.CurrentItemVMList:Get(i)
        if ItemVM.IsSelect then
            SelectGID = ItemVM.GID
            break
        end
    end--]]

    if _G.HousingMgr:GetHouseModel() == HouseCommon.HouseModel.FurnitureModel or _G.HousingMgr:GetHouseModel() == HouseCommon.HouseModel.YardModel then
        self:UpdatePlacedInfo()
    end

    --已放置
    if self.TabSelectIndex == HouseCommon.SelectHouseLeftBarType.Placed then
        self:UpdateDepotInfo()
        local HouseDecorateInfo = _G.HousingMgr:GetHouseInfo(_G.HousingMgr.HouseID,_G.HousingMgr.Region)

        if HouseDecorateInfo ~= nil and HouseDecorateInfo.Furniture ~= nil then
            local RefreshData = {}
            
            if _G.HousingMgr:IsInDoor() then
                for _,Entity in pairs(HouseDecorateInfo.Furniture.Entities) do
                    local Cfg = HousingFurnitureCfg:FindCfgByKey(Entity.Key)

                    if self.TabSelectType == 100 or self.TabSelectType == 101 or self.TabSelectType == 102 then
                        table.insert(HouseItems,{GID = Entity.GID,ResID = Cfg.ItemID})
                    else
                        if Cfg.Category == HouseCommon.HousingItemCategoryMap[self.TabSelectType] then
                            table.insert(HouseItems,{GID = Entity.GID,ResID = Cfg.ItemID})
                        end
                    end
                end
            else
                for _,Entity in pairs(HouseDecorateInfo.Furniture.Entities) do
                    local Cfg = HousingYardCfg:FindCfgByKey(Entity.Key)
                    table.insert(HouseItems,{GID = Entity.GID,ResID = Cfg.ItemID})
                end
            end

            for k,Item in pairs(HouseItems) do
                Item.Index = #RefreshData + 1

                --if Item.GID == SelectGID then
                    --Item.Selected = true
                --end

                RefreshData[#RefreshData + 1] = Item
            end

            if #RefreshData > 0 then
                self.CommBackpackEmptyVisible = false
                self.CommBackpackEmptySVisible = false
                self.CurrentItemVMList.UpdateVMParams = {IsAllowDoubleClick = true}
                self.CurrentItemVMList:UpdateByValues(RefreshData)
            else
                if _G.HousingMgr:GetRightBarExpend() then
                    self.CommBackpackEmptyVisible = true
                    self.CommBackpackEmptySVisible = false
                else
                    self.CommBackpackEmptyVisible = false
                    self.CommBackpackEmptySVisible = true
                end
            end
        end

    elseif self.TabSelectIndex == HouseCommon.SelectHouseLeftBarType.Bag or self.TabSelectIndex == HouseCommon.SelectHouseLeftBarType.StoreHouse then
        if _G.HousingMgr:GetHouseModel() == HouseCommon.HouseModel.IndoorTerritoryModel or _G.HousingMgr:GetHouseModel() == HouseCommon.HouseModel.HouseTerritoryModel then
            table.insert(ItemTypes,self.TabSelectType)

            local PartsCategory = HouseCommon.HouseItemCatagory.Invalid

            if _G.HousingMgr:GetHouseModel() == HouseCommon.HouseModel.IndoorTerritoryModel then
                PartsCategory = self:RevertPartsCategoryToHouseItemCategory(_G.HousingMgr.SelectInDoorPartsCategory,true)
            else
                PartsCategory = self:RevertPartsCategoryToHouseItemCategory(_G.HousingMgr.SelectHousePartsCategory,false)
            end

            if PartsCategory ~= HouseCommon.HouseItemCatagory.Invalid then
                if self.TabSelectIndex == HouseCommon.SelectHouseLeftBarType.Bag then
                    --显示背包当前数量
                    self:UpdateBagInfo()

                    if self.PreviewModelData.Bag[PartsCategory] == nil then
                        HouseItems = _G.BagMainVM:GetHouseItems(ItemTypes)
                        self:AddBagPreviewData({Type = PartsCategory,Items = HouseItems})
                    else
                        HouseItems = self.PreviewModelData.Bag[PartsCategory]
                    end
                else
                    --显示仓库当前数量
                    self:UpdateDepotInfo()

                    if _G.HousingMgr:GetHouseModel() == HouseCommon.HouseModel.IndoorTerritoryModel then
                        if self.PreviewModelData.InternalDepot[PartsCategory] == nil then
                            HouseItems = _G.HousingMgr:GetDepotItems(ItemTypes)
                            self:AddDepotPreviewData({Type = PartsCategory,Items = HouseItems})
                        else
                            HouseItems = self.PreviewModelData.InternalDepot[PartsCategory]
                        end
                    else
                        if self.PreviewModelData.HouseDepot[PartsCategory] == nil then
                            HouseItems = _G.HousingMgr:GetDepotItems(ItemTypes)
                            self:AddDepotPreviewData({Type = PartsCategory,Items = HouseItems})
                        else
                            HouseItems = self.PreviewModelData.HouseDepot[PartsCategory]
                        end
                    end
                end
            end
        else
            if self.TabSelectType == 100 or self.TabSelectType == 101 or self.TabSelectType == 102 then --全部
                local Children = self.TabList[1].Children
                for k,v in ipairs(Children) do
                    if v.Key ~= 100 and v.Key ~= 101 and v.Key ~= 102 then
                        table.insert(ItemTypes,v.Key)
                    end
                end
            else
                table.insert(ItemTypes,self.TabSelectType)
            end

            if self.TabSelectIndex == HouseCommon.SelectHouseLeftBarType.Bag then
                --显示背包当前数量
                self:UpdateBagInfo()
                HouseItems = _G.BagMainVM:GetHouseItems(ItemTypes)
            else
                self:UpdateDepotInfo()
                HouseItems = _G.HousingMgr:GetDepotItems(ItemTypes)
            end
        end

        --一体墙现在没有
        if self.TabSelectType == HouseCommon.HouseItemTabCatagory.EXTERIOR_ALLWALL_Bag or self.TabSelectType == HouseCommon.HouseItemTabCatagory.EXTERIOR_ALLWALL_Depot then
            HouseItems = {}
        end

        local RefreshData = {}

        for k,Item in pairs(HouseItems) do
            Item.Index = #RefreshData + 1

            if Item.GID == SelectGID then
                Item.Selected = true
            end

            RefreshData[#RefreshData + 1] = Item
        end

        if #RefreshData > 0 then
            self.CommBackpackEmptyVisible = false
            self.CommBackpackEmptySVisible = false
            self.CurrentItemVMList.UpdateVMParams = {IsAllowDoubleClick = true}
            self.CurrentItemVMList:UpdateByValues(RefreshData)

            --这里要判断如果不符合房子大小的，则对图标做灰化
            if _G.HousingMgr:GetHouseModel() == HouseCommon.HouseModel.HouseTerritoryModel then

            end

        else
            if _G.HousingMgr:GetRightBarExpend() then
                self.CommBackpackEmptyVisible = true
                self.CommBackpackEmptySVisible = false
            else
                self.CommBackpackEmptyVisible = false
                self.CommBackpackEmptySVisible = true
            end
        end
    end
end

function HouseMainPanelVM:GetTabSelectIndex()
    return self.TabSelectIndex
end

---@type 切换标签
---@param Index number @一级标签索引
---@param SubIndex number @二级页签索引
function HouseMainPanelVM:ChangeTab(InHouseModel, ParentKey, ChildKey)
    --重复点相同的地方无效
    if self.LastHouseModel == InHouseModel and ParentKey == self.TabSelectIndex and ChildKey == self.TabSelectType then
        return
    end

    self.LastHouseModel = InHouseModel
    self.TabSelectIndex = ParentKey
    self.TabSelectType = ChildKey

    --设置选择的内装类型
    if ChildKey == HouseCommon.HouseItemTabCatagory.INTERIOR_WALL_Bag or ChildKey == HouseCommon.HouseItemTabCatagory.INTERIOR_WALL_Depot then
        _G.HousingMgr:SetSelectInDoorPartsCategory(HouseCommon.HouseInteriorParts.INTERIOR_CATEGORY_WALL)
    elseif ChildKey == HouseCommon.HouseItemTabCatagory.INTERIOR_FLOOR_Bag or ChildKey == HouseCommon.HouseItemTabCatagory.INTERIOR_FLOOR_Depot then
        _G.HousingMgr:SetSelectInDoorPartsCategory(HouseCommon.HouseInteriorParts.INTERIOR_CATEGORY_FLOOR)
    elseif ChildKey == HouseCommon.HouseItemTabCatagory.INTERIOR_LIGHT_Bag or ChildKey == HouseCommon.HouseItemTabCatagory.INTERIOR_LIGHT_Depot then
        _G.HousingMgr:SetSelectInDoorPartsCategory(HouseCommon.HouseInteriorParts.INTERIOR_CATEGORY_ILLUMINATION)
    end

    --设置选择的外装类型
    if ChildKey == HouseCommon.HouseItemTabCatagory.EXTERIOR_WALL_Bag or ChildKey == HouseCommon.HouseItemTabCatagory.EXTERIOR_WALL_Depot then
        _G.HousingMgr:SetSelectHousePartsCategory(HouseCommon.HouseExteriorParts.HOUSE_EXTERIOR_PARTS_WALL)
    elseif ChildKey == HouseCommon.HouseItemTabCatagory.EXTERIOR_ROOF_Bag or ChildKey == HouseCommon.HouseItemTabCatagory.EXTERIOR_ROOF_Depot then
        _G.HousingMgr:SetSelectHousePartsCategory(HouseCommon.HouseExteriorParts.HOUSE_EXTERIOR_PARTS_ROOF)
    elseif ChildKey == HouseCommon.HouseItemTabCatagory.EXTERIOR_WINDOW_Bag or ChildKey == HouseCommon.HouseItemTabCatagory.EXTERIOR_WINDOW_Depot then
        _G.HousingMgr:SetSelectHousePartsCategory(HouseCommon.HouseExteriorParts.HOUSE_EXTERIOR_PARTS_WIND)
    elseif ChildKey == HouseCommon.HouseItemTabCatagory.EXTERIOR_DOOR_Bag or ChildKey == HouseCommon.HouseItemTabCatagory.EXTERIOR_DOOR_Depot then
        _G.HousingMgr:SetSelectHousePartsCategory(HouseCommon.HouseExteriorParts.HOUSE_EXTERIOR_PARTS_DOOR)
    elseif ChildKey == HouseCommon.HouseItemTabCatagory.EXTERIOR_WALL_OPTION_Bag or ChildKey == HouseCommon.HouseItemTabCatagory.EXTERIOR_WALL_OPTION_Depot then
        _G.HousingMgr:SetSelectHousePartsCategory(HouseCommon.HouseExteriorParts.HOUSE_EXTERIOR_PARTS_OPT_WALL)
    elseif ChildKey == HouseCommon.HouseItemTabCatagory.EXTERIOR_ROOF_OPTION_Bag or ChildKey == HouseCommon.HouseItemTabCatagory.EXTERIOR_ROOF_Depot then
        _G.HousingMgr:SetSelectHousePartsCategory(HouseCommon.HouseExteriorParts.HOUSE_EXTERIOR_PARTS_OPT_ROOF)
    elseif ChildKey == HouseCommon.HouseItemTabCatagory.EXTERIOR_SIGN_Bag or ChildKey == HouseCommon.HouseItemTabCatagory.EXTERIOR_SIGN_Depot then
        _G.HousingMgr:SetSelectHousePartsCategory(HouseCommon.HouseExteriorParts.HOUSE_EXTERIOR_PARTS_OPT_SIGN)
    elseif ChildKey == HouseCommon.HouseItemTabCatagory.EXTERIOR_FENCE_Bag or ChildKey == HouseCommon.HouseItemTabCatagory.EXTERIOR_FENCE_Depot then
        _G.HousingMgr:SetSelectHousePartsCategory(HouseCommon.HouseExteriorParts.HOUSE_EXTERIOR_PARTS_FENCE)
    end

    if _G.HousingMgr:GetRightBarExpend() then
        self.CommBackpackEmptyVisible = true
        self.CommBackpackEmptySVisible = false
    else
        self.CommBackpackEmptyVisible = false
        self.CommBackpackEmptySVisible = true
    end

    self:UpdateItemList()
end

function HouseMainPanelVM:SetEmptyItem(IsEmpty)
    self.ItemDetailVisible = not IsEmpty
end

function HouseMainPanelVM:GetItem(Index)
    local ItemVM = self.CurrentItemVMList:Get(Index)
    if ItemVM and ItemVM.IsValid == true and ItemVM.Item then
        return ItemVM.Item
    end

    return nil
end

--设置当前选择的道具
function HouseMainPanelVM:SetCurItem(Index)
    self.CurGID = nil
    local CurItemVM = self.CurrentItemVMList:Get(self.ItemIndex)
    if CurItemVM and CurItemVM.IsValid == true and CurItemVM.Item then
        CurItemVM:SetItemSelected(false)
    end

    local ClickedItemVM = self.CurrentItemVMList:Get(Index)
    self:SetEmptyItem(ClickedItemVM == nil or ClickedItemVM.IsValid == false)
    if ClickedItemVM and ClickedItemVM.IsValid == true and ClickedItemVM.Item then
        ClickedItemVM:SetItemSelected(true)
        self.CurGID = ClickedItemVM.Item.GID
    end

    self.ItemIndex = Index
end

function HouseMainPanelVM:GetCurItem()
    local CurItemVM = self.CurrentItemVMList:Get(self.ItemIndex)
    if CurItemVM and CurItemVM.IsValid == true and CurItemVM.Item and CurItemVM.Item.GID == self.CurGID then
        CurItemVM.Item.FreezeGroup = CurItemVM.FreezeGroup
        return CurItemVM.Item
    end

    self.ItemIndex = self:UpdateItemIndexByGID(self.CurGID)

    local CurItemVM = self.CurrentItemVMList:Get(self.ItemIndex)
    if CurItemVM and CurItemVM.IsValid == true and CurItemVM.Item then
        return CurItemVM.Item
    end

    return nil
end

function HouseMainPanelVM:UpdateItemIndexByGID(GID)
    if GID == nil then
        return
    end

    for i = 1, self.CurrentItemVMList:Length() do
        local ItemVM = self.CurrentItemVMList:Get(i)
        if ItemVM and ItemVM.IsValid == true and ItemVM.Item and ItemVM.Item.GID == GID then
            return i
        end
    end
end

--更新背包信息
function HouseMainPanelVM:UpdateBagInfo()
    local Capacity = BagMgr.Capacity
    local BagCount = BagMgr:CalcBagUseCapacity()
    local CapacityText = string.format("%d/%d", BagCount, Capacity)
    self.RichTextBoxWarehouseText = RichTextUtil.GetText(string.format("%s:%s",LSTR(1640012),CapacityText), "ffffff", 0, nil)
end

function HouseMainPanelVM:UpdateDepotInfo()
    local Depot = _G.HousingMgr:GetCurrentDepot()
    local HouseRegionCfg = _G.HousingMgr:GetHouseRegionCfg()

    if HouseRegionCfg ~= nil then
        if Depot ~= nil then
            self.RichTextBoxWarehouseText = RichTextUtil.GetText(string.format("%s:%d/%d",LSTR(1640010),#Depot.ItemList,HouseRegionCfg.DepotSize), "ffffff", 0, nil)
        else
            self.RichTextBoxWarehouseText = RichTextUtil.GetText(string.format("%s:%d/%d",LSTR(1640010),0,HouseRegionCfg.DepotSize), "ffffff", 0, nil)
        end
    else
        if Depot ~= nil then
            self.RichTextBoxWarehouseText = RichTextUtil.GetText(string.format("%s:%d/%d",LSTR(1640010),#Depot.ItemList,0), "ffffff", 0, nil)
        else
            self.RichTextBoxWarehouseText = RichTextUtil.GetText(string.format("%s:%d/%d",LSTR(1640010),0,0), "ffffff", 0, nil)
        end
    end
end

function HouseMainPanelVM:UpdatePlacedInfo()
    local HouseRegionCfg = _G.HousingMgr:GetHouseRegionCfg()
    local FurnitureList = _G.HousingMgr:GetFurnitureList(_G.HousingMgr.HouseID,_G.HousingMgr.Region)

    if FurnitureList ~= nil then
        if HouseRegionCfg ~= nil then
            self.RichTextBoxlayoutText = RichTextUtil.GetText(string.format("%s:%d/%d",LSTR(1640001),#FurnitureList.Entities,HouseRegionCfg.FurnitureLimit), "ffffff", 0, nil)
        else
            self.RichTextBoxlayoutText = RichTextUtil.GetText(string.format("%s:%d/%d",LSTR(1640001),#FurnitureList.Entities,0), "ffffff", 0, nil)
        end
    else
        if HouseRegionCfg ~= nil then
            self.RichTextBoxlayoutText = RichTextUtil.GetText(string.format("%s:%d/%d",LSTR(1640001),0,HouseRegionCfg.FurnitureLimit), "ffffff", 0, nil)
        else
            self.RichTextBoxlayoutText = RichTextUtil.GetText(string.format("%s:%d/%d",LSTR(1640001),0,0), "ffffff", 0, nil)
        end
    end
end

function HouseMainPanelVM:SetHouseDecoratePanelVisible(Visible)
    self.HouseDecoratePanelVisible = Visible
end

function HouseMainPanelVM:SetTableViewSlotLVisible(Value)
    self.TableViewSlotLVisible = Value
end

function HouseMainPanelVM:SetToggleBtnArrowVisible(Value)
    self.ToggleBtnArrowVisible = Value
end

return HouseMainPanelVM