---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by skysong.
--- DateTime: 2025/5/10 11:27
---
---
local LuaClass = require("Core/LuaClass")
local UIViewModel = require("UI/UIViewModel")

---@class HouseCommMenuChildVM : UIViewModel
local HouseCommMenuChildVM = LuaClass(UIViewModel)

---Ctor
function HouseCommMenuChildVM:Ctor()
    self.Key = nil
    self.Name = ""
    self.IsUnLock = false
    self.ParentVM = nil
    self.AlwaysSelect = false
    self.Bg1Visible = false
    self.BgCradientVisible = false
end

function HouseCommMenuChildVM:IsEqualVM(Value)
    return nil ~= Value and Value.Key == self.Key
end

---UpdateVM
---@param Value table
function HouseCommMenuChildVM:UpdateVM(Value, Parent)
    self.Key = Value.Key
    self.Name = Value.Name
    self.RedDotName = Value.RedDotName
    self.RedDotID = Value.RedDotID
    self.RedDotStyle = Value.RedDotStyle
    self.RedDotText = Value.RedDotText
    self.RedDot2ID = Value.RedDot2ID
    self.RedDot2Text = Value.RedDot2Text
    self.ParentVM = Parent
    self.AlwaysSelect = Value.AlwaysSelect
    self.IsLast = Value.IsLast

    if self.IsLast then
        self.Bg1Visible = false
        self.BgCradientVisible = true
    else
        self.Bg1Visible = true
        self.BgCradientVisible = false
    end
end

function HouseCommMenuChildVM:GetKey()
    return self.Key
end

function HouseCommMenuChildVM:AdapterOnGetCanBeSelected()
    return true
end

function HouseCommMenuChildVM:AdapterOnGetWidgetIndex()
    return 1
end

function HouseCommMenuChildVM:AdapterOnGetIsCanExpand()
    return true
end

function HouseCommMenuChildVM:AdapterOnGetChildren()

end

function HouseCommMenuChildVM:AdapterOnExpansionChanged(IsExpanded)
    self.IsExpanded = IsExpanded
end

function HouseCommMenuChildVM:SetShowTogetherWithChildItem(IsShow)
    self.ParentVM:SetShowTogetherWithChildItem(IsShow)
end

function HouseCommMenuChildVM:SetNextClickItem(ItemData)
    self.ParentVM:SetNextClickItem(ItemData)
end
return HouseCommMenuChildVM