---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by mingyyzhang.
--- DateTime: 2025/7/4 11:09
---
local LuaClass = require("Core/LuaClass")
local UIViewModel = require("UI/UIViewModel")
local UIBindableList = require("UI/UIBindableList")
local MajorUtil = require("Utils/MajorUtil")
local RoleInfoMgr = require("Game/Role/RoleInfoMgr")

---@class HouseInfoInviteFriendsWinVM : UIViewModel
local HouseInfoInvitePanelVM = LuaClass(UIViewModel)

function HouseInfoInvitePanelVM:Ctor()
    self.InvitedListVisibility = true

    self.InvitedList = {}
    self.Invited = {}
end


function HouseInfoInvitePanelVM:GetInvitedList(MsgBody)
    if MsgBody then
        self.InvitedList = MsgBody
        self.InvitedListVisibility = true
    end
end










return HouseInfoInvitePanelVM