---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by mingyyzhang.
--- DateTime: 2025/7/2 10:31
---

local LuaClass = require("Core/LuaClass")
local UIViewModel = require("UI/UIViewModel")
local UIBindableList = require("UI/UIBindableList")

local RoleInfoMgr = require("Game/Role/RoleInfoMgr")
local InviteFriendListItemVM = require("Game/House/VM/Item/HouseInfoInviteFriendsItemVM")
local ChatPublicChannelItemVM = require("Game/Chat/VM/ChatPublicChannelItemVM")
local EasyToUseSelectTabVM = require("Game/Common/Frame/CommEasytoUseVM/EasyToUseSeletTabVM")

local function SortPlayerVMListPredicate(Lhs, Rhs)
    local LhsRoleVM = RoleInfoMgr:FindRoleVM(Lhs.RoleID, true)  ---@type RoleVM
    local RhsRoleVM = RoleInfoMgr:FindRoleVM(Rhs.RoleID, true)  ---@type RoleVM

    if LhsRoleVM.IsOnline ~= RhsRoleVM.IsOnline then
        return LhsRoleVM.IsOnline
    end

    if LhsRoleVM.IsOnline then
        return LhsRoleVM.LoginTime < RhsRoleVM.LoginTime
    else
        return LhsRoleVM.LogoutTime > RhsRoleVM.LogoutTime
    end
end

local function UpdatePlayerVMList(VMList, RoleIDList)
    local Values = {}
    for _, v in ipairs(RoleIDList or {}) do
        local RVM = _G.RoleInfoMgr:FindRoleVM(v.RoleID, true)

        local Value = {
            RoleID = v.RoleID,
            HasRoommate = v.SharedHouseID,
            ProfID = RVM and RVM.Prof or 1,
            HeadInfo = RVM and RVM.HeadInfo or {},
        }
        table.insert(Values, Value)
    end
    
    table.sort(Values, SortPlayerVMListPredicate)

    if VMList then
        VMList:UpdateByValues(Values)
    end
end

---@class HouseInfoInviteFriendsWinVM : UIViewModel
local HouseInfoInviteFriendsWinVM = LuaClass(UIViewModel)


function HouseInfoInviteFriendsWinVM:Ctor()
    self.IsEmptyMember = nil
    self.FilterKeyword = nil
    self.IsQuerying = nil --- 是否正在查询角色数据
    self.Menus = nil ---页签数据
    self.Players = nil ---玩家数据
    self.MenuItemVMList = nil --页签列表
    self.PlayerItemVMList = nil --玩家列表
    self.ViewingPlayerItemVMList = nil --玩家列表（显示用）
    self.FilterPlayerItemVMList = nil --玩家列表（搜索用）
    self.MenuCurSelectItem = nil
    self.ItemType = nil
    self.ExpandItem = false --目前需求不显示 后续有需求可删除
end

function HouseInfoInviteFriendsWinVM:OnShutdown()
    self:Reset()
end

function HouseInfoInviteFriendsWinVM:Reset()
    self.IsEmptyMember = true
    self.FilterKeyword = ""
    self.IsQuerying = false --- 是否正在查询角色数据
    
    
    self.MenuItemVMList = self:ResetBindableList(self.MenuItemVMList, 	EasyToUseSelectTabVM) --页签列表
    self.PlayerItemVMList = self:ResetBindableList(self.PlayerItemVMList, InviteFriendListItemVM) --玩家列表
    self.ViewingPlayerItemVMList = self.PlayerItemVMList --玩家列表（显示用）
    self.FilterPlayerItemVMList = self:ResetBindableList(self.FilterPlayerItemVMList, InviteFriendListItemVM) --玩家列表（搜索用）
    self.MenuCurSelectItem = nil
    self:ClearTimer()
end

--MenuID用于后续拓展邀请列表类型 目前只有好友
function HouseInfoInviteFriendsWinVM:RefreshInviteMemberDataByButton(MenuID)
    --- 如果在查询角色数据
    if self.IsQuerying then
        _G.FLOG_WARNING("Querying, Try Later")
        return
    end

    self.IsQuerying = true
    self:ClearTimer()
    --获取好友列表
    local RoleIDList = self:GetFriendMemberRoleIDList()
    if RoleIDList == nil  then
        _G.FLOG_WARNING("InviteSignSideWinVM:RefreshInviteMemberData MenuID is UnKnown")
        return
    elseif #RoleIDList == 0 then
        self.PlayerItemVMList:Clear()
        self.ViewingPlayerItemVMList = self.PlayerItemVMList
        self:UpdateEmptyMark()
        return
    end
    local QueryCallback = function( )
        self.IsQuerying = false
        self:ClearTimer()
        _G.HouseInfoMgr:SendPullRoleBasicInfo(RoleIDList)
    end
    ---2s后清理查询阻塞状态，防止弱网丢包阻塞
    self.ClearQueryingTimer = _G.TimerMgr:AddTimer(nil, function()
        self.IsQuerying = false
    end, 2, 0, 1)
    _G.RoleInfoMgr:QueryRoleSimples(RoleIDList, QueryCallback, nil, false)
end

function HouseInfoInviteFriendsWinVM:FreshInvite(RoleIDList)
    UpdatePlayerVMList(self.PlayerItemVMList, RoleIDList.Roles)
    self.ViewingPlayerItemVMList = self.PlayerItemVMList
    self:UpdateEmptyMark()
end

---获取好友的玩家ID列表
function HouseInfoInviteFriendsWinVM:GetFriendMemberRoleIDList()
    local Ret = {}
    for _, v in pairs(_G.FriendMgr:GetAllFriends() or {}) do
        local RoleID = v.RoleID
        table.insert(Ret, RoleID)
    end
    
    return Ret
end

--初始化Menu
function HouseInfoInviteFriendsWinVM:SetTabVMByTabValues(TabValues)
    if self.MenuItemVMList == nil then
        return
    end

    self.MenuItemVMList:Clear()
    for _, v in ipairs(TabValues) do
        local VM = ChatPublicChannelItemVM.New()
        for k, value in pairs(v) do
            VM[k] = value
        end
        self.MenuItemVMList:Add(VM)
    end
end


---通过玩家名关键词过滤
---@param Keyword string @关键词 
function HouseInfoInviteFriendsWinVM:FilterParentItemByKeyword( Keyword )
    if  Keyword == "" then
        ---按策划/视觉要求，空字符串搜索不进入搜索状态，直接清理
        self:ClearFilterData()
        return
    end
    Keyword = Keyword or ""
    UpdatePlayerVMList(self.FilterPlayerItemVMList, self:GetFilteredRoleIDList(Keyword))
    self.ViewingPlayerItemVMList = self.FilterPlayerItemVMList

    self:UpdateEmptyMark()
    self.FilterKeyword = Keyword
end

function HouseInfoInviteFriendsWinVM:GetFilteredRoleIDList(Keyword)
    local Ret = {}
    for _, v in ipairs(self.PlayerItemVMList:GetItems()) do
        local Name = v.Name
        if Name and (Keyword == nil or Keyword == "" or  Name == Keyword) then
            table.insert(Ret, v.RoleID)
        end
    end
    return Ret
end

function HouseInfoInviteFriendsWinVM:ClearFilterData()
    self.FilterKeyword = ""

    self.ViewingPlayerItemVMList = self.PlayerItemVMList
    self.FilterPlayerItemVMList:Clear()

    self:UpdateEmptyMark()
end

function HouseInfoInviteFriendsWinVM:Clear()
    self.IsQuerying = false
    self.PlayerItemVMList:Clear()
    self:ClearFilterData()
end

function HouseInfoInviteFriendsWinVM:UpdateEmptyMark()
    self.IsEmptyMember = self.ViewingPlayerItemVMList:Length() == 0
end


function HouseInfoInviteFriendsWinVM:ClearTimer()
    if self.ClearQueryingTimer then
        _G.TimerMgr:CancelTimer(self.ClearQueryingTimer)
        self.ClearQueryingTimer = nil
    end
end


return HouseInfoInviteFriendsWinVM