---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by skysong.
--- DateTime: 2025/5/10 11:51
---

local LuaClass = require("Core/LuaClass")
local UIViewModel = require("UI/UIViewModel")
local ItemCfg = require("TableCfg/ItemCfg")
local UIUtil = require("Utils/UIUtil")
local HouseCommon = require("Game/House/HouseCommon")

local LSTR = _G.LSTR

---@class HouseSlotLItemVM : UIViewModel
local HouseSlotLItemVM = LuaClass(UIViewModel)

---Ctor
function HouseSlotLItemVM:Ctor()
    self.IsSelect = nil
    self.Name = nil
    self.Item = nil
    self.IsValid = false
    self.GID = nil
    self.ResID = nil
    self.Icon = nil
end

function HouseSlotLItemVM:SetItemSelected(IsSelected)
    self.IsSelect = IsSelected
end

function HouseSlotLItemVM:IsEqualVM(Value)
    return nil ~= Value and Value.Index == self.Index
end

function HouseSlotLItemVM:SetEmptyItem(Param)
    if Param.ResID == HouseCommon.HouseItemCatagory.EXTERIOR_ROOF_OPTION then
        self.Icon = "Texture2D'/Game/UI/Texture/House/UI_House_Icon_Slot1.UI_House_Icon_Slot2'"
        self.Name = LSTR(1640027)
    elseif Param.ResID == HouseCommon.HouseItemCatagory.EXTERIOR_WALL_OPTION then
        self.Icon = "Texture2D'/Game/UI/Texture/House/UI_House_Icon_Slot1.UI_House_Icon_Slot1'"
        self.Name = LSTR(1640026)
    elseif Param.ResID == HouseCommon.HouseItemCatagory.EXTERIOR_SIGN then
        self.Icon = "Texture2D'/Game/UI/Texture/House/UI_House_Icon_Slot1.UI_House_Icon_Slot3'"
        self.Name = LSTR(1640028)
    elseif Param.ResID == HouseCommon.HouseItemCatagory.EXTERIOR_FENCE then
        self.Icon = "Texture2D'/Game/UI/Texture/House/UI_House_Icon_Slot1.UI_House_Icon_Slot4'"
        self.Name = LSTR(1640029)
    end
end

function HouseSlotLItemVM:UpdateVM(Value, Param)
    local IsValid = nil ~= Value and Value.ResID ~= nil
    self.IsValid = IsValid

    if not IsValid then
        self.ResID = nil
        return
    end

    local ValueResID = Value.ResID
    self.Index = Value.Index
    self.Item = Value
    self.GID = Value.GID

    if Value.GID == 0 then
        self:SetEmptyItem(Value.ResID)
        self.IsSelect = false
        return
    end

    self.ResID = ValueResID

    local Cfg = ItemCfg:FindCfgByKey(ValueResID)
    if nil == Cfg then
        FLOG_WARNING("ItemVM:UpdateVM can't find item cfg, ResID =%d", ValueResID)
        return
    end

    self.Name = ItemCfg:GetItemName(ValueResID)

   --rawset(self, "Name", ItemCfg:GetItemName(ValueResID))
    self.Icon = Cfg.IconID
    self.IsSelect = false
end

function HouseSlotLItemVM:AdapterOnGetCanBeSelected()
    --local Model = _G.HousingMgr:


    --local ExteriorCfg = HouseUtil.GetHousePartsCfg(CurItem.ResID)
    --local HouseID = _G.HousingMgr.HouseID
    --local HouseSize = _G.HousingMgr:GetHouseSize(HouseID)

   -- if self:CanExteriorReplace(ExteriorCfg,HouseSize) then

    return true
end

return HouseSlotLItemVM
