---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2024/12/24 14:44
---

local LuaClass = require("Core/LuaClass")
local ActorUtil = require("Utils/ActorUtil")
local ProtoRes = require("Protocol/ProtoRes")
local BandCmdBase = require("Game/TouringBand/BandTimelineExtension/BandCmd/BandCmdBase")
local TouringBandNodeAnimCfg = require("TableCfg/TouringBandNodeAnimCfg")
local TouringBandUtil = require("Game/TouringBand/TouringBandUtil")
local BandCmdAnimationClip = require("Game/TouringBand/BandTimelineExtension/BandCmd/BandCmdAnimationClip")
local NpcCfgTable = require("TableCfg/NpcCfg")
local CommonUtil = require("Utils/CommonUtil")

local BandCmdAniMulti = LuaClass(BandCmdBase)

function BandCmdAniMulti:OnInit()
    self.Name = "BandCmdAniMulti"
    self.EventType = ProtoRes.TOURING_BAND_TIMELINE_EVENT_PARENT_TYPE.TB_EVENT_BAND_ANIMATION
    self.SubCmdList = {}
    self.IsPlaying = false
    self.NpcActor = nil
end

function BandCmdAniMulti:OnStart()
    if self.Param == nil then
        TouringBandUtil.Err("BandCmdAniMulti.OnStart Create Failed ID =  : " .. self.ID)
        return
    end

    local Timeline = _G.BandTimelineMgr:GetTimelineByID(self.TimelineID)
    if Timeline == nil then
        TouringBandUtil.Err("BandCmdAniMulti.OnStart Create Failed Timeline =  : " .. self.TimelineID)
        return
    end

    local Member = Timeline:GetMemberEntityIDList()
    local EntityID = Member[self.TargetIndex]
    if EntityID <= 0 then
        TouringBandUtil.Err("BandCmdAniMulti.OnStart Failed: Invalid EntityID (0) at Index = " .. tostring(self.TargetIndex))
    end

    self.NpcActor = ActorUtil.GetActorByEntityID(EntityID)
    if self.NpcActor == nil then
        TouringBandUtil.Err("BandCmdAniMulti.OnStart Failed: Invalid self.NpcActor at EntityID = " .. tostring(EntityID))
        return
    end

    local ClipID = self.Param[1] or 0
    local ClipsCfg = TouringBandNodeAnimCfg:FindAllCfg(string.format("ClipID = %d", ClipID))

    self.SubCmdList = {}
    for __, ClipCfg in ipairs(ClipsCfg) do
        local Cmd = BandCmdAnimationClip.New()

        if Cmd ~= nil then
            Cmd:Init(ClipCfg, self.TimelineID, self.StartTime, self.PlayRate)
            Cmd:SetEntityID(EntityID)
            table.insert(self.SubCmdList, Cmd)
        end
    end
    
    self.IsPlaying = true
end

function BandCmdAniMulti:OnUpdate(DeltaTime)
    if not self.IsPlaying then
        return
    end

    if self.NpcActor == nil then
        TouringBandUtil.Err("BandCmdAniMulti.OnUpdate Failed: Invalid self.NpcActor")
        return
    end
    
    local LastTime = self.CurrentTime
    local NextTime = LastTime + DeltaTime
    self.CurrentTime = NextTime
    for _, Cmd in ipairs(self.SubCmdList) do
        if Cmd.IsEnd then
            goto continue
        end

        if not Cmd.IsStart then
            if LastTime <= Cmd.StartTime and NextTime >= Cmd.StartTime then
                Cmd:Start(Cmd.StartTime, false)
            elseif NextTime >= Cmd.StartTime and NextTime <= Cmd.EndTime then
                Cmd:Start(self.CurrentTime, true)
            end
        end
        
        if NextTime > Cmd.EndTime and Cmd.PlayCount == 0 then
            Cmd:TriggerEventAfterStartTime()
        end

        if Cmd.IsStart then
            if NextTime > Cmd.StartTime then
                Cmd:Update(DeltaTime, self.CurrentTime)
            end

            if NextTime >= Cmd.EndTime then
                Cmd:End()
            end
        end

        :: continue ::
    end

    if NextTime >= self.EndTime then
        if self.IsLoop then
            self.StartTime = self.StartTime + self.DurationTime
            self.EndTime = self.StartTime + self.DurationTime
            self.CycleNumber = self.CycleBaseNumber
            for _, Cmd in ipairs(self.CmdList) do
                Cmd:ReSetStartTime(self.StartTime)
            end
        else
            self:End()
        end
    end
end

function BandCmdAniMulti:OnEnd()
    self.IsPlaying = false

    local iNeedStop = self.Param[2] or 0
    if iNeedStop == 0 then
        return
    end
    
    if self.NpcActor == nil or not CommonUtil.IsObjectValid(self.NpcActor) then
        TouringBandUtil.Err("BandCmdAniMulti.OnEnd Failed: Invalid self.NpcActor")
        return
    end
    
    local AttributeComp = self.NpcActor:GetAttributeComponent()
    if AttributeComp == nil then
        return
    end
    
    local ResID = AttributeComp.ResID
    local NpcCfg = NpcCfgTable:FindCfgByKey(ResID)
    if NpcCfg == nil then
        return
    end

    local AnimComp = self.NpcActor:GetAnimationComponent()
    if AnimComp == nil or not CommonUtil.IsObjectValid(AnimComp) then
        return
    end

    AnimComp:StopAnimation()
end

return BandCmdAniMulti