---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2025/1/2 18:53
---

local LuaClass = require("Core/LuaClass")
local ActorUtil = require("Utils/ActorUtil")
local ProtoRes = require("Protocol/ProtoRes")
local BandCmdBase = require("Game/TouringBand/BandTimelineExtension/BandCmd/BandCmdBase")
local TouringBandNodePetCfg = require("TableCfg/TouringBandNodePetCfg")
local TouringBandUtil = require("Game/TouringBand/TouringBandUtil")
local BandCmdPlayAtl = require("Game/TouringBand/BandTimelineExtension/BandCmd/BandCmdPlayAtl")
local BandCmdMoveClip = require("Game/TouringBand/BandTimelineExtension/BandCmd/BandCmdMoveClip")

local BandCmdPetBehavior = LuaClass(BandCmdBase)

function BandCmdPetBehavior:OnInit()
    self.Name = "BandCmdPetBehavior"
    self.EventType = ProtoRes.TOURING_BAND_TIMELINE_EVENT_PARENT_TYPE.TB_EVENT_SUB_PET_BEHAVIOR
    self.SubCmdList = {}
    self.IsPlaying = false
    self.PetActor = nil
end

function BandCmdPetBehavior:OnStart()
    if self.Param == nil then
        TouringBandUtil.Err("BandCmdPetBehavior.OnStart Create Failed ID =  : " .. self.ID)
        return
    end

    local Timeline = _G.BandTimelineMgr:GetTimelineByID(self.TimelineID)
    if Timeline == nil then
        TouringBandUtil.Err("BandCmdPetBehavior.OnStart Create Failed Timeline =  : " .. self.TimelineID)
        return
    end

    local Member = Timeline:GetMemberEntityIDList()
    local EntityID = Member[ProtoRes.TOURING_BAND_TIMELINE_EVENT_TARGET_TYPE.TB_TARGET_PET]
    if EntityID <= 0 then
        TouringBandUtil.Err("BandCmdPetBehavior.OnStart Failed: Invalid EntityID (0) at Index = " .. tostring(self.TargetIndex))
    end

    self.PetActor = ActorUtil.GetActorByEntityID(EntityID)
    if self.PetActor == nil then
        TouringBandUtil.Err("BandCmdPetBehavior.OnStart Failed: Invalid self.PetActor at EntityID = " .. tostring(EntityID))
        return
    end

    local ClipID = self.Param[1] or 0
    local ClipsCfg = TouringBandNodePetCfg:FindAllCfg(string.format("ClipID = %d", ClipID))

    self.SubCmdList = {}
    for __, ClipCfg in ipairs(ClipsCfg) do
        local Cmd = nil
        if ClipCfg.Event == ProtoRes.TOURING_BAND_TIMELINE_EVENT_SUB_TYPE.TB_SUB_MOVE then
            Cmd = BandCmdMoveClip.New()
            Cmd:Init(ClipCfg, self.TimelineID, self.StartTime, self.PlayRate)
            Cmd:SetRelativePos(self.Param[2], self.Param[3], self.Param[4])
            Cmd:SetRelativeRotation(self.CenterPos, self.Param[5], self.Param[6])
        elseif ClipCfg.Event == ProtoRes.TOURING_BAND_TIMELINE_EVENT_SUB_TYPE.TB_SUB_ANIMATION then
            Cmd = BandCmdPlayAtl.New()
            Cmd:Init(ClipCfg, self.TimelineID, self.StartTime, self.PlayRate)
        end
        if Cmd ~= nil then
            Cmd:SetEntityID(EntityID)
            table.insert(self.SubCmdList, Cmd)
        end
    end

    self.IsPlaying = true
end

function BandCmdPetBehavior:OnUpdate(DeltaTime)
    if not self.IsPlaying then
        return
    end

    if self.PetActor == nil then
        TouringBandUtil.Err("BandCmdPetBehavior.OnUpdate Failed: Invalid self.PetActor")
        return
    end

    local LastTime = self.CurrentTime
    local NextTime = LastTime + DeltaTime
    self.CurrentTime = NextTime
    for _, Cmd in ipairs(self.SubCmdList) do
        if Cmd.IsEnd then
            goto continue
        end

        if not Cmd.IsStart then
            if LastTime <= Cmd.StartTime and NextTime >= Cmd.StartTime then
                Cmd:Start(Cmd.StartTime, false)
            elseif NextTime >= Cmd.StartTime and NextTime <= Cmd.EndTime then
                Cmd:Start(self.CurrentTime, true)
            end
        end

        if NextTime > Cmd.EndTime and Cmd.PlayCount == 0 then
            Cmd:TriggerEventAfterStartTime()
        end

        if Cmd.IsStart then
            if NextTime > Cmd.StartTime then
                Cmd:Update(DeltaTime, self.CurrentTime)
            end

            if NextTime >= Cmd.EndTime then
                Cmd:End()
            end
        end

        :: continue ::
    end

    if NextTime >= self.EndTime then
        if self.IsLoop then
            self.StartTime = self.StartTime + self.DurationTime
            self.EndTime = self.StartTime + self.DurationTime
            self.CycleNumber = self.CycleBaseNumber
            for _, Cmd in ipairs(self.CmdList) do
                Cmd:ReSetStartTime(self.StartTime)
            end
        else
            self:End()
        end
    end
end

function BandCmdPetBehavior:OnEnd()
    self.IsPlaying = false
end

return BandCmdPetBehavior