---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2024/7/2 17:25
---
local LuaClass = require("Core/LuaClass")
local ProtoRes = require ("Protocol/ProtoRes")
local BandCmdBase = require("Game/TouringBand/BandTimelineExtension/BandCmd/BandCmdBase")
local TouringBandUtil = require("Game/TouringBand/TouringBandUtil")

local BandCmdBubbleClip = LuaClass(BandCmdBase)

function BandCmdBubbleClip:OnInit()
    self.Name = "BandCmdBubbleClip"
    self.EventType = ProtoRes.TOURING_BAND_TIMELINE_EVENT_PARENT_TYPE.TB_EVENT_SUB_BUBBLE
end

function BandCmdBubbleClip:OnStart()
    if self.Param == nil then
        TouringBandUtil.Err("BandCmdBubbleClip.OnStart Failed ID =  : " .. self.ID)
        return
    end

    local Timeline = _G.BandTimelineMgr:GetTimelineByID(self.TimelineID)
    if not Timeline then
        TouringBandUtil.Err("BandCmdBubbleClip.OnStart Failed: Timeline not found for ID = " .. tostring(self.TimelineID))
        return
    end

    local Member = Timeline:GetMemberEntityIDList()
    local EntityID = Member[self.TargetIndex]
    if EntityID <= 0 then
        TouringBandUtil.Err("BandCmdBubbleClip.OnStart Failed: Invalid EntityID (0) at Index = " .. tostring(self.TargetIndex))
        return
    end
    
    local Bubble = self.Param[1] or 0
    _G.SpeechBubbleMgr:ShowBubbleByID(EntityID, Bubble)
end

return BandCmdBubbleClip