---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by skysong.
--- DateTime: 2023/12/13 14:22
---

local LuaClass = require("Core/LuaClass")
local UIViewModel = require("UI/UIViewModel")
local UIBindableList = require("UI/UIBindableList")
local PworldWarningCfg = require("TableCfg/PworldWarningCfg")
local PworldTextCfg = require("TableCfg/PworldTextCfg")


local WarningColor = {
    "187EB9FF", "E94767FF"
}

local WarningProBarBG =
{
    IconNormal = "PaperSprite'/Game/UI/Atlas/Warning/Frames/UI_Warning_Probar_Normal_png.UI_Warning_Probar_Normal_png'",
    IconDanger = "PaperSprite'/Game/UI/Atlas/Warning/Frames/UI_Warning_Probar_Danger_png.UI_Warning_Probar_Danger_png'",
}

local WarningProBarFillImage =
{
    IconNormal = "PaperSprite'/Game/UI/Atlas/Warning/Frames/UI_Warning_Probar_Blue_png.UI_Warning_Probar_Blue_png'",
    IconDanger = "PaperSprite'/Game/UI/Atlas/Warning/Frames/UI_Warning_Probar_Red_png.UI_Warning_Probar_Red_png'",
}

---@class WarningSkillCDItemVM : UIViewModel
local WarningSkillCDItemVM = LuaClass(UIViewModel)

---Ctor
function WarningSkillCDItemVM:Ctor()
    self.Name = ""
    self.Icon = nil
    self.RemainTime = 0.0
    self.WarningTimeProgress = 0.0
    self.RemainTimeColor = WarningColor[1]
    self.NameColor = WarningColor[1]
    self.ImgProBarBG = WarningProBarBG.IconNormal
end

--- func desc
function WarningSkillCDItemVM:OnInit()
end

--- func desc
function WarningSkillCDItemVM:OnBegin()
end

function WarningSkillCDItemVM:OnEnd()

end

function WarningSkillCDItemVM:OnShutdown()

end

function WarningSkillCDItemVM:UpdateVM(Value)
    local IsValid = nil ~= Value

    if not IsValid then
        return
    end

    self.Name = PworldTextCfg:GetText(Value.MultilingualID)
    self.RemainTime = Value.RemainTime
    self.WarningTimeProgress = Value.Percent

    if self.RemainTime < 3.0 then
        self.Icon = PworldWarningCfg:GetWarningIcon(Value.IconID,true)
        self.RemainTimeColor = WarningColor[2]
        self.NameColor = WarningColor[2]
        self.ImgProBarBG = WarningProBarBG.IconDanger

        local BindableProperty = self:FindBindableProperty("WarningTimeProgress")

        if BindableProperty ~= nil then
            if #BindableProperty.Binders > 0 then
                UIUtil.ProgressBarSetFillImage(BindableProperty.Binders[1].Widget,WarningProBarFillImage.IconDanger)
            end
        end

    else
        self.Icon = PworldWarningCfg:GetWarningIcon(Value.IconID,false)
        self.RemainTimeColor = WarningColor[1]
        self.NameColor = WarningColor[1]
        self.ImgProBarBG = WarningProBarBG.IconNormal

        local BindableProperty = self:FindBindableProperty("WarningTimeProgress")

        if BindableProperty ~= nil then
            if #BindableProperty.Binders > 0 then
                UIUtil.ProgressBarSetFillImage(BindableProperty.Binders[1].Widget,WarningProBarFillImage.IconNormal)
            end
        end
    end
end

return WarningSkillCDItemVM