-- AUTO GENERATED CODE BEGIN, PLEASE DON'T MODIFY

local CfgBase = require("TableCfg/CfgBase")

local CS = {
    _1_1 = '[]',
    _1_2 = '[6]',
    _1_3 = '[3]',
    _2_1 = 'Texture2D\'/Game/Assets/Icon/ItemIcon/907000/UI_Icon_907003.UI_Icon_907003\'',
    _2_2 = 'Texture2D\'/Game/Assets/Icon/ItemIcon/907000/UI_Icon_907002.UI_Icon_907002\'',
    _2_3 = 'Texture2D\'/Game/Assets/Icon/ItemIcon/008000/UI_Icon_008017.UI_Icon_008017\'',
    _2_4 = 'Texture2D\'/Game/Assets/Icon/ItemIcon/008000/UI_Icon_008018.UI_Icon_008018\'',
    _2_5 = 'Texture2D\'/Game/Assets/Icon/ItemIcon/008000/UI_Icon_008019.UI_Icon_008019\'',
    _2_6 = 'Texture2D\'/Game/Assets/Icon/ItemIcon/903000/UI_Icon_903725.UI_Icon_903725\'',
    _3_1 = 'B',
    _4_1 = '2.2.0',
    _4_2 = '2.0.1',
    _4_3 = '2.0.0',
    _4_4 = '3.0.0',
    _4_5 = '2.3.8',
    _5_1 = 'a0001',
}

---@class FashionDecorateCfg : CfgBase
local FashionDecorateCfg = {
	TableName = "c_FashionDecorate_cfg",
    LruKeyType = nil,
	KeyName = "ID",
    bEncrypted = false,
	Localization = {
        Config = {
            {
                Name = 'Name',
            },
		}
    },
    DefaultValues = {
        _Action = '[1,2]',
        CustomizeGroup = 1,
        DecorationType = 2,
        ID = 1,
        Icon = 'Texture2D\'/Game/Assets/Icon/ItemIcon/008000/UI_Icon_008020.UI_Icon_008020\'',
        ImeChanId = 1,
        PackageName = '',
        PatternId = 1,
        PoseEmoteStance = 0,
        SkeletonId = 6001,
        VersionName = '',
        papvariation = '',
    },
	LuaData = {
        {
            DecorationType = 1,
            Icon = 'Texture2D\'/Game/Assets/Icon/ItemIcon/008000/UI_Icon_008001.UI_Icon_008001\'',
            PackageName = CS._3_1,
            PoseEmoteStance = 1,
            VersionName = CS._4_5,
        },
        {
            DecorationType = 1,
            ID = 2,
            Icon = 'Texture2D\'/Game/Assets/Icon/ItemIcon/008000/UI_Icon_008002.UI_Icon_008002\'',
            ImeChanId = 2,
            PackageName = CS._3_1,
            PoseEmoteStance = 1,
            VersionName = CS._4_3,
        },
        {
            DecorationType = 1,
            ID = 3,
            Icon = 'Texture2D\'/Game/Assets/Icon/ItemIcon/008000/UI_Icon_008003.UI_Icon_008003\'',
            PatternId = 2,
            PoseEmoteStance = 1,
        },
        {
            DecorationType = 1,
            ID = 4,
            Icon = 'Texture2D\'/Game/Assets/Icon/ItemIcon/008000/UI_Icon_008004.UI_Icon_008004\'',
            ImeChanId = 2,
            PatternId = 2,
            PoseEmoteStance = 1,
        },
        {
            DecorationType = 1,
            ID = 5,
            Icon = 'Texture2D\'/Game/Assets/Icon/ItemIcon/008000/UI_Icon_008005.UI_Icon_008005\'',
            ImeChanId = 3,
            PatternId = 2,
            PoseEmoteStance = 1,
        },
        {
            DecorationType = 1,
            ID = 6,
            Icon = 'Texture2D\'/Game/Assets/Icon/ItemIcon/008000/UI_Icon_008006.UI_Icon_008006\'',
            PackageName = CS._3_1,
            PatternId = 3,
            PoseEmoteStance = 1,
            VersionName = CS._4_1,
        },
        {
            DecorationType = 1,
            ID = 7,
            Icon = 'Texture2D\'/Game/Assets/Icon/ItemIcon/008000/UI_Icon_008007.UI_Icon_008007\'',
            ImeChanId = 2,
            PatternId = 3,
            PoseEmoteStance = 1,
        },
        {
            DecorationType = 1,
            ID = 8,
            Icon = 'Texture2D\'/Game/Assets/Icon/ItemIcon/008000/UI_Icon_008008.UI_Icon_008008\'',
            ImeChanId = 3,
            PatternId = 3,
            PoseEmoteStance = 1,
        },
        {
            _Action = CS._1_1,
            CustomizeGroup = 2,
            ID = 9,
            Icon = 'Texture2D\'/Game/Assets/Icon/ItemIcon/008000/UI_Icon_008013.UI_Icon_008013\'',
            PackageName = CS._3_1,
            SkeletonId = 6002,
            VersionName = CS._4_1,
            papvariation = CS._5_1,
        },
        {
            DecorationType = 1,
            ID = 10,
            Icon = 'Texture2D\'/Game/Assets/Icon/ItemIcon/008000/UI_Icon_008012.UI_Icon_008012\'',
            PatternId = 5,
            PoseEmoteStance = 1,
        },
        {
            DecorationType = 1,
            ID = 11,
            Icon = 'Texture2D\'/Game/Assets/Icon/ItemIcon/008000/UI_Icon_008009.UI_Icon_008009\'',
            PatternId = 4,
            PoseEmoteStance = 1,
        },
        {
            DecorationType = 1,
            ID = 12,
            Icon = 'Texture2D\'/Game/Assets/Icon/ItemIcon/008000/UI_Icon_008010.UI_Icon_008010\'',
            ImeChanId = 2,
            PatternId = 4,
            PoseEmoteStance = 1,
        },
        {
            DecorationType = 1,
            ID = 13,
            Icon = 'Texture2D\'/Game/Assets/Icon/ItemIcon/008000/UI_Icon_008011.UI_Icon_008011\'',
            ImeChanId = 3,
            PackageName = CS._3_1,
            PatternId = 4,
            PoseEmoteStance = 1,
            VersionName = '2.3.5',
        },
        {
            DecorationType = 1,
            ID = 14,
            Icon = 'Texture2D\'/Game/Assets/Icon/ItemIcon/008000/UI_Icon_008014.UI_Icon_008014\'',
            PatternId = 6,
            PoseEmoteStance = 1,
        },
        {
            DecorationType = 1,
            ID = 15,
            Icon = 'Texture2D\'/Game/Assets/Icon/ItemIcon/008000/UI_Icon_008015.UI_Icon_008015\'',
            PatternId = 7,
            PoseEmoteStance = 1,
        },
        {
            DecorationType = 1,
            ID = 16,
            Icon = 'Texture2D\'/Game/Assets/Icon/ItemIcon/008000/UI_Icon_008016.UI_Icon_008016\'',
            PatternId = 8,
            PoseEmoteStance = 1,
        },
        {
            _Action = CS._1_1,
            CustomizeGroup = 2,
            ID = 17,
            Icon = CS._2_3,
            ImeChanId = 2,
            PackageName = CS._3_1,
            SkeletonId = 6002,
            VersionName = CS._4_3,
            papvariation = CS._5_1,
        },
        {
            _Action = CS._1_1,
            CustomizeGroup = 2,
            ID = 18,
            Icon = CS._2_4,
            ImeChanId = 3,
            PackageName = CS._3_1,
            SkeletonId = 6002,
            VersionName = CS._4_1,
            papvariation = CS._5_1,
        },
        {
            _Action = CS._1_1,
            CustomizeGroup = 3,
            ID = 19,
            Icon = CS._2_5,
            SkeletonId = 6003,
            VersionName = CS._4_4,
        },
        {
            _Action = CS._1_1,
            CustomizeGroup = 6,
            ID = 20,
            SkeletonId = 6004,
        },
        {
            _Action = CS._1_2,
            CustomizeGroup = 1002,
            ID = 1001,
            Icon = CS._2_1,
            ImeChanId = 1001,
            PackageName = CS._3_1,
            PatternId = 1001,
            SkeletonId = 6003,
            VersionName = CS._4_2,
            papvariation = CS._5_1,
        },
        {
            _Action = CS._1_3,
            CustomizeGroup = 1001,
            ID = 1002,
            Icon = CS._2_2,
            PackageName = CS._3_1,
            SkeletonId = 90009,
            VersionName = CS._4_1,
            papvariation = CS._5_1,
        },
        {
            _Action = CS._1_1,
            CustomizeGroup = 1003,
            ID = 1003,
            Icon = 'Texture2D\'/Game/Assets/Icon/ItemIcon/903000/UI_Icon_903724.UI_Icon_903724\'',
            PatternId = 1001,
            SkeletonId = 6002,
            VersionName = CS._4_3,
            papvariation = CS._5_1,
        },
        {
            _Action = CS._1_1,
            CustomizeGroup = 1004,
            ID = 1004,
            Icon = CS._2_6,
            ImeChanId = 2,
            PatternId = 1001,
            SkeletonId = 6002,
            VersionName = CS._4_3,
            papvariation = CS._5_1,
        },
        {
            _Action = CS._1_1,
            CustomizeGroup = 1005,
            ID = 1005,
            Icon = CS._2_6,
            ImeChanId = 2,
            PatternId = 1001,
            SkeletonId = 6002,
            VersionName = CS._4_5,
            papvariation = CS._5_1,
        },
        {
            _Action = CS._1_1,
            CustomizeGroup = 2,
            ID = 2001,
            Icon = CS._2_3,
            ImeChanId = 2,
            PackageName = CS._3_1,
            SkeletonId = 6002,
            VersionName = CS._4_3,
            papvariation = CS._5_1,
        },
        {
            _Action = CS._1_1,
            CustomizeGroup = 2,
            ID = 2002,
            Icon = CS._2_4,
            ImeChanId = 3,
            SkeletonId = 6002,
            VersionName = CS._4_4,
        },
        {
            _Action = CS._1_1,
            CustomizeGroup = 3,
            ID = 2003,
            Icon = CS._2_5,
            SkeletonId = 6003,
            VersionName = CS._4_4,
        },
        {
            _Action = CS._1_1,
            CustomizeGroup = 6,
            ID = 2004,
            SkeletonId = 6004,
        },
        {
            _Action = CS._1_2,
            CustomizeGroup = 1002,
            ID = 2005,
            Icon = CS._2_1,
            ImeChanId = 1001,
            PackageName = CS._3_1,
            PatternId = 1001,
            SkeletonId = 6003,
            VersionName = CS._4_2,
            papvariation = CS._5_1,
        },
        {
            _Action = CS._1_3,
            CustomizeGroup = 1001,
            ID = 2006,
            Icon = CS._2_2,
            PackageName = CS._3_1,
            SkeletonId = 90009,
            VersionName = CS._4_1,
            papvariation = CS._5_1,
        },
        {
            _Action = CS._1_1,
            CustomizeGroup = 6,
            ID = 2007,
            SkeletonId = 6004,
        },
        {
            _Action = CS._1_2,
            CustomizeGroup = 1002,
            ID = 2008,
            Icon = CS._2_1,
            ImeChanId = 1001,
            PackageName = CS._3_1,
            PatternId = 1001,
            SkeletonId = 6003,
            VersionName = CS._4_2,
            papvariation = CS._5_1,
        },
        {
            _Action = CS._1_3,
            CustomizeGroup = 1001,
            ID = 2009,
            Icon = CS._2_2,
            PackageName = CS._3_1,
            SkeletonId = 90009,
            VersionName = CS._4_1,
            papvariation = CS._5_1,
        },
        {
            _Action = CS._1_1,
            CustomizeGroup = 6,
            ID = 2010,
            SkeletonId = 6004,
        },
        {
            _Action = CS._1_2,
            CustomizeGroup = 1002,
            ID = 2011,
            Icon = CS._2_1,
            ImeChanId = 1001,
            PackageName = CS._3_1,
            PatternId = 1001,
            SkeletonId = 6003,
            VersionName = CS._4_2,
            papvariation = CS._5_1,
        },
        {
            _Action = CS._1_3,
            CustomizeGroup = 1001,
            ID = 2012,
            Icon = CS._2_2,
            PackageName = CS._3_1,
            SkeletonId = 90009,
            VersionName = CS._4_1,
            papvariation = CS._5_1,
        },
        {
            _Action = CS._1_2,
            CustomizeGroup = 1002,
            ID = 10012,
            Icon = 'Texture2D\'/Game/Assets/Icon/ItemIcon/907000/UI_Icon_907059.UI_Icon_907059\'',
            ImeChanId = 1002,
            PackageName = CS._3_1,
            PatternId = 1001,
            SkeletonId = 6003,
            VersionName = CS._4_2,
            papvariation = CS._5_1,
        },
        {
            _Action = CS._1_2,
            CustomizeGroup = 1002,
            ID = 10013,
            Icon = 'Texture2D\'/Game/Assets/Icon/ItemIcon/907000/UI_Icon_907060.UI_Icon_907060\'',
            ImeChanId = 1003,
            PackageName = CS._3_1,
            PatternId = 1001,
            SkeletonId = 6003,
            VersionName = CS._4_2,
            papvariation = CS._5_1,
        },
        {
            _Action = CS._1_2,
            CustomizeGroup = 1002,
            ID = 10014,
            Icon = 'Texture2D\'/Game/Assets/Icon/ItemIcon/907000/UI_Icon_907061.UI_Icon_907061\'',
            ImeChanId = 1004,
            PackageName = CS._3_1,
            PatternId = 1001,
            SkeletonId = 6003,
            VersionName = CS._4_2,
            papvariation = CS._5_1,
        },
	},
}

setmetatable(FashionDecorateCfg, { __index = CfgBase })

FashionDecorateCfg:InitCfg()

-- AUTO GENERATED CODE END, PLEASE DON'T MODIFY

return FashionDecorateCfg
