-- AUTO GENERATED CODE BEGIN, PLEASE DON'T MODIFY

local CfgBase = require("TableCfg/CfgBase")

local CS = {
    _1_1 = '_G.CompanySealMgr:IsOpenCompany()',
    _2_1 = '_G.StoreMgr:JumpToGoods(nil,10011,false)',
    _3_1 = '完成15级支线任务开放。',
    _3_2 = '完成4级主线任务后，完成支线任务开放。',
    _3_3 = '5级主线任务后开放。',
    _3_4 = '未解锁该副本',
    _3_5 = '完成10级主线任务开放。',
    _4_1 = '["1"]',
    _4_2 = '["3"]',
    _4_3 = '["2"]',
    _4_4 = '["1","1"]',
    _4_5 = '["25010301"]',
    _4_6 = '["weimingrenwu"]',
    _4_7 = '["3","1202022"]',
    _4_8 = '["3","1203277"]',
    _4_9 = '["25043007"]',
    _4_10 = '["25043005"]',
    _4_11 = '["25043006"]',
}

---@class JumpCfg : CfgBase
local JumpCfg = {
	TableName = "c_jump_cfg",
    LruKeyType = nil,
	KeyName = "ID",
    bEncrypted = false,
	Localization = {
        Config = {}
    },
    DefaultValues = {
        CheckOpenFunc = '',
        CustomJumpFunc = '',
        ForbiddenTips = '',
        ID = 1,
        JumpType = 1,
        ModuleID = 0,
        _Params = '[]',
        ViewID = 0,
    },
	LuaData = {
        {
            ModuleID = 118,
            _Params = CS._4_3,
            ViewID = 1314,
        },
        {
            ID = 2,
            JumpType = 2,
            ModuleID = 140,
            _Params = '["5","1","240"]',
        },
        {
            ID = 3,
            ModuleID = 104,
            ViewID = 300201,
        },
        {
            ID = 4,
            ModuleID = 106,
            ViewID = 300002,
        },
        {
            ID = 5,
            ModuleID = 105,
            ViewID = 300601,
        },
        {
            CheckOpenFunc = CS._1_1,
            CustomJumpFunc = '_G.AdventureMgr:JumpSupplyByGrandCompanyID()',
            ID = 6,
            JumpType = 3,
        },
        {
            ForbiddenTips = CS._3_2,
            ID = 7,
            ModuleID = 132,
            ViewID = 201700,
        },
        {
            ID = 8,
            JumpType = 2,
            ModuleID = 122,
            _Params = CS._4_4,
        },
        {
            ID = 9,
            ModuleID = 125,
            ViewID = 301301,
        },
        {
            CustomJumpFunc = '_G.TreasureHuntMgr:OpenTreasureHuntMainPanel()',
            ForbiddenTips = '完成30级支线任务开放。',
            ID = 10,
            JumpType = 3,
            ModuleID = 146,
        },
        {
            ForbiddenTips = CS._3_2,
            ID = 11,
            ModuleID = 148,
            ViewID = 302001,
        },
        {
            CustomJumpFunc = '_G.FateMgr:ShowFateArchive()',
            ID = 12,
            JumpType = 3,
        },
        {
            ID = 13,
            ModuleID = 138,
            ViewID = 2240,
        },
        {
            ID = 14,
            JumpType = 4,
            _Params = '["12060","29100004"]',
        },
        {
            ID = 15,
            JumpType = 4,
            _Params = '["12060","1011093"]',
        },
        {
            ForbiddenTips = CS._3_1,
            ID = 16,
            JumpType = 15,
            ModuleID = 138,
            _Params = '["201"]',
        },
        {
            ForbiddenTips = CS._3_3,
            ID = 17,
            JumpType = 7,
            ModuleID = 101,
            _Params = '["233"]',
        },
        {
            ID = 18,
            ModuleID = 124,
            _Params = CS._4_1,
            ViewID = 6000,
        },
        {
            CustomJumpFunc = '_G.WorldMapMgr:ShowCurrWorldMap()',
            ID = 19,
            JumpType = 3,
        },
        {
            ForbiddenTips = '完成11级主线任务开放。',
            ID = 20,
            ModuleID = 122,
            _Params = CS._4_1,
            ViewID = 3301,
        },
        {
            ID = 21,
            ModuleID = 158,
            _Params = '["4","1"]',
            ViewID = 3301,
        },
        {
            ID = 22,
            ModuleID = 158,
            _Params = '["4","28"]',
            ViewID = 3301,
        },
        {
            CustomJumpFunc = '_G.WardrobeMgr:OpenWardrobeMainPanel()',
            ID = 23,
            JumpType = 3,
            ModuleID = 119,
        },
        {
            CustomJumpFunc = '_G.AetherCurrentsMgr:OpenAetherCurrentMainPanel()',
            ForbiddenTips = '完成5级主线任务开放。',
            ID = 24,
            JumpType = 3,
            ModuleID = 145,
        },
        {
            CustomJumpFunc = '_G.DiscoverNoteMgr:OpenDiscoverNoteMainPanel()',
            ForbiddenTips = '完成17级主线任务后，完成支线任务开放。',
            ID = 25,
            JumpType = 3,
            ModuleID = 144,
        },
        {
            CheckOpenFunc = '_G.TouringBandMgr:IsTouringBandUnLock()',
            CustomJumpFunc = '_G.TouringBandMgr:OpenTouringBandView()',
            ID = 26,
            JumpType = 3,
            ModuleID = 155,
        },
        {
            ForbiddenTips = CS._3_1,
            ID = 27,
            JumpType = 15,
            ModuleID = 143,
            _Params = '["502"]',
        },
        {
            ForbiddenTips = CS._3_1,
            ID = 28,
            JumpType = 15,
            ModuleID = 142,
            _Params = '["501"]',
        },
        {
            ForbiddenTips = CS._3_1,
            ID = 29,
            JumpType = 15,
            ModuleID = 141,
            _Params = '["4"]',
        },
        {
            ForbiddenTips = CS._3_1,
            ID = 30,
            JumpType = 15,
            ModuleID = 140,
            _Params = '["302"]',
        },
        {
            ID = 31,
            ModuleID = 118,
            _Params = CS._4_1,
            ViewID = 1314,
        },
        {
            ForbiddenTips = '您还未解锁战令系统',
            ID = 32,
            ModuleID = 133,
            ViewID = 201900,
        },
        {
            CustomJumpFunc = '_G.QuestMgr:OpenPanelByQuestType(0)',
            ID = 33,
            JumpType = 3,
        },
        {
            ForbiddenTips = '任一能工巧匠、大地使者职业等级40级后，完成支线任务开放。',
            ID = 34,
            ModuleID = 137,
            ViewID = 300301,
        },
        {
            CheckOpenFunc = CS._1_1,
            ForbiddenTips = '您还未解锁军需品筹备',
            ID = 35,
            ModuleID = 151,
            _Params = CS._4_1,
            ViewID = 301901,
        },
        {
            ID = 36,
            ViewID = 4701,
        },
        {
            CustomJumpFunc = '_G.EquipmentMgr:OpenEquipmentMainPanelAndProfTab(true)',
            ID = 37,
            JumpType = 3,
        },
        {
            CustomJumpFunc = '_G.EquipmentMgr:OpenEquipmentMainPanelAndProfTab(false)',
            ID = 38,
            JumpType = 3,
        },
        {
            CustomJumpFunc = '_G.ShopMgr:OpenInletMainView(2)',
            ID = 39,
            JumpType = 3,
        },
        {
            CustomJumpFunc = '_G.ShopMgr:OpenInletMainView(3)',
            ID = 40,
            JumpType = 3,
        },
        {
            CustomJumpFunc = '_G.WorldMapMgr:ShowWorldMapChocoboStable()',
            ID = 41,
            JumpType = 3,
        },
        {
            ForbiddenTips = CS._3_3,
            ID = 42,
            JumpType = 9,
            _Params = '["61700041"]',
        },
        {
            CustomJumpFunc = CS._2_1,
            ID = 43,
            JumpType = 3,
            ModuleID = 120,
        },
        {
            CustomJumpFunc = '_G.StoreMgr:JumpToCategoryPage(1)',
            ID = 44,
            JumpType = 3,
            ModuleID = 120,
        },
        {
            ID = 45,
            _Params = CS._4_5,
            ViewID = 6009,
        },
        {
            ID = 46,
            ModuleID = 157,
            _Params = CS._4_2,
            ViewID = 6000,
        },
        {
            CustomJumpFunc = '_G.StoreMgr:JumpToCategoryPage(2)',
            ID = 47,
            JumpType = 3,
            ModuleID = 120,
        },
        {
            ID = 48,
            JumpType = 9,
            _Params = '["90000110"]',
        },
        {
            ID = 49,
            JumpType = 9,
            _Params = '["90000111"]',
        },
        {
            ID = 50,
            JumpType = 9,
            _Params = '["90001077"]',
        },
        {
            ID = 51,
            JumpType = 9,
            _Params = '["90000113"]',
        },
        {
            ID = 52,
            JumpType = 9,
            _Params = '["90000112"]',
        },
        {
            ID = 53,
            JumpType = 9,
            _Params = '["90001069"]',
        },
        {
            ID = 54,
            JumpType = 5,
            _Params = '["https://ff14m.qq.com/act/a20250113nczdzzm/index.html"]',
        },
        {
            ForbiddenTips = '请先解锁金碟游乐场玩法',
            ID = 55,
            JumpType = 10,
            _Params = '["2002","200207"]',
        },
        {
            ID = 56,
            ModuleID = 109,
            _Params = CS._4_2,
            ViewID = 1314,
        },
        {
            ID = 57,
            JumpType = 11,
            _Params = '["26019"]',
        },
        {
            ID = 58,
            JumpType = 11,
            _Params = '["26020"]',
        },
        {
            ID = 59,
            JumpType = 21,
            _Params = '["11002","930.8","801.3"]',
        },
        {
            ID = 60,
            JumpType = 10,
            _Params = '["7001"]',
        },
        {
            ForbiddenTips = CS._3_5,
            ID = 61,
            JumpType = 13,
            ModuleID = 160,
        },
        {
            CustomJumpFunc = '_G.FateMgr:ShowFateArchive(nil,nil,true)',
            ID = 62,
            JumpType = 3,
        },
        {
            ID = 63,
            JumpType = 12,
            _Params = '["yitaizhiguang"]',
        },
        {
            ID = 64,
            JumpType = 12,
            _Params = '["meirisuijirenwu"]',
        },
        {
            ID = 65,
            JumpType = 12,
            _Params = '["zhuxianrenwu"]',
        },
        {
            ID = 66,
            JumpType = 12,
            _Params = '["shengchanzhiye"]',
        },
        {
            ID = 67,
            JumpType = 12,
            _Params = '["yichu"]',
        },
        {
            ID = 68,
            JumpType = 12,
            _Params = '["luxingniaofang"]',
        },
        {
            ID = 69,
            JumpType = 12,
            _Params = '["fengmaiquan"]',
        },
        {
            ID = 70,
            JumpType = 12,
            _Params = CS._4_6,
        },
        {
            ID = 71,
            JumpType = 12,
            _Params = '["jindieyoulechang"]',
        },
        {
            ID = 72,
            JumpType = 12,
            _Params = '["daxiaoshuijingzonghe"]',
        },
        {
            ID = 73,
            JumpType = 12,
            _Params = CS._4_6,
        },
        {
            ID = 74,
            JumpType = 12,
            _Params = '["xunbao"]',
        },
        {
            ID = 75,
            JumpType = 12,
            _Params = '["tansuobiji"]',
        },
        {
            ID = 76,
            JumpType = 12,
            _Params = '["xunhuiyuetuan"]',
        },
        {
            ID = 77,
            JumpType = 12,
            _Params = '["yewaibaoxiang"]',
        },
        {
            ID = 78,
            JumpType = 12,
            _Params = '["maoxianyoushangtuan"]',
        },
        {
            ID = 79,
            JumpType = 12,
            _Params = '["xianrenweicai"]',
        },
        {
            ID = 80,
            JumpType = 12,
            _Params = '["xianrenxiancai"]',
        },
        {
            ID = 81,
            JumpType = 12,
            _Params = '["shishangpinjian"]',
        },
        {
            ID = 82,
            JumpType = 12,
            _Params = '["luxingniaojingsai"]',
        },
        {
            ID = 83,
            JumpType = 12,
            _Params = '["jiugonghuankaduiju"]',
        },
        {
            ID = 84,
            JumpType = 12,
            _Params = '["jiyulinmenwanfa"]',
        },
        {
            ID = 85,
            JumpType = 12,
            _Params = '["jindiexiaoyouxi"]',
        },
        {
            ID = 86,
            JumpType = 12,
            _Params = '["zhandouzhiye"]',
        },
        {
            ID = 87,
            JumpType = 12,
            _Params = '["huoquzhandoujingyan"]',
        },
        {
            ID = 88,
            JumpType = 12,
            _Params = '["zhuangdengtisheng"]',
        },
        {
            ID = 89,
            JumpType = 12,
            _Params = '["shendianshi"]',
        },
        {
            ID = 90,
            JumpType = 12,
            _Params = '["jizhitexun"]',
        },
        {
            ID = 91,
            JumpType = 12,
            _Params = '["dadishizhe"]',
        },
        {
            ID = 92,
            JumpType = 12,
            _Params = '["nenggongqiaojiang"]',
        },
        {
            ID = 93,
            JumpType = 12,
            _Params = '["lifurenwu"]',
        },
        {
            ID = 94,
            JumpType = 12,
            _Params = '["choubeijunxupinbujipin"]',
        },
        {
            ID = 95,
            JumpType = 12,
            _Params = '["shoucangpin"]',
        },
        {
            ID = 96,
            JumpType = 9,
            _Params = '["90000107"]',
        },
        {
            ID = 97,
            JumpType = 9,
            _Params = '["90000106"]',
        },
        {
            ID = 98,
            JumpType = 11,
            _Params = '["22019"]',
        },
        {
            ID = 99,
            JumpType = 11,
            _Params = '["22020"]',
        },
        {
            ID = 100,
            JumpType = 11,
            _Params = '["22021"]',
        },
        {
            ID = 101,
            JumpType = 10,
            _Params = '["7002"]',
        },
        {
            ID = 102,
            _Params = '["24121001"]',
            ViewID = 6000,
        },
        {
            ID = 103,
            _Params = '["24112101"]',
            ViewID = 6000,
        },
        {
            ID = 104,
            _Params = '["24120402"]',
            ViewID = 6000,
        },
        {
            ID = 105,
            _Params = '["24120403"]',
            ViewID = 6000,
        },
        {
            ID = 106,
            _Params = '["24120404"]',
            ViewID = 6000,
        },
        {
            ID = 107,
            _Params = '["24112501"]',
            ViewID = 6000,
        },
        {
            ID = 108,
            _Params = '["24112502"]',
            ViewID = 6000,
        },
        {
            ID = 109,
            JumpType = 14,
            _Params = CS._4_4,
        },
        {
            CheckOpenFunc = CS._1_1,
            ID = 110,
            ModuleID = 151,
            _Params = CS._4_3,
            ViewID = 301901,
        },
        {
            CheckOpenFunc = CS._1_1,
            ForbiddenTips = '您还未解锁稀有品筹备',
            ID = 111,
            ModuleID = 151,
            _Params = CS._4_2,
            ViewID = 301901,
        },
        {
            ID = 112,
            _Params = '["25032605"]',
            ViewID = 6000,
        },
        {
            ID = 113,
            JumpType = 4,
            _Params = '["12004","2006110"]',
        },
        {
            ID = 114,
            JumpType = 7,
            ModuleID = 101,
            _Params = '["1001"]',
        },
        {
            ID = 115,
            JumpType = 9,
            _Params = '["61700043"]',
        },
        {
            ForbiddenTips = '请先解锁<span color="#D1BA8E">展示魔科学滑板</>的情感动作',
            ID = 116,
            JumpType = 17,
            _Params = '["2","1001"]',
        },
        {
            ID = 117,
            JumpType = 16,
            _Params = '["25032801","200011"]',
        },
        {
            CustomJumpFunc = '_G.StoreMgr:JumpToGoods(nil,10007,false)',
            ID = 118,
            JumpType = 3,
            ModuleID = 120,
        },
        {
            CustomJumpFunc = '_G.StoreMgr:JumpToGoods(nil,10009,false)',
            ID = 119,
            JumpType = 3,
            ModuleID = 120,
        },
        {
            CustomJumpFunc = '_G.StoreMgr:JumpToGoods(nil,30016,false)',
            ID = 120,
            JumpType = 3,
            ModuleID = 120,
        },
        {
            CustomJumpFunc = '_G.StoreMgr:JumpToGoods(nil,30001,false)',
            ID = 121,
            JumpType = 3,
            ModuleID = 120,
        },
        {
            CustomJumpFunc = '_G.StoreMgr:JumpToGoods(nil,30012,false)',
            ID = 122,
            JumpType = 3,
            ModuleID = 120,
        },
        {
            CustomJumpFunc = CS._2_1,
            ID = 123,
            JumpType = 3,
            ModuleID = 120,
        },
        {
            CustomJumpFunc = '_G.StoreMgr:JumpToGoods(nil,10006,false)',
            ID = 124,
            JumpType = 3,
            ModuleID = 120,
        },
        {
            CustomJumpFunc = '_G.StoreMgr:JumpToGoods(nil,30005,false)',
            ID = 125,
            JumpType = 3,
            ModuleID = 120,
        },
        {
            CustomJumpFunc = '_G.StoreMgr:JumpToGoods(nil,10029,false)',
            ID = 126,
            JumpType = 3,
            ModuleID = 120,
        },
        {
            CustomJumpFunc = '_G.StoreMgr:JumpToGoods(nil,10022,false)',
            ID = 127,
            JumpType = 3,
            ModuleID = 120,
        },
        {
            CustomJumpFunc = '_G.StoreMgr:JumpToGoods(61600006,nil,false,true)',
            ID = 128,
            JumpType = 3,
            ModuleID = 120,
        },
        {
            CustomJumpFunc = '_G.StoreMgr:JumpToGoods(61600012,nil,false,true)',
            ID = 129,
            JumpType = 3,
            ModuleID = 120,
        },
        {
            CustomJumpFunc = '_G.StoreMgr:JumpToGoods(nil,30007,false)',
            ID = 130,
            JumpType = 3,
            ModuleID = 120,
        },
        {
            CustomJumpFunc = '_G.StoreMgr:JumpToGoods(nil,10013,false)',
            ID = 131,
            JumpType = 3,
            ModuleID = 120,
        },
        {
            CustomJumpFunc = '_G.StoreMgr:JumpToGoods(nil,30008,false)',
            ID = 132,
            JumpType = 3,
            ModuleID = 120,
        },
        {
            ID = 133,
            _Params = '["24120601"]',
            ViewID = 6000,
        },
        {
            ID = 134,
            _Params = '["24120901"]',
            ViewID = 6000,
        },
        {
            ID = 135,
            _Params = CS._4_5,
            ViewID = 6000,
        },
        {
            ID = 136,
            _Params = '["24121601"]',
            ViewID = 6000,
        },
        {
            ID = 137,
            _Params = '["25032801"]',
            ViewID = 6000,
        },
        {
            ForbiddenTips = CS._3_5,
            ID = 138,
            ModuleID = 118,
            _Params = CS._4_1,
            ViewID = 1314,
        },
        {
            CustomJumpFunc = '_G.ShopMgr:OpenInletMainView(1)',
            ID = 139,
            JumpType = 3,
        },
        {
            CustomJumpFunc = '_G.QuestMgr:OpenPanelByQuestType(1)',
            ID = 140,
            JumpType = 3,
        },
        {
            CustomJumpFunc = '_G.QuestMgr:OpenPanelByQuestType(2)',
            ID = 141,
            JumpType = 3,
        },
        {
            ID = 142,
            JumpType = 18,
            _Params = '["12002","740"]',
        },
        {
            ID = 143,
            JumpType = 18,
            _Params = '["13001","969"]',
        },
        {
            ID = 144,
            JumpType = 18,
            _Params = '["12001","704"]',
        },
        {
            ID = 145,
            JumpType = 18,
            _Params = '["11002","55"]',
        },
        {
            ID = 146,
            JumpType = 18,
            _Params = '["12001","702"]',
        },
        {
            ID = 147,
            JumpType = 18,
            _Params = '["13002","1008"]',
        },
        {
            ID = 148,
            JumpType = 18,
            _Params = '["11001","19"]',
        },
        {
            ID = 149,
            JumpType = 18,
            _Params = '["11002","59"]',
        },
        {
            ForbiddenTips = '您已解锁学者特职开启任务',
            ID = 150,
            JumpType = 11,
            _Params = '["17227"]',
        },
        {
            ID = 151,
            JumpType = 18,
            _Params = '["13002","1009"]',
        },
        {
            ID = 152,
            JumpType = 18,
            _Params = '["12002","742"]',
        },
        {
            ID = 153,
            JumpType = 18,
            _Params = '["11002","62"]',
        },
        {
            ID = 154,
            JumpType = 18,
            _Params = '["11001","14"]',
        },
        {
            ID = 155,
            JumpType = 18,
            _Params = '["13001","971"]',
        },
        {
            ID = 156,
            JumpType = 18,
            _Params = '["13001","972"]',
        },
        {
            ID = 157,
            JumpType = 18,
            _Params = '["13001","970"]',
        },
        {
            ID = 158,
            JumpType = 18,
            _Params = '["12002","801","73"]',
        },
        {
            ID = 159,
            JumpType = 18,
            _Params = '["12002","745"]',
        },
        {
            ID = 160,
            JumpType = 18,
            _Params = '["11002","53"]',
        },
        {
            ID = 161,
            JumpType = 18,
            _Params = '["12002","741"]',
        },
        {
            ForbiddenTips = '寻宝已解锁',
            ID = 162,
            JumpType = 11,
            _Params = '["17197"]',
        },
        {
            ForbiddenTips = '习得弓箭手并转职为吟游诗人后，完成吟游诗人10级特职任务开放。',
            ID = 163,
            JumpType = 19,
            ModuleID = 134,
        },
        {
            CustomJumpFunc = '_G.StoreMgr:JumpToGoods(nil,10005,false)',
            ID = 164,
            JumpType = 3,
            ModuleID = 120,
        },
        {
            ID = 165,
            ModuleID = 104,
            _Params = '["36"]',
            ViewID = 300201,
        },
        {
            ID = 166,
            ModuleID = 104,
            _Params = '["37"]',
            ViewID = 300201,
        },
        {
            ID = 167,
            ViewID = 2501,
        },
        {
            CustomJumpFunc = '_G.RechargingMgr:ShowMainPanel()',
            ID = 168,
            JumpType = 3,
        },
        {
            ForbiddenTips = CS._3_3,
            ID = 169,
            JumpType = 7,
            ModuleID = 101,
        },
        {
            CustomJumpFunc = '_G.CompanionMgr:OpenCompanionView()',
            ForbiddenTips = '首次获得宠物后开放。',
            ID = 170,
            JumpType = 3,
            ModuleID = 116,
        },
        {
            ID = 171,
            ModuleID = 120,
            ViewID = 201406,
        },
        {
            ForbiddenTips = '完成2.0全部主线任务后，完成支线任务开放。',
            ID = 172,
            ModuleID = 129,
            ViewID = 5300,
        },
        {
            CustomJumpFunc = '_G.AchievementMgr:OpenAchievementEntryPanelView()',
            ID = 173,
            JumpType = 3,
        },
        {
            ID = 174,
            ViewID = 201502,
        },
        {
            ForbiddenTips = CS._3_2,
            ID = 175,
            ModuleID = 109,
            ViewID = 308001,
        },
        {
            ID = 176,
            ViewID = 1151,
        },
        {
            CustomJumpFunc = '_G.FashionDecoMgr:ShowFashionDecoMgrMainPanel()',
            ForbiddenTips = '首次获得时尚配饰后开放。',
            ID = 177,
            JumpType = 3,
            ModuleID = 163,
        },
        {
            ID = 178,
            ViewID = 2800,
        },
        {
            CustomJumpFunc = '_G.ArmyMgr:OpenArmyMainPanel()',
            ForbiddenTips = '角色等级15级后开放。',
            ID = 179,
            JumpType = 3,
            ModuleID = 108,
        },
        {
            CustomJumpFunc = '_G.ShopMgr:OpenInletMainView(4)',
            ID = 180,
            JumpType = 3,
        },
        {
            CustomJumpFunc = '_G.FootPrintMgr:OpenFootPrintMainPanel()',
            ID = 181,
            JumpType = 3,
        },
        {
            ForbiddenTips = '首次获得新手指南后开放。',
            ID = 182,
            ModuleID = 117,
            ViewID = 200509,
        },
        {
            CustomJumpFunc = '_G.PandoraMgr:OpenAnnouncement()',
            ID = 183,
            JumpType = 3,
        },
        {
            ID = 184,
            JumpType = 12,
        },
        {
            CustomJumpFunc = '_G.MailMgr:OpenMailMainView()',
            ID = 185,
            JumpType = 3,
        },
        {
            CustomJumpFunc = '_G.WorldExploraMgr:OpenWorldExploreMain()',
            ForbiddenTips = '完成7级主线任务开放。',
            ID = 186,
            JumpType = 3,
            ModuleID = 169,
        },
        {
            ID = 187,
            JumpType = 20,
            _Params = '["2","2"]',
        },
        {
            ID = 188,
            _Params = '["125043001"]',
            ViewID = 6000,
        },
        {
            ID = 189,
            _Params = '["125043002"]',
            ViewID = 6000,
        },
        {
            ID = 190,
            _Params = '["125043003"]',
            ViewID = 6000,
        },
        {
            ID = 191,
            JumpType = 11,
            _Params = '["17074"]',
        },
        {
            ID = 192,
            ModuleID = 158,
            _Params = '["4","37"]',
            ViewID = 3301,
        },
        {
            ID = 193,
            ModuleID = 158,
            _Params = '["4","38"]',
            ViewID = 3301,
        },
        {
            ForbiddenTips = '请前往<推荐任务>接取50级大型任务<蛮神苏醒>开启！',
            ID = 194,
            JumpType = 2,
            _Params = '["4","1205015"]',
        },
        {
            ForbiddenTips = '请前往<推荐任务>接取50级大型任务<英雄叙事诗：大迷宫之章>开启！',
            ID = 195,
            JumpType = 2,
            _Params = '["4","1205011"]',
        },
        {
            ForbiddenTips = '请前往<推荐任务>接取50级讨伐歼灭战任务<英雄叙事诗：幻想之章>开启！',
            ID = 196,
            JumpType = 2,
            _Params = CS._4_7,
        },
        {
            ForbiddenTips = '请前往<推荐任务>接取50级讨伐歼灭战任务<登峰造极的水神利维亚桑>开启！',
            ID = 197,
            JumpType = 2,
            _Params = CS._4_8,
        },
        {
            ForbiddenTips = '请前往<推荐任务>接取50级大型任务<希尔科斯塔>开启！',
            ID = 198,
            JumpType = 2,
            _Params = '["4","1206004"]',
        },
        {
            ForbiddenTips = '完成25级支线任务开放。',
            ID = 199,
            ModuleID = 109,
            _Params = CS._4_2,
            ViewID = 1314,
        },
        {
            ID = 200,
            _Params = CS._4_9,
            ViewID = 6000,
        },
        {
            ID = 201,
            _Params = CS._4_10,
            ViewID = 6000,
        },
        {
            ID = 202,
            _Params = CS._4_11,
            ViewID = 6000,
        },
        {
            ID = 203,
            _Params = '["125043007"]',
            ViewID = 6000,
        },
        {
            ID = 204,
            _Params = '["125043008"]',
            ViewID = 6000,
        },
        {
            ID = 205,
            _Params = '["125043009"]',
            ViewID = 6000,
        },
        {
            ForbiddenTips = '暂未解锁前置任务或已经完成过该任务。',
            ID = 206,
            JumpType = 11,
            _Params = '["24002"]',
        },
        {
            ForbiddenTips = CS._3_1,
            ID = 207,
            JumpType = 8,
            _Params = '["12060","62"]',
        },
        {
            ID = 208,
            _Params = CS._4_10,
            ViewID = 6000,
        },
        {
            ID = 209,
            _Params = CS._4_11,
            ViewID = 6000,
        },
        {
            ID = 210,
            _Params = CS._4_9,
            ViewID = 6000,
        },
        {
            ID = 211,
            _Params = '["25043008"]',
            ViewID = 6000,
        },
        {
            CustomJumpFunc = '_G.StoreMgr:JumpToGoods(nil,10040,false)',
            ID = 214,
            JumpType = 3,
            ModuleID = 120,
        },
        {
            CustomJumpFunc = '_G.StoreMgr:JumpToGoods(nil,30017,false)',
            ID = 215,
            JumpType = 3,
            ModuleID = 120,
        },
        {
            CustomJumpFunc = '_G.StoreMgr:JumpToGoods(nil,30018,false)',
            ID = 216,
            JumpType = 3,
            ModuleID = 120,
        },
        {
            CustomJumpFunc = '_G.OpsSeasonActivityMgr:ShowSeasonActivityUI()',
            ID = 219,
            JumpType = 3,
        },
        {
            CheckOpenFunc = '_G.ShopMgr:ShopIsUnLock(3010)',
            CustomJumpFunc = '_G.ShopMgr:JumpToShopGoods(3010,60900138)',
            ID = 229,
            JumpType = 3,
        },
        {
            ID = 234,
            _Params = '["125062410"]',
            ViewID = 6000,
        },
        {
            ID = 235,
            _Params = '["125062411"]',
            ViewID = 6000,
        },
        {
            ID = 236,
            _Params = '["125062412"]',
            ViewID = 6000,
        },
        {
            ID = 237,
            _Params = '["125062413"]',
            ViewID = 6000,
        },
        {
            ID = 238,
            _Params = '["125062414"]',
            ViewID = 6000,
        },
        {
            ID = 239,
            _Params = '["125062415"]',
            ViewID = 6000,
        },
        {
            ID = 240,
            _Params = '["125062416"]',
            ViewID = 6000,
        },
        {
            ID = 241,
            _Params = '["125062417"]',
            ViewID = 6000,
        },
        {
            ID = 242,
            _Params = '["125062418"]',
            ViewID = 6000,
        },
        {
            ID = 243,
            _Params = '["125062419"]',
            ViewID = 6000,
        },
        {
            ID = 244,
            _Params = '["125062420"]',
            ViewID = 6000,
        },
        {
            ID = 245,
            _Params = '["125062421"]',
            ViewID = 6000,
        },
        {
            ID = 246,
            _Params = '["125062422"]',
            ViewID = 6000,
        },
        {
            ID = 247,
            _Params = '["125062423"]',
            ViewID = 6000,
        },
        {
            ID = 248,
            _Params = '["125062424"]',
            ViewID = 6000,
        },
        {
            ID = 249,
            _Params = '["125062425"]',
            ViewID = 6000,
        },
        {
            ID = 250,
            _Params = '["125062426"]',
            ViewID = 6000,
        },
        {
            ID = 251,
            _Params = '["125062427"]',
            ViewID = 6000,
        },
        {
            ID = 252,
            _Params = '["125062428"]',
            ViewID = 6000,
        },
        {
            ID = 253,
            _Params = '["125062429"]',
            ViewID = 6000,
        },
        {
            CustomJumpFunc = '_G.StoreMgr:JumpToGoods(nil,10045,false)',
            ID = 254,
            JumpType = 3,
            ModuleID = 120,
        },
        {
            ForbiddenTips = CS._3_4,
            ID = 262,
            JumpType = 2,
            _Params = '["3","1203016"]',
        },
        {
            ForbiddenTips = CS._3_4,
            ID = 263,
            JumpType = 2,
            _Params = CS._4_7,
        },
        {
            CustomJumpFunc = '_G.StoreMgr:JumpToGoods(nil,10048,false)',
            ID = 264,
            JumpType = 3,
        },
        {
            CustomJumpFunc = '_G.StoreMgr:JumpToGoods(nil,10051,false)',
            ID = 265,
            JumpType = 3,
        },
        {
            CustomJumpFunc = '_G.StoreMgr:JumpToGoods(nil,10050,false)',
            ID = 266,
            JumpType = 3,
        },
        {
            ForbiddenTips = CS._3_4,
            ID = 308,
            JumpType = 2,
            _Params = CS._4_8,
        },
	},
}

setmetatable(JumpCfg, { __index = CfgBase })

JumpCfg:InitCfg()

-- AUTO GENERATED CODE END, PLEASE DON'T MODIFY

return JumpCfg
