-- AUTO GENERATED CODE BEGIN, PLEASE DON'T MODIFY

local CfgBase = require("TableCfg/CfgBase")

local CS = {
    _1_1 = 'Texture2D\'/Game/UI/Texture/PWorld/BG/Details/UI_PWorld_BG_Details_BHMTDMGRQZZ4.UI_PWorld_BG_Details_BHMTDMGRQZZ4\'',
    _1_2 = 'Texture2D\'/Game/UI/Texture/PWorld/BG/Match/UI_PWorld_BG_Match_HKDJS.UI_PWorld_BG_Match_HKDJS\'',
    _1_3 = 'Texture2D\'/Game/UI/Texture/PWorld/BG/Details/UI_PWorld_BG_Details_TT.UI_PWorld_BG_Details_TT\'',
    _1_4 = 'Texture2D\'/Game/UI/Texture/PWorld/BG/Details/UI_PWorld_BG_Details_LMJMZ.UI_PWorld_BG_Details_LMJMZ\'',
    _1_5 = 'Texture2D\'/Game/UI/Texture/PWorld/BG/Details/UI_PWorld_BG_Details_LWYSJMZ.UI_PWorld_BG_Details_LWYSJMZ\'',
    _1_6 = 'Texture2D\'/Game/UI/Texture/PWorld/BG/Details/UI_PWorld_BG_Details_BHMTDMGRQZZ1.UI_PWorld_BG_Details_BHMTDMGRQZZ1\'',
    _1_7 = 'Texture2D\'/Game/UI/Texture/PWorld/BG/Details/UI_PWorld_BG_Details_BHMTDMGXHZZ1.UI_PWorld_BG_Details_BHMTDMGXHZZ1\'',
    _1_8 = 'Texture2D\'/Game/UI/Texture/PWorld/BG/Details/UI_PWorld_BG_Details_BHMTDMGXHZZ5.UI_PWorld_BG_Details_BHMTDMGXHZZ5\'',
    _1_9 = 'Texture2D\'/Game/UI/Texture/Ops/OpsHalloween/UI_Pworld_BG_Halloween.UI_Pworld_BG_Halloween\'',
    _2_1 = 'Texture2D\'/Game/UI/Texture/PWorld/Banner/UI_PWorld_Banner_PWorldList_25.UI_PWorld_Banner_PWorldList_25\'',
    _2_2 = 'Texture2D\'/Game/UI/Texture/PWorld/Banner/UI_PWorld_Banner_PWorldList_38.UI_PWorld_Banner_PWorldList_38\'',
    _2_3 = 'Texture2D\'/Game/UI/Texture/PWorld/Banner/UI_PWorld_Banner_PWorldList_43.UI_PWorld_Banner_PWorldList_43\'',
    _2_4 = 'Texture2D\'/Game/UI/Texture/PWorld/BG/Match/UI_PWorld_BG_Match_HKDJS.UI_PWorld_BG_Match_HKDJS\'',
    _2_5 = 'Texture2D\'/Game/UI/Texture/PWorld/Banner/UI_PWorld_Banner_PWorldList_30.UI_PWorld_Banner_PWorldList_30\'',
    _2_6 = 'Texture2D\'/Game/UI/Texture/PWorld/Banner/UI_PWorld_Banner_PWorldList_28.UI_PWorld_Banner_PWorldList_28\'',
    _2_7 = 'Texture2D\'/Game/UI/Texture/PWorld/Banner/UI_PWorld_Banner_PWorldList_27.UI_PWorld_Banner_PWorldList_27\'',
    _2_8 = 'Texture2D\'/Game/UI/Texture/PWorld/Banner/UI_PWorld_Banner_PWorldList_26.UI_PWorld_Banner_PWorldList_26\'',
    _2_9 = 'Texture2D\'/Game/UI/Texture/PWorld/Banner/UI_PWorld_Banner_PWorldList_36.UI_PWorld_Banner_PWorldList_36\'',
    _2_10 = 'Texture2D\'/Game/UI/Texture/PWorld/Banner/UI_PWorld_Banner_PWorldList_05.UI_PWorld_Banner_PWorldList_05\'',
    _2_11 = 'Texture2D\'/Game/UI/Texture/PWorld/Banner/UI_PWorld_Banner_PWorldList_SSTXRD.UI_PWorld_Banner_PWorldList_SSTXRD\'',
    _3_1 = '信息\
限制时间：3分钟/无法补充队员/不可与其他任务同时搜索\
\
人数要求：1人（不限制职业）',
    _3_2 = '信息\
限制时间：120分钟/古代人迷宫\
\
人数要求：1~4人战斗职业（防护职业：1/治疗职业：1/进攻职业：2）\
参与等级：50级，超过等级上限时会自动进行等级同步\
装备品级：平均品级不低于1级，且品级同步115级\
\
※在品级同步状态下，所有的装备性能都会下调至对应品级的规格。\
※8人数组队时可以以任何职业构成参加，且不会受到装备品级限制。',
    _3_3 = '信息\
限制时间 60分钟/后营门/重新挑战时发动“超越之力”状态',
    _3_4 = '信息\
限制时间：60分钟/奥·哥摩罗火口神殿/重新挑战时发动“超越之力”状态\
\
参加条件\
人数要求：1~4人战斗职业（防护职业：1/治疗职业：1/进攻职业：2）\
参与等级：35级，超过等级上限时会自动进行等级同步\
装备品级：平均品级不低于1级，且品级同步80级\
\
※在品级同步状态下，所有的装备性能都会下调至对应品级的规格。\
※8人数组队时可以以任何职业构成参加，且不会受到装备品级限制。',
    _3_5 = '信息\
限制时间：120分钟/天幕魔导城\
\
参加条件\
人数要求：1~4人战斗职业（防护职业：1/治疗职业：1/进攻职业：2）\
参与等级：50级，超过等级上限时会自动进行等级同步\
装备品级：平均品级不低于1级，且品级同步130级\
\
※在品级同步状态下，所有的装备性能都会下调至对应品级的规格。\
※4人数组队时可以以任何职业构成参加，且不会受到装备品级限制。',
    _3_6 = '信息\
限制时间：90分钟/沙斯塔夏溶洞\
\
参加条件\
人数要求：1~4人战斗职业（防护职业：1/治疗职业：1/进攻职业：2）\
参与等级：10级，超过等级上限时会自动进行等级同步\
装备品级：平均品级不低于1级，且品级同步20级\
\
※在品级同步状态下，所有的装备性能都会下调至对应品级的规格。\
※4人数组队时可以以任何职业构成参加，且不会受到装备品级限制。',
    _3_7 = '信息\
限制时间：10分钟/无法补充队员/不可与其他任务同时搜索\
\
人数要求：1~8人（不限制职业）\
参与等级：1级\
\
※无法解除限制/更改分配方式/同步到最低品级\
※不支持自由探索',
    _4_1 = '[50]',
    _4_2 = '[80]',
    _4_3 = '[100]',
    _5_1 = '[19000101]',
    _5_2 = '[19000100]',
    _6_1 = '[30,1]',
    _6_2 = '[50,10]',
    _6_3 = '[20,1]',
    _6_4 = '[50,10,4]',
    _6_5 = '[50,10,1]',
    _6_6 = '[80,35]',
    _6_7 = '[1,1]',
    _6_8 = '[1]',
    _6_9 = '[1,1,1,1]',
    _7_1 = '[19000101,19000102]',
    _7_2 = '[19000100,66700181]',
    _7_3 = '[19000004,19000502]',
    _7_4 = '[19000100,66700182]',
    _7_5 = '[66700181]',
    _7_6 = '[19000099,19000098,19000100,19000002]',
    _9_1 = '[2]',
}

---@class SceneEnterCfg : CfgBase
local SceneEnterCfg = {
	TableName = "c_scene_enter_cfg",
    LruKeyType = nil,
	KeyName = "ID",
    bEncrypted = false,
	Localization = {
        Config = {
            {
                Name = 'Summary',
            },
		}
    },
    DefaultValues = {
        ArmSyncLevel = 0,
        AttackProfNum = 0,
        BG = 'Texture2D\'/Game/UI/Texture/PWorld/BG/Details/UI_PWorld_BG_Details_MRSJMRJMZ.UI_PWorld_BG_Details_MRSJMRJMZ\'',
        BackgroudImageIcon = 'Texture2D\'/Game/UI/Texture/PWorld/Banner/UI_PWorld_Banner_PWorldList_10.UI_PWorld_Banner_PWorldList_10\'',
        CanMidWay = 1,
        Counter = 0,
        Explain = '',
        GuardProfNum = 0,
        HasChallenge = 1,
        HasExplore = 0,
        HasNormal = 1,
        HasUnlimited = 0,
        HelpInfoID = 1000004,
        ID = 1116012,
        _InitialRewardCnt = '[]',
        _InitialRewards = '[]',
        IsHideInList = 0,
        MatchTimeoutGuideRecruitID = 0,
        MatchTimeoutGuideTime = 0,
        MatchTimeoutGuideType = 0,
        NurseProfNum = 0,
        PVPAdvanceProfNum = 0,
        PlayerSyncLevel = 0,
        PreQuestID = 0,
        PrepassEntID = 0,
        Priority = 49,
        PunishmentTime = 0,
        RecruitID = 0,
        _RewardCnt = '[]',
        _RewardPropIndex = '[]',
        _Rewards = '[]',
        SPID = 0,
        TypeID = 2,
        _WeeklyItem = '[]',
        _WeeklyItemCnt = '[]',
        ZeroFormPriority = 0,
        ZeroFormWeeklyCounter = 0,
    },
	LuaData = {
        {
            BG = CS._1_2,
            BackgroudImageIcon = CS._2_4,
            CanMidWay = 0,
            Explain = '信息\
人数要求：1~8人（不限制职业）',
            HasChallenge = 0,
            HelpInfoID = 0,
            PreQuestID = 171101,
            SPID = 500101,
            TypeID = 6,
        },
        {
            AttackProfNum = 4,
            BG = CS._1_3,
            BackgroudImageIcon = CS._2_5,
            Counter = 21300,
            Explain = CS._3_4,
            GuardProfNum = 2,
            HasUnlimited = 1,
            ID = 1202015,
            _InitialRewardCnt = CS._4_2,
            _InitialRewards = CS._5_2,
            MatchTimeoutGuideRecruitID = 20,
            MatchTimeoutGuideTime = 180,
            MatchTimeoutGuideType = 2,
            NurseProfNum = 2,
            PreQuestID = 160407,
            Priority = 16,
            RecruitID = 5,
            _RewardCnt = CS._6_3,
            _Rewards = '[19000100,60900163]',
            TypeID = 3,
        },
        {
            AttackProfNum = 4,
            BG = 'Texture2D\'/Game/UI/Texture/PWorld/BG/Details/UI_PWorld_BG_Details_JLL.UI_PWorld_BG_Details_JLL\'',
            BackgroudImageIcon = 'Texture2D\'/Game/UI/Texture/PWorld/Banner/UI_PWorld_Banner_PWorldList_35.UI_PWorld_Banner_PWorldList_35\'',
            Counter = 21400,
            Explain = '信息\
限制时间：60分钟/呼啸眼石塔群/重新挑战时发动“超越之力”状态\
\
参加条件\
人数要求：1~4人战斗职业（防护职业：1/治疗职业：1/进攻职业：2）\
参与等级：45级，超过等级上限时会自动进行等级同步\
装备品级：平均品级不低于1级，且品级同步105级\
\
※在品级同步状态下，所有的装备性能都会下调至对应品级的规格。\
※8人数组队时可以以任何职业构成参加，且不会受到装备品级限制。',
            GuardProfNum = 2,
            HasUnlimited = 1,
            ID = 1202020,
            _InitialRewardCnt = CS._4_2,
            _InitialRewards = CS._5_2,
            MatchTimeoutGuideRecruitID = 21,
            MatchTimeoutGuideTime = 180,
            MatchTimeoutGuideType = 2,
            NurseProfNum = 2,
            PreQuestID = 140525,
            Priority = 17,
            RecruitID = 5,
            _RewardCnt = CS._6_3,
            _Rewards = '[19000100,60900164]',
            TypeID = 3,
        },
        {
            AttackProfNum = 4,
            BG = 'Texture2D\'/Game/UI/Texture/PWorld/BG/Details/UI_PWorld_BG_Details_YFLTTFZ.UI_PWorld_BG_Details_YFLTTFZ\'',
            BackgroudImageIcon = 'Texture2D\'/Game/UI/Texture/PWorld/Banner/UI_PWorld_Banner_PWorldList_34.UI_PWorld_Banner_PWorldList_34\'',
            Counter = 21200,
            Explain = '信息\
限制时间：60分钟/炎帝陵/重新挑战时发动"超越之力"状态\
\
参加条件\
人数要求：1~4人战斗职业（防护职业：1/治疗职业：1/进攻职业：2）\
参与等级：15级，超过等级上限时会自动进行等级同步\
装备品级：平均品级不低于1级，且品级同步30级\
\
※在品级同步状态下，所有的装备性能都会下调至对应品级的规格。\
※8人数组队时可以以任何职业构成参加，且不会受到装备品级限制。',
            GuardProfNum = 2,
            HasUnlimited = 1,
            ID = 1202021,
            _InitialRewardCnt = CS._4_2,
            _InitialRewards = CS._5_2,
            MatchTimeoutGuideRecruitID = 19,
            MatchTimeoutGuideTime = 180,
            MatchTimeoutGuideType = 2,
            NurseProfNum = 2,
            PreQuestID = 140374,
            Priority = 15,
            RecruitID = 5,
            _RewardCnt = CS._6_3,
            _Rewards = '[19000100,60900162]',
            TypeID = 3,
        },
        {
            AttackProfNum = 4,
            BG = 'Texture2D\'/Game/UI/Texture/PWorld/BG/Details/UI_PWorld_BG_Details_JJSBJXZZ.UI_PWorld_BG_Details_JJSBJXZZ\'',
            BackgroudImageIcon = 'Texture2D\'/Game/UI/Texture/PWorld/Banner/UI_PWorld_Banner_PWorldList_03.UI_PWorld_Banner_PWorldList_03\'',
            Explain = CS._3_3,
            GuardProfNum = 2,
            ID = 1202022,
            _InitialRewardCnt = CS._4_2,
            _InitialRewards = CS._5_1,
            MatchTimeoutGuideRecruitID = 27,
            MatchTimeoutGuideTime = 180,
            MatchTimeoutGuideType = 2,
            NurseProfNum = 2,
            PreQuestID = 210126,
            Priority = 23,
            RecruitID = 5,
            _RewardCnt = CS._6_4,
            _Rewards = '[19000101,19000102,66700192]',
            TypeID = 3,
        },
        {
            AttackProfNum = 4,
            BG = CS._1_4,
            BackgroudImageIcon = CS._2_6,
            Explain = CS._3_3,
            GuardProfNum = 2,
            ID = 1202023,
            _InitialRewardCnt = CS._4_2,
            _InitialRewards = CS._5_1,
            MatchTimeoutGuideRecruitID = 25,
            MatchTimeoutGuideTime = 180,
            MatchTimeoutGuideType = 2,
            NurseProfNum = 2,
            PreQuestID = 171183,
            Priority = 21,
            RecruitID = 5,
            _RewardCnt = CS._6_5,
            _Rewards = '[19000101,19000102,60900167]',
            TypeID = 3,
        },
        {
            AttackProfNum = 4,
            BG = 'Texture2D\'/Game/UI/Texture/PWorld/BG/Details/UI_PWorld_BG_Details_MGLXWJMZ.UI_PWorld_BG_Details_MGLXWJMZ\'',
            BackgroudImageIcon = 'Texture2D\'/Game/UI/Texture/PWorld/Banner/UI_PWorld_Banner_PWorldList_07.UI_PWorld_Banner_PWorldList_07\'',
            Explain = CS._3_3,
            GuardProfNum = 2,
            ID = 1202024,
            _InitialRewardCnt = CS._4_2,
            _InitialRewards = CS._5_1,
            MatchTimeoutGuideRecruitID = 23,
            MatchTimeoutGuideTime = 180,
            MatchTimeoutGuideType = 2,
            NurseProfNum = 2,
            PreQuestID = 160012,
            Priority = 19,
            RecruitID = 5,
            _RewardCnt = CS._6_5,
            _Rewards = '[19000101,19000102,60900165]',
            TypeID = 3,
        },
        {
            AttackProfNum = 4,
            BG = CS._1_5,
            BackgroudImageIcon = CS._2_7,
            Explain = CS._3_3,
            GuardProfNum = 2,
            ID = 1202025,
            _InitialRewardCnt = CS._4_2,
            _InitialRewards = CS._5_1,
            MatchTimeoutGuideRecruitID = 24,
            MatchTimeoutGuideTime = 180,
            MatchTimeoutGuideType = 2,
            NurseProfNum = 2,
            PreQuestID = 200250,
            Priority = 20,
            RecruitID = 5,
            _RewardCnt = CS._6_5,
            _Rewards = '[19000101,19000102,60900166]',
            TypeID = 3,
        },
        {
            AttackProfNum = 4,
            BG = CS._1_3,
            BackgroudImageIcon = CS._2_5,
            Counter = 21600,
            Explain = '信息\
限制时间：60分钟/奥·哥摩罗火口神殿/重新挑战时发动“超越之力”状态\
\
人数要求：1~4人战斗职业（防护职业：1/治疗职业：1/进攻职业：2）\
参与等级：50级，超过等级上限时会自动进行等级同步\
装备品级：平均品级不低于1级，且品级同步125级\
\
※在品级同步状态下，所有的装备性能都会下调至对应品级的规格。\
※8人数组队时可以以任何职业构成参加，且不会受到装备品级限制。',
            GuardProfNum = 2,
            ID = 1203016,
            _InitialRewardCnt = CS._4_2,
            _InitialRewards = CS._5_1,
            MatchTimeoutGuideRecruitID = 26,
            MatchTimeoutGuideTime = 180,
            MatchTimeoutGuideType = 2,
            NurseProfNum = 2,
            PreQuestID = 220005,
            Priority = 22,
            RecruitID = 5,
            _RewardCnt = CS._6_4,
            _Rewards = '[19000101,19000102,66700190]',
            TypeID = 3,
        },
        {
            AttackProfNum = 4,
            BG = CS._1_4,
            BackgroudImageIcon = CS._2_6,
            Explain = CS._3_3,
            GuardProfNum = 2,
            ID = 1203024,
            _InitialRewardCnt = CS._4_2,
            _InitialRewards = CS._5_1,
            MatchTimeoutGuideRecruitID = 29,
            MatchTimeoutGuideTime = 180,
            MatchTimeoutGuideType = 2,
            NurseProfNum = 2,
            PreQuestID = 160039,
            Priority = 25,
            RecruitID = 5,
            _RewardCnt = CS._6_2,
            _Rewards = CS._7_1,
            TypeID = 3,
        },
        {
            AttackProfNum = 4,
            BG = CS._1_5,
            BackgroudImageIcon = CS._2_7,
            Explain = CS._3_3,
            GuardProfNum = 2,
            ID = 1203277,
            _InitialRewardCnt = CS._4_2,
            _InitialRewards = CS._5_1,
            MatchTimeoutGuideRecruitID = 28,
            MatchTimeoutGuideTime = 180,
            MatchTimeoutGuideType = 2,
            NurseProfNum = 2,
            PreQuestID = 160038,
            Priority = 24,
            RecruitID = 5,
            _RewardCnt = CS._6_4,
            _Rewards = '[19000101,19000102,66700193]',
            TypeID = 3,
        },
        {
            AttackProfNum = 4,
            BG = CS._1_6,
            BackgroudImageIcon = CS._2_8,
            Counter = 21700,
            Explain = CS._3_2,
            GuardProfNum = 2,
            HelpInfoID = 1000006,
            ID = 1205010,
            _InitialRewardCnt = CS._4_3,
            _InitialRewards = CS._5_1,
            MatchTimeoutGuideRecruitID = 38,
            MatchTimeoutGuideTime = 180,
            MatchTimeoutGuideType = 2,
            NurseProfNum = 2,
            PreQuestID = 210128,
            PrepassEntID = 1206002,
            Priority = 34,
            RecruitID = 14,
            _RewardCnt = CS._6_2,
            _Rewards = CS._7_1,
            TypeID = 4,
            _WeeklyItem = '[66700201]',
            _WeeklyItemCnt = CS._9_1,
            ZeroFormPriority = 3,
            ZeroFormWeeklyCounter = 1300,
        },
        {
            AttackProfNum = 4,
            BG = CS._1_7,
            BackgroudImageIcon = CS._2_9,
            Counter = 22000,
            Explain = CS._3_4,
            GuardProfNum = 2,
            HelpInfoID = 1000006,
            ID = 1205011,
            _InitialRewardCnt = CS._4_3,
            _InitialRewards = CS._5_1,
            MatchTimeoutGuideRecruitID = 36,
            MatchTimeoutGuideTime = 180,
            MatchTimeoutGuideType = 2,
            NurseProfNum = 2,
            PreQuestID = 210127,
            Priority = 32,
            RecruitID = 12,
            _RewardCnt = CS._6_2,
            _Rewards = CS._7_1,
            TypeID = 4,
            _WeeklyItem = '[66700199]',
            _WeeklyItemCnt = CS._9_1,
            ZeroFormPriority = 1,
            ZeroFormWeeklyCounter = 1100,
        },
        {
            AttackProfNum = 4,
            BG = CS._1_6,
            BackgroudImageIcon = CS._2_8,
            Counter = 21700,
            Explain = CS._3_2,
            GuardProfNum = 2,
            ID = 1205012,
            _InitialRewardCnt = CS._4_3,
            _InitialRewards = CS._5_1,
            MatchTimeoutGuideRecruitID = 34,
            MatchTimeoutGuideTime = 180,
            MatchTimeoutGuideType = 2,
            NurseProfNum = 2,
            PreQuestID = 210136,
            Priority = 30,
            RecruitID = 10,
            _RewardCnt = CS._6_2,
            _Rewards = CS._7_1,
            TypeID = 4,
        },
        {
            AttackProfNum = 4,
            BG = CS._1_1,
            BackgroudImageIcon = CS._2_1,
            Counter = 21700,
            Explain = CS._3_2,
            GuardProfNum = 2,
            HelpInfoID = 1000006,
            ID = 1205013,
            _InitialRewardCnt = CS._4_3,
            _InitialRewards = CS._5_1,
            MatchTimeoutGuideRecruitID = 39,
            MatchTimeoutGuideTime = 180,
            MatchTimeoutGuideType = 2,
            NurseProfNum = 2,
            PreQuestID = 210128,
            PrepassEntID = 1205010,
            Priority = 35,
            RecruitID = 15,
            _RewardCnt = CS._6_2,
            _Rewards = CS._7_1,
            TypeID = 4,
            _WeeklyItem = '[66700202]',
            _WeeklyItemCnt = CS._9_1,
            ZeroFormPriority = 4,
            ZeroFormWeeklyCounter = 1400,
        },
        {
            AttackProfNum = 4,
            BG = CS._1_1,
            BackgroudImageIcon = CS._2_1,
            Counter = 21700,
            Explain = CS._3_2,
            GuardProfNum = 2,
            ID = 1205014,
            _InitialRewardCnt = CS._4_3,
            _InitialRewards = CS._5_1,
            MatchTimeoutGuideRecruitID = 35,
            MatchTimeoutGuideTime = 180,
            MatchTimeoutGuideType = 2,
            NurseProfNum = 2,
            PreQuestID = 210137,
            Priority = 31,
            RecruitID = 11,
            _RewardCnt = CS._6_2,
            _Rewards = CS._7_1,
            TypeID = 4,
            _WeeklyItem = '[66700191]',
            _WeeklyItemCnt = '[1]',
            ZeroFormWeeklyCounter = 1500,
        },
        {
            AttackProfNum = 4,
            BG = CS._1_7,
            BackgroudImageIcon = CS._2_9,
            Counter = 22000,
            Explain = CS._3_4,
            GuardProfNum = 2,
            ID = 1205015,
            _InitialRewardCnt = CS._4_3,
            _InitialRewards = CS._5_1,
            MatchTimeoutGuideRecruitID = 32,
            MatchTimeoutGuideTime = 180,
            MatchTimeoutGuideType = 2,
            NurseProfNum = 2,
            PreQuestID = 210130,
            Priority = 28,
            RecruitID = 8,
            _RewardCnt = CS._6_2,
            _Rewards = CS._7_1,
            TypeID = 4,
        },
        {
            AttackProfNum = 4,
            BG = CS._1_1,
            BackgroudImageIcon = CS._2_1,
            Explain = CS._3_2,
            GuardProfNum = 2,
            HasChallenge = 0,
            HelpInfoID = 1000007,
            ID = 1205024,
            MatchTimeoutGuideRecruitID = 612,
            MatchTimeoutGuideTime = 180,
            MatchTimeoutGuideType = 2,
            NurseProfNum = 2,
            PreQuestID = 270067,
            PrepassEntID = 1205013,
            Priority = 36,
            RecruitID = 612,
            _RewardCnt = '[200]',
            _Rewards = '[19000101]',
            TypeID = 4,
        },
        {
            AttackProfNum = 4,
            BG = 'Texture2D\'/Game/UI/Texture/PWorld/BG/Details/UI_PWorld_BG_Details_SJTGDRMG.UI_PWorld_BG_Details_SJTGDRMG\'',
            BackgroudImageIcon = 'Texture2D\'/Game/UI/Texture/PWorld/Banner/UI_PWorld_Banner_PWorldList_20.UI_PWorld_Banner_PWorldList_20\'',
            Counter = 21700,
            Explain = CS._3_2,
            GuardProfNum = 2,
            ID = 1206001,
            _InitialRewardCnt = CS._4_1,
            _InitialRewards = CS._5_1,
            MatchTimeoutGuideRecruitID = 30,
            MatchTimeoutGuideTime = 180,
            MatchTimeoutGuideType = 2,
            NurseProfNum = 2,
            PreQuestID = 150938,
            Priority = 26,
            RecruitID = 6,
            _RewardCnt = '[70,70,25]',
            _Rewards = '[19000100,19000101,19000102]',
            TypeID = 4,
        },
        {
            AttackProfNum = 4,
            BG = CS._1_8,
            BackgroudImageIcon = CS._2_10,
            Counter = 22000,
            Explain = CS._3_4,
            GuardProfNum = 2,
            HelpInfoID = 1000006,
            ID = 1206002,
            _InitialRewardCnt = CS._4_3,
            _InitialRewards = CS._5_1,
            MatchTimeoutGuideRecruitID = 37,
            MatchTimeoutGuideTime = 180,
            MatchTimeoutGuideType = 2,
            NurseProfNum = 2,
            PreQuestID = 210127,
            PrepassEntID = 1205011,
            Priority = 33,
            RecruitID = 13,
            _RewardCnt = CS._6_2,
            _Rewards = CS._7_1,
            TypeID = 4,
            _WeeklyItem = '[66700200]',
            _WeeklyItemCnt = CS._9_1,
            ZeroFormPriority = 2,
            ZeroFormWeeklyCounter = 1200,
        },
        {
            AttackProfNum = 4,
            BG = CS._1_8,
            BackgroudImageIcon = CS._2_10,
            Counter = 22000,
            Explain = CS._3_4,
            GuardProfNum = 2,
            ID = 1206003,
            _InitialRewardCnt = CS._4_3,
            _InitialRewards = CS._5_1,
            MatchTimeoutGuideRecruitID = 33,
            MatchTimeoutGuideTime = 180,
            MatchTimeoutGuideType = 2,
            NurseProfNum = 2,
            PreQuestID = 210132,
            Priority = 29,
            RecruitID = 9,
            _RewardCnt = CS._6_2,
            _Rewards = CS._7_1,
            TypeID = 4,
        },
        {
            AttackProfNum = 4,
            BG = 'Texture2D\'/Game/UI/Texture/PWorld/BG/Details/UI_PWorld_BG_Details_SJTXEKST.UI_PWorld_BG_Details_SJTXEKST\'',
            BackgroudImageIcon = 'Texture2D\'/Game/UI/Texture/PWorld/Banner/UI_PWorld_Banner_PWorldList_19.UI_PWorld_Banner_PWorldList_19\'',
            Counter = 21700,
            Explain = CS._3_2,
            GuardProfNum = 2,
            ID = 1206004,
            _InitialRewardCnt = CS._4_1,
            _InitialRewards = CS._5_1,
            MatchTimeoutGuideRecruitID = 31,
            MatchTimeoutGuideTime = 180,
            MatchTimeoutGuideType = 2,
            NurseProfNum = 2,
            PreQuestID = 150947,
            Priority = 27,
            RecruitID = 6,
            _RewardCnt = '[70,70,25,4]',
            _Rewards = '[19000100,19000101,19000102,66700194]',
            TypeID = 4,
        },
        {
            AttackProfNum = 2,
            BG = 'Texture2D\'/Game/UI/Texture/PWorld/BG/Details/UI_PWorld_BG_Details_XYSD.UI_PWorld_BG_Details_XYSD\'',
            BackgroudImageIcon = 'Texture2D\'/Game/UI/Texture/PWorld/Banner/UI_PWorld_Banner_PWorldList_16.UI_PWorld_Banner_PWorldList_16\'',
            Counter = 20800,
            Explain = '信息\
限制时间：90分钟/布雷福洛克斯野营地\
\
参加条件\
人数要求：1~4人战斗职业（防护职业：1/治疗职业：1/进攻职业：2）\
参与等级：30级，超过等级上限时会自动进行等级同步\
装备品级：平均品级不低于1级，且品级同步70级\
\
※在品级同步状态下，所有的装备性能都会下调至对应品级的规格。\
※4人数组队时可以以任何职业构成参加，且不会受到装备品级限制。',
            GuardProfNum = 1,
            HasUnlimited = 1,
            HelpInfoID = 1000003,
            ID = 1211002,
            _InitialRewardCnt = CS._4_1,
            _InitialRewards = CS._5_2,
            MatchTimeoutGuideTime = 120,
            MatchTimeoutGuideType = 1,
            NurseProfNum = 1,
            PreQuestID = 160370,
            Priority = 9,
            RecruitID = 3,
            _RewardCnt = CS._6_1,
            _Rewards = '[19000100,66700183]',
        },
        {
            AttackProfNum = 2,
            BG = 'Texture2D\'/Game/UI/Texture/PWorld/BG/Details/UI_PWorld_BG_Details_DLC.UI_PWorld_BG_Details_DLC\'',
            BackgroudImageIcon = 'Texture2D\'/Game/UI/Texture/PWorld/Banner/UI_PWorld_Banner_PWorldList_31.UI_PWorld_Banner_PWorldList_31\'',
            Counter = 20900,
            Explain = '信息\
限制时间：90分钟/石卫塔\
\
参加条件\
人数要求：1~4人战斗职业（防护职业：1/治疗职业：1/进攻职业：2）\
参与等级：40级，超过等级上限时会自动进行等级同步\
装备品级：平均品级不低于1级，且品级同步95级\
\
※在品级同步状态下，所有的装备性能都会下调至对应品级的规格。\
※4人数组队时可以以任何职业构成参加，且不会受到装备品级限制。',
            GuardProfNum = 1,
            HasUnlimited = 1,
            HelpInfoID = 1000003,
            ID = 1211003,
            _InitialRewardCnt = CS._4_1,
            _InitialRewards = CS._5_2,
            MatchTimeoutGuideTime = 120,
            MatchTimeoutGuideType = 1,
            NurseProfNum = 1,
            PreQuestID = 140481,
            Priority = 11,
            RecruitID = 3,
            _RewardCnt = CS._6_1,
            _Rewards = '[19000100,66700184]',
        },
        {
            AttackProfNum = 2,
            BG = 'Texture2D\'/Game/UI/Texture/PWorld/BG/Details/UI_PWorld_BG_Details_TMMDC.UI_PWorld_BG_Details_TMMDC\'',
            BackgroudImageIcon = 'Texture2D\'/Game/UI/Texture/PWorld/Banner/UI_PWorld_Banner_PWorldList_17.UI_PWorld_Banner_PWorldList_17\'',
            Counter = 21100,
            Explain = CS._3_5,
            GuardProfNum = 1,
            HelpInfoID = 1000005,
            ID = 1211004,
            _InitialRewardCnt = '[350]',
            _InitialRewards = CS._5_1,
            MatchTimeoutGuideTime = 120,
            MatchTimeoutGuideType = 1,
            NurseProfNum = 1,
            PreQuestID = 180087,
            Priority = 14,
            RecruitID = 3,
            _RewardCnt = CS._6_6,
            _Rewards = CS._7_1,
        },
        {
            AttackProfNum = 2,
            BG = 'Texture2D\'/Game/UI/Texture/PWorld/BG/Details/UI_PWorld_BG_Details_QYFX.UI_PWorld_BG_Details_QYFX\'',
            BackgroudImageIcon = 'Texture2D\'/Game/UI/Texture/PWorld/Banner/UI_PWorld_Banner_PWorldList_24.UI_PWorld_Banner_PWorldList_24\'',
            Counter = 20600,
            Explain = '信息\
限制时间：90分钟/托托·拉克千狱\
\
参加条件\
人数要求：1~4人战斗职业（防护职业：1/治疗职业：1/进攻职业：2）\
参与等级：20级，超过等级上限时会自动进行等级同步\
装备品级：平均品级不低于1级，且品级同步45级\
\
※在品级同步状态下，所有的装备性能都会下调至对应品级的规格。\
※4人数组队时可以以任何职业构成参加，且不会受到装备品级限制。',
            GuardProfNum = 1,
            HasUnlimited = 1,
            HelpInfoID = 1000003,
            ID = 1211005,
            _InitialRewardCnt = CS._4_1,
            _InitialRewards = CS._5_2,
            MatchTimeoutGuideTime = 120,
            MatchTimeoutGuideType = 1,
            NurseProfNum = 1,
            PreQuestID = 160229,
            Priority = 7,
            RecruitID = 3,
            _RewardCnt = CS._6_1,
            _Rewards = CS._7_4,
        },
        {
            AttackProfNum = 2,
            BG = 'Texture2D\'/Game/UI/Texture/PWorld/BG/Details/UI_PWorld_BG_Details_MMFDJYZY.UI_PWorld_BG_Details_MMFDJYZY\'',
            BackgroudImageIcon = 'Texture2D\'/Game/UI/Texture/PWorld/Banner/UI_PWorld_Banner_PWorldList_08.UI_PWorld_Banner_PWorldList_08\'',
            Counter = 20700,
            Explain = '信息\
限制时间：90分钟/静语庄园\
\
参加条件\
人数要求：1~4人战斗职业（防护职业：1/治疗职业：1/进攻职业：2）\
参与等级：25级，超过等级上限时会自动进行等级同步\
装备品级：平均品级不低于1级，且品级同步60级\
\
※在品级同步状态下，所有的装备性能都会下调至对应品级的规格。\
※4人数组队时可以以任何职业构成参加，且不会受到装备品级限制。',
            GuardProfNum = 1,
            HasUnlimited = 1,
            HelpInfoID = 1000003,
            ID = 1211006,
            _InitialRewardCnt = CS._4_1,
            _InitialRewards = CS._5_2,
            MatchTimeoutGuideTime = 120,
            MatchTimeoutGuideType = 1,
            NurseProfNum = 1,
            PreQuestID = 160325,
            Priority = 8,
            RecruitID = 3,
            _RewardCnt = CS._6_1,
            _Rewards = CS._7_4,
        },
        {
            AttackProfNum = 2,
            BG = 'Texture2D\'/Game/UI/Texture/PWorld/BG/Details/UI_PWorld_BG_Details_SBYSDGNFB.UI_PWorld_BG_Details_SBYSDGNFB\'',
            BackgroudImageIcon = 'Texture2D\'/Game/UI/Texture/PWorld/Banner/UI_PWorld_Banner_PWorldList_22.UI_PWorld_Banner_PWorldList_22\'',
            Counter = 21000,
            Explain = '信息\
限制时间：90分钟/帝国南方堡\
\
参加条件\
人数要求：1~4人战斗职业（防护职业：1/治疗职业：1/进攻职业：2）\
参与等级：50级，超过等级上限时会自动进行等级同步\
装备品级：平均品级不低于1级，且品级同步115级\
\
※在品级同步状态下，所有的装备性能都会下调至对应品级的规格。\
※4人数组队时可以以任何职业构成参加，且不会受到装备品级限制。',
            GuardProfNum = 1,
            HelpInfoID = 1000005,
            ID = 1211007,
            _InitialRewardCnt = CS._4_3,
            _InitialRewards = CS._5_1,
            MatchTimeoutGuideTime = 120,
            MatchTimeoutGuideType = 1,
            NurseProfNum = 1,
            PreQuestID = 180097,
            Priority = 13,
            RecruitID = 3,
            _RewardCnt = CS._6_6,
            _Rewards = CS._7_1,
        },
        {
            AttackProfNum = 2,
            BG = 'Texture2D\'/Game/UI/Texture/PWorld/BG/Details/UI_PWorld_BG_Details_SSTXRD.UI_PWorld_BG_Details_SSTXRD\'',
            BackgroudImageIcon = 'Texture2D\'/Game/UI/Texture/PWorld/Banner/UI_PWorld_Banner_PWorldList_23.UI_PWorld_Banner_PWorldList_23\'',
            Counter = 20300,
            Explain = CS._3_6,
            GuardProfNum = 1,
            HasUnlimited = 1,
            HelpInfoID = 1000003,
            ID = 1211008,
            _InitialRewardCnt = CS._4_1,
            _InitialRewards = CS._5_2,
            MatchTimeoutGuideTime = 120,
            MatchTimeoutGuideType = 1,
            NurseProfNum = 1,
            PreQuestID = 140313,
            Priority = 3,
            RecruitID = 3,
            _RewardCnt = CS._6_1,
            _Rewards = CS._7_2,
        },
        {
            AttackProfNum = 2,
            BG = 'Texture2D\'/Game/UI/Texture/PWorld/BG/Details/UI_PWorld_BG_Details_TMTLMY.UI_PWorld_BG_Details_TMTLMY\'',
            BackgroudImageIcon = 'Texture2D\'/Game/UI/Texture/PWorld/Banner/UI_PWorld_Banner_PWorldList_18.UI_PWorld_Banner_PWorldList_18\'',
            Counter = 20400,
            Explain = '信息\
限制时间：90分钟/塔姆·塔拉墓园\
\
参加条件\
人数要求：1~4人战斗职业（防护职业：1/治疗职业：1/进攻职业：2）\
参与等级：11级，超过等级上限时会自动进行等级同步\
装备品级：平均品级不低于1级，且品级同步20级\
\
※在品级同步状态下，所有的装备性能都会下调至对应品级的规格。\
※4人数组队时可以以任何职业构成参加，且不会受到装备品级限制。',
            GuardProfNum = 1,
            HasUnlimited = 1,
            HelpInfoID = 1000003,
            ID = 1211009,
            _InitialRewardCnt = CS._4_1,
            _InitialRewards = CS._5_2,
            MatchTimeoutGuideTime = 120,
            MatchTimeoutGuideType = 1,
            NurseProfNum = 1,
            PreQuestID = 140319,
            Priority = 4,
            RecruitID = 3,
            _RewardCnt = CS._6_1,
            _Rewards = CS._7_2,
        },
        {
            AttackProfNum = 2,
            BG = 'Texture2D\'/Game/UI/Texture/PWorld/BG/Details/UI_PWorld_BG_Details_FSKDTLTS.UI_PWorld_BG_Details_FSKDTLTS\'',
            BackgroudImageIcon = 'Texture2D\'/Game/UI/Texture/PWorld/Banner/UI_PWorld_Banner_PWorldList_04.UI_PWorld_Banner_PWorldList_04\'',
            Counter = 20500,
            Explain = '信息\
限制时间：90分钟/铜铃铜山\
\
参加条件\
人数要求：1~4人战斗职业（防护职业：1/治疗职业：1/进攻职业：2）\
参与等级：12级，超过等级上限时会自动进行等级同步\
装备品级：平均品级不低于1级，且品级同步20级\
\
※在品级同步状态下，所有的装备性能都会下调至对应品级的规格。\
※4人数组队时可以以任何职业构成参加，且不会受到装备品级限制。',
            GuardProfNum = 1,
            HasUnlimited = 1,
            HelpInfoID = 1000003,
            ID = 1211010,
            _InitialRewardCnt = CS._4_1,
            _InitialRewards = CS._5_2,
            MatchTimeoutGuideTime = 120,
            MatchTimeoutGuideType = 1,
            NurseProfNum = 1,
            PreQuestID = 140326,
            Priority = 5,
            RecruitID = 3,
            _RewardCnt = CS._6_1,
            _Rewards = CS._7_2,
        },
        {
            AttackProfNum = 2,
            BG = 'Texture2D\'/Game/UI/Texture/PWorld/BG/Details/UI_PWorld_BG_Details_JJSBPHZZ.UI_PWorld_BG_Details_JJSBPHZZ\'',
            BackgroudImageIcon = 'Texture2D\'/Game/UI/Texture/PWorld/Banner/UI_PWorld_Banner_PWorldList_29.UI_PWorld_Banner_PWorldList_29\'',
            Counter = 21500,
            Explain = '信息\
限制时间：60分钟/后营门/重新挑战时发动“超越之力”状态\
\
参加条件\
人数要求：1~4人战斗职业（防护职业：1/治疗职业：1/进攻职业：2）\
参与等级：50级，超过等级上限时会自动进行等级同步\
装备品级：平均品级不低于1级，且品级同步115级\
\
※在品级同步状态下，所有的装备性能都会下调至对应品级的规格。\
※4人数组队时可以以任何职业构成参加，且不会受到装备品级限制。',
            GuardProfNum = 1,
            HelpInfoID = 1000005,
            ID = 1211011,
            _InitialRewardCnt = '[150]',
            _InitialRewards = CS._5_1,
            MatchTimeoutGuideTime = 120,
            MatchTimeoutGuideType = 1,
            NurseProfNum = 1,
            PreQuestID = 180088,
            Priority = 18,
            RecruitID = 3,
            _RewardCnt = CS._6_6,
            _Rewards = CS._7_1,
        },
        {
            AttackProfNum = 2,
            BG = 'Texture2D\'/Game/UI/Texture/PWorld/BG/Details/UI_PWorld_BG_Details_MSLYRYDXLS.UI_PWorld_BG_Details_MSLYRYDXLS\'',
            BackgroudImageIcon = 'Texture2D\'/Game/UI/Texture/PWorld/Banner/UI_PWorld_Banner_PWorldList_51.UI_PWorld_Banner_PWorldList_51\'',
            Counter = 21100,
            Explain = CS._3_5,
            GuardProfNum = 1,
            HasUnlimited = 1,
            ID = 1211012,
            _InitialRewardCnt = CS._4_1,
            _InitialRewards = CS._5_2,
            MatchTimeoutGuideTime = 120,
            MatchTimeoutGuideType = 1,
            NurseProfNum = 1,
            PreQuestID = 171246,
            Priority = 6,
            RecruitID = 3,
            _RewardCnt = CS._6_1,
            _Rewards = '[19000100,66700290]',
        },
        {
            AttackProfNum = 2,
            BG = 'Texture2D\'/Game/UI/Texture/PWorld/BG/Details/UI_PWorld_BG_Details_GDYJKEMMST.UI_PWorld_BG_Details_GDYJKEMMST\'',
            BackgroudImageIcon = 'Texture2D\'/Game/UI/Texture/PWorld/Banner/UI_PWorld_Banner_PWorldList_47.UI_PWorld_Banner_PWorldList_47\'',
            Counter = 21100,
            Explain = CS._3_5,
            GuardProfNum = 1,
            HasUnlimited = 1,
            ID = 1211013,
            _InitialRewardCnt = CS._4_1,
            _InitialRewards = CS._5_2,
            MatchTimeoutGuideTime = 120,
            MatchTimeoutGuideType = 1,
            NurseProfNum = 1,
            PreQuestID = 171244,
            Priority = 10,
            RecruitID = 3,
            _RewardCnt = CS._6_1,
            _Rewards = '[19000100,66700291]',
        },
        {
            AttackProfNum = 2,
            BG = 'Texture2D\'/Game/UI/Texture/PWorld/BG/Details/UI_PWorld_BG_Details_DWDKHJG.UI_PWorld_BG_Details_DWDKHJG\'',
            BackgroudImageIcon = 'Texture2D\'/Game/UI/Texture/PWorld/Banner/UI_PWorld_Banner_PWorldList_46.UI_PWorld_Banner_PWorldList_46\'',
            Counter = 21100,
            Explain = CS._3_5,
            GuardProfNum = 1,
            HasUnlimited = 1,
            ID = 1211014,
            _InitialRewardCnt = CS._4_1,
            _InitialRewards = CS._5_2,
            MatchTimeoutGuideTime = 120,
            MatchTimeoutGuideType = 1,
            NurseProfNum = 1,
            PreQuestID = 171248,
            Priority = 12,
            RecruitID = 3,
            _RewardCnt = CS._6_1,
            _Rewards = '[19000100,66700292]',
        },
        {
            AttackProfNum = 2,
            BG = CS._1_9,
            BackgroudImageIcon = CS._2_11,
            Counter = 20300,
            Explain = CS._3_6,
            GuardProfNum = 1,
            HasChallenge = 0,
            HelpInfoID = 1000005,
            ID = 1211015,
            NurseProfNum = 1,
            PreQuestID = 260068,
            Priority = 1,
            RecruitID = 3,
            _RewardCnt = CS._6_8,
            _Rewards = CS._7_5,
            TypeID = 13,
        },
        {
            AttackProfNum = 2,
            BG = CS._1_9,
            BackgroudImageIcon = CS._2_11,
            Counter = 20300,
            Explain = CS._3_6,
            GuardProfNum = 1,
            HasChallenge = 0,
            HelpInfoID = 1000005,
            ID = 1211016,
            NurseProfNum = 1,
            PreQuestID = 260068,
            Priority = 2,
            RecruitID = 3,
            _RewardCnt = CS._6_8,
            _Rewards = CS._7_5,
            TypeID = 13,
        },
        {
            BG = 'Texture2D\'/Game/UI/Texture/PWorld/BG/Details/UI_PWorld_BG_Details_LXNJSTYHA.UI_PWorld_BG_Details_LXNJSTYHA\'',
            BackgroudImageIcon = 'Texture2D\'/Game/UI/Texture/PWorld/Banner/UI_PWorld_Banner_PWorldList_LXNJSTYHA.UI_PWorld_Banner_PWorldList_LXNJSTYHA\'',
            CanMidWay = 0,
            Explain = CS._3_7,
            HasChallenge = 0,
            HelpInfoID = 0,
            ID = 1216001,
            Priority = 46,
            _RewardCnt = CS._6_7,
            _Rewards = CS._7_3,
            TypeID = 5,
        },
        {
            BG = 'Texture2D\'/Game/UI/Texture/PWorld/BG/Details/UI_PWorld_BG_Details_LXNJSHYDD.UI_PWorld_BG_Details_LXNJSHYDD\'',
            BackgroudImageIcon = 'Texture2D\'/Game/UI/Texture/PWorld/Banner/UI_PWorld_Banner_PWorldList_LXNJSHYDD.UI_PWorld_Banner_PWorldList_LXNJSHYDD\'',
            CanMidWay = 0,
            Explain = CS._3_7,
            HasChallenge = 0,
            HelpInfoID = 0,
            ID = 1216002,
            Priority = 47,
            _RewardCnt = CS._6_7,
            _Rewards = CS._7_3,
            TypeID = 5,
        },
        {
            BG = 'Texture2D\'/Game/UI/Texture/PWorld/BG/Details/UI_PWorld_BG_Details_LXNJSTJXL.UI_PWorld_BG_Details_LXNJSTJXL\'',
            BackgroudImageIcon = 'Texture2D\'/Game/UI/Texture/PWorld/Banner/UI_PWorld_Banner_PWorldList_LXNJSTJXL.UI_PWorld_Banner_PWorldList_LXNJSTJXL\'',
            CanMidWay = 0,
            Explain = CS._3_7,
            HasChallenge = 0,
            HelpInfoID = 0,
            ID = 1216003,
            Priority = 48,
            _RewardCnt = CS._6_7,
            _Rewards = CS._7_3,
            TypeID = 5,
        },
        {
            BG = 'Texture2D\'/Game/UI/Texture/PWorld/BG/Match/UI_PWorld_BG_Match_SCBWK.UI_PWorld_BG_Match_SCBWK\'',
            BackgroudImageIcon = 'Texture2D\'/Game/UI/Texture/PWorld/BG/Match/UI_PWorld_BG_Match_SCBWK.UI_PWorld_BG_Match_SCBWK\'',
            CanMidWay = 0,
            HasChallenge = 0,
            HasNormal = 0,
            HelpInfoID = 0,
            ID = 1216014,
            Priority = 59,
            TypeID = 12,
        },
        {
            BG = CS._1_2,
            BackgroudImageIcon = CS._2_4,
            CanMidWay = 0,
            HasChallenge = 0,
            HasNormal = 0,
            HelpInfoID = 0,
            ID = 1216015,
            Priority = 60,
            TypeID = 0,
        },
        {
            BG = 'Texture2D\'/Game/UI/Texture/PWorld/BG/Details/UI_PWorld_BG_Details_SJCTLXSSJ.UI_PWorld_BG_Details_SJCTLXSSJ\'',
            BackgroudImageIcon = CS._2_2,
            CanMidWay = 0,
            HasChallenge = 0,
            HasNormal = 0,
            HelpInfoID = 11162,
            ID = 1218010,
            PVPAdvanceProfNum = 1,
            Priority = 50,
            _RewardCnt = CS._6_9,
            _Rewards = CS._7_6,
            TypeID = 9,
        },
        {
            BG = 'Texture3D\'/Game/UI/Texture/PWorld/BG/Details/UI_PWorld_BG_Details_SJCTLXSSJ.UI_PWorld_BG_Details_SJCTLXSSJ\'',
            BackgroudImageIcon = CS._2_2,
            CanMidWay = 0,
            HasChallenge = 0,
            HasNormal = 0,
            HelpInfoID = 11162,
            ID = 1218011,
            IsHideInList = 1,
            Priority = 51,
            TypeID = 9,
        },
        {
            BG = 'Texture4D\'/Game/UI/Texture/PWorld/BG/Details/UI_PWorld_BG_Details_SJCTLXSSJ.UI_PWorld_BG_Details_SJCTLXSSJ\'',
            BackgroudImageIcon = CS._2_2,
            CanMidWay = 0,
            HasChallenge = 0,
            HasNormal = 0,
            HelpInfoID = 11162,
            ID = 1218012,
            IsHideInList = 1,
            Priority = 52,
            TypeID = 9,
        },
        {
            BG = 'Texture2D\'/Game/UI/Texture/PWorld/BG/Details/UI_PWorld_BG_Details_SJCTLXSSJYW.UI_PWorld_BG_Details_SJCTLXSSJYW\'',
            BackgroudImageIcon = CS._2_3,
            CanMidWay = 0,
            HasChallenge = 0,
            HasNormal = 0,
            HelpInfoID = 11162,
            ID = 1218020,
            PVPAdvanceProfNum = 1,
            Priority = 53,
            _RewardCnt = CS._6_9,
            _Rewards = CS._7_6,
            TypeID = 10,
        },
        {
            BG = 'Texture3D\'/Game/UI/Texture/PWorld/BG/Details/UI_PWorld_BG_Details_SJCTLXSSJYW.UI_PWorld_BG_Details_SJCTLXSSJYW\'',
            BackgroudImageIcon = CS._2_3,
            CanMidWay = 0,
            HasChallenge = 0,
            HasNormal = 0,
            HelpInfoID = 11162,
            ID = 1218021,
            IsHideInList = 1,
            Priority = 54,
            TypeID = 10,
        },
        {
            BG = 'Texture4D\'/Game/UI/Texture/PWorld/BG/Details/UI_PWorld_BG_Details_SJCTLXSSJYW.UI_PWorld_BG_Details_SJCTLXSSJYW\'',
            BackgroudImageIcon = CS._2_3,
            CanMidWay = 0,
            HasChallenge = 0,
            HasNormal = 0,
            HelpInfoID = 11162,
            ID = 1218022,
            IsHideInList = 1,
            Priority = 55,
            TypeID = 10,
        },
        {
            BG = 'Texture2D\'/Game/UI/Texture/PWorld/BG/Details/UI_PWorld_BG_Details_PVPSJCTZDSJLXX.UI_PWorld_BG_Details_PVPSJCTZDSJLXX\'',
            BackgroudImageIcon = 'Texture2D\'/Game/UI/Texture/PWorld/Banner/UI_PWorld_Banner_PWorldList_41.UI_PWorld_Banner_PWorldList_41\'',
            CanMidWay = 0,
            HasChallenge = 0,
            HasNormal = 0,
            HelpInfoID = 11162,
            ID = 1218030,
            IsHideInList = 1,
            PVPAdvanceProfNum = 1,
            Priority = 56,
            TypeID = 11,
        },
        {
            BG = 'Texture2D\'/Game/UI/Texture/PWorld/BG/Details/UI_PWorld_BG_Details_SJCTZDSHSZX.UI_PWorld_BG_Details_SJCTZDSHSZX\'',
            BackgroudImageIcon = 'Texture2D\'/Game/UI/Texture/PWorld/Banner/UI_PWorld_Banner_PWorldList_39.UI_PWorld_Banner_PWorldList_39\'',
            CanMidWay = 0,
            HasChallenge = 0,
            HasNormal = 0,
            HelpInfoID = 11162,
            ID = 1218031,
            IsHideInList = 1,
            PVPAdvanceProfNum = 1,
            Priority = 57,
            TypeID = 11,
        },
        {
            BG = 'Texture2D\'/Game/UI/Texture/PWorld/BG/Details/UI_PWorld_BG_Details_SJCTZDSJXYS.UI_PWorld_BG_Details_SJCTZDSJXYS\'',
            BackgroudImageIcon = 'Texture2D\'/Game/UI/Texture/PWorld/Banner/UI_PWorld_Banner_PWorldList_40.UI_PWorld_Banner_PWorldList_40\'',
            CanMidWay = 0,
            HasChallenge = 0,
            HasNormal = 0,
            HelpInfoID = 11162,
            ID = 1218032,
            IsHideInList = 1,
            PVPAdvanceProfNum = 1,
            Priority = 58,
            TypeID = 11,
        },
        {
            CanMidWay = 0,
            Explain = CS._3_1,
            HasChallenge = 0,
            HasNormal = 0,
            HelpInfoID = 11052,
            ID = 1230041,
            PreQuestID = 171152,
            Priority = 37,
            SPID = 533,
            TypeID = 7,
        },
        {
            CanMidWay = 0,
            Explain = CS._3_1,
            HasChallenge = 0,
            HasNormal = 0,
            HelpInfoID = 11052,
            ID = 1230051,
            PreQuestID = 220005,
            Priority = 38,
            SPID = 534,
            TypeID = 7,
        },
        {
            CanMidWay = 0,
            Explain = CS._3_1,
            HasChallenge = 0,
            HasNormal = 0,
            HelpInfoID = 11052,
            ID = 1230052,
            PreQuestID = 210126,
            Priority = 39,
            SPID = 535,
            TypeID = 7,
        },
        {
            CanMidWay = 0,
            Explain = CS._3_1,
            HasChallenge = 0,
            HasNormal = 0,
            HelpInfoID = 11052,
            ID = 1230053,
            PreQuestID = 210128,
            Priority = 42,
            SPID = 536,
            TypeID = 7,
        },
        {
            CanMidWay = 0,
            Explain = CS._3_1,
            HasChallenge = 0,
            HasNormal = 0,
            HelpInfoID = 11052,
            ID = 1230054,
            PreQuestID = 210128,
            Priority = 43,
            SPID = 537,
            TypeID = 7,
        },
        {
            CanMidWay = 0,
            Explain = CS._3_1,
            HasChallenge = 0,
            HasNormal = 0,
            HelpInfoID = 11052,
            ID = 1230055,
            PreQuestID = 210127,
            Priority = 40,
            SPID = 538,
            TypeID = 7,
        },
        {
            CanMidWay = 0,
            Explain = CS._3_1,
            HasChallenge = 0,
            HasNormal = 0,
            HelpInfoID = 11052,
            ID = 1230056,
            PreQuestID = 210127,
            Priority = 41,
            SPID = 539,
            TypeID = 7,
        },
        {
            BG = '',
            BackgroudImageIcon = '',
            CanMidWay = 0,
            HasChallenge = 0,
            HasNormal = 0,
            HelpInfoID = 0,
            ID = 1230057,
            PreQuestID = 900001,
            Priority = 44,
            TypeID = 0,
        },
        {
            CanMidWay = 0,
            Explain = CS._3_1,
            HasChallenge = 0,
            HasNormal = 0,
            HelpInfoID = 11052,
            ID = 1230058,
            PreQuestID = 160038,
            Priority = 45,
            SPID = 567,
            TypeID = 7,
        },
	},
}

setmetatable(SceneEnterCfg, { __index = CfgBase })

SceneEnterCfg:InitCfg()

-- AUTO GENERATED CODE END, PLEASE DON'T MODIFY

---获取副本进入前置任务ID
---@param ID number @副本入口ID
---@return number
function SceneEnterCfg:GetPreQuestID( ID )
	local Cfg = self:FindCfgByKey(ID)
	if nil == Cfg then 
		return 
	end

	return Cfg.PreQuestID
end

return SceneEnterCfg
