-- AUTO GENERATED CODE BEGIN, PLEASE DON'T MODIFY

local CfgBase = require("TableCfg/CfgBase")

local CS = {
    _1_1 = 'Texture2D\'/Game/UI/Texture/PWorld/BG/Details/UI_PWorld_BG_Details_BHMTDMGRQZZ4.UI_PWorld_BG_Details_BHMTDMGRQZZ4\'',
    _1_2 = 'Texture2D\'/Game/UI/Texture/PWorld/BG/Details/UI_PWorld_BG_Details_TT.UI_PWorld_BG_Details_TT\'',
    _1_3 = 'Texture2D\'/Game/UI/Texture/PWorld/BG/Details/UI_PWorld_BG_Details_LMJMZ.UI_PWorld_BG_Details_LMJMZ\'',
    _1_4 = 'Texture2D\'/Game/UI/Texture/PWorld/BG/Details/UI_PWorld_BG_Details_LWYSJMZ.UI_PWorld_BG_Details_LWYSJMZ\'',
    _1_5 = 'Texture2D\'/Game/UI/Texture/PWorld/BG/Details/UI_PWorld_BG_Details_XWJMZ.UI_PWorld_BG_Details_XWJMZ\'',
    _1_6 = 'Texture2D\'/Game/UI/Texture/PWorld/BG/Details/UI_PWorld_BG_Details_BHMTDMGRQZZ1.UI_PWorld_BG_Details_BHMTDMGRQZZ1\'',
    _1_7 = 'Texture2D\'/Game/UI/Texture/PWorld/BG/Details/UI_PWorld_BG_Details_BHMTDMGXHZZ1.UI_PWorld_BG_Details_BHMTDMGXHZZ1\'',
    _1_8 = 'Texture2D\'/Game/UI/Texture/PWorld/BG/Details/UI_PWorld_BG_Details_BHMTDMGZYZZ1.UI_PWorld_BG_Details_BHMTDMGZYZZ1\'',
    _1_9 = 'Texture2D\'/Game/UI/Texture/PWorld/BG/Details/UI_PWorld_BG_Details_BHMTDMGZYZZ4.UI_PWorld_BG_Details_BHMTDMGZYZZ4\'',
    _1_10 = 'Texture2D\'/Game/UI/Texture/PWorld/BG/Details/UI_PWorld_BG_Details_BHMTDMGZYZZ3.UI_PWorld_BG_Details_BHMTDMGZYZZ3\'',
    _1_11 = 'Texture2D\'/Game/UI/Texture/PWorld/BG/Details/UI_PWorld_BG_Details_BHMTDMGZYZZ2.UI_PWorld_BG_Details_BHMTDMGZYZZ2\'',
    _1_12 = 'Texture2D\'/Game/UI/Texture/PWorld/BG/Details/UI_PWorld_BG_Details_BHMTDMGXHZZ5.UI_PWorld_BG_Details_BHMTDMGXHZZ5\'',
    _1_13 = 'Texture2D\'/Game/UI/Texture/Ops/OpsHalloween/UI_Pworld_BG_Halloween.UI_Pworld_BG_Halloween\'',
    _2_1 = 'Texture2D\'/Game/UI/Texture/PWorld/Banner/UI_PWorld_Banner_PWorldList_25.UI_PWorld_Banner_PWorldList_25\'',
    _2_2 = 'Texture2D\'/Game/UI/Texture/PWorld/Banner/UI_PWorld_Banner_PWorldList_38.UI_PWorld_Banner_PWorldList_38\'',
    _2_3 = 'Texture2D\'/Game/UI/Texture/PWorld/Banner/UI_PWorld_Banner_PWorldList_43.UI_PWorld_Banner_PWorldList_43\'',
    _2_4 = 'Texture2D\'/Game/UI/Texture/PWorld/Banner/UI_PWorld_Banner_PWorldList_30.UI_PWorld_Banner_PWorldList_30\'',
    _2_5 = 'Texture2D\'/Game/UI/Texture/PWorld/Banner/UI_PWorld_Banner_PWorldList_28.UI_PWorld_Banner_PWorldList_28\'',
    _2_6 = 'Texture2D\'/Game/UI/Texture/PWorld/Banner/UI_PWorld_Banner_PWorldList_27.UI_PWorld_Banner_PWorldList_27\'',
    _2_7 = 'Texture2D\'/Game/UI/Texture/PWorld/Banner/UI_PWorld_Banner_PWorldList_50.UI_PWorld_Banner_PWorldList_50\'',
    _2_8 = 'Texture2D\'/Game/UI/Texture/PWorld/Banner/UI_PWorld_Banner_PWorldList_26.UI_PWorld_Banner_PWorldList_26\'',
    _2_9 = 'Texture2D\'/Game/UI/Texture/PWorld/Banner/UI_PWorld_Banner_PWorldList_36.UI_PWorld_Banner_PWorldList_36\'',
    _2_10 = 'Texture2D\'/Game/UI/Texture/PWorld/Banner/UI_PWorld_Banner_PWorldList_37.UI_PWorld_Banner_PWorldList_37\'',
    _2_11 = 'Texture2D\'/Game/UI/Texture/PWorld/Banner/UI_PWorld_Banner_PWorldList_33.UI_PWorld_Banner_PWorldList_33\'',
    _2_12 = 'Texture2D\'/Game/UI/Texture/PWorld/Banner/UI_PWorld_Banner_PWorldList_32.UI_PWorld_Banner_PWorldList_32\'',
    _2_13 = 'Texture2D\'/Game/UI/Texture/PWorld/Banner/UI_PWorld_Banner_PWorldList_06.UI_PWorld_Banner_PWorldList_06\'',
    _2_14 = 'Texture2D\'/Game/UI/Texture/PWorld/Banner/UI_PWorld_Banner_PWorldList_05.UI_PWorld_Banner_PWorldList_05\'',
    _2_15 = 'Texture2D\'/Game/UI/Texture/PWorld/Banner/UI_PWorld_Banner_PWorldList_SSTXRD.UI_PWorld_Banner_PWorldList_SSTXRD\'',
    _3_1 = '信息\
限制时间：120分钟/古代人迷宫\
\
人数要求：1~4人战斗职业（防护职业：1/治疗职业：1/进攻职业：2）\
参与等级：50级，超过等级上限时会自动进行等级同步\
装备品级：平均品级不低于1级，且品级同步115级\
\
※在品级同步状态下，所有的装备性能都会下调至对应品级的规格。\
※8人数组队时可以以任何职业构成参加，且不会受到装备品级限制。',
    _3_3 = '信息\
限制时间 60分钟/后营门/重新挑战时发动“超越之力”状态',
    _3_4 = '信息\
限制时间：60分钟/奥·哥摩罗火口神殿/重新挑战时发动“超越之力”状态\
\
参加条件\
人数要求：1~4人战斗职业（防护职业：1/治疗职业：1/进攻职业：2）\
参与等级：35级，超过等级上限时会自动进行等级同步\
装备品级：平均品级不低于1级，且品级同步80级\
\
※在品级同步状态下，所有的装备性能都会下调至对应品级的规格。\
※8人数组队时可以以任何职业构成参加，且不会受到装备品级限制。',
    _3_5 = '信息\
限制时间：120分钟/天幕魔导城\
\
参加条件\
人数要求：1~4人战斗职业（防护职业：1/治疗职业：1/进攻职业：2）\
参与等级：50级，超过等级上限时会自动进行等级同步\
装备品级：平均品级不低于1级，且品级同步130级\
\
※在品级同步状态下，所有的装备性能都会下调至对应品级的规格。\
※4人数组队时可以以任何职业构成参加，且不会受到装备品级限制。',
    _3_6 = '信息\
限制时间：90分钟/沙斯塔夏溶洞\
\
参加条件\
人数要求：1~4人战斗职业（防护职业：1/治疗职业：1/进攻职业：2）\
参与等级：10级，超过等级上限时会自动进行等级同步\
装备品级：平均品级不低于1级，且品级同步20级\
\
※在品级同步状态下，所有的装备性能都会下调至对应品级的规格。\
※4人数组队时可以以任何职业构成参加，且不会受到装备品级限制。',
    _3_7 = '信息\
限制时间：60分钟/后营门/重新挑战时发动“超越之力”状态\
\
参加条件\
人数要求：1~4人战斗职业（防护职业：1/治疗职业：1/进攻职业：2）\
参与等级：50级，超过等级上限时会自动进行等级同步\
装备品级：平均品级不低于1级，且品级同步115级\
\
※在品级同步状态下，所有的装备性能都会下调至对应品级的规格。\
※4人数组队时可以以任何职业构成参加，且不会受到装备品级限制。',
    _3_8 = '信息\
限制时间：10分钟/无法补充队员/不可与其他任务同时搜索\
\
人数要求：1~8人（不限制职业）\
参与等级：1级\
\
※无法解除限制/更改分配方式/同步到最低品级\
※不支持自由探索',
    _4_1 = '[100]',
    _4_2 = '[50]',
    _4_3 = '[80]',
    _5_1 = '[]',
    _5_2 = '[19000100]',
    _6_1 = '[50,10]',
    _6_2 = '[30,1,1,1]',
    _6_3 = '[50,10,2]',
    _6_4 = '[20,1,1,1]',
    _6_5 = '[50,10,1,1,1]',
    _6_6 = '[50,10,1,1]',
    _6_7 = '[50,10,1]',
    _6_8 = '[1,1]',
    _6_9 = '[30,1,1,1,1]',
    _6_10 = '[80,35,1,1]',
    _6_11 = '[1]',
    _6_12 = '[1,1,1,1]',
    _7_1 = '[3,4]',
    _7_2 = '[3]',
    _7_3 = '[4,5]',
    _7_4 = '[3,4,5]',
    _7_5 = '[4]',
    _7_6 = '[4,5,6,7,8,9,10]',
    _8_1 = '[19000101,19000102]',
    _8_2 = '[19000004,19000502]',
    _8_3 = '[66700181]',
    _8_4 = '[19000099,19000098,19000100,19000002]',
    _10_1 = '[2]',
}

---@class SceneEnterCfg : CfgBase
local SceneEnterCfg = {
	TableName = "c_scene_enter_cfg",
    LruKeyType = nil,
	KeyName = "ID",
    bEncrypted = false,
	Localization = {
        Config = {
            {
                Name = 'Summary',
            },
		}
    },
    DefaultValues = {
        ArmSyncLevel = 0,
        AttackProfNum = 4,
        BG = 'Texture2D\'/Game/UI/Texture/PWorld/BG/Details/UI_PWorld_BG_Details_MRSJMRJMZ.UI_PWorld_BG_Details_MRSJMRJMZ\'',
        BackgroudImageIcon = 'Texture2D\'/Game/UI/Texture/PWorld/Banner/UI_PWorld_Banner_PWorldList_10.UI_PWorld_Banner_PWorldList_10\'',
        CanMidWay = 1,
        Counter = 0,
        Explain = '信息\
限制时间：3分钟/无法补充队员/不可与其他任务同时搜索\
\
人数要求：1人（不限制职业）',
        GuardProfNum = 2,
        HasChallenge = 1,
        HasExplore = 0,
        HasNormal = 1,
        HasUnlimited = 0,
        HelpInfoID = 1000004,
        ID = 1116012,
        _InitialRewardCnt = '[]',
        _InitialRewards = '[19000101]',
        IsHideInList = 0,
        MatchTimeoutGuideRecruitID = 0,
        MatchTimeoutGuideTime = 180,
        MatchTimeoutGuideType = 2,
        NurseProfNum = 2,
        PVPAdvanceProfNum = 0,
        PlayerSyncLevel = 0,
        PreQuestID = 0,
        PrepassEntID = 0,
        Priority = 70,
        PunishmentTime = 1800,
        RecruitID = 0,
        _RewardCnt = '[]',
        _RewardPropIndex = '[]',
        _Rewards = '[]',
        SPID = 0,
        TypeID = 4,
        _WeeklyItem = '[]',
        _WeeklyItemCnt = '[]',
        ZeroFormPriority = 0,
        ZeroFormWeeklyCounter = 0,
        bBattlePWorld = 0,
    },
	LuaData = {
        {
            AttackProfNum = 0,
            BG = 'Texture2D\'/Game/UI/Texture/PWorld/BG/Match/UI_PWorld_BG_Match_HKDJS.UI_PWorld_BG_Match_HKDJS\'',
            BackgroudImageIcon = 'Texture2D\'/Game/UI/Texture/PWorld/BG/Match/UI_PWorld_BG_Match_HKDJS.UI_PWorld_BG_Match_HKDJS\'',
            CanMidWay = 0,
            Explain = '信息\
人数要求：1~8人（不限制职业）',
            GuardProfNum = 0,
            HasChallenge = 0,
            HelpInfoID = 0,
            _InitialRewards = CS._5_1,
            MatchTimeoutGuideTime = 0,
            MatchTimeoutGuideType = 0,
            NurseProfNum = 0,
            PreQuestID = 171249,
            PunishmentTime = 0,
            SPID = 500101,
            TypeID = 6,
        },
        {
            BG = CS._1_2,
            BackgroudImageIcon = CS._2_4,
            Counter = 21300,
            Explain = CS._3_4,
            HasUnlimited = 1,
            ID = 1202015,
            _InitialRewardCnt = CS._4_3,
            _InitialRewards = CS._5_2,
            MatchTimeoutGuideRecruitID = 301,
            PreQuestID = 160407,
            Priority = 19,
            PunishmentTime = 0,
            RecruitID = 301,
            _RewardCnt = CS._6_4,
            _RewardPropIndex = CS._7_1,
            _Rewards = '[19000100,60900163,61400041,61800169]',
            TypeID = 3,
        },
        {
            BG = 'Texture2D\'/Game/UI/Texture/PWorld/BG/Details/UI_PWorld_BG_Details_JLL.UI_PWorld_BG_Details_JLL\'',
            BackgroudImageIcon = 'Texture2D\'/Game/UI/Texture/PWorld/Banner/UI_PWorld_Banner_PWorldList_35.UI_PWorld_Banner_PWorldList_35\'',
            Counter = 21400,
            Explain = '信息\
限制时间：60分钟/呼啸眼石塔群/重新挑战时发动“超越之力”状态\
\
参加条件\
人数要求：1~4人战斗职业（防护职业：1/治疗职业：1/进攻职业：2）\
参与等级：45级，超过等级上限时会自动进行等级同步\
装备品级：平均品级不低于1级，且品级同步105级\
\
※在品级同步状态下，所有的装备性能都会下调至对应品级的规格。\
※8人数组队时可以以任何职业构成参加，且不会受到装备品级限制。',
            HasUnlimited = 1,
            ID = 1202020,
            _InitialRewardCnt = CS._4_3,
            _InitialRewards = CS._5_2,
            MatchTimeoutGuideRecruitID = 302,
            PreQuestID = 140525,
            Priority = 20,
            PunishmentTime = 0,
            RecruitID = 302,
            _RewardCnt = CS._6_4,
            _RewardPropIndex = CS._7_1,
            _Rewards = '[19000100,60900164,61400042,61800168]',
            TypeID = 3,
        },
        {
            BG = 'Texture2D\'/Game/UI/Texture/PWorld/BG/Details/UI_PWorld_BG_Details_YFLTTFZ.UI_PWorld_BG_Details_YFLTTFZ\'',
            BackgroudImageIcon = 'Texture2D\'/Game/UI/Texture/PWorld/Banner/UI_PWorld_Banner_PWorldList_34.UI_PWorld_Banner_PWorldList_34\'',
            Counter = 21200,
            Explain = '信息\
限制时间：60分钟/炎帝陵/重新挑战时发动"超越之力"状态\
\
参加条件\
人数要求：1~4人战斗职业（防护职业：1/治疗职业：1/进攻职业：2）\
参与等级：15级，超过等级上限时会自动进行等级同步\
装备品级：平均品级不低于1级，且品级同步30级\
\
※在品级同步状态下，所有的装备性能都会下调至对应品级的规格。\
※8人数组队时可以以任何职业构成参加，且不会受到装备品级限制。',
            HasUnlimited = 1,
            ID = 1202021,
            _InitialRewardCnt = CS._4_3,
            _InitialRewards = CS._5_2,
            MatchTimeoutGuideRecruitID = 300,
            PreQuestID = 140374,
            Priority = 18,
            PunishmentTime = 0,
            RecruitID = 300,
            _RewardCnt = CS._6_4,
            _RewardPropIndex = CS._7_1,
            _Rewards = '[19000100,60900162,61400040,61800167]',
            TypeID = 3,
        },
        {
            BG = 'Texture2D\'/Game/UI/Texture/PWorld/BG/Details/UI_PWorld_BG_Details_JJSBJXZZ.UI_PWorld_BG_Details_JJSBJXZZ\'',
            BackgroudImageIcon = 'Texture2D\'/Game/UI/Texture/PWorld/Banner/UI_PWorld_Banner_PWorldList_03.UI_PWorld_Banner_PWorldList_03\'',
            Explain = CS._3_3,
            ID = 1202022,
            _InitialRewardCnt = CS._4_3,
            MatchTimeoutGuideRecruitID = 401,
            PreQuestID = 210126,
            Priority = 28,
            RecruitID = 401,
            _RewardCnt = '[50,10,4,1,1]',
            _RewardPropIndex = CS._7_3,
            _Rewards = '[19000101,19000102,66700192,61400051,61500029]',
            TypeID = 3,
        },
        {
            BG = CS._1_3,
            BackgroudImageIcon = CS._2_5,
            Explain = CS._3_3,
            ID = 1202023,
            _InitialRewardCnt = CS._4_3,
            MatchTimeoutGuideRecruitID = 305,
            PreQuestID = 171183,
            Priority = 23,
            RecruitID = 305,
            _RewardCnt = CS._6_5,
            _RewardPropIndex = CS._7_3,
            _Rewards = '[19000101,19000102,60900167,61400053,61800184]',
            TypeID = 3,
        },
        {
            BG = 'Texture2D\'/Game/UI/Texture/PWorld/BG/Details/UI_PWorld_BG_Details_MGLXWJMZ.UI_PWorld_BG_Details_MGLXWJMZ\'',
            BackgroudImageIcon = 'Texture2D\'/Game/UI/Texture/PWorld/Banner/UI_PWorld_Banner_PWorldList_07.UI_PWorld_Banner_PWorldList_07\'',
            Explain = CS._3_3,
            ID = 1202024,
            _InitialRewardCnt = CS._4_3,
            MatchTimeoutGuideRecruitID = 303,
            PreQuestID = 160012,
            Priority = 21,
            RecruitID = 303,
            _RewardCnt = CS._6_6,
            _RewardPropIndex = CS._7_5,
            _Rewards = '[19000101,19000102,60900165,61400043]',
            TypeID = 3,
        },
        {
            BG = CS._1_4,
            BackgroudImageIcon = CS._2_6,
            Explain = CS._3_3,
            ID = 1202025,
            _InitialRewardCnt = CS._4_3,
            MatchTimeoutGuideRecruitID = 304,
            PreQuestID = 200250,
            Priority = 22,
            RecruitID = 304,
            _RewardCnt = CS._6_5,
            _RewardPropIndex = CS._7_3,
            _Rewards = '[19000101,19000102,60900166,61400054,61800170]',
            TypeID = 3,
        },
        {
            BG = 'Texture2D\'/Game/UI/Texture/PWorld/BG/Details/UI_PWorld_BG_Details_ADJMZ.UI_PWorld_BG_Details_ADJMZ\'',
            BackgroudImageIcon = 'Texture2D\'/Game/UI/Texture/PWorld/Banner/UI_PWorld_Banner_PWorldList_54.UI_PWorld_Banner_PWorldList_54\'',
            Explain = CS._3_3,
            ID = 1202026,
            _InitialRewardCnt = CS._4_3,
            MatchTimeoutGuideRecruitID = 308,
            PreQuestID = 160461,
            Priority = 26,
            RecruitID = 308,
            _RewardCnt = CS._6_6,
            _RewardPropIndex = CS._7_1,
            _Rewards = '[19000101,19000102,61400052,61500133]',
            TypeID = 3,
        },
        {
            BG = 'Texture2D\'/Game/UI/Texture/PWorld/BG/Details/UI_PWorld_BG_Details_NBLYLSJMZ.UI_PWorld_BG_Details_NBLYLSJMZ\'',
            BackgroudImageIcon = 'Texture2D\'/Game/UI/Texture/PWorld/Banner/UI_PWorld_Banner_PWorldList_56.UI_PWorld_Banner_PWorldList_56\'',
            Explain = CS._3_3,
            ID = 1202027,
            _InitialRewardCnt = CS._4_3,
            MatchTimeoutGuideRecruitID = 306,
            PreQuestID = 171208,
            Priority = 24,
            RecruitID = 306,
            _RewardCnt = CS._6_1,
            _Rewards = CS._8_1,
            TypeID = 3,
        },
        {
            BG = CS._1_5,
            BackgroudImageIcon = CS._2_7,
            Explain = CS._3_3,
            ID = 1202028,
            _InitialRewardCnt = CS._4_3,
            MatchTimeoutGuideRecruitID = 307,
            PreQuestID = 210075,
            Priority = 25,
            RecruitID = 307,
            _RewardCnt = CS._6_5,
            _RewardPropIndex = CS._7_3,
            _Rewards = '[19000101,19000102,60900168,61400055,61800185]',
            TypeID = 3,
        },
        {
            BG = CS._1_2,
            BackgroudImageIcon = CS._2_4,
            Counter = 21600,
            Explain = '信息\
限制时间：60分钟/奥·哥摩罗火口神殿/重新挑战时发动“超越之力”状态\
\
人数要求：1~4人战斗职业（防护职业：1/治疗职业：1/进攻职业：2）\
参与等级：50级，超过等级上限时会自动进行等级同步\
装备品级：平均品级不低于1级，且品级同步125级\
\
※在品级同步状态下，所有的装备性能都会下调至对应品级的规格。\
※8人数组队时可以以任何职业构成参加，且不会受到装备品级限制。',
            ID = 1203016,
            _InitialRewardCnt = CS._4_3,
            MatchTimeoutGuideRecruitID = 400,
            PreQuestID = 220005,
            Priority = 27,
            RecruitID = 400,
            _RewardCnt = '[50,4,1,1,1]',
            _RewardPropIndex = CS._7_4,
            _Rewards = '[19000101,66700190,61400041,61500032,61700018]',
            TypeID = 3,
        },
        {
            BG = CS._1_3,
            BackgroudImageIcon = CS._2_5,
            Explain = CS._3_3,
            ID = 1203024,
            _InitialRewardCnt = CS._4_3,
            MatchTimeoutGuideRecruitID = 403,
            PreQuestID = 160039,
            Priority = 30,
            RecruitID = 403,
            _RewardCnt = '[50,10,1,1,1,1,1,1,1]',
            _RewardPropIndex = '[4,5,6,7,8,9]',
            _Rewards = '[19000101,19000102,66700196,61400053,61500106,61700027,62100067,62100068,62100069]',
            TypeID = 3,
        },
        {
            BG = CS._1_5,
            BackgroudImageIcon = CS._2_7,
            Explain = CS._3_3,
            ID = 1203025,
            _InitialRewardCnt = CS._4_3,
            MatchTimeoutGuideRecruitID = 404,
            PreQuestID = 160414,
            Priority = 31,
            RecruitID = 404,
            _RewardCnt = '[50,10,1,1,1,1,1,1,1,1]',
            _RewardPropIndex = CS._7_6,
            _Rewards = '[19000101,19000102,66700197,61400055,61500104,61500105,61700031,62100074,62100075,62100076]',
            TypeID = 3,
        },
        {
            BG = CS._1_4,
            BackgroudImageIcon = CS._2_6,
            Explain = CS._3_3,
            ID = 1203277,
            _InitialRewardCnt = CS._4_3,
            MatchTimeoutGuideRecruitID = 402,
            PreQuestID = 160038,
            Priority = 29,
            RecruitID = 402,
            _RewardCnt = '[50,10,4,1,1,1,1,1,1,1]',
            _RewardPropIndex = CS._7_6,
            _Rewards = '[19000101,19000102,66700193,61400054,61500068,61500069,61700019,62100060,62100061,62100062]',
            TypeID = 3,
        },
        {
            BG = CS._1_6,
            BackgroudImageIcon = CS._2_8,
            Counter = 21700,
            Explain = CS._3_1,
            ID = 1205010,
            _InitialRewardCnt = CS._4_1,
            MatchTimeoutGuideRecruitID = 610,
            PreQuestID = 210128,
            Priority = 45,
            RecruitID = 610,
            _RewardCnt = CS._6_3,
            _Rewards = '[19000101,19000102,66700201]',
        },
        {
            BG = CS._1_7,
            BackgroudImageIcon = CS._2_9,
            Counter = 22000,
            Explain = CS._3_4,
            ID = 1205011,
            _InitialRewardCnt = CS._4_1,
            MatchTimeoutGuideRecruitID = 608,
            PreQuestID = 210127,
            Priority = 43,
            RecruitID = 608,
            _RewardCnt = CS._6_3,
            _Rewards = '[19000101,19000102,66700199]',
        },
        {
            BG = CS._1_6,
            BackgroudImageIcon = CS._2_8,
            Counter = 21700,
            Explain = CS._3_1,
            ID = 1205012,
            _InitialRewardCnt = CS._4_1,
            MatchTimeoutGuideRecruitID = 602,
            PreQuestID = 210136,
            Priority = 37,
            RecruitID = 602,
            _RewardCnt = CS._6_1,
            _Rewards = CS._8_1,
        },
        {
            BG = CS._1_1,
            BackgroudImageIcon = CS._2_1,
            Counter = 21700,
            Explain = CS._3_1,
            ID = 1205013,
            _InitialRewardCnt = CS._4_1,
            MatchTimeoutGuideRecruitID = 611,
            PreQuestID = 210128,
            Priority = 46,
            RecruitID = 611,
            _RewardCnt = CS._6_3,
            _Rewards = '[19000101,19000102,66700202]',
        },
        {
            BG = CS._1_1,
            BackgroudImageIcon = CS._2_1,
            Counter = 21700,
            Explain = CS._3_1,
            ID = 1205014,
            _InitialRewardCnt = CS._4_1,
            MatchTimeoutGuideRecruitID = 603,
            PreQuestID = 210137,
            Priority = 38,
            RecruitID = 603,
            _RewardCnt = CS._6_6,
            _RewardPropIndex = CS._7_5,
            _Rewards = '[19000101,19000102,66700191,61500043]',
        },
        {
            BG = CS._1_7,
            BackgroudImageIcon = CS._2_9,
            Counter = 22000,
            Explain = CS._3_4,
            ID = 1205015,
            _InitialRewardCnt = CS._4_1,
            MatchTimeoutGuideRecruitID = 600,
            PreQuestID = 210130,
            Priority = 35,
            RecruitID = 600,
            _RewardCnt = CS._6_1,
            _Rewards = CS._8_1,
        },
        {
            BG = CS._1_8,
            BackgroudImageIcon = CS._2_10,
            Counter = 22000,
            Explain = CS._3_4,
            HelpInfoID = 1000006,
            ID = 1205016,
            _InitialRewardCnt = CS._4_1,
            MatchTimeoutGuideRecruitID = 613,
            PreQuestID = 210129,
            Priority = 48,
            RecruitID = 613,
            _RewardCnt = CS._6_1,
            _Rewards = CS._8_1,
            _WeeklyItem = '[66700203]',
            _WeeklyItemCnt = CS._10_1,
            ZeroFormPriority = 1,
            ZeroFormWeeklyCounter = 1100,
        },
        {
            BG = CS._1_8,
            BackgroudImageIcon = CS._2_10,
            Counter = 22000,
            Explain = CS._3_4,
            ID = 1205017,
            _InitialRewardCnt = CS._4_1,
            MatchTimeoutGuideRecruitID = 604,
            PreQuestID = 210141,
            Priority = 39,
            RecruitID = 604,
            _RewardCnt = CS._6_1,
            _Rewards = CS._8_1,
        },
        {
            BG = CS._1_9,
            BackgroudImageIcon = CS._2_11,
            Counter = 21700,
            Explain = CS._3_1,
            HelpInfoID = 1000006,
            ID = 1205018,
            _InitialRewardCnt = CS._4_1,
            MatchTimeoutGuideRecruitID = 616,
            PreQuestID = 210129,
            PrepassEntID = 1205020,
            Priority = 51,
            RecruitID = 616,
            _RewardCnt = CS._6_1,
            _Rewards = CS._8_1,
            _WeeklyItem = '[66700206]',
            _WeeklyItemCnt = CS._10_1,
            ZeroFormPriority = 4,
            ZeroFormWeeklyCounter = 1400,
        },
        {
            BG = CS._1_9,
            BackgroudImageIcon = CS._2_11,
            Counter = 21700,
            Explain = CS._3_1,
            ID = 1205019,
            _InitialRewardCnt = CS._4_1,
            MatchTimeoutGuideRecruitID = 607,
            PreQuestID = 210146,
            Priority = 42,
            RecruitID = 607,
            _RewardCnt = CS._6_7,
            _RewardPropIndex = CS._7_2,
            _Rewards = '[19000101,19000102,61500045]',
            _WeeklyItem = '[66700195]',
            _WeeklyItemCnt = CS._10_1,
            ZeroFormWeeklyCounter = 1500,
        },
        {
            BG = CS._1_10,
            BackgroudImageIcon = CS._2_12,
            Counter = 21700,
            Explain = CS._3_1,
            HelpInfoID = 1000006,
            ID = 1205020,
            _InitialRewardCnt = CS._4_1,
            MatchTimeoutGuideRecruitID = 615,
            PreQuestID = 210129,
            PrepassEntID = 1205022,
            Priority = 50,
            RecruitID = 615,
            _RewardCnt = CS._6_1,
            _Rewards = CS._8_1,
            _WeeklyItem = '[66700205]',
            _WeeklyItemCnt = CS._10_1,
            ZeroFormPriority = 3,
            ZeroFormWeeklyCounter = 1300,
        },
        {
            BG = CS._1_10,
            BackgroudImageIcon = CS._2_12,
            Counter = 21700,
            Explain = CS._3_1,
            ID = 1205021,
            _InitialRewardCnt = CS._4_1,
            MatchTimeoutGuideRecruitID = 606,
            PreQuestID = 210144,
            Priority = 41,
            RecruitID = 606,
            _RewardCnt = CS._6_7,
            _RewardPropIndex = CS._7_2,
            _Rewards = '[19000101,19000102,61500044]',
        },
        {
            BG = CS._1_11,
            BackgroudImageIcon = CS._2_13,
            Counter = 22000,
            Explain = CS._3_4,
            HelpInfoID = 1000006,
            ID = 1205022,
            _InitialRewardCnt = CS._4_1,
            MatchTimeoutGuideRecruitID = 614,
            PreQuestID = 210129,
            PrepassEntID = 1205016,
            Priority = 49,
            RecruitID = 614,
            _RewardCnt = CS._6_1,
            _Rewards = CS._8_1,
            _WeeklyItem = '[66700204]',
            _WeeklyItemCnt = CS._10_1,
            ZeroFormPriority = 2,
            ZeroFormWeeklyCounter = 1200,
        },
        {
            BG = CS._1_11,
            BackgroudImageIcon = CS._2_13,
            Counter = 22000,
            Explain = CS._3_4,
            ID = 1205023,
            _InitialRewardCnt = CS._4_1,
            MatchTimeoutGuideRecruitID = 605,
            PreQuestID = 210142,
            Priority = 40,
            RecruitID = 605,
            _RewardCnt = CS._6_1,
            _Rewards = CS._8_1,
        },
        {
            BG = CS._1_1,
            BackgroudImageIcon = CS._2_1,
            Counter = 21700,
            Explain = CS._3_1,
            HasChallenge = 0,
            HelpInfoID = 1000007,
            ID = 1205024,
            _InitialRewards = CS._5_1,
            MatchTimeoutGuideRecruitID = 612,
            PreQuestID = 270067,
            PrepassEntID = 1205013,
            Priority = 47,
            RecruitID = 612,
            _RewardCnt = '[200]',
            _Rewards = '[19000101]',
            bBattlePWorld = 1,
        },
        {
            BG = 'Texture2D\'/Game/UI/Texture/PWorld/BG/Details/UI_PWorld_BG_Details_SJTGDRMG.UI_PWorld_BG_Details_SJTGDRMG\'',
            BackgroudImageIcon = 'Texture2D\'/Game/UI/Texture/PWorld/Banner/UI_PWorld_Banner_PWorldList_20.UI_PWorld_Banner_PWorldList_20\'',
            Counter = 21700,
            Explain = CS._3_1,
            ID = 1206001,
            _InitialRewardCnt = CS._4_2,
            MatchTimeoutGuideRecruitID = 500,
            PreQuestID = 150938,
            Priority = 32,
            RecruitID = 500,
            _RewardCnt = '[70,70,25,1,1,1]',
            _RewardPropIndex = '[4,5,6]',
            _Rewards = '[19000100,19000101,19000102,61400119,61500035,61500036]',
        },
        {
            BG = CS._1_12,
            BackgroudImageIcon = CS._2_14,
            Counter = 22000,
            Explain = CS._3_4,
            ID = 1206002,
            _InitialRewardCnt = CS._4_1,
            MatchTimeoutGuideRecruitID = 609,
            PreQuestID = 210127,
            Priority = 44,
            RecruitID = 609,
            _RewardCnt = CS._6_3,
            _Rewards = '[19000101,19000102,66700200]',
        },
        {
            BG = CS._1_12,
            BackgroudImageIcon = CS._2_14,
            Counter = 22000,
            Explain = CS._3_4,
            ID = 1206003,
            _InitialRewardCnt = CS._4_1,
            MatchTimeoutGuideRecruitID = 601,
            PreQuestID = 210132,
            Priority = 36,
            RecruitID = 601,
            _RewardCnt = CS._6_7,
            _RewardPropIndex = CS._7_2,
            _Rewards = '[19000101,19000102,61500042]',
        },
        {
            BG = 'Texture2D\'/Game/UI/Texture/PWorld/BG/Details/UI_PWorld_BG_Details_SJTXEKST.UI_PWorld_BG_Details_SJTXEKST\'',
            BackgroudImageIcon = 'Texture2D\'/Game/UI/Texture/PWorld/Banner/UI_PWorld_Banner_PWorldList_19.UI_PWorld_Banner_PWorldList_19\'',
            Counter = 21700,
            Explain = CS._3_1,
            ID = 1206004,
            _InitialRewardCnt = CS._4_2,
            MatchTimeoutGuideRecruitID = 501,
            PreQuestID = 150947,
            Priority = 33,
            RecruitID = 501,
            _RewardCnt = '[70,70,25,4,1,1,1,1,1]',
            _RewardPropIndex = '[5,6,7,8,9]',
            _Rewards = '[19000100,19000101,19000102,66700194,61400122,61500218,61500038,61500037,61800092]',
        },
        {
            BG = 'Texture2D\'/Game/UI/Texture/PWorld/BG/Details/UI_PWorld_BG_Details_SJTAZSJ.UI_PWorld_BG_Details_SJTAZSJ\'',
            BackgroudImageIcon = 'Texture2D\'/Game/UI/Texture/PWorld/Banner/UI_PWorld_Banner_PWorldList_21.UI_PWorld_Banner_PWorldList_21\'',
            Counter = 21700,
            Explain = CS._3_1,
            ID = 1206005,
            _InitialRewardCnt = CS._4_2,
            MatchTimeoutGuideRecruitID = 502,
            PreQuestID = 150954,
            Priority = 34,
            RecruitID = 502,
            _RewardCnt = '[70,70,25,4,1,1,1,1]',
            _RewardPropIndex = '[5,6,7,8]',
            _Rewards = '[19000100,19000101,19000102,66700198,61400127,61500039,61500040,61800101]',
        },
        {
            AttackProfNum = 2,
            BG = 'Texture2D\'/Game/UI/Texture/PWorld/BG/Details/UI_PWorld_BG_Details_XYSD.UI_PWorld_BG_Details_XYSD\'',
            BackgroudImageIcon = 'Texture2D\'/Game/UI/Texture/PWorld/Banner/UI_PWorld_Banner_PWorldList_16.UI_PWorld_Banner_PWorldList_16\'',
            Counter = 20800,
            Explain = '信息\
限制时间：90分钟/布雷福洛克斯野营地\
\
参加条件\
人数要求：1~4人战斗职业（防护职业：1/治疗职业：1/进攻职业：2）\
参与等级：30级，超过等级上限时会自动进行等级同步\
装备品级：平均品级不低于1级，且品级同步70级\
\
※在品级同步状态下，所有的装备性能都会下调至对应品级的规格。\
※4人数组队时可以以任何职业构成参加，且不会受到装备品级限制。',
            GuardProfNum = 1,
            HasUnlimited = 1,
            HelpInfoID = 1000003,
            ID = 1211002,
            _InitialRewardCnt = CS._4_2,
            _InitialRewards = CS._5_2,
            MatchTimeoutGuideTime = 120,
            MatchTimeoutGuideType = 1,
            NurseProfNum = 1,
            PreQuestID = 160370,
            Priority = 9,
            RecruitID = 106,
            _RewardCnt = CS._6_2,
            _RewardPropIndex = CS._7_1,
            _Rewards = '[19000100,66700183,61500555,61800451]',
            TypeID = 2,
        },
        {
            AttackProfNum = 2,
            BG = 'Texture2D\'/Game/UI/Texture/PWorld/BG/Details/UI_PWorld_BG_Details_DLC.UI_PWorld_BG_Details_DLC\'',
            BackgroudImageIcon = 'Texture2D\'/Game/UI/Texture/PWorld/Banner/UI_PWorld_Banner_PWorldList_31.UI_PWorld_Banner_PWorldList_31\'',
            Counter = 20900,
            Explain = '信息\
限制时间：90分钟/石卫塔\
\
参加条件\
人数要求：1~4人战斗职业（防护职业：1/治疗职业：1/进攻职业：2）\
参与等级：40级，超过等级上限时会自动进行等级同步\
装备品级：平均品级不低于1级，且品级同步95级\
\
※在品级同步状态下，所有的装备性能都会下调至对应品级的规格。\
※4人数组队时可以以任何职业构成参加，且不会受到装备品级限制。',
            GuardProfNum = 1,
            HasUnlimited = 1,
            HelpInfoID = 1000003,
            ID = 1211003,
            _InitialRewardCnt = CS._4_2,
            _InitialRewards = CS._5_2,
            MatchTimeoutGuideTime = 120,
            MatchTimeoutGuideType = 1,
            NurseProfNum = 1,
            PreQuestID = 140481,
            Priority = 11,
            RecruitID = 108,
            _RewardCnt = CS._6_2,
            _RewardPropIndex = CS._7_1,
            _Rewards = '[19000100,66700184,61400026,61500571]',
            TypeID = 2,
        },
        {
            AttackProfNum = 2,
            BG = 'Texture2D\'/Game/UI/Texture/PWorld/BG/Details/UI_PWorld_BG_Details_TMMDC.UI_PWorld_BG_Details_TMMDC\'',
            BackgroudImageIcon = 'Texture2D\'/Game/UI/Texture/PWorld/Banner/UI_PWorld_Banner_PWorldList_17.UI_PWorld_Banner_PWorldList_17\'',
            Counter = 21100,
            Explain = CS._3_5,
            GuardProfNum = 1,
            HelpInfoID = 1000005,
            ID = 1211004,
            _InitialRewardCnt = '[350]',
            MatchTimeoutGuideTime = 120,
            MatchTimeoutGuideType = 1,
            NurseProfNum = 1,
            PreQuestID = 180087,
            Priority = 14,
            RecruitID = 111,
            _RewardCnt = '[80,35,1]',
            _RewardPropIndex = CS._7_2,
            _Rewards = '[19000101,19000102,61400064]',
            TypeID = 2,
        },
        {
            AttackProfNum = 2,
            BG = 'Texture2D\'/Game/UI/Texture/PWorld/BG/Details/UI_PWorld_BG_Details_QYFX.UI_PWorld_BG_Details_QYFX\'',
            BackgroudImageIcon = 'Texture2D\'/Game/UI/Texture/PWorld/Banner/UI_PWorld_Banner_PWorldList_24.UI_PWorld_Banner_PWorldList_24\'',
            Counter = 20600,
            Explain = '信息\
限制时间：90分钟/托托·拉克千狱\
\
参加条件\
人数要求：1~4人战斗职业（防护职业：1/治疗职业：1/进攻职业：2）\
参与等级：20级，超过等级上限时会自动进行等级同步\
装备品级：平均品级不低于1级，且品级同步45级\
\
※在品级同步状态下，所有的装备性能都会下调至对应品级的规格。\
※4人数组队时可以以任何职业构成参加，且不会受到装备品级限制。',
            GuardProfNum = 1,
            HasUnlimited = 1,
            HelpInfoID = 1000003,
            ID = 1211005,
            _InitialRewardCnt = CS._4_2,
            _InitialRewards = CS._5_2,
            MatchTimeoutGuideTime = 120,
            MatchTimeoutGuideType = 1,
            NurseProfNum = 1,
            PreQuestID = 160229,
            Priority = 7,
            RecruitID = 104,
            _RewardCnt = CS._6_2,
            _RewardPropIndex = CS._7_1,
            _Rewards = '[19000100,66700182,61500554,61800479]',
            TypeID = 2,
        },
        {
            AttackProfNum = 2,
            BG = 'Texture2D\'/Game/UI/Texture/PWorld/BG/Details/UI_PWorld_BG_Details_MMFDJYZY.UI_PWorld_BG_Details_MMFDJYZY\'',
            BackgroudImageIcon = 'Texture2D\'/Game/UI/Texture/PWorld/Banner/UI_PWorld_Banner_PWorldList_08.UI_PWorld_Banner_PWorldList_08\'',
            Counter = 20700,
            Explain = '信息\
限制时间：90分钟/静语庄园\
\
参加条件\
人数要求：1~4人战斗职业（防护职业：1/治疗职业：1/进攻职业：2）\
参与等级：25级，超过等级上限时会自动进行等级同步\
装备品级：平均品级不低于1级，且品级同步60级\
\
※在品级同步状态下，所有的装备性能都会下调至对应品级的规格。\
※4人数组队时可以以任何职业构成参加，且不会受到装备品级限制。',
            GuardProfNum = 1,
            HasUnlimited = 1,
            HelpInfoID = 1000003,
            ID = 1211006,
            _InitialRewardCnt = CS._4_2,
            _InitialRewards = CS._5_2,
            MatchTimeoutGuideTime = 120,
            MatchTimeoutGuideType = 1,
            NurseProfNum = 1,
            PreQuestID = 160325,
            Priority = 8,
            RecruitID = 105,
            _RewardCnt = CS._6_9,
            _RewardPropIndex = CS._7_4,
            _Rewards = '[19000100,66700182,61400024,61500367,61800480]',
            TypeID = 2,
        },
        {
            AttackProfNum = 2,
            BG = 'Texture2D\'/Game/UI/Texture/PWorld/BG/Details/UI_PWorld_BG_Details_SBYSDGNFB.UI_PWorld_BG_Details_SBYSDGNFB\'',
            BackgroudImageIcon = 'Texture2D\'/Game/UI/Texture/PWorld/Banner/UI_PWorld_Banner_PWorldList_22.UI_PWorld_Banner_PWorldList_22\'',
            Counter = 21000,
            Explain = '信息\
限制时间：90分钟/帝国南方堡\
\
参加条件\
人数要求：1~4人战斗职业（防护职业：1/治疗职业：1/进攻职业：2）\
参与等级：50级，超过等级上限时会自动进行等级同步\
装备品级：平均品级不低于1级，且品级同步115级\
\
※在品级同步状态下，所有的装备性能都会下调至对应品级的规格。\
※4人数组队时可以以任何职业构成参加，且不会受到装备品级限制。',
            GuardProfNum = 1,
            HelpInfoID = 1000005,
            ID = 1211007,
            _InitialRewardCnt = CS._4_1,
            MatchTimeoutGuideTime = 120,
            MatchTimeoutGuideType = 1,
            NurseProfNum = 1,
            PreQuestID = 180097,
            Priority = 13,
            RecruitID = 110,
            _RewardCnt = CS._6_10,
            _RewardPropIndex = CS._7_1,
            _Rewards = '[19000101,19000102,61400031,61700046]',
            TypeID = 2,
        },
        {
            AttackProfNum = 2,
            BG = 'Texture2D\'/Game/UI/Texture/PWorld/BG/Details/UI_PWorld_BG_Details_SSTXRD.UI_PWorld_BG_Details_SSTXRD\'',
            BackgroudImageIcon = 'Texture2D\'/Game/UI/Texture/PWorld/Banner/UI_PWorld_Banner_PWorldList_23.UI_PWorld_Banner_PWorldList_23\'',
            Counter = 20300,
            Explain = CS._3_6,
            GuardProfNum = 1,
            HasUnlimited = 1,
            HelpInfoID = 1000003,
            ID = 1211008,
            _InitialRewardCnt = CS._4_2,
            _InitialRewards = CS._5_2,
            MatchTimeoutGuideTime = 120,
            MatchTimeoutGuideType = 1,
            NurseProfNum = 1,
            PreQuestID = 140313,
            Priority = 3,
            RecruitID = 100,
            _RewardCnt = CS._6_2,
            _RewardPropIndex = CS._7_1,
            _Rewards = '[19000100,66700181,61400018,61500498]',
            TypeID = 2,
        },
        {
            AttackProfNum = 2,
            BG = 'Texture2D\'/Game/UI/Texture/PWorld/BG/Details/UI_PWorld_BG_Details_TMTLMY.UI_PWorld_BG_Details_TMTLMY\'',
            BackgroudImageIcon = 'Texture2D\'/Game/UI/Texture/PWorld/Banner/UI_PWorld_Banner_PWorldList_18.UI_PWorld_Banner_PWorldList_18\'',
            Counter = 20400,
            Explain = '信息\
限制时间：90分钟/塔姆·塔拉墓园\
\
参加条件\
人数要求：1~4人战斗职业（防护职业：1/治疗职业：1/进攻职业：2）\
参与等级：11级，超过等级上限时会自动进行等级同步\
装备品级：平均品级不低于1级，且品级同步20级\
\
※在品级同步状态下，所有的装备性能都会下调至对应品级的规格。\
※4人数组队时可以以任何职业构成参加，且不会受到装备品级限制。',
            GuardProfNum = 1,
            HasUnlimited = 1,
            HelpInfoID = 1000003,
            ID = 1211009,
            _InitialRewardCnt = CS._4_2,
            _InitialRewards = CS._5_2,
            MatchTimeoutGuideTime = 120,
            MatchTimeoutGuideType = 1,
            NurseProfNum = 1,
            PreQuestID = 140319,
            Priority = 4,
            RecruitID = 101,
            _RewardCnt = '[30,1,1]',
            _RewardPropIndex = CS._7_2,
            _Rewards = '[19000100,66700181,61800478]',
            TypeID = 2,
        },
        {
            AttackProfNum = 2,
            BG = 'Texture2D\'/Game/UI/Texture/PWorld/BG/Details/UI_PWorld_BG_Details_FSKDTLTS.UI_PWorld_BG_Details_FSKDTLTS\'',
            BackgroudImageIcon = 'Texture2D\'/Game/UI/Texture/PWorld/Banner/UI_PWorld_Banner_PWorldList_04.UI_PWorld_Banner_PWorldList_04\'',
            Counter = 20500,
            Explain = '信息\
限制时间：90分钟/铜铃铜山\
\
参加条件\
人数要求：1~4人战斗职业（防护职业：1/治疗职业：1/进攻职业：2）\
参与等级：12级，超过等级上限时会自动进行等级同步\
装备品级：平均品级不低于1级，且品级同步20级\
\
※在品级同步状态下，所有的装备性能都会下调至对应品级的规格。\
※4人数组队时可以以任何职业构成参加，且不会受到装备品级限制。',
            GuardProfNum = 1,
            HasUnlimited = 1,
            HelpInfoID = 1000003,
            ID = 1211010,
            _InitialRewardCnt = CS._4_2,
            _InitialRewards = CS._5_2,
            MatchTimeoutGuideTime = 120,
            MatchTimeoutGuideType = 1,
            NurseProfNum = 1,
            PreQuestID = 140326,
            Priority = 5,
            RecruitID = 102,
            _RewardCnt = CS._6_2,
            _RewardPropIndex = CS._7_1,
            _Rewards = '[19000100,66700181,61500429,61800038]',
            TypeID = 2,
        },
        {
            AttackProfNum = 2,
            BG = 'Texture2D\'/Game/UI/Texture/PWorld/BG/Details/UI_PWorld_BG_Details_JJSBPHZZ.UI_PWorld_BG_Details_JJSBPHZZ\'',
            BackgroudImageIcon = 'Texture2D\'/Game/UI/Texture/PWorld/Banner/UI_PWorld_Banner_PWorldList_29.UI_PWorld_Banner_PWorldList_29\'',
            Counter = 21500,
            Explain = CS._3_7,
            GuardProfNum = 1,
            HelpInfoID = 1000005,
            ID = 1211011,
            _InitialRewardCnt = '[150]',
            MatchTimeoutGuideTime = 120,
            MatchTimeoutGuideType = 1,
            NurseProfNum = 1,
            PreQuestID = 180088,
            Priority = 15,
            RecruitID = 112,
            _RewardCnt = '[80,35]',
            _Rewards = CS._8_1,
            TypeID = 2,
        },
        {
            AttackProfNum = 2,
            BG = 'Texture2D\'/Game/UI/Texture/PWorld/BG/Details/UI_PWorld_BG_Details_MSLYRYDXLS.UI_PWorld_BG_Details_MSLYRYDXLS\'',
            BackgroudImageIcon = 'Texture2D\'/Game/UI/Texture/PWorld/Banner/UI_PWorld_Banner_PWorldList_51.UI_PWorld_Banner_PWorldList_51\'',
            Counter = 21100,
            Explain = CS._3_5,
            GuardProfNum = 1,
            HasUnlimited = 1,
            ID = 1211012,
            _InitialRewardCnt = CS._4_2,
            _InitialRewards = CS._5_2,
            MatchTimeoutGuideTime = 120,
            MatchTimeoutGuideType = 1,
            NurseProfNum = 1,
            PreQuestID = 171246,
            Priority = 6,
            RecruitID = 103,
            _RewardCnt = CS._6_2,
            _RewardPropIndex = CS._7_1,
            _Rewards = '[19000100,66700290,61500424,61800360]',
            TypeID = 2,
        },
        {
            AttackProfNum = 2,
            BG = 'Texture2D\'/Game/UI/Texture/PWorld/BG/Details/UI_PWorld_BG_Details_GDYJKEMMST.UI_PWorld_BG_Details_GDYJKEMMST\'',
            BackgroudImageIcon = 'Texture2D\'/Game/UI/Texture/PWorld/Banner/UI_PWorld_Banner_PWorldList_47.UI_PWorld_Banner_PWorldList_47\'',
            Counter = 21100,
            Explain = CS._3_5,
            GuardProfNum = 1,
            HasUnlimited = 1,
            ID = 1211013,
            _InitialRewardCnt = CS._4_2,
            _InitialRewards = CS._5_2,
            MatchTimeoutGuideTime = 120,
            MatchTimeoutGuideType = 1,
            NurseProfNum = 1,
            PreQuestID = 171244,
            Priority = 10,
            RecruitID = 107,
            _RewardCnt = CS._6_2,
            _RewardPropIndex = CS._7_1,
            _Rewards = '[19000100,66700291,61500570,61800447]',
            TypeID = 2,
        },
        {
            AttackProfNum = 2,
            BG = 'Texture2D\'/Game/UI/Texture/PWorld/BG/Details/UI_PWorld_BG_Details_DWDKHJG.UI_PWorld_BG_Details_DWDKHJG\'',
            BackgroudImageIcon = 'Texture2D\'/Game/UI/Texture/PWorld/Banner/UI_PWorld_Banner_PWorldList_46.UI_PWorld_Banner_PWorldList_46\'',
            Counter = 21100,
            Explain = CS._3_5,
            GuardProfNum = 1,
            HasUnlimited = 1,
            ID = 1211014,
            _InitialRewardCnt = CS._4_2,
            _InitialRewards = CS._5_2,
            MatchTimeoutGuideTime = 120,
            MatchTimeoutGuideType = 1,
            NurseProfNum = 1,
            PreQuestID = 171248,
            Priority = 12,
            RecruitID = 109,
            _RewardCnt = CS._6_9,
            _RewardPropIndex = CS._7_4,
            _Rewards = '[19000100,66700292,61400009,61500572,61800012]',
            TypeID = 2,
        },
        {
            AttackProfNum = 0,
            BG = CS._1_13,
            BackgroudImageIcon = CS._2_15,
            Counter = 20300,
            Explain = CS._3_6,
            GuardProfNum = 0,
            HasChallenge = 0,
            HelpInfoID = 1000005,
            ID = 1211015,
            _InitialRewards = CS._5_1,
            MatchTimeoutGuideTime = 0,
            MatchTimeoutGuideType = 0,
            NurseProfNum = 0,
            PreQuestID = 260068,
            Priority = 1,
            RecruitID = 3,
            _RewardCnt = CS._6_11,
            _Rewards = CS._8_3,
            TypeID = 13,
        },
        {
            AttackProfNum = 0,
            BG = CS._1_13,
            BackgroudImageIcon = CS._2_15,
            Counter = 20300,
            Explain = CS._3_6,
            GuardProfNum = 0,
            HasChallenge = 0,
            HelpInfoID = 1000005,
            ID = 1211016,
            _InitialRewards = CS._5_1,
            MatchTimeoutGuideTime = 0,
            MatchTimeoutGuideType = 0,
            NurseProfNum = 0,
            PreQuestID = 260068,
            Priority = 2,
            RecruitID = 3,
            _RewardCnt = CS._6_11,
            _Rewards = CS._8_3,
            TypeID = 13,
        },
        {
            AttackProfNum = 2,
            BG = 'Texture2D\'/Game/UI/Texture/PWorld/BG/Details/UI_PWorld_BG_Details_LLDTPXDBB.UI_PWorld_BG_Details_LLDTPXDBB\'',
            BackgroudImageIcon = 'Texture2D\'/Game/UI/Texture/PWorld/Banner/UI_PWorld_Banner_PWorldList_48.UI_PWorld_Banner_PWorldList_48\'',
            Counter = 21500,
            Explain = CS._3_7,
            GuardProfNum = 1,
            HasUnlimited = 1,
            HelpInfoID = 1000003,
            ID = 1211017,
            _InitialRewardCnt = CS._4_2,
            MatchTimeoutGuideTime = 120,
            MatchTimeoutGuideType = 1,
            NurseProfNum = 1,
            PreQuestID = 160428,
            Priority = 16,
            RecruitID = 113,
            _RewardCnt = CS._6_10,
            _RewardPropIndex = CS._7_1,
            _Rewards = '[19000101,19000102,61400112,61500062]',
            TypeID = 2,
        },
        {
            AttackProfNum = 2,
            BG = 'Texture2D\'/Game/UI/Texture/PWorld/BG/Details/UI_PWorld_BG_Details_HLCHMYZT.UI_PWorld_BG_Details_HLCHMYZT\'',
            BackgroudImageIcon = 'Texture2D\'/Game/UI/Texture/PWorld/Banner/UI_PWorld_Banner_PWorldList_55.UI_PWorld_Banner_PWorldList_55\'',
            Counter = 21500,
            Explain = CS._3_7,
            GuardProfNum = 1,
            HasUnlimited = 1,
            HelpInfoID = 1000003,
            ID = 1211018,
            _InitialRewardCnt = CS._4_2,
            MatchTimeoutGuideTime = 120,
            MatchTimeoutGuideType = 1,
            NurseProfNum = 1,
            PreQuestID = 210107,
            Priority = 17,
            RecruitID = 114,
            _RewardCnt = '[80,1]',
            _RewardPropIndex = '[2]',
            _Rewards = '[19000101,61500102]',
            TypeID = 2,
        },
        {
            AttackProfNum = 0,
            BG = 'Texture2D\'/Game/UI/Texture/PWorld/BG/Details/UI_PWorld_BG_Details_LXNJSTYHA.UI_PWorld_BG_Details_LXNJSTYHA\'',
            BackgroudImageIcon = 'Texture2D\'/Game/UI/Texture/PWorld/Banner/UI_PWorld_Banner_PWorldList_LXNJSTYHA.UI_PWorld_Banner_PWorldList_LXNJSTYHA\'',
            CanMidWay = 0,
            Explain = CS._3_8,
            GuardProfNum = 0,
            HasChallenge = 0,
            HelpInfoID = 0,
            ID = 1216001,
            _InitialRewards = CS._5_1,
            MatchTimeoutGuideTime = 0,
            MatchTimeoutGuideType = 0,
            NurseProfNum = 0,
            Priority = 67,
            PunishmentTime = 0,
            _RewardCnt = CS._6_8,
            _Rewards = CS._8_2,
            TypeID = 5,
        },
        {
            AttackProfNum = 0,
            BG = 'Texture2D\'/Game/UI/Texture/PWorld/BG/Details/UI_PWorld_BG_Details_LXNJSHYDD.UI_PWorld_BG_Details_LXNJSHYDD\'',
            BackgroudImageIcon = 'Texture2D\'/Game/UI/Texture/PWorld/Banner/UI_PWorld_Banner_PWorldList_LXNJSHYDD.UI_PWorld_Banner_PWorldList_LXNJSHYDD\'',
            CanMidWay = 0,
            Explain = CS._3_8,
            GuardProfNum = 0,
            HasChallenge = 0,
            HelpInfoID = 0,
            ID = 1216002,
            _InitialRewards = CS._5_1,
            MatchTimeoutGuideTime = 0,
            MatchTimeoutGuideType = 0,
            NurseProfNum = 0,
            Priority = 68,
            PunishmentTime = 0,
            _RewardCnt = CS._6_8,
            _Rewards = CS._8_2,
            TypeID = 5,
        },
        {
            AttackProfNum = 0,
            BG = 'Texture2D\'/Game/UI/Texture/PWorld/BG/Details/UI_PWorld_BG_Details_LXNJSTJXL.UI_PWorld_BG_Details_LXNJSTJXL\'',
            BackgroudImageIcon = 'Texture2D\'/Game/UI/Texture/PWorld/Banner/UI_PWorld_Banner_PWorldList_LXNJSTJXL.UI_PWorld_Banner_PWorldList_LXNJSTJXL\'',
            CanMidWay = 0,
            Explain = CS._3_8,
            GuardProfNum = 0,
            HasChallenge = 0,
            HelpInfoID = 0,
            ID = 1216003,
            _InitialRewards = CS._5_1,
            MatchTimeoutGuideTime = 0,
            MatchTimeoutGuideType = 0,
            NurseProfNum = 0,
            Priority = 69,
            PunishmentTime = 0,
            _RewardCnt = CS._6_8,
            _Rewards = CS._8_2,
            TypeID = 5,
        },
        {
            AttackProfNum = 0,
            BG = 'Texture2D\'/Game/UI/Texture/PWorld/BG/Match/UI_PWorld_BG_Match_SCBWK.UI_PWorld_BG_Match_SCBWK\'',
            BackgroudImageIcon = 'Texture2D\'/Game/UI/Texture/PWorld/BG/Match/UI_PWorld_BG_Match_SCBWK.UI_PWorld_BG_Match_SCBWK\'',
            CanMidWay = 0,
            Explain = '',
            GuardProfNum = 0,
            HasChallenge = 0,
            HasNormal = 0,
            HelpInfoID = 0,
            ID = 1216014,
            _InitialRewards = CS._5_1,
            MatchTimeoutGuideTime = 0,
            MatchTimeoutGuideType = 0,
            NurseProfNum = 0,
            Priority = 80,
            PunishmentTime = 0,
            TypeID = 12,
        },
        {
            AttackProfNum = 0,
            BG = 'Texture2D\'/Game/UI/Texture/PWorld/BG/Match/UI_PWorld_BG_Match_BWKSD.UI_PWorld_BG_Match_BWKSD\'',
            BackgroudImageIcon = 'Texture2D\'/Game/UI/Texture/PWorld/BG/Match/UI_PWorld_BG_Match_BWKSD.UI_PWorld_BG_Match_BWKSD\'',
            CanMidWay = 0,
            Explain = '',
            GuardProfNum = 0,
            HasChallenge = 0,
            HasNormal = 0,
            HelpInfoID = 0,
            ID = 1216015,
            _InitialRewards = CS._5_1,
            MatchTimeoutGuideTime = 0,
            MatchTimeoutGuideType = 0,
            NurseProfNum = 0,
            Priority = 81,
            PunishmentTime = 0,
            TypeID = 12,
        },
        {
            AttackProfNum = 0,
            BG = 'Texture2D\'/Game/UI/Texture/PWorld/BG/Details/UI_PWorld_BG_Details_SJCTLXSSJ.UI_PWorld_BG_Details_SJCTLXSSJ\'',
            BackgroudImageIcon = CS._2_2,
            CanMidWay = 0,
            Explain = '',
            GuardProfNum = 0,
            HasChallenge = 0,
            HasNormal = 0,
            HelpInfoID = 11162,
            ID = 1218010,
            _InitialRewards = CS._5_1,
            MatchTimeoutGuideTime = 0,
            MatchTimeoutGuideType = 0,
            NurseProfNum = 0,
            PVPAdvanceProfNum = 1,
            Priority = 71,
            _RewardCnt = CS._6_12,
            _Rewards = CS._8_4,
            TypeID = 9,
        },
        {
            AttackProfNum = 0,
            BG = 'Texture3D\'/Game/UI/Texture/PWorld/BG/Details/UI_PWorld_BG_Details_SJCTLXSSJ.UI_PWorld_BG_Details_SJCTLXSSJ\'',
            BackgroudImageIcon = CS._2_2,
            CanMidWay = 0,
            Explain = '',
            GuardProfNum = 0,
            HasChallenge = 0,
            HasNormal = 0,
            HelpInfoID = 11162,
            ID = 1218011,
            _InitialRewards = CS._5_1,
            IsHideInList = 1,
            MatchTimeoutGuideTime = 0,
            MatchTimeoutGuideType = 0,
            NurseProfNum = 0,
            Priority = 72,
            TypeID = 9,
        },
        {
            AttackProfNum = 0,
            BG = 'Texture4D\'/Game/UI/Texture/PWorld/BG/Details/UI_PWorld_BG_Details_SJCTLXSSJ.UI_PWorld_BG_Details_SJCTLXSSJ\'',
            BackgroudImageIcon = CS._2_2,
            CanMidWay = 0,
            Explain = '',
            GuardProfNum = 0,
            HasChallenge = 0,
            HasNormal = 0,
            HelpInfoID = 11162,
            ID = 1218012,
            _InitialRewards = CS._5_1,
            IsHideInList = 1,
            MatchTimeoutGuideTime = 0,
            MatchTimeoutGuideType = 0,
            NurseProfNum = 0,
            Priority = 73,
            TypeID = 9,
        },
        {
            AttackProfNum = 0,
            BG = 'Texture2D\'/Game/UI/Texture/PWorld/BG/Details/UI_PWorld_BG_Details_SJCTLXSSJYW.UI_PWorld_BG_Details_SJCTLXSSJYW\'',
            BackgroudImageIcon = CS._2_3,
            CanMidWay = 0,
            Explain = '',
            GuardProfNum = 0,
            HasChallenge = 0,
            HasNormal = 0,
            HelpInfoID = 11162,
            ID = 1218020,
            _InitialRewards = CS._5_1,
            MatchTimeoutGuideTime = 0,
            MatchTimeoutGuideType = 0,
            NurseProfNum = 0,
            PVPAdvanceProfNum = 1,
            Priority = 74,
            _RewardCnt = CS._6_12,
            _Rewards = CS._8_4,
            TypeID = 10,
        },
        {
            AttackProfNum = 0,
            BG = 'Texture3D\'/Game/UI/Texture/PWorld/BG/Details/UI_PWorld_BG_Details_SJCTLXSSJYW.UI_PWorld_BG_Details_SJCTLXSSJYW\'',
            BackgroudImageIcon = CS._2_3,
            CanMidWay = 0,
            Explain = '',
            GuardProfNum = 0,
            HasChallenge = 0,
            HasNormal = 0,
            HelpInfoID = 11162,
            ID = 1218021,
            _InitialRewards = CS._5_1,
            IsHideInList = 1,
            MatchTimeoutGuideTime = 0,
            MatchTimeoutGuideType = 0,
            NurseProfNum = 0,
            Priority = 75,
            TypeID = 10,
        },
        {
            AttackProfNum = 0,
            BG = 'Texture4D\'/Game/UI/Texture/PWorld/BG/Details/UI_PWorld_BG_Details_SJCTLXSSJYW.UI_PWorld_BG_Details_SJCTLXSSJYW\'',
            BackgroudImageIcon = CS._2_3,
            CanMidWay = 0,
            Explain = '',
            GuardProfNum = 0,
            HasChallenge = 0,
            HasNormal = 0,
            HelpInfoID = 11162,
            ID = 1218022,
            _InitialRewards = CS._5_1,
            IsHideInList = 1,
            MatchTimeoutGuideTime = 0,
            MatchTimeoutGuideType = 0,
            NurseProfNum = 0,
            Priority = 76,
            TypeID = 10,
        },
        {
            AttackProfNum = 0,
            BG = 'Texture2D\'/Game/UI/Texture/PWorld/BG/Details/UI_PWorld_BG_Details_PVPSJCTZDSJLXX.UI_PWorld_BG_Details_PVPSJCTZDSJLXX\'',
            BackgroudImageIcon = 'Texture2D\'/Game/UI/Texture/PWorld/Banner/UI_PWorld_Banner_PWorldList_41.UI_PWorld_Banner_PWorldList_41\'',
            CanMidWay = 0,
            Explain = '',
            GuardProfNum = 0,
            HasChallenge = 0,
            HasNormal = 0,
            HelpInfoID = 11162,
            ID = 1218030,
            _InitialRewards = CS._5_1,
            IsHideInList = 1,
            MatchTimeoutGuideTime = 0,
            MatchTimeoutGuideType = 0,
            NurseProfNum = 0,
            PVPAdvanceProfNum = 1,
            Priority = 77,
            PunishmentTime = 0,
            TypeID = 11,
        },
        {
            AttackProfNum = 0,
            BG = 'Texture2D\'/Game/UI/Texture/PWorld/BG/Details/UI_PWorld_BG_Details_SJCTZDSHSZX.UI_PWorld_BG_Details_SJCTZDSHSZX\'',
            BackgroudImageIcon = 'Texture2D\'/Game/UI/Texture/PWorld/Banner/UI_PWorld_Banner_PWorldList_39.UI_PWorld_Banner_PWorldList_39\'',
            CanMidWay = 0,
            Explain = '',
            GuardProfNum = 0,
            HasChallenge = 0,
            HasNormal = 0,
            HelpInfoID = 11162,
            ID = 1218031,
            _InitialRewards = CS._5_1,
            IsHideInList = 1,
            MatchTimeoutGuideTime = 0,
            MatchTimeoutGuideType = 0,
            NurseProfNum = 0,
            PVPAdvanceProfNum = 1,
            Priority = 78,
            PunishmentTime = 0,
            TypeID = 11,
        },
        {
            AttackProfNum = 0,
            BG = 'Texture2D\'/Game/UI/Texture/PWorld/BG/Details/UI_PWorld_BG_Details_SJCTZDSJXYS.UI_PWorld_BG_Details_SJCTZDSJXYS\'',
            BackgroudImageIcon = 'Texture2D\'/Game/UI/Texture/PWorld/Banner/UI_PWorld_Banner_PWorldList_40.UI_PWorld_Banner_PWorldList_40\'',
            CanMidWay = 0,
            Explain = '',
            GuardProfNum = 0,
            HasChallenge = 0,
            HasNormal = 0,
            HelpInfoID = 11162,
            ID = 1218032,
            _InitialRewards = CS._5_1,
            IsHideInList = 1,
            MatchTimeoutGuideTime = 0,
            MatchTimeoutGuideType = 0,
            NurseProfNum = 0,
            PVPAdvanceProfNum = 1,
            Priority = 79,
            PunishmentTime = 0,
            TypeID = 11,
        },
        {
            AttackProfNum = 0,
            CanMidWay = 0,
            GuardProfNum = 0,
            HasChallenge = 0,
            HasNormal = 0,
            HelpInfoID = 11052,
            ID = 1230041,
            _InitialRewards = CS._5_1,
            MatchTimeoutGuideTime = 0,
            MatchTimeoutGuideType = 0,
            NurseProfNum = 0,
            PreQuestID = 171152,
            Priority = 52,
            PunishmentTime = 0,
            SPID = 533,
            TypeID = 7,
        },
        {
            AttackProfNum = 0,
            CanMidWay = 0,
            GuardProfNum = 0,
            HasChallenge = 0,
            HasNormal = 0,
            HelpInfoID = 11052,
            ID = 1230051,
            _InitialRewards = CS._5_1,
            MatchTimeoutGuideTime = 0,
            MatchTimeoutGuideType = 0,
            NurseProfNum = 0,
            PreQuestID = 220005,
            Priority = 53,
            PunishmentTime = 0,
            SPID = 534,
            TypeID = 7,
        },
        {
            AttackProfNum = 0,
            CanMidWay = 0,
            GuardProfNum = 0,
            HasChallenge = 0,
            HasNormal = 0,
            HelpInfoID = 11052,
            ID = 1230052,
            _InitialRewards = CS._5_1,
            MatchTimeoutGuideTime = 0,
            MatchTimeoutGuideType = 0,
            NurseProfNum = 0,
            PreQuestID = 210126,
            Priority = 54,
            PunishmentTime = 0,
            SPID = 535,
            TypeID = 7,
        },
        {
            AttackProfNum = 0,
            CanMidWay = 0,
            GuardProfNum = 0,
            HasChallenge = 0,
            HasNormal = 0,
            HelpInfoID = 11052,
            ID = 1230053,
            _InitialRewards = CS._5_1,
            MatchTimeoutGuideTime = 0,
            MatchTimeoutGuideType = 0,
            NurseProfNum = 0,
            PreQuestID = 210128,
            Priority = 57,
            PunishmentTime = 0,
            SPID = 536,
            TypeID = 7,
        },
        {
            AttackProfNum = 0,
            CanMidWay = 0,
            GuardProfNum = 0,
            HasChallenge = 0,
            HasNormal = 0,
            HelpInfoID = 11052,
            ID = 1230054,
            _InitialRewards = CS._5_1,
            MatchTimeoutGuideTime = 0,
            MatchTimeoutGuideType = 0,
            NurseProfNum = 0,
            PreQuestID = 210128,
            Priority = 58,
            PunishmentTime = 0,
            SPID = 537,
            TypeID = 7,
        },
        {
            AttackProfNum = 0,
            CanMidWay = 0,
            GuardProfNum = 0,
            HasChallenge = 0,
            HasNormal = 0,
            HelpInfoID = 11052,
            ID = 1230055,
            _InitialRewards = CS._5_1,
            MatchTimeoutGuideTime = 0,
            MatchTimeoutGuideType = 0,
            NurseProfNum = 0,
            PreQuestID = 210127,
            Priority = 55,
            PunishmentTime = 0,
            SPID = 538,
            TypeID = 7,
        },
        {
            AttackProfNum = 0,
            CanMidWay = 0,
            GuardProfNum = 0,
            HasChallenge = 0,
            HasNormal = 0,
            HelpInfoID = 11052,
            ID = 1230056,
            _InitialRewards = CS._5_1,
            MatchTimeoutGuideTime = 0,
            MatchTimeoutGuideType = 0,
            NurseProfNum = 0,
            PreQuestID = 210127,
            Priority = 56,
            PunishmentTime = 0,
            SPID = 539,
            TypeID = 7,
        },
        {
            AttackProfNum = 0,
            BG = '',
            BackgroudImageIcon = '',
            CanMidWay = 0,
            Explain = '',
            GuardProfNum = 0,
            HasChallenge = 0,
            HasNormal = 0,
            HelpInfoID = 0,
            ID = 1230057,
            _InitialRewards = CS._5_1,
            MatchTimeoutGuideTime = 0,
            MatchTimeoutGuideType = 0,
            NurseProfNum = 0,
            PreQuestID = 900001,
            Priority = 59,
            PunishmentTime = 0,
            TypeID = 0,
        },
        {
            AttackProfNum = 0,
            CanMidWay = 0,
            GuardProfNum = 0,
            HasChallenge = 0,
            HasNormal = 0,
            HelpInfoID = 11052,
            ID = 1230058,
            _InitialRewards = CS._5_1,
            MatchTimeoutGuideTime = 0,
            MatchTimeoutGuideType = 0,
            NurseProfNum = 0,
            PreQuestID = 160038,
            Priority = 60,
            PunishmentTime = 0,
            SPID = 567,
            TypeID = 7,
        },
        {
            AttackProfNum = 0,
            CanMidWay = 0,
            GuardProfNum = 0,
            HasChallenge = 0,
            HasNormal = 0,
            HelpInfoID = 11052,
            ID = 1230102,
            _InitialRewards = CS._5_1,
            MatchTimeoutGuideTime = 0,
            MatchTimeoutGuideType = 0,
            NurseProfNum = 0,
            PreQuestID = 160039,
            Priority = 61,
            PunishmentTime = 0,
            SPID = 568,
            TypeID = 7,
        },
        {
            AttackProfNum = 0,
            CanMidWay = 0,
            GuardProfNum = 0,
            HasChallenge = 0,
            HasNormal = 0,
            HelpInfoID = 11052,
            ID = 1230103,
            _InitialRewards = CS._5_1,
            MatchTimeoutGuideTime = 0,
            MatchTimeoutGuideType = 0,
            NurseProfNum = 0,
            PreQuestID = 160414,
            Priority = 62,
            PunishmentTime = 0,
            SPID = 569,
            TypeID = 7,
        },
        {
            AttackProfNum = 0,
            CanMidWay = 0,
            GuardProfNum = 0,
            HasChallenge = 0,
            HasNormal = 0,
            HelpInfoID = 11052,
            ID = 1230104,
            _InitialRewards = CS._5_1,
            MatchTimeoutGuideTime = 0,
            MatchTimeoutGuideType = 0,
            NurseProfNum = 0,
            PreQuestID = 210129,
            Priority = 63,
            PunishmentTime = 0,
            SPID = 570,
            TypeID = 7,
        },
        {
            AttackProfNum = 0,
            CanMidWay = 0,
            GuardProfNum = 0,
            HasChallenge = 0,
            HasNormal = 0,
            HelpInfoID = 11052,
            ID = 1230105,
            _InitialRewards = CS._5_1,
            MatchTimeoutGuideTime = 0,
            MatchTimeoutGuideType = 0,
            NurseProfNum = 0,
            PreQuestID = 210129,
            Priority = 64,
            PunishmentTime = 0,
            SPID = 571,
            TypeID = 7,
        },
        {
            AttackProfNum = 0,
            CanMidWay = 0,
            GuardProfNum = 0,
            HasChallenge = 0,
            HasNormal = 0,
            HelpInfoID = 11052,
            ID = 1230106,
            _InitialRewards = CS._5_1,
            MatchTimeoutGuideTime = 0,
            MatchTimeoutGuideType = 0,
            NurseProfNum = 0,
            PreQuestID = 210129,
            Priority = 65,
            PunishmentTime = 0,
            SPID = 572,
            TypeID = 7,
        },
        {
            AttackProfNum = 0,
            CanMidWay = 0,
            GuardProfNum = 0,
            HasChallenge = 0,
            HasNormal = 0,
            HelpInfoID = 11052,
            ID = 1230107,
            _InitialRewards = CS._5_1,
            MatchTimeoutGuideTime = 0,
            MatchTimeoutGuideType = 0,
            NurseProfNum = 0,
            PreQuestID = 210129,
            Priority = 66,
            PunishmentTime = 0,
            SPID = 573,
            TypeID = 7,
        },
	},
}

setmetatable(SceneEnterCfg, { __index = CfgBase })

SceneEnterCfg:InitCfg()

-- AUTO GENERATED CODE END, PLEASE DON'T MODIFY

---获取副本进入前置任务ID
---@param ID number @副本入口ID
---@return number
function SceneEnterCfg:GetPreQuestID( ID )
	local Cfg = self:FindCfgByKey(ID)
	if nil == Cfg then 
		return 
	end

	return Cfg.PreQuestID
end

return SceneEnterCfg
