-- AUTO GENERATED CODE BEGIN, PLEASE DON'T MODIFY

local CfgBase = require("TableCfg/CfgBase")

local CS = {
    _1_1 = '4010',
    _1_2 = '4',
    _1_3 = '4005',
    _1_4 = '35',
    _1_5 = '179',
    _1_6 = '4003',
    _1_7 = '42',
    _1_8 = '15&24',
    _1_9 = '43',
    _1_10 = '4009',
    _1_11 = '24&70',
    _1_12 = '4004',
    _1_13 = '1',
    _1_14 = '41',
    _1_15 = '4008',
    _1_16 = '4015',
    _1_17 = '128',
    _1_18 = '4002',
    _1_19 = '15',
    _1_20 = '16',
    _1_21 = '18',
    _1_22 = '25',
    _1_23 = '34',
    _1_24 = '38&24',
    _1_25 = '38',
    _1_26 = '16&24',
    _1_27 = '59',
    _1_28 = '1135',
    _1_29 = '1141',
    _1_30 = '43&179',
    _1_31 = '99|100',
    _1_32 = '170',
    _1_33 = '208',
    _1_34 = '4001',
    _1_35 = '5101',
    _1_36 = '15&6006',
    _1_37 = '6008|6009|6010',
    _1_38 = '180',
    _1_39 = '7696',
    _1_40 = '7696&35',
    _1_41 = '7499&35',
    _1_42 = '7505',
    _1_43 = '9159&9160&9158&9212',
    _1_44 = '9166',
    _1_45 = '9199&9200&9201',
    _1_46 = '9257&9258&9259&9268&9269&9270',
}

---@class SkillTargetSelectCfg : CfgBase
local SkillTargetSelectCfg = {
	TableName = "c_skill_target_select_cfg",
    LruKeyType = nil,
	KeyName = "ID",
    bEncrypted = false,
	Localization = {
        Config = {}
    },
    DefaultValues = {
        Attr = 0,
        ConditionExpr = '',
        ConditionList = '0',
        ID = 1,
        SelectCount = 1,
        SelectFunc = 3,
        SelectType = 1,
        SkillFillterTargetType = 1,
        SkillRelationType = 8,
    },
	LuaData = {
        {
            ConditionExpr = CS._1_13,
            SelectFunc = 2,
        },
        {
            ID = 2,
            SelectFunc = 0,
            SelectType = 0,
            SkillRelationType = 1,
        },
        {
            ConditionExpr = CS._1_2,
            ID = 3,
            SelectCount = 40,
            SelectFunc = 2,
        },
        {
            ConditionExpr = '3',
            ID = 4,
            SelectCount = 2,
            SelectType = 2,
        },
        {
            ConditionExpr = CS._1_2,
            ID = 5,
            SelectCount = 8,
        },
        {
            ConditionExpr = CS._1_2,
            ID = 6,
            SelectCount = 2,
            SelectFunc = 2,
            SkillRelationType = 16,
        },
        {
            ConditionExpr = '8&9',
            ID = 7,
            SelectFunc = 2,
            SkillRelationType = 1,
        },
        {
            ConditionExpr = CS._1_19,
            ID = 8,
            SelectFunc = 2,
        },
        {
            ConditionExpr = CS._1_20,
            ID = 9,
            SelectFunc = 2,
        },
        {
            ConditionExpr = CS._1_2,
            ID = 10,
            SelectCount = 10,
            SelectFunc = 2,
            SkillRelationType = 17,
        },
        {
            ConditionExpr = CS._1_21,
            ID = 11,
            SelectFunc = 2,
        },
        {
            ConditionExpr = '15&20',
            ID = 12,
            SelectType = 2,
        },
        {
            ConditionExpr = CS._1_2,
            ID = 13,
        },
        {
            ConditionExpr = '21',
            ID = 14,
            SelectType = 2,
        },
        {
            ConditionExpr = CS._1_2,
            ID = 15,
            SelectFunc = 1,
            SelectType = 2,
        },
        {
            ConditionExpr = CS._1_4,
            ID = 16,
            SelectType = 2,
        },
        {
            ConditionExpr = CS._1_8,
            ID = 17,
            SelectFunc = 2,
            SkillRelationType = 2,
        },
        {
            ConditionExpr = CS._1_20,
            ID = 18,
            SelectCount = 40,
            SelectFunc = 2,
        },
        {
            ConditionExpr = CS._1_21,
            ID = 19,
            SelectCount = 40,
            SelectFunc = 2,
        },
        {
            ConditionExpr = CS._1_22,
            ID = 20,
        },
        {
            ConditionExpr = '26',
            ID = 21,
            SelectFunc = 0,
            SelectType = 0,
        },
        {
            ConditionExpr = CS._1_8,
            ID = 22,
            SelectCount = 40,
            SelectFunc = 2,
            SkillRelationType = 17,
        },
        {
            ConditionExpr = CS._1_19,
            ID = 23,
            SelectCount = 40,
            SelectFunc = 2,
        },
        {
            ConditionExpr = CS._1_2,
            ID = 24,
        },
        {
            ConditionExpr = '33',
            ID = 25,
        },
        {
            ConditionExpr = CS._1_23,
            ID = 26,
            SelectFunc = 2,
            SelectType = 11,
            SkillRelationType = 3,
        },
        {
            Attr = 101,
            ConditionExpr = '37&67',
            ID = 27,
            SelectFunc = 2,
            SelectType = 3,
            SkillRelationType = 2,
        },
        {
            ConditionExpr = CS._1_24,
            ID = 28,
            SelectCount = 8,
            SelectFunc = 2,
            SkillRelationType = 17,
        },
        {
            ConditionExpr = CS._1_7,
            ID = 29,
        },
        {
            ConditionExpr = CS._1_14,
            ID = 30,
        },
        {
            ConditionExpr = CS._1_9,
            ID = 31,
        },
        {
            ConditionExpr = '46',
            ID = 32,
            SelectFunc = 0,
            SelectType = 0,
        },
        {
            ConditionExpr = '48&252',
            ID = 33,
            SelectFunc = 0,
            SelectType = 0,
            SkillFillterTargetType = 2,
            SkillRelationType = 4,
        },
        {
            ConditionExpr = CS._1_25,
            ID = 34,
            SelectCount = 3,
            SelectFunc = 0,
            SelectType = 0,
            SkillRelationType = 2,
        },
        {
            ConditionExpr = CS._1_26,
            ID = 35,
            SelectCount = 8,
            SelectFunc = 2,
            SkillRelationType = 16,
        },
        {
            ConditionExpr = CS._1_27,
            ID = 36,
            SelectCount = 40,
            SelectFunc = 2,
        },
        {
            ConditionExpr = CS._1_27,
            ID = 37,
            SelectFunc = 2,
        },
        {
            ID = 38,
            SelectFunc = 2,
            SkillRelationType = 16,
        },
        {
            ConditionExpr = CS._1_26,
            ID = 39,
            SelectCount = 8,
            SelectFunc = 2,
            SkillRelationType = 17,
        },
        {
            ConditionExpr = CS._1_2,
            ID = 40,
            SelectFunc = 2,
        },
        {
            ConditionExpr = CS._1_4,
            ID = 41,
            SelectCount = 5,
        },
        {
            ConditionExpr = CS._1_13,
            ID = 42,
            SelectFunc = 2,
            SkillRelationType = 17,
        },
        {
            ConditionExpr = CS._1_11,
            ID = 43,
            SelectCount = 40,
            SelectFunc = 2,
            SkillRelationType = 3,
        },
        {
            ConditionExpr = '6002',
            ID = 44,
            SkillRelationType = 255,
        },
        {
            ConditionExpr = CS._1_8,
            ID = 45,
            SelectCount = 40,
            SelectFunc = 2,
            SkillRelationType = 16,
        },
        {
            ConditionExpr = '34&39',
            ID = 46,
            SelectFunc = 2,
            SelectType = 11,
            SkillRelationType = 17,
        },
        {
            ConditionExpr = CS._1_25,
            ID = 47,
            SelectFunc = 2,
        },
        {
            ConditionExpr = '90',
            ID = 48,
            SelectCount = 40,
            SelectFunc = 2,
        },
        {
            ConditionExpr = CS._1_13,
            ID = 49,
            SelectFunc = 2,
            SkillRelationType = 16,
        },
        {
            ConditionExpr = CS._1_8,
            ID = 50,
            SelectCount = 8,
            SelectFunc = 2,
            SkillRelationType = 17,
        },
        {
            ConditionExpr = '70&24',
            ID = 51,
            SelectCount = 8,
            SelectFunc = 2,
            SkillRelationType = 49,
        },
        {
            ConditionExpr = '35&9007',
            ID = 52,
        },
        {
            ConditionExpr = '96&97&98&179',
            ID = 53,
            SelectFunc = 2,
            SkillRelationType = 2,
        },
        {
            ConditionExpr = '100',
            ID = 54,
            SelectCount = 100,
        },
        {
            ConditionExpr = '7162&7163&7164&7165&7166&7167&7168&7169&35',
            ID = 55,
            SelectType = 2,
        },
        {
            ConditionExpr = '1007',
            ID = 56,
        },
        {
            ConditionExpr = '1008',
            ID = 57,
        },
        {
            ConditionExpr = '1009',
            ID = 58,
        },
        {
            ConditionExpr = '1010',
            ID = 59,
        },
        {
            ConditionExpr = '7162&7163&7164&7165&7166&7167&7168&7169',
            ID = 60,
            SelectType = 2,
        },
        {
            ConditionExpr = '37&260&204',
            ID = 61,
            SkillRelationType = 2,
        },
        {
            ConditionExpr = CS._1_28,
            ID = 62,
            SelectFunc = 2,
        },
        {
            ConditionExpr = '1136',
            ID = 63,
            SelectFunc = 2,
        },
        {
            ID = 64,
            SelectFunc = 2,
            SkillRelationType = 16,
        },
        {
            ConditionExpr = CS._1_28,
            ID = 65,
            SelectCount = 10,
            SelectFunc = 2,
        },
        {
            ConditionExpr = CS._1_29,
            ID = 66,
            SelectFunc = 2,
        },
        {
            ConditionExpr = CS._1_29,
            ID = 67,
            SelectCount = 10,
            SelectFunc = 2,
        },
        {
            ConditionExpr = '6003',
            ID = 68,
            SkillRelationType = 255,
        },
        {
            ConditionExpr = CS._1_7,
            ID = 69,
            SelectCount = 2,
        },
        {
            ConditionExpr = '124&179',
            ID = 70,
            SelectCount = 4,
            SkillRelationType = 2,
        },
        {
            ConditionExpr = CS._1_8,
            ID = 71,
            SelectCount = 8,
            SelectFunc = 2,
            SkillRelationType = 16,
        },
        {
            ConditionExpr = CS._1_24,
            ID = 72,
            SelectCount = 8,
            SelectFunc = 2,
            SkillRelationType = 16,
        },
        {
            ConditionExpr = CS._1_17,
            ID = 73,
            SelectFunc = 2,
        },
        {
            ConditionExpr = '131',
            ID = 74,
            SelectCount = 40,
            SelectFunc = 2,
        },
        {
            ConditionExpr = CS._1_17,
            ID = 75,
            SelectCount = 40,
            SelectFunc = 2,
        },
        {
            ConditionExpr = '41&179',
            ID = 76,
            SkillRelationType = 2,
        },
        {
            ConditionExpr = CS._1_30,
            ID = 77,
            SkillRelationType = 2,
        },
        {
            ConditionExpr = '42&179',
            ID = 78,
            SelectCount = 2,
            SkillRelationType = 2,
        },
        {
            ConditionExpr = CS._1_5,
            ID = 79,
            SelectCount = 5,
        },
        {
            ConditionExpr = '135&179',
            ID = 80,
            SelectCount = 4,
            SkillRelationType = 2,
        },
        {
            ConditionExpr = '35&9118',
            ID = 81,
        },
        {
            ConditionExpr = '260&24',
            ID = 82,
            SelectCount = 40,
            SelectFunc = 2,
            SkillRelationType = 49,
        },
        {
            ConditionExpr = CS._1_4,
            ID = 83,
        },
        {
            ConditionExpr = '152',
            ID = 84,
            SelectFunc = 2,
            SelectType = 11,
            SkillRelationType = 3,
        },
        {
            ConditionExpr = '1&42',
            ID = 85,
            SelectFunc = 2,
            SkillRelationType = 16,
        },
        {
            ConditionExpr = '1&41',
            ID = 86,
            SelectFunc = 2,
            SkillRelationType = 16,
        },
        {
            ConditionExpr = '1&43',
            ID = 87,
            SelectFunc = 2,
            SkillRelationType = 16,
        },
        {
            ConditionExpr = CS._1_31,
            ID = 99,
            SelectCount = 10,
            SelectFunc = 2,
            SkillFillterTargetType = 6,
            SkillRelationType = 255,
        },
        {
            ConditionExpr = CS._1_2,
            ID = 100,
            SelectCount = 100,
            SelectFunc = 2,
        },
        {
            ConditionExpr = '101',
            ID = 101,
            SelectCount = 10,
        },
        {
            ConditionExpr = '102',
            ID = 102,
            SelectCount = 10,
        },
        {
            ConditionExpr = '103',
            ID = 103,
            SelectCount = 10,
        },
        {
            ConditionExpr = '104',
            ID = 104,
            SelectCount = 10,
        },
        {
            ConditionExpr = '105',
            ID = 105,
            SelectCount = 10,
        },
        {
            ConditionExpr = '106',
            ID = 106,
            SelectCount = 10,
        },
        {
            ConditionExpr = '107',
            ID = 107,
            SelectCount = 10,
        },
        {
            ConditionExpr = '108',
            ID = 108,
            SelectCount = 10,
        },
        {
            ConditionExpr = '109',
            ID = 109,
            SelectCount = 10,
        },
        {
            ConditionExpr = '110',
            ID = 110,
            SelectCount = 10,
        },
        {
            ConditionExpr = '117',
            ID = 115,
        },
        {
            ConditionExpr = '118',
            ID = 116,
            SelectFunc = 2,
        },
        {
            ConditionExpr = '119',
            ID = 117,
        },
        {
            ConditionExpr = CS._1_23,
            ID = 120,
            SelectFunc = 2,
            SelectType = 11,
            SkillRelationType = 16,
        },
        {
            ConditionExpr = '130',
            ID = 121,
            SelectCount = 40,
            SelectFunc = 2,
        },
        {
            ID = 150,
            SelectCount = 0,
            SelectFunc = 0,
            SelectType = 0,
        },
        {
            ID = 151,
            SelectCount = 100,
            SkillRelationType = 1,
        },
        {
            ID = 152,
            SelectCount = 100,
            SkillRelationType = 2,
        },
        {
            ID = 153,
            SelectCount = 100,
        },
        {
            ID = 154,
            SelectCount = 100,
            SkillRelationType = 3,
        },
        {
            ID = 155,
            SelectCount = 100,
            SkillRelationType = 9,
        },
        {
            ID = 156,
            SelectCount = 100,
            SkillRelationType = 10,
        },
        {
            ID = 157,
            SelectCount = 100,
            SkillRelationType = 255,
        },
        {
            ConditionExpr = CS._1_32,
            ID = 158,
            SelectCount = 100,
            SkillRelationType = 2,
        },
        {
            ConditionExpr = CS._1_32,
            ID = 159,
            SelectCount = 100,
        },
        {
            ID = 160,
            SelectCount = 100,
            SkillRelationType = 2,
        },
        {
            ID = 161,
            SelectCount = 100,
            SkillRelationType = 3,
        },
        {
            ID = 162,
            SelectCount = 100,
        },
        {
            ID = 163,
            SelectCount = 100,
            SkillRelationType = 10,
        },
        {
            ConditionExpr = CS._1_5,
            ID = 164,
        },
        {
            ConditionExpr = CS._1_5,
            ID = 165,
            SelectCount = 100,
        },
        {
            ConditionExpr = '166',
            ID = 166,
            SelectCount = 100,
        },
        {
            ConditionExpr = '166&171',
            ID = 167,
            SelectCount = 100,
        },
        {
            ConditionExpr = '191',
            ID = 191,
            SelectCount = 10,
            SelectFunc = 0,
            SelectType = 0,
        },
        {
            ConditionExpr = '203',
            ID = 203,
            SelectCount = 100,
        },
        {
            ConditionExpr = '206',
            ID = 206,
            SelectCount = 99,
        },
        {
            ConditionExpr = '207',
            ID = 207,
            SelectCount = 99,
        },
        {
            ConditionExpr = CS._1_33,
            ID = 208,
        },
        {
            ConditionExpr = '209',
            ID = 209,
            SelectCount = 99,
            SkillRelationType = 255,
        },
        {
            ConditionExpr = '210',
            ID = 210,
            SelectCount = 99,
            SkillRelationType = 255,
        },
        {
            ConditionExpr = '211',
            ID = 211,
            SelectCount = 99,
            SkillRelationType = 255,
        },
        {
            ConditionExpr = '212',
            ID = 212,
            SelectCount = 99,
            SkillRelationType = 255,
        },
        {
            ConditionExpr = '213',
            ID = 213,
            SelectCount = 99,
            SkillRelationType = 255,
        },
        {
            ConditionExpr = '214',
            ID = 214,
            SkillRelationType = 255,
        },
        {
            ConditionExpr = '215',
            ID = 215,
            SelectCount = 99,
            SkillRelationType = 255,
        },
        {
            ConditionExpr = '216',
            ID = 216,
            SelectCount = 99,
            SkillRelationType = 255,
        },
        {
            ConditionExpr = '217',
            ID = 217,
            SelectCount = 99,
            SkillRelationType = 255,
        },
        {
            ConditionExpr = '218',
            ID = 218,
            SelectCount = 99,
            SkillRelationType = 255,
        },
        {
            ConditionExpr = '219',
            ID = 219,
            SelectCount = 99,
            SkillRelationType = 255,
        },
        {
            ConditionExpr = '220',
            ID = 220,
            SelectCount = 99,
            SkillRelationType = 255,
        },
        {
            ConditionExpr = '221',
            ID = 221,
            SelectCount = 99,
            SkillRelationType = 255,
        },
        {
            ConditionExpr = '222',
            ID = 222,
            SelectCount = 99,
            SkillRelationType = 255,
        },
        {
            ConditionExpr = '223',
            ID = 223,
            SelectCount = 99,
            SkillRelationType = 255,
        },
        {
            ConditionExpr = '224',
            ID = 224,
            SelectCount = 99,
            SkillRelationType = 255,
        },
        {
            ConditionExpr = '225',
            ID = 225,
            SelectCount = 99,
            SkillRelationType = 255,
        },
        {
            ConditionExpr = '226',
            ID = 226,
            SelectCount = 99,
            SkillRelationType = 255,
        },
        {
            ConditionExpr = '227',
            ID = 227,
            SelectCount = 99,
            SkillRelationType = 255,
        },
        {
            ConditionExpr = '228',
            ID = 228,
            SelectCount = 99,
            SkillRelationType = 255,
        },
        {
            ConditionExpr = '229',
            ID = 229,
            SelectCount = 99,
        },
        {
            ConditionExpr = '230',
            ID = 230,
            SelectCount = 99,
            SkillRelationType = 255,
        },
        {
            ConditionExpr = '231',
            ID = 231,
            SelectCount = 99,
            SkillRelationType = 255,
        },
        {
            ConditionExpr = '232',
            ID = 232,
            SelectCount = 99,
            SkillRelationType = 255,
        },
        {
            ConditionExpr = '233',
            ID = 233,
            SelectCount = 99,
            SkillRelationType = 255,
        },
        {
            ConditionExpr = '234',
            ID = 234,
            SelectCount = 99,
            SkillRelationType = 255,
        },
        {
            ConditionExpr = '235',
            ID = 235,
            SelectCount = 99,
            SkillRelationType = 255,
        },
        {
            ConditionExpr = '236',
            ID = 236,
            SelectCount = 99,
            SkillRelationType = 255,
        },
        {
            ConditionExpr = '237',
            ID = 237,
            SelectCount = 99,
            SelectFunc = 0,
            SkillRelationType = 255,
        },
        {
            ConditionExpr = '238',
            ID = 238,
            SelectCount = 99,
            SkillRelationType = 255,
        },
        {
            ConditionExpr = '239',
            ID = 239,
            SelectCount = 99,
            SkillRelationType = 255,
        },
        {
            ConditionExpr = '240',
            ID = 240,
            SelectCount = 99,
            SkillRelationType = 255,
        },
        {
            ConditionExpr = '241',
            ID = 241,
            SelectCount = 99,
            SkillRelationType = 255,
        },
        {
            ConditionExpr = '242',
            ID = 242,
            SelectCount = 99,
            SkillRelationType = 255,
        },
        {
            ConditionExpr = '243',
            ID = 243,
            SelectCount = 99,
            SkillRelationType = 255,
        },
        {
            ConditionExpr = '244',
            ID = 244,
            SelectCount = 99,
            SkillRelationType = 255,
        },
        {
            ConditionExpr = '146&147',
            ID = 245,
            SkillRelationType = 2,
        },
        {
            ID = 300,
            SelectCount = 0,
            SelectFunc = 0,
            SelectType = 0,
        },
        {
            ConditionExpr = CS._1_11,
            ID = 500,
            SelectCount = 40,
            SelectFunc = 2,
            SkillRelationType = 16,
        },
        {
            ConditionExpr = CS._1_11,
            ID = 501,
            SelectFunc = 2,
            SkillRelationType = 17,
        },
        {
            ConditionExpr = CS._1_11,
            ID = 502,
            SelectCount = 40,
            SelectFunc = 2,
            SkillRelationType = 17,
        },
        {
            ConditionExpr = CS._1_13,
            ID = 503,
            SelectCount = 40,
            SelectFunc = 2,
        },
        {
            ConditionExpr = CS._1_8,
            ID = 504,
            SelectCount = 40,
            SelectFunc = 2,
            SkillRelationType = 16,
        },
        {
            ConditionExpr = CS._1_11,
            ID = 505,
            SelectCount = 40,
            SelectFunc = 2,
            SkillRelationType = 16,
        },
        {
            ConditionExpr = CS._1_34,
            ID = 1001,
            SelectFunc = 2,
        },
        {
            ConditionExpr = CS._1_34,
            ID = 1002,
            SelectCount = 5,
            SelectFunc = 2,
        },
        {
            ConditionExpr = CS._1_18,
            ID = 1003,
            SelectCount = 5,
            SelectFunc = 2,
        },
        {
            ConditionExpr = CS._1_6,
            ID = 1004,
            SelectCount = 5,
            SelectFunc = 2,
        },
        {
            ConditionExpr = CS._1_12,
            ID = 1005,
            SelectFunc = 2,
        },
        {
            ConditionExpr = CS._1_3,
            ID = 1006,
            SelectFunc = 2,
            SelectType = 11,
            SkillRelationType = 16,
        },
        {
            ConditionExpr = '4006',
            ID = 1007,
            SelectCount = 5,
            SelectFunc = 2,
        },
        {
            ConditionExpr = '4007',
            ID = 1008,
            SelectCount = 5,
            SelectFunc = 2,
        },
        {
            ConditionExpr = CS._1_15,
            ID = 1009,
            SelectFunc = 2,
        },
        {
            ConditionExpr = CS._1_3,
            ID = 1010,
            SelectFunc = 2,
            SelectType = 11,
            SkillRelationType = 3,
        },
        {
            ConditionExpr = CS._1_10,
            ID = 1011,
            SelectCount = 5,
            SelectFunc = 2,
            SelectType = 11,
            SkillRelationType = 17,
        },
        {
            ConditionExpr = CS._1_3,
            ID = 1012,
            SelectFunc = 2,
        },
        {
            ConditionExpr = CS._1_18,
            ID = 1013,
            SelectCount = 5,
            SelectFunc = 2,
            SkillRelationType = 17,
        },
        {
            ConditionExpr = CS._1_3,
            ID = 1014,
            SelectCount = 5,
            SelectFunc = 2,
        },
        {
            ConditionExpr = CS._1_10,
            ID = 1015,
            SelectCount = 5,
            SelectFunc = 2,
            SelectType = 11,
            SkillRelationType = 3,
        },
        {
            ConditionExpr = CS._1_6,
            ID = 1016,
            SelectCount = 5,
            SelectFunc = 2,
            SkillRelationType = 17,
        },
        {
            ConditionExpr = CS._1_1,
            ID = 1017,
            SelectCount = 5,
            SelectFunc = 2,
        },
        {
            ConditionExpr = CS._1_12,
            ID = 1018,
            SelectCount = 5,
            SelectFunc = 2,
        },
        {
            ConditionExpr = CS._1_3,
            ID = 1019,
            SelectFunc = 2,
            SelectType = 11,
            SkillRelationType = 16,
        },
        {
            ConditionExpr = '4012',
            ID = 1020,
            SelectFunc = 2,
        },
        {
            ConditionExpr = CS._1_18,
            ID = 1021,
            SelectFunc = 2,
        },
        {
            ConditionExpr = CS._1_6,
            ID = 1022,
            SelectType = 0,
            SkillRelationType = 255,
        },
        {
            ConditionExpr = CS._1_35,
            ID = 1023,
            SelectCount = 10,
            SelectType = 0,
            SkillFillterTargetType = 6,
            SkillRelationType = 4,
        },
        {
            ConditionExpr = CS._1_35,
            ID = 1024,
            SelectCount = 10,
            SelectFunc = 2,
            SkillFillterTargetType = 6,
            SkillRelationType = 4,
        },
        {
            ConditionExpr = CS._1_6,
            ID = 1025,
            SelectFunc = 2,
            SelectType = 11,
            SkillRelationType = 3,
        },
        {
            ConditionExpr = CS._1_6,
            ID = 1026,
            SelectCount = 5,
            SelectFunc = 2,
            SelectType = 11,
            SkillRelationType = 3,
        },
        {
            ConditionExpr = CS._1_10,
            ID = 1027,
            SelectFunc = 2,
            SelectType = 11,
            SkillRelationType = 3,
        },
        {
            ConditionExpr = CS._1_10,
            ID = 1028,
            SelectCount = 5,
            SelectFunc = 2,
            SelectType = 11,
            SkillRelationType = 3,
        },
        {
            ConditionExpr = CS._1_16,
            ID = 1029,
            SelectFunc = 2,
            SelectType = 11,
            SkillRelationType = 3,
        },
        {
            ConditionExpr = CS._1_16,
            ID = 1030,
            SelectCount = 5,
            SelectFunc = 2,
            SelectType = 11,
            SkillRelationType = 3,
        },
        {
            ConditionExpr = CS._1_12,
            ID = 1031,
            SelectFunc = 2,
            SelectType = 11,
            SkillRelationType = 3,
        },
        {
            ConditionExpr = CS._1_12,
            ID = 1032,
            SelectCount = 5,
            SelectFunc = 2,
            SelectType = 11,
            SkillRelationType = 3,
        },
        {
            ConditionExpr = CS._1_15,
            ID = 1033,
            SelectFunc = 2,
            SelectType = 11,
            SkillRelationType = 3,
        },
        {
            ConditionExpr = CS._1_15,
            ID = 1034,
            SelectCount = 2,
            SelectFunc = 2,
            SelectType = 11,
            SkillRelationType = 3,
        },
        {
            ConditionExpr = CS._1_3,
            ID = 1035,
            SelectFunc = 2,
            SelectType = 11,
            SkillRelationType = 2,
        },
        {
            ConditionExpr = CS._1_3,
            ID = 1036,
            SelectCount = 5,
            SelectFunc = 2,
            SelectType = 11,
            SkillRelationType = 3,
        },
        {
            ConditionExpr = CS._1_3,
            ID = 1037,
            SelectFunc = 2,
            SelectType = 11,
            SkillRelationType = 3,
        },
        {
            ConditionExpr = CS._1_3,
            ID = 1038,
            SelectCount = 5,
            SelectFunc = 2,
            SelectType = 11,
            SkillRelationType = 2,
        },
        {
            ConditionExpr = CS._1_16,
            ID = 1040,
            SelectFunc = 2,
            SelectType = 11,
            SkillRelationType = 16,
        },
        {
            ConditionExpr = CS._1_16,
            ID = 1041,
            SelectFunc = 2,
        },
        {
            ConditionExpr = CS._1_6,
            ID = 1042,
            SelectCount = 5,
            SelectFunc = 2,
        },
        {
            ConditionExpr = CS._1_15,
            ID = 1043,
            SelectFunc = 2,
            SelectType = 11,
        },
        {
            ConditionExpr = CS._1_6,
            ID = 1050,
            SelectCount = 5,
            SelectFunc = 2,
            SelectType = 11,
            SkillRelationType = 16,
        },
        {
            ConditionExpr = CS._1_6,
            ID = 1051,
            SelectFunc = 2,
            SelectType = 11,
            SkillRelationType = 16,
        },
        {
            ConditionExpr = CS._1_10,
            ID = 1052,
            SelectCount = 5,
            SelectFunc = 2,
            SelectType = 11,
            SkillRelationType = 17,
        },
        {
            ConditionExpr = CS._1_10,
            ID = 1053,
            SelectFunc = 2,
            SelectType = 11,
            SkillRelationType = 17,
        },
        {
            ConditionExpr = CS._1_12,
            ID = 1055,
            SelectFunc = 2,
            SelectType = 11,
            SkillRelationType = 16,
        },
        {
            ConditionExpr = CS._1_1,
            ID = 1060,
            SelectFunc = 2,
        },
        {
            ConditionExpr = '18&5122',
            ID = 1061,
            SelectCount = 5,
            SelectFunc = 2,
        },
        {
            ConditionExpr = CS._1_17,
            ID = 1062,
            SelectCount = 5,
            SelectFunc = 2,
        },
        {
            ConditionExpr = '5157',
            ID = 1063,
            SelectCount = 5,
            SelectFunc = 2,
        },
        {
            ConditionExpr = '5158',
            ID = 1064,
            SelectCount = 5,
            SelectFunc = 2,
        },
        {
            ConditionExpr = CS._1_3,
            ID = 1065,
            SelectCount = 5,
            SelectFunc = 2,
            SelectType = 11,
            SkillRelationType = 2,
        },
        {
            ConditionExpr = CS._1_1,
            ID = 1066,
            SelectFunc = 2,
        },
        {
            ConditionExpr = CS._1_1,
            ID = 1067,
            SelectFunc = 2,
        },
        {
            ConditionExpr = CS._1_1,
            ID = 1068,
            SelectFunc = 2,
        },
        {
            ConditionExpr = CS._1_1,
            ID = 1069,
            SelectFunc = 2,
        },
        {
            ConditionExpr = '5303',
            ID = 1070,
            SelectFunc = 2,
            SkillRelationType = 3,
        },
        {
            ConditionExpr = '5302',
            ID = 1071,
            SelectFunc = 2,
        },
        {
            ConditionExpr = CS._1_3,
            ID = 1072,
            SelectCount = 15,
            SelectFunc = 2,
            SkillRelationType = 3,
        },
        {
            ConditionExpr = CS._1_3,
            ID = 1073,
            SelectCount = 15,
            SelectFunc = 2,
        },
        {
            ConditionExpr = '4005&5303',
            ID = 1074,
            SelectCount = 15,
            SelectFunc = 2,
            SkillRelationType = 3,
        },
        {
            ConditionExpr = '4005&5302',
            ID = 1075,
            SelectCount = 15,
            SelectFunc = 2,
        },
        {
            ConditionExpr = CS._1_1,
            ID = 1076,
            SelectFunc = 2,
        },
        {
            ConditionExpr = CS._1_1,
            ID = 1077,
            SelectFunc = 2,
        },
        {
            ConditionExpr = CS._1_1,
            ID = 1078,
            SelectFunc = 2,
        },
        {
            ConditionExpr = CS._1_1,
            ID = 1079,
            SelectFunc = 2,
        },
        {
            ConditionExpr = CS._1_1,
            ID = 1080,
            SelectFunc = 2,
        },
        {
            ConditionExpr = CS._1_1,
            ID = 1081,
            SelectFunc = 2,
        },
        {
            ConditionExpr = CS._1_1,
            ID = 1082,
            SelectFunc = 2,
        },
        {
            ConditionExpr = CS._1_1,
            ID = 1083,
            SelectFunc = 2,
        },
        {
            ConditionExpr = CS._1_1,
            ID = 1084,
            SelectFunc = 2,
        },
        {
            ConditionExpr = CS._1_1,
            ID = 1085,
            SelectFunc = 2,
        },
        {
            ConditionExpr = CS._1_1,
            ID = 1086,
            SelectFunc = 2,
        },
        {
            ConditionExpr = CS._1_1,
            ID = 1087,
            SelectFunc = 2,
        },
        {
            ConditionExpr = CS._1_1,
            ID = 1088,
            SelectFunc = 2,
        },
        {
            ConditionExpr = CS._1_1,
            ID = 1089,
            SelectFunc = 2,
        },
        {
            ConditionExpr = CS._1_1,
            ID = 1090,
            SelectFunc = 2,
        },
        {
            ConditionExpr = CS._1_1,
            ID = 1091,
            SelectFunc = 2,
        },
        {
            ConditionExpr = CS._1_1,
            ID = 1092,
            SelectFunc = 2,
        },
        {
            ConditionExpr = CS._1_1,
            ID = 1093,
            SelectFunc = 2,
        },
        {
            ConditionExpr = CS._1_1,
            ID = 1094,
            SelectFunc = 2,
        },
        {
            ConditionExpr = CS._1_1,
            ID = 1095,
            SelectFunc = 2,
        },
        {
            ConditionExpr = CS._1_1,
            ID = 1096,
            SelectFunc = 2,
        },
        {
            ConditionExpr = CS._1_1,
            ID = 1097,
            SelectFunc = 2,
        },
        {
            ConditionExpr = CS._1_1,
            ID = 1098,
            SelectFunc = 2,
        },
        {
            ConditionExpr = CS._1_1,
            ID = 1099,
            SelectFunc = 2,
        },
        {
            ConditionExpr = CS._1_3,
            ID = 1100,
            SelectCount = 15,
            SelectFunc = 2,
            SkillRelationType = 10,
        },
        {
            ID = 1805,
            SelectCount = 0,
            SelectFunc = 0,
            SelectType = 0,
        },
        {
            ConditionExpr = '3503',
            ID = 3503,
            SelectCount = 99,
        },
        {
            ConditionExpr = '5003',
            ID = 5000,
            SelectCount = 99,
            SelectFunc = 2,
        },
        {
            ConditionExpr = '5004',
            ID = 5001,
            SelectCount = 99,
            SelectFunc = 2,
        },
        {
            ConditionExpr = '6001',
            ID = 6001,
            SelectCount = 99,
        },
        {
            ConditionExpr = '6004',
            ID = 6002,
            SelectCount = 99,
            SkillRelationType = 2,
        },
        {
            ConditionExpr = CS._1_36,
            ID = 6003,
            SelectFunc = 1,
            SelectType = 2,
        },
        {
            ConditionExpr = CS._1_36,
            ID = 6004,
        },
        {
            ConditionExpr = '15&6007',
            ID = 6005,
        },
        {
            ConditionExpr = CS._1_37,
            ID = 6006,
            SelectCount = 3,
            SkillRelationType = 2,
        },
        {
            ConditionExpr = CS._1_37,
            ID = 6007,
            SkillRelationType = 2,
        },
        {
            ConditionExpr = '6054&191',
            ID = 6054,
            SelectCount = 99,
            SkillRelationType = 1,
        },
        {
            ConditionExpr = '6055&191',
            ID = 6055,
            SelectCount = 99,
            SkillRelationType = 1,
        },
        {
            ConditionExpr = CS._1_2,
            ID = 7000,
            SelectCount = 4,
            SelectFunc = 1,
        },
        {
            ConditionExpr = CS._1_2,
            ID = 7001,
            SelectCount = 8,
        },
        {
            ConditionExpr = CS._1_22,
            ID = 7002,
            SelectCount = 8,
            SelectFunc = 2,
        },
        {
            ConditionExpr = '39',
            ID = 7003,
            SelectFunc = 0,
            SelectType = 0,
            SkillRelationType = 1,
        },
        {
            ConditionExpr = '17',
            ID = 7004,
            SelectFunc = 2,
        },
        {
            ConditionExpr = '29&28',
            ID = 7005,
            SelectCount = 7,
            SelectFunc = 0,
            SelectType = 0,
        },
        {
            ConditionExpr = CS._1_2,
            ID = 7006,
            SelectFunc = 2,
            SelectType = 2,
        },
        {
            ConditionExpr = '30',
            ID = 7007,
            SelectFunc = 0,
            SelectType = 0,
        },
        {
            ConditionExpr = '31',
            ID = 7008,
            SelectCount = 2,
            SelectFunc = 0,
            SelectType = 0,
            SkillRelationType = 2,
        },
        {
            ConditionExpr = '32',
            ID = 7009,
            SelectFunc = 0,
            SelectType = 0,
        },
        {
            ConditionExpr = '47',
            ID = 7010,
        },
        {
            ConditionExpr = '50&34',
            ID = 7011,
            SelectCount = 8,
            SelectFunc = 0,
        },
        {
            ConditionExpr = '52',
            ID = 7012,
            SelectCount = 0,
            SelectFunc = 0,
            SelectType = 0,
        },
        {
            ConditionExpr = '53',
            ID = 7013,
            SelectCount = 0,
            SelectFunc = 0,
            SelectType = 0,
        },
        {
            ConditionExpr = '56',
            ID = 7014,
            SelectFunc = 0,
            SelectType = 0,
            SkillRelationType = 2,
        },
        {
            ConditionExpr = '57',
            ID = 7015,
            SelectFunc = 0,
            SelectType = 0,
            SkillRelationType = 2,
        },
        {
            ConditionExpr = '58',
            ID = 7016,
            SelectFunc = 0,
            SelectType = 0,
            SkillRelationType = 2,
        },
        {
            ConditionExpr = CS._1_2,
            ID = 7017,
            SelectCount = 3,
        },
        {
            ConditionExpr = '82&42',
            ID = 7018,
        },
        {
            ConditionExpr = '82&43',
            ID = 7019,
        },
        {
            ConditionExpr = '82&41',
            ID = 7020,
        },
        {
            ConditionExpr = CS._1_38,
            ID = 7021,
            SelectFunc = 2,
        },
        {
            ConditionExpr = '83',
            ID = 7022,
            SelectCount = 8,
            SkillRelationType = 2,
        },
        {
            ConditionExpr = '1005',
            ID = 7023,
            SelectCount = 8,
            SkillRelationType = 2,
        },
        {
            ConditionExpr = '92',
            ID = 7024,
            SelectCount = 8,
        },
        {
            ConditionExpr = '189',
            ID = 7025,
            SelectCount = 4,
            SelectFunc = 2,
        },
        {
            ConditionExpr = '9026',
            ID = 7026,
            SelectFunc = 2,
            SkillRelationType = 255,
        },
        {
            ConditionExpr = '9025',
            ID = 7027,
            SelectFunc = 2,
            SkillRelationType = 255,
        },
        {
            ConditionExpr = '50&155',
            ID = 7028,
            SelectCount = 8,
            SelectFunc = 0,
        },
        {
            ConditionExpr = '7029',
            ID = 7029,
            SelectFunc = 2,
            SkillRelationType = 255,
        },
        {
            ConditionExpr = '7030',
            ID = 7030,
            SelectFunc = 2,
        },
        {
            ConditionExpr = '7031',
            ID = 7031,
            SelectCount = 8,
            SelectFunc = 2,
        },
        {
            ConditionExpr = '7033',
            ID = 7033,
            SelectCount = 8,
            SelectFunc = 2,
            SkillRelationType = 255,
        },
        {
            ConditionExpr = CS._1_31,
            ID = 7034,
            SelectCount = 100,
        },
        {
            ConditionExpr = '7035',
            ID = 7035,
        },
        {
            ConditionExpr = '201&42',
            ID = 7038,
        },
        {
            ConditionExpr = '201&43',
            ID = 7039,
        },
        {
            ConditionExpr = '201&41',
            ID = 7040,
        },
        {
            ConditionExpr = CS._1_38,
            ID = 7041,
            SelectFunc = 2,
        },
        {
            ConditionExpr = '202',
            ID = 7042,
            SelectCount = 8,
            SkillRelationType = 2,
        },
        {
            ConditionExpr = '7427',
            ID = 7043,
        },
        {
            ConditionExpr = '7429',
            ID = 7044,
        },
        {
            ConditionExpr = '96&97&98&7172',
            ID = 7045,
            SelectCount = 8,
            SkillRelationType = 16,
        },
        {
            ConditionExpr = '7046',
            ID = 7046,
            SelectCount = 8,
        },
        {
            ConditionExpr = '7047',
            ID = 7047,
        },
        {
            ID = 7048,
            SelectFunc = 1,
        },
        {
            ID = 7049,
            SelectFunc = 2,
        },
        {
            ConditionExpr = '7047&7031',
            ID = 7050,
        },
        {
            ConditionExpr = '7051',
            ID = 7051,
        },
        {
            ConditionExpr = '7052',
            ID = 7052,
        },
        {
            ConditionExpr = '9049',
            ID = 7306,
            SelectFunc = 2,
            SkillRelationType = 255,
        },
        {
            ConditionExpr = '9050',
            ID = 7307,
            SelectFunc = 2,
            SkillRelationType = 255,
        },
        {
            ConditionExpr = '35&9118&171',
            ID = 7308,
            SelectCount = 3,
            SelectType = 2,
        },
        {
            ConditionExpr = CS._1_4,
            ID = 7309,
            SelectType = 2,
        },
        {
            ConditionExpr = CS._1_33,
            ID = 7310,
            SelectCount = 2,
        },
        {
            ConditionExpr = '7312',
            ID = 7312,
            SelectFunc = 2,
            SkillRelationType = 10,
        },
        {
            ConditionExpr = '7313',
            ID = 7313,
            SelectFunc = 2,
            SkillRelationType = 2,
        },
        {
            ConditionExpr = CS._1_5,
            ID = 7314,
            SelectCount = 4,
        },
        {
            ConditionExpr = '7314',
            ID = 7315,
        },
        {
            ConditionExpr = '7316',
            ID = 7316,
        },
        {
            ConditionExpr = '7317',
            ID = 7317,
        },
        {
            ConditionExpr = '9034|9038|9035|9169|9170|7554|7555|7556|7551|7552|7557|7558|7559|7560|7561',
            ID = 7318,
            SelectCount = 24,
            SkillRelationType = 2,
        },
        {
            ConditionExpr = '7319',
            ID = 7319,
        },
        {
            ConditionExpr = '7320',
            ID = 7320,
        },
        {
            ConditionExpr = '7321',
            ID = 7321,
        },
        {
            ConditionExpr = '7322',
            ID = 7322,
        },
        {
            ConditionExpr = '7323',
            ID = 7323,
        },
        {
            ConditionExpr = '7324',
            ID = 7324,
        },
        {
            ConditionExpr = '7325',
            ID = 7325,
        },
        {
            ConditionExpr = '7326',
            ID = 7326,
        },
        {
            ConditionExpr = '7513',
            ID = 7327,
            SelectCount = 99,
        },
        {
            ConditionExpr = '9035|9169|9170|9034|9038|179',
            ID = 7328,
            SelectCount = 24,
            SkillRelationType = 10,
        },
        {
            ConditionExpr = '7329&179',
            ID = 7329,
            SelectCount = 24,
        },
        {
            ConditionExpr = '7330',
            ID = 7330,
            SelectFunc = 2,
        },
        {
            ConditionExpr = '7331',
            ID = 7331,
            SelectFunc = 2,
        },
        {
            ConditionExpr = '7333&179',
            ID = 7332,
            SelectCount = 24,
        },
        {
            ConditionExpr = '7336&179',
            ID = 7333,
        },
        {
            ConditionExpr = '7335',
            ID = 7334,
            SelectFunc = 2,
        },
        {
            ConditionExpr = CS._1_39,
            ID = 7335,
            SelectCount = 99,
        },
        {
            ConditionExpr = CS._1_4,
            ID = 7401,
            SelectCount = 2,
            SelectType = 2,
        },
        {
            ConditionExpr = CS._1_4,
            ID = 7402,
            SelectCount = 3,
        },
        {
            ConditionExpr = '35&7481',
            ID = 7403,
            SelectCount = 3,
        },
        {
            ConditionExpr = '35&179',
            ID = 7404,
            SelectCount = 99,
        },
        {
            ConditionExpr = '7497',
            ID = 7497,
            SkillRelationType = 2,
        },
        {
            ID = 7542,
            SelectCount = 0,
            SelectFunc = 0,
            SelectType = 0,
        },
        {
            ConditionExpr = '7640|7641',
            ID = 7640,
            SelectCount = 8,
            SkillRelationType = 255,
        },
        {
            ID = 7641,
            SelectCount = 0,
            SelectFunc = 0,
            SelectType = 0,
        },
        {
            ConditionExpr = '7660',
            ID = 7660,
        },
        {
            ConditionExpr = '7661',
            ID = 7661,
        },
        {
            ConditionExpr = '7662',
            ID = 7662,
        },
        {
            ConditionExpr = '7663',
            ID = 7663,
        },
        {
            ConditionExpr = CS._1_40,
            ID = 7664,
        },
        {
            ConditionExpr = CS._1_39,
            ID = 7665,
        },
        {
            ConditionExpr = '7696&43&7681',
            ID = 7666,
        },
        {
            ConditionExpr = '7696&7681',
            ID = 7667,
        },
        {
            ConditionExpr = '7683',
            ID = 7668,
        },
        {
            ConditionExpr = '7684',
            ID = 7669,
        },
        {
            ConditionExpr = '7696&35&7681&7682&42',
            ID = 7670,
        },
        {
            ConditionExpr = '7696&7681&7682',
            ID = 7671,
        },
        {
            ConditionExpr = '7696&35&7681&7682&43',
            ID = 7672,
        },
        {
            ConditionExpr = '7696&35&7681&7682&41',
            ID = 7673,
        },
        {
            ConditionExpr = '7696&35&42',
            ID = 7674,
        },
        {
            ConditionExpr = '7696&35&43',
            ID = 7675,
        },
        {
            ConditionExpr = '7696&35&41',
            ID = 7676,
        },
        {
            ConditionExpr = '35&43',
            ID = 7677,
            SelectCount = 2,
        },
        {
            ConditionExpr = '35&42',
            ID = 7678,
            SelectCount = 2,
        },
        {
            ConditionExpr = '35&41',
            ID = 7679,
            SelectCount = 2,
        },
        {
            ConditionExpr = CS._1_40,
            ID = 7680,
        },
        {
            ConditionExpr = '7698&7699&7701',
            ID = 7681,
            SelectCount = 99,
        },
        {
            ConditionExpr = '7702',
            ID = 7683,
            SelectCount = 4,
        },
        {
            ConditionExpr = '7703',
            ID = 7684,
            SelectCount = 8,
        },
        {
            ConditionExpr = '7704',
            ID = 7685,
        },
        {
            ConditionExpr = '7705',
            ID = 7686,
        },
        {
            ConditionExpr = '9002',
            ID = 9002,
            SelectFunc = 2,
        },
        {
            ConditionExpr = '9027',
            ID = 9027,
            SelectCount = 8,
            SelectFunc = 0,
            SelectType = 0,
            SkillRelationType = 255,
        },
        {
            ConditionExpr = '9031',
            ID = 9031,
            SelectFunc = 2,
            SkillRelationType = 255,
        },
        {
            ConditionExpr = '9032|9277',
            ID = 9032,
            SelectFunc = 2,
            SkillRelationType = 255,
        },
        {
            ConditionExpr = '9034',
            ID = 9034,
            SelectCount = 8,
            SelectFunc = 2,
            SkillRelationType = 255,
        },
        {
            ConditionExpr = '9035',
            ID = 9035,
            SelectCount = 3,
            SelectFunc = 2,
            SkillRelationType = 255,
        },
        {
            ConditionExpr = '9036',
            ID = 9036,
            SelectCount = 8,
            SelectFunc = 2,
        },
        {
            ConditionExpr = '9037',
            ID = 9037,
            SelectCount = 8,
            SelectFunc = 2,
        },
        {
            ConditionExpr = '9038',
            ID = 9038,
            SelectCount = 8,
            SelectFunc = 2,
            SkillRelationType = 255,
        },
        {
            ConditionExpr = '9039',
            ID = 9039,
            SelectCount = 8,
            SelectFunc = 2,
        },
        {
            ConditionExpr = '9040',
            ID = 9040,
            SelectCount = 8,
            SelectFunc = 2,
        },
        {
            ConditionExpr = '9041&179',
            ID = 9041,
            SelectCount = 8,
        },
        {
            ConditionExpr = '9042&43',
            ID = 9042,
            SelectFunc = 2,
        },
        {
            ConditionExpr = '9042',
            ID = 9043,
            SelectFunc = 2,
        },
        {
            ConditionExpr = '9051',
            ID = 9044,
            SelectFunc = 1,
            SelectType = 5,
        },
        {
            ConditionExpr = '9051&9052',
            ID = 9045,
            SelectFunc = 1,
            SelectType = 5,
        },
        {
            ConditionExpr = CS._1_41,
            ID = 9046,
        },
        {
            ConditionExpr = '9052&35',
            ID = 9047,
        },
        {
            ConditionExpr = '9060',
            ID = 9048,
            SelectCount = 8,
            SelectFunc = 2,
        },
        {
            ConditionExpr = CS._1_5,
            ID = 9049,
        },
        {
            ConditionExpr = '179&9063',
            ID = 9050,
        },
        {
            ConditionExpr = '179&9062&9063',
            ID = 9051,
        },
        {
            ConditionExpr = '9067',
            ID = 9052,
        },
        {
            ConditionExpr = '9068',
            ID = 9053,
        },
        {
            ConditionExpr = '9070&9071&9075',
            ID = 9054,
            SelectFunc = 2,
            SkillFillterTargetType = 6,
            SkillRelationType = 255,
        },
        {
            ConditionExpr = '9069&9071&9075',
            ID = 9055,
            SelectFunc = 2,
            SkillFillterTargetType = 6,
            SkillRelationType = 255,
        },
        {
            ConditionExpr = '9069&9070&9075',
            ID = 9056,
            SelectFunc = 2,
            SkillFillterTargetType = 6,
            SkillRelationType = 255,
        },
        {
            ConditionExpr = '9072',
            ID = 9057,
            SkillRelationType = 255,
        },
        {
            ConditionExpr = '9073',
            ID = 9058,
            SkillRelationType = 255,
        },
        {
            ConditionExpr = '9074',
            ID = 9059,
            SkillRelationType = 255,
        },
        {
            ConditionExpr = '9075',
            ID = 9060,
            SelectCount = 3,
            SelectFunc = 0,
            SelectType = 0,
            SkillRelationType = 2,
        },
        {
            ConditionExpr = '9080',
            ID = 9070,
            SelectFunc = 1,
        },
        {
            ConditionExpr = '9081',
            ID = 9071,
            SelectFunc = 1,
        },
        {
            ConditionExpr = '9082',
            ID = 9072,
            SelectFunc = 1,
        },
        {
            ConditionExpr = '9083',
            ID = 9073,
            SelectFunc = 1,
        },
        {
            ConditionExpr = '9083&9084',
            ID = 9074,
            SelectFunc = 1,
        },
        {
            ConditionExpr = '9060&179',
            ID = 9075,
            SelectFunc = 1,
        },
        {
            ID = 9076,
            SelectFunc = 2,
        },
        {
            ConditionExpr = '43&9089',
            ID = 9077,
        },
        {
            ConditionExpr = CS._1_9,
            ID = 9078,
        },
        {
            ConditionExpr = '9089',
            ID = 9079,
        },
        {
            ConditionExpr = '7282',
            ID = 9080,
            SelectCount = 100,
        },
        {
            ConditionExpr = '9097',
            ID = 9081,
            SelectCount = 100,
        },
        {
            ConditionExpr = '9097&43',
            ID = 9082,
        },
        {
            ConditionExpr = '9099|179',
            ID = 9083,
            SelectCount = 99,
            SkillRelationType = 10,
        },
        {
            ConditionExpr = CS._1_7,
            ID = 9084,
        },
        {
            ConditionExpr = '42&9100',
            ID = 9085,
        },
        {
            ConditionExpr = '9100',
            ID = 9086,
        },
        {
            ConditionExpr = '146&9101',
            ID = 9087,
            SkillRelationType = 2,
        },
        {
            ID = 9088,
            SelectCount = 0,
            SelectFunc = 0,
            SelectType = 0,
        },
        {
            ConditionExpr = CS._1_7,
            ID = 9089,
            SelectCount = 4,
        },
        {
            ID = 9090,
            SelectCount = 2,
            SelectFunc = 1,
        },
        {
            ConditionExpr = '9129',
            ID = 9091,
            SelectFunc = 2,
        },
        {
            ConditionExpr = '9130&179',
            ID = 9092,
            SelectCount = 99,
            SelectFunc = 2,
        },
        {
            ConditionExpr = '9138',
            ID = 9093,
            SelectFunc = 2,
            SkillRelationType = 2,
        },
        {
            ConditionExpr = '9139',
            ID = 9094,
            SelectFunc = 2,
            SkillRelationType = 2,
        },
        {
            ConditionExpr = '9177',
            ID = 9095,
            SkillRelationType = 255,
        },
        {
            ConditionExpr = '7687',
            ID = 9096,
            SelectCount = 99,
            SelectFunc = 0,
            SelectType = 0,
            SkillRelationType = 255,
        },
        {
            ConditionExpr = '9306&179',
            ID = 9097,
            SelectFunc = 1,
        },
        {
            ConditionExpr = '9113',
            ID = 9113,
        },
        {
            ID = 9114,
            SelectCount = 8,
            SelectFunc = 2,
            SkillRelationType = 16,
        },
        {
            ConditionExpr = '9118',
            ID = 9115,
        },
        {
            ConditionExpr = '9127',
            ID = 9116,
            SelectCount = 8,
            SelectFunc = 2,
        },
        {
            ConditionExpr = '9134',
            ID = 9117,
            SelectCount = 4,
        },
        {
            ConditionExpr = '9136',
            ID = 9118,
            SelectCount = 5,
            SkillFillterTargetType = 6,
            SkillRelationType = 2,
        },
        {
            ConditionExpr = '4&9271',
            ID = 9119,
        },
        {
            ConditionExpr = '9141',
            ID = 9120,
            SkillRelationType = 2,
        },
        {
            ConditionExpr = '7498&7501',
            ID = 9121,
            SelectCount = 2,
            SkillRelationType = 2,
        },
        {
            ConditionExpr = CS._1_41,
            ID = 9122,
            SelectCount = 3,
        },
        {
            ConditionExpr = '9005&9008&7170&35',
            ID = 9123,
        },
        {
            ConditionExpr = '9005&9008&7170',
            ID = 9124,
        },
        {
            ConditionExpr = '7500',
            ID = 9125,
            SelectCount = 99,
            SkillRelationType = 2,
        },
        {
            ConditionExpr = '7498',
            ID = 9126,
            SelectFunc = 2,
            SkillRelationType = 2,
        },
        {
            ConditionExpr = '7499',
            ID = 9127,
            SelectCount = 3,
        },
        {
            ConditionExpr = '9005&9008',
            ID = 9128,
            SelectType = 2,
        },
        {
            ConditionExpr = '7504',
            ID = 9129,
            SkillRelationType = 2,
        },
        {
            ConditionExpr = CS._1_42,
            ID = 9130,
            SkillRelationType = 2,
        },
        {
            ConditionExpr = '7506|7505|7504',
            ID = 9131,
            SelectFunc = 0,
            SelectType = 0,
        },
        {
            ConditionExpr = '9143&9144&9145&35',
            ID = 9132,
            SelectType = 2,
        },
        {
            ConditionExpr = '9147',
            ID = 9133,
            SelectCount = 20,
            SelectFunc = 0,
            SelectType = 0,
            SkillRelationType = 2,
        },
        {
            ConditionExpr = '7512',
            ID = 9134,
            SelectFunc = 2,
            SkillRelationType = 2,
        },
        {
            ConditionExpr = '9151',
            ID = 9135,
            SelectFunc = 0,
            SelectType = 0,
            SkillRelationType = 2,
        },
        {
            ConditionExpr = '9152|9175',
            ID = 9136,
            SelectFunc = 0,
            SelectType = 0,
            SkillRelationType = 2,
        },
        {
            ConditionExpr = CS._1_4,
            ID = 9137,
            SelectCount = 2,
            SelectType = 2,
        },
        {
            ConditionExpr = CS._1_42,
            ID = 9138,
            SelectFunc = 0,
            SelectType = 0,
        },
        {
            ConditionExpr = '(9156|9157)&9212',
            ID = 9139,
            SelectFunc = 2,
            SkillRelationType = 2,
        },
        {
            ConditionExpr = CS._1_43,
            ID = 9140,
        },
        {
            ConditionExpr = '9159&9160&35&9158&9212',
            ID = 9141,
            SelectCount = 2,
        },
        {
            ConditionExpr = '9161',
            ID = 9142,
            SelectFunc = 2,
        },
        {
            ConditionExpr = CS._1_43,
            ID = 9143,
            SelectFunc = 1,
            SelectType = 2,
        },
        {
            ConditionExpr = '(9162&179)|9161',
            ID = 9144,
            SelectFunc = 2,
            SkillRelationType = 10,
        },
        {
            ConditionExpr = '9163&9159',
            ID = 9145,
            SelectCount = 8,
            SelectFunc = 0,
            SelectType = 0,
        },
        {
            ConditionExpr = '9164',
            ID = 9146,
        },
        {
            ConditionExpr = '7511|9147',
            ID = 9147,
            SelectFunc = 2,
            SkillRelationType = 10,
        },
        {
            ConditionExpr = '9165',
            ID = 9148,
        },
        {
            ConditionExpr = '9166&241',
            ID = 9149,
            SelectCount = 2,
        },
        {
            ConditionExpr = CS._1_44,
            ID = 9150,
            SelectType = 2,
        },
        {
            ConditionExpr = '9167',
            ID = 9151,
            SelectCount = 20,
            SkillRelationType = 2,
        },
        {
            ConditionExpr = '9168',
            ID = 9152,
            SelectCount = 8,
            SelectFunc = 0,
            SelectType = 0,
        },
        {
            ConditionExpr = '9143&9144&9145',
            ID = 9153,
            SelectFunc = 1,
            SelectType = 2,
        },
        {
            ConditionExpr = '9171&9172',
            ID = 9154,
            SelectFunc = 0,
            SelectType = 0,
            SkillRelationType = 2,
        },
        {
            ConditionExpr = '9173',
            ID = 9155,
            SelectCount = 99,
            SelectFunc = 0,
            SelectType = 0,
        },
        {
            ConditionExpr = CS._1_9,
            ID = 9156,
        },
        {
            ConditionExpr = '7544&43',
            ID = 9157,
        },
        {
            ConditionExpr = '7544',
            ID = 9158,
        },
        {
            ConditionExpr = '9176',
            ID = 9159,
            SelectCount = 99,
        },
        {
            ConditionExpr = '9005&9008&35',
            ID = 9160,
            SelectType = 2,
        },
        {
            ConditionExpr = '9178',
            ID = 9161,
            SelectCount = 99,
        },
        {
            ConditionExpr = '9052&41',
            ID = 9162,
            SelectCount = 99,
        },
        {
            ConditionExpr = '9052',
            ID = 9163,
            SelectCount = 99,
        },
        {
            ConditionExpr = CS._1_44,
            ID = 9164,
            SelectCount = 2,
        },
        {
            ConditionExpr = '9190',
            ID = 9165,
        },
        {
            ConditionExpr = '7506',
            ID = 9166,
            SelectCount = 10,
        },
        {
            ConditionExpr = CS._1_5,
            ID = 9167,
            SelectFunc = 1,
        },
        {
            ConditionExpr = '9192&179',
            ID = 9168,
            SelectCount = 24,
        },
        {
            ConditionExpr = '9193&179',
            ID = 9169,
            SelectCount = 24,
        },
        {
            ConditionExpr = '9195&41',
            ID = 9170,
        },
        {
            ConditionExpr = '9196&41',
            ID = 9171,
        },
        {
            ConditionExpr = '9197&41',
            ID = 9172,
        },
        {
            ConditionExpr = '9198&41',
            ID = 9173,
        },
        {
            ConditionExpr = '9195&9052&(42|43)',
            ID = 9174,
        },
        {
            ConditionExpr = '9196&9052&(42|43)',
            ID = 9175,
        },
        {
            ConditionExpr = '9197&9052&(42|43)',
            ID = 9176,
        },
        {
            ConditionExpr = '9198&9052&(42|43)',
            ID = 9177,
        },
        {
            ConditionExpr = CS._1_45,
            ID = 9178,
            SelectFunc = 1,
        },
        {
            ConditionExpr = '9199&9200&9201&35',
            ID = 9179,
            SelectCount = 3,
        },
        {
            ConditionExpr = CS._1_45,
            ID = 9180,
            SelectFunc = 1,
            SelectType = 2,
        },
        {
            ConditionExpr = '(7498|7665)&7501',
            ID = 9181,
            SelectCount = 4,
            SkillRelationType = 2,
        },
        {
            ConditionExpr = '7498|7665',
            ID = 9182,
            SelectFunc = 2,
            SkillRelationType = 2,
        },
        {
            ConditionExpr = '9200&9201',
            ID = 9183,
            SelectCount = 3,
        },
        {
            ConditionExpr = '9200&9201&7499',
            ID = 9184,
            SelectCount = 8,
        },
        {
            ConditionExpr = '7666|7667|7668',
            ID = 9185,
            SelectFunc = 0,
            SelectType = 0,
        },
        {
            ConditionExpr = '9210',
            ID = 9186,
        },
        {
            ConditionExpr = '7666',
            ID = 9187,
            SelectCount = 10,
        },
        {
            ConditionExpr = '9005&9008&7174&35',
            ID = 9188,
            SelectCount = 0,
        },
        {
            ConditionExpr = '9005&9008&7174',
            ID = 9189,
        },
        {
            ConditionExpr = '7544&42',
            ID = 9190,
        },
        {
            ConditionExpr = '7318&9042&43',
            ID = 9191,
        },
        {
            ConditionExpr = '7318',
            ID = 9192,
        },
        {
            ConditionExpr = '9214&35',
            ID = 9193,
        },
        {
            ConditionExpr = '9214',
            ID = 9194,
        },
        {
            ConditionExpr = '9195&(42|43)',
            ID = 9195,
        },
        {
            ConditionExpr = '9196&(42|43)',
            ID = 9196,
        },
        {
            ConditionExpr = '9197&(42|43)',
            ID = 9197,
        },
        {
            ConditionExpr = '9198&(42|43)',
            ID = 9198,
        },
        {
            ConditionExpr = '9195&9052&41',
            ID = 9199,
        },
        {
            ConditionExpr = '9196&9052&41',
            ID = 9200,
        },
        {
            ConditionExpr = '9197&9052&41',
            ID = 9201,
        },
        {
            ConditionExpr = '9198&9052&41',
            ID = 9202,
        },
        {
            ConditionExpr = '9219',
            ID = 9203,
            SelectCount = 20,
        },
        {
            ConditionExpr = '93418',
            ID = 9204,
            SelectType = 2,
        },
        {
            ConditionExpr = '35&41&93408',
            ID = 9205,
        },
        {
            ConditionExpr = '35&43&93408',
            ID = 9206,
        },
        {
            ConditionExpr = '35&42&93408',
            ID = 9207,
        },
        {
            ConditionExpr = '7500|9220',
            ID = 9208,
            SelectCount = 99,
            SelectFunc = 0,
            SelectType = 0,
            SkillRelationType = 2,
        },
        {
            ConditionExpr = '9224&9230&9233&35',
            ID = 9209,
            SelectFunc = 0,
            SelectType = 0,
        },
        {
            ConditionExpr = '9224&9230&9233',
            ID = 9210,
            SelectFunc = 1,
            SelectType = 2,
        },
        {
            ConditionExpr = '9225',
            ID = 9211,
            SelectFunc = 2,
        },
        {
            ConditionExpr = '9226',
            ID = 9212,
            SelectFunc = 2,
        },
        {
            ConditionExpr = '9227&43',
            ID = 9213,
        },
        {
            ConditionExpr = '9227&42',
            ID = 9214,
        },
        {
            ConditionExpr = '9228',
            ID = 9215,
            SelectFunc = 2,
        },
        {
            ConditionExpr = '9229',
            ID = 9216,
            SelectFunc = 2,
        },
        {
            ConditionExpr = '9232',
            ID = 9217,
            SelectFunc = 2,
        },
        {
            ConditionExpr = '9231',
            ID = 9218,
            SelectFunc = 2,
        },
        {
            ConditionExpr = '9234',
            ID = 9219,
        },
        {
            ConditionExpr = '9235',
            ID = 9220,
            SelectCount = 20,
            SkillRelationType = 2,
        },
        {
            ConditionExpr = '93419',
            ID = 9221,
            SelectCount = 24,
            SkillRelationType = 2,
        },
        {
            ConditionExpr = '9159&35',
            ID = 9222,
            SelectCount = 2,
        },
        {
            ConditionExpr = '9159',
            ID = 9223,
        },
        {
            ConditionExpr = '9236&18',
            ID = 9224,
            SelectCount = 40,
            SelectFunc = 2,
        },
        {
            ConditionExpr = CS._1_9,
            ID = 9225,
            SelectFunc = 2,
        },
        {
            ConditionExpr = CS._1_7,
            ID = 9226,
        },
        {
            ConditionExpr = CS._1_14,
            ID = 9227,
        },
        {
            ConditionExpr = CS._1_14,
            ID = 9228,
        },
        {
            ConditionExpr = '(93419|93424|93425)&93420&93421',
            ID = 9229,
            SelectCount = 24,
            SkillRelationType = 2,
        },
        {
            ConditionExpr = '9254|9255|9256|9260|9261|9262',
            ID = 9230,
        },
        {
            ConditionExpr = CS._1_46,
            ID = 9231,
            SelectCount = 8,
        },
        {
            ConditionExpr = '9263',
            ID = 9232,
        },
        {
            ConditionExpr = '9264&9265&9266&35',
            ID = 9233,
            SelectType = 2,
        },
        {
            ConditionExpr = '9267',
            ID = 9234,
        },
        {
            ConditionExpr = CS._1_46,
            ID = 9235,
            SelectCount = 8,
            SkillRelationType = 2,
        },
        {
            ConditionExpr = '9272',
            ID = 9236,
            SelectCount = 20,
            SkillRelationType = 2,
        },
        {
            ConditionExpr = '7036',
            ID = 9237,
        },
        {
            ConditionExpr = '9300',
            ID = 9238,
            SelectFunc = 0,
            SelectType = 0,
            SkillFillterTargetType = 2,
            SkillRelationType = 4,
        },
        {
            ConditionExpr = '9159&9160&35&9158&9212&9302',
            ID = 9239,
            SelectCount = 2,
        },
        {
            ConditionExpr = '9210|9190',
            ID = 9242,
            SelectCount = 10,
        },
        {
            ConditionExpr = CS._1_7,
            ID = 9243,
            SelectCount = 2,
        },
        {
            ConditionExpr = CS._1_9,
            ID = 9244,
            SelectCount = 2,
        },
        {
            ConditionExpr = '9392|9393|9394|9395|9396|9397|9398',
            ID = 9393,
            SkillRelationType = 2,
        },
        {
            ConditionExpr = '7506|7666',
            ID = 9403,
        },
        {
            ConditionExpr = CS._1_5,
            ID = 9422,
            SelectCount = 3,
            SelectFunc = 1,
        },
        {
            ConditionExpr = CS._1_5,
            ID = 9423,
            SelectCount = 8,
        },
        {
            ID = 10001,
            SelectFunc = 0,
            SelectType = 0,
            SkillRelationType = 1,
        },
        {
            ID = 10002,
            SelectFunc = 0,
            SelectType = 0,
        },
        {
            ID = 10003,
            SelectFunc = 1,
            SelectType = 2,
        },
        {
            ConditionExpr = '201',
            ID = 10004,
            SelectFunc = 0,
            SelectType = 0,
        },
        {
            ConditionExpr = '40000',
            ID = 40000,
            SkillRelationType = 255,
        },
        {
            ConditionExpr = '40001',
            ID = 40001,
            SelectCount = 0,
            SelectFunc = 0,
            SelectType = 0,
            SkillFillterTargetType = 6,
            SkillRelationType = 255,
        },
        {
            ConditionExpr = '40002',
            ID = 40002,
            SelectFunc = 2,
        },
        {
            ConditionExpr = '40003',
            ID = 40003,
            SelectFunc = 2,
        },
        {
            ID = 40004,
            SelectFunc = 2,
        },
        {
            ConditionExpr = '40005',
            ID = 40005,
            SelectFunc = 2,
        },
        {
            ConditionExpr = '40006',
            ID = 40006,
            SelectFunc = 2,
        },
        {
            ConditionExpr = '40007',
            ID = 40007,
            SelectFunc = 2,
        },
        {
            ID = 40008,
            SelectFunc = 2,
        },
        {
            ConditionExpr = '40009',
            ID = 40009,
            SelectFunc = 2,
        },
        {
            ConditionExpr = '40010',
            ID = 40010,
            SelectFunc = 2,
        },
        {
            ConditionExpr = '40011',
            ID = 40011,
            SelectFunc = 2,
        },
        {
            ConditionExpr = '40012',
            ID = 40012,
            SelectFunc = 2,
        },
        {
            ConditionExpr = '40013',
            ID = 40013,
            SelectFunc = 2,
        },
        {
            ConditionExpr = '40014',
            ID = 40014,
            SelectFunc = 2,
        },
        {
            ConditionExpr = '40015&88',
            ID = 40015,
            SkillRelationType = 255,
        },
        {
            ConditionExpr = '40016',
            ID = 40016,
            SkillRelationType = 255,
        },
        {
            ConditionExpr = '40017',
            ID = 40017,
            SelectFunc = 2,
        },
        {
            ConditionExpr = '40018',
            ID = 40018,
            SelectFunc = 2,
        },
        {
            ConditionExpr = '40019',
            ID = 40019,
            SelectFunc = 2,
        },
        {
            ConditionExpr = '40020',
            ID = 40020,
            SelectFunc = 2,
        },
        {
            ConditionExpr = '40021',
            ID = 40021,
            SelectFunc = 2,
        },
        {
            ConditionExpr = '40022',
            ID = 40022,
            SelectFunc = 2,
        },
        {
            ConditionExpr = '40023',
            ID = 40023,
            SelectFunc = 2,
        },
        {
            ConditionExpr = '40024',
            ID = 40024,
            SelectFunc = 2,
        },
        {
            ConditionExpr = '40025',
            ID = 40025,
            SelectFunc = 2,
        },
        {
            ConditionExpr = '40026',
            ID = 40026,
            SelectFunc = 2,
        },
        {
            ConditionExpr = '40027',
            ID = 40027,
            SkillRelationType = 255,
        },
        {
            ConditionExpr = '40029',
            ID = 40029,
            SelectFunc = 2,
        },
        {
            ConditionExpr = '40030',
            ID = 40030,
            SelectFunc = 2,
        },
        {
            ConditionExpr = '40031',
            ID = 40031,
            SelectFunc = 2,
        },
        {
            ConditionExpr = '40032',
            ID = 40032,
            SkillRelationType = 255,
        },
        {
            ConditionExpr = '40034',
            ID = 40034,
            SelectFunc = 2,
        },
        {
            ConditionExpr = '40035',
            ID = 40035,
            SelectFunc = 2,
        },
        {
            ConditionExpr = '40036',
            ID = 40036,
            SelectFunc = 2,
        },
        {
            ID = 40037,
            SelectCount = 10,
            SelectFunc = 2,
            SkillFillterTargetType = 9,
            SkillRelationType = 255,
        },
        {
            ConditionExpr = CS._1_7,
            ID = 72301,
            SelectCount = 4,
        },
        {
            ConditionExpr = '41|43',
            ID = 72302,
            SelectCount = 4,
        },
        {
            ConditionExpr = '72303',
            ID = 72303,
            SelectCount = 10,
        },
        {
            ConditionExpr = '85330',
            ID = 85330,
        },
        {
            ConditionExpr = '4&93400',
            ID = 93400,
            SkillRelationType = 2,
        },
        {
            ConditionExpr = '93402|93403',
            ID = 93402,
            SelectCount = 100,
            SkillRelationType = 2,
        },
        {
            ConditionExpr = CS._1_9,
            ID = 93403,
            SelectCount = 2,
        },
        {
            ConditionExpr = '43&7452',
            ID = 93404,
        },
        {
            ConditionExpr = '43&7453',
            ID = 93405,
        },
        {
            ConditionExpr = '9112|9109|9110|9111',
            ID = 93486,
        },
        {
            ConditionExpr = '7452',
            ID = 93557,
            SelectCount = 4,
        },
        {
            ConditionExpr = '7453',
            ID = 93558,
            SelectCount = 4,
        },
        {
            ConditionExpr = '42&7452',
            ID = 93572,
        },
        {
            ConditionExpr = '42&7453',
            ID = 93573,
        },
        {
            ConditionExpr = CS._1_30,
            ID = 93574,
        },
        {
            ConditionExpr = '43&93408&179',
            ID = 93575,
        },
        {
            ConditionExpr = '93408&179',
            ID = 93576,
        },
        {
            ConditionExpr = '93409|93410',
            ID = 93578,
            SelectCount = 2,
        },
        {
            ConditionExpr = '7454&7455',
            ID = 93579,
            SelectCount = 8,
        },
        {
            ConditionExpr = '93415',
            ID = 93580,
            SkillRelationType = 2,
        },
        {
            ConditionExpr = CS._1_4,
            ID = 93581,
            SelectCount = 7,
        },
        {
            ID = 93582,
            SelectCount = 4,
            SkillRelationType = 2,
        },
        {
            ConditionExpr = '93413',
            ID = 101876,
            SkillFillterTargetType = 6,
            SkillRelationType = 255,
        },
        {
            ConditionExpr = '(229600&179)|229599',
            ID = 229599,
            SelectFunc = 2,
            SkillRelationType = 10,
        },
        {
            ConditionExpr = '229601',
            ID = 229600,
            SelectCount = 8,
        },
        {
            ConditionExpr = CS._1_14,
            ID = 853301,
            SelectCount = 2,
        },
	},
}

setmetatable(SkillTargetSelectCfg, { __index = CfgBase })

SkillTargetSelectCfg:InitCfg()

-- AUTO GENERATED CODE END, PLEASE DON'T MODIFY


return SkillTargetSelectCfg
