---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by yuhang_lightpaw
--- DateTime: 2025/7/11 10:28
---

local LuaClass = require("Core/LuaClass")
local UIViewModel = require("UI/UIViewModel")
local RhythmGameStarVM = require("Game/StarlightCelebration/RhythmGame/VM/RhythmGameStarVM")

---@class RhythmGameVM : UIViewModel
local RhythmGameVM = LuaClass(UIViewModel)

---Ctor
function RhythmGameVM:Ctor()
    self:Cleanup()
end

function RhythmGameVM:OnEnd()
end

function RhythmGameVM:Cleanup()
    -- 观众满意度 - 表示观众对表演的整体满意程度
    self.Satisfaction = 0
    -- 得分 - 玩家在游戏中获得的总分
    self.SScore = 0
    self.Combo = 0
    self.IsSuc = false
    -- 完美次数 - PERFECT判定次数
    self.PerfectHits = 0
    -- 很棒次数 - GREAT判定次数
    self.GreatHits = 0
    -- 不错次数 - GOOD判定次数
    self.GoodHits = 0
    -- 失误次数 - MISS判定次数
    self.Misses = 0
    self.CurModeText = ""
    self.CurModePath = "PaperSprite'/Game/UI/Atlas/StarlightCelebration/RhythmGame/Frames/UI_Icon_StarLight_RhythmGame_Music3_png.UI_Icon_StarLight_RhythmGame_Music3_png'"
    self.SatisfactionText = ""
    self.IsNewSatisfaction = false
    self.IsNewSScore = false
    self.IsFullCombo = false
    self.IsPerfectCombo = false
    self.FullComboText = ""
    self.DebugText = ""
    
    self.LootID = 0
    
    self.SatisfactionVMList = self:ResetBindableList(self.ActiveSkillVMList, RhythmGameStarVM)
end

function RhythmGameVM:UpdateMode(Mode)
    if Mode == _G.RhythmGameMgr.GameMode.EASY then
        self.CurModeText = _G.LSTR(1710008) --普通
        self.CurModePath = "PaperSprite'/Game/UI/Atlas/StarlightCelebration/RhythmGame/Frames/UI_Icon_StarLight_RhythmGame_Music3_png.UI_Icon_StarLight_RhythmGame_Music3_png'"
    else
        self.CurModeText = _G.LSTR(1710009) --困难
        self.CurModePath = "PaperSprite'/Game/UI/Atlas/StarlightCelebration/RhythmGame/Frames/UI_Icon_StarLight_RhythmGame_Music4_png.UI_Icon_StarLight_RhythmGame_Music4_png'"
    end
    
    local Data = {}
    for i = 1, _G.RhythmGameMgr.MaxSatisfaction do
        local TempData = {}
        TempData.IsShow = true
        table.insert(Data, TempData)
    end
    self.SatisfactionVMList:UpdateByValues(Data)
end

function RhythmGameVM:UpdateScore(Value)
    self.SScore = Value
end

function RhythmGameVM:UpdateCombo(Value)
    self.Combo = Value
end

function RhythmGameVM:SetIsNewSatisfaction(Value)
    self.IsNewSatisfaction = Value
end

function RhythmGameVM:SetIsNewSScore(Value)
    self.IsNewSScore = Value
end

function RhythmGameVM:UpdateSatisfaction(Value)
    self.Satisfaction = Value
    self.IsSuc = self.Satisfaction > 0

    for Index, VM in ipairs(self.SatisfactionVMList:GetItems() or {}) do
        VM:SetIsShow(Index <= self.Satisfaction)
    end
end


function RhythmGameVM:UpdateResult(Mode, JudgementCounts)
    self.SatisfactionText = self.Satisfaction .. "/" .. _G.RhythmGameMgr.MaxSatisfaction
    self.PerfectHits = JudgementCounts[_G.RhythmGameMgr.Judgement.PERFECT] or 0
    self.GreatHits = JudgementCounts[_G.RhythmGameMgr.Judgement.GREAT] or 0
    self.GoodHits = JudgementCounts[_G.RhythmGameMgr.Judgement.GOOD] or 0
    self.Misses = JudgementCounts[_G.RhythmGameMgr.Judgement.MISS] or 0
    
    -- 判断是否满连（无MISS）
    self.IsFullCombo = self.Misses == 0
    self.IsPerfectCombo = false
    if self.IsFullCombo then
        if self.GreatHits == 0 and self.GoodHits == 0 then
            self.IsPerfectCombo = true
            self.FullComboText = _G.LSTR(1710010) -- 完美连击
        else
            self.FullComboText = _G.LSTR(1710011) -- 满连
        end
    end

    local GameGlobalCfg = require("TableCfg/GameGlobalCfg")
    local ProtoRes = require ("Protocol/ProtoRes")
    local TableData = nil
    if Mode == _G.RhythmGameMgr.GameMode.EASY then
        TableData = GameGlobalCfg:FindValue(ProtoRes.Game.game_global_cfg_id.GAME_CFG_STAR_LIGHT_MUSIC_NORMAL_REWARD_CFG, "Value")
    else
        TableData = GameGlobalCfg:FindValue(ProtoRes.Game.game_global_cfg_id.GAME_CFG_STAR_LIGHT_MUSIC_HARD_REWARD_CFG, "Value")
    end
    
    if TableData then
        if self.IsPerfectCombo then
            self.LootID = TableData[1] or 0
        elseif self.IsFullCombo then
            self.LootID = TableData[2] or 0
        elseif self.IsSuc then
            self.LootID = TableData[3] or 0
        end
    end
end

function RhythmGameVM:UpdateDebugText(JudgementCounts)
    self.PerfectHits = JudgementCounts[_G.RhythmGameMgr.Judgement.PERFECT] or 0
    self.GreatHits = JudgementCounts[_G.RhythmGameMgr.Judgement.GREAT] or 0
    self.GoodHits = JudgementCounts[_G.RhythmGameMgr.Judgement.GOOD] or 0
    self.Misses = JudgementCounts[_G.RhythmGameMgr.Judgement.MISS] or 0

    self.IsFullCombo = self.Misses == 0
    self.IsPerfectCombo = false
    if self.IsFullCombo then
        if self.GreatHits == 0 and self.GoodHits == 0 then
            self.IsPerfectCombo = true
        end
    end
    
    local DebugLines = {
        string.format("PERFECT: %d", self.PerfectHits),
        string.format("GREAT: %d", self.GreatHits),
        string.format("GOOD: %d", self.GoodHits),
        string.format("MISS: %d", self.Misses),
        string.format("满连: %s", self.IsFullCombo and "Yes" or "No"),
        string.format("完美连击: %s", self.IsPerfectCombo and "Yes" or "No"),
    }

    self.DebugText = table.concat(DebugLines, "\n")
end


return RhythmGameVM