---
--- Generated by Luanalysis
--- Created by skysong.
--- DateTime: 2022/12/15 9:25
---

local LuaClass = require("Core/LuaClass")
local UIAdapterTableView = require("UI/Adapter/UIAdapterTableView")

---@class UIAdventureAdapterTableView : UIAdapterTableView
local UIAdventureAdapterTableView = LuaClass(UIAdapterTableView, true)

---OnTableItemClicked
---@param Index number
---@private
function UIAdventureAdapterTableView:SetItemSelectState(Index)
    if nil ~= Index then
        local SubViews = self.SubViews
        if nil == SubViews then
            return
        end

        for i = 1, #SubViews do
            local v = SubViews[i]
            if Index == i then
                v:OnSelectChanged(true)
            else
                v:OnSelectChanged(false)
            end
        end
    end
end

---OnTableItemClicked
---@param ItemView UIView
function UIAdventureAdapterTableView:OnTableItemClicked(ItemView, Index, ItemData)
    self.Super:OnTableItemClicked(ItemView, Index, ItemData)
    self:SetItemSelectState(Index)
end

---SetSelectedIndex
---@param Index number @下标，从1开始
---@return boolean  @是否设置成功
function UIAdventureAdapterTableView:SetSelectedIndex(Index)
    self:SetItemSelectState(Index)
    return self.Super:SetSelectedIndex(Index)
end


return UIAdventureAdapterTableView
