---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by richyczhou.
--- DateTime: 2024/6/27 10:33
---


local LuaClass = require("Core/LuaClass")
local UIViewModel = require("UI/UIViewModel")

---@class LoginEmailVM : UIViewModel
---@field Email string
local LoginEmailVM = LuaClass(UIViewModel)

---Ctor
function LoginEmailVM:Ctor()
    self.Email = nil
    self.VerifyCode = nil

    self.CodeTotalTime = 180
    self.VerifyCodeSentTime = 0
    self.IsCountdownTime = false
end

function LoginEmailVM:OnInit()
end

function LoginEmailVM:OnBegin()
end

function LoginEmailVM:OnEnd()
end

function LoginEmailVM:OnShutdown()
end

---SetEmail
---@param Email string
function LoginEmailVM:SetEmail(Email)
    --print("[LoginEmailVM:SetEmail] ", Email)
    self.Email = Email
end

---GetEmail
---@return string
function LoginEmailVM:GetEmail()
    return self.Email
end

---SetVerifyCode
---@param VerifyCode string
function LoginEmailVM:SetVerifyCode(VerifyCode)
    --print("[LoginEmailVM:SetVerifyCode] ", VerifyCode)
    self.VerifyCode = VerifyCode
end

---GetVerifyCode
---@return string
function LoginEmailVM:GetVerifyCode()
    return self.VerifyCode
end

return LoginEmailVM