---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by richyczhou.
--- DateTime: 2024/6/26 20:00
---

local LuaClass = require("Core/LuaClass")
local UIViewModel = require("UI/UIViewModel")
local UIBindableList = require("UI/UIBindableList")
local LoginLanguageItemVM = require("Game/LoginNew/VM/Item/LoginLanguageItemVM")
local SettingsDefine = require("Game/Settings/SettingsDefine")

--local FLOG_INFO = _G.FLOG_INFO
--local FLOG_ERROR = _G.FLOG_ERROR

---@class LoginLanguageVM : UIViewModel
local LoginLanguageVM = LuaClass(UIViewModel)

---Ctor
function LoginLanguageVM:Ctor()
    self.LanguageIndex = 1

    ---@type UIBindableList
    self.LanguageList = UIBindableList.New(LoginLanguageItemVM)
end

function LoginLanguageVM:OnInit()
end

function LoginLanguageVM:OnBegin()
end

function LoginLanguageVM:OnEnd()
end

function LoginLanguageVM:OnShutdown()
end

function LoginLanguageVM:UpdateLanguageList()
    local LanguageList = {}

    for i = 1, #SettingsDefine.LanguagesDesc do
        local LanguageItemData = { Name = SettingsDefine.LanguagesDesc[i], Index = i }
        table.insert(LanguageList, LanguageItemData)
    end

    --FLOG_INFO("LoginLanguageVM:UpdateLanguageList")
    self.LanguageList:UpdateByValues(LanguageList)
end

return LoginLanguageVM