---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by richyczhou.
--- DateTime: 2025/4/22 19:21
---
local FLOG_INFO = _G.FLOG_INFO

local HttpDNSUtil = {}

function HttpDNSUtil.GetAddrByName(Domain)
    local Addr = _G.UE.UHttpDNSMgr.Get():GetAddrByName(Domain);
    print("[HttpDNSUtil.GetAddrByName] Addr:", Addr)
    return Addr
end

--- HttpDNS 解析域名
---@param Url string
function HttpDNSUtil.GetAddrUrl(Url)
    -- 判断 Url 是否为空
    if string.isnilorempty(Url) then
        return Url
    end

    local Domain = Url:gsub("^%w+://", ""):gsub("/.*$", ""):gsub(":%d+$", "")
    if HttpDNSUtil.IsIP(Domain) then
        return Url
    end
    FLOG_INFO("[HttpDNSUtil.GetAddrUrl] Domain: %s", Domain)

    -- 移除端口号和路径部分
    Domain = Domain:gsub(":[0-9]+", ""):gsub("/.*$", "")
    -- 移除查询参数和锚点
    Domain = Domain:gsub("%?.*$", ""):gsub("#.*$", "")

    local Addr = HttpDNSUtil.GetAddrByName(Domain)
    --Addr = "117.62.240.190;0"
    if not string.isnilorempty(Addr) then
        Addr = Addr:match("^([^;]+)") or Addr
        return Url:gsub(Domain, Addr)
    end

    return Url
end

--- 判断是否是IP地址
---@param Domain string
---@return boolean
function HttpDNSUtil.IsIP(Domain)
    if type(Domain) ~= "string" then
        return false
    end

    -- IPv4正则匹配 (如: 192.168.1.1)
    local ipv4Pattern = "^(%d+)%.(%d+)%.(%d+)%.(%d+)$"
    if Domain:match(ipv4Pattern) then
        for num in Domain:gmatch("%d+") do
            local n = tonumber(num)
            if n == nil or n < 0 or n > 255 then
                return false
            end
        end
        return true
    end

    ---- IPv6正则匹配 (简化版，如: 2001:0db8:85a3:0000:0000:8a2e:0370:7334)
    --local ipv6Pattern = "^[%x:]+$"
    --if Url:match(ipv6Pattern) and #Url <= 45 then  -- IPv6最大长度为45字符
    --    -- 简化验证，实际可能需要更严格的验证
    --    return true
    --end

    return false
end

return HttpDNSUtil