---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by richyczhou.
--- DateTime: 2024/7/4 17:00
---

local LuaClass = require("Core/LuaClass")
local LoginMgr = require("Game/Login/LoginMgr")
local UIViewModel = require("UI/UIViewModel")

---@class FriendItemVM : UIViewModel
local FriendItemVM = LuaClass(UIViewModel)

---Ctor
function FriendItemVM:Ctor()
    self.Name = nil
    self.IconUrl = nil
    self.WorldID = nil
    self.State = nil
    self.Tag = nil
end

function FriendItemVM:UpdateVM(Value)
    self.Name = Value.Name
    self.IconUrl = Value.IconUrl
    self.WorldID = Value.WorldID

    local ServerListItem = LoginMgr.AllMapleNodeInfo[self.WorldID]
    if ServerListItem then
        --self.Name = ServerListItem.Name
        --self.Host = ServerListItem.Host
        self.Tag = ServerListItem.Tag
        self.State = ServerListItem.State
    else
        --self.Name = nil
        --self.Host = nil
        self.State = nil
        self.Tag = nil
    end
end

function FriendItemVM:IsEqualVM(Value)
    --return nil ~= Value and Value.Type == self.Type
end

return FriendItemVM