---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by richyczhou.
--- DateTime: 2024/6/28 14:07
---
---
---
local LoginMgr = require("Game/Login/LoginMgr")
local LuaClass = require("Core/LuaClass")
local UIViewModel = require("UI/UIViewModel")
--local ServerListItemVM = require("Game/LoginNew/VM/Item/ServerListItemVM")

---@class FriendServerListItemVM : UIViewModel
local FriendServerListItemVM = LuaClass(UIViewModel)

---Ctor
function FriendServerListItemVM:Ctor()
    self.FriendName = nil
    self.HeadUrl = nil
    self.RoleID = nil
    self.RoleName = nil
    self.Level = nil
    self.Prof = nil
    self.LoginTime = nil
    self.HeadPortraitID = nil
    self.OpenID = nil
    self.IsOnline = nil

    self.WorldID = nil
    self.Name = nil
    self.Host = nil
    self.State = nil
    self.Tag = nil
end

function FriendServerListItemVM:OnInit()

end

---UpdateVM
---@param List table
function FriendServerListItemVM:UpdateVM(List)
    self.FriendName = List.Name
    self.HeadUrl = List.HeadUrl
    print("[FriendServerListItemVM:UpdateVM] Name:", self.FriendName)

    self.RoleID = List.Role.RoleID
    self.RoleName = List.Role.Name
    self.Level = List.Role.Level
    self.Prof = List.Role.Prof
    self.LoginTime = List.Role.LoginTime
    self.HeadPortraitID = List.Role.HeadPortraitID
    self.OpenID = List.Role.OpenID
    self.IsOnline = List.Role.IsOnline

    self.WorldID = List.Role.WorldID
    local ServerListItem = LoginMgr.AllMapleNodeInfo[self.WorldID]
    if ServerListItem then
        self.Name = ServerListItem.Name
        self.Host = ServerListItem.Host
        self.Tag = ServerListItem.Tag
        self.State = ServerListItem.State
    else
        self.Name = nil
        self.Host = nil
        self.State = nil
        self.Tag = nil
    end
end

function FriendServerListItemVM:IsEqualVM(Value)
    return nil ~= Value and Value.WorldID == self.WorldID and Value.OpenID == self.OpenID
end

return FriendServerListItemVM