---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by richyczhou.
--- DateTime: 2024/6/27 22:55
---

local LuaClass = require("Core/LuaClass")
local UIViewModel = require("UI/UIViewModel")

---@class LoginMapleTabItemVM : UIViewModel
local LoginMapleTabItemVM = LuaClass(UIViewModel)

---Ctor
function LoginMapleTabItemVM:Ctor()
    self.Type = nil
    self.Desc = nil
    self.CheckIconPath = nil
    self.UnCheckIconPath = nil
end

function LoginMapleTabItemVM:UpdateVM(Value)
    self.Type = Value.Type
    self.Desc = Value.Desc
    self.CheckIconPath = Value.CheckIconPath
    self.UnCheckIconPath = Value.UnCheckIconPath
end

function LoginMapleTabItemVM:IsEqualVM(Value)
    return nil ~= Value and Value.Type == self.Type
end

return LoginMapleTabItemVM