---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by richyczhou.
--- DateTime: 2024/6/28 11:06
---
local LuaClass = require("Core/LuaClass")
local UIViewModel = require("UI/UIViewModel")

---@class ServerGroupItemVM : UIViewModel
local ServerGroupItemVM = LuaClass(UIViewModel)

---Ctor
function ServerGroupItemVM:Ctor()
    self.GroupID = nil
    self.Name = nil
    self.Key = nil
end

function ServerGroupItemVM:OnInit()

end

---UpdateVM
---@param List table
function ServerGroupItemVM:UpdateVM(List)
    self.GroupID = List.GroupID
    self.Name = List.Name
    self.Key = List.Key
end

function ServerGroupItemVM:IsEqualVM(Value)
    return nil ~= Value and Value.GroupID == self.GroupID
end

return ServerGroupItemVM