---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by richyczhou.
--- DateTime: 2024/6/28 14:07
---
---
---
local LuaClass = require("Core/LuaClass")
local UIViewModel = require("UI/UIViewModel")
local LoginMgr = require("Game/Login/LoginMgr")

local FLOG_INFO = _G.FLOG_INFO

---@class ServerListItemVM : UIViewModel
local ServerListItemVM = LuaClass(UIViewModel)

---Ctor
function ServerListItemVM:Ctor()
    self.WorldID = nil
    self.Name = nil
    self.Host = nil
    self.State = nil
    self.Tag = nil
    self.CustomValue1 = nil
    self.CustomValue2 = nil

    self.RoleID = nil
    --self.RoleName = nil
    --self.Level = nil
    --self.Prof = nil
    --self.LoginTime = nil
    self.HeadPortraitID = nil

    self.HeadId = nil
    self.HeadType = nil
    self.HeadUrl = nil
    self.Gender = nil
    self.Race = nil
    self.Tribe = nil
end

function ServerListItemVM:OnInit()

end

---UpdateVM
---@param List table
function ServerListItemVM:UpdateVM(List)
    -- self.RecommendOrMyList:UpdateByValues(self.MyServerListData)
    self.WorldID = List.WorldID
    self.Name = List.Name
    self.Host = List.Host
    self.State = List.State
    self.Tag = List.Tag
    self.CustomValue1 = List.CustomValue1
    self.CustomValue2 = List.CustomValue2
    --FLOG_INFO("[Login] ServerListItemVM:UpdateVM Name:%s, State:%d", List.Name, List.State)

    if LoginMgr.AllMyRoles then
        ---@type RoleItem
        local RoleItem = LoginMgr.AllMyRoles[List.WorldID]
        --print("[Login] ServerListItemVM:UpdateVM RoleItem:", List.WorldID, RoleItem)
        if RoleItem then
            --self.RoleID = RoleItem.RoleID
            --self.RoleName = RoleItem.Name
            --self.Level = RoleItem.Level
            --self.Prof = RoleItem.Prof
            --self.LoginTime = RoleItem.LoginTime
            self.HeadPortraitID = RoleItem.HeadPortraitID

            if RoleItem.HeadData then
                self.HeadId = RoleItem.HeadData.HeadID
                self.HeadType = RoleItem.HeadData.HeadType
                self.HeadUrl = RoleItem.HeadData.HeadUrl
            end
            self.Gender = RoleItem.Gender
            self.Race = RoleItem.Race
            self.Tribe = RoleItem.Tribe
        else
            --self.RoleID = nil
            --self.RoleName = nil
            --self.Level = nil
            --self.Prof = nil
            --self.LoginTime = nil
            self.HeadPortraitID = nil

            self.HeadId = nil
            self.HeadType = nil
            self.HeadUrl = nil
            self.Gender = nil
            self.Race = nil
            self.Tribe = nil
        end
    end
end

function ServerListItemVM:IsEqualVM(Value)
    return nil ~= Value and Value.WorldID == self.WorldID
end

return ServerListItemVM