---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by richyczhou.
--- DateTime: 2024/6/28 16:48
---

local LuaClass = require("Core/LuaClass")
local UIViewModel = require("UI/UIViewModel")

---@class ServerRecommendItemVM : UIViewModel
local ServerRecommendItemVM = LuaClass(UIViewModel)

---Ctor
function ServerRecommendItemVM:Ctor()
    self.WorldID = nil
    self.Name = nil
    self.Host = nil
    self.State = nil
end

function ServerRecommendItemVM:OnInit()

end

---UpdateVM
---@param List table
function ServerRecommendItemVM:UpdateVM(List)
    self.WorldID = List.WorldID
    self.Name = List.Name
    self.Host = List.Host
    self.State = List.State
end

function ServerRecommendItemVM:IsEqualVM(Value)
    return nil ~= Value and Value.WorldID == self.WorldID
end

return ServerRecommendItemVM