---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2024/11/12 20:08
---


local LuaClass = require("Core/LuaClass")
local UIViewModel = require("UI/UIViewModel")
local UIUtil = require("Utils/UIUtil")
local ItemUtil = require("Utils/ItemUtil")

---@class ChocoboRaceNpcChallengeVM : UIViewModel
local ChocoboRaceNpcChallengeVM = LuaClass(UIViewModel)

---Ctor
function ChocoboRaceNpcChallengeVM:Ctor()
end

function ChocoboRaceNpcChallengeVM:UpdateVM(Data)
end

return ChocoboRaceNpcChallengeVM