---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by richyczhou.
--- DateTime: 2025/4/24 21:41
---
local LoginNewDefine = require("Game/LoginNew/LoginNewDefine")
local FLOG_INFO = _G.FLOG_INFO

local LoginNewUnitTest = {}

function LoginNewUnitTest:SetTreeInfoType(WorldId, NewFlag)
    FLOG_INFO("[LoginNewUnitTest:SetTreeInfoType] WorldId:%d, NewFlag:%d", WorldId, NewFlag)
    self.WorldId = WorldId
    self.NewFlag = NewFlag
end

_G.LoginNewUnitTest = LoginNewUnitTest

return LoginNewUnitTest