-- AUTO GENERATED CODE BEGIN, PLEASE DON'T MODIFY

local CfgBase = require("TableCfg/CfgBase")

local CS = {
    _2_1 = 'Texture2D\'/Game/Assets/Icon/900000/UI_Icon_900257.UI_Icon_900257\'',
    _2_2 = 'Texture2D\'/Game/Assets/Icon/061000/UI_Icon_061816.UI_Icon_061816\'',
    _2_3 = 'Texture2D\'/Game/Assets/Icon/061000/UI_Icon_061809.UI_Icon_061809\'',
    _2_4 = 'Texture2D\'/Game/Assets/Icon/061000/UI_Icon_061808.UI_Icon_061808\'',
    _2_5 = 'Texture2D\'/Game/Assets/Icon/061000/UI_Icon_061810.UI_Icon_061810\'',
    _2_6 = 'Texture2D\'/Game/Assets/Icon/900000/UI_Icon_903818.UI_Icon_903818\'',
    _2_7 = 'Texture2D\'/Game/Assets/Icon/061000/UI_Icon_061821.UI_Icon_061821\'',
    _2_8 = 'Texture2D\'/Game/Assets/Icon/061000/UI_Icon_061817.UI_Icon_061817\'',
    _2_9 = 'Texture2D\'/Game/Assets/Icon/061000/UI_Icon_061813.UI_Icon_061813\'',
    _2_10 = 'Texture2D\'/Game/Assets/Icon/061000/UI_Icon_061815.UI_Icon_061815\'',
    _2_11 = 'Texture2D\'/Game/Assets/Icon/061000/UI_Icon_061812.UI_Icon_061812\'',
    _2_12 = 'Texture2D\'/Game/Assets/Icon/061000/UI_Icon_061814.UI_Icon_061814\'',
    _2_13 = 'Texture2D\'/Game/Assets/Icon/061000/UI_Icon_061807.UI_Icon_061807\'',
    _2_14 = 'Texture2D\'/Game/Assets/Icon/061000/UI_Icon_061805.UI_Icon_061805\'',
}

---@class ChallengeLogCfg : CfgBase
local ChallengeLogCfg = {
	TableName = "c_challenge_log_cfg",
    LruKeyType = nil,
	KeyName = "LogID",
    bEncrypted = false,
	Localization = {
        Config = {
            {
                Name = 'Desc',
            },
		}
    },
    DefaultValues = {
        Category = 10,
        Count = 5,
        FinishMsg = '危命任务最高评价次数1',
        Icon = 'Texture2D\'/Game/Assets/Icon/900000/UI_Icon_900258.UI_Icon_900258\'',
        JumpID = 2,
        LogID = 1,
        LootID = 85000001,
        ModuleID = 0,
        PWorldID = 0,
        _Produce = '[{"Num":0,"ID":0},{"Num":0,"ID":0},{"Num":0,"ID":0},{"Num":0,"ID":0}]',
        Type = 1,
    },
	LuaData = {
        {
            Category = 3,
            Icon = CS._2_5,
            JumpID = 12,
            Type = 13,
        },
        {
            Category = 3,
            Count = 10,
            FinishMsg = '危命任务最高评价次数2',
            Icon = CS._2_5,
            JumpID = 12,
            LogID = 2,
            LootID = 85000002,
            Type = 13,
        },
        {
            Count = 3,
            FinishMsg = '小游戏次数',
            Icon = CS._2_6,
            JumpID = 14,
            LogID = 4,
            LootID = 85000004,
            ModuleID = 148,
            Type = 34,
        },
        {
            Count = 100,
            FinishMsg = '小游戏获得金碟币',
            Icon = CS._2_6,
            JumpID = 14,
            LogID = 5,
            LootID = 85000005,
            ModuleID = 148,
            Type = 35,
        },
        {
            FinishMsg = '参加机遇任务次数',
            Icon = CS._2_7,
            JumpID = 15,
            LogID = 6,
            LootID = 85000006,
            ModuleID = 148,
            Type = 36,
        },
        {
            Count = 3,
            FinishMsg = '机遇任务次数',
            Icon = CS._2_7,
            JumpID = 15,
            LogID = 7,
            LootID = 85000007,
            ModuleID = 148,
            Type = 37,
        },
        {
            Count = 3,
            FinishMsg = '参加陆行鸟竞赛数次1',
            LogID = 8,
            LootID = 85000008,
            ModuleID = 140,
            Type = 38,
        },
        {
            Count = 10,
            FinishMsg = '参加陆行鸟竞赛数次2',
            LogID = 9,
            LootID = 85000009,
            ModuleID = 140,
            Type = 38,
        },
        {
            Count = 1,
            FinishMsg = '陆行鸟竞赛胜利次数1',
            LogID = 10,
            LootID = 85000010,
            ModuleID = 140,
            Type = 39,
        },
        {
            FinishMsg = '陆行鸟竞赛胜利次数2',
            LogID = 11,
            LootID = 85000011,
            ModuleID = 140,
            Type = 39,
        },
        {
            Count = 10,
            FinishMsg = '九宫幻卡对局次数',
            Icon = CS._2_1,
            JumpID = 16,
            LogID = 12,
            LootID = 85000012,
            ModuleID = 138,
            Type = 40,
        },
        {
            FinishMsg = '九宫幻卡取胜次数',
            Icon = CS._2_1,
            JumpID = 16,
            LogID = 13,
            LootID = 85000013,
            ModuleID = 138,
            Type = 41,
        },
        {
            FinishMsg = '幻卡对局室对局次数',
            Icon = CS._2_1,
            JumpID = 13,
            LogID = 14,
            LootID = 85000014,
            ModuleID = 138,
            Type = 42,
        },
        {
            Count = 3,
            FinishMsg = '幻卡对局室取胜次数',
            Icon = CS._2_1,
            JumpID = 13,
            LogID = 15,
            LootID = 85000015,
            ModuleID = 138,
            Type = 43,
        },
        {
            Category = 5,
            Count = 100,
            FinishMsg = '采集次数',
            Icon = CS._2_2,
            JumpID = 3,
            LogID = 16,
            LootID = 85000016,
            ModuleID = 104,
            Type = 18,
        },
        {
            Category = 5,
            Count = 30,
            FinishMsg = '获得额外采集奖励次数',
            Icon = CS._2_2,
            JumpID = 3,
            LogID = 17,
            LootID = 85000017,
            ModuleID = 104,
            Type = 48,
        },
        {
            Category = 5,
            Count = 30,
            FinishMsg = '钓鱼次数',
            Icon = CS._2_2,
            JumpID = 4,
            LogID = 18,
            LootID = 85000018,
            ModuleID = 106,
            Type = 20,
        },
        {
            Category = 5,
            Count = 10,
            FinishMsg = '优质钓鱼次数',
            Icon = CS._2_2,
            JumpID = 4,
            LogID = 19,
            LootID = 85000019,
            ModuleID = 106,
            Type = 21,
        },
        {
            Category = 5,
            Count = 50,
            FinishMsg = '制作数量',
            Icon = CS._2_8,
            JumpID = 5,
            LogID = 20,
            LootID = 85000020,
            ModuleID = 105,
            Type = 16,
        },
        {
            Category = 5,
            Count = 30,
            FinishMsg = '优质制作数量',
            Icon = CS._2_8,
            JumpID = 5,
            LogID = 21,
            LootID = 85000021,
            ModuleID = 105,
            Type = 17,
        },
        {
            Category = 8,
            FinishMsg = '军需品补给品筹备次数1',
            Icon = CS._2_9,
            JumpID = 6,
            LogID = 22,
            LootID = 85000022,
            ModuleID = 151,
            Type = 29,
        },
        {
            Category = 8,
            Count = 10,
            FinishMsg = '军需品补给品筹备次数2',
            Icon = CS._2_9,
            JumpID = 6,
            LogID = 23,
            LootID = 85000025,
            ModuleID = 151,
            Type = 29,
        },
        {
            Category = 7,
            FinishMsg = '友好部族日常任务次数1',
            Icon = CS._2_10,
            JumpID = 0,
            LogID = 24,
            LootID = 85000028,
            ModuleID = 156,
            Type = 28,
        },
        {
            Category = 7,
            Count = 15,
            FinishMsg = '友好部族日常任务次数2',
            Icon = CS._2_10,
            JumpID = 0,
            LogID = 25,
            LootID = 85000029,
            ModuleID = 156,
            Type = 28,
        },
        {
            Category = 4,
            FinishMsg = '理符任务次数1',
            Icon = CS._2_11,
            JumpID = 7,
            LogID = 26,
            LootID = 85000030,
            ModuleID = 132,
            Type = 14,
        },
        {
            Category = 4,
            Count = 20,
            FinishMsg = '理符任务次数2',
            Icon = CS._2_11,
            JumpID = 7,
            LogID = 27,
            LootID = 85000031,
            ModuleID = 132,
            Type = 14,
        },
        {
            Category = 6,
            Count = 3,
            FinishMsg = '藏宝图采集次数',
            Icon = CS._2_3,
            JumpID = 10,
            LogID = 28,
            LootID = 85000035,
            ModuleID = 146,
            Type = 25,
        },
        {
            Category = 6,
            FinishMsg = '藏宝图挖掘次数',
            Icon = CS._2_3,
            JumpID = 10,
            LogID = 29,
            LootID = 85000036,
            ModuleID = 146,
            Type = 26,
        },
        {
            Category = 6,
            FinishMsg = '宝物库宝箱打开次数',
            Icon = CS._2_3,
            JumpID = 10,
            LogID = 30,
            LootID = 85000034,
            ModuleID = 168,
            Type = 27,
        },
        {
            Category = 1,
            Count = 4,
            FinishMsg = '挑战每日随机副本次数1',
            Icon = CS._2_4,
            JumpID = 8,
            LogID = 31,
            LootID = 85000038,
            ModuleID = 122,
        },
        {
            Category = 1,
            Count = 8,
            FinishMsg = '挑战每日随机副本次数2',
            Icon = CS._2_4,
            JumpID = 8,
            LogID = 32,
            LootID = 85000039,
            ModuleID = 122,
        },
        {
            Category = 1,
            Count = 12,
            FinishMsg = '挑战每日随机副本次数3',
            Icon = CS._2_4,
            JumpID = 8,
            LogID = 33,
            LootID = 85000040,
            ModuleID = 122,
        },
        {
            Category = 1,
            Count = 20,
            FinishMsg = '搭档讨伐数量1',
            Icon = CS._2_12,
            JumpID = 9,
            LogID = 36,
            LootID = 85000041,
            ModuleID = 125,
            Type = 5,
        },
        {
            Category = 1,
            Count = 100,
            FinishMsg = '搭档讨伐数量2',
            Icon = CS._2_12,
            JumpID = 9,
            LogID = 37,
            LootID = 85000042,
            ModuleID = 125,
            Type = 5,
        },
        {
            Category = 1,
            FinishMsg = '最优队员推荐次数',
            Icon = 'Texture2D\'/Game/Assets/Icon/061000/UI_Icon_061818.UI_Icon_061818\'',
            JumpID = 8,
            LogID = 38,
            LootID = 85000043,
            ModuleID = 111,
            Type = 4,
        },
        {
            Category = 2,
            FinishMsg = '水晶冲突参战次数1',
            Icon = CS._2_13,
            JumpID = 56,
            LogID = 39,
            LootID = 85000032,
            ModuleID = 153,
            Type = 7,
        },
        {
            Category = 2,
            Count = 10,
            FinishMsg = '水晶冲突参战次数2',
            Icon = CS._2_13,
            JumpID = 56,
            LogID = 40,
            LootID = 85000033,
            ModuleID = 153,
            Type = 7,
        },
        {
            Category = 1,
            Count = 1,
            FinishMsg = '通关究极神兵假想作战',
            Icon = CS._2_14,
            JumpID = 263,
            LogID = 41,
            LootID = 85000055,
            PWorldID = 1202022,
            Type = 51,
        },
        {
            Category = 1,
            Count = 1,
            FinishMsg = '通关利维亚桑歼殛战',
            Icon = CS._2_14,
            JumpID = 308,
            LogID = 42,
            LootID = 85000056,
            PWorldID = 1203277,
            Type = 52,
        },
	},
}

setmetatable(ChallengeLogCfg, { __index = CfgBase })

ChallengeLogCfg:InitCfg()

-- AUTO GENERATED CODE END, PLEASE DON'T MODIFY

return ChallengeLogCfg
