-- AUTO GENERATED CODE BEGIN, PLEASE DON'T MODIFY

local CfgBase = require("TableCfg/CfgBase")

local CS = {
    _1_1 = '2.2.0',
    _1_2 = '2.0.1',
    _1_3 = '2.1.0',
    _1_4 = '2.3.0',
}

---@class GatherNoteCfg : CfgBase
local GatherNoteCfg = {
	TableName = "c_gather_note_cfg",
    LruKeyType = nil,
	KeyName = "ID",
    bEncrypted = false,
	Localization = {
        Config = {
            {
                Name = 'Name',
            },
            {
                Name = 'GatheringLabel',
            },
            {
                Name = 'GatherLabel',
            },
		}
    },
    DefaultValues = {
        AcquisitionBalance = 100,
        BaseEXP = 76,
        BaseGatheringRate = 6000,
        BaseHQRate = 500,
        ChildTypeFilter = '',
        CollectionTemplate = 0,
        EXPBonus = 2440,
        EXPModify = 1,
        GatheringGrade = 50,
        GatheringJob = 37,
        GatheringStar = 0,
        ID = 1,
        InsightBalance = 100,
        IsCollection = 0,
        IsHidden = 0,
        ItemID = 66700153,
        ItemLevel = 10,
        LineageVolume = 0,
        MinAcquisition = 193,
        MinInsight = 0,
        StdAcquisition = 276,
        StdInsight = 276,
        TimeCondition = '',
        VersionName = '2.0.0',
        _GatherLabelNum = 2,
    },
	LuaData = {
        {
            BaseEXP = 5,
            EXPBonus = 193,
            GatheringGrade = 1,
            GatheringJob = 36,
            ItemID = 62400004,
            ItemLevel = 1,
            MinAcquisition = 1,
            StdAcquisition = 2,
            StdInsight = 2,
        },
        {
            BaseEXP = 5,
            EXPBonus = 200,
            GatheringGrade = 3,
            GatheringJob = 36,
            ID = 2,
            ItemID = 63000057,
            ItemLevel = 1,
            MinAcquisition = 4,
            StdAcquisition = 6,
            StdInsight = 6,
        },
        {
            BaseEXP = 5,
            EXPBonus = 207,
            GatheringGrade = 5,
            GatheringJob = 36,
            ID = 3,
            ItemID = 62900001,
            ItemLevel = 1,
            MinAcquisition = 7,
            StdAcquisition = 10,
            StdInsight = 10,
        },
        {
            BaseEXP = 9,
            EXPBonus = 241,
            GatheringGrade = 6,
            GatheringJob = 36,
            ID = 4,
            ItemID = 62400005,
            ItemLevel = 5,
            MinAcquisition = 8,
            StdAcquisition = 12,
            StdInsight = 12,
        },
        {
            BaseEXP = 9,
            EXPBonus = 248,
            GatheringGrade = 7,
            GatheringJob = 36,
            ID = 5,
            ItemID = 62400025,
            ItemLevel = 5,
            MinAcquisition = 9,
            StdAcquisition = 14,
            StdInsight = 14,
        },
        {
            BaseEXP = 9,
            EXPBonus = 248,
            GatheringGrade = 7,
            GatheringJob = 36,
            ID = 6,
            ItemID = 62400030,
            ItemLevel = 5,
            MinAcquisition = 9,
            StdAcquisition = 14,
            StdInsight = 14,
        },
        {
            BaseEXP = 9,
            EXPBonus = 255,
            GatheringGrade = 8,
            GatheringJob = 36,
            ID = 7,
            ItemID = 62900002,
            ItemLevel = 5,
            MinAcquisition = 11,
            StdAcquisition = 17,
            StdInsight = 17,
        },
        {
            BaseEXP = 9,
            EXPBonus = 255,
            GatheringGrade = 8,
            GatheringJob = 36,
            ID = 8,
            ItemID = 63000076,
            ItemLevel = 5,
            MinAcquisition = 11,
            StdAcquisition = 17,
            StdInsight = 17,
        },
        {
            BaseEXP = 10,
            EXPBonus = 263,
            GatheringGrade = 9,
            GatheringJob = 36,
            ID = 9,
            ItemID = 62400008,
            ItemLevel = 5,
            MinAcquisition = 12,
            StdAcquisition = 18,
            StdInsight = 18,
        },
        {
            BaseEXP = 12,
            EXPBonus = 283,
            GatheringGrade = 10,
            GatheringJob = 36,
            ID = 10,
            ItemID = 62400007,
            ItemLevel = 5,
            MinAcquisition = 18,
            StdAcquisition = 27,
            StdInsight = 27,
        },
        {
            BaseEXP = 13,
            EXPBonus = 318,
            GatheringGrade = 11,
            GatheringJob = 36,
            ID = 11,
            ItemID = 63000079,
            MinAcquisition = 19,
            StdAcquisition = 28,
            StdInsight = 28,
        },
        {
            BaseEXP = 13,
            EXPBonus = 318,
            GatheringGrade = 11,
            GatheringJob = 36,
            ID = 12,
            ItemID = 62400128,
            MinAcquisition = 19,
            StdAcquisition = 28,
            StdInsight = 28,
        },
        {
            BaseEXP = 13,
            EXPBonus = 328,
            GatheringGrade = 12,
            GatheringJob = 36,
            ID = 13,
            ItemID = 62400129,
            MinAcquisition = 20,
            StdAcquisition = 29,
            StdInsight = 29,
        },
        {
            BaseEXP = 13,
            EXPBonus = 339,
            GatheringGrade = 13,
            GatheringJob = 36,
            ID = 14,
            ItemID = 62400117,
            MinAcquisition = 28,
            StdAcquisition = 41,
            StdInsight = 41,
        },
        {
            BaseEXP = 14,
            EXPBonus = 350,
            GatheringGrade = 14,
            GatheringJob = 36,
            ID = 15,
            ItemID = 62400009,
            MinAcquisition = 29,
            StdAcquisition = 42,
            StdInsight = 42,
        },
        {
            BaseEXP = 14,
            EXPBonus = 350,
            GatheringGrade = 14,
            GatheringJob = 36,
            ID = 16,
            ItemID = 63000080,
            MinAcquisition = 29,
            StdAcquisition = 42,
            StdInsight = 42,
        },
        {
            BaseEXP = 14,
            EXPBonus = 363,
            GatheringGrade = 15,
            GatheringJob = 36,
            ID = 17,
            ItemID = 62400130,
            MinAcquisition = 32,
            StdAcquisition = 47,
            StdInsight = 47,
        },
        {
            BaseEXP = 20,
            EXPBonus = 472,
            GatheringGrade = 16,
            GatheringJob = 36,
            ID = 18,
            ItemID = 62400027,
            ItemLevel = 20,
            MinAcquisition = 33,
            StdAcquisition = 48,
            StdInsight = 48,
        },
        {
            BaseEXP = 20,
            EXPBonus = 489,
            GatheringGrade = 17,
            GatheringJob = 36,
            ID = 19,
            ItemID = 62400028,
            ItemLevel = 20,
            MinAcquisition = 34,
            StdAcquisition = 49,
            StdInsight = 49,
        },
        {
            BaseEXP = 20,
            EXPBonus = 489,
            GatheringGrade = 17,
            GatheringJob = 36,
            ID = 20,
            ItemID = 62400029,
            ItemLevel = 20,
            MinAcquisition = 34,
            StdAcquisition = 49,
            StdInsight = 49,
        },
        {
            BaseEXP = 21,
            EXPBonus = 508,
            GatheringGrade = 18,
            GatheringJob = 36,
            ID = 21,
            ItemID = 62400026,
            ItemLevel = 20,
            MinAcquisition = 43,
            StdAcquisition = 62,
            StdInsight = 62,
        },
        {
            BaseEXP = 21,
            EXPBonus = 527,
            GatheringGrade = 19,
            GatheringJob = 36,
            ID = 22,
            ItemID = 63000084,
            ItemLevel = 20,
            MinAcquisition = 44,
            StdAcquisition = 63,
            StdInsight = 63,
        },
        {
            BaseEXP = 21,
            EXPBonus = 527,
            GatheringGrade = 19,
            GatheringJob = 36,
            ID = 23,
            ItemID = 62400118,
            ItemLevel = 20,
            MinAcquisition = 44,
            StdAcquisition = 63,
            StdInsight = 63,
        },
        {
            BaseEXP = 22,
            EXPBonus = 543,
            GatheringGrade = 20,
            GatheringJob = 36,
            ID = 24,
            ItemID = 62400119,
            ItemLevel = 20,
            MinAcquisition = 47,
            StdAcquisition = 68,
            StdInsight = 68,
        },
        {
            BaseEXP = 22,
            EXPBonus = 543,
            GatheringGrade = 20,
            GatheringJob = 36,
            ID = 25,
            ItemID = 61300190,
            ItemLevel = 20,
            MinAcquisition = 47,
            StdAcquisition = 68,
            StdInsight = 68,
        },
        {
            BaseEXP = 22,
            EXPBonus = 543,
            GatheringGrade = 20,
            GatheringJob = 36,
            ID = 26,
            ItemLevel = 20,
            MinAcquisition = 47,
            StdAcquisition = 68,
            StdInsight = 68,
        },
        {
            BaseEXP = 22,
            EXPBonus = 624,
            GatheringGrade = 22,
            GatheringJob = 36,
            ID = 27,
            ItemID = 62400052,
            ItemLevel = 30,
            MinAcquisition = 50,
            StdAcquisition = 72,
            StdInsight = 72,
        },
        {
            BaseEXP = 22,
            EXPBonus = 639,
            GatheringGrade = 23,
            GatheringJob = 36,
            ID = 28,
            ItemID = 62400131,
            ItemLevel = 30,
            MinAcquisition = 60,
            StdAcquisition = 86,
            StdInsight = 86,
        },
        {
            BaseEXP = 22,
            EXPBonus = 639,
            GatheringGrade = 23,
            GatheringJob = 36,
            ID = 29,
            ItemID = 62400049,
            ItemLevel = 30,
            MinAcquisition = 60,
            StdAcquisition = 86,
            StdInsight = 86,
        },
        {
            BaseEXP = 22,
            EXPBonus = 639,
            GatheringGrade = 23,
            GatheringJob = 36,
            ID = 30,
            ItemID = 62400050,
            ItemLevel = 30,
            MinAcquisition = 60,
            StdAcquisition = 86,
            StdInsight = 86,
        },
        {
            BaseEXP = 22,
            EXPBonus = 655,
            GatheringGrade = 24,
            GatheringJob = 36,
            ID = 31,
            ItemID = 63000059,
            ItemLevel = 30,
            MinAcquisition = 61,
            StdAcquisition = 88,
            StdInsight = 88,
        },
        {
            BaseEXP = 22,
            EXPBonus = 655,
            GatheringGrade = 24,
            GatheringJob = 36,
            ID = 32,
            ItemID = 62400051,
            ItemLevel = 30,
            MinAcquisition = 61,
            StdAcquisition = 88,
            StdInsight = 88,
        },
        {
            BaseEXP = 22,
            EXPBonus = 670,
            GatheringGrade = 25,
            GatheringJob = 36,
            ID = 33,
            ItemID = 62400053,
            ItemLevel = 30,
            MinAcquisition = 67,
            StdAcquisition = 97,
            StdInsight = 97,
        },
        {
            BaseEXP = 22,
            EXPBonus = 670,
            GatheringGrade = 25,
            GatheringJob = 36,
            ID = 34,
            ItemID = 62400054,
            ItemLevel = 30,
            MinAcquisition = 67,
            StdAcquisition = 97,
            StdInsight = 97,
        },
        {
            BaseEXP = 22,
            EXPBonus = 670,
            GatheringGrade = 25,
            GatheringJob = 36,
            ID = 35,
            ItemID = 62400011,
            ItemLevel = 30,
            MinAcquisition = 67,
            StdAcquisition = 97,
            StdInsight = 97,
        },
        {
            BaseEXP = 23,
            EXPBonus = 753,
            GatheringGrade = 27,
            GatheringJob = 36,
            ID = 36,
            ItemID = 63000088,
            ItemLevel = 40,
            MinAcquisition = 70,
            StdAcquisition = 101,
            StdInsight = 101,
        },
        {
            BaseEXP = 24,
            EXPBonus = 789,
            GatheringGrade = 28,
            GatheringJob = 36,
            ID = 37,
            ItemID = 63000083,
            ItemLevel = 40,
            MinAcquisition = 76,
            StdAcquisition = 109,
            StdInsight = 109,
        },
        {
            BaseEXP = 24,
            EXPBonus = 789,
            GatheringGrade = 28,
            GatheringJob = 36,
            ID = 38,
            ItemID = 62400010,
            ItemLevel = 40,
            MinAcquisition = 76,
            StdAcquisition = 109,
            StdInsight = 109,
        },
        {
            BaseEXP = 25,
            EXPBonus = 826,
            GatheringGrade = 29,
            GatheringJob = 36,
            ID = 39,
            ItemID = 63000087,
            ItemLevel = 40,
            MinAcquisition = 77,
            StdAcquisition = 111,
            StdInsight = 111,
        },
        {
            BaseEXP = 27,
            EXPBonus = 862,
            GatheringGrade = 30,
            GatheringJob = 36,
            ID = 40,
            ItemID = 62400120,
            ItemLevel = 40,
            MinAcquisition = 86,
            StdAcquisition = 123,
            StdInsight = 123,
        },
        {
            BaseEXP = 27,
            EXPBonus = 862,
            GatheringGrade = 30,
            GatheringJob = 36,
            ID = 41,
            ItemID = 63000082,
            ItemLevel = 40,
            MinAcquisition = 86,
            StdAcquisition = 123,
            StdInsight = 123,
        },
        {
            BaseEXP = 28,
            EXPBonus = 949,
            GatheringGrade = 31,
            GatheringJob = 36,
            ID = 42,
            ItemID = 62400141,
            ItemLevel = 50,
            MinAcquisition = 87,
            StdAcquisition = 125,
            StdInsight = 125,
        },
        {
            BaseEXP = 28,
            EXPBonus = 949,
            GatheringGrade = 31,
            GatheringJob = 36,
            ID = 43,
            ItemID = 62400031,
            ItemLevel = 50,
            MinAcquisition = 87,
            StdAcquisition = 125,
            StdInsight = 125,
        },
        {
            BaseEXP = 29,
            EXPBonus = 985,
            GatheringGrade = 32,
            GatheringJob = 36,
            ID = 44,
            ItemID = 62400034,
            ItemLevel = 50,
            MinAcquisition = 88,
            StdAcquisition = 127,
            StdInsight = 127,
        },
        {
            BaseEXP = 30,
            EXPBonus = 1022,
            GatheringGrade = 33,
            GatheringJob = 36,
            ID = 45,
            ItemID = 62400032,
            ItemLevel = 50,
            MinAcquisition = 95,
            StdAcquisition = 136,
            StdInsight = 136,
        },
        {
            BaseEXP = 30,
            EXPBonus = 1022,
            GatheringGrade = 33,
            GatheringJob = 36,
            ID = 46,
            ItemID = 62400033,
            ItemLevel = 50,
            MinAcquisition = 95,
            StdAcquisition = 136,
            StdInsight = 136,
        },
        {
            BaseEXP = 30,
            EXPBonus = 1022,
            GatheringGrade = 33,
            GatheringJob = 36,
            ID = 47,
            ItemID = 62400132,
            ItemLevel = 50,
            MinAcquisition = 95,
            StdAcquisition = 136,
            StdInsight = 136,
        },
        {
            BaseEXP = 31,
            EXPBonus = 1058,
            GatheringGrade = 34,
            GatheringJob = 36,
            ID = 48,
            ItemID = 62400035,
            ItemLevel = 50,
            MinAcquisition = 96,
            StdAcquisition = 138,
            StdInsight = 138,
        },
        {
            BaseEXP = 31,
            EXPBonus = 1058,
            GatheringGrade = 34,
            GatheringJob = 36,
            ID = 49,
            ItemID = 62400012,
            ItemLevel = 50,
            MinAcquisition = 96,
            StdAcquisition = 138,
            StdInsight = 138,
        },
        {
            BaseEXP = 31,
            EXPBonus = 1097,
            GatheringGrade = 35,
            GatheringJob = 36,
            ID = 50,
            ItemID = 62400036,
            ItemLevel = 50,
            MinAcquisition = 104,
            StdAcquisition = 149,
            StdInsight = 149,
        },
        {
            BaseEXP = 32,
            EXPBonus = 1157,
            GatheringGrade = 36,
            GatheringJob = 36,
            ID = 51,
            ItemID = 62400039,
            ItemLevel = 60,
            MinAcquisition = 105,
            StdAcquisition = 151,
            StdInsight = 151,
        },
        {
            BaseEXP = 32,
            EXPBonus = 1167,
            GatheringGrade = 37,
            GatheringJob = 36,
            ID = 52,
            ItemID = 62400041,
            ItemLevel = 60,
            MinAcquisition = 107,
            StdAcquisition = 153,
            StdInsight = 153,
        },
        {
            BaseEXP = 33,
            EXPBonus = 1177,
            GatheringGrade = 38,
            GatheringJob = 36,
            ID = 53,
            ItemID = 62400038,
            ItemLevel = 60,
            MinAcquisition = 113,
            StdAcquisition = 162,
            StdInsight = 162,
        },
        {
            BaseEXP = 33,
            EXPBonus = 1187,
            GatheringGrade = 39,
            GatheringJob = 36,
            ID = 54,
            ItemID = 62400059,
            ItemLevel = 60,
            MinAcquisition = 114,
            StdAcquisition = 164,
            StdInsight = 164,
        },
        {
            BaseEXP = 34,
            EXPBonus = 1197,
            GatheringGrade = 40,
            GatheringJob = 36,
            ID = 55,
            ItemID = 63000085,
            ItemLevel = 60,
            MinAcquisition = 123,
            StdAcquisition = 177,
            StdInsight = 177,
        },
        {
            BaseEXP = 34,
            EXPBonus = 1197,
            GatheringGrade = 40,
            GatheringJob = 36,
            ID = 56,
            ItemID = 63000086,
            ItemLevel = 60,
            MinAcquisition = 123,
            StdAcquisition = 177,
            StdInsight = 177,
        },
        {
            BaseEXP = 34,
            EXPBonus = 1257,
            GatheringGrade = 41,
            GatheringJob = 36,
            ID = 57,
            ItemID = 62400042,
            ItemLevel = 70,
            MinAcquisition = 125,
            StdAcquisition = 179,
            StdInsight = 179,
        },
        {
            BaseEXP = 35,
            EXPBonus = 1269,
            GatheringGrade = 42,
            GatheringJob = 36,
            ID = 58,
            ItemID = 62400133,
            ItemLevel = 70,
            MinAcquisition = 126,
            StdAcquisition = 181,
            StdInsight = 181,
        },
        {
            BaseEXP = 40,
            EXPBonus = 1378,
            GatheringGrade = 43,
            GatheringJob = 36,
            ID = 59,
            ItemID = 62400013,
            ItemLevel = 70,
            MinAcquisition = 131,
            StdAcquisition = 188,
            StdInsight = 188,
        },
        {
            BaseEXP = 45,
            EXPBonus = 1486,
            GatheringGrade = 44,
            GatheringJob = 36,
            ID = 60,
            ItemID = 62400040,
            ItemLevel = 70,
            MinAcquisition = 133,
            StdAcquisition = 190,
            StdInsight = 190,
        },
        {
            BaseEXP = 45,
            EXPBonus = 1486,
            GatheringGrade = 44,
            GatheringJob = 36,
            ID = 61,
            ItemID = 62400037,
            ItemLevel = 70,
            MinAcquisition = 133,
            StdAcquisition = 190,
            StdInsight = 190,
        },
        {
            BaseEXP = 50,
            EXPBonus = 1595,
            GatheringGrade = 45,
            GatheringJob = 36,
            ID = 62,
            ItemID = 62400143,
            ItemLevel = 70,
            MinAcquisition = 142,
            StdAcquisition = 203,
            StdInsight = 203,
        },
        {
            BaseEXP = 61,
            EXPBonus = 1862,
            GatheringGrade = 47,
            GatheringJob = 36,
            ID = 63,
            ItemID = 62400127,
            ItemLevel = 80,
            MinAcquisition = 144,
            StdAcquisition = 207,
            StdInsight = 207,
        },
        {
            BaseEXP = 71,
            EXPBonus = 2080,
            GatheringGrade = 49,
            GatheringJob = 36,
            ID = 64,
            ItemID = 62400014,
            ItemLevel = 80,
            MinAcquisition = 151,
            StdAcquisition = 216,
            StdInsight = 216,
        },
        {
            EXPBonus = 2240,
            GatheringJob = 36,
            ID = 65,
            ItemID = 62900008,
            ItemLevel = 90,
            MinAcquisition = 160,
            StdAcquisition = 229,
            StdInsight = 229,
        },
        {
            GatheringJob = 36,
            GatheringStar = 1,
            ID = 66,
            ItemID = 62400055,
            ItemLevel = 130,
            LineageVolume = 1,
            VersionName = CS._1_2,
            _GatherLabelNum = 3,
        },
        {
            GatheringJob = 36,
            GatheringStar = 1,
            ID = 67,
            ItemID = 62400016,
            ItemLevel = 130,
            LineageVolume = 1,
            VersionName = CS._1_2,
            _GatherLabelNum = 3,
        },
        {
            GatheringJob = 36,
            GatheringStar = 1,
            ID = 68,
            ItemID = 62400019,
            ItemLevel = 130,
            LineageVolume = 1,
            VersionName = CS._1_2,
            _GatherLabelNum = 3,
        },
        {
            GatheringJob = 36,
            GatheringStar = 1,
            ID = 69,
            ItemID = 62400134,
            ItemLevel = 130,
            LineageVolume = 1,
            VersionName = CS._1_2,
            _GatherLabelNum = 3,
        },
        {
            GatheringJob = 36,
            GatheringStar = 1,
            ID = 70,
            ItemID = 63000124,
            ItemLevel = 130,
            LineageVolume = 1,
            VersionName = CS._1_2,
            _GatherLabelNum = 3,
        },
        {
            GatheringJob = 36,
            GatheringStar = 1,
            ID = 71,
            ItemID = 62400146,
            ItemLevel = 130,
            LineageVolume = 1,
            VersionName = CS._1_3,
            _GatherLabelNum = 3,
        },
        {
            GatheringJob = 36,
            GatheringStar = 1,
            ID = 72,
            ItemID = 62400147,
            ItemLevel = 130,
            LineageVolume = 1,
            VersionName = CS._1_3,
            _GatherLabelNum = 3,
        },
        {
            EXPBonus = 2590,
            GatheringJob = 36,
            GatheringStar = 1,
            ID = 73,
            ItemID = 62400043,
            ItemLevel = 160,
            LineageVolume = 2,
            MinAcquisition = 235,
            StdAcquisition = 336,
            StdInsight = 336,
            VersionName = CS._1_1,
            _GatherLabelNum = 3,
        },
        {
            EXPBonus = 2590,
            GatheringJob = 36,
            GatheringStar = 1,
            ID = 74,
            ItemID = 62400044,
            ItemLevel = 160,
            LineageVolume = 2,
            MinAcquisition = 235,
            StdAcquisition = 336,
            StdInsight = 336,
            VersionName = CS._1_1,
            _GatherLabelNum = 3,
        },
        {
            EXPBonus = 2590,
            GatheringJob = 36,
            GatheringStar = 1,
            ID = 75,
            ItemID = 62400045,
            ItemLevel = 160,
            LineageVolume = 2,
            MinAcquisition = 235,
            StdAcquisition = 336,
            StdInsight = 336,
            VersionName = CS._1_1,
            _GatherLabelNum = 3,
        },
        {
            EXPBonus = 2590,
            GatheringJob = 36,
            GatheringStar = 1,
            ID = 76,
            ItemID = 62400046,
            ItemLevel = 160,
            LineageVolume = 2,
            MinAcquisition = 235,
            StdAcquisition = 336,
            StdInsight = 336,
            VersionName = CS._1_1,
            _GatherLabelNum = 3,
        },
        {
            EXPBonus = 2590,
            GatheringJob = 36,
            GatheringStar = 1,
            ID = 77,
            ItemID = 62400047,
            ItemLevel = 160,
            LineageVolume = 2,
            MinAcquisition = 235,
            StdAcquisition = 336,
            StdInsight = 336,
            VersionName = CS._1_1,
            _GatherLabelNum = 3,
        },
        {
            EXPBonus = 2590,
            GatheringJob = 36,
            GatheringStar = 1,
            ID = 78,
            ItemID = 62400048,
            ItemLevel = 160,
            LineageVolume = 2,
            MinAcquisition = 235,
            StdAcquisition = 336,
            StdInsight = 336,
            VersionName = CS._1_1,
            _GatherLabelNum = 3,
        },
        {
            EXPBonus = 2590,
            GatheringJob = 36,
            GatheringStar = 2,
            ID = 79,
            ItemID = 62400018,
            ItemLevel = 160,
            LineageVolume = 2,
            MinAcquisition = 235,
            StdAcquisition = 336,
            StdInsight = 336,
            VersionName = CS._1_1,
            _GatherLabelNum = 3,
        },
        {
            EXPBonus = 2590,
            GatheringJob = 36,
            GatheringStar = 2,
            ID = 80,
            ItemID = 62400156,
            ItemLevel = 160,
            LineageVolume = 2,
            MinAcquisition = 235,
            StdAcquisition = 336,
            StdInsight = 336,
            VersionName = CS._1_1,
            _GatherLabelNum = 3,
        },
        {
            AcquisitionBalance = 110,
            EXPBonus = 2590,
            GatheringJob = 36,
            GatheringStar = 2,
            ID = 81,
            InsightBalance = 110,
            ItemID = 62400155,
            ItemLevel = 160,
            LineageVolume = 2,
            MinAcquisition = 258,
            StdAcquisition = 369,
            StdInsight = 369,
            VersionName = CS._1_4,
            _GatherLabelNum = 3,
        },
        {
            BaseEXP = 5,
            EXPBonus = 193,
            GatheringGrade = 1,
            ID = 82,
            ItemID = 63000074,
            ItemLevel = 1,
            MinAcquisition = 1,
            StdAcquisition = 2,
            StdInsight = 2,
        },
        {
            BaseEXP = 6,
            EXPBonus = 197,
            GatheringGrade = 2,
            ID = 83,
            ItemID = 63000066,
            ItemLevel = 1,
            MinAcquisition = 2,
            StdAcquisition = 4,
            StdInsight = 4,
        },
        {
            BaseEXP = 6,
            EXPBonus = 197,
            GatheringGrade = 2,
            ID = 84,
            ItemID = 62300111,
            ItemLevel = 1,
            MinAcquisition = 2,
            StdAcquisition = 4,
            StdInsight = 4,
        },
        {
            BaseEXP = 5,
            EXPBonus = 200,
            GatheringGrade = 3,
            ID = 85,
            ItemID = 62600020,
            ItemLevel = 1,
            MinAcquisition = 4,
            StdAcquisition = 6,
            StdInsight = 6,
        },
        {
            BaseEXP = 5,
            EXPBonus = 203,
            GatheringGrade = 4,
            ID = 86,
            ItemID = 62300073,
            ItemLevel = 1,
            MinAcquisition = 5,
            StdAcquisition = 8,
            StdInsight = 8,
        },
        {
            BaseEXP = 5,
            EXPBonus = 207,
            GatheringGrade = 5,
            ID = 87,
            ItemID = 63000078,
            ItemLevel = 1,
            MinAcquisition = 7,
            StdAcquisition = 10,
            StdInsight = 10,
        },
        {
            BaseEXP = 5,
            EXPBonus = 207,
            GatheringGrade = 5,
            ID = 88,
            ItemID = 62600036,
            ItemLevel = 1,
            MinAcquisition = 7,
            StdAcquisition = 10,
            StdInsight = 10,
        },
        {
            BaseEXP = 9,
            EXPBonus = 241,
            GatheringGrade = 6,
            ID = 89,
            ItemID = 62700028,
            ItemLevel = 5,
            MinAcquisition = 8,
            StdAcquisition = 12,
            StdInsight = 12,
        },
        {
            BaseEXP = 9,
            EXPBonus = 241,
            GatheringGrade = 6,
            ID = 90,
            ItemID = 63000094,
            ItemLevel = 5,
            MinAcquisition = 8,
            StdAcquisition = 12,
            StdInsight = 12,
        },
        {
            BaseEXP = 9,
            EXPBonus = 248,
            GatheringGrade = 7,
            ID = 91,
            ItemID = 62300055,
            ItemLevel = 5,
            MinAcquisition = 9,
            StdAcquisition = 14,
            StdInsight = 14,
        },
        {
            BaseEXP = 9,
            EXPBonus = 255,
            GatheringGrade = 8,
            ID = 92,
            ItemID = 62600023,
            ItemLevel = 5,
            MinAcquisition = 11,
            StdAcquisition = 17,
            StdInsight = 17,
        },
        {
            BaseEXP = 10,
            EXPBonus = 263,
            GatheringGrade = 9,
            ID = 93,
            ItemID = 62300049,
            ItemLevel = 5,
            MinAcquisition = 12,
            StdAcquisition = 18,
            StdInsight = 18,
        },
        {
            BaseEXP = 10,
            EXPBonus = 263,
            GatheringGrade = 9,
            ID = 94,
            ItemID = 62600042,
            ItemLevel = 5,
            MinAcquisition = 12,
            StdAcquisition = 18,
            StdInsight = 18,
        },
        {
            BaseEXP = 10,
            EXPBonus = 263,
            GatheringGrade = 9,
            ID = 95,
            ItemID = 62700018,
            ItemLevel = 5,
            MinAcquisition = 12,
            StdAcquisition = 18,
            StdInsight = 18,
        },
        {
            BaseEXP = 12,
            EXPBonus = 283,
            GatheringGrade = 10,
            ID = 96,
            ItemID = 62700029,
            ItemLevel = 5,
            MinAcquisition = 18,
            StdAcquisition = 27,
            StdInsight = 27,
        },
        {
            BaseEXP = 12,
            EXPBonus = 283,
            GatheringGrade = 10,
            ID = 97,
            ItemID = 62300076,
            ItemLevel = 5,
            MinAcquisition = 18,
            StdAcquisition = 27,
            StdInsight = 27,
        },
        {
            BaseEXP = 13,
            EXPBonus = 318,
            GatheringGrade = 11,
            ID = 98,
            ItemID = 62300068,
            MinAcquisition = 19,
            StdAcquisition = 28,
            StdInsight = 28,
        },
        {
            BaseEXP = 13,
            EXPBonus = 318,
            GatheringGrade = 11,
            ID = 99,
            ItemID = 62300054,
            MinAcquisition = 19,
            StdAcquisition = 28,
            StdInsight = 28,
        },
        {
            BaseEXP = 13,
            EXPBonus = 318,
            GatheringGrade = 11,
            ID = 100,
            ItemID = 62300069,
            MinAcquisition = 19,
            StdAcquisition = 28,
            StdInsight = 28,
        },
        {
            BaseEXP = 13,
            EXPBonus = 318,
            GatheringGrade = 11,
            ID = 101,
            ItemID = 62300074,
            MinAcquisition = 19,
            StdAcquisition = 28,
            StdInsight = 28,
        },
        {
            BaseEXP = 13,
            EXPBonus = 318,
            GatheringGrade = 11,
            ID = 102,
            ItemID = 62300112,
            MinAcquisition = 19,
            StdAcquisition = 28,
            StdInsight = 28,
        },
        {
            BaseEXP = 13,
            EXPBonus = 318,
            GatheringGrade = 11,
            ID = 103,
            ItemID = 62300044,
            MinAcquisition = 19,
            StdAcquisition = 28,
            StdInsight = 28,
        },
        {
            BaseEXP = 13,
            EXPBonus = 318,
            GatheringGrade = 11,
            ID = 104,
            ItemID = 63000098,
            MinAcquisition = 19,
            StdAcquisition = 28,
            StdInsight = 28,
        },
        {
            BaseEXP = 13,
            EXPBonus = 328,
            GatheringGrade = 12,
            ID = 105,
            ItemID = 62300026,
            MinAcquisition = 20,
            StdAcquisition = 29,
            StdInsight = 29,
        },
        {
            BaseEXP = 13,
            EXPBonus = 328,
            GatheringGrade = 12,
            ID = 106,
            ItemID = 63000119,
            MinAcquisition = 20,
            StdAcquisition = 29,
            StdInsight = 29,
        },
        {
            BaseEXP = 13,
            EXPBonus = 328,
            GatheringGrade = 12,
            ID = 107,
            ItemID = 62300063,
            MinAcquisition = 20,
            StdAcquisition = 29,
            StdInsight = 29,
        },
        {
            BaseEXP = 13,
            EXPBonus = 328,
            GatheringGrade = 12,
            ID = 108,
            ItemID = 62700019,
            MinAcquisition = 20,
            StdAcquisition = 29,
            StdInsight = 29,
        },
        {
            BaseEXP = 13,
            EXPBonus = 328,
            GatheringGrade = 12,
            ID = 109,
            ItemID = 63000099,
            MinAcquisition = 20,
            StdAcquisition = 29,
            StdInsight = 29,
        },
        {
            BaseEXP = 13,
            EXPBonus = 328,
            GatheringGrade = 12,
            ID = 110,
            ItemID = 62600025,
            MinAcquisition = 20,
            StdAcquisition = 29,
            StdInsight = 29,
        },
        {
            BaseEXP = 13,
            EXPBonus = 339,
            GatheringGrade = 13,
            ID = 111,
            ItemID = 63000077,
            MinAcquisition = 28,
            StdAcquisition = 41,
            StdInsight = 41,
        },
        {
            BaseEXP = 13,
            EXPBonus = 339,
            GatheringGrade = 13,
            ID = 112,
            ItemID = 62300027,
            MinAcquisition = 28,
            StdAcquisition = 41,
            StdInsight = 41,
        },
        {
            BaseEXP = 13,
            EXPBonus = 339,
            GatheringGrade = 13,
            ID = 113,
            ItemID = 62300028,
            MinAcquisition = 28,
            StdAcquisition = 41,
            StdInsight = 41,
        },
        {
            BaseEXP = 13,
            EXPBonus = 339,
            GatheringGrade = 13,
            ID = 114,
            ItemID = 62300050,
            MinAcquisition = 28,
            StdAcquisition = 41,
            StdInsight = 41,
        },
        {
            BaseEXP = 13,
            EXPBonus = 339,
            GatheringGrade = 13,
            ID = 115,
            ItemID = 63000100,
            MinAcquisition = 28,
            StdAcquisition = 41,
            StdInsight = 41,
        },
        {
            BaseEXP = 13,
            EXPBonus = 339,
            GatheringGrade = 13,
            ID = 116,
            ItemID = 62300031,
            MinAcquisition = 28,
            StdAcquisition = 41,
            StdInsight = 41,
        },
        {
            BaseEXP = 14,
            EXPBonus = 350,
            GatheringGrade = 14,
            ID = 117,
            ItemID = 62300075,
            MinAcquisition = 29,
            StdAcquisition = 42,
            StdInsight = 42,
        },
        {
            BaseEXP = 14,
            EXPBonus = 350,
            GatheringGrade = 14,
            ID = 118,
            ItemID = 62700020,
            MinAcquisition = 29,
            StdAcquisition = 42,
            StdInsight = 42,
        },
        {
            BaseEXP = 14,
            EXPBonus = 350,
            GatheringGrade = 14,
            ID = 119,
            ItemID = 62300032,
            MinAcquisition = 29,
            StdAcquisition = 42,
            StdInsight = 42,
        },
        {
            BaseEXP = 14,
            EXPBonus = 350,
            GatheringGrade = 14,
            ID = 120,
            ItemID = 62300051,
            MinAcquisition = 29,
            StdAcquisition = 42,
            StdInsight = 42,
        },
        {
            BaseEXP = 14,
            EXPBonus = 363,
            GatheringGrade = 15,
            ID = 121,
            ItemID = 62300029,
            MinAcquisition = 32,
            StdAcquisition = 47,
            StdInsight = 47,
        },
        {
            BaseEXP = 14,
            EXPBonus = 363,
            GatheringGrade = 15,
            ID = 122,
            ItemID = 62300030,
            MinAcquisition = 32,
            StdAcquisition = 47,
            StdInsight = 47,
        },
        {
            BaseEXP = 14,
            EXPBonus = 363,
            GatheringGrade = 15,
            ID = 123,
            ItemID = 62300033,
            MinAcquisition = 32,
            StdAcquisition = 47,
            StdInsight = 47,
        },
        {
            BaseEXP = 14,
            EXPBonus = 363,
            GatheringGrade = 15,
            ID = 124,
            ItemID = 62300077,
            MinAcquisition = 32,
            StdAcquisition = 47,
            StdInsight = 47,
        },
        {
            BaseEXP = 20,
            EXPBonus = 472,
            GatheringGrade = 16,
            ID = 125,
            ItemID = 62300079,
            ItemLevel = 20,
            MinAcquisition = 33,
            StdAcquisition = 48,
            StdInsight = 48,
        },
        {
            BaseEXP = 20,
            EXPBonus = 472,
            GatheringGrade = 16,
            ID = 126,
            ItemID = 62300034,
            ItemLevel = 20,
            MinAcquisition = 33,
            StdAcquisition = 48,
            StdInsight = 48,
        },
        {
            BaseEXP = 20,
            EXPBonus = 472,
            GatheringGrade = 16,
            ID = 127,
            ItemID = 62300056,
            ItemLevel = 20,
            MinAcquisition = 33,
            StdAcquisition = 48,
            StdInsight = 48,
        },
        {
            BaseEXP = 20,
            EXPBonus = 489,
            GatheringGrade = 17,
            ID = 128,
            ItemID = 62300065,
            ItemLevel = 20,
            MinAcquisition = 34,
            StdAcquisition = 49,
            StdInsight = 49,
        },
        {
            BaseEXP = 20,
            EXPBonus = 489,
            GatheringGrade = 17,
            ID = 129,
            ItemID = 62300057,
            ItemLevel = 20,
            MinAcquisition = 34,
            StdAcquisition = 49,
            StdInsight = 49,
        },
        {
            BaseEXP = 21,
            EXPBonus = 508,
            GatheringGrade = 18,
            ID = 130,
            ItemID = 62300035,
            ItemLevel = 20,
            MinAcquisition = 43,
            StdAcquisition = 62,
            StdInsight = 62,
        },
        {
            BaseEXP = 21,
            EXPBonus = 508,
            GatheringGrade = 18,
            ID = 131,
            ItemID = 62300036,
            ItemLevel = 20,
            MinAcquisition = 43,
            StdAcquisition = 62,
            StdInsight = 62,
        },
        {
            BaseEXP = 21,
            EXPBonus = 508,
            GatheringGrade = 18,
            ID = 132,
            ItemID = 63000101,
            ItemLevel = 20,
            MinAcquisition = 43,
            StdAcquisition = 62,
            StdInsight = 62,
        },
        {
            BaseEXP = 21,
            EXPBonus = 527,
            GatheringGrade = 19,
            ID = 133,
            ItemID = 62300045,
            ItemLevel = 20,
            MinAcquisition = 44,
            StdAcquisition = 63,
            StdInsight = 63,
        },
        {
            BaseEXP = 21,
            EXPBonus = 527,
            GatheringGrade = 19,
            ID = 134,
            ItemID = 62600026,
            ItemLevel = 20,
            MinAcquisition = 44,
            StdAcquisition = 63,
            StdInsight = 63,
        },
        {
            BaseEXP = 22,
            EXPBonus = 543,
            GatheringGrade = 20,
            ID = 135,
            ItemID = 62600045,
            ItemLevel = 20,
            MinAcquisition = 47,
            StdAcquisition = 68,
            StdInsight = 68,
        },
        {
            BaseEXP = 22,
            EXPBonus = 543,
            GatheringGrade = 20,
            ID = 136,
            ItemID = 63000122,
            ItemLevel = 20,
            MinAcquisition = 47,
            StdAcquisition = 68,
            StdInsight = 68,
        },
        {
            BaseEXP = 22,
            EXPBonus = 543,
            GatheringGrade = 20,
            ID = 137,
            ItemID = 63000129,
            ItemLevel = 20,
            MinAcquisition = 47,
            StdAcquisition = 68,
            StdInsight = 68,
        },
        {
            BaseEXP = 22,
            EXPBonus = 543,
            GatheringGrade = 20,
            ID = 138,
            ItemID = 63000130,
            ItemLevel = 20,
            MinAcquisition = 47,
            StdAcquisition = 68,
            StdInsight = 68,
        },
        {
            BaseEXP = 22,
            EXPBonus = 543,
            GatheringGrade = 20,
            ID = 139,
            ItemID = 63000131,
            ItemLevel = 20,
            MinAcquisition = 47,
            StdAcquisition = 68,
            StdInsight = 68,
        },
        {
            BaseEXP = 22,
            EXPBonus = 543,
            GatheringGrade = 20,
            ID = 140,
            ItemLevel = 20,
            MinAcquisition = 47,
            StdAcquisition = 68,
            StdInsight = 68,
        },
        {
            BaseEXP = 22,
            EXPBonus = 608,
            GatheringGrade = 21,
            ID = 141,
            ItemID = 62300052,
            ItemLevel = 30,
            MinAcquisition = 49,
            StdAcquisition = 70,
            StdInsight = 70,
        },
        {
            BaseEXP = 22,
            EXPBonus = 608,
            GatheringGrade = 21,
            ID = 142,
            ItemID = 62300058,
            ItemLevel = 30,
            MinAcquisition = 49,
            StdAcquisition = 70,
            StdInsight = 70,
        },
        {
            BaseEXP = 22,
            EXPBonus = 624,
            GatheringGrade = 22,
            ID = 143,
            ItemID = 62300114,
            ItemLevel = 30,
            MinAcquisition = 50,
            StdAcquisition = 72,
            StdInsight = 72,
        },
        {
            BaseEXP = 22,
            EXPBonus = 624,
            GatheringGrade = 22,
            ID = 144,
            ItemID = 62300046,
            ItemLevel = 30,
            MinAcquisition = 50,
            StdAcquisition = 72,
            StdInsight = 72,
        },
        {
            BaseEXP = 22,
            EXPBonus = 639,
            GatheringGrade = 23,
            ID = 145,
            ItemID = 62300080,
            ItemLevel = 30,
            MinAcquisition = 60,
            StdAcquisition = 86,
            StdInsight = 86,
        },
        {
            BaseEXP = 22,
            EXPBonus = 639,
            GatheringGrade = 23,
            ID = 146,
            ItemID = 63000095,
            ItemLevel = 30,
            MinAcquisition = 60,
            StdAcquisition = 86,
            StdInsight = 86,
        },
        {
            BaseEXP = 22,
            EXPBonus = 655,
            GatheringGrade = 24,
            ID = 147,
            ItemID = 62300081,
            ItemLevel = 30,
            MinAcquisition = 61,
            StdAcquisition = 88,
            StdInsight = 88,
        },
        {
            BaseEXP = 22,
            EXPBonus = 655,
            GatheringGrade = 24,
            ID = 148,
            ItemID = 63000102,
            ItemLevel = 30,
            MinAcquisition = 61,
            StdAcquisition = 88,
            StdInsight = 88,
        },
        {
            BaseEXP = 22,
            EXPBonus = 655,
            GatheringGrade = 24,
            ID = 149,
            ItemID = 62600028,
            ItemLevel = 30,
            MinAcquisition = 61,
            StdAcquisition = 88,
            StdInsight = 88,
        },
        {
            BaseEXP = 22,
            EXPBonus = 670,
            GatheringGrade = 25,
            ID = 150,
            ItemID = 62300066,
            ItemLevel = 30,
            MinAcquisition = 67,
            StdAcquisition = 97,
            StdInsight = 97,
        },
        {
            BaseEXP = 22,
            EXPBonus = 670,
            GatheringGrade = 25,
            ID = 151,
            ItemID = 62300064,
            ItemLevel = 30,
            MinAcquisition = 67,
            StdAcquisition = 97,
            StdInsight = 97,
        },
        {
            BaseEXP = 23,
            EXPBonus = 736,
            GatheringGrade = 26,
            ID = 152,
            ItemID = 62300067,
            ItemLevel = 40,
            MinAcquisition = 69,
            StdAcquisition = 99,
            StdInsight = 99,
        },
        {
            BaseEXP = 23,
            EXPBonus = 753,
            GatheringGrade = 27,
            ID = 153,
            ItemID = 62300037,
            ItemLevel = 40,
            MinAcquisition = 70,
            StdAcquisition = 101,
            StdInsight = 101,
        },
        {
            BaseEXP = 24,
            EXPBonus = 789,
            GatheringGrade = 28,
            ID = 154,
            ItemID = 62300038,
            ItemLevel = 40,
            MinAcquisition = 76,
            StdAcquisition = 109,
            StdInsight = 109,
        },
        {
            BaseEXP = 25,
            EXPBonus = 826,
            GatheringGrade = 29,
            ID = 155,
            ItemID = 62700036,
            ItemLevel = 40,
            MinAcquisition = 77,
            StdAcquisition = 111,
            StdInsight = 111,
        },
        {
            BaseEXP = 27,
            EXPBonus = 862,
            GatheringGrade = 30,
            ID = 156,
            ItemID = 62300059,
            ItemLevel = 40,
            MinAcquisition = 86,
            StdAcquisition = 123,
            StdInsight = 123,
        },
        {
            BaseEXP = 27,
            EXPBonus = 862,
            GatheringGrade = 30,
            ID = 157,
            ItemID = 63000118,
            ItemLevel = 40,
            MinAcquisition = 86,
            StdAcquisition = 123,
            StdInsight = 123,
        },
        {
            BaseEXP = 28,
            EXPBonus = 949,
            GatheringGrade = 31,
            ID = 158,
            ItemID = 62600049,
            ItemLevel = 50,
            MinAcquisition = 87,
            StdAcquisition = 125,
            StdInsight = 125,
        },
        {
            BaseEXP = 28,
            EXPBonus = 949,
            GatheringGrade = 31,
            ID = 159,
            ItemID = 62700023,
            ItemLevel = 50,
            MinAcquisition = 87,
            StdAcquisition = 125,
            StdInsight = 125,
        },
        {
            BaseEXP = 29,
            EXPBonus = 985,
            GatheringGrade = 32,
            ID = 160,
            ItemID = 62300039,
            ItemLevel = 50,
            MinAcquisition = 88,
            StdAcquisition = 127,
            StdInsight = 127,
        },
        {
            BaseEXP = 29,
            EXPBonus = 985,
            GatheringGrade = 32,
            ID = 161,
            ItemID = 62300082,
            ItemLevel = 50,
            MinAcquisition = 88,
            StdAcquisition = 127,
            StdInsight = 127,
        },
        {
            BaseEXP = 29,
            EXPBonus = 985,
            GatheringGrade = 32,
            ID = 162,
            ItemID = 62600030,
            ItemLevel = 50,
            MinAcquisition = 88,
            StdAcquisition = 127,
            StdInsight = 127,
        },
        {
            BaseEXP = 30,
            EXPBonus = 1022,
            GatheringGrade = 33,
            ID = 163,
            ItemID = 63000103,
            ItemLevel = 50,
            MinAcquisition = 95,
            StdAcquisition = 136,
            StdInsight = 136,
        },
        {
            BaseEXP = 30,
            EXPBonus = 1022,
            GatheringGrade = 33,
            ID = 164,
            ItemID = 62300047,
            ItemLevel = 50,
            MinAcquisition = 95,
            StdAcquisition = 136,
            StdInsight = 136,
        },
        {
            BaseEXP = 30,
            EXPBonus = 1022,
            GatheringGrade = 33,
            ID = 165,
            ItemID = 62700041,
            ItemLevel = 50,
            MinAcquisition = 95,
            StdAcquisition = 136,
            StdInsight = 136,
        },
        {
            BaseEXP = 31,
            EXPBonus = 1058,
            GatheringGrade = 34,
            ID = 166,
            ItemID = 62300040,
            ItemLevel = 50,
            MinAcquisition = 96,
            StdAcquisition = 138,
            StdInsight = 138,
        },
        {
            BaseEXP = 31,
            EXPBonus = 1058,
            GatheringGrade = 34,
            ID = 167,
            ItemID = 62300084,
            ItemLevel = 50,
            MinAcquisition = 96,
            StdAcquisition = 138,
            StdInsight = 138,
        },
        {
            BaseEXP = 31,
            EXPBonus = 1058,
            GatheringGrade = 34,
            ID = 168,
            ItemID = 62700037,
            ItemLevel = 50,
            MinAcquisition = 96,
            StdAcquisition = 138,
            StdInsight = 138,
        },
        {
            BaseEXP = 31,
            EXPBonus = 1097,
            GatheringGrade = 35,
            ID = 169,
            ItemID = 62300083,
            ItemLevel = 50,
            MinAcquisition = 104,
            StdAcquisition = 149,
            StdInsight = 149,
        },
        {
            BaseEXP = 31,
            EXPBonus = 1097,
            GatheringGrade = 35,
            ID = 170,
            ItemID = 63000121,
            ItemLevel = 50,
            MinAcquisition = 104,
            StdAcquisition = 149,
            StdInsight = 149,
        },
        {
            BaseEXP = 31,
            EXPBonus = 1097,
            GatheringGrade = 35,
            ID = 171,
            ItemID = 62300088,
            ItemLevel = 50,
            MinAcquisition = 104,
            StdAcquisition = 149,
            StdInsight = 149,
        },
        {
            BaseEXP = 32,
            EXPBonus = 1157,
            GatheringGrade = 36,
            ID = 172,
            ItemID = 62300060,
            ItemLevel = 60,
            MinAcquisition = 105,
            StdAcquisition = 151,
            StdInsight = 151,
        },
        {
            BaseEXP = 32,
            EXPBonus = 1157,
            GatheringGrade = 36,
            ID = 173,
            ItemID = 62300053,
            ItemLevel = 60,
            MinAcquisition = 105,
            StdAcquisition = 151,
            StdInsight = 151,
        },
        {
            BaseEXP = 32,
            EXPBonus = 1167,
            GatheringGrade = 37,
            ID = 174,
            ItemID = 62300085,
            ItemLevel = 60,
            MinAcquisition = 107,
            StdAcquisition = 153,
            StdInsight = 153,
        },
        {
            BaseEXP = 32,
            EXPBonus = 1167,
            GatheringGrade = 37,
            ID = 175,
            ItemID = 62600031,
            ItemLevel = 60,
            MinAcquisition = 107,
            StdAcquisition = 153,
            StdInsight = 153,
        },
        {
            BaseEXP = 33,
            EXPBonus = 1177,
            GatheringGrade = 38,
            ID = 176,
            ItemID = 62300042,
            ItemLevel = 60,
            MinAcquisition = 113,
            StdAcquisition = 162,
            StdInsight = 162,
        },
        {
            BaseEXP = 33,
            EXPBonus = 1187,
            GatheringGrade = 39,
            ID = 177,
            ItemID = 62300041,
            ItemLevel = 60,
            MinAcquisition = 114,
            StdAcquisition = 164,
            StdInsight = 164,
        },
        {
            BaseEXP = 33,
            EXPBonus = 1187,
            GatheringGrade = 39,
            ID = 178,
            ItemID = 62300086,
            ItemLevel = 60,
            MinAcquisition = 114,
            StdAcquisition = 164,
            StdInsight = 164,
        },
        {
            BaseEXP = 33,
            EXPBonus = 1187,
            GatheringGrade = 39,
            ID = 179,
            ItemID = 62300089,
            ItemLevel = 60,
            MinAcquisition = 114,
            StdAcquisition = 164,
            StdInsight = 164,
        },
        {
            BaseEXP = 34,
            EXPBonus = 1197,
            GatheringGrade = 40,
            ID = 180,
            ItemID = 62300087,
            ItemLevel = 60,
            MinAcquisition = 123,
            StdAcquisition = 177,
            StdInsight = 177,
        },
        {
            BaseEXP = 34,
            EXPBonus = 1257,
            GatheringGrade = 41,
            ID = 181,
            ItemID = 62300090,
            ItemLevel = 70,
            MinAcquisition = 125,
            StdAcquisition = 179,
            StdInsight = 179,
        },
        {
            BaseEXP = 35,
            EXPBonus = 1269,
            GatheringGrade = 42,
            ID = 182,
            ItemID = 62300115,
            ItemLevel = 70,
            MinAcquisition = 126,
            StdAcquisition = 181,
            StdInsight = 181,
        },
        {
            BaseEXP = 35,
            EXPBonus = 1269,
            GatheringGrade = 42,
            ID = 183,
            ItemID = 63000123,
            ItemLevel = 70,
            MinAcquisition = 126,
            StdAcquisition = 181,
            StdInsight = 181,
        },
        {
            BaseEXP = 40,
            EXPBonus = 1378,
            GatheringGrade = 43,
            ID = 184,
            ItemID = 62300061,
            ItemLevel = 70,
            MinAcquisition = 131,
            StdAcquisition = 188,
            StdInsight = 188,
        },
        {
            BaseEXP = 45,
            EXPBonus = 1486,
            GatheringGrade = 44,
            ID = 185,
            ItemID = 63000096,
            ItemLevel = 70,
            MinAcquisition = 133,
            StdAcquisition = 190,
            StdInsight = 190,
        },
        {
            BaseEXP = 50,
            EXPBonus = 1595,
            GatheringGrade = 45,
            ID = 186,
            ItemID = 63000056,
            ItemLevel = 70,
            MinAcquisition = 142,
            StdAcquisition = 203,
            StdInsight = 203,
        },
        {
            BaseEXP = 56,
            EXPBonus = 1753,
            GatheringGrade = 46,
            ID = 187,
            ItemID = 62600033,
            ItemLevel = 80,
            MinAcquisition = 143,
            StdAcquisition = 205,
            StdInsight = 205,
        },
        {
            BaseEXP = 61,
            EXPBonus = 1862,
            GatheringGrade = 47,
            ID = 188,
            ItemID = 62600054,
            ItemLevel = 80,
            MinAcquisition = 144,
            StdAcquisition = 207,
            StdInsight = 207,
        },
        {
            BaseEXP = 66,
            EXPBonus = 1970,
            GatheringGrade = 48,
            ID = 189,
            ItemID = 62300091,
            ItemLevel = 80,
            MinAcquisition = 149,
            StdAcquisition = 214,
            StdInsight = 214,
        },
        {
            EXPBonus = 2240,
            ID = 190,
            ItemID = 62700042,
            ItemLevel = 90,
            MinAcquisition = 160,
            StdAcquisition = 229,
            StdInsight = 229,
        },
        {
            GatheringStar = 1,
            ID = 191,
            ItemID = 62300116,
            ItemLevel = 130,
            LineageVolume = 1,
            VersionName = CS._1_2,
            _GatherLabelNum = 3,
        },
        {
            GatheringStar = 1,
            ID = 192,
            ItemID = 62300048,
            ItemLevel = 130,
            LineageVolume = 1,
            VersionName = CS._1_2,
            _GatherLabelNum = 3,
        },
        {
            GatheringStar = 1,
            ID = 193,
            ItemID = 62300062,
            ItemLevel = 130,
            LineageVolume = 1,
            VersionName = CS._1_2,
            _GatherLabelNum = 3,
        },
        {
            GatheringStar = 1,
            ID = 194,
            ItemID = 62600035,
            ItemLevel = 130,
            LineageVolume = 1,
            VersionName = CS._1_2,
            _GatherLabelNum = 3,
        },
        {
            GatheringStar = 1,
            ID = 195,
            ItemID = 62700027,
            ItemLevel = 130,
            LineageVolume = 1,
            VersionName = CS._1_2,
            _GatherLabelNum = 3,
        },
        {
            GatheringStar = 1,
            ID = 196,
            ItemID = 63000097,
            ItemLevel = 130,
            LineageVolume = 1,
            VersionName = CS._1_2,
            _GatherLabelNum = 3,
        },
        {
            GatheringStar = 1,
            ID = 197,
            ItemID = 63000104,
            ItemLevel = 130,
            LineageVolume = 1,
            VersionName = CS._1_2,
            _GatherLabelNum = 3,
        },
        {
            GatheringStar = 1,
            ID = 198,
            ItemID = 63000105,
            ItemLevel = 130,
            LineageVolume = 1,
            VersionName = CS._1_2,
            _GatherLabelNum = 3,
        },
        {
            GatheringStar = 1,
            ID = 199,
            ItemID = 63000142,
            ItemLevel = 130,
            LineageVolume = 1,
            VersionName = CS._1_3,
            _GatherLabelNum = 3,
        },
        {
            GatheringStar = 1,
            ID = 200,
            ItemID = 63000143,
            ItemLevel = 130,
            LineageVolume = 1,
            VersionName = CS._1_3,
            _GatherLabelNum = 3,
        },
        {
            GatheringStar = 1,
            ID = 201,
            ItemID = 62300117,
            ItemLevel = 130,
            LineageVolume = 1,
            VersionName = CS._1_3,
            _GatherLabelNum = 3,
        },
        {
            EXPBonus = 2590,
            GatheringStar = 2,
            ID = 202,
            ItemID = 62300122,
            ItemLevel = 160,
            LineageVolume = 2,
            MinAcquisition = 235,
            StdAcquisition = 336,
            StdInsight = 336,
            VersionName = CS._1_1,
            _GatherLabelNum = 3,
        },
        {
            EXPBonus = 2590,
            GatheringStar = 2,
            ID = 203,
            ItemID = 62300121,
            ItemLevel = 160,
            LineageVolume = 2,
            MinAcquisition = 235,
            StdAcquisition = 336,
            StdInsight = 336,
            VersionName = CS._1_1,
            _GatherLabelNum = 3,
        },
        {
            EXPBonus = 2590,
            GatheringStar = 2,
            ID = 204,
            ItemID = 62300123,
            ItemLevel = 160,
            LineageVolume = 2,
            MinAcquisition = 235,
            StdAcquisition = 336,
            StdInsight = 336,
            VersionName = CS._1_1,
            _GatherLabelNum = 3,
        },
        {
            EXPBonus = 2590,
            GatheringStar = 2,
            ID = 205,
            ItemID = 62300124,
            ItemLevel = 160,
            LineageVolume = 2,
            MinAcquisition = 235,
            StdAcquisition = 336,
            StdInsight = 336,
            VersionName = CS._1_1,
            _GatherLabelNum = 3,
        },
        {
            EXPBonus = 2590,
            GatheringStar = 2,
            ID = 206,
            ItemID = 62600034,
            ItemLevel = 160,
            LineageVolume = 2,
            MinAcquisition = 235,
            StdAcquisition = 336,
            StdInsight = 336,
            VersionName = CS._1_1,
            _GatherLabelNum = 3,
        },
        {
            EXPBonus = 2590,
            GatheringStar = 2,
            ID = 207,
            ItemID = 63000106,
            ItemLevel = 160,
            LineageVolume = 2,
            MinAcquisition = 235,
            StdAcquisition = 336,
            StdInsight = 336,
            VersionName = CS._1_1,
            _GatherLabelNum = 3,
        },
        {
            EXPBonus = 2590,
            GatheringStar = 2,
            ID = 208,
            ItemID = 63000171,
            ItemLevel = 160,
            LineageVolume = 2,
            MinAcquisition = 235,
            StdAcquisition = 336,
            StdInsight = 336,
            VersionName = CS._1_1,
            _GatherLabelNum = 3,
        },
        {
            EXPBonus = 2590,
            GatheringStar = 2,
            ID = 209,
            ItemID = 62600075,
            ItemLevel = 160,
            LineageVolume = 2,
            MinAcquisition = 235,
            StdAcquisition = 336,
            StdInsight = 336,
            VersionName = CS._1_4,
            _GatherLabelNum = 3,
        },
        {
            AcquisitionBalance = 110,
            BaseEXP = 340,
            CollectionTemplate = 2,
            EXPBonus = 1307,
            GatheringGrade = 41,
            GatheringJob = 36,
            ID = 210,
            InsightBalance = 110,
            IsCollection = 1,
            ItemID = 66100006,
            ItemLevel = 80,
            MinAcquisition = 137,
            StdAcquisition = 196,
            StdInsight = 196,
            _GatherLabelNum = 3,
        },
        {
            AcquisitionBalance = 110,
            BaseEXP = 400,
            CollectionTemplate = 2,
            EXPBonus = 1428,
            GatheringGrade = 43,
            GatheringJob = 36,
            ID = 211,
            InsightBalance = 110,
            IsCollection = 1,
            ItemID = 66100007,
            ItemLevel = 80,
            MinAcquisition = 144,
            StdAcquisition = 206,
            StdInsight = 206,
            _GatherLabelNum = 3,
        },
        {
            AcquisitionBalance = 110,
            BaseEXP = 500,
            CollectionTemplate = 2,
            EXPBonus = 1695,
            GatheringGrade = 45,
            GatheringJob = 36,
            ID = 212,
            InsightBalance = 110,
            IsCollection = 1,
            ItemID = 66100008,
            ItemLevel = 90,
            MinAcquisition = 156,
            StdAcquisition = 223,
            StdInsight = 223,
            _GatherLabelNum = 3,
        },
        {
            AcquisitionBalance = 110,
            BaseEXP = 610,
            CollectionTemplate = 2,
            EXPBonus = 1912,
            GatheringGrade = 47,
            GatheringJob = 36,
            ID = 213,
            InsightBalance = 110,
            IsCollection = 1,
            ItemID = 66100009,
            ItemLevel = 90,
            MinAcquisition = 158,
            StdAcquisition = 227,
            StdInsight = 227,
            _GatherLabelNum = 3,
        },
        {
            AcquisitionBalance = 110,
            BaseEXP = 710,
            CollectionTemplate = 2,
            EXPBonus = 2130,
            GatheringGrade = 49,
            GatheringJob = 36,
            ID = 214,
            InsightBalance = 110,
            IsCollection = 1,
            ItemID = 66100010,
            ItemLevel = 90,
            MinAcquisition = 165,
            StdAcquisition = 237,
            StdInsight = 237,
            _GatherLabelNum = 3,
        },
        {
            AcquisitionBalance = 120,
            BaseEXP = 760,
            CollectionTemplate = 2,
            EXPBonus = 2240,
            GatheringJob = 36,
            ID = 215,
            InsightBalance = 120,
            IsCollection = 1,
            ItemID = 66100011,
            ItemLevel = 90,
            MinAcquisition = 191,
            StdAcquisition = 274,
            StdInsight = 274,
            _GatherLabelNum = 3,
        },
        {
            AcquisitionBalance = 110,
            BaseEXP = 340,
            CollectionTemplate = 2,
            EXPBonus = 1307,
            GatheringGrade = 41,
            ID = 216,
            InsightBalance = 110,
            IsCollection = 1,
            ItemID = 66100012,
            ItemLevel = 80,
            MinAcquisition = 137,
            StdAcquisition = 196,
            StdInsight = 196,
            _GatherLabelNum = 3,
        },
        {
            AcquisitionBalance = 110,
            BaseEXP = 400,
            CollectionTemplate = 2,
            EXPBonus = 1428,
            GatheringGrade = 43,
            ID = 217,
            InsightBalance = 110,
            IsCollection = 1,
            ItemID = 66100013,
            ItemLevel = 80,
            MinAcquisition = 144,
            StdAcquisition = 206,
            StdInsight = 206,
            _GatherLabelNum = 3,
        },
        {
            AcquisitionBalance = 110,
            BaseEXP = 500,
            CollectionTemplate = 2,
            EXPBonus = 1695,
            GatheringGrade = 45,
            ID = 218,
            InsightBalance = 110,
            IsCollection = 1,
            ItemID = 66100014,
            ItemLevel = 90,
            MinAcquisition = 156,
            StdAcquisition = 223,
            StdInsight = 223,
            _GatherLabelNum = 3,
        },
        {
            AcquisitionBalance = 110,
            BaseEXP = 610,
            CollectionTemplate = 2,
            EXPBonus = 1912,
            GatheringGrade = 47,
            ID = 219,
            InsightBalance = 110,
            IsCollection = 1,
            ItemID = 66100015,
            ItemLevel = 90,
            MinAcquisition = 158,
            StdAcquisition = 227,
            StdInsight = 227,
            _GatherLabelNum = 3,
        },
        {
            AcquisitionBalance = 110,
            BaseEXP = 710,
            CollectionTemplate = 2,
            EXPBonus = 2130,
            GatheringGrade = 49,
            ID = 220,
            InsightBalance = 110,
            IsCollection = 1,
            ItemID = 66100016,
            ItemLevel = 90,
            MinAcquisition = 165,
            StdAcquisition = 237,
            StdInsight = 237,
            _GatherLabelNum = 3,
        },
        {
            AcquisitionBalance = 120,
            BaseEXP = 760,
            CollectionTemplate = 2,
            EXPBonus = 2240,
            ID = 221,
            InsightBalance = 120,
            IsCollection = 1,
            ItemID = 66100017,
            ItemLevel = 90,
            MinAcquisition = 191,
            StdAcquisition = 274,
            StdInsight = 274,
            _GatherLabelNum = 3,
        },
	},
}

setmetatable(GatherNoteCfg, { __index = CfgBase })

GatherNoteCfg:InitCfg()

-- AUTO GENERATED CODE END, PLEASE DON'T MODIFY

function GatherNoteCfg:FindCfgByItemID(ItemID)
    local CachedData = self:GetCachedData()
    if CachedData then
        for _,v in pairs(CachedData) do
            if v.ItemID == ItemID then
                return v
            end
        end
    end

	local SearchConditions = string.format("ItemID = %d", ItemID)
	return self:FindCfg(SearchConditions)
end

return GatherNoteCfg
