-- AUTO GENERATED CODE BEGIN, PLEASE DON'T MODIFY

local CfgBase = require("TableCfg/CfgBase")

local CS = {
    _3_1 = '[20000,130]',
    _4_1 = '[2000,40]',
    _5_1 = '[20000,130]',
    _6_1 = '[2000,40]',
}

---@class SceneEnterDailyRandomCfg : CfgBase
local SceneEnterDailyRandomCfg = {
	TableName = "c_scene_enter_daily_random_cfg",
    LruKeyType = nil,
	KeyName = "ID",
    bEncrypted = false,
	Localization = {
        Config = {
            {
                Name = 'Name',
            },
            {
                Name = 'Summary',
            },
            {
                Name = 'Explain',
            },
		}
    },
    DefaultValues = {
        ArmSyncLevel = 0,
        AttackProfNum = 2,
        BG = 'Texture2D\'/Game/UI/Texture/PWorld/BG/Details/UI_PWorld_BG_Details_MRSJLJ.UI_PWorld_BG_Details_MRSJLJ\'',
        BackgroudImageIcon = 'Texture2D\'/Game/UI/Texture/PWorld/Banner/UI_PWorld_Banner_PWorldList_01.UI_PWorld_Banner_PWorldList_01\'',
        Counter = 1900,
        _DailyRewardCnt = '[5000,40]',
        _DailyRewards = '[19000002,19000101]',
        EquipLv = 10,
        _FewFuncRewardCnt = '[500,10]',
        _FewFuncRewards = '[19000002,19000100]',
        GuardProfNum = 1,
        HasChallenge = 0,
        HasExplore = 0,
        HasNormal = 0,
        HasUnlimited = 0,
        HelpInfoID = 11053,
        ID = 1,
        _MaxLvDailyRewardCnt = '[5000,40]',
        _MaxLvDailyRewards = '[19000002,19000101]',
        _MaxLvFewFuncRewardCnt = '[500,10]',
        _MaxLvFewFuncRewards = '[19000002,19000100]',
        NurseProfNum = 1,
        PWorldBanner = 'Texture2D\'/Game/UI/Texture/PWorld/BG/Match/UI_PWorld_BG_Match_MRSJLJ.UI_PWorld_BG_Match_MRSJLJ\'',
        _PassSceneIDs = '[]',
        PlayerLv = 50,
        PlayerSyncLevel = 0,
        PoolID = 1,
        PreQuestID = 140319,
        Priority = 2,
        RecruitID = 3,
        SyncMaxLv = 0,
        TaskType = 0,
        TypeID = 1,
        UnlockSceneNum = 0,
    },
	LuaData = {
        {
            _DailyRewardCnt = '[10000,70]',
            _FewFuncRewardCnt = '[1000,20]',
            _MaxLvDailyRewardCnt = '[10000,70]',
            _MaxLvFewFuncRewardCnt = '[1000,20]',
            PlayerLv = 10,
        },
        {
            AttackProfNum = 4,
            BG = 'Texture2D\'/Game/UI/Texture/PWorld/BG/Details/UI_PWorld_BG_Details_MRSJTFJMZ.UI_PWorld_BG_Details_MRSJTFJMZ\'',
            BackgroudImageIcon = 'Texture2D\'/Game/UI/Texture/PWorld/Banner/UI_PWorld_Banner_PWorldList_02.UI_PWorld_Banner_PWorldList_02\'',
            Counter = 2000,
            EquipLv = 60,
            GuardProfNum = 2,
            HelpInfoID = 11054,
            ID = 2,
            NurseProfNum = 2,
            PWorldBanner = 'Texture2D\'/Game/UI/Texture/PWorld/BG/Match/UI_PWorld_BG_Match_MRSJTFJMZ.UI_PWorld_BG_Match_MRSJTFJMZ\'',
            PlayerLv = 35,
            PoolID = 2,
            PreQuestID = 160407,
            Priority = 3,
            RecruitID = 4,
        },
        {
            BG = 'Texture2D\'/Game/UI/Texture/PWorld/BG/Details/UI_PWorld_BG_Details_MRSJMJMG.UI_PWorld_BG_Details_MRSJMJMG\'',
            BackgroudImageIcon = 'Texture2D\'/Game/UI/Texture/PWorld/Banner/UI_PWorld_Banner_PWorldList_12.UI_PWorld_Banner_PWorldList_12\'',
            Counter = 2100,
            _DailyRewardCnt = CS._3_1,
            EquipLv = 90,
            _FewFuncRewardCnt = CS._4_1,
            HelpInfoID = 11055,
            ID = 3,
            _MaxLvDailyRewardCnt = CS._5_1,
            _MaxLvFewFuncRewardCnt = CS._6_1,
            PWorldBanner = 'Texture2D\'/Game/UI/Texture/PWorld/BG/Match/UI_PWorld_BG_Match_MRSJMJMG.UI_PWorld_BG_Match_MRSJMJMG\'',
            _PassSceneIDs = '[1211007,1211004,1211011]',
            PoolID = 3,
            PreQuestID = 180087,
            Priority = 1,
            RecruitID = 2,
        },
        {
            BG = 'Texture2D\'/Game/UI/Texture/PWorld/BG/Details/UI_PWorld_BG_Details_MRSJZDZ.UI_PWorld_BG_Details_MRSJZDZ\'',
            BackgroudImageIcon = 'Texture2D\'/Game/UI/Texture/PWorld/Banner/UI_PWorld_Banner_PWorldList_13.UI_PWorld_Banner_PWorldList_13\'',
            Counter = 21800,
            _DailyRewardCnt = CS._3_1,
            EquipLv = 125,
            _FewFuncRewardCnt = CS._4_1,
            HelpInfoID = 0,
            ID = 4,
            _MaxLvDailyRewardCnt = CS._5_1,
            _MaxLvFewFuncRewardCnt = CS._6_1,
            PWorldBanner = 'Texture2D\'/Game/UI/Texture/PWorld/BG/Match/UI_PWorld_BG_Match_MRSJZDZ.UI_PWorld_BG_Match_MRSJZDZ\'',
            PoolID = 4,
            Priority = 6,
            RecruitID = 0,
            TaskType = 1,
        },
        {
            AttackProfNum = 4,
            BG = 'Texture2D\'/Game/UI/Texture/PWorld/BG/Details/UI_PWorld_BG_Details_MRSJTDFB.UI_PWorld_BG_Details_MRSJTDFB\'',
            BackgroudImageIcon = 'Texture2D\'/Game/UI/Texture/PWorld/Banner/UI_PWorld_Banner_PWorldList_52.UI_PWorld_Banner_PWorldList_52\'',
            Counter = 2200,
            EquipLv = 150,
            GuardProfNum = 2,
            HelpInfoID = 11186,
            ID = 5,
            NurseProfNum = 2,
            PWorldBanner = 'Texture2D\'/Game/UI/Texture/PWorld/BG/Match/UI_PWorld_BG_Match_MRSJTDFB.UI_PWorld_BG_Match_MRSJTDFB\'',
            PoolID = 5,
            PreQuestID = 0,
            Priority = 4,
            RecruitID = 5,
            UnlockSceneNum = 2,
        },
        {
            AttackProfNum = 4,
            BG = 'Texture2D\'/Game/UI/Texture/PWorld/BG/Details/UI_PWorld_BG_Details_MRSJDXFB.UI_PWorld_BG_Details_MRSJDXFB\'',
            BackgroudImageIcon = 'Texture2D\'/Game/UI/Texture/PWorld/Banner/UI_PWorld_Banner_PWorldList_53.UI_PWorld_Banner_PWorldList_53\'',
            Counter = 2300,
            EquipLv = 120,
            GuardProfNum = 2,
            HelpInfoID = 11187,
            ID = 6,
            NurseProfNum = 2,
            PWorldBanner = 'Texture2D\'/Game/UI/Texture/PWorld/BG/Match/UI_PWorld_BG_Match_MRSJDXFB.UI_PWorld_BG_Match_MRSJDXFB\'',
            PoolID = 6,
            PreQuestID = 0,
            Priority = 5,
            RecruitID = 6,
            UnlockSceneNum = 2,
        },
	},
}

setmetatable(SceneEnterDailyRandomCfg, { __index = CfgBase })

SceneEnterDailyRandomCfg:InitCfg()

-- AUTO GENERATED CODE END, PLEASE DON'T MODIFY

return SceneEnterDailyRandomCfg
