--
-- Author: anypkvcai
-- Date: 2020-08-05 15:41:53
-- Description:
--

--life有："Game" "Account" "Role"	"Level"

-- priority有:   ！！！！！ 注意： lua模块的优先级最好大于1600 ！！！！
-- SuperPrioritizedFirst = 1000,
-- SuperPrioritized = 1200,
-- Prioritized = 1500,
-- Normal = 2000,
-- Late = 2500,
-- SuperLate = 3000,
-- Last = 5000,

---@class GameMgrConfig
--modulename(全局表中模块的table名), life, priority, luaPath, tickEnable(true/false)
GameMgrConfig = GameMgrConfig or {
    --region U2PM
    "U2pmMgr",         	    "Game",         1600,       "U2pm/U2pm/U2pmMgr",                                false,
    -- Game
    "SampleMgr",         	"Game",         1600,       "Game/Sample/SampleMgr",                                false,
    "EventMgr",         	"Game",         1600,       "Event/EventMgr",                                       true,
    "GameNetworkMgr",       "Game",         1600,       "Network/GameNetworkMgr",                               false,
    "HttpMgr",              "Game",         1600,       "Http/HttpMgr",                                      false,
    "HeartBeatMgr",         "Game",         1600,       "Game/Network/HeartBeatMgr",                            false,
    "NetworkRTTMgr",        "Game",         1600,       "Game/Network/NetworkRTTMgr",                            false,
    "TimerMgr",         	"Game",         1600,       "Timer/TimerMgr",                                       true,
    "SlicingMgr",         	"Role",         1600,       "Event/SlicingMgr",                                     false,
    "UIViewMgr",         	"Game",         1700,       "UI/UIViewMgr",                                         false,
    "UIViewModelMgr",       "Game",         1700,       "UI/UIViewModelMgr",                                    false,
    "ObjectMgr",         	"Game",         1800,       "Object/ObjectMgr",                                     false,
    "ObjectPoolMgr",        "Game",         1800,       "Game/ObjectPool/ObjectPoolMgr",                        false,
    "TipsMgr",         		"Game",         2000,       "Game/InfoTips/TipsMgr",                                false,
    "WorldMsgMgr",          "Game",         2000,       "Game/World/WorldMsgMgr",                               false,
    "LoginMgr",         	"Game",         2000,       "Game/Login/LoginMgr",                                  false,
    "PreDownloadMgr",       "Game",         2000,       "Game/LoginNew/Mgr/PreDownloadMgr",                     false,
    "CgMgr",                "Game",         2000,       "Game/LoginNew/Mgr/CgMgr",                              false,
    "QueueMgr",             "Game",         2000,       "Game/LoginNew/Mgr/QueueMgr",                           false,
    "LoginUIMgr",         	"Game",         2000,       "Game/LoginRole/LoginUIMgr",                            false,
    "LoginAvatarMgr",       "Game",         2000,       "Game/LoginCreate/LoginAvatarMgr",                      false,
    "NetworkStateMgr",      "Game",         2000,       "Game/Network/NetworkStateMgr",                         false,
    "NetworkImplMgr",       "Game",         2000,       "Game/Network/NetworkImplMgr",                          false,
    "ActorMgr",         	"Game",         2000,       "Game/Actor/ActorMgr",                        			false,
    "DanmakuMgr",           "Role",         2000,       "Game/Danmaku/DanmakuMgr",                              false,
    "MainPanelMgr",         "Role",         2000,       "Game/Main/MainPanelMgr",                               false,
    "PWorldMgr",         	"Role",         2000,       "Game/PWorld/PWorldMgr",                        		false,
    "MapLoadingStateMgr",  "Role",         2000,       "Game/PWorld/MapLoadingState/MapLoadingStateMgr",        false,
    "PWorldQuestMgr",       "Role",         2000,       "Game/PWorld/Quest/PWorldQuestMgr",                  false,
    "PWorldMatchMgr",       "Role",         2000,       "Game/PWorld/Match/PWorldMatchMgr",                  false,
    "TeamHelperMgr",        "Role",         1999,       "Game/Team/Abs/TeamHelperMgr",                           false,
    "PWorldTeamMgr",        "Role",         2000,       "Game/PWorld/Team/PWorldTeamMgr",                  false,
    "PVPTeamMgr",           "Role",         2000,       "Game/PVP/Team/PVPTeamMgr",                  false,
    "PWorldEntMgr",    "Role",         2000,       "Game/PWorld/Entrance/PWorldEntMgr",                  false,
    "PWorldEntourageMgr",    "Role",         2000,       "Game/PWorld/Entrance/Entourage/PWorldEntourageMgr",                  false,
    "PWorldEntourageTeamMgr",        "Role",         2000,       "Game/PWorld/Team/PWorldEntourageTeamMgr",                  false,
    "MapAreaMgr",        	  "Game",         2000,       "Game/PWorld/MapAreaMgr",                        		false,
    "MapAreaImageMgr",      "Game",         2000,       "Game/PWorld/MapAreaImageMgr",                        	false,
    "MapEditDataMgr",       "Game",         2000,       "Game/PWorld/MapEditDataMgr",                        	false,
    "MapGimmickFishAreaMgr",  "Game",       2000,       "Game/PWorld/MapGimmickFishAreaMgr",                    false,
    "PWorldStageMgr",       "Game",         2000,       "Game/PWorld/Stage/PWorldStageMgr",                     false,
    "PWorldVoteMgr",        "Role",         2000,       "Game/PWorld/Vote/PWorldVoteMgr",                       			false,
    "AutoPathMoveMgr",      "Role",         2000,       "Game/PWorld/AutoPathMove/AutoPathMoveMgr",             false,
    "NavigationPathMgr",    "Role",         2000,       "Game/PWorld/Navigation/NavigationPathMgr",             false,
    "HUDMgr",         		"Role",         2000,       "Game/HUD/HUDMgr",                        				false,
    "TeamMgr",         		"Role",         2000,       "Game/Team/TeamMgr",                        			false,
    "TeamVoiceMgr",       "Role",         2000,       "Game/Team/TeamVoiceMgr",                        			false,
    "TeamRecruitMgr",       "Role",         2000,       "Game/TeamRecruit/TeamRecruitMgr",                        	    false,
    "TargetMgr",         	"Role",         2000,       "Game/Target/TargetMgr",                        		false,
    "GMMgr",         		"Game",         2000,       "Game/GM/GMMgr",                        				false,
    "ChatMgr",         		"Role",         2000,       "Game/Chat/ChatMgr",                        			false,
    "MapMgr",         		"Role",         2000,       "Game/Map/MapMgr",                        			    false,
    "WorldMapMgr",         	"Role",         2000,       "Game/Map/WorldMapMgr",                        			false,
    "MapMarkerMgr",         "Role",         2000,       "Game/Map/MapMarkerMgr",                        		false,
    "MapMarkerMsgMgr",       "Role",         2000,      "Game/Map/MapMarkerMsgMgr",                        		false,
    "EasyTraceMapMgr",         		"Role",         2000,       "Game/Map/EasyTraceMapMgr",                        			    false,
    --监听了CS_CMD_LOGIN，所以现在需要是Game
    "SkillLogicMgr",        "Game",         2000,       "Game/Skill/SkillLogicMgr",                        		false,

    "CounterMgr",         	"Role",         2000,       "Game/Counter/CounterMgr",                        		false,
    "InputMgr",         	"Game",         2000,       "Game/Input/InputMgr",                        			false,
    -- "BuglyMgr",         	"Game",         2000,       "Game/GCloud/Bugly/BuglyMgr",                        	false,
    "ReviveMgr",         	"Game",         2000,       "Game/PWorld/Death/ReviveMgr",                        	false,
    "UIMoveMgr",         	"Game",         2000,       "UI/UIMoveMgr",                        					false,
    "NpcMgr",         		"Game",         2000,       "Game/Npc/NpcMgr",                        				false,
    "MagicCardMgr",         "Role",         2000,       "Game/MagicCard/MagicCardMgr",                        	false,
    "MagicCardTourneyMgr",  "Role",         2000,       "Game/MagicCardTourney/MagicCardTourneyMgr",            false,
    "MagicCardCollectionMgr", "Role",       2000,       "Game/MagicCardCollection/MagicCardCollectionMgr",    	false,
    "MysterMerchantMgr",     "Role",        2000,       "Game/MysterMerchant/MysterMerchantMgr",                false,
    "DepartOfLightMgr",     "Role",         2000,       "Game/Departure/DepartOfLightMgr",                  false,
    "SpeechBubbleMgr",      "Game",         2000,       "Game/NPC/SpeechBubbleMgr",                        		false,
    "ScoreMgr",         	"Role",         2000,       "Game/Score/ScoreMgr",                        			false,
    "ProfMgr",         		"Role",         2000,       "Game/Profession/ProfMgr",                        		false,
    "CollectionMgr",        "Role",         2000,       "Game/Gather/CollectionMgr",                       		false,
    "GatherMgr",            "Role",         2000,       "Game/Gather/GatherMgr",                        		false,
    "SelectMonsterMgr",     "Level",        2000,       "Game/Interactive/SelectMonsterMgr",               		false,
    "InteractiveMgr",       "Role",         2000,       "Game/Interactive/InteractiveMgr",                		false,
    "NpcDialogMgr",         "Game",         2000,       "Game/NPC/NpcDialogMgr",                        		false,
    "BagMgr",         	    "Role",         2000,       "Game/Bag/BagMgr",                        	            false,
    "AetheryteticketMgr",   "Role",         2000,       "Game/Aetheryteticket/AetheryteticketMgr",              false,

    "RollMgr",         	    "Role",         2000,       "Game/Roll/RollMgr",                        	            false,
     --"BackpackMgr",         	"Game",         2000,       "Game/Backpack/BackpackMgr",                        	false,
    "DepotMgr",         	"Role",         2000,       "Game/Depot/DepotMgr",                        	        false,
    "PWorldWarningMgr",    	"Game",         2000,       "Game/PWorld/Warning/PWorldWarningMgr",                	false,
    "QuestMgr",             "Role",         2000,       "Game/Quest/QuestMgr",                        		      false,
    "QuestTrackMgr",        "Role",         2000,       "Game/Quest/QuestTrackMgr",                        		  false,
    "QuestFaultTolerantMgr","Role",         2000,       "Game/Quest/QuestFaultTolerantMgr",                     false,
    "QuestCondMgr",         "Role",         2000,       "Game/Quest/QuestCondMgr",                        		  false,
    "StoryMgr",             "Role",         2000,       "Game/Story/StoryMgr",                                  false,
    "SeqDynParamsMgr",      "Role",         2000,       "Game/Story/SeqDynParamsMgr",                           false,
    "StorySubLevelLoader",  "Role",         2000,       "Game/Story/StorySubLevelLoader",                       false,
    "FriendMgr",           "Role",          2000,       "Game/Social/Friend/FriendMgr",                                false,
    "LinkShellMgr",         "Role",         2000,       "Game/Social/LinkShell/LinkShellMgr",                               false,
    "SummonMgr",            "Game",         2000,       "Game/Summon/SummonMgr",                                false,
    "AdventureMgr",        "Game",          2000,       "Game/Adventure/AdventureMgr",                         false,
    "FateMgr",              "Role",         2000,        "Game/Fate/FateMgr",                                    false,
    "LuaCameraMgr",         "Game",         2000,       "Game/Camera/LuaCameraMgr",                             false,
    "LegendaryWeaponMgr",   "Game",         2000,       "Game/LegendaryWeapon/LegendaryWeaponMgr",              false,
    "PerformanceActionMgr", "Game",         2000,       "Game/PWorld/AIPerformance/PerformanceActionMgr",       false,
    "SelectTargetMgr",      "Role",         2000,       "Game/Skill/SelectTarget/SelectTargetMgr",              false,
    "SkillSeriesMgr",       "Role",         2000,       "Game/Skill/SkillSeries/SkillSeriesMgr",                false,
    "SkillStorageMgr",      "Role",         2000,       "Game/Skill/SkillStorage/SkillStorageMgr",              false,
    "SwitchTarget",         "Role",         2000,       "Game/Skill/SelectTarget/SwitchTarget",                 false,
    "SkillPreInputMgr",     "Role",         2000,       "Game/Skill/SkillPreInput/SkillPreInputMgr",            false,
    "CombatMgr",         	"Role",         2000,       "Game/Combat/CombatMgr",                        		false,
    "SkillCDMgr",         	"Role",         2000,       "Game/Skill/SkillCD/SkillCDMgr",                        false,
    "MainProSkillMgr",      "Account",      2000,       "Game/Main/ProSkill/MainProSkillMgr",                   false,
    "SkillBuffMgr",         "Role",         2000,       "Game/Skill/SkillBuffMgr",                        		false,
    "SkillSingEffectMgr",   "Role",         2000,       "Game/Skill/SkillSingEffectMgr",                        false,
    "SkillActionMgr",       "Role",         2000,       "Game/Skill/SkillAction/SkillActionMgr",                false,
    "SkillObjectMgr",       "Role",         2000,       "Game/Skill/SkillAction/SkillObjectMgr",                false,
    "SkillSystemMgr",       "Role",         2000,       "Game/Skill/SkillSystem/SkillSystemMgr",                false,
    "SkillTipsMgr",         "Role",         2000,       "Game/Skill/SkillTipsMgr",                              false,
    "SkillCustomMgr",       "Role",         2000,       "Game/Skill/SkillCustomMgr",                            false,
    "LootMgr",         	    "Role",         2000,       "Game/Loot/LootMgr",                        			false,
    "FishMgr",              "Role",         2000,       "Game/Fish/FishMgr",                                    false,
    "EmotionMgr",           "Role",        2000,       "Game/Emotion/EmotionMgr",                              false,
    "LifeSkillBuffMgr",     "Role",         2000,       "Game/Skill/LifeSkillBuffMgr",                          false,
    "RoleInfoMgr",          "Game",         2000,       "Game/Role/RoleInfoMgr",                                false,
    "WeatherMgr",           "Game",         2000,       "Game/Weather/WeatherMgr",                              false,
    "LoginMapMgr",         	"Game",         2000,       "Game/LoginRole/LoginMapMgr",                            false,
    "MiniCactpotMgr",       "Role",         2000,       "Game/MiniCactpot/MiniCactpotMgr",                      false,
    "FieldTestMgr",        "Level",         2000,       "Game/Test/FieldTest/FieldTestMgr",                  false,
    "SingBarMgr",          "Level",         2000,       "Game/Interactive/SingBar/SingBarMgr",                  false,
    "EquipmentMgr",         "Role",         2000,       "Game/Equipment/EquipmentMgr",                          false,
    "ClientVisionMgr", 	    "Role",         2000,       "Game/Actor/ClientVisionMgr",              		    	false,
    "SkillLimitMgr",        "Role",         2000,       "Game/Skill/SkillLimit/SkillLimitMgr",                  false,
    "ClientSetupMgr",      "Role",         2000,       "Game/ClientSetup/ClientSetupMgr",                    false,
    "ClientReportMgr",      "Role",         2000,       "Game/ClientSetup/ClientReportMgr",                    false,
    "AnimMgr",              "Game",         2000,       "Game/Anim/AnimMgr",                                   false,
    "NaviDecalMgr",         "Role",         2000,       "Game/Navi/NaviDecalMgr",                               false,
    "BuoyMgr",              "Level",         2000,       "Game/HUD/BuoyMgr",                                     false,
    "CrafterMgr",           "Role",         2000,       "Game/Crafter/CrafterMgr",                             false,
    -- "AlchemistMgr",         "Role",         2000,       "Game/Crafter/Alchemist/AlchemistMgr",                   false,
    "CrafterSkillCheckMgr", "Role",         2000,       "Game/Crafter/CrafterSkillCheckMgr",                      false,

    "ClickFeedbackMgr",     "Game",           2000,       "Game/Input/ClickFeedbackMgr",                         false,
    "MountMgr",             "Role",           2000,       "Game/Mount/MountMgr",                                  false,
    "FashionDecoMgr",             "Role",           2000,       "Game/FashionDeco/FashionDecoMgr",                                  false,
    "OnlineStatusMgr",      "Role",           2000,       "Game/OnlineStatus/OnlineStatusMgr",                    false,
    "SettingsMgr",          "Role",           2500,       "Game/Settings/SettingsMgr",                            false,
    "VoiceMgr",             "Role",           1900,       "Game/Voice/VoiceMgr",                                false,

    "BoardMgr",             "Role",           2000,       "Game/MessageBoard/BoardMgr",                           false,
    "RechargingMgr",      "Role",           2000,       "Game/Recharging/RechargingMgr",                    false,
    "SDKMgr",               "Game",           2000,       "Game/SDK/SDKMgr",                                  false,
    "PersonInfoMgr",        "Role",         2000,       "Game/PersonInfo/PersonInfoMgr",                          false,
    "PersonPortraitHeadMgr",    "Role",         2000,       "Game/PersonPortraitHead/PersonPortraitHeadMgr",                   false,
    "PersonPortraitMgr",    "Role",         2000,       "Game/PersonPortrait/PersonPortraitMgr",                   false,
    "AvatarConfigMgr",      "Game",         2500,       "Game/Actor/Avatar/AvatarConfigMgr",                      false,
    "SidebarMgr",           "Role",         2000,       "Game/Sidebar/SidebarMgr",                              false,
    "LeftSidebarMgr",       "Role",         2000,       "Game/Sidebar/LeftSidebarMgr",                          false,
    "SidePopUpMgr",           "Role",         2000,       "Game/SidePopUp/SidePopUpMgr",                              false,
    "JudgeSearchMgr",       "Role",         2000,       "Game/JudgeSearch/JudgeSearchMgr",                      false,
    "CameraSettingsMgr",          "Role",         2000,       "Game/CameraSettings/CameraSettingsMgr",                            false,
    "RideShootingMgr",      "Role",           2000,       "Game/RideShooting/RideShootingMgr",                  false,
    "FogMgr",               "Role",           2000,       "Game/Fog/FogMgr",                                    false,
    "MusicPerformanceMgr",  "Level",        2000,       "Game/MusicPerformance/MusicPerformanceMgr",            true,
    "MarketMgr",            "Role",         2000,       "Game/Market/MarketMgr",                                false,
    "AudioPlayerTypeMgr",   "Game",         2000,       "Audio/AudioPlayerTypeMgr",                             false,
    "ShopMgr",     "Role",           2000,       "Game/Shop/ShopMgr",                         false,
    "CompanionMgr",          "Role",         2000,       "Game/Companion/CompanionMgr",                            false,
    "PreviewMgr",          "Role",         2000,       "Game/Preview/PreviewMgr",                            false,
    "CommonModelToImageMgr", "Game",         2000,       "Game/Common/ModelImage/CommonModelToImageMgr",           false,
    "JumboCactpotMgr",        "Role",         2000,       "Game/JumboCactpot/JumboCactpotMgr",                      false,
    "JumboCactpotDynaMgr",        "Role",         2000,       "Game/JumboCactpot/JumboCactpotDynaMgr",                      false,
    "JumboCactpotLottoryCeremonyMgr",        "Role",         2000,       "Game/JumboCactpot/JumboCactpotLottoryCeremonyMgr",                      false,
    "WorldExploraMgr",        "Role",         2000,       "Game/WorldExplora/WorldExploraMgr",                      false,

    
    "ModuleOpenMgr",          "Role",         2000,       "Game/ModuleOpen/ModuleOpenMgr",                          false,
    "NewTutorialMgr",         "Role",         2000,       "Game/Tutorial/NewTutorialMgr",                              false,
    "TutorialGuideMgr",       "Role",         2000,       "Game/Tutorial/TutorialGuideMgr",                              false,
    "MentorMgr",              "Role",         2000,       "Game/Mentor/MentorMgr",                                  false,
    "NewbieMgr",              "Role",         2000,       "Game/Newbie/NewbieMgr",                                  false,
    "ReturneeMgr",            "Role",         2000,       "Game/Returnee/ReturneeMgr",                              false,
    "MailMgr",                "Role",         2000,       "Game/Mail/MailMgr",                                      false,
    "AreaMailMgr",            "Role",         2000,       "Game/AreaMail/AreaMailMgr",                              false,
    "StoreMgr",               "Role",         2000,       "Game/Store/StoreMgr",                                    false,
    "TitleMgr",               "Role",         2000,       "Game/Title/TitleMgr",                                    false,
    "MusicPlayerMgr",         "Role",         2000,       "Game/MusicPlayer/MusicPlayerMgr",                        false,
    "MonthCardMgr",           "Role",         2000,       "Game/MonthCard/MonthCardMgr",                            false,
    "BattlePassMgr",          "Role",         2000,       "Game/BattlePass/BattlePassMgr",                          false,
    "BattlePassShowModelMgr",          "Role",         2000,       "Game/BattlePass/BattlePassShowModelMgr",                          false,
    "LeveQuestMgr",           "Role",         2000,       "Game/LeveQuest/LeveQuestMgr",                            false,
    "WardrobeMgr",           "Role",         2000,       "Game/Wardrobe/WardrobeMgr",                            false,
    "AchievementMgr",         "Role",         2000,       "Game/Achievement/AchievementMgr",                        false,
    "BuddyMgr",               "Role",         2000,       "Game/Buddy/BuddyMgr",                                    false,
    "GatheringLogMgr",              "Role",         2000,       "Game/GatheringLog/GatheringLogMgr",                                   false,
    "FishNotesMgr",      "Role",           2000,       "Game/FishNotes/FishNotesMgr",                    false,
    "CollectablesMgr",     "Role",         2000,       "Game/Collectables/CollectablesMgr",                     false,
    "ArmyMgr",     "Role",           2000,       "Game/Army/ArmyMgr",                         false,
    "OpsNewbieStrategyMgr",          "Role",         2000,         "Game/Ops/OpsNewbieStrategy/OpsNewbieStrategyMgr",                           false,

    "GoldSauserMainPanelMgr",     "Role",           2000,       "Game/GoldSauserMainPanel/GoldSauserMainPanelMgr",                         false,

    --"GlamoursMgr",     "Role",           2000,       "Game/Glamours/GlamoursMgr",                         false,
    "AetherCurrentsMgr",                "Role",         2000,           "Game/AetherCurrent/AetherCurrentsMgr",                     false,
    "GoldSauserMgr",                    "Role",         2000,           "Game/Gate/GoldSauserMgr",                                  false,
    "GoldSauserCeremonyMgr",                    "Role",         2000,           "Game/Gate/GoldSauserCeremonyMgr",                                  false,

    "GoldSauserLeapOfFaithMgr",         "Role",         2000,           "Game/Gate/GoldSauserLeapOfFaithMgr",                       false,
    "GoldSaucerMiniGameMgr",            "Role",         2000,           "Game/GoldSaucerMiniGame/GoldSaucerMiniGameMgr",            false,
    "GoldSaucerBlessingMgr",            "Role",         2000,           "Game/GoldSaucerMiniGame/MiniGameBless/GoldSaucerBlessingMgr",            false,
    "GoldSauserActivityMgr",            "Role",         2000,           "Game/Gate/GoldSauserActivityMgr",                          false,
    "CraftingLogMgr",           "Role",         2000,       "Game/CraftingLog/CraftingLogMgr",                    false,
    "ChocoboRaceMgr",           "Role",         2000,       "Game/Chocobo/Race/ChocoboRaceMgr",                   true,
    "ChocoboMgr",               "Role",         2000,       "Game/Chocobo/Life/ChocoboMgr",                       false,
    "ChocoboShowModelMgr",      "Role",         2000,       "Game/Chocobo/Life/ChocoboShowModelMgr",              false,
    "ChocoboCodexArmorMgr",     "Role",         2000,       "Game/Chocobo/Codex/ChocoboCodexArmorMgr",            false,
    "ChocoboTransportMgr",    "Role",         2000,       "Game/Chocobo/Transport/ChocoboTransportMgr",           false,
    "TreasureHuntMgr",      "Game",           2000,       "Game/TreasureHunt/TreasureHuntMgr",                    false,
    "TreasuryMgr",          "Game",           2000,       "Game/TreasureHunt/TreasuryMgr",                    false,
    "AdventureRecommendTaskMgr",      "Role",           2000,       "Game/Adventure/AdventureRecommendTaskMgr",                    false,
    "AdventureCareerMgr",      "Game",           2000,       "Game/Adventure/AdventureCareerMgr",                    false,
    "OpsActivityMgr",          "Role",         2000,         "Game/Ops/OpsActivityMgr",                           false,
    "OpsActivityFirstChargeMgr",          "Role",         2000,         "Game/Ops/OpsActivityFirstChargeMgr",                           false,
    "OpsSeasonActivityMgr",          "Role",         2000,         "Game/Ops/OpsSeasonActivityMgr",                           false,
    --endregion

    --region FashionEvaluation
    "FashionEvaluationMgr",      "Role",           2000,       "Game/FashionEvaluation/FashionEvaluationMgr",                    false,
    --endregion
    "HaircutMgr",             "Role",           2000,       "Game/Haircut/HaircutMgr",                        false,
    "SavageRankMgr",  "Role", 2000,   "Game/SavageRank/SavageRankMgr",    false,

    --region Photo
    "PhotoMgr",      "Game",           2000,       "Game/Photo/PhotoMgr",                    false,
    --endregion Photo
    "TravelLogMgr",           "Role",           2000,       "Game/TravelLog/TravelLogMgr",                    false,
    "FootPrintMgr",           "Role",           2000,       "Game/FootPrint/FootPrintMgr",                    false,
    "DiscoverNoteMgr",           "Role",           2000,       "Game/SightSeeingLog/DiscoverNoteMgr",                    false,
    "RedDotMgr",     "Role",           2000,       "Game/CommonRedDot/RedDotMgr",                         false,
    "LightMgr",               "Game",           2000,       "Game/Light/LightMgr",                            false,
    "SignsMgr",               "Game",           2000,       "Game/Signs/SignsMgr",                            false,
    "TeachingMgr",         	  "Game",           2000,       "Game/PWorld/Teaching/TeachingMgr",                     false,
    "MirrorEffectMgr",         	  "Game",           2000,       "Game/Effect/MirrorEffectMgr",                     false,
    "LoadingMgr",         	  "Game",           2000,       "Game/Loading/LoadingMgr",                        false,
    "VisionMeshMgr",         	  "Role",           2000,       "Game/Actor/VisionMeshMgr",                        false,
    "WildBoxMoundMgr",         	  "Role",           2000,       "Game/WildBoxMound/WildBoxMoundMgr",                        false,
    "LevelRecordMgr",         	  "Game",           2000,       "Game/Record/LevelRecordMgr",                        false,
    "UIAsyncTaskMgr",           "Game",         5000,           "UI/UITask/UIAsyncTaskMgr",                                true,
    "CompanySealMgr",         	  "Role",           2000,       "Game/CompanySeal/CompanySealMgr",                        false,
    "BonusStateMgr",         	  "Role",           2000,       "Game/BonusState/BonusStateMgr",                        false,
    --priority = 1900 需要在埋点的Mgr之前初始化
    "TouringBandMgr",             "Role",           1900,       "Game/TouringBand/TouringBandMgr",                      false,
    "BandTimelineMgr",            "Role",           2000,       "Game/TouringBand/BandTimelineExtension/BandTimelineMgr",   true,
    --Hotel
    "HotelMgr",                 "Game",         2000,       "Game/Hotel/HotelMgr",                          false,
    "AnnouncementMgr",            "Role",         2000,       "Game/Announcement/AnnouncementMgr",                   false,
    "MURSurveyMgr",       "Role",         2000,       "Game/MURSurvey/MURSurveyMgr",                		false,
    "UILevelMgr",       "Game",         2000,       "Game/Common/Render2D/Level/UILevelMgr",                		false,
    "PuzzleMgr",        "Role",         2000,       "Game/NewBieGame/Puzzle/PuzzleMgr", false,
    "TipsQueueMgr",          "Role",         2000,       "Game/TipsQueue/TipsQueueMgr",                          false,
    "ExclusiveBattleQuestMgr",  "Role", 2000,   "Game/ExclusiveBattleQuest/ExclusiveBattleQuestMgr",    false,
    "TreasureChestMgr",  			"Role", 		2000,   	"Game/TreasureChest/TreasureChestMgr",   		false,
    "ReportMgr",          "Role",         2000,       "Game/Report/ReportMgr",                          false,
    "MajorTriggerSkillMgr",   "Role",         2000,       "Game/Skill/MajorTriggerSkillMgr",                        false,
    "PVPColosseumMgr",  "Role",        2000,       "Game/PVP/Colosseum/PVPColosseumMgr",            true,
    "PVPInfoMgr",  "Role", 2000,   "Game/PVP/PVPInfoMgr",    false,
    "ShareMgr",         	"Game",         2000,       "Game/Share/ShareMgr",                        			false,
    "PandoraMgr",       "Role",         2000,       "Game/Pandora/PandoraMgr",                		false,
    "WolvesDenPierMgr",  "Role", 2000,   "Game/PVP/WolvesDenPierMgr",    false,
    "MeetTradeMgr",      "Role",         2000,       "Game/MeetTrade/MeetTradeMgr",                		false,
    "SkillGuideMgr",      "Role",         2000,       "Game/Skill/SkillGuide/SkillGuideMgr",                		false,
    "LookAtMgr",      "Game",           2000,       "Game/Actor/LookAt/LookAtMgr",                    false,
    "BusinessUIMgr",         	"Game",         1700,       "UI/BusinessUIMgr",     false,
    "PromoteLevelUpMgr",   "Game",         2000,       "Game/PromoteLevelUp/PromoteLevelUpMgr",              false,
    "RangeCheckTriggerMgr",       "Role",         2000,       "Game/RangeCheckTrigger/RangeCheckTriggerMgr",   false,
    "DeepLinkMgr",       "Game",         2000,       "Game/DeepLink/DeepLinkMgr",   false,
    "UpgradeMgr",       "Role",         2000,       "Game/Upgrade/UpgradeMgr",   false,
    "GroupMgr",       "Game",         2000,       "Game/Group/GroupMgr",   false,
    "IOS26ResDownloadMgr",       "Game",         2000,       "Game/LoginNew/Mgr/IOS26ResDownloadMgr",                     false,
    "PowerSavingMgr",       "Role",         2000,       "Game/Settings/PowerSavingMgr",                         false,
    "OpsGameplayMgr",     "Game",         2000,       "Game/OpsGameplay/OpsGameplayMgr",   false,
}

return #GameMgrConfig, GameMgrConfig
