---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by richyczhou.
--- DateTime: 2024/12/27 16:34
---
local GCloudDefine = {

}

GCloudDefine.SpeechLanguageType = {
    SPEECH_LANGUAGE_ZH = 0,     -- Chinese
    SPEECH_LANGUAGE_EN = 1,     -- English
    SPEECH_LANGUAGE_JA = 2,     -- Japanese
    SPEECH_LANGUAGE_KO = 3,     -- Korean
    SPEECH_LANGUAGE_DE = 4,     -- German
    SPEECH_LANGUAGE_FR = 5,     -- French
}

return GCloudDefine