---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2024/2/19 10:54
---

local LuaClass = require("Core/LuaClass")
local UIViewModel = require("UI/UIViewModel")
local UIUtil = require("Utils/UIUtil")
local ItemUtil = require("Utils/ItemUtil")

---@class MagicCardTourneyRewardItemVM : UIViewModel
local MagicCardTourneyRewardItemVM = LuaClass(UIViewModel)

---Ctor
function MagicCardTourneyRewardItemVM:Ctor()
    self.QuaImg = ""
    self.Icon = ""
    self.FuncImg = ""
    self.TextNum = ""
    self.HasGot = false
    self.ShowFunc = false
    self.ShowTipDaily = false
    self.ShowTipFirst = false
    self.IsMask = false
    self.TextDes = ""
    self.IsShowTextNum = false
    self.ID = 0
    self.IconChooseVisible = false
    self.HideItemLevel = true
    self.NumVisible = false
end

function MagicCardTourneyRewardItemVM:UpdateVM(Value)
    self.ID = Value.ResID
    --self.TextNum = 1-- tostring(Data.Num)
    if self.ID == nil then
        return
    end
    self.Icon = UIUtil.GetIconPath(ItemUtil.GetItemIcon(self.ID)) or ""
    self.QuaImg = ItemUtil.GetItemColorIcon(self.ID) or ""
end

function MagicCardTourneyRewardItemVM:IsEqualVM(Value)
    return Value.ResID == self.ID
end

function MagicCardTourneyRewardItemVM:GetKey()
    return self.ID
end

return MagicCardTourneyRewardItemVM