---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2023/11/1 10:03
---

local LuaClass = require("Core/LuaClass")
local UIViewModel = require("UI/UIViewModel")
local ColorDefine = require("Define/ColorDefine")

---@class ChocoboNameVM : UIViewModel
local ChocoboNameVM = LuaClass(UIViewModel)

---Ctor
function ChocoboNameVM:Ctor()
    self.Selected = false
    self.TextWord = ""
    self.TextWordColor = ColorDefine.ListSelectedColor.Normal
    self.ID = 0
end

function ChocoboNameVM:UpdateVM(Value)
    if Value == nil then return end
    self.ID = Value.ID
    self.TextWord = Value.Name
end

function ChocoboNameVM:SetSelect(Value)
    self.Selected = Value
    if Value then
        self.TextWordColor = ColorDefine.ListSelectedColor.Selected
    else
        self.TextWordColor = ColorDefine.ListSelectedColor.Normal
    end
end

function ChocoboNameVM:IsEqualVM(Value)
    return false
end

--要返回当前类
return ChocoboNameVM