---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2024/6/11 15:26
---

local LuaClass = require("Core/LuaClass")
local UIViewModel = require("UI/UIViewModel")
local TouringBandCfg = require("TableCfg/TouringBandCfg")
local TouringBandNpcCfg = require("TableCfg/TouringBandNpcCfg")
local TouringBandSongCfg = require("TableCfg/TouringBandSongCfg")
local TouringBandTabItemVM = require("Game/TouringBand/VM/TouringBandTabItemVM")
local TouringBandMemberItemVM = require("Game/TouringBand/VM/TouringBandMemberItemVM")
local TouringBandSongListItemVM = require("Game/TouringBand/VM/TouringBandSongListItemVM")

local TouringBandMgr = nil

---@type TouringBandGuideVM : UIViewModel
---@field BandGuideList table @乐团图鉴列表
local TouringBandGuideVM = LuaClass(UIViewModel)

function TouringBandGuideVM:Ctor()
    TouringBandMgr = _G.TouringBandMgr
    self.BandTabVMList = self:ResetBindableList(self.BandTabVMList, TouringBandTabItemVM)
    self.BandMemberVMList = self:ResetBindableList(self.BandMemberVMList, TouringBandMemberItemVM)
    self.BandSongVMList = self:ResetBindableList(self.BandSongVMList, TouringBandSongListItemVM)
    self.SelectBandID = 0
    self.TextJob = ""
end

function TouringBandGuideVM:Reset()

end

function TouringBandGuideVM:UpdateVM()
    
end

function TouringBandGuideVM:InitBandTabList()
    local AllBandData = TouringBandMgr:GetAllBandData()
    self.BandTabVMList:Clear()

    local function STableSort(a, b)
        local ra = tonumber(a.BandNumber) or 0
        local rb = tonumber(b.BandNumber) or 0
        return ra < rb or (ra == rb and a.BandID < b.BandID)
    end
    self.BandTabVMList:UpdateByValues(AllBandData, STableSort)
end

function TouringBandGuideVM:UpdateSelectBand(BandID)
    local BandCfg = TouringBandCfg:FindCfgByKey(BandID)
    if BandCfg == nil then
        return
    end
    
    self.SelectBandID = BandID
    local PosterVM = TouringBandMgr:GetPosterVM()
    PosterVM:UpdateVM(BandID, true)

    local IsUnLock = TouringBandMgr:IsBandUnLockByID(self.SelectBandID)
    if not IsUnLock then
        return
    end
    
    -- 更新成员
    local MemberData = {}
    for i = 1, #BandCfg.MemberNpcID do
        local MemberCfg = TouringBandNpcCfg:FindCfgByKey(BandCfg.MemberNpcID[i])
        if MemberCfg ~= nil then
            local Temp = {}
            Temp.ID = MemberCfg.ID
            Temp.TextName = MemberCfg.Name or ""
            Temp.HeadIcon = MemberCfg.HeadIcon or ""
            table.insert(MemberData, Temp)
        end
    end
    self.BandMemberVMList:Clear()
    self.BandMemberVMList:UpdateByValues(MemberData)

    local IsSongLock = not TouringBandMgr:IsBandFansByID(self.SelectBandID)
    -- 更新歌曲
    local SingsData = {}
    for i = 1, #BandCfg.SongID do
        local SongCfg = TouringBandSongCfg:FindCfgByKey(BandCfg.SongID[i])
        if SongCfg ~= nil then
            local Temp = {}
            Temp.ID = SongCfg.ID
            Temp.TextSequence = "0" .. i
            Temp.TextName = SongCfg.Name or ""
            Temp.Time = SongCfg.Time or 0
            Temp.IsLock = IsSongLock
            table.insert(SingsData, Temp)
        end
    end
    self.BandSongVMList:Clear()
    self.BandSongVMList:UpdateByValues(SingsData)
end

return TouringBandGuideVM