---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2025/2/12 10:42
---
local LuaClass = require("Core/LuaClass")
local UIViewModel = require("UI/UIViewModel")
local TimeUtil = require("Utils/TimeUtil")
local TimerMgr = require("Timer/TimerMgr")

---@class TouringBandActionBtnVM : UIViewModel
local TouringBandActionBtnVM = LuaClass(UIViewModel)

local ProgressPoint =
{
    [0] = 0,
    [1] = 0.205,
    [2] = 0.41,
    [3] = 0.59,
    [4] = 0.795,
    [5] = 1
}

---Ctor
function TouringBandActionBtnVM:Ctor()
    self.BandID = 0
    self.SkillCDText = ""
    self.NormalCDPercent = 0
    self.bNormalCD = false
    self.ReplaceCDTimer = 0
    self.CDEndTime = 0
    self.CDTime = 0
    self.IsCD = false
    self.IsPlayClickAnim = false
    self.Progress = 0
    self.IsVisible = true
    self.CurActionNum = 0
    self.IsProBarVisible = true
end

function TouringBandActionBtnVM:OnEnd()
    if self.ReplaceCDTimer ~= 0 then
        TimerMgr:CancelTimer(self.ReplaceCDTimer)
        self.ReplaceCDTimer = 0
    end
end

function TouringBandActionBtnVM:UpdateBandID(ID)
    self.BandID = ID
end

function TouringBandActionBtnVM:UpdateBandNum(Num)
    local Max = _G.TouringBandMgr:GetCheeringMaxNum()
    self.CurActionNum = Num
    local Index = math.min(Num, #ProgressPoint)
    self.Progress = ProgressPoint[Index]
    self.IsProBarVisible = Num < Max
end

function TouringBandActionBtnVM:UpdateSkillCD(CDBeginTimeMs)
    if CDBeginTimeMs == nil then return end
    
    local CDTimeMS = _G.TouringBandMgr:GetEmotionCD() * 1000
    local CDEndTime = CDBeginTimeMs + CDTimeMS
    local NowTimeMS = TimeUtil.GetServerLogicTimeMS()
    
    if CDEndTime <= NowTimeMS then
        self:ResetSkillCDState()
        return
    end

    self.IsPlayClickAnim = true
    self.CDTime = CDTimeMS
    self.CDEndTime = CDEndTime
    self.IsCD = true

    if self.ReplaceCDTimer ~= 0 then
        TimerMgr:CancelTimer(self.ReplaceCDTimer)
        self.ReplaceCDTimer = 0
    end
    self.ReplaceCDTimer = TimerMgr:AddTimer(self, self.TickSkillCD, 0, 0.1, 0)
end

function TouringBandActionBtnVM:TickSkillCD()
    local SubNum = self.CDEndTime - TimeUtil.GetServerLogicTimeMS()
    if SubNum > 0 then
        self.bNormalCD = true
        self.SkillCDText = tostring(math.ceil(SubNum / 1000)) 
        self.NormalCDPercent = 1 - (SubNum / self.CDTime)
    else
        TimerMgr:CancelTimer(self.ReplaceCDTimer)
        self.ReplaceCDTimer = 0
        self:ResetSkillCDState()
    end
end

function TouringBandActionBtnVM:ResetSkillCDState()
    self.SkillCDText = ""
    self.NormalCDPercent = 0
    self.bNormalCD = false
    self.IsCD = false
    self.IsPlayClickAnim = false
end

return TouringBandActionBtnVM