---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2025/2/12 16:29
---

local LuaClass = require("Core/LuaClass")
local UIViewModel = require("UI/UIViewModel")
local GroupBonusStateDataCfg = require("TableCfg/GroupBonusStateDataCfg")

---@class TouringBandSupportBuffItemVM : UIViewModel
local TouringBandSupportBuffItemVM = LuaClass(UIViewModel)

---Ctor
function TouringBandSupportBuffItemVM:Ctor()
    self.Icon = ""
    self.Name = ""
    self.Content = ""
end

function TouringBandSupportBuffItemVM:UpdateVM(Data)
    local ID = Data.ID
    local CfgData = GroupBonusStateDataCfg:FindCfgByKey(ID)
    if CfgData == nil then
        return
    end
    
    self.Icon = CfgData.EffectIcon
    self.Name = CfgData.EffectName
    self.Content = CfgData.Desc
end

return TouringBandSupportBuffItemVM