---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by yuhang_lightpaw
--- DateTime: 2025/7/18 16:25
---
local LuaClass = require("Core/LuaClass")
local MgrBase = require("Common/MgrBase")
local EventID = require("Define/EventID")
local ProtoCS = require ("Protocol/ProtoCS")
local ProtoRes = require("Protocol/ProtoRes")
local MsgTipsUtil = require("Utils/MsgTipsUtil")
local HouseLocalDef = require("Game/House/HouseLocalDef")
local GameNetworkMgr = require("Network/GameNetworkMgr")
local ItemCfg = require("TableCfg/ItemCfg")
local HousingFurnitureCfg = require("TableCfg/HousingFurnitureCfg")

local CS_CMD = ProtoCS.CS_CMD
local SUB_MSG_FURNITURE_ID = ProtoCS.CS_SUBMSGID_FURNITURE_INTERACTION

local SharedGroupTimelineState = {
    NONE  = 0x0000, -- 二进制: 0000 0000 0000 0000
    STATE_0  = 0x0001, -- 1 << 0
    STATE_1  = 0x0002, -- 1 << 1
    STATE_2  = 0x0004, -- 1 << 2
    STATE_3  = 0x0008, -- 1 << 3
    STATE_4  = 0x0010, -- 1 << 4
    STATE_5  = 0x0020, -- 1 << 5
    STATE_6  = 0x0040, -- 1 << 6
    STATE_7  = 0x0080, -- 1 << 7
    STATE_8  = 0x0100, -- 1 << 8
    STATE_9  = 0x0200, -- 1 << 9
    STATE_10 = 0x0400, -- 1 << 10
    STATE_11 = 0x0800, -- 1 << 11
    STATE_12 = 0x1000, -- 1 << 12
    STATE_13 = 0x2000, -- 1 << 13
    STATE_14 = 0x4000, -- 1 << 14
    STATE_15 = 0x8000, -- 1 << 15
}

---@class FurnitureInteractionMgr : MgrBase
local FurnitureInteractionMgr = LuaClass(MgrBase)


function FurnitureInteractionMgr:OnInit()
end

function FurnitureInteractionMgr:OnReset()
end

function FurnitureInteractionMgr:OnBegin()

end

function FurnitureInteractionMgr:OnEnd()

end

function FurnitureInteractionMgr:OnShutdown()

end

function FurnitureInteractionMgr:OnRegisterNetMsg()
    self:RegisterGameNetMsg(CS_CMD.CS_CMD_FURNITURE_INTERACTION, SUB_MSG_FURNITURE_ID.CS_SUBMSGID_FURNITURE_INTERACTION_FOOD_EAT, self.RspFurnitureFoodEat)
    --self:RegisterGameNetMsg(CS_CMD.CS_CMD_FURNITURE_INTERACTION, SUB_MSG_FURNITURE_ID.CS_SUBMSGID_FURNITURE_INTERACTION_FOOD_EAT_BC, self.RspFurnitureFoodEatBc)
    self:RegisterGameNetMsg(CS_CMD.CS_CMD_FURNITURE_INTERACTION, SUB_MSG_FURNITURE_ID.CS_SUBMSGID_FURNITURE_INTERACTION_DISPLAY_EFFECTS_BC, self.RspFurnitureDisplayEffectsBc)
    self:RegisterGameNetMsg(CS_CMD.CS_CMD_FURNITURE_INTERACTION, SUB_MSG_FURNITURE_ID.CS_SUBMSGID_FURNITURE_INTERACTION_CHANGE_STATUS_BC, self.RspFurnitureChangeStatusBc)
end

function FurnitureInteractionMgr:OnRegisterGameEvent()
    self:RegisterGameEvent(EventID.FurnitureDataUpdate, self.OnGameEventFurnitureDataUpdate)
end

--region 协议请求
function FurnitureInteractionMgr:ReqFurnitureFoodEat(InFurnitureID)
    --需要先检查下剩余次数，有可能其他人使用过了
    local FurnitureInfo = _G.HousingMgr:GetFurnitureInfo(InFurnitureID)
    if not FurnitureInfo then
        return
    end

    local ResID = FurnitureInfo.Key or 0
    local Cfg = HousingFurnitureCfg:FindCfgByKey(ResID)
    if not Cfg then
        return
    end

    if FurnitureInfo.Attr and FurnitureInfo.Attr.Food then
        local LeftTime = (Cfg.FuncParam[1] or 0) - (FurnitureInfo.Attr.Food.EatedTimes or 0)
        if LeftTime <= 0 then
            local ItemID = Cfg.ItemID
            local Name = ItemCfg:GetItemName(ItemID)
            MsgTipsUtil.ShowTips(string.format(HouseLocalDef.FurnitureInteractionFood.Tips3, Name))
            return
        end
    end
    
    local HouseID = _G.HousingMgr:GetIndoorHouseID()
    if HouseID <= 0 then
        HouseID = _G.HousingMgr.HouseID
    end
    local MsgID = CS_CMD.CS_CMD_FURNITURE_INTERACTION
    local SubMsgID = SUB_MSG_FURNITURE_ID.CS_SUBMSGID_FURNITURE_INTERACTION_FOOD_EAT
    local MsgBody = {}
    MsgBody.SubCmd = SubMsgID
    MsgBody.FootEat = {}
    MsgBody.FootEat.HouseID = HouseID
    MsgBody.FootEat.Region = _G.HousingMgr.Region
    MsgBody.FootEat.FurnitureID = InFurnitureID
    GameNetworkMgr:SendMsg(MsgID, SubMsgID, MsgBody,0, HouseID)
end

function FurnitureInteractionMgr:ReqDisplayEffects(InFurnitureID)
    local HouseID = _G.HousingMgr:GetIndoorHouseID()
    if HouseID <= 0 then
        HouseID = _G.HousingMgr.HouseID
    end
    local MsgID = CS_CMD.CS_CMD_FURNITURE_INTERACTION
    local SubMsgID = SUB_MSG_FURNITURE_ID.CS_SUBMSGID_FURNITURE_INTERACTION_DISPLAY_EFFECTS
    local MsgBody = {}
    MsgBody.SubCmd = SubMsgID
    MsgBody.DisplayEffects = {}
    MsgBody.DisplayEffects.HouseID = HouseID
    MsgBody.DisplayEffects.Region = _G.HousingMgr.Region
    MsgBody.DisplayEffects.FurnitureID = InFurnitureID
    GameNetworkMgr:SendMsg(MsgID, SubMsgID, MsgBody,0, HouseID)
end


function FurnitureInteractionMgr:ReqChangeStatus(InFurnitureID, InStatus)
    local HouseID = _G.HousingMgr:GetIndoorHouseID()
    if HouseID <= 0 then
        HouseID = _G.HousingMgr.HouseID
    end
    local MsgID = CS_CMD.CS_CMD_FURNITURE_INTERACTION
    local SubMsgID = SUB_MSG_FURNITURE_ID.CS_SUBMSGID_FURNITURE_INTERACTION_CHANGE_STATUS
    local MsgBody = {}
    MsgBody.SubCmd = SubMsgID
    MsgBody.ChangeStatus = {}
    MsgBody.ChangeStatus.HouseID = HouseID
    MsgBody.ChangeStatus.Region = _G.HousingMgr.Region
    MsgBody.ChangeStatus.FurnitureID = InFurnitureID
    MsgBody.ChangeStatus.Status = InStatus
    GameNetworkMgr:SendMsg(MsgID, SubMsgID, MsgBody,0, HouseID)
end
--endregion

--region 协议回包
function FurnitureInteractionMgr:RspFurnitureFoodEat(MsgBody)
    if not MsgBody then
        return
    end
    
    local FootEat = MsgBody.FootEat
    if not FootEat then
        return
    end
    
    local FurnitureID = FootEat.FurnitureID
    local EatedTimes = FootEat.EatedTimes
    local FurnitureInfo = _G.HousingMgr:GetFurnitureInfo(FurnitureID)
    if not FurnitureInfo then
        return
    end
    
    local ResID = FurnitureInfo.Key or 0
    local Cfg = HousingFurnitureCfg:FindCfgByKey(ResID)
    if not Cfg then
        return
    end
    
    local ItemID = Cfg.ItemID
    local LeftTime = (Cfg.FuncParam[1] or 0) - EatedTimes
    local Name = ItemCfg:GetItemName(ItemID)

    if LeftTime > 0 then
        MsgTipsUtil.ShowTips(string.format(HouseLocalDef.FurnitureInteractionFood.Tips1, Name))
    elseif LeftTime == 0 then
        MsgTipsUtil.ShowTips(string.format(HouseLocalDef.FurnitureInteractionFood.Tips2, Name))
    else
        MsgTipsUtil.ShowTips(string.format(HouseLocalDef.FurnitureInteractionFood.Tips3, Name))
    end
end

function FurnitureInteractionMgr:OnGameEventFurnitureDataUpdate(MsgBody)
    if not MsgBody then
        return
    end

    local FootEatBc = MsgBody.FootEatBc
    if not FootEatBc then
        return
    end

    local FurnitureID = FootEatBc.FurnitureID
    local FurnitureInfo = _G.HousingMgr:GetFurnitureInfo(FurnitureID)
    local TimelineState = self:GetFurnitureTimelineState(FurnitureInfo)

    local FixIndex = _G.HousingMgr:GetFurnitureObjectIndex(FurnitureID) - 1
    _G.HousingMgr:UpdateFurnitureTimelineState(FixIndex, TimelineState)
end

function FurnitureInteractionMgr:RspFurnitureDisplayEffectsBc(MsgBody)
    if not MsgBody then
        return
    end

    local DisplayEffectsBc = MsgBody.DisplayEffectsBc
    if not DisplayEffectsBc then
        return
    end

    local FixIndex = _G.HousingMgr:GetFurnitureObjectIndex(DisplayEffectsBc.FurnitureID) - 1
    _G.HousingMgr:UpdateFurnitureTimelineState(FixIndex, SharedGroupTimelineState.STATE_1)
end

function FurnitureInteractionMgr:RspFurnitureChangeStatusBc(MsgBody)
    if not MsgBody then
        return
    end

    local ChangeStatusBc = MsgBody.ChangeStatusBc
    if not ChangeStatusBc then
        return
    end

    local FixIndex = _G.HousingMgr:GetFurnitureObjectIndex(ChangeStatusBc.FurnitureID) - 1
    _G.HousingMgr:UpdateFurnitureTimelineState(FixIndex, ChangeStatusBc.Status)
end

--endregion

---家具交互统一入口
function FurnitureInteractionMgr:FurnitureInteractionByEntityID(EntityID)
    local FurnitureInfo = _G.HousingMgr:GetFurnitureInfoByEObyEntityID(EntityID)
    if not FurnitureInfo then
        return
    end

    local ResID = FurnitureInfo.Key or 0
    local Cfg = HousingFurnitureCfg:FindCfgByKey(ResID)
    if not Cfg then
        return
    end

    if Cfg.Function == ProtoRes.HouseFurnitureFunction.HouseFurnitureFunction_Food then --食物
        if FurnitureInfo and FurnitureInfo.Attr and FurnitureInfo.Attr.Food then
            local TotalTimes = 0
            if Cfg and Cfg.FuncParam and Cfg.FuncParam[1] then
                TotalTimes = Cfg.FuncParam[1]
            end
            local EatTimes = FurnitureInfo.Attr.Food.EatedTimes or 0
            local LeftTime = TotalTimes - EatTimes
            self:ShowFurnitureFoodUI(FurnitureInfo.GID, Cfg.ItemID or 0, LeftTime)
        end
    elseif Cfg.Function == ProtoRes.HouseFurnitureFunction.HouseFurnitureFunction_Effects then
        self:ReqDisplayEffects(FurnitureInfo.GID)
    elseif Cfg.Function == ProtoRes.HouseFurnitureFunction.HouseFurnitureFunction_Status then
        local NextStatus = SharedGroupTimelineState.STATE_1
        if FurnitureInfo.Attr and FurnitureInfo.Attr.Status then
            if FurnitureInfo.Attr.Status.CurStatus == SharedGroupTimelineState.STATE_0 then
                NextStatus = SharedGroupTimelineState.STATE_1
            else
                NextStatus = SharedGroupTimelineState.STATE_0
            end
        end
        self:ReqChangeStatus(FurnitureInfo.GID, NextStatus)
    end
end

function FurnitureInteractionMgr:ShowFurnitureFoodUI(GID, InItemID, InLeftTime)
    _G.UIViewMgr:ShowView(_G.UIViewID.HouseThingWinView, {
        ViewType = ProtoRes.HouseFurnitureFunction.HouseFurnitureFunction_Food,
        GID = GID,
        ItemID = InItemID,
        LeftTime = InLeftTime,
    })
end

---获取家具对应的TimelinState
---@param FurnitureInfo table
---@return number
function FurnitureInteractionMgr:GetFurnitureTimelineState(FurnitureInfo)
    if not FurnitureInfo then
        return SharedGroupTimelineState.STATE_0
    end
    
    local ResID = FurnitureInfo.Key or 0
    local Cfg = HousingFurnitureCfg:FindCfgByKey(ResID)
    if not Cfg then
        return SharedGroupTimelineState.STATE_0
    end

    if Cfg.Function == ProtoRes.HouseFurnitureFunction.HouseFurnitureFunction_Food then --食物
        if FurnitureInfo.Attr and FurnitureInfo.Attr.Food then
            local LeftTime = (Cfg.FuncParam[1] or 0) - (FurnitureInfo.Attr.Food.EatedTimes or 0)
            if LeftTime <= 0 then
                return SharedGroupTimelineState.STATE_1
            end
        end
    end

    return SharedGroupTimelineState.STATE_0
end

return FurnitureInteractionMgr