---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by skysong.
--- DateTime: 2025/5/7 17:32
---
local ProtoRes = require("Protocol/ProtoRes")

local SelectHouseLeftBarType =
{
    Placed = 1001, --已放置
    Bag = 1002,
    StoreHouse = 1003,
    DecorateSlot = 1004
}

local HouseInteriorParts =
{
    INTERIOR_CATEGORY_NONE = -1,
    INTERIOR_CATEGORY_WALL = 0,
    INTERIOR_CATEGORY_WIND = 1,
    INTERIOR_CATEGORY_DOOR = 2,
    INTERIOR_CATEGORY_FLOOR = 3,
    INTERIOR_CATEGORY_ILLUMINATION = 4,
    INTERIOR_CATEGORY_MAX = 5,
}

local HouseOptType =
{
    Furniture = 1,
    InteriorTerritory = 2,
    ExteriorTerritory = 3,
    ExteriorBackBag = 4, --外装可选配件放回背包
    ExteriorBackDepot = 5 --外装可选配件放回仓库
}

local HouseExteriorParts =
{
    HOUSE_EXTERIOR_PARTS_NONE = -1,
    HOUSE_EXTERIOR_PARTS_ROOF = 0,
    HOUSE_EXTERIOR_PARTS_WALL = 1,
    HOUSE_EXTERIOR_PARTS_WIND = 2,
    HOUSE_EXTERIOR_PARTS_DOOR = 3,

    HOUSE_EXTERIOR_PARTS_OPT_ROOF = 4,
    HOUSE_EXTERIOR_PARTS_OPT_WALL = 5,
    HOUSE_EXTERIOR_PARTS_OPT_SIGN = 6,
    HOUSE_EXTERIOR_PARTS_FENCE = 7,

    HOUSE_EXTERIOR_PARTS_NUM = 9
}

local HouseSize =
{
    HOUSE_SIZE_S = 0,
    HOUSE_SIZE_M = 1,
    HOUSE_SIZE_L = 2,
}

local ServerFloorCategory =
{
    FLOOR_CATEGORY_NONE = 0,
    FLOOR_CATEGORY_B1 = -1,
    FLOOR_CATEGORY_1F = 1,
    FLOOR_CATEGORY_2F = 2,
}

local FloorCategory =
{
    FLOOR_CATEGORY_NONE = 0,
    FLOOR_CATEGORY_1F = 1,
    FLOOR_CATEGORY_2F = 2,
    FLOOR_CATEGORY_B1 = 3,
    FLOOR_CATEGORY_COMMON = 4,
    FLOOR_CATEGORY_MAX = 5
}

local HouseItemCatagory =
{
    Invalid = 0,
    EXTERIOR_ROOF = 1,
    EXTERIOR_WALL = 2,
    EXTERIOR_WINDOW = 3,
    EXTERIOR_DOOR = 4,
    EXTERIOR_ROOF_OPTION = 5,
    EXTERIOR_WALL_OPTION = 6,
    EXTERIOR_SIGN = 7, --看板
    EXTERIOR_FENCE = 8, --栅栏
    INTERIOR_WALL = 9,
    INTERIOR_FLOOR = 10,
    INTERIOR_LIGHT = 11,
    FURNITURE_SINGLE = 12, --普通家具
    FURNITURE_BASE = 13, --桌台
    FURNITURE_DESKTOP = 14, --桌上
    FURNITURE_WALLHUNG = 15, --挂壁
    FURNITURE_CARPET = 16, --地毯
    FURNITURE_YARD = 17, --庭院
    EXTERIOR_ALLWALL = 100, --一体外墙(端游不存在这个类型)
}

local HouseItemTabCatagory =
{
    FURNITURE_SINGLE_Placed = 1, --普通家具
    FURNITURE_BASE_Placed = 2, --桌台
    FURNITURE_DESKTOP_Placed = 3, --桌上
    FURNITURE_WALLHUNG_Placed = 4, --挂壁
    FURNITURE_CARPET_Placed = 5, --地毯
    FURNITURE_SINGLE_Bag = 6, --普通家具
    FURNITURE_BASE_Bag  = 7, --桌台
    FURNITURE_DESKTOP_Bag  = 8, --桌上
    FURNITURE_WALLHUNG_Bag  = 9, --挂壁
    FURNITURE_CARPET_Bag  = 10, --地毯
    FURNITURE_SINGLE_Depot = 11, --普通家具
    FURNITURE_BASE_Depot  = 12, --桌台
    FURNITURE_DESKTOP_Depot  = 13, --桌上
    FURNITURE_WALLHUNG_Depot  = 14, --挂壁
    FURNITURE_CARPET_Depot  = 15, --地毯
    FURNITURE_YARD_Placed = 16,
    FURNITURE_YARD_Bag = 17,
    FURNITURE_YARD_Depot = 18,
    INTERIOR_WALL_Bag = 19,
    INTERIOR_FLOOR_Bag = 20,
    INTERIOR_LIGHT_Bag = 21,
    INTERIOR_WALL_Depot = 22,
    INTERIOR_FLOOR_Depot = 23,
    INTERIOR_LIGHT_Depot = 24,
    EXTERIOR_WALL_Bag = 25,
    EXTERIOR_ALLWALL_Bag = 26,
    EXTERIOR_ROOF_Bag = 27,
    EXTERIOR_WINDOW_Bag = 28,
    EXTERIOR_DOOR_Bag = 29,
    EXTERIOR_WALL_Depot = 30,
    EXTERIOR_ALLWALL_Depot = 31,
    EXTERIOR_ROOF_Depot = 32,
    EXTERIOR_WINDOW_Depot = 33,
    EXTERIOR_DOOR_Depot = 34,
    EXTERIOR_WALL_OPTION_Bag = 35,
    EXTERIOR_ROOF_OPTION_Bag = 36,
    EXTERIOR_SIGN_Bag = 37, --看板
    EXTERIOR_FENCE_Bag =38, --栅栏
    EXTERIOR_WALL_OPTION_Depot  = 39,
    EXTERIOR_ROOF_OPTION_Depot = 40,
    EXTERIOR_SIGN_Depot  = 41, --看板
    EXTERIOR_FENCE_Depot  = 42, --栅栏
}

--house道具变化类型
local HouseItemUpdateType =
{
    AddDepotItem = 1,
    RemoveDepotItem = 2,
    AddBagItem = 3,
    RemoveBagItem = 4,
    AddDecorSlotItem = 5,
    RemoveDecorSlotItem = 6
}

local HouseModel =
{
    None = 0,
    FurnitureModel = 1, --家具模式
    IndoorTerritoryModel = 2, --内装潢模式
    YardModel = 3, --庭院家具模式
    HouseTerritoryModel = 4, --庭院装潢模式
}

--配件类型
local TerritoryOptType =
{
    Base = 1, --基础配件
    Option = 2 --可选配件
}

--操作类型
local MajorOptType =
{
    Place = 1, --放置物件
    Replace = 2, --替换装潢
}

local PreviewModelDataType =
{
    Placed = 1,
    Bag = 2,
    InternalDepot = 3,
    HouseDepot = 4,
    InternalData = 5,
    ExteriorData = 6
}

--旋转编辑的家具来源
local FurnitureSource =
{
    BagDepot = 1,--背包仓库
    Placed = 2 --场景中已放置的
}

local LayoutEditErrorStatus =
{
    LAYOUTEDIT_ERROR_PLACEMENT = 0,
    LAYOUTEDIT_ERROR_OVERFLOW = 1,
    LAYOUTEDIT_ERROR_MOUNT = 2
}

local eLayoutEditMode =
{
    LAYOUTEDIT_MODE_INVALID = 0,		--!< 無効
    LAYOUTEDIT_MODE_TRANSLATE = 1,		--!< 移動
    LAYOUTEDIT_MODE_ROTATE = 2,			--!< 回転
    LAYOUTEDIT_MODE_REMOVE = 3,			--!< 撤去
    LAYOUTEDIT_MODE_APPEND = 4,			--!< 追加
    LAYOUTEDIT_MODE_STAIN = 5,			--!< 染色
    LAYOUTEDIT_MODE_REMOVESTORAGE = 6,	--!< 倉庫へ撤去
}

local HousingItemCategoryMap = {

    [HouseItemTabCatagory.FURNITURE_SINGLE_Placed] = ProtoRes.HOUSING_ITEM_CATEGORY_TYPE.HOUSING_ITEM_CATEGORY_FURNITURE_SINGLE,
    [HouseItemTabCatagory.FURNITURE_BASE_Placed] = ProtoRes.HOUSING_ITEM_CATEGORY_TYPE.HOUSING_ITEM_CATEGORY_FURNITURE_BASE,
    [HouseItemTabCatagory.FURNITURE_DESKTOP_Placed] = ProtoRes.HOUSING_ITEM_CATEGORY_TYPE.HOUSING_ITEM_CATEGORY_FURNITURE_DESKTOP,
    [HouseItemTabCatagory.FURNITURE_WALLHUNG_Placed] = ProtoRes.HOUSING_ITEM_CATEGORY_TYPE.HOUSING_ITEM_CATEGORY_FURNITURE_WALLHUNG,
    [HouseItemTabCatagory.FURNITURE_CARPET_Placed] = ProtoRes.HOUSING_ITEM_CATEGORY_TYPE.HOUSING_ITEM_CATEGORY_FURNITURE_CARPET,

    [HouseItemTabCatagory.FURNITURE_SINGLE_Bag] = ProtoRes.HOUSING_ITEM_CATEGORY_TYPE.HOUSING_ITEM_CATEGORY_FURNITURE_SINGLE,
    [HouseItemTabCatagory.FURNITURE_BASE_Bag] = ProtoRes.HOUSING_ITEM_CATEGORY_TYPE.HOUSING_ITEM_CATEGORY_FURNITURE_BASE,
    [HouseItemTabCatagory.FURNITURE_DESKTOP_Bag] = ProtoRes.HOUSING_ITEM_CATEGORY_TYPE.HOUSING_ITEM_CATEGORY_FURNITURE_DESKTOP,
    [HouseItemTabCatagory.FURNITURE_WALLHUNG_Bag] = ProtoRes.HOUSING_ITEM_CATEGORY_TYPE.HOUSING_ITEM_CATEGORY_FURNITURE_WALLHUNG,
    [HouseItemTabCatagory.FURNITURE_CARPET_Bag] = ProtoRes.HOUSING_ITEM_CATEGORY_TYPE.HOUSING_ITEM_CATEGORY_FURNITURE_CARPET,

    [HouseItemTabCatagory.FURNITURE_SINGLE_Depot] = ProtoRes.HOUSING_ITEM_CATEGORY_TYPE.HOUSING_ITEM_CATEGORY_FURNITURE_SINGLE,
    [HouseItemTabCatagory.FURNITURE_BASE_Depot] = ProtoRes.HOUSING_ITEM_CATEGORY_TYPE.HOUSING_ITEM_CATEGORY_FURNITURE_BASE,
    [HouseItemTabCatagory.FURNITURE_DESKTOP_Depot] = ProtoRes.HOUSING_ITEM_CATEGORY_TYPE.HOUSING_ITEM_CATEGORY_FURNITURE_DESKTOP,
    [HouseItemTabCatagory.FURNITURE_WALLHUNG_Depot] = ProtoRes.HOUSING_ITEM_CATEGORY_TYPE.HOUSING_ITEM_CATEGORY_FURNITURE_WALLHUNG,
    [HouseItemTabCatagory.FURNITURE_CARPET_Depot] = ProtoRes.HOUSING_ITEM_CATEGORY_TYPE.HOUSING_ITEM_CATEGORY_FURNITURE_CARPET,
}

local HouseCommon =
{
    HouseModel = HouseModel,
    SelectHouseLeftBarType = SelectHouseLeftBarType,
    HouseItemCatagory = HouseItemCatagory,
    HouseSize = HouseSize,
    HouseInteriorParts = HouseInteriorParts,
    HouseExteriorParts = HouseExteriorParts,
    TerritoryOptType = TerritoryOptType,
    HouseItemTabCatagory = HouseItemTabCatagory,
    FloorCategory = FloorCategory,
    MajorOptType = MajorOptType,
    HouseOptType = HouseOptType,
    PreviewModelDataType = PreviewModelDataType,
    HouseItemUpdateType = HouseItemUpdateType,
    ServerFloorCategory = ServerFloorCategory,
    FurnitureSource = FurnitureSource,
    LayoutEditErrorStatus = LayoutEditErrorStatus,
    eLayoutEditMode = eLayoutEditMode,
    HousingItemCategoryMap = HousingItemCategoryMap,
}

return HouseCommon